fesystem: /Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadDatabase.C File Reference
LoadDatabase.C File Reference
#include "Loads/LoadDatabase.h"
#include "Utilities/InputOutputUtility.h"
#include "FESystem/FESystemNumbers.h"
#include "Loads/load.h"
#include "Loads/LoadSet.h"
#include "Loads/LoadCase.h"
#include "Loads/LoadCombination.h"
#include "Loads/LoadDataInfo.h"
Functions
template<>
void LoadDatabase::getLoadCombination< Loads::VolumeLoadDataInfo, Loads::VolumeLoadCombination > (const Loads::VolumeLoadDataInfo &load_info, Loads::VolumeLoadCombination &load_combo)
template<>
void LoadDatabase::getLoadCombination< Loads::SurfaceLoadDataInfo, Loads::SurfaceLoadCombination > (const Loads::SurfaceLoadDataInfo &load_info, Loads::SurfaceLoadCombination &load_combo)
template<>
void LoadDatabase::getLoadCombination< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination > (const Loads::NodalLoadDataInfo &load_info, Loads::NodalLoadCombination &load_combo)
template<>
FESystemUtility::AutoPtrVector
< Loads::NodalLoadCombination > LoadDatabase::getAllLoadCombinations< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination > (const Loads::NodalLoadDataInfo &load_info)
template<>
FESystemUtility::AutoPtrVector
< Loads::DirichletBoundaryConditionCombination > LoadDatabase::getAllLoadCombinations< Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination > (const Loads::DirichletBoundaryConditionDataInfo &load_info)
Function Documentation
template<> FESystemUtility::AutoPtrVector<Loads::DirichletBoundaryConditionCombination> LoadDatabase::getAllLoadCombinations< Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination > (const Loads::DirichletBoundaryConditionDataInfo & load_info)
Definition at line 421 of file LoadDatabase.C.
References Loads::DirichletBoundaryConditionCombination::clear(), Loads::createDirichletBoundaryConditionCombination(), BoundaryConditionLoadSet::getAllLoads(), Loads::LoadDataInfoBase::getLoadCaseID(), Loads::LoadDataInfoBase::getLoadClassEnumID(), LoadCaseBase::getLoadFactorLoadSetPair(), Loads::LoadDataInfoBase::getLoadNameEnumID(), LoadSetBase::getLoadNameEnumID(), and FESystemUtility::AutoPtrVector< T >::reset().
{
  static std::vector<const DirichletBoundaryCondition*> load_vec;
  load_vec.clear();
  static std::vector<std::pair<unsigned int, double> > load_pair;
  load_pair.clear();
  const LoadCaseBase& load_case = this->getLoadCaseFromID(load_info.getLoadCaseID());
  load_case.getLoadFactorLoadSetPair(load_info, load_pair);
  // create a map of load combos for the nodes
  static std::map<unsigned int, std::map<unsigned int,
  Loads::DirichletBoundaryConditionCombination*> > load_combo_map;
  load_combo_map.clear();
  static std::map<unsigned int, std::map<unsigned int,
  Loads::DirichletBoundaryConditionCombination*> >::iterator it;
  static std::map<unsigned int, Loads::DirichletBoundaryConditionCombination*>::iterator dof_it;
  unsigned int n_bcs = 0;
  // iterate over the load pairs, and add the loads to the load vector
  for (unsigned int i=0; i < load_pair.size(); i++)
    {
      const BoundaryConditionLoadSet& load_set =
      dynamic_cast<const BoundaryConditionLoadSet&>(this->getLoadSetFromID(load_pair[i].first));
      // make sure that the loads are of the same kind
      AssertThrow(load_info.getLoadNameEnumID() == load_set.getLoadNameEnumID(), ExcInternalError());
      load_vec.clear();
      // finally, ask the load set to return the load vector
      load_set.getAllLoads(load_vec);
      for (unsigned int j=0; j < load_vec.size(); j++)
        {
          it = load_combo_map.find(load_vec[j]->getNodeID());
          // if the node does not exist in the map, add it
          if (it == load_combo_map.end())
            it = load_combo_map.insert
            (std::map<unsigned int, std::map<unsigned int,
             Loads::DirichletBoundaryConditionCombination*> >::value_type
             (load_vec[j]->getNodeID(),
              std::map<unsigned int, Loads::DirichletBoundaryConditionCombination*>())).first;
          // now, look for the dof number for this boundary condition
          dof_it = it->second.find(load_vec[j]->getDofNumber());
          if (dof_it == it->second.end())
            {
              dof_it = it->second.insert
              (std::map<unsigned int, Loads::DirichletBoundaryConditionCombination*>::value_type
               (load_vec[j]->getDofNumber(), Loads::createDirichletBoundaryConditionCombination
                (load_info.getLoadClassEnumID()).release())).first;
              n_bcs++;
            }
          dof_it->second->addLoad(load_pair[i].second, load_vec[j]);
        }
    }
  // finally, transfer the created load combo pointers to the return vector
  FESystemUtility::AutoPtrVector<Loads::DirichletBoundaryConditionCombination>
  return_load_vec(n_bcs);
  it = load_combo_map.begin();
  unsigned int bc_it = 0;
  for ( ; it != load_combo_map.end(); it++)
    {
      dof_it = it->second.begin();
      for ( ; dof_it != it->second.end(); dof_it++)
        {
          return_load_vec.reset(bc_it, dof_it->second);
          bc_it++;
        }
    }
  load_combo_map.clear();
  return return_load_vec;
}
template<> FESystemUtility::AutoPtrVector<Loads::NodalLoadCombination> LoadDatabase::getAllLoadCombinations< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination > (const Loads::NodalLoadDataInfo & load_info)
Definition at line 355 of file LoadDatabase.C.
References FESystemUtility::AutoPtrVector< T >::clear(), Loads::createNodalLoadCombination(), NodalLoadSet::getAllLoads(), Loads::LoadDataInfoBase::getLoadCaseID(), Loads::LoadDataInfoBase::getLoadClassEnumID(), LoadCaseBase::getLoadFactorLoadSetPair(), Loads::LoadDataInfoBase::getLoadNameEnumID(), LoadSetBase::getLoadNameEnumID(), and FESystemUtility::AutoPtrVector< T >::reset().
{
  static std::vector<const NodalLoad*> load_vec;
  load_vec.clear();
  static std::vector<std::pair<unsigned int, double> > load_pair;
  load_pair.clear();
  const LoadCaseBase& load_case = this->getLoadCaseFromID(load_info.getLoadCaseID());
  load_case.getLoadFactorLoadSetPair(load_info, load_pair);
  // create a map of load combos for the nodes
  static std::map<unsigned int, Loads::NodalLoadCombination*> load_combo_map;
  static std::map<unsigned int, Loads::NodalLoadCombination*>::iterator it;
  load_combo_map.clear();
  // iterate over the load pairs, and add the loads to the load vector
  for (unsigned int i=0; i < load_pair.size(); i++)
    {
      const NodalLoadSet& load_set =
      dynamic_cast<const NodalLoadSet&>(this->getLoadSetFromID(load_pair[i].first));
      // make sure that the loads are of the same kind
      AssertThrow(load_info.getLoadNameEnumID() == load_set.getLoadNameEnumID(), ExcInternalError());
      load_vec.clear();
      // finally, ask the load set to return the load vector
      load_set.getAllLoads(load_vec);
      for (unsigned int j=0; j < load_vec.size(); j++)
        {
          it = load_combo_map.find(load_vec[j]->getNodeID());
          // if the node does not exist in the map, add it
          if (it == load_combo_map.end())
            it = load_combo_map.insert
            (std::map<unsigned int, Loads::NodalLoadCombination*>::value_type
             (load_vec[j]->getNodeID(), Loads::createNodalLoadCombination
              (load_info.getLoadClassEnumID()).release())).first;
          it->second->addLoad(load_pair[i].second, load_vec[j]);
        }
    }
  // finally, transfer the created load combo pointers to the return vector
  FESystemUtility::AutoPtrVector<Loads::NodalLoadCombination> return_load_vec(load_combo_map.size());
  it = load_combo_map.begin();
  for (unsigned int i=0 ; i < load_combo_map.size(); i++)
    {
      return_load_vec.reset(i, it->second);
      it++;
    }
  load_combo_map.clear();
  return return_load_vec;
}
template<> void LoadDatabase::getLoadCombination< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination > (const Loads::NodalLoadDataInfo & load_info, Loads::NodalLoadCombination & load_combo)
Definition at line 315 of file LoadDatabase.C.
References Loads::LoadDataInfoBase::getLoadCaseID(), LoadCaseBase::getLoadFactorLoadSetPair(), Loads::LoadDataInfoBase::getLoadNameEnumID(), LoadSetBase::getLoadNameEnumID(), NodalLoadSet::getLoadsForNode(), and Loads::NodalLoadDataInfo::getNodeID().
{
  load_combo.clear();
  static std::vector<const NodalLoad*> load_vec;
  load_vec.clear();
  static std::vector<std::pair<unsigned int, double> > load_pair;
  load_pair.clear();
  const LoadCaseBase& load_case = this->getLoadCaseFromID(load_info.getLoadCaseID());
  load_case.getLoadFactorLoadSetPair(load_info, load_pair);
  // iterate over the load pairs, and add the loads to the load vector
  for (unsigned int i=0; i < load_pair.size(); i++)
    {
      const NodalLoadSet& load_set =
      dynamic_cast<const NodalLoadSet&>(this->getLoadSetFromID(load_pair[i].first));
      // make sure that the loads are of the same kind
      AssertThrow(load_info.getLoadNameEnumID() == load_set.getLoadNameEnumID(), ExcInternalError());
      load_vec.clear();
      // finally, ask the load set to return the load vector
      load_set.getLoadsForNode(load_info.getNodeID(), load_vec);
      for (unsigned int j=0; j < load_vec.size(); j++)
        load_combo.addLoad(load_pair[i].second, load_vec[j]);
    }
}
template<> void LoadDatabase::getLoadCombination< Loads::SurfaceLoadDataInfo, Loads::SurfaceLoadCombination > (const Loads::SurfaceLoadDataInfo & load_info, Loads::SurfaceLoadCombination & load_combo)
Definition at line 274 of file LoadDatabase.C.
References Loads::ElemLoadDataInfo::getElemID(), Loads::LoadDataInfoBase::getLoadCaseID(), LoadCaseBase::getLoadFactorLoadSetPair(), Loads::LoadDataInfoBase::getLoadNameEnumID(), LoadSetBase::getLoadNameEnumID(), SurfaceLoadSet::getLoadsForElementSide(), and Loads::SurfaceLoadDataInfo::getSurfaceID().
{
  load_combo.clear();
  static std::vector<const SurfaceLoad*> load_vec;
  load_vec.clear();
  static std::vector<std::pair<unsigned int, double> > load_pair;
  load_pair.clear();
  const LoadCaseBase& load_case = this->getLoadCaseFromID(load_info.getLoadCaseID());
  load_case.getLoadFactorLoadSetPair(load_info, load_pair);
  // iterate over the load pairs, and add the loads to the load vector
  for (unsigned int i=0; i < load_pair.size(); i++)
    {
      const SurfaceLoadSet& load_set =
      dynamic_cast<const SurfaceLoadSet&>(this->getLoadSetFromID(load_pair[i].first));
      // make sure that the loads are of the same kind
      AssertThrow(load_info.getLoadNameEnumID() == load_set.getLoadNameEnumID(), ExcInternalError());
      load_vec.clear();
      // finally, ask the load set to return the load vector
      load_set.getLoadsForElementSide(load_info.getElemID(), load_info.getSurfaceID(),
                                      load_vec);
      for (unsigned int j=0; j < load_vec.size(); j++)
        load_combo.addLoad(load_pair[i].second, load_vec[j]);
    }
}
template<> void LoadDatabase::getLoadCombination< Loads::VolumeLoadDataInfo, Loads::VolumeLoadCombination > (const Loads::VolumeLoadDataInfo & load_info, Loads::VolumeLoadCombination & load_combo)
Definition at line 235 of file LoadDatabase.C.
References Loads::ElemLoadDataInfo::getElemID(), Loads::LoadDataInfoBase::getLoadCaseID(), LoadCaseBase::getLoadFactorLoadSetPair(), Loads::LoadDataInfoBase::getLoadNameEnumID(), LoadSetBase::getLoadNameEnumID(), and VolumeLoadSet::getLoadsForElement().
{
  load_combo.clear();
  static std::vector<const VolumeLoad*> load_vec;
  load_vec.clear();
  static std::vector<std::pair<unsigned int, double> > load_pair;
  load_pair.clear();
  const LoadCaseBase& load_case = this->getLoadCaseFromID(load_info.getLoadCaseID());
  load_case.getLoadFactorLoadSetPair(load_info, load_pair);
  // iterate over the load pairs, and add the loads to the load vector
  for (unsigned int i=0; i < load_pair.size(); i++)
    {
      const VolumeLoadSet& load_set =
      dynamic_cast<const VolumeLoadSet&>(this->getLoadSetFromID(load_pair[i].first));
      // make sure that the loads are of the same kind
      AssertThrow(load_info.getLoadNameEnumID() == load_set.getLoadNameEnumID(), ExcInternalError());
      load_vec.clear();
      // finally, ask the load set to return the load vector
      load_set.getLoadsForElement(load_info.getElemID(), load_vec);
      for (unsigned int j=0; j < load_vec.size(); j++)
        load_combo.addLoad(load_pair[i].second, load_vec[j]);
    }
}