fesystem: /Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/PetscTransientSolver.C File Reference
PetscTransientSolver.C File Reference
#include "Solvers/PetscTransientSolver.h"
#include "Solvers/PetscNonlinearSolver.h"
#include "FESystem/FESystemController.h"
#include "Solvers/TransientSolverInfo.h"
#include "Solvers/NonlinearSolverInfo.h"
#include "Solvers/LinearSolverInfo.h"
#include "Utilities/TimeLogs.h"
#include "AnalysisDriver/TransientAnalysisDriver.h"
#include "petsc_vector.h"
#include "petsc_matrix.h"
Functions
PetscErrorCode FESystemNonlinearTransientSolverRHSFunctionEvaluation (TS tsolver, PetscReal time, Vec x, Vec f, void *ctx)
PetscErrorCode FESystemNonlinearTransientSolverRHSJacobianEvaluation (TS tsolver, PetscReal time, Vec x, Mat *A, Mat *B, MatStructure *flag, void *ctx)
PetscErrorCode FESystemTransientSolverMonitor (TS tsolver, PetscInt iter_num, PetscReal time, Vec x, void *ctx)
Function Documentation
PetscErrorCode FESystemNonlinearTransientSolverRHSFunctionEvaluation (TS tsolver, PetscReal time, Vec x, Vec f, void * ctx)
Definition at line 345 of file PetscTransientSolver.C.
References Solver::NonlinearTransientSolverBase::evaluateRHSFunction().
Referenced by Solver::PetscNonlinearTransientSolver::solve().
{
  // unused parameters
  (void) tsolver;
  // get the pointer to the solver, and ask it to calculate the
  // residual at the function value given
  Solver::NonlinearTransientSolverBase *solver =
  static_cast<Solver::NonlinearTransientSolverBase*> (ctx);
  PetscVector<double> sol_vec(x);
  PetscVector<double> res_vec(f);
  solver->evaluateRHSFunction(time, sol_vec, res_vec);
  return 0;
}
PetscErrorCode FESystemNonlinearTransientSolverRHSJacobianEvaluation (TS tsolver, PetscReal time, Vec x, Mat * A, Mat * B, MatStructure * flag, void * ctx)
Definition at line 367 of file PetscTransientSolver.C.
References Solver::NonlinearTransientSolverBase::evaluateRHSJacobian().
Referenced by Solver::PetscNonlinearTransientSolver::solve().
{
  // unused parameter
  (void) tsolver;
  (void) B;
  // get the pointer to the solver, and ask it to calculate the
  // residual at the function value given
  Solver::NonlinearTransientSolverBase *solver =
  static_cast<Solver::NonlinearTransientSolverBase*> (ctx);
  PetscVector<double> sol_vec(x);
  PetscMatrix<double> jac_mat(*A);
  solver->evaluateRHSJacobian(time, sol_vec, jac_mat);
  *flag = SAME_NONZERO_PATTERN;
  return 0;
}
PetscErrorCode FESystemTransientSolverMonitor (TS tsolver, PetscInt iter_num, PetscReal time, Vec x, void * ctx)
Definition at line 391 of file PetscTransientSolver.C.
References Solver::FESystemSolverBase::getAnalysisDriver().
Referenced by Solver::PetscNonlinearTransientSolver::solve().
{
  // unused parameter
  (void) tsolver;
  Solver::NonlinearTransientSolverBase *solver =
    static_cast<Solver::NonlinearTransientSolverBase*> (ctx);
  Driver::TransientAnalysisDriver& driver =
    static_cast<Driver::TransientAnalysisDriver&>(solver->getAnalysisDriver());
  PetscVector<double> sol_vec(x);
  driver.setSolverIterationIncrement(time, iter_num, sol_vec);
  return 0;
}