fesystem: /Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/PetscNonlinearSolver.C File Reference
PetscNonlinearSolver.C File Reference
#include "Solvers/PetscNonlinearSolver.h"
#include "AnalysisDriver/AnalysisDriver.h"
#include "Solvers/LinearSolverInfo.h"
#include "Solvers/NonlinearSolverInfo.h"
#include "Solvers/PetscLinearSolver.h"
#include "Utilities/TimeLogs.h"
#include "Utilities/ParallelUtility.h"
#include "petsc_vector.h"
#include "petsc_matrix.h"
Functions
PetscErrorCode FESystemNonlinearSolverFunctionEvaluation (SNES snes, Vec x, Vec f, void *ctx)
PetscErrorCode FESystemNonlinearSolverJacobianEvaluation (SNES snes, Vec x, Mat *A, Mat *B, MatStructure *flag, void *ctx)
Function Documentation
PetscErrorCode FESystemNonlinearSolverFunctionEvaluation (SNES snes, Vec x, Vec f, void * ctx)
Definition at line 277 of file PetscNonlinearSolver.C.
References Solver::NonlinearSolver::evaluateResidual().
Referenced by Solver::PetscNonlinearSolver::solve().
{
  // unused parameters
  (void) snes;
  // get the pointer to the solver, and ask it to calculate the
  // residual at the function value given
  Solver::NonlinearSolver *solver =
  static_cast<Solver::NonlinearSolver*> (ctx);
  PetscVector<double> sol_vec(x);
  PetscVector<double> res_vec(f);
  solver->evaluateResidual(sol_vec, res_vec);
  return 0;
}
PetscErrorCode FESystemNonlinearSolverJacobianEvaluation (SNES snes, Vec x, Mat * A, Mat * B, MatStructure * flag, void * ctx)
Definition at line 299 of file PetscNonlinearSolver.C.
References Solver::NonlinearSolver::evaluateJacobian().
Referenced by Solver::PetscNonlinearSolver::solve().
{
  // unused parameter
  (void) snes;
  (void) B;
  // get the pointer to the solver, and ask it to calculate the
  // residual at the function value given
  Solver::NonlinearSolver *solver =
  static_cast<Solver::NonlinearSolver*> (ctx);
  PetscVector<double> sol_vec(x);
  PetscMatrix<double> jac_mat(*A);
  solver->evaluateJacobian(sol_vec, jac_mat);
  *flag = SAME_NONZERO_PATTERN;
  return 0;
}