fesystem: Loads::NodalLoadCombination Class Reference
Loads::NodalLoadCombination Class Reference
#include <LoadCombination.h>
Public Member Functions
NodalLoadCombination ()
virtual ~NodalLoadCombination ()
virtual unsigned int nLoads () const
unsigned int getNodeID () const
virtual void addLoad (const double factor, const NodalLoad *load)=0
Protected Attributes
std::set< const NodalLoad * > load_set
Detailed Description
Definition at line 43 of file LoadCombination.h.
Constructor & Destructor Documentation
Loads::NodalLoadCombination::NodalLoadCombination () [inline]
Definition at line 46 of file LoadCombination.h.
                            :
      LoadCombinationBase()
      { }
virtual Loads::NodalLoadCombination::~NodalLoadCombination () [inline, virtual]
Definition at line 50 of file LoadCombination.h.
      { }
Member Function Documentation
virtual void Loads::NodalLoadCombination::addLoad (const double factor, const NodalLoad * load) [pure virtual]
Implemented in Loads::DirichletBoundaryConditionCombination, and Loads::NodalPointLoadCombination.
unsigned int Loads::NodalLoadCombination::getNodeID () const [inline]
Definition at line 63 of file LoadCombination.h.
References load_set, and nLoads().
Referenced by Loads::NodalPointLoadCombination::addLoad(), Loads::DirichletBoundaryConditionCombination::addLoad(), and Discipline::AnalysisDisciplineBase::getElemLoads().
      {
        Assert (this->nLoads() > 0, ExcInternalError());
        return (*this->load_set.begin())->getNodeID();
      }
virtual unsigned int Loads::NodalLoadCombination::nLoads () const [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 58 of file LoadCombination.h.
References load_set.
Referenced by Loads::DirichletBoundaryConditionCombination::addLoad(), Loads::DirichletBoundaryConditionCombination::getDofNumber(), Discipline::AnalysisDisciplineBase::getElemLoads(), Loads::NodalPointLoadCombination::getNDofs(), and getNodeID().
      {
        return this->load_set.size();
      }
Member Data Documentation
std::set<const NodalLoad*> Loads::NodalLoadCombination::load_set [protected]
Definition at line 73 of file LoadCombination.h.
Referenced by Loads::NodalPointLoadCombination::addLoad(), Loads::DirichletBoundaryConditionCombination::addLoad(), Loads::NodalPointLoadCombination::clear(), Loads::DirichletBoundaryConditionCombination::getDofNumber(), Loads::NodalPointLoadCombination::getNDofs(), getNodeID(), and nLoads().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCombination.h