fesystem: Loads::FlightCondition Class Reference
Loads::FlightCondition Class Reference
#include <FlightCondition.h>
Public Member Functions
FlightCondition ()
contructor
FlightCondition (const Loads::FlightCondition &flt_cond)
copy contructor
~FlightCondition ()
destructor
double getDynamicPressure () const
double getMachNumber () const
double getDensity () const
double getSpeedOfSound () const
const Point & getFluidFlowVector () const
void setDynamicPressure (const double dyn_press)
sets the value of the flight dynamic vector
void setMachNumber (const double m_num)
sets the flight mach number
void setDensity (const double dens)
sets the flight density
void setFluidFlowVector (const Point &vec)
sets the fluid flow vector
Protected Attributes
double dynamic_pressure
dynamic pressure
double mach_number
mach number
double density
density
Point fluid_flow_vector
fluid flow vector
Detailed Description
Definition at line 19 of file FlightCondition.h.
Constructor & Destructor Documentation
Loads::FlightCondition::FlightCondition ()
contructor
Definition at line 17 of file FlightCondition.cpp.
                                     :
dynamic_pressure(0.0),
mach_number(0.0),
density(0.0)
{
}
Loads::FlightCondition::FlightCondition (const Loads::FlightCondition & flt_cond)
copy contructor
Definition at line 26 of file FlightCondition.cpp.
                                                                         :
dynamic_pressure(flt_cond.dynamic_pressure),
mach_number(flt_cond.mach_number),
density(flt_cond.density),
fluid_flow_vector(flt_cond.fluid_flow_vector)
{
}
Loads::FlightCondition::~FlightCondition ()
destructor
Definition at line 36 of file FlightCondition.cpp.
{
}
Member Function Documentation
double Loads::FlightCondition::getDensity () const
Returns:
the flight density
Definition at line 59 of file FlightCondition.cpp.
{
  return this->density;
}
double Loads::FlightCondition::getDynamicPressure () const
Returns:
the flight dynamic pressure
Definition at line 44 of file FlightCondition.cpp.
{
  return this->dynamic_pressure;
}
const Point & Loads::FlightCondition::getFluidFlowVector () const
Returns:
the fluid flow vector
Definition at line 75 of file FlightCondition.cpp.
Referenced by Discipline::PistonTheory::getElemQty().
{
  return this->fluid_flow_vector;
}
double Loads::FlightCondition::getMachNumber () const
Returns:
the flight mach number
Definition at line 52 of file FlightCondition.cpp.
Referenced by Discipline::PistonTheory::getElemQty().
{
  return this->mach_number;
}
double Loads::FlightCondition::getSpeedOfSound () const
Returns:
the speed of sound at flight condition
Definition at line 66 of file FlightCondition.cpp.
Referenced by Discipline::PistonTheory::getElemQty().
{
  return (sqrt(2.0 * this->dynamic_pressure / this->density) / this->mach_number);
}
void Loads::FlightCondition::setDensity (const double dens)
sets the flight density
Definition at line 98 of file FlightCondition.cpp.
Referenced by Solution::AeroelasticitySolution::readFromInputStream().
{
  this->density = dens;
}
void Loads::FlightCondition::setDynamicPressure (const double dyn_press)
sets the value of the flight dynamic vector
Definition at line 83 of file FlightCondition.cpp.
Referenced by Solution::AeroelasticitySolution::readFromInputStream().
{
  this->dynamic_pressure = dyn_press;
}
void Loads::FlightCondition::setFluidFlowVector (const Point & vec)
sets the fluid flow vector
Definition at line 105 of file FlightCondition.cpp.
Referenced by Solution::AeroelasticitySolution::readFromInputStream().
{
  this->fluid_flow_vector = vec;
}
void Loads::FlightCondition::setMachNumber (const double m_num)
sets the flight mach number
Definition at line 91 of file FlightCondition.cpp.
Referenced by Solution::AeroelasticitySolution::readFromInputStream().
{
  this->mach_number = m_num;
}
Member Data Documentation
double Loads::FlightCondition::density [protected]
density
Definition at line 69 of file FlightCondition.h.
double Loads::FlightCondition::dynamic_pressure [protected]
dynamic pressure
Definition at line 63 of file FlightCondition.h.
Point Loads::FlightCondition::fluid_flow_vector [protected]
fluid flow vector
Definition at line 72 of file FlightCondition.h.
double Loads::FlightCondition::mach_number [protected]
mach number
Definition at line 66 of file FlightCondition.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/FlightCondition.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/FlightCondition.cpp