fesystem: FESystemNumerics::MatrixBase< T > Class Template Reference
FESystemNumerics::MatrixBase< T > Class Template Reference
#include <MatrixBase.h>
Public Member Functions
MatrixBase ()
constructor
virtual ~MatrixBase ()
virtual unsigned int getMatrixPackage () const =0
virtual void resize (const unsigned int m, const unsigned int n)=0
virtual void zero ()=0
virtual T el (const unsigned int i, const unsigned int j) const =0
virtual void getRow (const unsigned int i, FESystemNumerics::VectorBase< T > &vec)=0
returns the i th row of the matrix in the given vector
virtual void getDiagonal (FESystemNumerics::VectorBase< T > &vec)=0
returns the diagonal of the matrix in the given vector
virtual void shift (const T val)=0
adds val to all diagonal elements of the matrix
virtual void set (const unsigned int i, const unsigned int j, const T val)=0
virtual void set (const std::vector< unsigned int > &i, const std::vector< unsigned int > &j, const T *val)=0
virtual void leftDiagonalScale (const FESystemNumerics::VectorBase< T > &vector)=0
virtual void rightDiagonalScale (const FESystemNumerics::VectorBase< T > &vector)=0
virtual void leftMultiply (const FESystemNumerics::MatrixBase< T > &matrix)=0
virtual void leftMultiplyTranspose (const FESystemNumerics::MatrixBase< T > &matrix)=0
virtual void rightMultiply (const FESystemNumerics::MatrixBase< T > &matrix)=0
virtual void leftMultiplyVector (const FESystemNumerics::VectorBase< T > &vector_in, FESystemNumerics::VectorBase< T > &result)=0
virtual void rightMultiplyVector (const FESystemNumerics::VectorBase< T > &vector_in, FESystemNumerics::VectorBase< T > &result)=0
virtual unsigned int m () const =0
virtual unsigned int n () const =0
void operator= (const FESystemNumerics::MatrixBase< T > &matrix)
virtual void copy (const FESystemNumerics::MatrixBase< T > &matrix)=0
virtual void add (const T val, const FESystemNumerics::MatrixBase< T > &matrix, const bool same_nonzero)=0
virtual void add (const unsigned int i, const unsigned int j, const T val)=0
virtual void add (const std::vector< unsigned int > &i, const std::vector< unsigned int > &j, const T *val)=0
virtual void diagonalAdd (const T val, const FESystemNumerics::VectorBase< T > &diag)=0
virtual void scale (const T factor)=0
virtual void print (std::ostream &output)
Detailed Description
template<typename T>
class FESystemNumerics::MatrixBase< T >
this class provides a base class for different kinds of matrices
Definition at line 17 of file MatrixBase.h.
Constructor & Destructor Documentation
template<typename T > FESystemNumerics::MatrixBase< T >::MatrixBase ()
constructor
Definition at line 200 of file MatrixBase.h.
{}
template<typename T > FESystemNumerics::MatrixBase< T >::~MatrixBase () [virtual]
Destructor. Empty.
Definition at line 206 of file MatrixBase.h.
{}
Member Function Documentation
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::add (const T val, const FESystemNumerics::MatrixBase< T > & matrix, const bool same_nonzero) [pure virtual]
Adds to this matrix
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::add (const unsigned int i, const unsigned int j, const T val) [pure virtual]
Adds factor to given element in the matrix.
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::add (const std::vector< unsigned int > & i, const std::vector< unsigned int > & j, const T * val) [pure virtual]
adds multiple elements with the indeces given in i and j. The val should be a 2-D matrix of dimensions equal to size of vectors i and j.
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::copy (const FESystemNumerics::MatrixBase< T > & matrix) [pure virtual]
Copies to this matrix
Implemented in FESystemNumerics::PetscSeqDenseMatrix< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::diagonalAdd (const T val, const FESystemNumerics::VectorBase< T > & diag) [pure virtual]
adds a diagonal matrix times a factor to this matrix. The diagonal matrix is given as a vector.
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual T FESystemNumerics::MatrixBase< T >::el (const unsigned int i, const unsigned int j) const [pure virtual]
Returns:
the (i,j) element of the matrix. Since internal data representations may differ, you must redefine this function.
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::getDiagonal (FESystemNumerics::VectorBase< T > & vec) [pure virtual]
returns the diagonal of the matrix in the given vector
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual unsigned int FESystemNumerics::MatrixBase< T >::getMatrixPackage () const [pure virtual]
Returns:
the matrix package
Implemented in FESystemNumerics::PetscMatrixBase< T >.
Referenced by FESystemNumerics::PetscMatrixBase< T >::add(), FESystemNumerics::PetscSeqDenseMatrix< T >::copy(), FESystemNumerics::PetscSeqDenseMatrix< T >::leftMultiply(), FESystemNumerics::PetscMatrixBase< T >::leftMultiply(), FESystemNumerics::PetscSeqDenseMatrix< T >::leftMultiplyTranspose(), FESystemNumerics::PetscMatrixBase< T >::leftMultiplyTranspose(), FESystemNumerics::PetscSeqDenseMatrix< T >::rightMultiply(), and FESystemNumerics::PetscMatrixBase< T >::rightMultiply().
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::getRow (const unsigned int i, FESystemNumerics::VectorBase< T > & vec) [pure virtual]
returns the i th row of the matrix in the given vector
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::leftDiagonalScale (const FESystemNumerics::VectorBase< T > & vector) [pure virtual]
multiplies the matrix with a diagonal matrix on the left hand side. The diagonal matrix is represented as a vector.
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::leftMultiply (const FESystemNumerics::MatrixBase< T > & matrix) [pure virtual]
Performs the operation: (*this) <- M2 * (*this)
Implemented in FESystemNumerics::PetscMatrixBase< T >, and FESystemNumerics::PetscSeqDenseMatrix< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::leftMultiplyTranspose (const FESystemNumerics::MatrixBase< T > & matrix) [pure virtual]
Performs the operation: (*this) <- M2^T * (*this)
Implemented in FESystemNumerics::PetscMatrixBase< T >, and FESystemNumerics::PetscSeqDenseMatrix< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::leftMultiplyVector (const FESystemNumerics::VectorBase< T > & vector_in, FESystemNumerics::VectorBase< T > & result) [pure virtual]
Performs the operation: (*this) <- M2 * (*this)
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual unsigned int FESystemNumerics::MatrixBase< T >::m () const [pure virtual]
Returns:
the row-dimension of the matrix.
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual unsigned int FESystemNumerics::MatrixBase< T >::n () const [pure virtual]
Returns:
the column-dimension of the matrix.
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> void FESystemNumerics::MatrixBase< T >::operator= (const FESystemNumerics::MatrixBase< T > & matrix) [inline]
Copies to this matrix
Definition at line 141 of file MatrixBase.h.
      {Assert(false,ExcInternalError());}
template<typename T > void FESystemNumerics::MatrixBase< T >::print (std::ostream & output) [virtual]
prints the values of this matrix to the output
Definition at line 213 of file MatrixBase.h.
References n.
{
  unsigned int m= this->m(), n = this->n();
  for (unsigned int i=0; i< m; i++)
    {
      for (unsigned int j=0; j< n; j++)
        output << this->el(i,j) << "  ";
      output << std::endl;
    }
}
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::resize (const unsigned int m, const unsigned int n) [pure virtual]
Set every element in the matrix to 0. You must redefine what you mean by zeroing the matrix since it depends on how your values are stored.
Implemented in FESystemNumerics::PetscSeqDenseMatrix< T >, and FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::rightDiagonalScale (const FESystemNumerics::VectorBase< T > & vector) [pure virtual]
multiplies the matrix with a diagonal matrix on the right hand side. The diagonal matrix is represented as a vector.
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::rightMultiply (const FESystemNumerics::MatrixBase< T > & matrix) [pure virtual]
Performs the operation: (*this) <- (*this) * M3
Implemented in FESystemNumerics::PetscMatrixBase< T >, and FESystemNumerics::PetscSeqDenseMatrix< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::rightMultiplyVector (const FESystemNumerics::VectorBase< T > & vector_in, FESystemNumerics::VectorBase< T > & result) [pure virtual]
Performs the operation: (*this) <- M2 * (*this)
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::scale (const T factor) [pure virtual]
multiplies factor to every element in the matrix.
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::set (const unsigned int i, const unsigned int j, const T val) [pure virtual]
sets the given element to
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::set (const std::vector< unsigned int > & i, const std::vector< unsigned int > & j, const T * val) [pure virtual]
sets multiple elements with the indeces given in i and j. The val should be a 2-D matrix of dimensions equal to size of vectors i and j.
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::shift (const T val) [pure virtual]
adds val to all diagonal elements of the matrix
Implemented in FESystemNumerics::PetscMatrixBase< T >.
template<typename T> virtual void FESystemNumerics::MatrixBase< T >::zero () [pure virtual]
Set every element in the matrix to 0. You must redefine what you mean by zeroing the matrix since it depends on how your values are stored.
Implemented in FESystemNumerics::PetscMatrixBase< T >.
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Numerics/MatrixBase.h