fesystem: MaterialPropertyNameEnumerationHandler Class Reference
MaterialPropertyNameEnumerationHandler Class Reference
#include <MaterialPropertyNameEnums.h>
Public Member Functions
void registerEnumData (const unsigned int ID, const std::string &name, const bool if_isotropic)
bool ifOnlyIsotropic (const unsigned int ID) const
Protected Types
typedef std::map< unsigned int,
bool > PropertyKindMapType
Static Protected Attributes
static PropertyKindMapType property_kind_map
Detailed Description
Definition at line 14 of file MaterialPropertyNameEnums.h.
Member Typedef Documentation
typedef std::map<unsigned int, bool> MaterialPropertyNameEnumerationHandler::PropertyKindMapType [protected]
map for storing extra information about the properties, whether they are isotropic in nature or not
Definition at line 27 of file MaterialPropertyNameEnums.h.
Member Function Documentation
bool MaterialPropertyNameEnumerationHandler::ifOnlyIsotropic (const unsigned int ID) const [inline]
Definition at line 60 of file MaterialPropertyNameEnums.h.
References property_kind_map.
Referenced by MaterialPropertyNameBase::ifOnlyIsotropic().
{
  // get the iterator from the map and return the ID
  MaterialPropertyNameEnumerationHandler::PropertyKindMapType::const_iterator it, end;
  it = this->property_kind_map.find(ID);
  end = this->property_kind_map.end();
  Assert(it != end, ExcFESystemIDDoesNotExist(ID));
  return it->second;
}
void MaterialPropertyNameEnumerationHandler::registerEnumData (const unsigned int ID, const std::string & name, const bool if_isotropic) [inline]
Definition at line 34 of file MaterialPropertyNameEnums.h.
References property_kind_map, and NameEnumerationHandler::registerNameAndID().
Referenced by MaterialPropertyNameBase::EnumRegistration< SPRING_CONSTANT >::EnumRegistration().
{
  this->registerNameAndID(ID, name);
  // find the name in the map. If it does not exist, add it, else return the
  // id for this name
  MaterialPropertyNameEnumerationHandler::PropertyKindMapType::const_iterator it, end;
  it = this->property_kind_map.find(ID);
  end = this->property_kind_map.end();
  // make sure that the id and name are unique
  Assert(it == end, ExcFESystemNameAlreadyExists(ID, name));
  // now add the ID to the map
  std::pair<MaterialPropertyNameEnumerationHandler::PropertyKindMapType::iterator, bool>
    return_pair = this->property_kind_map.insert
    (MaterialPropertyNameEnumerationHandler::PropertyKindMapType::value_type(ID, if_isotropic));
  assert (return_pair.second == true);
}
Member Data Documentation
MaterialPropertyNameEnumerationHandler::PropertyKindMapType MaterialPropertyNameEnumerationHandler::property_kind_map [static, protected]
Definition at line 28 of file MaterialPropertyNameEnums.h.
Referenced by ifOnlyIsotropic(), and registerEnumData().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/MaterialPropertyNameEnums.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/FESystem/FESystemStaticMemberDefinitions.C