fesystem: GeometricLine Class Reference
GeometricLine Class Reference
this class defines a geometric point
#include <GeometricLine.h>
Public Member Functions
GeometricLine (GeometricModel &)
constructor
virtual ~GeometricLine ()
destructor
virtual GeometricEntityType type () const =0
returns the type of this entity
const std::vector
< GeometricPoint * > & getPoints () const
returns the coordinates of this point
virtual bool checkIfDuplicate (const GeometricEntity &)=0
method to check if this iobject is a duplicate of the given object
Protected Member Functions
virtual void readFromInput (std::istream &)=0
method to read from input
virtual void writeToOutput (std::ostream &)=0
method to write to output
Protected Attributes
std::vector< GeometricPoint * > points
location of this point
Detailed Description
this class defines a geometric point
Definition at line 17 of file GeometricLine.h.
Constructor & Destructor Documentation
GeometricLine::GeometricLine (GeometricModel & model)
constructor
Definition at line 16 of file GeometricLine.C.
  :GeometricEntity(model)
{
}
GeometricLine::~GeometricLine () [virtual]
destructor
Definition at line 23 of file GeometricLine.C.
{
}
Member Function Documentation
virtual bool GeometricLine::checkIfDuplicate (const GeometricEntity &) [pure virtual]
method to check if this iobject is a duplicate of the given object
Implements GeometricEntity.
Implemented in GeometricCircularArc, GeometricEllipticArc, and GeometricStraightLine.
const std::vector< GeometricPoint * > & GeometricLine::getPoints () const [inline]
returns the coordinates of this point
Definition at line 50 of file GeometricLine.h.
References points.
Referenced by GeometricCircularArc::checkIfDuplicate(), GeometricStraightLine::checkIfDuplicate(), and GeometricEllipticArc::checkIfDuplicate().
{
  return this->points;
}
virtual void GeometricLine::readFromInput (std::istream &) [protected, pure virtual]
method to read from input
Implements GeometricEntity.
Implemented in GeometricCircularArc, GeometricEllipticArc, and GeometricStraightLine.
virtual GeometricEntityType GeometricLine::type () const [inline, pure virtual]
returns the type of this entity
Implements GeometricEntity.
Implemented in GeometricCircularArc, GeometricEllipticArc, and GeometricStraightLine.
virtual void GeometricLine::writeToOutput (std::ostream &) [protected, pure virtual]
method to write to output
Implements GeometricEntity.
Implemented in GeometricCircularArc, GeometricEllipticArc, and GeometricStraightLine.
Member Data Documentation
std::vector<GeometricPoint*> GeometricLine::points [protected]
location of this point
Reimplemented in GeometricCircularArc, GeometricEllipticArc, and GeometricStraightLine.
Definition at line 45 of file GeometricLine.h.
Referenced by getPoints().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricLine.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricLine.C