fesystem: ElemSetList Class Reference
ElemSetList Class Reference
#include <ElemSetList.h>
Public Member Functions
ElemSetList ()
~ElemSetList ()
void clear ()
std::istream & readFromInputStream (std::istream &)
const ElemSet & getElemSetFromID (const unsigned int) const
returns the elem_set card for this ID
Protected Member Functions
void addElemSetToMap (const unsigned int, ElemSet *)
Protected Attributes
std::map< unsigned int, ElemSet * > ID_to_elem_set_map
Detailed Description
Elem_SetList class performs the function of reading the elem_set cards from a specified input stream, storing them, and returning the card when asked for by the user
Definition at line 16 of file ElemSetList.h.
Constructor & Destructor Documentation
ElemSetList::ElemSetList ()
Definition at line 13 of file ElemSetList.C.
{
}
ElemSetList::~ElemSetList ()
Definition at line 24 of file ElemSetList.C.
References clear().
{
  this->clear();
}
Member Function Documentation
void ElemSetList::addElemSetToMap (const unsigned int ID, ElemSet * card) [protected]
Definition at line 99 of file ElemSetList.C.
References ID_to_elem_set_map.
Referenced by readFromInputStream().
{
        // first make sure that the property ID does not already exist in the map
        assert (this->ID_to_elem_set_map.find(ID) ==
                        this->ID_to_elem_set_map.end());
        // then insert the ID, ElemSet pair
        std::pair<std::map<unsigned int, ElemSet*>::iterator, bool>
        insert_return_pair =
        this->ID_to_elem_set_map.insert(std::map<unsigned int, ElemSet*>::value_type(ID,card));
        // and check the return value for a successful insertion
        assert (insert_return_pair.second == true);
}
void ElemSetList::clear ()
Definition at line 35 of file ElemSetList.C.
References ID_to_elem_set_map.
Referenced by ~ElemSetList().
{
  std::map<unsigned int, ElemSet*>::iterator it, end;
  it = this->ID_to_elem_set_map.begin();
  end = this->ID_to_elem_set_map.end();
  for (; it != end; it++)
    {
      delete it->second;
      it->second = NULL;
    }
  this->ID_to_elem_set_map.clear();
}
const ElemSet & ElemSetList::getElemSetFromID (const unsigned int ID) const
returns the elem_set card for this ID
Definition at line 84 of file ElemSetList.C.
References ID_to_elem_set_map.
{
        // get the iterator for this ID, and then make sure that the card exists
        std::map<unsigned int, ElemSet*>::const_iterator card_it =
        this->ID_to_elem_set_map.find(ID);
        assert(card_it != this->ID_to_elem_set_map.end());
        return *(card_it->second);
}
std::istream & ElemSetList::readFromInputStream (std::istream & input)
Definition at line 55 of file ElemSetList.C.
References addElemSetToMap(), ElemSet::ID(), FESystemIOUtility::readFromInput(), and ElemSet::readFromInputStream().
{
  unsigned int n_cards=0;
  FESystemIOUtility::readFromInput(input, "ELEM_SET_LIST");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "N_ELEM_SETS", n_cards);
  for (unsigned int card_incr=0; card_incr < n_cards; card_incr++)
    {
      ElemSet* elem_set = new ElemSet;;
      elem_set->readFromInputStream(input);
      this->addElemSetToMap(elem_set->ID(),elem_set);
    }
  FESystemIOUtility::readFromInput(input, "ELEM_SET_LIST");
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Member Data Documentation
std::map<unsigned int, ElemSet*> ElemSetList::ID_to_elem_set_map [protected]
Definition at line 35 of file ElemSetList.h.
Referenced by addElemSetToMap(), clear(), and getElemSetFromID().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Utilities/ElemSetList.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Utilities/ElemSetList.C