fesystem: Solution::StructuralVibrationEigenSolution Class Reference
Solution::StructuralVibrationEigenSolution Class Reference
this class provides the base functionality for all solutions
#include <StructuralVibrationEigenSolution.h>
Public Member Functions
StructuralVibrationEigenSolution ()
constructor
virtual ~StructuralVibrationEigenSolution ()
destructor
virtual void solve ()
this method will solve for all the load cases and sensitivity analysis
virtual unsigned int getDisciplineTransientNatureEnumID (const unsigned int discipline) const
virtual
FESystemUtility::AutoPtrVector
< FESystemDatabase::DataInfoBase > getTimeIndependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID)
virtual
FESystemUtility::AutoPtrVector
< FESystemDatabase::TransientDataInfoSet > getTimeDependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID)
virtual std::istream & readFromInputStream (std::istream &input)
will read from the input stream
bool ifIncludeGeometricEffects () const
Protected Attributes
bool include_geometric_effects
if the geometric effects should be included in the solution
bool coupled_thermoelastic
unsigned int interpolation_case_ID
ID of the interpolation case if a coupled thermal structural analysis is requested.
Detailed Description
this class provides the base functionality for all solutions
Definition at line 43 of file StructuralVibrationEigenSolution.h.
Constructor & Destructor Documentation
Solution::StructuralVibrationEigenSolution::StructuralVibrationEigenSolution ()
constructor
Definition at line 14 of file StructuralVibrationEigenSolution.C.
References Solution::SolutionBase::addParticipatingDiscipline().
                                                                          :
Solution::SolutionBase(Solution::STRUCTURAL_VIBRATION_EIGEN_SOLUTION::num())
{
  // add the participating discipline to this solution
  this->addParticipatingDiscipline(Discipline::STRUCTURAL_DISCIPLINE::num());
}
Solution::StructuralVibrationEigenSolution::~StructuralVibrationEigenSolution () [virtual]
destructor
Definition at line 23 of file StructuralVibrationEigenSolution.C.
{
}
Member Function Documentation
unsigned int Solution::StructuralVibrationEigenSolution::getDisciplineTransientNatureEnumID (const unsigned int discipline) const [virtual]
Returns:
the transient nature of the given discipline
Implements Solution::SolutionBase.
Definition at line 32 of file StructuralVibrationEigenSolution.C.
References STRUCTURAL_DISCIPLINE_ENUM_ID.
{
  unsigned int enum_ID = 0;
  switch (discipline)
    {
    case STRUCTURAL_DISCIPLINE_ENUM_ID:
      enum_ID = Discipline::STEADY_STATE_SOLUTION::num();
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return enum_ID;
}
FESystemUtility::AutoPtrVector< FESystemDatabase::TransientDataInfoSet > Solution::StructuralVibrationEigenSolution::getTimeDependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID) [virtual]
Returns:
the vector of SolNameInfo structures for the nodal solutions, and for the specified disciplines
Implements Solution::SolutionBase.
Definition at line 202 of file StructuralVibrationEigenSolution.C.
{
  // unused parameter
  (void) discipline_enum_ID;
  // this solution does not have any transients. Hence, return an empty vector
  FESystemUtility::AutoPtrVector<FESystemDatabase::TransientDataInfoSet> vec;
  return vec;
}
FESystemUtility::AutoPtrVector< FESystemDatabase::DataInfoBase > Solution::StructuralVibrationEigenSolution::getTimeIndependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID) [virtual]
Returns:
the vector of SolNameInfo structures for the nodal solutions, and for the specified disciplines
Implements Solution::SolutionBase.
Definition at line 122 of file StructuralVibrationEigenSolution.C.
References FESystemDatabase::GenericDataInfoBase::clear(), FESystemUtility::AutoPtrVector< T >::push_back(), FESystemDatabase::GenericDataInfoBase::setDisciplineEnumID(), FESystemDatabase::GenericDataInfoBase::setDVID(), FESystemDatabase::GenericDataInfoBase::setLoadCase(), FESystemDatabase::GenericDataInfoBase::setName(), and STRUCTURAL_DISCIPLINE_ENUM_ID.
{
  FESystemUtility::AutoPtrVector<FESystemDatabase::DataInfoBase> data_info_vec;
  switch (discipline_enum_ID)
    {
    case STRUCTURAL_DISCIPLINE_ENUM_ID:
      {
        std::auto_ptr<std::vector<DesignData::DesignParameter*> >
        dv_vector(this->fesystem_controller->design_database->getParameters().release());
        FESystemDatabase::TimeIndependentDataInfo eig_val_data_info;
        FESystemDatabase::DataInfoBase *data_info  = NULL;
        DenseVector<double> eig_value_real;
        // iterate over each load case and DV and add the solutions
        for (unsigned int i=0; i < this->load_case_IDs.size(); i++)
          {
          // first get the number of converged eigen values for this load case
          eig_val_data_info.clear();
          eig_val_data_info.setDisciplineEnumID(Discipline::STRUCTURAL_DISCIPLINE::num());
          eig_val_data_info.setName("EigenValuesReal");
          eig_val_data_info.setLoadCase(this->load_case_IDs[i]);
          this->fesystem_controller->global_data_storage->fillVector(eig_val_data_info, eig_value_real);
          for (unsigned int j=0; j < eig_value_real.size(); j++)
            {
            data_info = new FESystemDatabase::TimeIndependentEigenDataInfo;
            data_info->setDisciplineEnumID(Discipline::STRUCTURAL_DISCIPLINE::num());
            data_info->setName("EigenVector_Real");
            data_info->setLoadCase(this->load_case_IDs[i]);
            dynamic_cast<FESystemDatabase::TimeIndependentEigenDataInfo*>(data_info)->setModeInfo(j+1);
            data_info_vec.push_back(data_info);
            data_info = NULL;
            }
          }
        for (unsigned int i=0; i < this->load_case_IDs.size(); i++)
          for (unsigned int j=0; j < dv_vector->size(); j++)
            {
            // first get the number of converged eigen values for this load case
            eig_val_data_info.clear();
            eig_val_data_info.setDisciplineEnumID(Discipline::STRUCTURAL_DISCIPLINE::num());
            eig_val_data_info.setName("EigenValuesReal");
            eig_val_data_info.setLoadCase(this->load_case_IDs[i]);
            eig_val_data_info.setDVID((*dv_vector)[j]->getID());
            this->fesystem_controller->global_data_storage->fillVector(eig_val_data_info,
                                                                       eig_value_real);
            for (unsigned int k=0; k < eig_value_real.size(); k++)
              {
              data_info = new FESystemDatabase::TimeIndependentEigenDataInfo;
              data_info->setDisciplineEnumID(Discipline::STRUCTURAL_DISCIPLINE::num());
              data_info->setName("EigenVector_Real");
              data_info->setLoadCase(this->load_case_IDs[i]);
              data_info->setDVID((*dv_vector)[j]->getID());
              dynamic_cast<FESystemDatabase::TimeIndependentEigenDataInfo*>(data_info)->setModeInfo(k+1);
              data_info_vec.push_back(data_info);
              data_info = NULL;
              }
            }
      }
        break;
        default:
          Assert(false, ExcInternalError());
    }
      return data_info_vec;
}
bool Solution::StructuralVibrationEigenSolution::ifIncludeGeometricEffects () const [inline]
Returns:
true if the geometric effects are to be included
Definition at line 98 of file StructuralVibrationEigenSolution.h.
References include_geometric_effects.
{
  return this->include_geometric_effects;
}
std::istream & Solution::StructuralVibrationEigenSolution::readFromInputStream (std::istream & input) [virtual]
will read from the input stream
Implements Solution::SolutionBase.
Definition at line 66 of file StructuralVibrationEigenSolution.C.
References FESystemIOUtility::readFromInput().
{
  std::string tag;
  unsigned int num = 0;
  FESystemIOUtility::readFromInput(input, Solution::STRUCTURAL_VIBRATION_EIGEN_SOLUTION::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->ID);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "GEOMETRIC_EFFECTS", this->include_geometric_effects);
  FESystemIOUtility::readFromInput(input, "COUPLED_THERMAL_STRUCTURAL",
                                   this->coupled_thermoelastic);
  if (this->coupled_thermoelastic)
    {
      this->addParticipatingDiscipline(Discipline::THERMAL_DISCIPLINE::num());
      FESystemIOUtility::readFromInput(input, "INTERPOLATION_CASE_ID",
                                       this->interpolation_case_ID);
    }
  // Read in the list of load cases
  unsigned int case_ID =0;
  FESystemIOUtility::readFromInput(input, "N_ANALYSIS_LOAD_CASES", num);
  for (unsigned int case_it =0; case_it < num; case_it++)
    {
    case_ID = 0;
    input >> case_ID;
    this->load_case_IDs.push_back(case_ID);
    }
  FESystemIOUtility::readFromInput(input, "N_SOLVER_INFO_ID", num);
  unsigned int solver_class = 0, info_id = 0;
  for (unsigned int i=0; i < num; i++)
    {
    tag.clear();
    input >> tag;
    solver_class = Solver::SolverClassEnum::enumID(tag);
    input >> info_id;
    this->addSolverID(solver_class, info_id);
    }
  FESystemIOUtility::readFromInput(input, Solution::STRUCTURAL_VIBRATION_EIGEN_SOLUTION::name());
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
void Solution::StructuralVibrationEigenSolution::solve () [virtual]
this method will solve for all the load cases and sensitivity analysis
Implements Solution::SolutionBase.
Definition at line 51 of file StructuralVibrationEigenSolution.C.
{
  // solve the linear system if the geometric effects are needed
  if (include_geometric_effects)
    this->linearSolve(Discipline::STRUCTURAL_DISCIPLINE::num());
  // solve the eigen problem
  this->eigenSolve(Discipline::STRUCTURAL_DISCIPLINE::num());
}
Member Data Documentation
bool Solution::StructuralVibrationEigenSolution::coupled_thermoelastic [protected]
boolean to check if coupled thermoelastic solution is needed, which will need solution of the thermal discipline
Definition at line 87 of file StructuralVibrationEigenSolution.h.
bool Solution::StructuralVibrationEigenSolution::include_geometric_effects [protected]
if the geometric effects should be included in the solution
Definition at line 83 of file StructuralVibrationEigenSolution.h.
Referenced by ifIncludeGeometricEffects().
unsigned int Solution::StructuralVibrationEigenSolution::interpolation_case_ID [protected]
ID of the interpolation case if a coupled thermal structural analysis is requested.
Definition at line 90 of file StructuralVibrationEigenSolution.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solutions/StructuralVibrationEigenSolution.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solutions/StructuralVibrationEigenSolution.C