fesystem: LoadBase Class Reference
LoadBase Class Reference
#include <load.h>
Public Member Functions
LoadBase ()
virtual ~LoadBase ()
virtual unsigned int getLoadClassEnumID () const =0
unsigned int getLoadID () const
return the ID of the load
virtual std::istream & readFromInputStream (std::istream &input)=0
Protected Attributes
unsigned int load_ID
Detailed Description
Definition at line 194 of file load.h.
Constructor & Destructor Documentation
LoadBase::LoadBase () [inline]
Definition at line 198 of file load.h.
            :
    load_ID(FESystemNumbers::InvalidID)
    { }
virtual LoadBase::~LoadBase () [inline, virtual]
Definition at line 202 of file load.h.
    { }
Member Function Documentation
virtual unsigned int LoadBase::getLoadClassEnumID () const [pure virtual]
Implemented in DirichletBoundaryCondition, ScalarVolumeLoad, SurfaceRadiationLoad, SurfaceConvectionLoad, ScalarSurfaceLoad, and NodalPointLoad.
Referenced by Loads::NodalPointLoadCombination::addLoad(), Loads::ScalarSurfaceLoadCombination::addLoad(), Loads::SurfaceConvectionLoadCombination::addLoad(), Loads::SurfaceRadiationLoadCombination::addLoad(), Loads::ScalarVolumeLoadCombination::addLoad(), and Loads::DirichletBoundaryConditionCombination::addLoad().
unsigned int LoadBase::getLoadID () const [inline]
return the ID of the load
Definition at line 210 of file load.h.
References FESystemNumbers::InvalidID, and load_ID.
    {
      Assert (this->load_ID != FESystemNumbers::InvalidID, ExcInternalError());
      return this->load_ID;
    }
virtual std::istream& LoadBase::readFromInputStream (std::istream & input) [pure virtual]
Implemented in DirichletBoundaryCondition, ScalarVolumeLoad, SurfaceRadiationLoad, SurfaceConvectionLoad, ScalarSurfaceLoad, and NodalPointLoad.
Member Data Documentation
unsigned int LoadBase::load_ID [protected]
Definition at line 220 of file load.h.
Referenced by getLoadID(), NodalPointLoad::readFromInputStream(), ScalarSurfaceLoad::readFromInputStream(), SurfaceConvectionLoad::readFromInputStream(), SurfaceRadiationLoad::readFromInputStream(), ScalarVolumeLoad::readFromInputStream(), and DirichletBoundaryCondition::readFromInputStream().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/load.h