fesystem: Property::PropertyDatabase Class Reference
Property::PropertyDatabase Class Reference
#include <PropertyDatabase.h>
Public Member Functions
PropertyDatabase (FESystem::FESystemController &controller)
default constructor
~PropertyDatabase ()
destructor
template<typename T >
Property::PropertyCard< T > & getMaterialPropertyCardFromID (const unsigned int card_id)
returns the material property card for this ID
ElemDataCard & getElemDataCardFromID (const unsigned int card_id)
returns the element property card for this ID
void initAllCardsForLocalParameters (std::map< unsigned int, double > *value_map=NULL)
void initAllCardsForGlobalParameters (std::map< unsigned int, double > &value_map)
void clearLocalParameterInitializationForAllCards ()
clears the local parameter initialization of all property card and elem data cards
void clearGlobalParameterInitializationForAllCards ()
clears the global parameter initialization of all property card and elem data cards
std::istream & readFromInputStream (std::istream &input)
method reads the data from an input stream
Protected Types
typedef std::map< unsigned int,
Property::PropertyCardBase * > PropertyCardMap
local type definitions
typedef std::map< unsigned int,
ElemDataCard * > ElemDataCardMap
Protected Member Functions
void readAndStoreMaterialCard (std::istream &input, const unsigned int card_type_enum_ID)
adds a material property card to the map
void readAndStoreElemDataCard (std::istream &input, const unsigned int card_type_enum_ID)
adds an element property card to the map
Protected Attributes
FESystem::FESystemController & fesystem_controller
FESystem controller.
PropertyCardMap ID_to_material_property_card_map
this map stores the material property cards
ElemDataCardMap ID_to_elem_data_card_map
this map stores the elem property cards
Friends
std::istream & operator>> (std::istream &input, Property::PropertyDatabase &database)
overloaded input stream operator
Detailed Description
Definition at line 32 of file PropertyDatabase.h.
Member Typedef Documentation
typedef std::map<unsigned int, ElemDataCard*> Property::PropertyDatabase::ElemDataCardMap [protected]
Definition at line 83 of file PropertyDatabase.h.
typedef std::map<unsigned int, Property::PropertyCardBase*> Property::PropertyDatabase::PropertyCardMap [protected]
local type definitions
Definition at line 82 of file PropertyDatabase.h.
Constructor & Destructor Documentation
Property::PropertyDatabase::PropertyDatabase (FESystem::FESystemController & controller)
default constructor
Definition at line 18 of file PropertyDatabase.C.
                                                                                :
fesystem_controller(controller)
{
}
Property::PropertyDatabase::~PropertyDatabase ()
destructor
Definition at line 30 of file PropertyDatabase.C.
{
  {
    Property::PropertyDatabase::PropertyCardMap::iterator it, end;
    it = this->ID_to_material_property_card_map.begin();
    end = this->ID_to_material_property_card_map.end();
    for (; it!= end; it++)
      {
      delete it->second;
      it->second = NULL;
      }
  }
  {
    Property::PropertyDatabase::ElemDataCardMap::iterator it, end;
    it = this->ID_to_elem_data_card_map.begin();
    end = this->ID_to_elem_data_card_map.end();
    for (; it!= end; it++)
      {
      delete it->second;
      it->second = NULL;
      }
  }
}
Member Function Documentation
void Property::PropertyDatabase::clearGlobalParameterInitializationForAllCards ()
clears the global parameter initialization of all property card and elem data cards
Definition at line 348 of file PropertyDatabase.C.
{
  // get iterators for all elem data cards, and initialize them
  {
    Property::PropertyDatabase::ElemDataCardMap::iterator it, end;
    it = this->ID_to_elem_data_card_map.begin();
    end = this->ID_to_elem_data_card_map.end();
    for (; it != end; it++)
      it->second->clearGlobalParameterInitialization();
  }
  // get iterators for all material property cards, and initialize them
  {
    Property::PropertyDatabase::PropertyCardMap::iterator it, end;
    it = this->ID_to_material_property_card_map.begin();
    end = this->ID_to_material_property_card_map.end();
    for (; it != end; it++)
      it->second->clearGlobalParameterInitialization();
  }
}
void Property::PropertyDatabase::clearLocalParameterInitializationForAllCards ()
clears the local parameter initialization of all property card and elem data cards
Definition at line 320 of file PropertyDatabase.C.
{
  // get iterators for all elem data cards, and initialize them
  {
    Property::PropertyDatabase::ElemDataCardMap::iterator it, end;
    it = this->ID_to_elem_data_card_map.begin();
    end = this->ID_to_elem_data_card_map.end();
    for (; it != end; it++)
      it->second->clearLocalParameterInitialization();
  }
  // get iterators for all material property cards, and initialize them
  {
    Property::PropertyDatabase::PropertyCardMap::iterator it, end;
    it = this->ID_to_material_property_card_map.begin();
    end = this->ID_to_material_property_card_map.end();
    for (; it != end; it++)
      it->second->clearLocalParameterInitialization();
  }
}
ElemDataCard & Property::PropertyDatabase::getElemDataCardFromID (const unsigned int card_id)
returns the element property card for this ID
Definition at line 128 of file PropertyDatabase.C.
Referenced by RadiationCavityAnalysis::calculateB_Matrix(), RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution(), and RadiationCavityAnalysis::calculateEmissivityVector().
{
        // get the iterator for this ID, and then make sure that the card exists
        Property::PropertyDatabase::ElemDataCardMap::const_iterator
  card_it, card_end;
  card_it =     this->ID_to_elem_data_card_map.find(ID);
        card_end =      this->ID_to_elem_data_card_map.end();
        Assert(card_it != card_end,
         FESystemExceptions::ExcIDDoesNotExist("ElemDataCard", ID));
        return *(card_it->second);
}
template<typename T > Property::PropertyCard< T > & Property::PropertyDatabase::getMaterialPropertyCardFromID (const unsigned int card_id)
returns the material property card for this ID
Definition at line 111 of file PropertyDatabase.h.
References ID_to_material_property_card_map.
Referenced by ForcedConvection_1D_ElemDataCard::getFluidMaterialCard(), IsotropicElemDataCard::getMaterialCard(), and ForcedConvection_1D_ElemDataCard::getWallMaterialCard().
{
        // get the iterator for this ID, and then make sure that the card exists
        Property::PropertyDatabase::PropertyCardMap::const_iterator
  card_it, card_end;
  card_it =     this->ID_to_material_property_card_map.find(ID);
        card_end =      this->ID_to_material_property_card_map.end();
        Assert(card_it != card_end,
         FESystemExceptions::ExcIDDoesNotExist("Material Property Card",ID));
  // next, dynamic cast the map, and return it
  Property::PropertyCard<T> *card =
    dynamic_cast<Property::PropertyCard<T>*> (card_it->second);
  return *card;
}
void Property::PropertyDatabase::initAllCardsForGlobalParameters (std::map< unsigned int, double > & value_map)
this method initializes all element data cards at the global parameters provided in the input.
Definition at line 293 of file PropertyDatabase.C.
{
  // get iterators for all elem data cards, and initialize them
  {
    Property::PropertyDatabase::ElemDataCardMap::iterator it, end;
    it = this->ID_to_elem_data_card_map.begin();
    end = this->ID_to_elem_data_card_map.end();
    for (; it != end; it++)
      it->second->reinitGlobalParameters(value_map);
  }
  // get iterators for all material property cards, and initialize them
  {
    Property::PropertyDatabase::PropertyCardMap::iterator it, end;
    it = this->ID_to_material_property_card_map.begin();
    end = this->ID_to_material_property_card_map.end();
    for (; it != end; it++)
      it->second->reinitGlobalParameters(value_map);
  }
}
void Property::PropertyDatabase::initAllCardsForLocalParameters (std::map< unsigned int, double > * value_map = NULL)
this method initializes all element data and property cards at the local parameters provided in the input.
Definition at line 263 of file PropertyDatabase.C.
{
  // get iterators for all elem data cards, and initialize them
  {
    Property::PropertyDatabase::ElemDataCardMap::iterator it, end;
    it = this->ID_to_elem_data_card_map.begin();
    end = this->ID_to_elem_data_card_map.end();
    for (; it != end; it++)
      it->second->reinitLocalParameters(value_map);
  }
  // get iterators for all material property cards, and initialize them
  {
    Property::PropertyDatabase::PropertyCardMap::iterator it, end;
    it = this->ID_to_material_property_card_map.begin();
    end = this->ID_to_material_property_card_map.end();
    for (; it != end; it++)
      it->second->reinitLocalParameters(value_map);
  }
}
void Property::PropertyDatabase::readAndStoreElemDataCard (std::istream & input, const unsigned int card_type_enum_ID) [protected]
adds an element property card to the map
Definition at line 191 of file PropertyDatabase.C.
References Property::PropertyCardBase::attachFunctionDatabase(), ElemDataCard::attachPropertyDatabase(), FORCED_CONVECTION_1D_ELEM_DATA_CARD_ENUM_ID, Property::PropertyCardBase::getID(), ISOTROPIC_1D_ELEM_DATA_CARD_ENUM_ID, ISOTROPIC_2D_ELEM_DATA_CARD_ENUM_ID, and ISOTROPIC_3D_ELEM_DATA_CARD_ENUM_ID.
{
  ElemDataCard *card = NULL;
  // first read in the card
  switch (card_type_enum_ID)
    {
    case ISOTROPIC_1D_ELEM_DATA_CARD_ENUM_ID:
      {
        Isotropic1D_ElemDataCard *data_card = new Isotropic1D_ElemDataCard;
        input >> (*data_card);
        card = data_card;
      }
      break;
    case ISOTROPIC_2D_ELEM_DATA_CARD_ENUM_ID:
      {
        Isotropic2D_ElemDataCard *data_card = new Isotropic2D_ElemDataCard;
        input >> (*data_card);
        card = data_card;
      }
      break;
    case ISOTROPIC_3D_ELEM_DATA_CARD_ENUM_ID:
      {
        Isotropic3D_ElemDataCard *data_card = new Isotropic3D_ElemDataCard;
        input >> (*data_card);
        card = data_card;
      }
      break;
    case FORCED_CONVECTION_1D_ELEM_DATA_CARD_ENUM_ID:
      {
        ForcedConvection_1D_ElemDataCard *data_card = new ForcedConvection_1D_ElemDataCard;
        input >> (*data_card);
        card = data_card;
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (ElemDataCardEnum::enumName(card_type_enum_ID)));
    }
  // attach the function database to the card
  card->attachFunctionDatabase(*(this->fesystem_controller.function_database.get()));
  // attach the property database to this card
  card->attachPropertyDatabase(*this);
  // now add it
  unsigned int ID = card->getID();
  // first make sure that the property ID does not already exist in the map
  bool insert_success =
    this->ID_to_elem_data_card_map.insert
    (PropertyDatabase::ElemDataCardMap::value_type(ID, card)).second;
        if (!insert_success)
    delete card;
  Assert(insert_success,
         FESystemExceptions::ExcDuplicateID("ElemDataCard" ,ID));
}
void Property::PropertyDatabase::readAndStoreMaterialCard (std::istream & input, const unsigned int card_type_enum_ID) [protected]
adds a material property card to the map
Definition at line 146 of file PropertyDatabase.C.
References Property::PropertyCardBase::attachFunctionDatabase(), Property::PropertyCardBase::getID(), and ISOTROPIC_MATERIAL_PROPERTY_CARD_ENUM_ID.
{
  Property::PropertyCardBase *card = NULL;
  // first read in the card
  switch (card_type_enum_ID)
    {
    case ISOTROPIC_MATERIAL_PROPERTY_CARD_ENUM_ID:
      {
        IsotropicMaterialPropertyCard *mat_card = new IsotropicMaterialPropertyCard;
        input >> (*mat_card);
        card = mat_card;
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (MaterialPropertyCardEnum::enumName(card_type_enum_ID)));
    }
  // attach the function database to the card
  card->attachFunctionDatabase(*(this->fesystem_controller.function_database.get()));
  // now add it
  unsigned int ID = card->getID();
  // first make sure that the property ID does not already exist in the map
  bool insert_success =
    this->ID_to_material_property_card_map.insert
    (PropertyDatabase::PropertyCardMap::value_type(ID, card)).second;
        if (!insert_success)
    delete card;
  Assert(insert_success,
         FESystemExceptions::ExcDuplicateID("MaterialPropertyCard", ID));
}
std::istream & Property::PropertyDatabase::readFromInputStream (std::istream & input)
method reads the data from an input stream
Definition at line 67 of file PropertyDatabase.C.
References FESystemIOUtility::peekFromInput(), and FESystemIOUtility::readFromInput().
{
        std::string tag;
        unsigned int n_cards=0;
  FESystemIOUtility::readFromInput(input, "PROPERTY_DATABASE");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  {
    FESystemIOUtility::readFromInput(input, "MATERIAL_PROPERTY_CARDS");
    FESystemIOUtility::readFromInput(input, "BEGIN");
    FESystemIOUtility::readFromInput(input, "N_MATERIAL_PROPERTY_CARDS", n_cards);
    unsigned int card_enum_ID = 0;
    for (unsigned int i=0; i < n_cards; i++)
      {
      FESystemIOUtility::peekFromInput(input, tag);
      card_enum_ID = MaterialPropertyCardEnum::enumID(tag);
      this->readAndStoreMaterialCard(input, card_enum_ID);
      }
    FESystemIOUtility::readFromInput(input, "MATERIAL_PROPERTY_CARDS");
    FESystemIOUtility::readFromInput(input, "END");
  }
  {
    FESystemIOUtility::readFromInput(input, "ELEM_DATA_CARDS");
    FESystemIOUtility::readFromInput(input, "BEGIN");
    FESystemIOUtility::readFromInput(input, "N_ELEM_DATA_CARDS", n_cards);
    unsigned int card_enum_ID = 0;
    for (unsigned int i=0; i < n_cards; i++)
      {
      FESystemIOUtility::peekFromInput(input, tag);
      card_enum_ID = ElemDataCardEnum::enumID(tag);
      this->readAndStoreElemDataCard(input, card_enum_ID);
      }
    FESystemIOUtility::readFromInput(input, "ELEM_DATA_CARDS");
    FESystemIOUtility::readFromInput(input, "END");
  }
  FESystemIOUtility::readFromInput(input, "PROPERTY_DATABASE");
  FESystemIOUtility::readFromInput(input, "END");
        return input;
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, Property::PropertyDatabase & database) [friend]
overloaded input stream operator
Definition at line 97 of file PropertyDatabase.h.
    {
      database.readFromInputStream(input);
      return input;
    }
Member Data Documentation
FESystem::FESystemController& Property::PropertyDatabase::fesystem_controller [protected]
FESystem controller.
Definition at line 86 of file PropertyDatabase.h.
ElemDataCardMap Property::PropertyDatabase::ID_to_elem_data_card_map [protected]
this map stores the elem property cards
Definition at line 92 of file PropertyDatabase.h.
PropertyCardMap Property::PropertyDatabase::ID_to_material_property_card_map [protected]
this map stores the material property cards
Definition at line 89 of file PropertyDatabase.h.
Referenced by getMaterialPropertyCardFromID().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/PropertyDatabase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/PropertyDatabase.C