fesystem: RadiationElement Class Reference
RadiationElement Class Reference
#include <RadiationElement.h>
Public Member Functions
RadiationElement (RadiationCavityFiniteElem &rad_cav_elem, const Elem *fe_elem)
~RadiationElement ()
destructor
void init ()
init this object
unsigned int ID () const
ID of the elem.
unsigned int FeElementID () const
ID of the finite element that this is attached to.
int FeElementFaceID () const
face ID for the finite element
void setData (unsigned int elem_ID, unsigned int x_div_num, unsigned int y_div_num)
Elem * getRadiationGeometricElem ()
this function gets the geom elem for the radiation elem
Point & getSurfaceNormal ()
returns the surface normal for this element
double getArea ()
returns the area for this element
void printInfo (std::ostream &output)
writes the information for this element
void getRadElemG_Vector (FESystemNumerics::PetscSeqVector< double > &vector)
const std::vector< Node * > & getGlobalCoordinateNodes ()
returns a reference to the nodes in global ocordinates for this element
const std::vector< Node * > & getLocalCoordinateNodes ()
returns a reference to the nodes in local coorodinates for this element
void initLocalRadiationElement ()
method to init the local radiation element in its own coordinates
Elem * getLocalRadiationGeometricElem ()
returns the local radiation element
Protected Attributes
RadiationCavityFiniteElem & fe_rad_elem
const Elem * fe_elem
geometric finite element to which this element belongs
unsigned int elem_ID
element ID
unsigned int x_division_number
x div number on FE
unsigned int y_division_number
y div number on FE
std::auto_ptr< Elem > geometric_rad_elem
std::auto_ptr< Elem > local_elem
double area
area
bool initialized
says if this is initialized
Point normal
normal
std::vector< Node * > global_coordinate_nodes
std::vector< Node * > local_coordinate_nodes
std::vector< Node * > local_nodes
Detailed Description
Definition at line 28 of file RadiationElement.h.
Constructor & Destructor Documentation
RadiationElement::RadiationElement (RadiationCavityFiniteElem & rad_cav_elem, const Elem * fe_elem)
constructor
Parameters:
rad_cav_elem the radiation cavity element that contains the details of the finite element to which this element belongs
fe_elem the geometric elem defining the finite element to which this element belongs
Definition at line 22 of file RadiationElement.C.
                                                       :
  fe_rad_elem(rad_cav_elem),
  fe_elem(fe_elem),
  elem_ID(0),
  x_division_number(0),
  y_division_number(0),
  geometric_rad_elem(NULL),
  local_elem(NULL),
  area(0.0),
  initialized(false)
{
}
RadiationElement::~RadiationElement ()
destructor
Definition at line 38 of file RadiationElement.C.
References global_coordinate_nodes, local_coordinate_nodes, and local_nodes.
{
  // iterate over the nodes and delete them
  std::vector<Node*>::iterator it, end;
  it = this->global_coordinate_nodes.begin();
  end = this->global_coordinate_nodes.end();
  for (; it != end; it++)
    delete *it;
  it = this->local_coordinate_nodes.begin();
  end = this->local_coordinate_nodes.end();
  for (; it != end; it++)
    delete *it;
  it = this->local_nodes.begin();
  end = this->local_nodes.end();
  for (; it != end; it++)
    delete *it;
}
Member Function Documentation
int RadiationElement::FeElementFaceID () const [inline]
face ID for the finite element
Definition at line 175 of file RadiationElement.h.
References fe_rad_elem, and RadiationCavityFiniteElem::side_num.
Referenced by RadiationElementPair::analyticShapeFactor(), and RadiationElementPair::mitalasContourIntShapeFactor().
{
  return this->fe_rad_elem.side_num;
}
unsigned int RadiationElement::FeElementID () const [inline]
ID of the finite element that this is attached to.
Definition at line 168 of file RadiationElement.h.
References RadiationCavityFiniteElem::elem_ID, and fe_rad_elem.
Referenced by RadiationCavityAnalysis::calculateB_Matrix(), and RadiationElementPair::reinit().
{
  return this->fe_rad_elem.elem_ID;
}
double RadiationElement::getArea () [inline]
returns the area for this element
Definition at line 195 of file RadiationElement.h.
References area, init(), and initialized.
Referenced by RadiationElementPair::analyticShapeFactor(), RadiationElementPair::contourIntShapeFactor(), RadiationElementPair::doubleAreaIntShapeFactor(), and RadiationElementPair::mitalasContourIntShapeFactor().
{
  if (!this->initialized)
    this->init();
  return this->area;
}
const std::vector< Node * > & RadiationElement::getGlobalCoordinateNodes () [inline]
returns a reference to the nodes in global ocordinates for this element
Definition at line 215 of file RadiationElement.h.
References global_coordinate_nodes, init(), and initialized.
{
  if (!this->initialized)
    this->init();
  return this->global_coordinate_nodes;
}
const std::vector< Node * > & RadiationElement::getLocalCoordinateNodes () [inline]
returns a reference to the nodes in local coorodinates for this element
Definition at line 225 of file RadiationElement.h.
References init(), initialized, and local_coordinate_nodes.
{
  if (!this->initialized)
    this->init();
  return this->local_coordinate_nodes;
}
Elem * RadiationElement::getLocalRadiationGeometricElem () [inline]
returns the local radiation element
Definition at line 235 of file RadiationElement.h.
References init(), initialized, and local_elem.
Referenced by RadiationElementPair::doubleAreaIntShapeFactor().
{
  if (!this->initialized)
    this->init();
  return this->local_elem.get();
}
void RadiationElement::getRadElemG_Vector (FESystemNumerics::PetscSeqVector< double > & vector)
returns the element G vector used for interpolation between FE and radiation quantities
Parameters:
the vector is returned in this arguement
Definition at line 363 of file RadiationElement.C.
References FESystemNumerics::PetscVectorBase< T >::add(), fe_elem, local_coordinate_nodes, local_elem, FESystemNumerics::PetscSeqVector< T >::resize(), FESystemNumerics::PetscVectorBase< T >::size(), and FESystemNumerics::PetscVectorBase< T >::zero().
{
  // for now, this method will handle only the 2-D elems
  assert (this->fe_elem->dim() == 2);
  unsigned int n_nodes = this->fe_elem->n_nodes();
  // resize the vector if necessary
  if (vector.size() != n_nodes)
    vector.resize(n_nodes);
  // now process and insert the data
  // init a gauss quadrature and calculate the local coordinates for this elem
  std::auto_ptr<QBase> quadrature(new QGauss(2,FIFTH));
  std::auto_ptr<FEBase> fe_rad(new FE<2, LAGRANGE>(FEType()));
  // to calculate the JxW, an element in its local coordinate needs to be
  // used, since in general, an element can exist in a 3-D space, and this will
  // create problems for 3-D elems
  //
  fe_rad->attach_quadrature_rule(quadrature.get());
  fe_rad->reinit(local_elem.get());
  const std::vector<std::vector<Real> >& phi_rad = fe_rad->get_phi();
  const std::vector<Real>& JxW_rad = fe_rad->get_JxW();
  std::vector<Point> points;
  for (unsigned int qp = 0; qp < phi_rad[0].size(); qp++)
    {
      Point pt;
      for (unsigned int i=0; i < phi_rad.size(); i++)
        {
          Node& node = *(this->local_coordinate_nodes[i]);
          pt(0) += phi_rad[i][qp] * node(0);
          pt(1) += phi_rad[i][qp] * node(1);
        }
      points.push_back(pt);
    }
  // the point localtions calculated above are the nodal values of the
  // quad points in the local coordinates of the FE to which this
  // element is attached
  std::auto_ptr<FEBase> global_fe(new FE<2,LAGRANGE>(FEType()));
  global_fe->reinit(this->fe_elem, &points);
  const std::vector<std::vector<Real> >& phi_global = global_fe->get_phi();
  // now, calculate the G_vector
  vector.zero();
  for (unsigned int qp=0; qp < JxW_rad.size(); qp++)
    for (unsigned int i=0; i < phi_global.size(); i++)
      vector.add(i, phi_global[i][qp] * JxW_rad[qp]);
}
Elem * RadiationElement::getRadiationGeometricElem ()
this function gets the geom elem for the radiation elem
Definition at line 221 of file RadiationElement.C.
References geometric_rad_elem, init(), and initialized.
Referenced by RadiationElementPair::analyticShapeFactor(), RadiationElementPair::contourIntShapeFactor(), RadiationElementPair::doubleAreaIntShapeFactor(), RadiationElementPair::mitalasContourIntShapeFactor(), and RadiationElementPair::reinit().
{
  // if the elem has not been initialized, init it and
  // then return the elem
  if (!this->initialized)
    this->init();
  return this->geometric_rad_elem.get();
}
Point & RadiationElement::getSurfaceNormal () [inline]
returns the surface normal for this element
Definition at line 205 of file RadiationElement.h.
References init(), initialized, and normal.
Referenced by RadiationElementPair::analyticShapeFactor(), RadiationElementPair::contourIntShapeFactor(), RadiationElementPair::doubleAreaIntShapeFactor(), RadiationElementPair::mitalasContourIntShapeFactor(), and RadiationElementPair::reinit().
{
  if (!this->initialized)
    this->init();
  return this->normal;
}
unsigned int RadiationElement::ID () const [inline]
ID of the elem.
Definition at line 161 of file RadiationElement.h.
References elem_ID.
Referenced by RadiationCavityAnalysis::calculateShapeFactorMatrix().
{
  return this->elem_ID;
}
void RadiationElement::init ()
init this object
first point
first point
Definition at line 61 of file RadiationElement.C.
References area, fe_elem, fe_rad_elem, geometric_rad_elem, global_coordinate_nodes, initialized, initLocalRadiationElement(), local_coordinate_nodes, RadiationCavityFiniteElem::n_x_divs, RadiationCavityFiniteElem::n_y_divs, normal, RadiationCavityFiniteElem::side_num, x_division_number, and y_division_number.
Referenced by getArea(), getGlobalCoordinateNodes(), getLocalCoordinateNodes(), getLocalRadiationGeometricElem(), getRadiationGeometricElem(), getSurfaceNormal(), and printInfo().
{
  // get the finite element data from the cavity
  unsigned int  n_x_divs = 0, n_y_divs = 0;
  n_x_divs = this->fe_rad_elem.n_x_divs;
  n_y_divs = this->fe_rad_elem.n_y_divs;
  // calculate the local coordinates of the local elem
  double dx=2.0/n_x_divs, dy=2.0/n_y_divs;
  static Point point;
  static Elem* fe_elem_ptr = NULL;
  // first point
  std::vector<Point> point_vec;
  switch (this->fe_elem->type())
    {
    case TRI3:
      {
        // for now, no divisions are supported for triangle elements
        Assert (n_x_divs == 1, ExcInternalError());
        Assert (n_y_divs == 1, ExcInternalError());
        /// first point
        point.zero();
        point(0) = 0.0;
        point(1) = 0.0;
        point_vec.push_back(point);
        this->local_coordinate_nodes.push_back(new Node(point,0));
        // second point
        point.zero();
        point(0) = 1.0;
        point(1) = 0.0;
        point_vec.push_back(point);
        this->local_coordinate_nodes.push_back(new Node(point,1));
        // third point
        point.zero();
        point(0) = 0.0;
        point(1) = 1.0;
        point_vec.push_back(point);
        this->local_coordinate_nodes.push_back(new Node(point,2));
        fe_elem_ptr = const_cast<Elem*>(this->fe_elem);
      }
    break;
    case QUAD4:
      {
        /// first point
        point.zero();
        point(0) = -1.0 + dx * this->x_division_number;
        point(1) = -1.0 + dy * this->y_division_number;
        point_vec.push_back(point);
        this->local_coordinate_nodes.push_back(new Node(point,0));
        // second point
        point.zero();
        point(0) = -1.0 + dx * (this->x_division_number + 1);
        point(1) = -1.0 + dy * (this->y_division_number);
        point_vec.push_back(point);
        this->local_coordinate_nodes.push_back(new Node(point,1));
        // third point
        point.zero();
        point(0) = -1.0 + dx * (this->x_division_number + 1);
        point(1) = -1.0 + dy * (this->y_division_number + 1);
        point_vec.push_back(point);
        this->local_coordinate_nodes.push_back(new Node(point,2));
        // fourth point
        point.zero();
        point(0) = -1.0 + dx * (this->x_division_number);
        point(1) = -1.0 + dy * (this->y_division_number + 1);
        point_vec.push_back(point);
        this->local_coordinate_nodes.push_back(new Node(point,3));
        fe_elem_ptr = const_cast<Elem*>(this->fe_elem);
      }
      break;
    default:
      Assert(false, ExcInternalError());
    }
  // now, init a finite element with the FE geometric elem,
  // and init it as the points calculated above
  std::auto_ptr<FEBase> fe(new FE<2,LAGRANGE>(FEType()));
//  else if (this->fe_elem->type() == HEX8)
//    {
//      elem_for_init.reset(this->fe_elem->build_side(this->fe_rad_elem.side_num).release());
//      fe_elem_ptr = elem_for_init.get();
//    }
  fe->reinit(fe_elem_ptr, &point_vec);
  // get the phi map
  const std::vector<std::vector<Real> >& phi = fe->get_phi();
  // now iterate over the points and calculate the nodal values,
  // create the nodes and add them to the nodal vector
  for (unsigned int i=0; i< this->fe_elem->n_nodes(); i++)
    {
      point.zero();
      for (unsigned int j=0; j < this->fe_elem->n_nodes(); j++)
        {
        const Node& elem_node = *(this->fe_elem->get_node(j));
        for (unsigned int k = 0; k < 3; k++)
          point(k) += phi[j][i] * elem_node(k);
        }
      std::auto_ptr<Node> node(new Node(point, i));
      this->global_coordinate_nodes.push_back(node.release());
    }
  // now create an elem
  this->geometric_rad_elem.reset(Elem::build(this->fe_elem->type()).release());
  for (unsigned int i=0; i < this->fe_elem->n_nodes(); i++)
    this->geometric_rad_elem->set_node(i) =
      this->global_coordinate_nodes[i];
  // now calculate the area and surface normal of the element
  // get the location of the four nodes of this element
  const Point& point0 = this->geometric_rad_elem->point(0);
  const Point& point1 = this->geometric_rad_elem->point(1);
  const Point& point2 = this->geometric_rad_elem->point(2);
  //calculate the position vectors from point 0
  static Point vector02, vector01, tmp_vector1;
  vector02.assign(point2 - point0);
  vector01.assign(point1 - point0);
  // calculate the cross product and scale it by the side (for +ve or -ve)
  tmp_vector1.assign(vector01.cross(vector02));
  this->area = this->geometric_rad_elem->volume();
  this->normal.assign(tmp_vector1.unit());
  // now, based on the sign of the side, scale the normal to indicate a +ve or -ve
  // element normal
  if (fe_rad_elem.side_num < 0)
  this->normal *= -1.0;
  this->initLocalRadiationElement();
  this->initialized = true;
}
void RadiationElement::initLocalRadiationElement ()
method to init the local radiation element in its own coordinates
Definition at line 262 of file RadiationElement.C.
References fe_elem, geometric_rad_elem, local_elem, and local_nodes.
Referenced by init().
{
  // this method will initialize the Elem for this radiation element in its
  // own local coordinates. This coordinate is different from the
  // global coordinate or the local coordinate system in the FE elem
  //get the four nodes of this elem
  switch (this->fe_elem->type())
    {
    case TRI3:
      {
        //get the three nodes of this elem
        const Point& point0 = this->geometric_rad_elem->point(0);
        const Point& point1 = this->geometric_rad_elem->point(1);
        const Point& point2 = this->geometric_rad_elem->point(2);
        //calculate the position vectors from point 0
        static Point vector01, vector02, tmp_vector1, tmp_vector2,
          new_unit_vec_x, new_unit_vec_y;
        vector01.assign(point1 - point0);
        vector02.assign(point2 - point0);
        new_unit_vec_x = vector01.unit();
        tmp_vector1.assign(new_unit_vec_x.cross(vector02));
        tmp_vector2 = tmp_vector1.unit();
        new_unit_vec_y = tmp_vector2.cross(new_unit_vec_x);
        //create a new element and set its two nodes at the
        //origin and the elem length
        static Point new_point0, new_point1, new_point2;
        new_point0.zero(); new_point1.zero(); new_point2.zero();
        new_point1(0)  = vector01.size();
        new_point2(0) = vector02 * new_unit_vec_x;
        new_point2(1) = vector02 * new_unit_vec_y;
        this->local_nodes.push_back(new Node(new_point0, 0));
        this->local_nodes.push_back(new Node(new_point1, 1));
        this->local_nodes.push_back(new Node(new_point2, 2));
      }
      break;
    case QUAD4:
      {
        //get the four nodes of this elem
        const Point& point0 = this->geometric_rad_elem->point(0);
        const Point& point1 = this->geometric_rad_elem->point(1);
        const Point& point2 = this->geometric_rad_elem->point(2);
        const Point& point3 = this->geometric_rad_elem->point(3);
        //calculate the position vectors from point 0
        static Point vector01, vector02, vector03, tmp_vector1, tmp_vector2,
          new_unit_vec_x, new_unit_vec_y;
        vector01.assign(point1 - point0);
        vector02.assign(point2 - point0);
        vector03.assign(point3 - point0);
        new_unit_vec_x = vector01.unit();
        tmp_vector1.assign(new_unit_vec_x.cross(vector03));
        tmp_vector2 = tmp_vector1.unit();
        new_unit_vec_y = tmp_vector2.cross(new_unit_vec_x);
        //create a new element and set its two nodes at the
        //origin and the elem length
        static Point new_point0, new_point1, new_point2, new_point3;
        new_point0.zero(); new_point1.zero(); new_point2.zero(); new_point3.zero();
        new_point1(0) = vector01.size();
        new_point2(0) = vector02 * new_unit_vec_x;
        new_point2(1) = vector02 * new_unit_vec_y;
        new_point3(0) = vector03 * new_unit_vec_x;
        new_point3(1) = vector03 * new_unit_vec_y;
        this->local_nodes.push_back(new Node(new_point0, 0));
        this->local_nodes.push_back(new Node(new_point1, 1));
        this->local_nodes.push_back(new Node(new_point2, 2));
        this->local_nodes.push_back(new Node(new_point3, 3));
      }
      break;
    default:
      // cases for TRI6, QUAD8, QUAD9 are not handled
      abort();
      break;
    }
  // now create the local element and set its nodes
  this->local_elem.reset(Elem::build(this->fe_elem->type()).release());
  for (unsigned int i=0; i<this->fe_elem->n_nodes(); i++)
    this->local_elem->set_node(i) = this->local_nodes[i];
}
void RadiationElement::printInfo (std::ostream & output)
writes the information for this element
Definition at line 233 of file RadiationElement.C.
References area, RadiationCavityFiniteElem::elem_ID, elem_ID, fe_rad_elem, global_coordinate_nodes, init(), initialized, normal, RadiationCavityFiniteElem::side_num, x_division_number, and y_division_number.
{
  // if the element is not initialized, initialize it and then print
  // the info
  if (!this->initialized)
    this->init();
  output << "Radiation Element ID: " << this->elem_ID << std::endl
         << "        FE Elem: " <<  this->fe_rad_elem.elem_ID
         << "  with Face: " << this->fe_rad_elem.side_num << std::endl
         << "        Division number in FE Elem: x = " << this->x_division_number
         << "  y = " << this->y_division_number << std::endl
         << "        Area = " << this->area << std::endl
         << "        Surface Normal = " << this->normal << std::endl
         << "        Node Locations: " << std::endl;
  // now print node locations
  std::vector<Node*>::const_iterator it, end;
  it = this->global_coordinate_nodes.begin();
  end = this->global_coordinate_nodes.end();
  for ( ; it != end; it++)
    output << (*(*it));
    output << std::endl;
}
void RadiationElement::setData (unsigned int elem_ID, unsigned int x_div_num, unsigned int y_div_num) [inline]
this method sets the data for the element.
Parameters:
elem_ID is the local radiation elem ID
FE_ID is the finite element ID of the elem
side_num is the side number of the element
x_div_num is the number of the division along the x-axis that the element will belong to
y_div_num is the number of the division along the y-axis that the element will belong to
Definition at line 183 of file RadiationElement.h.
References elem_ID, x_division_number, and y_division_number.
Referenced by RadiationCavity::createFENodeVectorAndRadiationElems().
{
  this->elem_ID = el_ID;
  this->x_division_number = x_div_num;
  this->y_division_number = y_div_num;
}
Member Data Documentation
double RadiationElement::area [protected]
area
Definition at line 136 of file RadiationElement.h.
Referenced by getArea(), init(), and printInfo().
unsigned int RadiationElement::elem_ID [protected]
element ID
Definition at line 110 of file RadiationElement.h.
Referenced by ID(), printInfo(), and setData().
const Elem* RadiationElement::fe_elem [protected]
geometric finite element to which this element belongs
Definition at line 107 of file RadiationElement.h.
Referenced by getRadElemG_Vector(), init(), and initLocalRadiationElement().
RadiationCavityFiniteElem& RadiationElement::fe_rad_elem [protected]
radiation cavity finite element that defines the finite element to which this radiation element is attached
Definition at line 104 of file RadiationElement.h.
Referenced by FeElementFaceID(), FeElementID(), init(), and printInfo().
std::auto_ptr<Elem> RadiationElement::geometric_rad_elem [protected]
geometric FE. This is the element in the Finite Element mesh to which this radiation element belongs.
Definition at line 120 of file RadiationElement.h.
Referenced by getRadiationGeometricElem(), init(), and initLocalRadiationElement().
std::vector<Node*> RadiationElement::global_coordinate_nodes [protected]
vector of nodes for the geometric rad elem. These define the global coordinates of this radiation element
Definition at line 146 of file RadiationElement.h.
Referenced by getGlobalCoordinateNodes(), init(), printInfo(), and ~RadiationElement().
bool RadiationElement::initialized [protected]
says if this is initialized
Definition at line 139 of file RadiationElement.h.
Referenced by getArea(), getGlobalCoordinateNodes(), getLocalCoordinateNodes(), getLocalRadiationGeometricElem(), getRadiationGeometricElem(), getSurfaceNormal(), init(), and printInfo().
std::vector<Node*> RadiationElement::local_coordinate_nodes [protected]
vector of local_coordinate nodes. These are the local non-dimensional coordinates of the radiation element inside the FE based upon the division number for this element.
Definition at line 151 of file RadiationElement.h.
Referenced by getLocalCoordinateNodes(), getRadElemG_Vector(), init(), and ~RadiationElement().
std::auto_ptr<Elem> RadiationElement::local_elem [protected]
elem in the local coordinate. This is the geometric element that defines the radiation element. This is created from the finite element to which this element belongs, along with the division number. The nodes Different sets of nodes are associated with this element. Upon creation of the element, the nodes associated with the global coordinates of this element are stored in global_coordinate_nodes. The non-dimensional coordinates of these nodes define their location inside the finite element, and these are stores in local_coordinate nodes. For the purpose of integration inside this element, a local axis is created with its origin at node 0 and x-axis along node0->node1 vector. These nodes are stored in local_nodes vector.
Definition at line 133 of file RadiationElement.h.
Referenced by getLocalRadiationGeometricElem(), getRadElemG_Vector(), and initLocalRadiationElement().
std::vector<Node*> RadiationElement::local_nodes [protected]
vector of ndoes for the local elem. These define the nodes in the coordinate system defined by the origin at node 0 and x-axis along node0->node1 vector.
Definition at line 156 of file RadiationElement.h.
Referenced by initLocalRadiationElement(), and ~RadiationElement().
Point RadiationElement::normal [protected]
normal
Definition at line 142 of file RadiationElement.h.
Referenced by getSurfaceNormal(), init(), and printInfo().
unsigned int RadiationElement::x_division_number [protected]
x div number on FE
Definition at line 113 of file RadiationElement.h.
Referenced by init(), printInfo(), and setData().
unsigned int RadiationElement::y_division_number [protected]
y div number on FE
Definition at line 116 of file RadiationElement.h.
Referenced by init(), printInfo(), and setData().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Radiation/RadiationElement.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Radiation/RadiationElement.C