fesystem: TimeDependentLoadCase Class Reference
TimeDependentLoadCase Class Reference
#include <LoadCase.h>
Public Member Functions
TimeDependentLoadCase (LoadDatabase &database)
constructor
virtual ~TimeDependentLoadCase ()
destructor
virtual void clear ()
clears the data structures for this object
virtual unsigned int getLoadCaseKindEnumID () const
bool ifLoadFactorDependent (unsigned int load_enum_ID)
virtual void getLoadFactorLoadSetPair (const Loads::LoadDataInfoBase &load_info, std::vector< std::pair< unsigned int, double > > &load_pair) const
fills the vector with the load set ID and its load factor
virtual std::istream & readFromInputStream (std::istream &)
this method reads the load case data from the input stream
void addLoadSetID (const double time, const unsigned int load_enum_ID, const unsigned int load_set_ID, const double load_factor, const unsigned int DV_ID)
void addLoadSetID (const unsigned int load_enum_ID, const unsigned int load_set_ID, const unsigned int load_factor_ID, const unsigned int DV_ID)
Protected Member Functions
void getLoadPair (const double time, const unsigned int load_enum_ID, const unsigned int DV_ID, std::vector< std::pair< unsigned int, double > > &load_pair) const
fills the vector with the load pair
Protected Attributes
LoadEnumToLoadFactorIDMap load_factor_dependent_load_ID_map
this stores the load set IDs for loads associated with a time dependent load factor
LoadEnumToDVTimeMap time_load_ID_map
Detailed Description
Definition at line 167 of file LoadCase.h.
Constructor & Destructor Documentation
TimeDependentLoadCase::TimeDependentLoadCase (LoadDatabase & database)
constructor
Definition at line 211 of file LoadCase.C.
                                                                  :
LoadCaseBase(database)
{
}
TimeDependentLoadCase::~TimeDependentLoadCase () [virtual]
destructor
Definition at line 218 of file LoadCase.C.
{
}
Member Function Documentation
void TimeDependentLoadCase::addLoadSetID (const double time, const unsigned int load_enum_ID, const unsigned int load_set_ID, const double load_factor, const unsigned int DV_ID)
this will add a loadset with its reference tag to a specified time instant. If the specified time instant does not exist, this method will create it and add the load
Definition at line 246 of file LoadCase.C.
References time_load_ID_map.
Referenced by readFromInputStream().
{
  // get the iterator to the specified time instant
  LoadEnumToDVTimeMap::iterator load_enum_it, load_enum_end;
  load_enum_it = this->time_load_ID_map.find(load_enum_ID);
  load_enum_end = this->time_load_ID_map.end();
  if (load_enum_it == load_enum_end)
    load_enum_it = this->time_load_ID_map.insert
      (LoadEnumToDVTimeMap::value_type(load_enum_ID, DVToTimeLoadFactorValueMap::map())).first;
  // get the iterator for the specified time instant
  DVToTimeLoadFactorValueMap::iterator DV_it, DV_end;
  DV_it = load_enum_it->second.find(DV_ID);
  DV_end = load_enum_it->second.end();
  if(DV_it == DV_end)
    DV_it = load_enum_it->second.insert
      (DVToTimeLoadFactorValueMap::value_type(DV_ID, TimeToLoadFactorValuePairMap::map())).first;
  // get the iterators for the load enum from this
  TimeToLoadFactorValuePairMap::iterator time_it, time_end;
  time_it = DV_it->second.find(time_value);
  time_end = DV_it->second.end();
  // duplicate time value specifies
  AssertThrow(time_it == time_end,  ExcInternalError());
  DV_it->second.insert
    (TimeToLoadFactorValuePairMap::value_type(time_value, std::pair<unsigned int, double>
                                              (load_set_ID, load_factor)));
}
void TimeDependentLoadCase::addLoadSetID (const unsigned int load_enum_ID, const unsigned int load_set_ID, const unsigned int load_factor_ID, const unsigned int DV_ID)
this will add a loadset with its reference tag to a specified time instant. If the specified time instant does not exist, this method will create it and add the load
Definition at line 288 of file LoadCase.C.
References load_factor_dependent_load_ID_map.
{
  // get the iterator for the specified time instant
  LoadEnumToLoadFactorIDMap::iterator load_enum_it, load_enum_end;
  load_enum_it = this->load_factor_dependent_load_ID_map.find(load_enum_ID);
  load_enum_end = this->load_factor_dependent_load_ID_map.end();
  if(load_enum_it == load_enum_end)
    load_enum_it = this->load_factor_dependent_load_ID_map.insert
      (LoadEnumToLoadFactorIDMap::value_type(load_enum_ID, DVToLoadFactorIDPairMap::map())).first;
  // get the iterators for the load enum from this
  DVToLoadFactorIDPairMap::iterator DV_it, DV_end;
  DV_it = load_enum_it->second.find(DV_ID);
  DV_end = load_enum_it->second.end();
  AssertThrow(DV_it == DV_end,  FESystemExceptions::ExcDuplicateID("Design Variable for Load Set",
                                                                   DV_ID));
  load_enum_it->second.insert
    (DVToLoadFactorIDPairMap::value_type(DV_ID, std::pair<unsigned int, unsigned int>
                                         (load_set_ID, load_factor_ID)));
}
void TimeDependentLoadCase::clear () [virtual]
clears the data structures for this object
Reimplemented from LoadCaseBase.
Definition at line 226 of file LoadCase.C.
References load_factor_dependent_load_ID_map, and time_load_ID_map.
{
  this->load_factor_dependent_load_ID_map.clear();
  this->time_load_ID_map.clear();
  LoadCaseBase::clear();
}
unsigned int TimeDependentLoadCase::getLoadCaseKindEnumID () const [virtual]
Returns:
the load case kind
Implements LoadCaseBase.
Definition at line 236 of file LoadCase.C.
{
  return TRANSIENT_LOAD_CASE::num();
}
void TimeDependentLoadCase::getLoadFactorLoadSetPair (const Loads::LoadDataInfoBase & load_info, std::vector< std::pair< unsigned int, double > > & load_pair) const [virtual]
fills the vector with the load set ID and its load factor
Implements LoadCaseBase.
Definition at line 398 of file LoadCase.C.
References Loads::LoadDataInfoBase::getDVID(), Loads::LoadDataInfoBase::getLoadNameEnumID(), Loads::LoadDataInfoBase::getTime(), Loads::LoadDataInfoBase::ifSensitivity(), Loads::LoadDataInfoBase::ifTimeDependent(), and FESystemNumbers::InvalidID.
{
  Assert(load_info.ifTimeDependent(), ExcInternalError());
  load_pair.clear();
  unsigned int DV_ID = FESystemNumbers::InvalidID;
  if (load_info.ifSensitivity())
    DV_ID = load_info.getDVID();
  this->getLoadPair(load_info.getTime(),
                    load_info.getLoadNameEnumID(),
                    DV_ID,
                    load_pair);
}
void TimeDependentLoadCase::getLoadPair (const double time, const unsigned int load_enum_ID, const unsigned int DV_ID, std::vector< std::pair< unsigned int, double > > & load_pair) const [protected]
fills the vector with the load pair
Definition at line 418 of file LoadCase.C.
References FESystem::FESystemController::function_database, LoadDatabase::getFESystemController(), LoadCaseBase::load_database, load_factor_dependent_load_ID_map, and time_load_ID_map.
{
  load_pair.clear();
  // find where the load exists: in the time loads, or the load factor loads
  // first check in the load factor based load
  // get the iterator for the specified time instant
  LoadEnumToLoadFactorIDMap::const_iterator load_enum_it, load_enum_end;
  load_enum_it = this->load_factor_dependent_load_ID_map.find(load_enum_ID);
  load_enum_end = this->load_factor_dependent_load_ID_map.end();
  if (load_enum_it != load_enum_end) // implies that the load exists in this map
    {
      // check for the DV
      DVToLoadFactorIDPairMap::const_iterator DV_it, DV_end;
      DV_it = load_enum_it->second.find(DV_ID);
      DV_end = load_enum_it->second.end();
      if (DV_it == DV_end)
        return;
      // get the function from the function database, and add the value to the pair
      double value = 0.0;
      this->load_database.getFESystemController().function_database->getScalarFunctionValue
        (DV_it->second.second, time_value, value);
      // If the code gets here, then a valid iterator has been found
      load_pair.push_back(std::pair<unsigned int, double>(DV_it->second.first, value));
    }
  // check for the load in the time dependent load. If the specified time instant does not exist in
  // the map, then the loads are interpolated
  // get the iterator to the specified time instant
  {
    LoadEnumToDVTimeMap::const_iterator load_enum_it, load_enum_end;
    load_enum_it = this->time_load_ID_map.find(load_enum_ID);
    load_enum_end = this->time_load_ID_map.end();
    if (load_enum_it == load_enum_end)
      return;
    // get the iterator for the specified time instant
    DVToTimeLoadFactorValueMap::const_iterator DV_it, DV_end;
    DV_it = load_enum_it->second.find(DV_ID);
    DV_end = load_enum_it->second.end();
    if(DV_it == DV_end)
      return;
    // get the iterators for the load enum from this
    TimeToLoadFactorValuePairMap::const_iterator time_it, time_end;
    time_it = DV_it->second.find(time_value);
    time_end = DV_it->second.end();
    // if the time value does not exist, then the load needs to be interpolated.
    if (time_it == time_end)
      Assert(false, ExcInternalError()); // needs to be implemented
  }
}
bool TimeDependentLoadCase::ifLoadFactorDependent (unsigned int load_enum_ID)
Returns:
true if the specified load enum ID is load factor dependent
std::istream & TimeDependentLoadCase::readFromInputStream (std::istream & input) [virtual]
this method reads the load case data from the input stream
Implements LoadCaseBase.
Definition at line 320 of file LoadCase.C.
References addLoadSetID(), FESystemNumbers::InvalidID, LoadCaseBase::load_case_ID, and FESystemIOUtility::readFromInput().
{
  std::string tag;
  unsigned int n_time_instants=0, n_load_sets=0, n_DV=0, load_set_ID,
    n_load_factor_vals =0, load_factor_ID;
  double load_factor = 0.0;
  // the input should begin with BEGIN
  FESystemIOUtility::readFromInput(input, TRANSIENT_LOAD_CASE::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  // read in the load case ID
  FESystemIOUtility::readFromInput(input, "ID", this->load_case_ID);
  // read in the number of time instants and the number of loadsets defined for
  // each time instant. The same loads will have to be redefined at each time instant
  FESystemIOUtility::readFromInput(input, "N_TRANSIENT_LOAD_FACTOR_DEPENDENT_LOAD_SETS", n_load_factor_vals);
  FESystemIOUtility::readFromInput(input, "N_TIME_INSTANTS", n_time_instants);
  FESystemIOUtility::readFromInput(input, "N_DESIGN_VARIABLES", n_DV);
  // for each time instant, read in the time value, the loadset tags and IDs
  double time=0.0;
  unsigned int load_enum_ID = 0, DV_ID = FESystemNumbers::InvalidID;
  for (unsigned int dv_it= 0; dv_it <= n_DV; dv_it++)
    {
    // apart from the first data set, all other will be for a specific design variable
      if (dv_it > 0)
        {
          FESystemIOUtility::readFromInput(input, "DESIGN_VARIABLE", DV_ID);
          // no given IDs should equal the invalid ID of FESystem
          AssertThrow(DV_ID != FESystemNumbers::InvalidID, ExcInternalError());
          FESystemIOUtility::readFromInput(input, "N_LOAD_SETS", n_load_factor_vals);
        }
      // iterate over all load factor dependent load sets and store them
      for (unsigned int nl_sets =0; nl_sets < n_load_factor_vals; nl_sets++)
        {
          input >> tag;
          load_enum_ID = LoadNameEnum::enumID(tag);
          input >> load_factor_ID;
          input >> load_set_ID;
          this->addLoadSetID(load_enum_ID, load_set_ID, load_factor_ID, DV_ID);
        }
      for (unsigned int time_incr=0; time_incr < n_time_instants; time_incr++)
        {
          FESystemIOUtility::readFromInput(input, "TIME_INSTANT", time);
          FESystemIOUtility::readFromInput(input, "N_LOAD_SETS", n_load_sets);
          for (unsigned int load_set_incr=0; load_set_incr < n_load_sets; load_set_incr++)
            {
              input >> tag; //load set name
              load_enum_ID = LoadNameEnum::enumID(tag);
              input >> load_factor;
              input >> load_set_ID; // load set ID
              this->addLoadSetID(time, load_enum_ID, load_set_ID, load_factor, DV_ID);
              tag.clear();
            }
        }
    }
  // the input should end with END
  FESystemIOUtility::readFromInput(input, TRANSIENT_LOAD_CASE::name());
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Member Data Documentation
LoadEnumToLoadFactorIDMap TimeDependentLoadCase::load_factor_dependent_load_ID_map [protected]
this stores the load set IDs for loads associated with a time dependent load factor
Definition at line 221 of file LoadCase.h.
Referenced by addLoadSetID(), clear(), and getLoadPair().
LoadEnumToDVTimeMap TimeDependentLoadCase::time_load_ID_map [protected]
this will store the LoadSetIDs for each time instant. At each time instant, multiple kinds of loads can exist. The LoadSetIDMap stores these as a tag to LoadSetID map
Definition at line 226 of file LoadCase.h.
Referenced by addLoadSetID(), clear(), and getLoadPair().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCase.C