fesystem: FESystemDatabase::DataInfoBase Class Reference
FESystemDatabase::DataInfoBase Class Reference
#include <DataInfo.h>
Public Member Functions
DataInfoBase ()
constructor
DataInfoBase (const DataInfoBase &data_info)
copy constructor
virtual ~DataInfoBase ()
Destructor.
virtual unsigned int getDataInfoKindEnumID () const =0
virtual const std::string getPath () const =0
virtual bool operator== (const FESystemDatabase::DataInfoBase &data_info) const
Detailed Description
this id the base class for all data info objects. The primary purpose of the data info objects is to give information about a numeric object (matrix/vector) about its kind, the time iteration and time value, nonlinear iteration, etc. and all such details that are necessary to property store the object.
Definition at line 186 of file DataInfo.h.
Constructor & Destructor Documentation
FESystemDatabase::DataInfoBase::DataInfoBase ()
constructor
Definition at line 217 of file DataInfo.C.
                                          :
  FESystemDatabase::GenericDataInfoBase()
{
}
FESystemDatabase::DataInfoBase::DataInfoBase (const DataInfoBase & data_info)
copy constructor
Definition at line 226 of file DataInfo.C.
                               :
  FESystemDatabase::GenericDataInfoBase(data_info)
{
}
FESystemDatabase::DataInfoBase::~DataInfoBase () [virtual]
Destructor.
Definition at line 234 of file DataInfo.C.
{
}
Member Function Documentation
virtual unsigned int FESystemDatabase::DataInfoBase::getDataInfoKindEnumID () const [pure virtual]
Returns:
the enumeration ID of the kind of the data
Implemented in FESystemDatabase::TimeDependentEigenDataInfo, FESystemDatabase::TimeIndependentEigenDataInfo, FESystemDatabase::TimeDependentDataInfo, and FESystemDatabase::TimeIndependentDataInfo.
Referenced by FESystemDatabase::createDataInfoCopy(), and operator==().
virtual const std::string FESystemDatabase::DataInfoBase::getPath () const [pure virtual]
Returns:
the exact path to the location of the data for this object in the database
Implemented in FESystemDatabase::TimeDependentEigenDataInfo, FESystemDatabase::TimeIndependentEigenDataInfo, FESystemDatabase::TimeDependentDataInfo, and FESystemDatabase::TimeIndependentDataInfo.
Referenced by FESystemDatabase::GlobalDataStorage::asciiStore(), FESystemDatabase::GlobalDataStorage::checkIfQtyExists(), FESystemDatabase::GlobalDataStorage::fillMatrix(), FESystemDatabase::GlobalDataStorage::fillVector(), FESystemDatabase::GlobalDataStorage::storeMatrix(), and FESystemDatabase::GlobalDataStorage::storeVector().
bool FESystemDatabase::DataInfoBase::operator== (const FESystemDatabase::DataInfoBase & data_info) const [virtual]
Returns:
true if the given data info object and this, point to the same data
Reimplemented in FESystemDatabase::TimeDependentEigenDataInfo, FESystemDatabase::TimeIndependentEigenDataInfo, FESystemDatabase::TimeDependentDataInfo, and FESystemDatabase::TimeIndependentDataInfo.
Definition at line 243 of file DataInfo.C.
References getDataInfoKindEnumID(), and FESystemDatabase::GenericDataInfoBase::isEqual().
{
  return (FESystemDatabase::GenericDataInfoBase::isEqual(data_info) &&
          this->getDataInfoKindEnumID() == data_info.getDataInfoKindEnumID());
}
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.C