fesystem: FESystemDatabase::GlobalDataStorage Class Reference
FESystemDatabase::GlobalDataStorage Class Reference
#include <GlobalDataStorage.h>
Public Member Functions
GlobalDataStorage (FESystem::FESystemController &fesystem, const std::string &name)
~GlobalDataStorage ()
void clear ()
template<class MatrixType >
void storeMatrix (const FESystemDatabase::DataInfoBase &data_info, MatrixType &)
template<class VectorType >
void storeVector (const FESystemDatabase::DataInfoBase &data_info, VectorType &)
template<class DataType >
void asciiStore (const FESystemDatabase::DataInfoBase &data_info, DataType &)
template<class MatrixType >
void fillMatrix (const FESystemDatabase::DataInfoBase &data_info, MatrixType &)
template<class VectorType >
void fillVector (const FESystemDatabase::DataInfoBase &data_info, VectorType &)
bool checkIfQtyExists (const FESystemDatabase::DataInfoBase &data_info)
template<>
void storeMatrix (const FESystemDatabase::DataInfoBase &data_info, SparseMatrix< double > &matrix)
template<>
void storeVector (const FESystemDatabase::DataInfoBase &data_info, NumericVector< double > &vector)
template<>
void fillMatrix (const FESystemDatabase::DataInfoBase &data_info, SparseMatrix< double > &matrix)
template<>
void fillVector (const FESystemDatabase::DataInfoBase &data_info, NumericVector< double > &vector)
Private Member Functions
void storeMatrixToHDF5 (const std::string &file_name, const unsigned int m, const unsigned int n, const double *mat_data, const bool if_overwrite)
void fillMatrixFromHDF5 (const std::string &file_name, unsigned int &m, unsigned int &n, double **mat_data)
Private Attributes
FESystem::FESystemController & fesystem_controller
reference to the FESystemController object
std::string database_name
name of the HDF5 database name
unsigned int hdf5_file_id
HDF5 database file id.
std::set< std::string > stored_quantity
map to keep track of quantities that have been stored in the database
Detailed Description
this class will store all the calculated element quantities for use in the assembly and sensitivity analysis process
Definition at line 38 of file GlobalDataStorage.h.
Constructor & Destructor Documentation
FESystemDatabase::GlobalDataStorage::GlobalDataStorage (FESystem::FESystemController & fesystem, const std::string & name)
Definition at line 24 of file GlobalDataStorage.C.
References FESystem::total_processors.
                       :
fesystem_controller(fesystem),
database_name(name),
hdf5_file_id(FESystemNumbers::InvalidID)
{
  // first create a CREATION property list
  int creation_property_list_id = H5Pcreate(H5P_FILE_CREATE);
  // and an ACCESS property list
  int access_property_list_id = H5Pcreate(H5P_FILE_ACCESS);
  // if only one processor is being used, then a local accessible file can be created,
  // otherwise, the file needs to be opened with parallel access.
  if (FESystem::total_processors > 1)
    {
//      hid_t ierr = H5Pset_fapl_mpio(access_property_list_id,
//                                    FESystem::COMM_WORLD,
//                                    FESystem::MPI_INFO);
//      AssertThrow (ierr >= 0, ExcInternalError());
                AssertThrow (false, ExcInternalError());
    }
  // now, using the creation and access property list, create a file
  this->hdf5_file_id = H5Fcreate(this->database_name.c_str(),
                                 H5F_ACC_TRUNC,
                                 creation_property_list_id,
                                 access_property_list_id);
  // make sure that the file was created without problems.
  AssertThrow (this->hdf5_file_id > 0, ExcInternalError());
  // now destroy the property lists
  int ierr = 0;
  ierr = H5Pclose(creation_property_list_id);
  AssertThrow (ierr >= 0, ExcInternalError());
  ierr = H5Pclose(access_property_list_id);
  AssertThrow (ierr >= 0, ExcInternalError());
}
FESystemDatabase::GlobalDataStorage::~GlobalDataStorage ()
Definition at line 69 of file GlobalDataStorage.C.
References hdf5_file_id.
{
  // close the HDF5 file
  int ierr = 0;
  ierr = H5Fclose(this->hdf5_file_id);
  AssertThrow (ierr >= 0, ExcInternalError());
}
Member Function Documentation
template<class DataType > void FESystemDatabase::GlobalDataStorage::asciiStore (const FESystemDatabase::DataInfoBase & data_info, DataType & matrix)
stores the matrix in an ascii format. the arguements are
Parameters:
load case number
matrix name
matrix to be stored
Definition at line 141 of file GlobalDataStorage.h.
References FESystemDatabase::DataInfoBase::getPath().
    {
      std::string file_name = data_info.getPath();
      std::fstream output;
      output.open(file_name.c_str(), std::fstream::out);
      // write the matrix elements to the file
      output << matrix;
      // close the file stream
      output.close();
    }
bool FESystemDatabase::GlobalDataStorage::checkIfQtyExists (const FESystemDatabase::DataInfoBase & data_info)
checks if the matrix exists, and returns it as a boolean. the input arguements are
Parameters:
load case number,
matrix name
Definition at line 82 of file GlobalDataStorage.C.
References FESystemDatabase::DataInfoBase::getPath().
Referenced by fillMatrix(), fillVector(), FESystemUtility::LoadedSolution::loadSolutionFromDatabase(), storeMatrix(), and storeVector().
{
  std::string file_name = data_info.getPath();
  unsigned int count = this->stored_quantity.count(file_name);
  if (count == 0)
    return false;
  else
    return true;
}
void FESystemDatabase::GlobalDataStorage::clear ()
function to clear the data stored
template<typename MatrixType > void FESystemDatabase::GlobalDataStorage::fillMatrix (const FESystemDatabase::DataInfoBase & data_info, MatrixType & matrix)
function to get a quantity from the stored data
Definition at line 247 of file GlobalDataStorage.h.
References checkIfQtyExists(), fillMatrixFromHDF5(), FESystemDatabase::DataInfoBase::getPath(), and n.
    {
      // make sure that the data has been stored earlier
      Assert(this->checkIfQtyExists(data_info), ExcInternalError());
      std::string file_name = data_info.getPath();
      // create an array and copy the values in it
      unsigned int m, n;
      double* vals = NULL;
      this->fillMatrixFromHDF5(file_name, m, n, &vals);
      Assert(vals != NULL, ExcInternalError());
      if (matrix.m() != m || matrix.n() != n)
        matrix.resize(m,n);
      for (unsigned int i=0; i<m; i++)
        for (unsigned int j=0; j<n; j++)
          matrix.set(i, j, *(vals+(i*n+j)));
      delete[] vals;
    }
template<> void FESystemDatabase::GlobalDataStorage::fillMatrix (const FESystemDatabase::DataInfoBase & data_info, SparseMatrix< double > & matrix) [inline]
Definition at line 313 of file GlobalDataStorage.h.
References checkIfQtyExists(), and FESystemDatabase::DataInfoBase::getPath().
    {
      // make sure that the data has been stored earlier
      Assert(this->checkIfQtyExists(data_info), ExcInternalError());
      std::string file_name = data_info.getPath();
      // make sure that the file exists
      matrix.load_from_binary_file(file_name);
    }
void FESystemDatabase::GlobalDataStorage::fillMatrixFromHDF5 (const std::string & file_name, unsigned int & m, unsigned int & n, double ** mat_data) [private]
this method stores a given array to the HDF5 database file. This can be used for both vectors and matrices. For vectors, specify the second dimension as 1. The user should now have any data pointed to by mat_data. Upon return, the matrix pointer mat_data will have a newly created array of data of the same dimensions as mxn. This should be deleted by user.
Definition at line 163 of file GlobalDataStorage.C.
References n.
Referenced by fillMatrix(), and fillVector().
{
//      std::string file_name = this->createName(load_case_ID, quantity);
  hid_t ndims = 0, dataspace_id=0, dataset_id=0, transfer_property_id =0,
    ierr = 0;
  // open dataset
  dataset_id = H5Dopen1(this->hdf5_file_id, file_name.c_str());
  AssertThrow (dataset_id > 0, ExcInternalError());
  // get the dataspace for this dataset
  dataspace_id = H5Dget_space(dataset_id);
  AssertThrow (dataspace_id > 0, ExcInternalError());
  // get the dimesnsion of the stored matrix, and make sure that the dimensions agree
  // with the matrix
  ndims = H5Sget_simple_extent_ndims(dataspace_id);
  AssertThrow (ndims == 2, ExcInternalError());
  hsize_t dims[2];
  ierr = H5Sget_simple_extent_dims(dataspace_id, dims,NULL);
  AssertThrow (ierr >= 0, ExcInternalError());
  m = dims[0];
  n = dims[1];
  *mat_data = new double[m*n];
  // create transfer property list
  transfer_property_id = H5Pcreate(H5P_DATASET_XFER);
  AssertThrow (transfer_property_id > 0, ExcInternalError());
  // read dataset
  ierr = H5Dread(dataset_id, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL,
                  transfer_property_id, *mat_data);
  AssertThrow (ierr >= 0, ExcInternalError());
  // destroy the objects created
  ierr = H5Pclose(transfer_property_id);   AssertThrow (ierr >= 0, ExcInternalError());
  ierr = H5Sclose(dataspace_id);   AssertThrow (ierr >= 0, ExcInternalError());
  ierr = H5Dclose(dataset_id);   AssertThrow (ierr >= 0, ExcInternalError());
}
template<typename VectorType > void FESystemDatabase::GlobalDataStorage::fillVector (const FESystemDatabase::DataInfoBase & data_info, VectorType & vector)
function to get a quantity from the stored data
Definition at line 188 of file GlobalDataStorage.h.
References checkIfQtyExists(), fillMatrixFromHDF5(), and FESystemDatabase::DataInfoBase::getPath().
Referenced by FESystemUtility::LoadedSolution::loadSolutionFromDatabase().
    {
      // make sure that the data has been stored earlier
      Assert(this->checkIfQtyExists(data_info), ExcInternalError());
      std::string file_name = data_info.getPath();
      // create an array and copy the values in it
      unsigned int n_vals, tmp;
      double *vals = NULL;
      this->fillMatrixFromHDF5(file_name, n_vals, tmp, &vals);
      Assert(tmp == 1, ExcInternalError());
      Assert(vals != NULL, ExcInternalError());
      if (vector.size() != n_vals)
        vector.resize(n_vals);
      for (unsigned int i=0; i<n_vals; i++)
        vector.set(i, *(vals+i));
      delete[] vals;
    }
template<> void FESystemDatabase::GlobalDataStorage::fillVector (const FESystemDatabase::DataInfoBase & data_info, NumericVector< double > & vector) [inline]
Definition at line 330 of file GlobalDataStorage.h.
References checkIfQtyExists(), and FESystemDatabase::DataInfoBase::getPath().
    {
      // make sure that the data has been stored earlier
      Assert(this->checkIfQtyExists(data_info), ExcInternalError());
      std::string file_name = data_info.getPath();
      // make sure that the file exists
      vector.load_from_binary_file(file_name);
    }
template<typename MatrixType > void FESystemDatabase::GlobalDataStorage::storeMatrix (const FESystemDatabase::DataInfoBase & data_info, MatrixType & matrix)
stores the matrix in a PETSC binary format. the arguements are
Parameters:
load case number
matrix name
matrix to be stored
Definition at line 217 of file GlobalDataStorage.h.
References checkIfQtyExists(), FESystemDatabase::DataInfoBase::getPath(), n, stored_quantity, and storeMatrixToHDF5().
    {
      std::string file_name = data_info.getPath();
      // create an array and copy the values in it
      unsigned int m = matrix.m(), n = matrix.n();
      double* vals = new double[m*n];
      for (unsigned int i=0; i<m; i++)
        for (unsigned int j=0; j<n; j++)
          vals[i*n+j] = matrix.el(i,j);
      bool if_overwrite = false;
      if (this->checkIfQtyExists(data_info))
        if_overwrite = true;
      this->storeMatrixToHDF5(file_name, m, n, &(vals[0]), if_overwrite);
      delete[] vals;
      // record the name in the map, if it already does not exist
      if ( ! this->checkIfQtyExists(data_info))
        this->stored_quantity.insert(file_name);
    }
template<> void FESystemDatabase::GlobalDataStorage::storeMatrix (const FESystemDatabase::DataInfoBase & data_info, SparseMatrix< double > & matrix) [inline]
Definition at line 279 of file GlobalDataStorage.h.
References checkIfQtyExists(), FESystemDatabase::DataInfoBase::getPath(), and stored_quantity.
    {
      std::string file_name = data_info.getPath();
      matrix.write_to_binary_file(file_name);
      // record the name in the map, if it already does not exist
      if ( ! this->checkIfQtyExists(data_info))
        this->stored_quantity.insert(file_name);
    }
void FESystemDatabase::GlobalDataStorage::storeMatrixToHDF5 (const std::string & file_name, const unsigned int m, const unsigned int n, const double * mat_data, const bool if_overwrite) [private]
this method stores a given array to the HDF5 database file. This can be used for both vectors and matrices. For vectors, specify the second dimension as 1.
Definition at line 98 of file GlobalDataStorage.C.
References n.
Referenced by storeMatrix(), and storeVector().
{
        // write this matrix to the hdf5 database file
  hid_t property_id = 0, dataspace_id=0, dataset_id=0, transfer_property_id =0,
    ierr = 0;
  // create dataset creation property list
  property_id = H5Pcreate(H5P_DATASET_CREATE);
  AssertThrow (property_id > 0, ExcInternalError());
  // set layout to contiguous data
  ierr = H5Pset_layout(property_id,H5D_CONTIGUOUS);
  AssertThrow(ierr >= 0, ExcInternalError());
  // fill value is left at 0.0, which is default
  // this also lets HDF5 handle the fill time at default
  // alloc time is also left to default
  // create dataspace
  hsize_t dims[2];
  dims[0] = m;
  dims[1] = n;
  dataspace_id = H5Screate_simple(2, dims, NULL);
  AssertThrow (dataspace_id > 0, ExcInternalError());
  // create dataset
  if (!if_overwrite)
    {
    dataset_id = H5Dcreate1(this->hdf5_file_id, file_name.c_str(), H5T_NATIVE_DOUBLE,
                           dataspace_id, property_id);
    AssertThrow (dataset_id > 0, ExcInternalError());
    }
  else
    {
    dataset_id  = H5Dopen1(this->hdf5_file_id, file_name.c_str());
    AssertThrow (dataset_id > 0, ExcInternalError());
    }
  // create transfer property list
  transfer_property_id = H5Pcreate(H5P_DATASET_XFER);
  AssertThrow (transfer_property_id > 0, ExcInternalError());
  // write dataset
  ierr = H5Dwrite(dataset_id, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL,
                  transfer_property_id, mat_data);
  AssertThrow (ierr >= 0, ExcInternalError());
  // destroy the objects created
  ierr = H5Pclose(property_id);   AssertThrow (ierr >= 0, ExcInternalError());
  ierr = H5Pclose(transfer_property_id);   AssertThrow (ierr >= 0, ExcInternalError());
  ierr = H5Sclose(dataspace_id);   AssertThrow (ierr >= 0, ExcInternalError());
  ierr = H5Dclose(dataset_id);   AssertThrow (ierr >= 0, ExcInternalError());
}
template<typename VectorType > void FESystemDatabase::GlobalDataStorage::storeVector (const FESystemDatabase::DataInfoBase & data_info, VectorType & vector)
stores the vector in an ascii format. the arguements are
Parameters:
load case number
matrix name
matrix to be stored
Definition at line 160 of file GlobalDataStorage.h.
References checkIfQtyExists(), FESystemDatabase::DataInfoBase::getPath(), stored_quantity, and storeMatrixToHDF5().
    {
      std::string file_name = data_info.getPath();
      // create an array and copy the values in it
      unsigned int n_vals = vector.size();
      double* vals = new double[n_vals];
      for (unsigned int i=0; i<n_vals; i++)
        vals[i] = vector.el(i);
      bool if_overwrite = false;
      if (this->checkIfQtyExists(data_info))
        if_overwrite = true;
      this->storeMatrixToHDF5(file_name, n_vals, 1, &(vals[0]), if_overwrite);
      delete[] vals;
      // record the name in the map, if it already does not exist
      if ( ! this->checkIfQtyExists(data_info))
        this->stored_quantity.insert(file_name);
    }
template<> void FESystemDatabase::GlobalDataStorage::storeVector (const FESystemDatabase::DataInfoBase & data_info, NumericVector< double > & vector) [inline]
Definition at line 296 of file GlobalDataStorage.h.
References checkIfQtyExists(), FESystemDatabase::DataInfoBase::getPath(), and stored_quantity.
    {
      std::string file_name = data_info.getPath();
      vector.write_to_binary_file(file_name);
      // record the name in the map, if it already does not exist
      if ( ! this->checkIfQtyExists(data_info))
        this->stored_quantity.insert(file_name);
    }
Member Data Documentation
std::string FESystemDatabase::GlobalDataStorage::database_name [private]
name of the HDF5 database name
Definition at line 126 of file GlobalDataStorage.h.
FESystem::FESystemController& FESystemDatabase::GlobalDataStorage::fesystem_controller [private]
reference to the FESystemController object
Definition at line 123 of file GlobalDataStorage.h.
unsigned int FESystemDatabase::GlobalDataStorage::hdf5_file_id [private]
HDF5 database file id.
Definition at line 129 of file GlobalDataStorage.h.
Referenced by ~GlobalDataStorage().
std::set<std::string> FESystemDatabase::GlobalDataStorage::stored_quantity [private]
map to keep track of quantities that have been stored in the database
Definition at line 132 of file GlobalDataStorage.h.
Referenced by storeMatrix(), and storeVector().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/GlobalDataStorage.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/GlobalDataStorage.C