fesystem: Solution::TransientStructuralSolution Class Reference
Solution::TransientStructuralSolution Class Reference
this class provides the base functionality for all solutions
#include <TransientStructuralSolution.h>
Public Member Functions
TransientStructuralSolution ()
constructor
virtual ~TransientStructuralSolution ()
destructor
virtual void solve ()
solves the problem
virtual unsigned int getDisciplineTransientNatureEnumID (const unsigned int discipline) const
virtual
FESystemUtility::AutoPtrVector
< FESystemDatabase::DataInfoBase > getTimeIndependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID)
virtual
FESystemUtility::AutoPtrVector
< FESystemDatabase::TransientDataInfoSet > getTimeDependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID)
virtual std::istream & readFromInputStream (std::istream &input)
will read from the input stream
Detailed Description
this class provides the base functionality for all solutions
Definition at line 42 of file TransientStructuralSolution.h.
Constructor & Destructor Documentation
Solution::TransientStructuralSolution::TransientStructuralSolution ()
constructor
Definition at line 14 of file TransientStructuralSolution.C.
References Solution::SolutionBase::addParticipatingDiscipline().
                                                                :
Solution::SolutionBase(Solution::TRANSIENT_STRUCTURAL_SOLUTION::num())
{
  // add the participating discipline to this solution
  this->addParticipatingDiscipline(Discipline::STRUCTURAL_DISCIPLINE::num());
}
Solution::TransientStructuralSolution::~TransientStructuralSolution () [virtual]
destructor
Definition at line 23 of file TransientStructuralSolution.C.
{
}
Member Function Documentation
unsigned int Solution::TransientStructuralSolution::getDisciplineTransientNatureEnumID (const unsigned int discipline) const [virtual]
Returns:
the transient nature of the given discipline
Implements Solution::SolutionBase.
Definition at line 32 of file TransientStructuralSolution.C.
References STRUCTURAL_DISCIPLINE_ENUM_ID.
{
  unsigned int enum_ID = 0;
  switch (discipline)
    {
    case STRUCTURAL_DISCIPLINE_ENUM_ID:
      enum_ID = Discipline::TRANSIENT_SOLUTION::num();
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return enum_ID;
}
FESystemUtility::AutoPtrVector< FESystemDatabase::TransientDataInfoSet > Solution::TransientStructuralSolution::getTimeDependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID) [virtual]
Returns:
the vector of SolNameInfo structures for the nodal solutions, and for the specified disciplines
Implements Solution::SolutionBase.
Definition at line 135 of file TransientStructuralSolution.C.
References FESystemNumerics::PetscVectorBase< T >::el(), FESystemUtility::AutoPtrVector< T >::push_back(), FESystemNumerics::PetscSeqVector< T >::resize(), FESystemDatabase::GenericDataInfoBase::setDisciplineEnumID(), FESystemDatabase::GenericDataInfoBase::setDVID(), FESystemDatabase::GenericDataInfoBase::setLoadCase(), FESystemDatabase::GenericDataInfoBase::setName(), FESystemDatabase::TransientDataInfoSet::setOrder(), FESystemDatabase::TransientDataInfoSet::setTransientIterationTimeVector(), FESystemNumerics::PetscVectorBase< T >::size(), and STRUCTURAL_DISCIPLINE_ENUM_ID.
{
  // this solution does not have any transients. Hence, return an empty vector
  FESystemUtility::AutoPtrVector<FESystemDatabase::TransientDataInfoSet> data_info_vec;
  FESystemDatabase::TransientDataInfoSet* data_info_set = NULL;
  switch (discipline_enum_ID)
    {
    case STRUCTURAL_DISCIPLINE_ENUM_ID:
      {
        std::auto_ptr<std::vector<DesignData::DesignParameter*> >
        dv_vector(this->fesystem_controller->design_database->getParameters().release());
        // get the time values for the solution
        FESystemDatabase::TimeIndependentDataInfo data_info;
        FESystemNumerics::PetscSeqVector<double> vec;
        std::vector<double> time_values;
        // iterate over each load case and DV and add the solutions
        for (unsigned int i=0; i < this->load_case_IDs.size(); i++)
          {
          data_info.clear();
          data_info.setDisciplineEnumID(Discipline::STRUCTURAL_DISCIPLINE::num());
          data_info.setName("TimeValues");
          data_info.setLoadCase(this->load_case_IDs[i]);
          this->fesystem_controller->global_data_storage->fillVector(data_info, vec);
          time_values.resize(vec.size());
          for (unsigned int k=0; k < vec.size(); k++)
            time_values[k] = vec.el(k);
          data_info_set = new FESystemDatabase::TransientDataInfoSet;
          data_info_set->setDisciplineEnumID(Discipline::STRUCTURAL_DISCIPLINE::num());
          data_info_set->setName("Solution");
          data_info_set->setLoadCase(this->load_case_IDs[i]);
          data_info_set->setOrder(0);
          data_info_set->setTransientIterationTimeVector(time_values);
          data_info_vec.push_back(data_info_set);
          data_info_set = NULL;
          for (unsigned int j=0; j < dv_vector->size(); j++)
            {
            data_info_set = new FESystemDatabase::TransientDataInfoSet;
            data_info_set->setDisciplineEnumID(Discipline::STRUCTURAL_DISCIPLINE::num());
            data_info_set->setName("Solution");
            data_info_set->setLoadCase(this->load_case_IDs[i]);
            data_info_set->setOrder(0);
            data_info_set->setDVID((*dv_vector)[j]->getID());
            data_info_set->setTransientIterationTimeVector(time_values);
            data_info_vec.push_back(data_info_set);
            data_info_set = NULL;
            }
          }
      }
        break;
        default:
          Assert(false, ExcInternalError());
    }
  return data_info_vec;
}
FESystemUtility::AutoPtrVector< FESystemDatabase::DataInfoBase > Solution::TransientStructuralSolution::getTimeIndependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID) [virtual]
Returns:
the vector of SolNameInfo structures for the nodal solutions, and for the specified disciplines
Implements Solution::SolutionBase.
Definition at line 120 of file TransientStructuralSolution.C.
{
  // unused parameter
  (void) discipline_enum_ID;
  FESystemUtility::AutoPtrVector<FESystemDatabase::DataInfoBase> data_info_vec;
  return data_info_vec;
}
std::istream & Solution::TransientStructuralSolution::readFromInputStream (std::istream & input) [virtual]
will read from the input stream
Implements Solution::SolutionBase.
Definition at line 75 of file TransientStructuralSolution.C.
References FESystemIOUtility::readFromInput().
{
  std::string tag;
  unsigned int num = 0;
  FESystemIOUtility::readFromInput(input, Solution::SolutionEnum::enumName(this->solution_enum_ID));
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->ID);
  // Read in the list of load cases
  unsigned int case_ID =0;
  FESystemIOUtility::readFromInput(input, "N_ANALYSIS_LOAD_CASES", num);
  for (unsigned int case_it =0; case_it < num; case_it++)
    {
    case_ID = 0;
    input >> case_ID;
    this->load_case_IDs.push_back(case_ID);
    }
  FESystemIOUtility::readFromInput(input, "N_SOLVER_INFO_ID", num);
  unsigned int solver_class = 0, info_id = 0;
  for (unsigned int i=0; i < num; i++)
    {
    tag.clear();
    input >> tag;
    solver_class = Solver::SolverClassEnum::enumID(tag);
    input >> info_id;
    this->addSolverID(solver_class, info_id);
    }
  FESystemIOUtility::readFromInput(input, Solution::SolutionEnum::enumName(this->solution_enum_ID));
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
void Solution::TransientStructuralSolution::solve () [virtual]
solves the problem
Implements Solution::SolutionBase.
Definition at line 52 of file TransientStructuralSolution.C.
References Discipline::DisciplineInfo::getAnalysisTypeEnumID(), info, LINEAR_ANALYSIS_ENUM_ID, and NONLINEAR_ANALYSIS_ENUM_ID.
{
  const Discipline::DisciplineInfo& info =
  this->fesystem_controller->analysis_case->getAnalysisDisciplineInfo
  (Discipline::STRUCTURAL_DISCIPLINE::num());
  switch (info.getAnalysisTypeEnumID())
    {
    case LINEAR_ANALYSIS_ENUM_ID:
      this->linearTransientSolve(Discipline::STRUCTURAL_DISCIPLINE::num());
      break;
    case NONLINEAR_ANALYSIS_ENUM_ID:
    default:
      Assert(false, ExcInternalError());
      break;
    }
}
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solutions/TransientStructuralSolution.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solutions/TransientStructuralSolution.C