fesystem: RadiationCavity Class Reference
RadiationCavity Class Reference
#include <RadiationCavity.h>
Public Member Functions
RadiationCavity ()
constructor
~RadiationCavity ()
destructor
std::istream & readFromInputStream (std::istream &)
method to read from input stream
unsigned int nFiniteElems () const
returns number of finite elems in the cavity
unsigned int getCavityID () const
returns the cavity ID
void setFiniteElementMeshID (unsigned int mesh_ID, unsigned int DV_ID=0)
unsigned int getFiniteElementMeshID (unsigned int DV_ID=0) const
unsigned int nRadiationElems () const
returns the number of radiation elems in the cavity
const std::vector< Node * > & getFENodes (unsigned int DV_ID=0) const
const RadiationElement & getElemFromID (const unsigned int elem_ID, const unsigned int DV_ID=0) const
RadiationCavityFiniteElem & getRadiationCavityFiniteElement (unsigned int elem_ID)
returns the radiation cavity finite element for the given ID
const Elem * getGeometricFE (unsigned int elem_ID, unsigned int DV_ID=0)
Elem * getGeometricRadiationElem (unsigned int elem_ID, unsigned int DV_ID=0)
RadiationElemConstIterator getElemBeginIterator (unsigned int DV_ID=0) const
RadiationElemConstIterator getElemEndIterator (unsigned int DV_ID=0) const
void getInternalNodeIDForRadElem (unsigned int rad_ID, std::vector< unsigned int > &vector)
void setMeshData (MeshDS::FEMeshData *mesh_data, unsigned int DV_ID=0)
MeshDS::FEMeshData * getMeshData (unsigned int DV_ID=0) const
bool ifApproximateABInvFactor () const
boolean about whether to approximate or recalculate ABInv factor
unsigned int getNItertionsToRecalculateABInv () const
unsigned int getNTaylorTermsForABInvApproximation () const
Protected Member Functions
void createFENodeVectorAndRadiationElems (unsigned int DV_ID)
Protected Attributes
unsigned int radiation_cavity_ID
ID of this radiation cavity.
bool if_approximate_AB_inv
if ABinv factor should be approximated? instead of recalculated
unsigned int n_AB_inv_taylor_approx_terms
number of terms to use in the approximation
unsigned int n_iters_before_AB_inv_recalculation
number of iterations before fully recalculating
std::map< unsigned int,
unsigned int > fe_mesh_ID_map
bool initialized
checks if the cavity data has been initialized or not
std::map< unsigned int,MeshDS::FEMeshData * > mesh_data_map
map of mesh data mesh data stored against the shape DV ID
std::map< unsigned int,
RadiationCavityFiniteElem * > ID_to_elem_map
std::map< unsigned int,
unsigned int > foreign_to_local_node_ID
map of foreign node ID to local node ID
std::vector< unsigned int > local_to_foreign_node_ID
std::map< unsigned int,
std::vector< Node * > > local_ID_to_node_map
std::map< unsigned int,
std::vector< RadiationElement * > > rad_elem_vector_map
Detailed Description
Definition at line 26 of file RadiationCavity.h.
Constructor & Destructor Documentation
RadiationCavity::RadiationCavity ()
constructor
Definition at line 19 of file RadiationCavity.C.
                                :
  radiation_cavity_ID(0),
if_approximate_AB_inv(false),
n_AB_inv_taylor_approx_terms(FESystemNumbers::InvalidID),
n_iters_before_AB_inv_recalculation(FESystemNumbers::InvalidID),
initialized(false)
{
}
RadiationCavity::~RadiationCavity ()
destructor
Definition at line 32 of file RadiationCavity.C.
References ID_to_elem_map, and rad_elem_vector_map.
{
  // iterate over all the elements, and delete all of them
  std::map<unsigned int, RadiationCavityFiniteElem*>::iterator
    elem_it , elem_end;
  elem_it = this->ID_to_elem_map.begin();
  elem_end = this->ID_to_elem_map.end();
  for (; elem_it != elem_end; elem_it++)
    {
      delete elem_it->second;
      elem_it->second = NULL;
    }
  this->ID_to_elem_map.clear();
  // node delete the rad elems
  std::map<unsigned int, std::vector<RadiationElement*> >::iterator
    rad_map_it, rad_map_end;
  rad_map_it = this->rad_elem_vector_map.begin();
  rad_map_end = this->rad_elem_vector_map.end();
  for ( ; rad_map_it != rad_map_end; rad_map_it++)
    {
      std::vector<RadiationElement*>::iterator rad_elem_it, rad_elem_end;
      rad_elem_it = rad_map_it->second.begin();
      rad_elem_end = rad_map_it->second.end();
      for (; rad_elem_it != rad_elem_end; rad_elem_it++)
        {
          delete (*rad_elem_it);
        }
      rad_map_it->second.clear();
    }
  this->rad_elem_vector_map.clear();
}
Member Function Documentation
void RadiationCavity::createFENodeVectorAndRadiationElems (unsigned int DV_ID) [protected]
method creates a vector of nodes for finite elements for the specified DV.
Definition at line 137 of file RadiationCavity.C.
References foreign_to_local_node_ID, MeshDS::FEMeshData::getElemFromForeignID(), MeshDS::FEMeshData::getForeignIDFromNode(), getMeshData(), MeshDS::FEMeshData::getNodeFromForeignID(), ID_to_elem_map, initialized, local_ID_to_node_map, local_to_foreign_node_ID, rad_elem_vector_map, and RadiationElement::setData().
Referenced by setMeshData().
{
  // iterate over all finite elems in the cavity
  // get the nodes for the elem. Insert them in the node set
  // once the set has been prepared, put it in the node vector
  // and record its location with each
  std::vector<Node*>* local_ID_to_node_vec = NULL;
  std::vector<RadiationElement*>* rad_elem_vec = NULL;
  MeshDS::FEMeshData* mesh_data = this->getMeshData(DV_ID);
  {
    std::map<unsigned int, std::vector<Node*> >::const_iterator node_map_it =
      this->local_ID_to_node_map.find(DV_ID);
    assert (node_map_it == this->local_ID_to_node_map.end());
    assert(this->local_ID_to_node_map.insert
           (std::map<unsigned int, std::vector<Node*> >::value_type
            (DV_ID, std::vector<Node*>())).second == true);
    local_ID_to_node_vec = &(this->local_ID_to_node_map[DV_ID]);
    std::map<unsigned int, std::vector<RadiationElement*> >::const_iterator rad_elem_map_it =
      this->rad_elem_vector_map.find(DV_ID);
    assert (rad_elem_map_it == this->rad_elem_vector_map.end());
    assert(this->rad_elem_vector_map.insert
           (std::map<unsigned int, std::vector<RadiationElement*> >::value_type
            (DV_ID, std::vector<RadiationElement*>())).second == true);
    rad_elem_vec = &(this->rad_elem_vector_map[DV_ID]);
  }
  Node* node = NULL;
  unsigned int foreign_node_ID = 0, internal_node_ID = 0;
  // only for the base design point, create the vector of local to global and
  // global to local ID maps. Once this is done, the map can be used to
  // create the vector of nodes
  if (DV_ID == 0)
    {
      std::map<unsigned int, RadiationCavityFiniteElem*>::const_iterator it, end;
      it = this->ID_to_elem_map.begin();
      end = this->ID_to_elem_map.end();
      std::map<unsigned int, unsigned int>::iterator node_it;
      for (; it != end; it++)
        {
          const Elem* elem =
            mesh_data->getElemFromForeignID(it->second->elem_ID);
          // the elem can only be a 2-D planar elem
          assert (elem->dim() < 3);
          // iterate over the nodes for this elem
          for (unsigned int i=0; i < elem->n_nodes(); i++)
            {
              node = elem->get_node(i);
              foreign_node_ID = mesh_data->getForeignIDFromNode(node);
              // if this node does not already exist in the map, insert it
              node_it = this->foreign_to_local_node_ID.find(foreign_node_ID);
              if (node_it == this->foreign_to_local_node_ID.end())
                {
                  // push the node in the vectors
                  this->local_to_foreign_node_ID.push_back(foreign_node_ID);
                  bool insert =
                    this->foreign_to_local_node_ID.insert
                    (std::map<unsigned int, unsigned int>::value_type
                     (foreign_node_ID, internal_node_ID)).second;
                  assert (insert == true);
                  internal_node_ID++;
                }
            }
        }
    }
  // now iterate over all the nodes and create the node vector
  {
    std::vector<unsigned int>::const_iterator node_ID_it, node_ID_end;
    node_ID_it = this->local_to_foreign_node_ID.begin();
    node_ID_end = this->local_to_foreign_node_ID.end();
    for ( ; node_ID_it != node_ID_end; node_ID_it++)
      {
        node =  const_cast<Node*>(mesh_data->getNodeFromForeignID(*node_ID_it));
        local_ID_to_node_vec->push_back(node);
      }
  }
  // create the radiation elements
  {
    std::map<unsigned int, RadiationCavityFiniteElem*>::const_iterator it, end;
    it = this->ID_to_elem_map.begin();
    end = this->ID_to_elem_map.end();
    RadiationElement* rad_elem = NULL;
    unsigned int local_rad_elem_ID = 0;
    for (; it != end; it++)
      {
        // for each elem, get the number of divisions in x and y direction
        // iterate over each row of divisions and create the radiation elems
        // calculate the local coordinates of the elem in the FE, and
        // also the global coordinates of the elem vertices
        const Elem* elem =
          mesh_data->getElemFromForeignID(it->second->elem_ID);
        for (unsigned int i=0; i < it->second->n_x_divs; i++) // increment along x
          for (unsigned int j = 0; j < it->second->n_y_divs; j++) // increment along y
            {
              // create the local radiation elem
              rad_elem = new RadiationElement(*(it->second), elem);
              rad_elem->setData(local_rad_elem_ID,
                                i, j);
              // insert the radiation elem in the elem vector
              rad_elem_vec->push_back(rad_elem);
              local_rad_elem_ID++;
            }
      }
  }
  this->initialized = true;
}
unsigned int RadiationCavity::getCavityID () const [inline]
returns the cavity ID
Definition at line 204 of file RadiationCavity.h.
References radiation_cavity_ID.
Referenced by MeshDS::MeshList::addRadiationCavity(), and RadiationCavityAnalysis::getDataInfoForQty().
{
  return this->radiation_cavity_ID;
}
RadiationElemConstIterator RadiationCavity::getElemBeginIterator (unsigned int DV_ID = 0) const [inline]
returns the beginning iterator to the radiation elems of the mesh corresponding to the DV. If no DV is specified, then the one for base mesh is returned
Definition at line 260 of file RadiationCavity.h.
References rad_elem_vector_map.
{
  std::map<unsigned int, std::vector<RadiationElement*> >::const_iterator it =
    this->rad_elem_vector_map.find(DV_ID);
  assert ( it != this->rad_elem_vector_map.end());
  return it->second.begin();
}
RadiationElemConstIterator RadiationCavity::getElemEndIterator (unsigned int DV_ID = 0) const [inline]
returns the end iterator to the radiation elems of the mesh corresponding to the DV. If no DV is specified, then the one for base mesh is returned
Definition at line 276 of file RadiationCavity.h.
References rad_elem_vector_map.
{
  std::map<unsigned int, std::vector<RadiationElement*> >::const_iterator it =
    this->rad_elem_vector_map.find(DV_ID);
  assert ( it != this->rad_elem_vector_map.end());
  return  it->second.end();
}
const RadiationElement & RadiationCavity::getElemFromID (const unsigned int elem_ID, const unsigned int DV_ID = 0) const [inline]
returns the finite element from the elem ID for the specified design variable. If no DV is specified, then it returns an element for the base cavity.
Parameters:
elem_ID ID of the elem to be retuned
DV_ID (optional) ID of the DV for which this quantity is needed
Definition at line 242 of file RadiationCavity.h.
References rad_elem_vector_map.
Referenced by RadiationCavityAnalysis::calculateB_Matrix().
{
  // make sure that this ID exists in the map
  std::map<unsigned int, std::vector<RadiationElement*> >::const_iterator
    it = this->rad_elem_vector_map.find(DV_ID);
  assert (it != this->rad_elem_vector_map.end());
  assert (elem_ID <= it->second.size());
  return *(it->second[elem_ID]);
}
const std::vector< Node * > & RadiationCavity::getFENodes (unsigned int DV_ID = 0) const [inline]
returns the nodes for finite element for the specified design variable. If no design variable is specified, then the nodes for the base mesh is returned
Definition at line 375 of file RadiationCavity.h.
References initialized, and local_ID_to_node_map.
Referenced by RadiationCavityAnalysis::getFENodalDofIDs(), and Discipline::ThermalAnalysis::ThermalAnalysis().
{
  assert (this->initialized);
  std::map<unsigned int, std::vector<Node*> >::const_iterator it =
    this->local_ID_to_node_map.find(DV_ID);
  assert (it != this->local_ID_to_node_map.end());
  return it->second;
}
unsigned int RadiationCavity::getFiniteElementMeshID (unsigned int DV_ID = 0) const [inline]
returns the finite element mesh ID for the specified DV. If no DV ID is specified, then the mesh ID of the base design point is returned
Definition at line 228 of file RadiationCavity.h.
References fe_mesh_ID_map.
Referenced by RadiationCavityAnalysis::RadiationCavityAnalysis().
{
  std::map<unsigned int, unsigned int>::const_iterator it =
    this->fe_mesh_ID_map.find(DV_ID);
  assert (it != this->fe_mesh_ID_map.end());
  return it->second;
}
const Elem * RadiationCavity::getGeometricFE (unsigned int elem_ID, unsigned int DV_ID = 0) [inline]
returns the geometric elem given by the FE ID, and DV ID. if no DV is specified, then the elem for base mesh is returned
Parameters:
elem_ID ID of the FE that is being requested
DV_ID design variable ID
Definition at line 327 of file RadiationCavity.h.
References MeshDS::FEMeshData::getElemFromForeignID(), and getMeshData().
{
  MeshDS::FEMeshData* mesh_data = this->getMeshData(DV_ID);
  return mesh_data->getElemFromForeignID(elem_ID);
}
Elem * RadiationCavity::getGeometricRadiationElem (unsigned int elem_ID, unsigned int DV_ID = 0) [inline]
returns the geometric elem given by the radiation elem ID for the DV_ID. If no design variable is specified, then the element for the base mesh is returned
Parameters:
elem_ID of the radiation element that is being requested
DV_ID ID of the design variable for which the elem is to be returned
Definition at line 349 of file RadiationCavity.h.
References initialized, and rad_elem_vector_map.
{
  assert (this->initialized);
  std::map<unsigned int, std::vector<RadiationElement*> >::const_iterator
    it = this->rad_elem_vector_map.find(DV_ID);
  assert ( it != this->rad_elem_vector_map.end());
  return (it->second[elem_ID])->getRadiationGeometricElem();
}
void RadiationCavity::getInternalNodeIDForRadElem (unsigned int rad_ID, std::vector< unsigned int > & vector)
returns the vector of internal node IDs for the given internal rad elem ID
Parameters:
rad_ID
vector the node IDs will be returned in this
Definition at line 270 of file RadiationCavity.C.
References foreign_to_local_node_ID, mesh_data_map, and rad_elem_vector_map.
{
  // get the FE elem ID for this rad elem
  unsigned int elem_ID =
    (this->rad_elem_vector_map[0])[rad_ID]->FeElementID(),
    node_external_ID = 0;
  const Elem* elem =
    (this->mesh_data_map[0])->getElemFromForeignID(elem_ID);
  std::map<unsigned int, unsigned int>::const_iterator it, end;
  end = this->foreign_to_local_node_ID.end();
  // iterate over the nodes in this elem, and get their node IDs
  // from the ID map
  node_vec.clear();
  for (unsigned int i=0; i<elem->n_nodes(); i++)
    {
      Node* node = elem->get_node(i);
      node_external_ID =
        (this->mesh_data_map[0])->getForeignIDFromNode(node);
      it = this->foreign_to_local_node_ID.find(node_external_ID);
      assert (it != end);
      node_vec.push_back(it->second);
    }
}
MeshDS::FEMeshData * RadiationCavity::getMeshData (unsigned int DV_ID = 0) const [inline]
returns a pointer the mesh data object for this cavity, qualified by the design variable.
Definition at line 311 of file RadiationCavity.h.
References mesh_data_map.
Referenced by RadiationCavityAnalysis::calculateB_Matrix(), createFENodeVectorAndRadiationElems(), and getGeometricFE().
{
  // make sure that the mesh data is still not null
  std::map<unsigned int, MeshDS::FEMeshData*>::const_iterator it =
    this->mesh_data_map.find(DV_ID);
  assert (it != this->mesh_data_map.end());
  assert (it->second != NULL);
  return it->second;
}
unsigned int RadiationCavity::getNItertionsToRecalculateABInv () const [inline]
Returns:
the number of iterations before the ABInv factor should be recalculated
Definition at line 396 of file RadiationCavity.h.
References initialized, and n_iters_before_AB_inv_recalculation.
{
  assert (this->initialized);
  return this->n_iters_before_AB_inv_recalculation;
}
unsigned int RadiationCavity::getNTaylorTermsForABInvApproximation () const [inline]
Returns:
the number of Taylor series terms to be used for approximation of the ABInv factor
Definition at line 404 of file RadiationCavity.h.
References initialized, and n_AB_inv_taylor_approx_terms.
{
  assert (this->initialized);
  return this->n_AB_inv_taylor_approx_terms;
}
RadiationCavityFiniteElem & RadiationCavity::getRadiationCavityFiniteElement (unsigned int elem_ID) [inline]
returns the radiation cavity finite element for the given ID
Definition at line 337 of file RadiationCavity.h.
References ID_to_elem_map.
{
  std::map<unsigned int, RadiationCavityFiniteElem*>::const_iterator it;
  it = this->ID_to_elem_map.find(elem_ID);
  assert (it != this->ID_to_elem_map.end());
  return *(it->second);
}
bool RadiationCavity::ifApproximateABInvFactor () const [inline]
boolean about whether to approximate or recalculate ABInv factor
Definition at line 387 of file RadiationCavity.h.
References if_approximate_AB_inv, and initialized.
{
  assert (this->initialized);
  return this->if_approximate_AB_inv;
}
unsigned int RadiationCavity::nFiniteElems () const [inline]
returns number of finite elems in the cavity
Definition at line 195 of file RadiationCavity.h.
References ID_to_elem_map.
{
  return this->ID_to_elem_map.size();
}
unsigned int RadiationCavity::nRadiationElems () const [inline]
returns the number of radiation elems in the cavity
Definition at line 364 of file RadiationCavity.h.
References initialized, and rad_elem_vector_map.
Referenced by RadiationCavityAnalysis::calculateA_Matrix(), and RadiationCavityAnalysis::calculateB_Matrix().
{
  // return the size of the base element vector
  assert (this->initialized);
  std::map<unsigned int, std::vector<RadiationElement*> >::const_iterator
    it = this->rad_elem_vector_map.find(0);
  return it->second.size();
}
std::istream & RadiationCavity::readFromInputStream (std::istream & input)
method to read from input stream
Definition at line 76 of file RadiationCavity.C.
References RadiationCavityFiniteElem::elem_ID, ID_to_elem_map, if_approximate_AB_inv, RadiationCavityFiniteElem::internal_ID, n_AB_inv_taylor_approx_terms, n_iters_before_AB_inv_recalculation, RadiationCavityFiniteElem::n_x_divs, RadiationCavityFiniteElem::n_y_divs, radiation_cavity_ID, FESystemIOUtility::readFromInput(), setFiniteElementMeshID(), and RadiationCavityFiniteElem::side_num.
Referenced by MeshDS::MeshList::readFromInputStream().
{
  std::string tag;
  unsigned int n_cards=0;
  FESystemIOUtility::readFromInput(input, "RADIATION_CAVITY");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "RADIATION_CAVITY_ID", this->radiation_cavity_ID);
  unsigned int id = 0;
  FESystemIOUtility::readFromInput(input, "FINITE_ELEMENT_MESH_ID", id);
  this->setFiniteElementMeshID(id);
  FESystemIOUtility::readFromInput(input, "N_ELEMENTS", n_cards);
  unsigned int internal_ID = 0;
  for (unsigned int i=0; i<n_cards; i++)
    {
      // read in all the element
      RadiationCavityFiniteElem* elem = new RadiationCavityFiniteElem();
      assert (elem != NULL);
      input >> elem->elem_ID;
      input >> elem->side_num;
      input >> elem->n_x_divs;
      input >> elem->n_y_divs;
      elem->internal_ID = internal_ID;
      internal_ID ++;
      std::pair<std::map<unsigned int, RadiationCavityFiniteElem*>::const_iterator, bool>
        insert_return_pair =
        this->ID_to_elem_map.insert(std::map<unsigned int, RadiationCavityFiniteElem*>::value_type
                                    (elem->elem_ID, elem));
      assert (insert_return_pair.second == true);
    }
  FESystemIOUtility::readFromInput(input, "IF_AB_INVERSE_APPROXIMATE",
                                   this->if_approximate_AB_inv);
  FESystemIOUtility::readFromInput(input, "N_AB_INV_TAYLOR_TERMS",
                                   this->n_AB_inv_taylor_approx_terms);
  FESystemIOUtility::readFromInput(input, "IF_AB_INV_APPROX_BEFORE_RECALCULATE",
                                   this->n_iters_before_AB_inv_recalculation);
  FESystemIOUtility::readFromInput(input, "RADIATION_CAVITY");
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
void RadiationCavity::setFiniteElementMeshID (unsigned int mesh_ID, unsigned int DV_ID = 0) [inline]
sets the finite element mesh ID for the specific DV. If no DV ID is specified, then the mesh ID is set for the base design point
Definition at line 212 of file RadiationCavity.h.
References fe_mesh_ID_map.
Referenced by readFromInputStream().
{
  std::map<unsigned int, unsigned int>::const_iterator it =
    this->fe_mesh_ID_map.find(DV_ID);
  assert (it == this->fe_mesh_ID_map.end());
  bool insert_bool =
    this->fe_mesh_ID_map.insert(std::map<unsigned int, unsigned int>::value_type
                                (DV_ID, mesh_ID)).second;
  assert ( insert_bool == true);
}
void RadiationCavity::setMeshData (MeshDS::FEMeshData * mesh_data, unsigned int DV_ID = 0) [inline]
sets the finite element mesh data for the cavity
Parameters:
mesh_data this is the mesh data corresponding to the mesh that is participating in the radiation. The mesh is specified for a DV, and if no DV is passed in the arguement, then it is assumed for the base mesh
Definition at line 289 of file RadiationCavity.h.
References createFENodeVectorAndRadiationElems(), and mesh_data_map.
Referenced by RadiationCavityAnalysis::RadiationCavityAnalysis().
{
  // the mesh data can be set only once
  assert (meshdata != NULL);
  std::map<unsigned int, MeshDS::FEMeshData*>::const_iterator it =
    this->mesh_data_map.find(DV_ID);
  assert (it == this->mesh_data_map.end());
  bool insert =
    this->mesh_data_map.insert(std::map<unsigned int, MeshDS::FEMeshData*>::value_type
                               (DV_ID, meshdata)).second;
  assert ( insert == true);
  this->createFENodeVectorAndRadiationElems(DV_ID);
}
Member Data Documentation
std::map<unsigned int, unsigned int> RadiationCavity::fe_mesh_ID_map [protected]
map of finite element mesh ID in which radiation is occurring the key used for this map is the design variable, where, the mesh ID for each DV perturbation is stored against the DV ID
Definition at line 157 of file RadiationCavity.h.
Referenced by getFiniteElementMeshID(), and setFiniteElementMeshID().
std::map<unsigned int, unsigned int > RadiationCavity::foreign_to_local_node_ID [protected]
map of foreign node ID to local node ID
Definition at line 174 of file RadiationCavity.h.
Referenced by createFENodeVectorAndRadiationElems(), and getInternalNodeIDForRadElem().
std::map<unsigned int, RadiationCavityFiniteElem*> RadiationCavity::ID_to_elem_map [protected]
map of the finite element ID to elem. This is the same for each DV
Definition at line 168 of file RadiationCavity.h.
Referenced by createFENodeVectorAndRadiationElems(), getRadiationCavityFiniteElement(), nFiniteElems(), readFromInputStream(), and ~RadiationCavity().
bool RadiationCavity::if_approximate_AB_inv [protected]
if ABinv factor should be approximated? instead of recalculated
Definition at line 146 of file RadiationCavity.h.
Referenced by ifApproximateABInvFactor(), and readFromInputStream().
bool RadiationCavity::initialized [protected]
checks if the cavity data has been initialized or not
Definition at line 160 of file RadiationCavity.h.
Referenced by createFENodeVectorAndRadiationElems(), getFENodes(), getGeometricRadiationElem(), getNItertionsToRecalculateABInv(), getNTaylorTermsForABInvApproximation(), ifApproximateABInvFactor(), and nRadiationElems().
std::map<unsigned int, std::vector<Node*> > RadiationCavity::local_ID_to_node_map [protected]
vector of IDs. The internal ID is the same as the location of the node in this vector. One vector is stored for each design variable
Definition at line 182 of file RadiationCavity.h.
Referenced by createFENodeVectorAndRadiationElems(), and getFENodes().
std::vector<unsigned int> RadiationCavity::local_to_foreign_node_ID [protected]
vector of local to foreign node ID. Local node ID is the location of the ID in this vector
Definition at line 178 of file RadiationCavity.h.
Referenced by createFENodeVectorAndRadiationElems().
std::map<unsigned int ,MeshDS::FEMeshData*> RadiationCavity::mesh_data_map [protected]
map of mesh data mesh data stored against the shape DV ID
Definition at line 163 of file RadiationCavity.h.
Referenced by getInternalNodeIDForRadElem(), getMeshData(), and setMeshData().
unsigned int RadiationCavity::n_AB_inv_taylor_approx_terms [protected]
number of terms to use in the approximation
Definition at line 149 of file RadiationCavity.h.
Referenced by getNTaylorTermsForABInvApproximation(), and readFromInputStream().
unsigned int RadiationCavity::n_iters_before_AB_inv_recalculation [protected]
number of iterations before fully recalculating
Definition at line 152 of file RadiationCavity.h.
Referenced by getNItertionsToRecalculateABInv(), and readFromInputStream().
std::map<unsigned int, std::vector<RadiationElement*> > RadiationCavity::rad_elem_vector_map [protected]
vector of radiation elements the local position of the elem in this vector is also its internal ID. This is stored as a map for each DV
Definition at line 187 of file RadiationCavity.h.
Referenced by createFENodeVectorAndRadiationElems(), getElemBeginIterator(), getElemEndIterator(), getElemFromID(), getGeometricRadiationElem(), getInternalNodeIDForRadElem(), nRadiationElems(), and ~RadiationCavity().
unsigned int RadiationCavity::radiation_cavity_ID [protected]
ID of this radiation cavity.
Definition at line 143 of file RadiationCavity.h.
Referenced by getCavityID(), and readFromInputStream().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Radiation/RadiationCavity.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Radiation/RadiationCavity.C