fesystem: FESystemDatabase::TimeIndependentEigenDataInfo Class Reference
FESystemDatabase::TimeIndependentEigenDataInfo Class Reference
this defines a time independent eigen quantity
#include <DataInfo.h>
Public Member Functions
TimeIndependentEigenDataInfo ()
constructor
TimeIndependentEigenDataInfo (const TimeIndependentEigenDataInfo &data_info)
copy constructor
~TimeIndependentEigenDataInfo ()
destructor
virtual void clear ()
clears the data structures of this object
unsigned int getModeNumber () const
void setModeInfo (const unsigned int mode_num)
sets the modal information for this quantity
virtual unsigned int getDataInfoKindEnumID () const
virtual const std::string getPath () const
virtual std::ostream & write (std::ostream &out)
this method writes the info to an output stream
virtual const std::string getDisplayName () const
virtual bool operator== (const FESystemDatabase::DataInfoBase &data_info) const
Protected Attributes
unsigned int mode_number
transient iteration
Detailed Description
this defines a time independent eigen quantity
Definition at line 315 of file DataInfo.h.
Constructor & Destructor Documentation
FESystemDatabase::TimeIndependentEigenDataInfo::TimeIndependentEigenDataInfo ()
constructor
Definition at line 594 of file DataInfo.C.
References clear().
                                                                          :
FESystemDatabase::TimeIndependentDataInfo()
{
  this->clear();
}
FESystemDatabase::TimeIndependentEigenDataInfo::TimeIndependentEigenDataInfo (const TimeIndependentEigenDataInfo & data_info)
copy constructor
Definition at line 604 of file DataInfo.C.
References mode_number.
                                               :
  FESystemDatabase::TimeIndependentDataInfo(data_info)
{
  this->mode_number = data_info.mode_number;
}
FESystemDatabase::TimeIndependentEigenDataInfo::~TimeIndependentEigenDataInfo ()
destructor
Definition at line 612 of file DataInfo.C.
{
}
Member Function Documentation
void FESystemDatabase::TimeIndependentEigenDataInfo::clear () [virtual]
clears the data structures of this object
Reimplemented from FESystemDatabase::GenericDataInfoBase.
Definition at line 621 of file DataInfo.C.
References FESystemDatabase::GenericDataInfoBase::clear(), and FESystemNumbers::InvalidID.
Referenced by Driver::EigenProblemAnalysisDriver::solveCurrentLoadCase(), Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase(), and TimeIndependentEigenDataInfo().
{
  this->mode_number = FESystemNumbers::InvalidID;
  FESystemDatabase::TimeIndependentDataInfo::clear();
}
unsigned int FESystemDatabase::TimeIndependentEigenDataInfo::getDataInfoKindEnumID () const [virtual]
Returns:
the enumeration ID of the kind of the data
Reimplemented from FESystemDatabase::TimeIndependentDataInfo.
Definition at line 660 of file DataInfo.C.
{
  return FESystemDatabase::TIME_INDEPENDENT_EIGEN_DATA::num();
}
const std::string FESystemDatabase::TimeIndependentEigenDataInfo::getDisplayName () const [virtual]
Reimplemented from FESystemDatabase::TimeIndependentDataInfo.
Definition at line 711 of file DataInfo.C.
{
  std::string full_path_name = this->getName();
  // append the mode information to the name
  std::ostringstream mode_num_oss;
  mode_num_oss << this->getModeNumber();
  full_path_name += "_MODE_";
  full_path_name += mode_num_oss.str();
  // append the sensitivity information to the name
  if (this->ifSensitivityData())
    {
    std::ostringstream dv_id_oss;
    dv_id_oss << this->getDVID();
    full_path_name += "_SENS_DV_";
    full_path_name += dv_id_oss.str();
    }
  // append the load case information to the name
  if (this->ifLoadCaseDependent())
    {
    std::ostringstream lc_oss;
    lc_oss << this->getLoadCase();
    full_path_name += "_LC_";
    full_path_name += lc_oss.str();
    }
  return full_path_name;
}
unsigned int FESystemDatabase::TimeIndependentEigenDataInfo::getModeNumber () const
Returns:
the time iteration number
Definition at line 632 of file DataInfo.C.
References FESystemNumbers::InvalidID.
{
  // make sure that this was set by the user
  Assert(this->mode_number != FESystemNumbers::InvalidID, ExcInternalError());
  return this->mode_number;
}
const std::string FESystemDatabase::TimeIndependentEigenDataInfo::getPath () const [virtual]
Returns:
the exact path to the location of the data for this object in the database
Reimplemented from FESystemDatabase::TimeIndependentDataInfo.
Definition at line 670 of file DataInfo.C.
{
  std::string full_path_name = this->getDisciplineEnumName();
  full_path_name +="_";
  full_path_name += this->getName();
  // append the mode information to the name
  std::ostringstream mode_num_oss;
  mode_num_oss << this->getModeNumber();
  full_path_name += "_MODE_NUM_";
  full_path_name += mode_num_oss.str();
  // append the sensitivity information to the name
  if (this->ifSensitivityData())
    {
    std::ostringstream dv_id_oss;
    dv_id_oss << this->getDVID();
    full_path_name += "_SENSITIVITY_DV_";
    full_path_name += dv_id_oss.str();
    }
  // append the load case information to the name
  if (this->ifLoadCaseDependent())
    {
    std::ostringstream lc_oss;
    lc_oss << this->getLoadCase();
    full_path_name += "_LC_";
    full_path_name += lc_oss.str();
    }
  return full_path_name;
}
bool FESystemDatabase::TimeIndependentEigenDataInfo::operator== (const FESystemDatabase::DataInfoBase & data_info) const [virtual]
Returns:
true if the given data info object and this, point to the same data
Reimplemented from FESystemDatabase::TimeIndependentDataInfo.
Definition at line 761 of file DataInfo.C.
References mode_number.
{
  if (! FESystemDatabase::TimeIndependentDataInfo::operator==(data_info))
    return false;
  else
    {
      const FESystemDatabase::TimeIndependentEigenDataInfo &eigen_data_info =
        dynamic_cast<const FESystemDatabase::TimeIndependentEigenDataInfo&>(data_info);
      // check each data and return the result
      if (this->mode_number != eigen_data_info.mode_number)
        return false;
    }
  // if it gets here, means that this the two objects are same
  return true;
}
void FESystemDatabase::TimeIndependentEigenDataInfo::setModeInfo (const unsigned int mode_num)
sets the modal information for this quantity
Definition at line 644 of file DataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Driver::EigenProblemAnalysisDriver::solveCurrentLoadCase(), and Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
{
  // make sure that this object was cleared
  Assert(this->mode_number == FESystemNumbers::InvalidID, ExcInternalError());
  // make sure that the number provided is correct
  Assert(mode_num != FESystemNumbers::InvalidID, ExcInternalError());
  this->mode_number = mode_num;
}
std::ostream & FESystemDatabase::TimeIndependentEigenDataInfo::write (std::ostream & out) [virtual]
this method writes the info to an output stream
Reimplemented from FESystemDatabase::GenericDataInfoBase.
Definition at line 748 of file DataInfo.C.
References FESystemDatabase::GenericDataInfoBase::write().
{
  FESystemDatabase::GenericDataInfoBase::write(out);
  out << "Mode Number :   " << this->getModeNumber() << std::endl;
  return out;
}
Member Data Documentation
unsigned int FESystemDatabase::TimeIndependentEigenDataInfo::mode_number [protected]
transient iteration
Definition at line 358 of file DataInfo.h.
Referenced by operator==(), and TimeIndependentEigenDataInfo().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.C