fesystem: Isotropic3D_ElemDataCard Class Reference
Isotropic3D_ElemDataCard Class Reference
#include <Isotropic3DElemDataCard.h>
Public Member Functions
Isotropic3D_ElemDataCard ()
virtual ~Isotropic3D_ElemDataCard ()
virtual unsigned int getPropertyCardKindEnumID () const
virtual const std::string getPropertyCardKindEnumName () const
virtual void getFactor (double &factor, const unsigned int factor_enum_ID)
returns the value of the factor
virtual void getFactorSensitivityForGlobalParameter (double &factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID)
virtual void getFactorSensitivityForLocalParameter (double &factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID)
virtual void getFactor (DenseMatrix< double > &factor, const unsigned int factor_enum_ID)
returns the value of the factor
virtual void getFactorSensitivityForGlobalParameter (DenseMatrix< double > &factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID)
virtual void getFactorSensitivityForLocalParameter (DenseMatrix< double > &factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID)
Protected Member Functions
virtual std::string getPropertyEnumName (const unsigned int enum_ID) const
virtual const unsigned int getPropertyEnumID (const std::string &enum_name) const
Friends
std::istream & operator>> (std::istream &input, Isotropic3D_ElemDataCard &plane_elem)
Detailed Description
Definition at line 51 of file Isotropic3DElemDataCard.h.
Constructor & Destructor Documentation
Isotropic3D_ElemDataCard::Isotropic3D_ElemDataCard ()
Definition at line 7 of file Isotropic3DElemDataCard.C.
                                                  :
IsotropicElemDataCard()
{
}
Isotropic3D_ElemDataCard::~Isotropic3D_ElemDataCard () [virtual]
Definition at line 15 of file Isotropic3DElemDataCard.C.
{
}
Member Function Documentation
void Isotropic3D_ElemDataCard::getFactor (double & factor, const unsigned int factor_enum_ID) [inline, virtual]
returns the value of the factor
Implements ElemDataCard.
Definition at line 123 of file Isotropic3DElemDataCard.h.
References IsotropicElemDataCard::getMaterialCard(), MASS_FACTOR_ENUM_ID, DENSITY::num(), SPECIFIC_HEAT::num(), ALPHA_EXPANSION::num(), THERMAL_CONDUCTIVITY::num(), YOUNGS_MODULUS::num(), POISSONS_RATIO::num(), EMISSIVITY::num(), THERMAL_CAPACITANCE_FACTOR_ENUM_ID, THERMAL_CONDUCTANCE_FACTOR_ENUM_ID, THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID, and THERMAL_EXPANSION_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& property =this->getMaterialCard();
  factor = 0.0;
  static double val1, val2;
  val1 = 0.0; val2 = 0.0;
  switch (factor_enum_ID)
    {
    case MASS_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(DENSITY::num(), val1);
        factor = val1;
      }
      break;
    case THERMAL_EXPANSION_FACTOR_ENUM_ID:
      {
        static double E, alpha, nu;
        property.getPropertyValue(YOUNGS_MODULUS::num(), E);
        property.getPropertyValue(ALPHA_EXPANSION::num(), alpha);
        property.getPropertyValue(POISSONS_RATIO::num(), nu);
        factor =  E*alpha*(1.0+nu)/(1.0-nu-2.0*nu*nu);
      }
      break;
    case THERMAL_CAPACITANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(DENSITY::num(), val1);
        property.getPropertyValue(SPECIFIC_HEAT::num(), val2);
        factor = val1 * val2;
      }
      break;
    case THERMAL_CONDUCTANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(THERMAL_CONDUCTIVITY::num(), val1);
        factor = val1;
      }
      break;
    case THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(EMISSIVITY::num(), val1);
        factor = val1;
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
void Isotropic3D_ElemDataCard::getFactor (DenseMatrix< double > & factor, const unsigned int factor_enum_ID) [inline, virtual]
returns the value of the factor
Implements ElemDataCard.
Definition at line 194 of file Isotropic3DElemDataCard.h.
References IsotropicElemDataCard::getMaterialCard(), MASS_FACTOR_ENUM_ID, YOUNGS_MODULUS::num(), POISSONS_RATIO::num(), and SOLID_STIFFNESS_MATRIX_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& property =this->getMaterialCard();
  if (matrix.m() != 6 || matrix.n() != 6)
    matrix.resize(6,6);
  matrix.zero();
  static double val1, val2, val3, val4;
  val1 = 0.0; val2 = 0.0; val3 = 0.0; val4 = 0.0;
  switch (factor_enum_ID)
    {
    case SOLID_STIFFNESS_MATRIX_FACTOR_ENUM_ID:
      {
        static double E, nu;
        property.getPropertyValue(YOUNGS_MODULUS::num(), E);
        property.getPropertyValue(POISSONS_RATIO::num(), nu);
        matrix(0,0) = E * (1.0-nu) / (1-nu-2.0*nu*nu);
        matrix(1,1) = matrix(0,0);
        matrix(2,2) = matrix(0,0);
        matrix(0,1) = E * nu / (1-nu-2.0*nu*nu);
        matrix(0,2) = matrix(0,1);
        matrix(1,0) = matrix(0,1);
        matrix(1,2) = matrix(0,1);
        matrix(2,0) = matrix(0,1);
        matrix(2,1) = matrix(0,1);
        matrix(3,3) = E / 2.0 / (1.0 + nu); // E / (2 *(1+nu))
        matrix(4,4) = matrix(3,3);
        matrix(5,5) = matrix(3,3);
      };
      break;
      case MASS_FACTOR_ENUM_ID:
      default:
        Assert(false,
               FESystemExceptions::ExcEnumCaseNotImplemented
               (ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
void Isotropic3D_ElemDataCard::getFactorSensitivityForGlobalParameter (double & factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID) [inline, virtual]
Implements ElemDataCard.
Definition at line 246 of file Isotropic3DElemDataCard.h.
References IsotropicElemDataCard::getMaterialCard(), MASS_FACTOR_ENUM_ID, DENSITY::num(), SPECIFIC_HEAT::num(), ALPHA_EXPANSION::num(), THERMAL_CONDUCTIVITY::num(), YOUNGS_MODULUS::num(), POISSONS_RATIO::num(), EMISSIVITY::num(), THERMAL_CAPACITANCE_FACTOR_ENUM_ID, THERMAL_CONDUCTANCE_FACTOR_ENUM_ID, THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID, and THERMAL_EXPANSION_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& property =this->getMaterialCard();
  factor = 0.0;
  static double val1, val2, val3, val4;
  static double val1_sens, val2_sens, val3_sens, val4_sens;
  val1 = 0.0; val2 = 0.0; val3 = 0.0; val4 = 0.0;
  val1_sens = 0.0; val2_sens = 0.0; val3_sens = 0.0; val4_sens = 0.0;
  switch (factor_enum_ID)
    {
    case MASS_FACTOR_ENUM_ID:
      {
        property.getPropertyDerivativeForGlobalParameter(DENSITY::num(),
                                                         global_param_ID,
                                                         val1_sens);
        factor = val1_sens;
      }
      break;
    case THERMAL_EXPANSION_FACTOR_ENUM_ID:
      {
        static double E, alpha, nu, E_sens, alpha_sens, nu_sens;
        property.getPropertyValue(YOUNGS_MODULUS::num(), E);
        property.getPropertyValue(ALPHA_EXPANSION::num(), alpha);
        property.getPropertyValue(POISSONS_RATIO::num(), nu);
        property.getPropertyDerivativeForGlobalParameter(YOUNGS_MODULUS::num(),
                                                         global_param_ID,
                                                         E_sens);
        property.getPropertyDerivativeForGlobalParameter(ALPHA_EXPANSION::num(),
                                                         global_param_ID, alpha_sens);
        property.getPropertyDerivativeForGlobalParameter(POISSONS_RATIO::num(),
                                                         global_param_ID, nu_sens);
        factor = (E_sens * alpha + E * alpha_sens)*(1.0+nu)/(1.0-nu-2.0*nu*nu) +
          nu_sens *  E*alpha*(2.0+4.0*nu+2.0*nu*nu)/pow((1.0-nu-2.0*nu*nu),2);
      }
      break;
    case THERMAL_CAPACITANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(DENSITY::num(), val1);
        property.getPropertyValue(SPECIFIC_HEAT::num(), val2);
        property.getPropertyDerivativeForGlobalParameter(DENSITY::num(),
                                                         global_param_ID, val1_sens);
        property.getPropertyDerivativeForGlobalParameter(SPECIFIC_HEAT::num(),
                                                         global_param_ID, val2_sens);
        factor = val1_sens * val2 * + val1 * val2_sens;
      }
      break;
    case THERMAL_CONDUCTANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyDerivativeForGlobalParameter
          (THERMAL_CONDUCTIVITY::num(),
           global_param_ID, val1_sens);
        factor = val1_sens;
      }
      break;
    case THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID:
      {
        property.getPropertyDerivativeForGlobalParameter
        (EMISSIVITY::num(),
         global_param_ID, val1_sens);
        factor = val1_sens;
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
void Isotropic3D_ElemDataCard::getFactorSensitivityForGlobalParameter (DenseMatrix< double > & factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID) [inline, virtual]
Implements ElemDataCard.
Definition at line 340 of file Isotropic3DElemDataCard.h.
References IsotropicElemDataCard::getMaterialCard(), YOUNGS_MODULUS::num(), POISSONS_RATIO::num(), and SOLID_STIFFNESS_MATRIX_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& property =this->getMaterialCard();
  if (matrix.m() != 6 || matrix.n() != 6)
    matrix.resize(6,6);
  matrix.zero();
  switch (factor_enum_ID)
    {
    case SOLID_STIFFNESS_MATRIX_FACTOR_ENUM_ID:
      {
        static double E, nu, E_sens, nu_sens;
        property.getPropertyValue(YOUNGS_MODULUS::num(), E);
        property.getPropertyValue(POISSONS_RATIO::num(), nu);
        property.getPropertyDerivativeForGlobalParameter(YOUNGS_MODULUS::num(),
                                                         global_param_ID,
                                                         E_sens);
        property.getPropertyDerivativeForGlobalParameter(POISSONS_RATIO::num(),
                                                         global_param_ID,
                                                         nu_sens);
        matrix(0,0) = E_sens * (1.0-nu) / (1-nu-2.0*nu*nu) +
          nu_sens * E * (-2.0*nu + 4.0) * nu / pow((1-nu-2.0*nu*nu),2);
        matrix(1,1) = matrix(0,0);
        matrix(2,2) = matrix(0,0);
        matrix(0,1) = E_sens * nu / (1-nu-2.0*nu*nu) +
          nu_sens * E * (1.0+2.0*nu*nu) / pow((1-nu-2.0*nu*nu),2);
        matrix(0,2) = matrix(0,1);
        matrix(1,0) = matrix(0,1);
        matrix(1,2) = matrix(0,1);
        matrix(2,0) = matrix(0,1);
        matrix(2,1) = matrix(0,1);
        matrix(3,3) = E_sens / 2.0 / (1.0 + nu) -
          nu_sens * -0.5 * E / pow((1.0 + nu),2);
        matrix(4,4) = matrix(3,3);
        matrix(5,5) = matrix(3,3);
      };
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
void Isotropic3D_ElemDataCard::getFactorSensitivityForLocalParameter (double & factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID) [inline, virtual]
Implements ElemDataCard.
Definition at line 400 of file Isotropic3DElemDataCard.h.
References IsotropicElemDataCard::getMaterialCard(), MASS_FACTOR_ENUM_ID, DENSITY::num(), SPECIFIC_HEAT::num(), ALPHA_EXPANSION::num(), THERMAL_CONDUCTIVITY::num(), YOUNGS_MODULUS::num(), POISSONS_RATIO::num(), EMISSIVITY::num(), THERMAL_CAPACITANCE_FACTOR_ENUM_ID, THERMAL_CONDUCTANCE_FACTOR_ENUM_ID, THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID, and THERMAL_EXPANSION_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& property =this->getMaterialCard();
  factor = 0.0;
  static double val1, val2, val3, val4;
  static double val1_sens, val2_sens, val3_sens, val4_sens;
  val1 = 0.0; val2 = 0.0; val3 = 0.0; val4 = 0.0;
  val1_sens = 0.0; val2_sens = 0.0; val3_sens = 0.0; val4_sens = 0.0;
  switch (factor_enum_ID)
    {
    case MASS_FACTOR_ENUM_ID:
      {
        property.getPropertyDerivativeForLocalParameter(DENSITY::num(),
                                                        param_enum_ID,
                                                        val1_sens);
        factor = val1_sens;
      }
      break;
    case THERMAL_EXPANSION_FACTOR_ENUM_ID:
      {
        static double E, alpha, nu, E_sens, alpha_sens, nu_sens;
        property.getPropertyValue(YOUNGS_MODULUS::num(), E);
        property.getPropertyValue(ALPHA_EXPANSION::num(), alpha);
        property.getPropertyValue(POISSONS_RATIO::num(), nu);
        property.getPropertyDerivativeForLocalParameter(YOUNGS_MODULUS::num(),
                                                         param_enum_ID,
                                                         E_sens);
        property.getPropertyDerivativeForLocalParameter(ALPHA_EXPANSION::num(),
                                                         param_enum_ID, alpha_sens);
        property.getPropertyDerivativeForLocalParameter(POISSONS_RATIO::num(),
                                                         param_enum_ID, nu_sens);
        factor = (E_sens * alpha + E * alpha_sens)*(1.0+nu)/(1.0-nu-2.0*nu*nu) +
          nu_sens *  E*alpha*(2.0+4.0*nu+2.0*nu*nu)/pow((1.0-nu-2.0*nu*nu),2);
      }
      break;
    case THERMAL_CAPACITANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(DENSITY::num(), val1);
        property.getPropertyValue(SPECIFIC_HEAT::num(), val2);
        property.getPropertyDerivativeForLocalParameter(DENSITY::num(),
                                                        param_enum_ID, val1_sens);
        property.getPropertyDerivativeForLocalParameter(SPECIFIC_HEAT::num(),
                                                        param_enum_ID, val2_sens);
        factor = val1_sens * val2 + val1 * val2_sens;
      }
      break;
    case THERMAL_CONDUCTANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyDerivativeForLocalParameter
          (THERMAL_CONDUCTIVITY::num(),
           param_enum_ID, val1_sens);
        factor = val1_sens;
      }
      break;
    case THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID:
      {
        property.getPropertyDerivativeForLocalParameter
        (EMISSIVITY::num(), param_enum_ID, val1_sens);
        factor = val1_sens;
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
void Isotropic3D_ElemDataCard::getFactorSensitivityForLocalParameter (DenseMatrix< double > & factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID) [inline, virtual]
Implements ElemDataCard.
Definition at line 495 of file Isotropic3DElemDataCard.h.
References IsotropicElemDataCard::getMaterialCard(), MASS_FACTOR_ENUM_ID, YOUNGS_MODULUS::num(), POISSONS_RATIO::num(), and SOLID_STIFFNESS_MATRIX_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& property =this->getMaterialCard();
  if (matrix.m() != 6 || matrix.n() != 6)
    matrix.resize(6,6);
  matrix.zero();
  switch (factor_enum_ID)
    {
    case SOLID_STIFFNESS_MATRIX_FACTOR_ENUM_ID:
      {
        static double E, nu, E_sens, nu_sens;
        property.getPropertyValue(YOUNGS_MODULUS::num(), E);
        property.getPropertyValue(POISSONS_RATIO::num(), nu);
        property.getPropertyDerivativeForLocalParameter(YOUNGS_MODULUS::num(),
                                                         param_enum_ID,
                                                         E_sens);
        property.getPropertyDerivativeForLocalParameter(POISSONS_RATIO::num(),
                                                         param_enum_ID,
                                                         nu_sens);
        matrix(0,0) = E_sens * (1.0-nu) / (1-nu-2.0*nu*nu) +
          nu_sens * E * (-2.0*nu + 4.0) * nu / pow((1-nu-2.0*nu*nu),2);
        matrix(1,1) = matrix(0,0);
        matrix(2,2) = matrix(0,0);
        matrix(0,1) = E_sens * nu / (1-nu-2.0*nu*nu) +
          nu_sens * E * (1.0+2.0*nu*nu) / pow((1-nu-2.0*nu*nu),2);
        matrix(0,2) = matrix(0,1);
        matrix(1,0) = matrix(0,1);
        matrix(1,2) = matrix(0,1);
        matrix(2,0) = matrix(0,1);
        matrix(2,1) = matrix(0,1);
        matrix(3,3) = E_sens / 2.0 / (1.0 + nu) -
          nu_sens * -0.5 * E / pow((1.0 + nu),2);
        matrix(4,4) = matrix(3,3);
        matrix(5,5) = matrix(3,3);
      };
      break;
      case MASS_FACTOR_ENUM_ID:
      default:
        Assert(false,
               FESystemExceptions::ExcEnumCaseNotImplemented
               (ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
unsigned int Isotropic3D_ElemDataCard::getPropertyCardKindEnumID () const [inline, virtual]
Returns:
the property card kind enumeration ID
Implements Property::PropertyCardBase.
Definition at line 103 of file Isotropic3DElemDataCard.h.
{
  return ISOTROPIC_3D_ELEM_DATA_CARD::num();
}
const std::string Isotropic3D_ElemDataCard::getPropertyCardKindEnumName () const [inline, virtual]
Returns:
the property card kind enumeration name
Implements Property::PropertyCardBase.
Definition at line 111 of file Isotropic3DElemDataCard.h.
{
  return ISOTROPIC_3D_ELEM_DATA_CARD::name();
}
const unsigned int Isotropic3D_ElemDataCard::getPropertyEnumID (const std::string & enum_name) const [inline, protected, virtual]
Returns:
the property ID from enumeration name of the property
Implements Property::PropertyCard< double >.
Definition at line 563 of file Isotropic3DElemDataCard.h.
{
  return Isotropic_3D_ElemDataEnum::enumID(enum_name);
}
std::string Isotropic3D_ElemDataCard::getPropertyEnumName (const unsigned int enum_ID) const [inline, protected, virtual]
Returns:
the property name from enumeration ID of the property
Implements Property::PropertyCard< double >.
Definition at line 554 of file Isotropic3DElemDataCard.h.
{
  return Isotropic_3D_ElemDataEnum::enumName(enum_ID);
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, Isotropic3D_ElemDataCard & plane_elem) [friend]
Definition at line 23 of file Isotropic3DElemDataCard.C.
{
  return solid_elem.readFromInputStream(input);
}
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/Isotropic3DElemDataCard.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/Isotropic3DElemDataCard.C