fesystem: FESystemNumerics::PetscMatrixBase< T > Class Template Reference
FESystemNumerics::PetscMatrixBase< T > Class Template Reference
#include <PetscMatrixBase.h>
Public Member Functions
PetscMatrixBase ()
constructor
virtual ~PetscMatrixBase ()
virtual unsigned int getMatrixPackage () const
virtual void resize (const unsigned int m, const unsigned int n)=0
virtual void zero ()
virtual T el (const unsigned int i, const unsigned int j) const
virtual void getRow (const unsigned int i, FESystemNumerics::VectorBase< T > &vec)
returns the i th row of the matrix in the given vector
virtual void getDiagonal (FESystemNumerics::VectorBase< T > &vec)
returns the diagonal of the matrix in the given vector
virtual void shift (const T val)
adds val to all diagonal elements of the matrix
virtual void set (const unsigned int i, const unsigned int j, const T val)
virtual void set (const std::vector< unsigned int > &i, const std::vector< unsigned int > &j, const T *val)
virtual void setRow (const unsigned row_num, const FESystemNumerics::PetscVectorBase< T > &vector)
virtual void setRow (const unsigned row_num, const std::vector< unsigned int > &col_ids, const FESystemNumerics::PetscVectorBase< T > &vector)
virtual void leftDiagonalScale (const FESystemNumerics::VectorBase< T > &vector)
virtual void rightDiagonalScale (const FESystemNumerics::VectorBase< T > &vector)
virtual void leftMultiply (const FESystemNumerics::MatrixBase< T > &matrix)
virtual void leftMultiplyTranspose (const FESystemNumerics::MatrixBase< T > &matrix)
virtual void rightMultiply (const FESystemNumerics::MatrixBase< T > &matrix)
virtual void leftMultiplyVector (const FESystemNumerics::VectorBase< T > &vector_in, FESystemNumerics::VectorBase< T > &result)
virtual void rightMultiplyVector (const FESystemNumerics::VectorBase< T > &vector_in, FESystemNumerics::VectorBase< T > &result)
virtual unsigned int m () const
virtual unsigned int n () const
virtual void add (const T val, const FESystemNumerics::MatrixBase< T > &matrix, const bool same_nonzer)
virtual void add (const unsigned int i, const unsigned int j, const T factor)
virtual void add (const std::vector< unsigned int > &i, const std::vector< unsigned int > &j, const T *val)
virtual void diagonalAdd (const T val, const FESystemNumerics::VectorBase< T > &diag)
virtual void scale (const T factor)
Mat getMat ()
returns the Petsc matrix data structure
const Mat getMat () const
void flushAssemble ()
method to flush assemble the matrix
void finalAssemble ()
method to perform a final assembly of the matrix
Protected Types
enum LastAction { ADD, INSERT, FLUSH_ASSEMBLE, FINAL_ASSEMBLE }
an enumeration to keep track of action performed
Protected Attributes
LastAction matrix_last_action
Mat petsc_mat
Petsc matrix data structure.
Detailed Description
template<typename T>
class FESystemNumerics::PetscMatrixBase< T >
this class provides a base class for different kinds of matrices
Definition at line 24 of file PetscMatrixBase.h.
Member Enumeration Documentation
template<typename T> enum FESystemNumerics::PetscMatrixBase::LastAction [protected]
an enumeration to keep track of action performed
Enumerator:
ADD
INSERT
FLUSH_ASSEMBLE
FINAL_ASSEMBLE
Definition at line 227 of file PetscMatrixBase.h.
{ADD, INSERT, FLUSH_ASSEMBLE, FINAL_ASSEMBLE};
Constructor & Destructor Documentation
template<typename T > FESystemNumerics::PetscMatrixBase< T >::PetscMatrixBase ()
constructor
Definition at line 243 of file PetscMatrixBase.h.
                                                   :
FESystemNumerics::MatrixBase<T>()
{}
template<typename T > FESystemNumerics::PetscMatrixBase< T >::~PetscMatrixBase () [virtual]
Destructor. Empty.
Definition at line 250 of file PetscMatrixBase.h.
{}
Member Function Documentation
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::add (const T val, const FESystemNumerics::MatrixBase< T > & matrix, const bool same_nonzer) [inline, virtual]
Adds to this matrix
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 897 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscMatrixBase< T >::getMat(), and FESystemNumerics::MatrixBase< T >::getMatrixPackage().
Referenced by RadiationCavityAnalysis::calculateA_Matrix(), RadiationCavityAnalysis::calculateG_Matrix(), and RadiationCavityAnalysis::calculateShapeFactorMatrix().
{
  Assert(matrix.getMatrixPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscMatrixBase<T>& mat =
    dynamic_cast<const FESystemNumerics::PetscMatrixBase<T>&>(matrix);
  const_cast<FESystemNumerics::PetscMatrixBase<T>&>(mat).finalAssemble();
  PetscErrorCode ierr;
  if (same_nonzero)
    ierr = MatAXPY(this->petsc_mat, val, mat.getMat(), SAME_NONZERO_PATTERN);
  else
    ierr = MatAXPY(this->petsc_mat, val, mat.getMat(), DIFFERENT_NONZERO_PATTERN);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::add (const unsigned int i, const unsigned int j, const T factor) [inline, virtual]
Adds factor to every element in the matrix.
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 936 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
{
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
      this->flushAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = MatSetValue (this->petsc_mat, i, j,
                      val, ADD_VALUES);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->matrix_last_action = FESystemNumerics::PetscMatrixBase<T>::ADD;
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::add (const std::vector< unsigned int > & i, const std::vector< unsigned int > & j, const T * val) [inline, virtual]
adds multiple elements with the indeces given in i and j. The val should be a 2-D matrix of dimensions equal to size of vectors i and j.
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 967 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
{
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
      this->flushAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = MatSetValues (this->petsc_mat, i.size(), (const PetscInt*) &(i[0]),
                       j.size(), (const PetscInt*) &(j[0]),
                       val, ADD_VALUES);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->matrix_last_action = FESystemNumerics::PetscMatrixBase<T>::ADD;
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::diagonalAdd (const T val, const FESystemNumerics::VectorBase< T > & diag) [inline, virtual]
adds a diagonal matrix times a factor to this matrix. The diagonal matrix is given as a vector.
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 1000 of file PetscMatrixBase.h.
References add, FESystem::COMM_WORLD, FESystemNumerics::VectorBase< T >::getVectorPackage(), n, and FESystemNumerics::VectorBase< T >::size().
Referenced by RadiationCavityAnalysis::calculateB_Matrix().
{
  Assert (vec.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  Assert (this->m() == this->n(), ExcInternalError());
  Assert (vec.size() == this->m(), ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
      this->flushAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscVectorBase<T> & pvec =
    dynamic_cast<const FESystemNumerics::PetscVectorBase<T> &>(vec);
  const_cast<FESystemNumerics::PetscVectorBase<T> &>(pvec).assemble();
  Vec petsc_vector =   const_cast<FESystemNumerics::PetscVectorBase<T> &>(pvec).getVec();
  PetscErrorCode ierr;
  T *vec_vals;
  ierr = VecGetArray (petsc_vector, &vec_vals);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  for (unsigned int i=0; i<this->m(); i++)
    this->add(i,i, val * vec_vals[i]);
  ierr = VecRestoreArray (petsc_vector, &vec_vals);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > T FESystemNumerics::PetscMatrixBase< T >::el (const unsigned int i, const unsigned int j) const [inline, virtual]
Returns:
the (i,j) element of the matrix. Since internal data representations may differ, you must redefine this function.
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 281 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
Referenced by Discipline::ThermalAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  // if the data has not been flushed, do that before accessing the value
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      const_cast<FESystemNumerics::PetscMatrixBase<T>*>(this)->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  PetscInt i_num = i;
  PetscInt j_num = j;
  T val;
  ierr = MatGetValues (this->petsc_mat, 1, &i_num, 1, &j_num, (PetscScalar*) &val);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  return val;
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::finalAssemble () [inline]
method to perform a final assembly of the matrix
Definition at line 1103 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateA_InverseMatrix(), and RadiationCavityAnalysis::calculateB_InverseMatrix().
{
  PetscErrorCode ierr;
  ierr = MatAssemblyBegin(this->petsc_mat,MAT_FINAL_ASSEMBLY);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = MatAssemblyEnd(this->petsc_mat,MAT_FINAL_ASSEMBLY);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->matrix_last_action = FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE;
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::flushAssemble () [inline]
method to flush assemble the matrix
Definition at line 1088 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
{
  PetscErrorCode ierr;
  ierr = MatAssemblyBegin(this->petsc_mat,MAT_FLUSH_ASSEMBLY);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = MatAssemblyEnd(this->petsc_mat,MAT_FLUSH_ASSEMBLY);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->matrix_last_action = FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE;
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::getDiagonal (FESystemNumerics::VectorBase< T > & vec) [inline, virtual]
returns the diagonal of the matrix in the given vector
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 365 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::VectorBase< T >::getVectorPackage(), n, and FESystemNumerics::VectorBase< T >::size().
Referenced by RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector().
{
  Assert(vec.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  Assert (vec.size() == this->n(), ExcInternalError());
  switch (this->matrix_last_action)
  {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
  }
  PetscErrorCode ierr;
  Vec pvec = dynamic_cast<FESystemNumerics::PetscVectorBase<T>&>(vec).getVec();
  // get the row
  ierr = MatGetDiagonal(this->petsc_mat, pvec);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > Mat FESystemNumerics::PetscMatrixBase< T >::getMat () [inline]
returns the Petsc matrix data structure
Definition at line 1069 of file PetscMatrixBase.h.
Referenced by FESystemNumerics::PetscMatrixBase< T >::add(), RadiationCavityAnalysis::calculateA_InverseMatrix(), RadiationCavityAnalysis::calculateB_InverseMatrix(), FESystemNumerics::PetscSeqDenseMatrix< T >::leftMultiply(), FESystemNumerics::PetscMatrixBase< T >::leftMultiply(), FESystemNumerics::PetscSeqDenseMatrix< T >::leftMultiplyTranspose(), FESystemNumerics::PetscMatrixBase< T >::leftMultiplyTranspose(), FESystemNumerics::PetscSeqDenseMatrix< T >::PetscSeqDenseMatrix(), FESystemNumerics::PetscSeqDenseMatrix< T >::rightMultiply(), and FESystemNumerics::PetscMatrixBase< T >::rightMultiply().
{
  return this->petsc_mat;
}
template<typename T > const Mat FESystemNumerics::PetscMatrixBase< T >::getMat () const [inline]
Returns:
a constant Petsc matrix data structure
Definition at line 1079 of file PetscMatrixBase.h.
{
  return this->petsc_mat;
}
template<typename T > unsigned int FESystemNumerics::PetscMatrixBase< T >::getMatrixPackage () const [virtual]
Returns:
the matrix package
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 257 of file PetscMatrixBase.h.
{
  return FESystem::PETSC_PACKAGE::num();
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::getRow (const unsigned int i, FESystemNumerics::VectorBase< T > & vec) [inline, virtual]
returns the i th row of the matrix in the given vector
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 313 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::VectorBase< T >::getVectorPackage(), n, FESystemNumerics::VectorBase< T >::size(), and FESystemNumerics::VectorBase< T >::zero().
Referenced by RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution().
{
  Assert(vec.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  Assert (vec.size() == this->n(), ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  unsigned int n_cols, *cols;
  T *row_vals, *vec_vals;
  // get the row
  ierr = MatGetRow (this->petsc_mat, i, (PetscInt*) &(n_cols), (const PetscInt**) &(cols),
                    (const PetscScalar**) &(row_vals));
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // copy values in the vector
  vec.zero();
  Vec pvec = dynamic_cast<FESystemNumerics::PetscVectorBase<T>&>(vec).getVec();
  ierr = VecGetArray (pvec, &vec_vals);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  for (unsigned int j=0; j < n_cols; j++)
    vec_vals[cols[j]] = row_vals[j];
  ierr = VecRestoreArray (pvec, &vec_vals);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = MatRestoreRow (this->petsc_mat, i, (PetscInt*) &(n_cols), (const PetscInt**) &(cols),
                        (const PetscScalar**) &(row_vals));
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::leftDiagonalScale (const FESystemNumerics::VectorBase< T > & vector) [inline, virtual]
multiplies the matrix with a diagonal matrix on the left hand side. The diagonal matrix is represented as a vector.
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 585 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscVectorBase< T >::getVec(), and FESystemNumerics::VectorBase< T >::getVectorPackage().
Referenced by RadiationCavityAnalysis::calculateB_Matrix(), and RadiationCavityAnalysis::getFEJacobianMatrix().
{
  Assert(vector.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscVectorBase<T>& vec =
    dynamic_cast<const FESystemNumerics::PetscVectorBase<T>&>(vector);
  const_cast<FESystemNumerics::PetscVectorBase<T>&>(vec).assemble();
  // create a temporary matrix to store the result in
  PetscErrorCode ierr = 0;
  ierr = MatDiagonalScale (this->petsc_mat, vec.getVec(), PETSC_NULL);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::leftMultiply (const FESystemNumerics::MatrixBase< T > & matrix) [inline, virtual]
Performs the operation: (*this) <- M2 * (*this)
Implements FESystemNumerics::MatrixBase< T >.
Reimplemented in FESystemNumerics::PetscSeqDenseMatrix< T >.
Definition at line 654 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscMatrixBase< T >::getMat(), and FESystemNumerics::MatrixBase< T >::getMatrixPackage().
{
  Assert(matrix.getMatrixPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscMatrixBase<T>& mat =
    dynamic_cast<const FESystemNumerics::PetscMatrixBase<T>&>(matrix);
  const_cast<FESystemNumerics::PetscMatrixBase<T>&>(mat).finalAssemble();
  // create a temporary matrix to store the result in
  Mat result_mat;
  PetscErrorCode ierr = 0;
  ierr = MatMatMult (mat.getMat(), this->petsc_mat, MAT_INITIAL_MATRIX, PETSC_DEFAULT,
                     &result_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // since Petsc will itself create the result matrix, we can destroy the matrix
  // of this object, and store the pointer of result_mat
  ierr = MatDestroy(this->petsc_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->petsc_mat = result_mat;
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::leftMultiplyTranspose (const FESystemNumerics::MatrixBase< T > & matrix) [inline, virtual]
Performs the operation: (*this) <- M2^T * (*this)
Implements FESystemNumerics::MatrixBase< T >.
Reimplemented in FESystemNumerics::PetscSeqDenseMatrix< T >.
Definition at line 698 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscMatrixBase< T >::getMat(), and FESystemNumerics::MatrixBase< T >::getMatrixPackage().
{
  Assert(matrix.getMatrixPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscMatrixBase<T>& mat =
    dynamic_cast<const FESystemNumerics::PetscMatrixBase<T>&>(matrix);
  const_cast<FESystemNumerics::PetscMatrixBase<T>&>(mat).finalAssemble();
  // create a temporary matrix to store the result in
  Mat result_mat;
  PetscErrorCode ierr = 0;
  ierr = MatMatMultTranspose(mat.getMat(), this->petsc_mat,
                             MAT_INITIAL_MATRIX, PETSC_DEFAULT, &result_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // since Petsc will itself create the result matrix, we can destroy the matrix
  // of this object, and store the pointer of result_mat
  ierr = MatDestroy(this->petsc_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->petsc_mat = result_mat;
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::leftMultiplyVector (const FESystemNumerics::VectorBase< T > & vector_in, FESystemNumerics::VectorBase< T > & result) [inline, virtual]
Performs the operation: (*this) <- M2 * (*this)
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 828 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscVectorBase< T >::getVec(), FESystemNumerics::VectorBase< T >::getVectorPackage(), and FESystemNumerics::PetscVectorBase< T >::zero().
Referenced by RadiationCavityAnalysis::getFENodalLoadVector(), and RadiationCavityAnalysis::getFENodalLoadVectorSensitivity().
{
  Assert(vector_in.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  Assert(result.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscVectorBase<T>& vec_in =
    dynamic_cast<const FESystemNumerics::PetscVectorBase<T>&>(vector_in);
  FESystemNumerics::PetscVectorBase<T>& vec_res =
    dynamic_cast<FESystemNumerics::PetscVectorBase<T>&>(result);
  const_cast<FESystemNumerics::PetscVectorBase<T>&>(vec_in).assemble();
  vec_res.zero();
  // create a temporary matrix to store the result in
  PetscErrorCode ierr = 0;
  ierr = MatMultTranspose(this->petsc_mat, vec_in.getVec(), vec_res.getVec());
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > unsigned int FESystemNumerics::PetscMatrixBase< T >::m () const [inline, virtual]
Returns:
the row-dimension of the matrix.
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 869 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateA_InverseMatrix(), RadiationCavityAnalysis::calculateA_Matrix(), RadiationCavityAnalysis::calculateB_InverseMatrix(), RadiationCavityAnalysis::calculateB_Matrix(), RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution(), RadiationCavityAnalysis::calculateG_Matrix(), RadiationCavityAnalysis::calculateShapeFactorMatrix(), RadiationCavityAnalysis::getFEJacobianMatrix(), RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector(), and Discipline::ThermalAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  PetscErrorCode ierr;
  PetscInt num1=0, num2=0;
  ierr = MatGetSize (this->petsc_mat, &num1, &num2);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  return num1;
}
template<typename T > unsigned int FESystemNumerics::PetscMatrixBase< T >::n () const [inline, virtual]
Returns:
the column-dimension of the matrix.
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 883 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateA_InverseMatrix(), RadiationCavityAnalysis::calculateA_Matrix(), RadiationCavityAnalysis::calculateB_InverseMatrix(), RadiationCavityAnalysis::calculateB_Matrix(), RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution(), RadiationCavityAnalysis::calculateG_Matrix(), RadiationCavityAnalysis::calculateShapeFactorMatrix(), RadiationCavityAnalysis::getFEJacobianMatrix(), RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector(), and Discipline::ThermalAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  PetscErrorCode ierr;
  PetscInt num1=0, num2=0;
  ierr = MatGetSize (this->petsc_mat, &num1, &num2);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  return num2;
}
template<typename T> virtual void FESystemNumerics::PetscMatrixBase< T >::resize (const unsigned int m, const unsigned int n) [pure virtual]
resize the matrix in the given dimensions
Implements FESystemNumerics::MatrixBase< T >.
Implemented in FESystemNumerics::PetscSeqDenseMatrix< T >.
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::rightDiagonalScale (const FESystemNumerics::VectorBase< T > & vector) [inline, virtual]
multiplies the matrix with a diagonal matrix on the right hand side. The diagonal matrix is represented as a vector.
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 619 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscVectorBase< T >::getVec(), and FESystemNumerics::VectorBase< T >::getVectorPackage().
{
  Assert(vector.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscVectorBase<T>& vec =
    dynamic_cast<const FESystemNumerics::PetscVectorBase<T>&>(vector);
  const_cast<FESystemNumerics::PetscVectorBase<T>&>(vec).assemble();
  // create a temporary matrix to store the result in
  PetscErrorCode ierr = 0;
  ierr = MatDiagonalScale (this->petsc_mat, PETSC_NULL, vec.getVec());
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::rightMultiply (const FESystemNumerics::MatrixBase< T > & matrix) [inline, virtual]
Performs the operation: (*this) <- (*this) * M3
Implements FESystemNumerics::MatrixBase< T >.
Reimplemented in FESystemNumerics::PetscSeqDenseMatrix< T >.
Definition at line 742 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscMatrixBase< T >::getMat(), and FESystemNumerics::MatrixBase< T >::getMatrixPackage().
{
  Assert(matrix.getMatrixPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscMatrixBase<T>& mat =
    dynamic_cast<const FESystemNumerics::PetscMatrixBase<T>&>(matrix);
  const_cast<FESystemNumerics::PetscMatrixBase<T>&>(mat).finalAssemble();
  // create a temporary matrix to store the result in
  Mat result_mat;
  PetscErrorCode ierr = 0;
  ierr = MatMatMult (this->petsc_mat, mat.getMat(), MAT_INITIAL_MATRIX, PETSC_DEFAULT, &result_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // since Petsc will itself create the result matrix, we can destroy the matrix
  // of this object, and store the pointer of result_mat
  ierr = MatDestroy(this->petsc_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->petsc_mat = result_mat;
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::rightMultiplyVector (const FESystemNumerics::VectorBase< T > & vector_in, FESystemNumerics::VectorBase< T > & result) [inline, virtual]
Performs the operation: (*this) <- M2 * (*this)
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 786 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscVectorBase< T >::getVec(), FESystemNumerics::VectorBase< T >::getVectorPackage(), and FESystemNumerics::PetscVectorBase< T >::zero().
Referenced by RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution(), RadiationCavityAnalysis::getFENodalLoadVector(), and RadiationCavityAnalysis::getFENodalLoadVectorSensitivity().
{
  Assert(vector_in.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  Assert(result.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscVectorBase<T>& vec_in =
    dynamic_cast<const FESystemNumerics::PetscVectorBase<T>&>(vector_in);
  FESystemNumerics::PetscVectorBase<T>& vec_res =
    dynamic_cast<FESystemNumerics::PetscVectorBase<T>&>(result);
  const_cast<FESystemNumerics::PetscVectorBase<T>&>(vec_in).assemble();
  vec_res.zero();
  // create a temporary matrix to store the result in
  PetscErrorCode ierr = 0;
  ierr = MatMult(this->petsc_mat, vec_in.getVec(), vec_res.getVec());
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::scale (const T factor) [inline, virtual]
Adds to this matrix Adds to this matrix multiplies factor to every element in the matrix.
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 1043 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateA_Matrix(), RadiationCavityAnalysis::calculateG_Matrix(), and RadiationCavityAnalysis::calculateShapeFactorMatrix().
{
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = MatScale (this->petsc_mat, factor);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::set (const unsigned int i, const unsigned int j, const T val) [inline, virtual]
sets the given element to
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 425 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateA_InverseMatrix(), RadiationCavityAnalysis::calculateB_InverseMatrix(), and RadiationCavityAnalysis::calculateShapeFactorMatrix().
{
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
      this->flushAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = MatSetValue (this->petsc_mat, i, j,
                       val, INSERT_VALUES);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->matrix_last_action = FESystemNumerics::PetscMatrixBase<T>::INSERT;
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::set (const std::vector< unsigned int > & i, const std::vector< unsigned int > & j, const T * val) [inline, virtual]
sets multiple elements with the indeces given in i and j. The val should be a 2-D matrix of dimensions equal to size of vectors i and j.
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 455 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
{
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
      this->flushAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = MatSetValues (this->petsc_mat, i.size(), (const PetscInt*) &(i[0]),
                       j.size(),  (const PetscInt*) &(j[0]),
                      val, INSERT_VALUES);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->matrix_last_action = FESystemNumerics::PetscMatrixBase<T>::INSERT;
}
template<typename T> virtual void FESystemNumerics::PetscMatrixBase< T >::setRow (const unsigned row_num, const FESystemNumerics::PetscVectorBase< T > & vector) [virtual]
Adds to this matrix
Referenced by RadiationCavityAnalysis::calculateG_Matrix(), and RadiationCavityAnalysis::getFEJacobianMatrix().
template<typename T> virtual void FESystemNumerics::PetscMatrixBase< T >::setRow (const unsigned row_num, const std::vector< unsigned int > & col_ids, const FESystemNumerics::PetscVectorBase< T > & vector) [virtual]
Adds to this matrix
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::shift (const T val) [inline, virtual]
adds val to all diagonal elements of the matrix
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 399 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateA_Matrix().
{
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = MatShift (this->petsc_mat, val);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > void FESystemNumerics::PetscMatrixBase< T >::zero () [inline, virtual]
Set every element in the matrix to 0. You must redefine what you mean by zeroing the matrix since it depends on how your values are stored.
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 267 of file PetscMatrixBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateA_InverseMatrix(), RadiationCavityAnalysis::calculateA_Matrix(), RadiationCavityAnalysis::calculateABInvFactorMatrix(), RadiationCavityAnalysis::calculateB_InverseMatrix(), RadiationCavityAnalysis::calculateB_Matrix(), RadiationCavityAnalysis::calculateFactorMatrix(), RadiationCavityAnalysis::calculateG_Matrix(), RadiationCavityAnalysis::calculateShapeFactorMatrix(), RadiationCavityAnalysis::getFEJacobianMatrix(), and FESystemNumerics::PetscSeqDenseMatrix< T >::PetscSeqDenseMatrix().
{
  PetscErrorCode ierr;
  ierr = MatZeroEntries(this->petsc_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->finalAssemble();
}
Member Data Documentation
template<typename T> LastAction FESystemNumerics::PetscMatrixBase< T >::matrix_last_action [protected]
last action performed, to decide whether to flush the matrix operations or not
Definition at line 231 of file PetscMatrixBase.h.
template<typename T> Mat FESystemNumerics::PetscMatrixBase< T >::petsc_mat [protected]
Petsc matrix data structure.
Definition at line 234 of file PetscMatrixBase.h.
Referenced by FESystemNumerics::PetscSeqDenseMatrix< T >::PetscSeqDenseMatrix().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Numerics/PetscMatrixBase.h