fesystem: Driver::TransientAnalysisDriver Class Reference
Driver::TransientAnalysisDriver Class Reference
this forms the basis of all transient analysis drivers.
#include <TransientAnalysisDriver.h>
Public Member Functions
TransientAnalysisDriver (const unsigned int ID, FESystem::FESystemController &controller, const unsigned int driver_enum_ID)
constructor
virtual ~TransientAnalysisDriver ()
destructor
double getCurrentAnalysisTime () const
double getSimulatedTime () const
current simulation time is the time that has been solved for the system
unsigned int getSimulatedIterationNumber () const
unsigned int getCurrentIterationNumber () const
virtual void clear ()
clears the data structures of this object
void setNewIteration (const double time, const unsigned int iter_num, const std::vector< NumericVector< double > * > &iter_sols)
virtual void getCoefficientMatrices (const double time, std::vector< SparseMatrix< double > * > &matrices)=0
virtual void getForceVector (const double time, NumericVector< double > &vector)=0
Protected Member Functions
void setInitialConditionForCurrentLoadCase (std::vector< NumericVector< double > * > &vector)
method sets the initial guess for the nonlinear solver
Protected Attributes
double current_analysis_time
current time of analysis
std::vector< double > time_values
vector of time instants for the transient iterations
Detailed Description
this forms the basis of all transient analysis drivers.
Definition at line 140 of file TransientAnalysisDriver.h.
Constructor & Destructor Documentation
Driver::TransientAnalysisDriver::TransientAnalysisDriver (const unsigned int ID, FESystem::FESystemController & controller, const unsigned int driver_enum_ID)
constructor
Definition at line 34 of file TransientAnalysisDriver.C.
                                   :
Driver::AnalysisDriver(ID, fesys_controller, driver_enum_ID),
current_analysis_time(0.0)
{
}
Driver::TransientAnalysisDriver::~TransientAnalysisDriver () [virtual]
destructor
Definition at line 47 of file TransientAnalysisDriver.C.
{
}
Member Function Documentation
void Driver::TransientAnalysisDriver::clear () [virtual]
clears the data structures of this object
Reimplemented from Driver::AnalysisDriver.
Definition at line 55 of file TransientAnalysisDriver.C.
References Driver::AnalysisDriver::clear().
Referenced by Solver::NewmarkNonlinearTransientSolver::solve().
{
  this->current_analysis_time = 0.0;
  this->time_values.clear();
  Driver::AnalysisDriver::clear();
}
virtual void Driver::TransientAnalysisDriver::getCoefficientMatrices (const double time, std::vector< SparseMatrix< double > * > & matrices) [pure virtual]
calculate the coefficient matrices. The location of the matrix is also the order of the time derivative vector
Implemented in Driver::NonlinearTransientAnalysisDriver, and Driver::LinearTransientAnalysisDriver.
double Driver::TransientAnalysisDriver::getCurrentAnalysisTime () const
Returns:
the current time for calculation of system quantitites. This will not necessarily be the same as the simulation time, since the solver might be going through sub-iterations for each time step. For actual simulation time that has been traversed, use the method currentSimulationTime();
Definition at line 66 of file TransientAnalysisDriver.C.
Referenced by Discipline::FluidAnalysis::getDataInfoForQty(), Discipline::StructuralAnalysis::getDataInfoForQty(), Discipline::ThermalAnalysis::getDataInfoForQty(), RadiationCavityAnalysis::getDataInfoForQty(), Discipline::ThermalAnalysis::getSolutionVector(), Discipline::FluidAnalysis::performAdditionalOperationsOnGlobalQuantities(), and Discipline::StructuralAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  return this->current_analysis_time;
}
unsigned int Driver::TransientAnalysisDriver::getCurrentIterationNumber () const
Returns:
the iteration number for which current quantities are being calculated
Definition at line 81 of file TransientAnalysisDriver.C.
Referenced by Discipline::FluidAnalysis::getDataInfoForQty(), Discipline::StructuralAnalysis::getDataInfoForQty(), Discipline::ThermalAnalysis::getDataInfoForQty(), RadiationCavityAnalysis::getDataInfoForQty(), and Discipline::ThermalAnalysis::getSolutionVector().
{
  return dynamic_cast<Solver::TransientSolverBase*>(this->solver)->getCurrentIterationNumber();
}
virtual void Driver::TransientAnalysisDriver::getForceVector (const double time, NumericVector< double > & vector) [pure virtual]
calculate the coefficient matrices. The location of the matrix is also the order of the time derivative vector
Implemented in Driver::NonlinearTransientAnalysisDriver, and Driver::LinearTransientAnalysisDriver.
unsigned int Driver::TransientAnalysisDriver::getSimulatedIterationNumber () const
Returns:
the iteration number for which solutions are available
Definition at line 88 of file TransientAnalysisDriver.C.
{
  return dynamic_cast<Solver::TransientSolverBase*>(this->solver)->getSimulatedIterationNumber();
}
double Driver::TransientAnalysisDriver::getSimulatedTime () const
current simulation time is the time that has been solved for the system
Definition at line 73 of file TransientAnalysisDriver.C.
{
  return dynamic_cast<Solver::TransientSolverBase*>(this->solver)->getSimulatedTime();
}
void Driver::TransientAnalysisDriver::setInitialConditionForCurrentLoadCase (std::vector< NumericVector< double > * > & vector) [protected]
method sets the initial guess for the nonlinear solver
Definition at line 157 of file TransientAnalysisDriver.C.
References ANALYSIS_ENUM_ID, and SENSITIVITY_ANALYSIS_ENUM_ID.
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  unsigned int order = it->second->getTransientSystemOrder();
  // make sure that the right number of vectors are given
  Assert(order > 0 , ExcInternalError());
  Assert(vectors.size() == order,       ExcInternalError());
  // get references to the necessary data strucutres
  LoadDatabase& load_database = *(this->fesystem_controller.load_database.get());
  const MeshDS::FEMeshData& mesh_data = it->second->getAnalysisMeshData();
  // set the value of the vector to the initialization value/vector
  // specified in the input file
  //   // first check the method that has been specified for initialization
  //   std::string method =
  //     this->fesystem_controller.analysis_case->getStringParameter("SOL_VECTOR_INIT_METHOD");
  //   if (method == "VALUE")
  //     {
  //       double init_value =
  //    this->fesystem_controller.analysis_case->getRealParameter("SOL_VECTOR_INIT_VALUE");
  //       Vec sol_vec = dynamic_cast<PetscVector<double>&>(vector).vec();
  //       VecSet(sol_vec, init_value);
  //     }
  //   else if (method == "VECTOR")
  //     {
  //       // this needs to be implemented.
  //       Assert(false, ExcInternalError());
  //       //     std::string vec_name =
  //       //     this->fesystem_controller.analysis_case->getStringParameter("SOL_VECTOR_INIT_VECTOR_FILE");
  //       //     unsigned int load_case = this->getCurrentLoadCase();
  //       //     this->fesystem_controller.global_data_storage->fillVector(load_case, vec_name, vector);
  //     }
  switch (this->current_analysis_kind_enum_ID)
  {
    case ANALYSIS_ENUM_ID:
    case SENSITIVITY_ANALYSIS_ENUM_ID:
    {
      // the Initial conditions for now, are being hardcoded as zero, but will be changesd later
      for (unsigned int i=0; i < order; i++)
        {
          vectors[i]->zero();
          vectors[i]->perform_intermediate_vector_assembly();
          if (i==0)
            this->applyBoundaryConditionsToVectorForCurrentAnalysis(*(vectors[i]), true, it->second->getDisciplineEnumID());
          else
            this->applyBoundaryConditionsToVectorForCurrentAnalysis(*(vectors[i]), false, it->second->getDisciplineEnumID());
          vectors[i]->close();
        }
    }
      break;
    default:
      Assert(false, ExcInternalError());
  }
}
void Driver::TransientAnalysisDriver::setNewIteration (const double time, const unsigned int iter_num, const std::vector< NumericVector< double > * > & iter_sols)
Reimplemented in Driver::UpdatedLagrangianNonlinearStructuralAnalysisDriver.
Definition at line 96 of file TransientAnalysisDriver.C.
References ANALYSIS_ENUM_ID, FESystemDatabase::TimeDependentDataInfo::clear(), and SENSITIVITY_ANALYSIS_ENUM_ID.
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  // make sure that the numbers make some sense
  Assert(time == this->getSimulatedTime() && iter_num == this->getSimulatedIterationNumber(),
         ExcInternalError());
  // depending upon the kind of analysis, check the iteration time
  switch (this->current_analysis_kind_enum_ID)
  {
    case ANALYSIS_ENUM_ID:
      this->time_values.push_back(time);
      break;
    case SENSITIVITY_ANALYSIS_ENUM_ID:
      Assert(time == this->time_values[iter_num-1], ExcInternalError());
      break;
    default:
      Assert(false, ExcInternalError());
  }
  // make sure that the number of solutions in the vector is same as the order of the
  // system
  unsigned int order = it->second->getTransientSystemOrder();
  Assert(sol_vec.size() == (order+1),
         ExcInternalError());
  FESystemDatabase::TimeDependentDataInfo data_info;
  // now store the solution vector
  for (unsigned int i=0; i <= order; i++)
    {
      data_info.clear();
      data_info.setDisciplineEnumID(it->second->getDisciplineEnumID());
      data_info.setName("Solution");
      data_info.setOrder(i);
      if (this->current_analysis_kind_enum_ID == SENSITIVITY_ANALYSIS::num())
        data_info.setDVID(this->getCurrentDesignParameter().getID());
      data_info.setLoadCase(this->current_load_case);
      data_info.setTransientIterationInfo(iter_num, time);
      this->fesystem_controller.global_data_storage->storeVector(data_info, *(sol_vec[i]));
      this->writeSolutionVectorToLog(data_info, *(sol_vec[i]), it->second->getDisciplineEnumID());
    }
}
Member Data Documentation
double Driver::TransientAnalysisDriver::current_analysis_time [protected]
current time of analysis
Definition at line 190 of file TransientAnalysisDriver.h.
std::vector<double> Driver::TransientAnalysisDriver::time_values [protected]
vector of time instants for the transient iterations
Definition at line 193 of file TransientAnalysisDriver.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/AnalysisDriver/TransientAnalysisDriver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/AnalysisDriver/TransientAnalysisDriver.C