fesystem: DesignData::DesignParameter Class Reference
DesignData::DesignParameter Class Reference
this class forms the base class for all design parameters.
#include <DesignParameter.h>
Public Member Functions
DesignParameter ()
virtual ~DesignParameter ()
const unsigned int getID () const
const std::string & getName () const
virtual const unsigned int getParameterTypeEnumID () const =0
virtual const std::string getParameterTypeEnumName () const =0
const unsigned int getSensitivityMethodEnumID () const
const std::string getSensitivityMethodEnumName () const
const double getValue () const
const double getPerturbationStepSize () const
Protected Member Functions
virtual std::istream & readFromInputStream (std::istream &input)=0
DeclException0 (ExcFESystemNonFDSensitivity)
Protected Attributes
unsigned int ID
std::string name
double value
unsigned int sensitivity_method
double finite_difference_step_size
Detailed Description
this class forms the base class for all design parameters.
Definition at line 63 of file DesignParameter.h.
Constructor & Destructor Documentation
DesignData::DesignParameter::DesignParameter ()
Definition at line 7 of file DesignParameter.C.
                                          :
ID(FESystemNumbers::InvalidID),
name(),
value(0.0),
sensitivity_method(FESystemNumbers::InvalidID),
finite_difference_step_size(0.0)
{}
DesignData::DesignParameter::~DesignParameter () [virtual]
Definition at line 16 of file DesignParameter.C.
{}
Member Function Documentation
DesignData::DesignParameter::DeclException0 (ExcFESystemNonFDSensitivity) [protected]
const unsigned int DesignData::DesignParameter::getID () const [inline]
Definition at line 109 of file DesignParameter.h.
References ID, and FESystemNumbers::InvalidID.
Referenced by DesignData::DesignDatabase::addParameterToDatabase(), RadiationCavityAnalysis::calculateB_Matrix(), RadiationCavityAnalysis::calculateG_Matrix(), Discipline::AnalysisDisciplineBase::calculateGlobalQty(), RadiationCavityAnalysis::calculateRadElemTempVector(), RadiationCavityAnalysis::calculateShapeFactorMatrix(), RadiationCavityAnalysis::getDataInfoForQty(), FEInterpolationAnalysis::getStringNameForQty(), and RadiationCavityAnalysis::RadiationCavityAnalysis().
{
  // make sure that the ID is a valid number before returning it
  Assert(this->ID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(this->ID));
  return this->ID;
}
const std::string & DesignData::DesignParameter::getName () const [inline]
Definition at line 121 of file DesignParameter.h.
{return this->name;}
virtual const unsigned int DesignData::DesignParameter::getParameterTypeEnumID () const [pure virtual]
Implemented in DesignData::ShapeParameter, and DesignData::PropertyParameter.
Referenced by RadiationCavityAnalysis::calculateA_Matrix(), RadiationCavityAnalysis::calculateB_Matrix(), RadiationCavityAnalysis::calculateG_Matrix(), Discipline::AnalysisDisciplineBase::calculateGlobalQty(), RadiationCavityAnalysis::calculateRadElemTempVector(), RadiationCavityAnalysis::calculateShapeFactorMatrix(), and RadiationCavityAnalysis::getFENodalLoadVectorSensitivity().
virtual const std::string DesignData::DesignParameter::getParameterTypeEnumName () const [pure virtual]
Implemented in DesignData::ShapeParameter, and DesignData::PropertyParameter.
const double DesignData::DesignParameter::getPerturbationStepSize () const [inline]
Definition at line 146 of file DesignParameter.h.
Referenced by RadiationCavityAnalysis::calculateG_Matrix(), Discipline::AnalysisDisciplineBase::calculateGlobalQty(), RadiationCavityAnalysis::calculateRadElemTempVector(), and RadiationCavityAnalysis::calculateShapeFactorMatrix().
{
  // make sure that the sensitivity method is finite difference before
  // returning the step size
  Assert(this->sensitivity_method == DesignData::EULER_FD_SENSITIVITY::num(),
         ExcFESystemNonFDSensitivity());
  return this->finite_difference_step_size;
}
const unsigned int DesignData::DesignParameter::getSensitivityMethodEnumID () const [inline]
Definition at line 127 of file DesignParameter.h.
{return this->sensitivity_method;}
const std::string DesignData::DesignParameter::getSensitivityMethodEnumName () const [inline]
Definition at line 133 of file DesignParameter.h.
{return DesignData::SensitivityMethodEnum::enumName(this->sensitivity_method);}
const double DesignData::DesignParameter::getValue () const [inline]
Definition at line 138 of file DesignParameter.h.
{
  return this->value;
}
virtual std::istream& DesignData::DesignParameter::readFromInputStream (std::istream & input) [protected, pure virtual]
Implemented in DesignData::PropertyParameter, and DesignData::ShapeParameter.
Member Data Documentation
double DesignData::DesignParameter::finite_difference_step_size [protected]
Definition at line 98 of file DesignParameter.h.
unsigned int DesignData::DesignParameter::ID [protected]
Definition at line 90 of file DesignParameter.h.
Referenced by getID().
std::string DesignData::DesignParameter::name [protected]
Definition at line 92 of file DesignParameter.h.
unsigned int DesignData::DesignParameter::sensitivity_method [protected]
Definition at line 96 of file DesignParameter.h.
double DesignData::DesignParameter::value [protected]
Definition at line 94 of file DesignParameter.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/DesignData/DesignParameter.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/DesignData/DesignParameter.C