fesystem: Loads::SurfaceLoadDataInfo Class Reference
Loads::SurfaceLoadDataInfo Class Reference
#include <LoadDataInfo.h>
Public Member Functions
SurfaceLoadDataInfo ()
virtual ~SurfaceLoadDataInfo ()
virtual void clear ()
void setSurfaceID (const unsigned int ID)
unsigned int getSurfaceID () const
Protected Attributes
unsigned int surface_ID
Detailed Description
Definition at line 122 of file LoadDataInfo.h.
Constructor & Destructor Documentation
Loads::SurfaceLoadDataInfo::SurfaceLoadDataInfo ()
Definition at line 248 of file LoadDataInfo.C.
                                             :
Loads::ElemLoadDataInfo(),
surface_ID(FESystemNumbers::InvalidID)
{
}
Loads::SurfaceLoadDataInfo::~SurfaceLoadDataInfo () [virtual]
Definition at line 258 of file LoadDataInfo.C.
{
  this->clear();
}
Member Function Documentation
void Loads::SurfaceLoadDataInfo::clear () [virtual]
Reimplemented from Loads::ElemLoadDataInfo.
Definition at line 267 of file LoadDataInfo.C.
References Loads::ElemLoadDataInfo::clear(), and FESystemNumbers::InvalidID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads().
{
  this->surface_ID = FESystemNumbers::InvalidID;
  Loads::ElemLoadDataInfo::clear();
}
unsigned int Loads::SurfaceLoadDataInfo::getSurfaceID () const
Definition at line 284 of file LoadDataInfo.C.
Referenced by LoadDatabase::getLoadCombination< Loads::SurfaceLoadDataInfo, Loads::SurfaceLoadCombination >().
{
  return this->surface_ID;
}
void Loads::SurfaceLoadDataInfo::setSurfaceID (const unsigned int ID)
Definition at line 276 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads().
{
  Assert(this->surface_ID == FESystemNumbers::InvalidID, ExcInternalError());
  this->surface_ID = ID;
}
Member Data Documentation
unsigned int Loads::SurfaceLoadDataInfo::surface_ID [protected]
Definition at line 137 of file LoadDataInfo.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadDataInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadDataInfo.C