fesystem: NodalLoadSet Class Reference
NodalLoadSet Class Reference
#include <LoadSet.h>
Public Member Functions
NodalLoadSet ()
~NodalLoadSet ()
virtual unsigned int getLoadSetKindEnumID () const
void getLoadsForNode (const unsigned int, std::vector< const NodalLoad * > &loads) const
void getAllLoads (std::vector< const NodalLoad * > &loads) const
virtual std::istream & readFromInputStream (std::istream &)
Protected Attributes
std::multimap< unsigned int,
NodalLoad * > node_ID_to_load_map
Detailed Description
Definition at line 221 of file LoadSet.h.
Constructor & Destructor Documentation
NodalLoadSet::NodalLoadSet ()
Definition at line 169 of file LoadSet.C.
                          :
  LoadSetBase()
{
}
NodalLoadSet::~NodalLoadSet ()
Definition at line 177 of file LoadSet.C.
References node_ID_to_load_map.
{
  // iterate over all loads and delete them
  std::multimap<unsigned int, NodalLoad*>::iterator it, end;
  it = this->node_ID_to_load_map.begin();
  end = this->node_ID_to_load_map.end();
  for (; it != end; it++)
    {
      delete it->second;
      it->second = NULL;
    }
  this->node_ID_to_load_map.clear();
}
Member Function Documentation
void NodalLoadSet::getAllLoads (std::vector< const NodalLoad * > & loads) const
Definition at line 219 of file LoadSet.C.
References node_ID_to_load_map.
Referenced by LoadDatabase::getAllLoadCombinations< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >().
{
  std::multimap<unsigned int, NodalLoad*>::const_iterator it, end;
  it = this->node_ID_to_load_map.begin();
  end = this->node_ID_to_load_map.end();
  loads.resize(this->node_ID_to_load_map.size());
  unsigned int i=0;
  for (; it != end; it++)
    {
      loads[i] = it->second;
      i++;
    }
}
unsigned int NodalLoadSet::getLoadSetKindEnumID () const [virtual]
Implements LoadSetBase.
Definition at line 196 of file LoadSet.C.
{
  return NODAL_LOAD_SET::num();
}
void NodalLoadSet::getLoadsForNode (const unsigned int elem_ID, std::vector< const NodalLoad * > & loads) const
This will search the loads in this set and add create a vector containing loads that act on a node
Definition at line 205 of file LoadSet.C.
References node_ID_to_load_map.
Referenced by LoadDatabase::getLoadCombination< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >().
{
  std::multimap<unsigned int, NodalLoad*>::const_iterator it, end;
  it = this->node_ID_to_load_map.lower_bound(elem_ID);
  end = this->node_ID_to_load_map.upper_bound(elem_ID);
  for ( ; it != end; it++)
    loads.push_back(it->second);
}
std::istream & NodalLoadSet::readFromInputStream (std::istream & input) [virtual]
Implements LoadSetBase.
Definition at line 236 of file LoadSet.C.
References createNodalLoad(), getLoadClassEnumIDForLoadName(), LoadSetBase::load_kind_enum_ID, LoadSetBase::load_set_ID, node_ID_to_load_map, FESystemIOUtility::readFromInput(), and LoadSetBase::set_tag.
{
  std::string tag;
  unsigned int n_loads=0, n_dofs=0, node_ID = 0, load_class_enum_ID = 0;
  // the load set should begin with the BEGIN tag, and followed by
  // the number of loads in the set
  FESystemIOUtility::readFromInput(input, NODAL_LOAD_SET::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  // next, it should contain the name, ID and kind, and number of DOFs of load
  FESystemIOUtility::readFromInput(input, "NAME", this->set_tag);
  FESystemIOUtility::readFromInput(input, "ID", this->load_set_ID);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "KIND", tag);
  this->load_kind_enum_ID = LoadNameEnum::enumID(tag);
  load_class_enum_ID = getLoadClassEnumIDForLoadName(this->load_kind_enum_ID);
  FESystemIOUtility::readFromInput(input, "N_DOFS", n_dofs);
  FESystemIOUtility::readFromInput(input, "N_LOADS", n_loads);
  std::auto_ptr<NodalLoad> load;
  for (unsigned int load_incr=0; load_incr < n_loads; load_incr++)
    {
      load.reset(createNodalLoad(load_class_enum_ID, n_dofs).release());
      load->readFromInputStream(input);
      node_ID = load->getNodeID();
      this->node_ID_to_load_map.insert
        (std::multimap<unsigned int, NodalLoad*>::value_type
         (node_ID, load.release()));
    }
  FESystemIOUtility::readFromInput(input, NODAL_LOAD_SET::name());
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Member Data Documentation
std::multimap<unsigned int, NodalLoad*> NodalLoadSet::node_ID_to_load_map [protected]
Definition at line 241 of file LoadSet.h.
Referenced by getAllLoads(), getLoadsForNode(), readFromInputStream(), and ~NodalLoadSet().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadSet.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadSet.C