fesystem: Solver::NewmarkLinearTransientSolver Class Reference
Solver::NewmarkLinearTransientSolver Class Reference
#include <NewmarkTransientSolver.h>
Public Member Functions
NewmarkLinearTransientSolver (const Solver::LinearTransientSolverInfo &transient_info, const Solver::LinearSolverInfo &linear_info)
constructor
virtual ~NewmarkLinearTransientSolver ()
virtual void clear ()
virtual void solve ()
method to solve the eigen system
virtual double getSimulatedTime ()
virtual double getCurrentTime ()
virtual double getCurrentStepSize ()
virtual unsigned int getSimulatedIterationNumber ()
virtual unsigned int getCurrentIterationNumber ()
virtual void setInitialCondition (std::vector< NumericVector< double > * > &state_vecs)
set initial conditions for the analysis
Protected Attributes
double simulated_time
simulated time
double current_time
current time
double time_step_size
current step size
unsigned int simulated_iteration_number
simulated iteration number
std::auto_ptr
< Solver::LinearSolver > linear_solver
linear solver
std::vector< double > newmark_constants
FESystemUtility::AutoPtrVector
< NumericVector< double > > current_state_vectors
FESystemUtility::AutoPtrVector
< NumericVector< double > > new_state_vectors
Detailed Description
this class provides an interface to a solver for the solution of eigensystem. This inherits from the FESystemSolverBase class. It takes a pointer to the analysis driver object that owns an instantiation of this class
Definition at line 79 of file NewmarkTransientSolver.h.
Constructor & Destructor Documentation
Solver::NewmarkLinearTransientSolver::NewmarkLinearTransientSolver (const Solver::LinearTransientSolverInfo & transient_info, const Solver::LinearSolverInfo & linear_info)
constructor
Definition at line 17 of file NewmarkTransientSolver.C.
                                           :
Solver::LinearTransientSolverBase(transient_info, linear_info),
simulated_time(0.0),
current_time(0.0),
time_step_size(0.0),
simulated_iteration_number(0)
{
}
Solver::NewmarkLinearTransientSolver::~NewmarkLinearTransientSolver () [virtual]
Definition at line 29 of file NewmarkTransientSolver.C.
{
}
Member Function Documentation
void Solver::NewmarkLinearTransientSolver::clear () [virtual]
this method clears the data structures of this object. This should be called each time the used finishes using this object.
Reimplemented from Solver::LinearTransientSolverBase.
Definition at line 38 of file NewmarkTransientSolver.C.
References Solver::LinearTransientSolverBase::clear().
{
  this->simulated_time = 0.0;
  this->current_time = 0.0;
  this->time_step_size = 0.0;
  this->simulated_iteration_number = 0;
  this->current_state_vectors.clear();
  this->new_state_vectors.clear();
  Solver::LinearTransientSolverBase::clear();
}
unsigned int Solver::NewmarkLinearTransientSolver::getCurrentIterationNumber () [virtual]
Returns:
the current time iteration of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 298 of file NewmarkTransientSolver.C.
{
  return this->simulated_iteration_number + 1;
}
double Solver::NewmarkLinearTransientSolver::getCurrentStepSize () [virtual]
Returns:
the current time step of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 281 of file NewmarkTransientSolver.C.
{
  return this->time_step_size;
}
double Solver::NewmarkLinearTransientSolver::getCurrentTime () [virtual]
Returns:
the current time of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 267 of file NewmarkTransientSolver.C.
{
  return this->current_time;
}
unsigned int Solver::NewmarkLinearTransientSolver::getSimulatedIterationNumber () [virtual]
Returns:
the current time iteration of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 290 of file NewmarkTransientSolver.C.
{
  return this->simulated_iteration_number;
}
double Solver::NewmarkLinearTransientSolver::getSimulatedTime () [virtual]
Returns:
the current time of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 274 of file NewmarkTransientSolver.C.
{
  return this->simulated_time;
}
void Solver::NewmarkLinearTransientSolver::setInitialCondition (std::vector< NumericVector< double > * > & state_vecs) [virtual]
set initial conditions for the analysis
Implements Solver::TransientSolverBase.
Definition at line 219 of file NewmarkTransientSolver.C.
{
  // make sure that the current solutions have not been initialized
  Assert(this->current_state_vectors.size() == 0, ExcInternalError());
  Assert(this->new_state_vectors.size() == 0, ExcInternalError());
  unsigned int system_order =
  dynamic_cast<const Solver::NewmarkLinearTransientSolverInfo&>(this->transient_solver_info).getSystemOrder();
  // make sure that the number of vectors provided are one less than the system order
  Assert(state_vecs.size() == system_order,
         ExcInternalError());
  this->current_state_vectors.resize(system_order+1);
  this->new_state_vectors.resize(system_order+1);
  std::auto_ptr<NumericVector<double> > vec;
  for (unsigned int i=0; i < system_order; i++)
    {
      vec.reset(NumericVector<double>::build().release());
      vec->duplicate_vector(*(state_vecs[i]), true);
      vec->close();
      this->current_state_vectors.reset(i, vec.release());
      vec.reset(NumericVector<double>::build().release());
      vec->duplicate_vector(*(state_vecs[i]), false);
      vec->close();
      this->new_state_vectors.reset(i, vec.release());
    }
  // finally, insert the highest order vectors. These vectors are later calculate from
  // the initial conditions.
  vec.reset(NumericVector<double>::build().release());
  vec->duplicate_vector(*(state_vecs[0]), false);
  vec->close();
  this->current_state_vectors.reset(system_order, vec.release());
  vec.reset(NumericVector<double>::build().release());
  vec->duplicate_vector(*(state_vecs[0]), false);
  vec->close();
  this->new_state_vectors.reset(system_order, vec.release());
}
void Solver::NewmarkLinearTransientSolver::solve () [virtual]
method to solve the eigen system
Implements Solver::TransientSolverBase.
Definition at line 54 of file NewmarkTransientSolver.C.
References Solver::createLinearSolver(), Driver::AnalysisDriver::getFESystemController(), Solver::NewmarkLinearTransientSolverInfo::getSystemOrder(), Solver::NewmarkSolver::initNewmarkConstants(), Solver::NewmarkSolver::initNewmarkForceVector(), Solver::NewmarkSolver::initNewmarkStiffnessMatrix(), FESystem::FESystemController::performance_logging, and Solver::NewmarkSolver::updateStateVectors().
{
  this->linear_solver.reset(Solver::createLinearSolver(this->linear_solver_info).release());
  this->linear_solver->attachAnalysisDriver(this->analysis_driver);
  const Solver::NewmarkLinearTransientSolverInfo& newmark_info =
  dynamic_cast<const Solver::NewmarkLinearTransientSolverInfo&>(this->transient_solver_info);
  unsigned int system_order = newmark_info.getSystemOrder();
  // make sure that the solver has the necessary information
  Assert(this->coefficient_matrices.size() == (system_order+1), ExcInternalError());
  Assert(this->current_state_vectors.size() == (system_order+1), ExcInternalError());
  Assert(this->new_state_vectors.size() == (system_order+1), ExcInternalError());
  this->analysis_driver->getFESystemController().performance_logging->setEvent
  ("NewmarkLinearTransientSolver::solve()", "Solver");
  // create the vectors to be used in this solution
  std::auto_ptr<NumericVector<double> >
  external_force_vector(NumericVector<double>::build().release()),
  scratch_vec1(NumericVector<double>::build().release()),
  scratch_vec2(NumericVector<double>::build().release()),
  newmark_force_vector(NumericVector<double>::build().release());
  external_force_vector->duplicate_vector(*(this->current_state_vectors[0]), false);
  scratch_vec1->duplicate_vector(*(this->current_state_vectors[0]), false);
  scratch_vec2->duplicate_vector(*(this->current_state_vectors[0]), false);
  newmark_force_vector->duplicate_vector(*(this->current_state_vectors[0]), false);
  // create the temporary matrix for calculation of the Newmark stiffness matrix
  std::auto_ptr<SparseMatrix<double> > newmark_stiffness_matrix(SparseMatrix<double>::build().release());
  this->coefficient_matrices[0]->close();
  newmark_stiffness_matrix->duplicate_matrix(*(this->coefficient_matrices[0]), false);
  // init the constants
  Solver::NewmarkSolver::initNewmarkConstants(newmark_info,
                                              this->newmark_constants);
  // init the iteration data
  this->simulated_time = this->transient_solver_info.getInitialTime();
  this->simulated_iteration_number = 0;
  // calculate the highest order derivative at initial time from the initial conditions
  // the basic equation to be solved is
  // dX/dt^(n) = inv(C_(n)) * (F_0 - sum_(i=0..n-1) (C_i * dX/dt^(i)))
  dynamic_cast<Driver::TransientAnalysisDriver*>(this->analysis_driver)->
  getCoefficientMatrices(this->transient_solver_info.getInitialTime(),
                         this->coefficient_matrices);
  dynamic_cast<Driver::TransientAnalysisDriver*>(this->analysis_driver)->
  getForceVector(this->transient_solver_info.getInitialTime(),
                 *external_force_vector);
  external_force_vector->close();
  // calculate the RHS of the linear equation
  for (unsigned int i=0; i < system_order; i++)
    {
      scratch_vec1->zero();
      scratch_vec1->close();
      this->coefficient_matrices[i]->close();
      this->coefficient_matrices[i]->multiply_vector(*(this->current_state_vectors[i]),
                                                     *scratch_vec1);
      scratch_vec1->close();
      external_force_vector->add(-1.0, *scratch_vec1);
    }
  external_force_vector->close();
  // tell the linear solver to factorize this matrix
  this->coefficient_matrices[system_order]->close();
  this->linear_solver->setSystemMatrix(*(this->coefficient_matrices[system_order]));
  this->linear_solver->setPreconditionerMatrix(*(this->coefficient_matrices[system_order]));
  this->linear_solver->solve(*external_force_vector,
                             *(this->current_state_vectors[system_order]));
  this->current_state_vectors[system_order]->close();
  // now, increment the iteration number to 1, for which the vectors will be stored
  this->simulated_iteration_number++;
  // tell the driver of the 1st iterate, which will be the initial conditions
  dynamic_cast<Driver::TransientAnalysisDriver*>(this->analysis_driver)->
  setNewIteration(this->getSimulatedTime(),
                  this->getSimulatedIterationNumber(),
                  this->current_state_vectors.getReference());
  while (this->getSimulatedTime() < this->transient_solver_info.getFinalTime())
    {
      this->current_time = this->simulated_time + this->transient_solver_info.getInitialTimeStep();
      // ask the driver to init the matrices. This needs to be done only once for a system where
      // the matrices are constant with iterations
      if (!this->time_independent_coefficient_matrices || this->simulated_iteration_number == 1)
        {
          dynamic_cast<Driver::TransientAnalysisDriver*>(this->analysis_driver)->
          getCoefficientMatrices(this->getCurrentTime(),
                                 this->coefficient_matrices);
          // calculate the Newmark stiffness matrix
          Solver::NewmarkSolver::initNewmarkStiffnessMatrix
          (newmark_info,
           this->newmark_constants,
           this->coefficient_matrices,
           *newmark_stiffness_matrix);
          // tell the linear solver to factorize this matrix
          this->linear_solver->setSystemMatrix(*newmark_stiffness_matrix);
          this->linear_solver->setPreconditionerMatrix(*newmark_stiffness_matrix);
        }
      // ask the driver to init the force vector;
      dynamic_cast<Driver::TransientAnalysisDriver*>(this->analysis_driver)->
      getForceVector(this->getCurrentTime(),
                     *external_force_vector);
      // calculate the Newmark force vector
      Solver::NewmarkSolver::initNewmarkForceVector
      (newmark_info,
       this->newmark_constants,
       this->coefficient_matrices,
       this->current_state_vectors.getReference(),
       *external_force_vector,
       *scratch_vec1,
       *scratch_vec2,
       *newmark_force_vector);
      // now solve for the new iterate
      this->linear_solver->solve(*newmark_force_vector, *(this->new_state_vectors[0]));
      // calculate the new derivatives
      Solver::NewmarkSolver::updateStateVectors
      (newmark_info,
       this->newmark_constants,
       this->current_state_vectors.getReference(),
       this->new_state_vectors.getReference());
      // increment the current time and the iteration number
      this->simulated_time = this->getCurrentTime();
      this->simulated_iteration_number++;
      // tell the analysis driver to record the iteration increment
      dynamic_cast<Driver::TransientAnalysisDriver*>(this->analysis_driver)->
      setNewIteration(this->getSimulatedTime(),
                      this->getSimulatedIterationNumber(),
                      this->current_state_vectors.getReference());
    }
  this->linear_solver.reset();
  this->analysis_driver->getFESystemController().performance_logging->unsetEvent
  ("NewmarkLinearTransientSolver::solve()", "Solver");
}
Member Data Documentation
FESystemUtility::AutoPtrVector<NumericVector<double> > Solver::NewmarkLinearTransientSolver::current_state_vectors [protected]
internal state vectors, arranged in increasing order of time derivative. The (n-1)th iterates are stored here
Definition at line 136 of file NewmarkTransientSolver.h.
double Solver::NewmarkLinearTransientSolver::current_time [protected]
current time
Definition at line 121 of file NewmarkTransientSolver.h.
std::auto_ptr<Solver::LinearSolver> Solver::NewmarkLinearTransientSolver::linear_solver [protected]
linear solver
Definition at line 130 of file NewmarkTransientSolver.h.
FESystemUtility::AutoPtrVector<NumericVector<double> > Solver::NewmarkLinearTransientSolver::new_state_vectors [protected]
internal state vectors, arranged in increasing order of time derivative. The nth iterates are stored here
Definition at line 140 of file NewmarkTransientSolver.h.
std::vector<double> Solver::NewmarkLinearTransientSolver::newmark_constants [protected]
Definition at line 132 of file NewmarkTransientSolver.h.
unsigned int Solver::NewmarkLinearTransientSolver::simulated_iteration_number [protected]
simulated iteration number
Definition at line 127 of file NewmarkTransientSolver.h.
double Solver::NewmarkLinearTransientSolver::simulated_time [protected]
simulated time
Definition at line 118 of file NewmarkTransientSolver.h.
double Solver::NewmarkLinearTransientSolver::time_step_size [protected]
current step size
Definition at line 124 of file NewmarkTransientSolver.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/NewmarkTransientSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/NewmarkTransientSolver.C