fesystem: Loads::SurfaceRadiationLoadCombination Class Reference
Loads::SurfaceRadiationLoadCombination Class Reference
#include <LoadCombination.h>
Public Member Functions
SurfaceRadiationLoadCombination ()
virtual ~SurfaceRadiationLoadCombination ()
virtual unsigned int getLoadClassEnumID () const
double getTemperature () const
virtual void clear ()
virtual void addLoad (const double factor, const SurfaceLoad *load_ptr)
Protected Attributes
double temperature
Detailed Description
Definition at line 334 of file LoadCombination.h.
Constructor & Destructor Documentation
Loads::SurfaceRadiationLoadCombination::SurfaceRadiationLoadCombination () [inline]
Definition at line 337 of file LoadCombination.h.
                                       :
      SurfaceLoadCombination(),
      temperature(0.0)
      {
      }
virtual Loads::SurfaceRadiationLoadCombination::~SurfaceRadiationLoadCombination () [inline, virtual]
Definition at line 344 of file LoadCombination.h.
      {
      }
Member Function Documentation
virtual void Loads::SurfaceRadiationLoadCombination::addLoad (const double factor, const SurfaceLoad * load_ptr) [inline, virtual]
Implements Loads::SurfaceLoadCombination.
Definition at line 366 of file LoadCombination.h.
References Loads::SurfaceLoadCombination::getElemID(), LoadBase::getLoadClassEnumID(), Loads::SurfaceLoadCombination::getSurfaceID(), Loads::SurfaceLoadCombination::load_set, and temperature.
      {
        Assert(load_ptr != NULL, ExcInternalError());
        Assert(load_ptr->getLoadClassEnumID() == SURFACE_RADIATION_LOAD::num(),
               ExcInternalError());
        const SurfaceRadiationLoad* ptr = dynamic_cast<const SurfaceRadiationLoad*>(load_ptr);
        // set the node ID
        if (this->load_set.size() > 0)
          Assert(this->getElemID() == ptr->getElemID() &&
                 this->getSurfaceID() == ptr->getSurfaceID(),
                 ExcInternalError());
        bool insert_success = this->load_set.insert(load_ptr).second;
        // add this pointer to the set, and adjust the value of the load
        Assert(insert_success, ExcInternalError());
        this->temperature += factor * ptr->getTemperature();
      }
virtual void Loads::SurfaceRadiationLoadCombination::clear () [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 360 of file LoadCombination.h.
References Loads::SurfaceLoadCombination::load_set, and temperature.
      {
        this->temperature = 0.0;
        this->load_set.clear();
      }
virtual unsigned int Loads::SurfaceRadiationLoadCombination::getLoadClassEnumID () const [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 349 of file LoadCombination.h.
      {
        return SURFACE_RADIATION_LOAD::num();
      }
double Loads::SurfaceRadiationLoadCombination::getTemperature () const [inline]
Definition at line 355 of file LoadCombination.h.
References temperature.
      {
        return this->temperature;
      }
Member Data Documentation
double Loads::SurfaceRadiationLoadCombination::temperature [protected]
Definition at line 391 of file LoadCombination.h.
Referenced by addLoad(), clear(), and getTemperature().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCombination.h