fesystem: FESystemUtility::LoadedVectorData Class Reference
FESystemUtility::LoadedVectorData Class Reference
this is a data structure to store the vector and its relevant data
#include <LoadedSolution.h>
Public Member Functions
LoadedVectorData ()
constructor
~LoadedVectorData ()
destructor
void clear ()
bool initialized ()
const
FESystemDatabase::DataInfoBase & getDataInfo ()
void setDataInfo (const FESystemDatabase::DataInfoBase &data_info_obj)
NumericVector< double > & getVector ()
Protected Attributes
std::auto_ptr
< FESystemDatabase::DataInfoBase > data_info
NumericVector< double > * vec
Detailed Description
this is a data structure to store the vector and its relevant data
Definition at line 28 of file LoadedSolution.h.
Constructor & Destructor Documentation
FESystemUtility::LoadedVectorData::LoadedVectorData () [inline]
constructor
Definition at line 32 of file LoadedSolution.h.
References vec.
                      :
    vec(NULL)
    {
      this->vec = NumericVector<double>::build().release();
    }
FESystemUtility::LoadedVectorData::~LoadedVectorData () [inline]
destructor
Definition at line 40 of file LoadedSolution.h.
References vec.
    {
      delete this->vec;
    }
Member Function Documentation
void FESystemUtility::LoadedVectorData::clear () [inline]
Definition at line 46 of file LoadedSolution.h.
References data_info, and vec.
    {
      if (this->vec->initialized())
        this->vec->zero();
      this->data_info.reset();
    }
const FESystemDatabase::DataInfoBase& FESystemUtility::LoadedVectorData::getDataInfo () [inline]
Returns:
the load case for this vector
Definition at line 63 of file LoadedSolution.h.
References data_info, and initialized().
{
      Assert(this->initialized(), ExcInternalError());
      return *(this->data_info.get());}
NumericVector<double>& FESystemUtility::LoadedVectorData::getVector () [inline]
Returns:
a reference to the vector
Definition at line 71 of file LoadedSolution.h.
References vec.
{
      return *(this->vec);}
bool FESystemUtility::LoadedVectorData::initialized () [inline]
Returns:
true if the data info has been set
Definition at line 55 of file LoadedSolution.h.
References data_info.
Referenced by getDataInfo(), and setDataInfo().
{
      bool init = false;
      if (this->data_info.get() != NULL)
        init = true;
      return init;}
void FESystemUtility::LoadedVectorData::setDataInfo (const FESystemDatabase::DataInfoBase & data_info_obj)
Definition at line 15 of file LoadedSolution.C.
References FESystemDatabase::createDataInfoCopy(), data_info, and initialized().
{
  Assert(!this->initialized(), ExcInternalError());
  this->data_info.reset(FESystemDatabase::createDataInfoCopy(data_info_obj).release());
}
Member Data Documentation
std::auto_ptr<FESystemDatabase::DataInfoBase> FESystemUtility::LoadedVectorData::data_info [protected]
Definition at line 78 of file LoadedSolution.h.
Referenced by clear(), getDataInfo(), initialized(), and setDataInfo().
NumericVector<double>* FESystemUtility::LoadedVectorData::vec [protected]
Definition at line 81 of file LoadedSolution.h.
Referenced by clear(), getVector(), LoadedVectorData(), and ~LoadedVectorData().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Utilities/LoadedSolution.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Utilities/LoadedSolution.C