fesystem: MeshDS::FEMeshData Class Reference
MeshDS::FEMeshData Class Reference
#include <FEMeshData.h>
Classes
struct ElemPropIDs
a structure for storing the element property and kind enum ID
struct NodeIDs
a structure for storing the node IDs
Public Member Functions
FEMeshData (const MeshDS::FEMesh &)
constructor
~FEMeshData ()
destructor
const Node * getNodeFromForeignID (const unsigned int fid) const
const Elem * getElemFromForeignID (const unsigned int fid) const
unsigned int getForeignIDFromElem (const Elem *elem) const
unsigned int getForeignIDFromNode (const Node *elem) const
unsigned int getElemPropertyID (const Elem *elem) const
unsigned int getElemKindEnumID (const Elem *elem) const
std::string getElemKindEnumName (const Elem *elem) const
const Node * getNodeFromInternalID (const unsigned int) const
unsigned int getInternalIDFromNode (const Node *) const
unsigned int getNodeForeignIDFromInternalID (const unsigned int) const
void writeMeshDataToStream (std::ostream &output)
Protected Types
typedef std::map< unsigned int,
const Elem * > IDToElemMap
typedef std::map< unsigned int,
const Node * > IDToNodeMap
typedef std::map< const Elem
*, ElemPropIDs > ElemToIDMap
typedef std::map< const Node
*, NodeIDs > NodeToIDMap
typedef std::vector< const Elem * > ElemVector
typedef std::vector< const Node * > NodeVector
Protected Member Functions
void addNodeAndIDData (const Node *node, const unsigned int foreign_node_id)
this method adds the node and its foreign ID to the mesh data
void addElemAndIDData (const Elem *elem, const unsigned int foreign_elem_ID, const unsigned int property_ID, const unsigned int elem_kind_enum_ID)
this method adds the elem and its foreign ID to the mesh data
const Elem * getElemFromInternalID (const unsigned int) const
unsigned int getInternalIDFromElem (const Elem *) const
unsigned int getNodeInternalIDFromForeignID (const unsigned int) const
unsigned int getElemInternalIDFromForeignID (const unsigned int) const
unsigned int getElemForeignIDFromInternalID (const unsigned int) const
DeclException2 (ExcDuplicateID, std::string, unsigned int,<< "Duplicate "<< arg1<< " ID: "<< arg2<< " specified.")
this exception is thrown if a duplicate ID is specified
DeclException1 (ExcDuplicatePointer, std::string,<< "Duplicate "<< arg1<< " pointer specified.")
this exception is thrown if a duplicate ID is specified
DeclException2 (ExcIDDoesNotExist, std::string, unsigned int,<< "Specified "<< arg1<< " ID: "<< arg2<< " does not exist.")
this exception is thrown if the ID does not exist in the data
DeclException1 (ExcPointerDoesNotExist, std::string,<< "Specified "<< arg1<< " pointer does not exist.")
this exception is thrown if the pointer does not exist in the data
DeclException2 (ExcInternalIDDoesNotExist, std::string, unsigned int,<< "Specified "<< arg1<< " internal ID: "<< arg2<< " does not exist.")
this exception is thrown if the internal ID does not exist in the data
Protected Attributes
const MeshDS::FEMesh & mesh
the mesh whose data is stored in this mesh data
IDToElemMap foreign_ID_to_elem_map
map for storing elems vs their external IDs
IDToNodeMap foreign_ID_to_node_map
map for storing nodes vs their external IDs
ElemToIDMap elem_ID_map
map for storing elem IDs vs their pointers
NodeToIDMap node_ID_map
map for storing node IDs vs their pointers
ElemVector elem_vector
NodeVector node_vector
Friends
class MeshList
the MeshList class is a friend since it performs the input
Detailed Description
Definition at line 29 of file FEMeshData.h.
Member Typedef Documentation
typedef std::map< const Elem*, ElemPropIDs> MeshDS::FEMeshData::ElemToIDMap [protected]
Definition at line 147 of file FEMeshData.h.
typedef std::vector<const Elem*> MeshDS::FEMeshData::ElemVector [protected]
Definition at line 149 of file FEMeshData.h.
typedef std::map<unsigned int, const Elem*> MeshDS::FEMeshData::IDToElemMap [protected]
Definition at line 145 of file FEMeshData.h.
typedef std::map<unsigned int, const Node*> MeshDS::FEMeshData::IDToNodeMap [protected]
Definition at line 146 of file FEMeshData.h.
typedef std::map< const Node*, NodeIDs> MeshDS::FEMeshData::NodeToIDMap [protected]
Definition at line 148 of file FEMeshData.h.
typedef std::vector<const Node*> MeshDS::FEMeshData::NodeVector [protected]
Definition at line 150 of file FEMeshData.h.
Constructor & Destructor Documentation
MeshDS::FEMeshData::FEMeshData (const MeshDS::FEMesh & m)
constructor
Definition at line 10 of file FEMeshData.C.
                                                 :
mesh(m)
{
}
MeshDS::FEMeshData::~FEMeshData ()
destructor
Definition at line 18 of file FEMeshData.C.
{
}
Member Function Documentation
void MeshDS::FEMeshData::addElemAndIDData (const Elem * elem, const unsigned int foreign_elem_ID, const unsigned int property_ID, const unsigned int elem_kind_enum_ID) [protected]
this method adds the elem and its foreign ID to the mesh data
Definition at line 31 of file FEMeshData.C.
References MeshDS::FEMeshData::ElemPropIDs::foreign_ID, MeshDS::FEMeshData::ElemPropIDs::internal_ID, FESystemNumbers::InvalidID, MeshDS::FEMeshData::ElemPropIDs::kind_enum_ID, and MeshDS::FEMeshData::ElemPropIDs::property_ID.
Referenced by MeshDS::MeshList::readFromInputStream().
{
  Assert(elem != NULL,
         ExcEmptyObject());
  Assert(foreign_elem_ID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(foreign_elem_ID));
  // create the entries in the differet maps and vectors.
  // first get the internal ID for this elem.
  unsigned int internal_ID = this->elem_vector.size();
  bool insert_success =
    this->foreign_ID_to_elem_map.insert(MeshDS::FEMeshData::IDToElemMap::value_type
                                        (foreign_elem_ID, elem)).second;
  // if the insert failed, then the ID is not unique
  Assert(insert_success,
         MeshDS::FEMeshData::ExcDuplicateID("Elem", foreign_elem_ID));
  // next create the ID data structure
  MeshDS::FEMeshData::ElemPropIDs elem_ids;
  elem_ids.foreign_ID = foreign_elem_ID;
  elem_ids.internal_ID = internal_ID;
  elem_ids.property_ID = property_ID;
  elem_ids.kind_enum_ID = elem_kind_enum_ID;
  // insert this in the map
  insert_success =
    this->elem_ID_map.insert(MeshDS::FEMeshData::ElemToIDMap::value_type
                                        (elem, elem_ids)).second;
  // if the insert failed, then the elem is not unique
  Assert(insert_success,
         MeshDS::FEMeshData::ExcDuplicatePointer("Elem"));
  // finally, insert the elem in the vector
  this->elem_vector.push_back(elem);
}
void MeshDS::FEMeshData::addNodeAndIDData (const Node * node, const unsigned int foreign_node_id) [protected]
this method adds the node and its foreign ID to the mesh data
Definition at line 78 of file FEMeshData.C.
References MeshDS::FEMeshData::NodeIDs::foreign_ID, MeshDS::FEMeshData::NodeIDs::internal_ID, and FESystemNumbers::InvalidID.
Referenced by MeshDS::MeshList::readFromInputStream().
{
  Assert(node != NULL,
         ExcEmptyObject());
  Assert(foreign_node_ID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(foreign_node_ID));
  // create the entries in the differet maps and vectors.
  // first get the internal ID for this elem.
  unsigned int internal_ID = this->node_vector.size();
  bool insert_success =
    this->foreign_ID_to_node_map.insert(MeshDS::FEMeshData::IDToNodeMap::value_type
                                        (foreign_node_ID, node)).second;
  // if the insert failed, then the ID is not unique
  Assert(insert_success,
         MeshDS::FEMeshData::ExcDuplicateID("Node", foreign_node_ID));
  // next create the ID data structure
  NodeIDs node_ids;
  node_ids.foreign_ID = foreign_node_ID;
  node_ids.internal_ID = internal_ID;
  // insert this in the map
  insert_success =
    this->node_ID_map.insert(MeshDS::FEMeshData::NodeToIDMap::value_type
                                        (node, node_ids)).second;
  // if the insert failed, then the elem is not unique
  Assert(insert_success,
         MeshDS::FEMeshData::ExcDuplicatePointer("Node"));
  // finally, insert the elem in the vector
  this->node_vector.push_back(node);
}
MeshDS::FEMeshData::DeclException1 (ExcDuplicatePointer , std::string , << "Duplicate "<< arg1<< " pointer specified.") [protected]
this exception is thrown if a duplicate ID is specified
MeshDS::FEMeshData::DeclException1 (ExcPointerDoesNotExist , std::string , << "Specified "<< arg1<< " pointer does not exist.") [protected]
this exception is thrown if the pointer does not exist in the data
MeshDS::FEMeshData::DeclException2 (ExcDuplicateID , std::string , unsigned int, << "Duplicate "<< arg1<< " ID: "<< arg2<< " specified.") [protected]
this exception is thrown if a duplicate ID is specified
MeshDS::FEMeshData::DeclException2 (ExcIDDoesNotExist , std::string , unsigned int, << "Specified "<< arg1<< " ID: "<< arg2<< " does not exist.") [protected]
this exception is thrown if the ID does not exist in the data
MeshDS::FEMeshData::DeclException2 (ExcInternalIDDoesNotExist , std::string , unsigned int, << "Specified "<< arg1<< " internal ID: "<< arg2<< " does not exist.") [protected]
this exception is thrown if the internal ID does not exist in the data
unsigned int MeshDS::FEMeshData::getElemForeignIDFromInternalID (const unsigned int internal_ID) const [inline, protected]
Returns:
the foreign ID of an elem whose internal ID is given
Definition at line 350 of file FEMeshData.h.
{
  const Elem* elem = this->getElemFromInternalID(internal_ID);
  return this->getForeignIDFromElem(elem);
}
const Elem * MeshDS::FEMeshData::getElemFromForeignID (const unsigned int fid) const [inline]
Returns:
the elem whose foreign ID is given in the input parameter
Definition at line 216 of file FEMeshData.h.
Referenced by RadiationCavityAnalysis::calculateB_Matrix(), RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution(), RadiationCavityAnalysis::calculateEmissivityVector(), Discipline::AnalysisDisciplineBase::calculateGlobalQty(), RadiationCavity::createFENodeVectorAndRadiationElems(), RadiationCavity::getGeometricFE(), and Discipline::AnalysisDisciplineBase::getPerturbedElemForShapeParameter().
{
  MeshDS::FEMeshData::IDToElemMap::const_iterator it, end;
  it = this->foreign_ID_to_elem_map.find(fid);
  end = this->foreign_ID_to_elem_map.end();
  Assert(it != end,
         MeshDS::FEMeshData::ExcIDDoesNotExist("Elem", fid));
  return it->second;
}
const Elem * MeshDS::FEMeshData::getElemFromInternalID (const unsigned int internal_ID) const [inline, protected]
Returns:
the element whose internal ID is given in the input parameter
Definition at line 264 of file FEMeshData.h.
{
  Assert(internal_ID < this->elem_vector.size(),
         MeshDS::FEMeshData::ExcInternalIDDoesNotExist("Elem", internal_ID));
  return this->elem_vector[internal_ID];
}
unsigned int MeshDS::FEMeshData::getElemInternalIDFromForeignID (const unsigned int fid) const [inline, protected]
Returns:
the internal ID of an elem whose foreign ID is given
Definition at line 323 of file FEMeshData.h.
{
        const Elem* elem = this->getElemFromForeignID(fid);
  return this->getInternalIDFromElem(elem);
}
unsigned int MeshDS::FEMeshData::getElemKindEnumID (const Elem * elem) const [inline]
Returns:
the elem kind enum ID
Definition at line 380 of file FEMeshData.h.
{
  MeshDS::FEMeshData::ElemToIDMap::const_iterator it, end;
  it = this->elem_ID_map.find(elem);
  end = this->elem_ID_map.end();
  Assert(it != end,
         MeshDS::FEMeshData::ExcPointerDoesNotExist("Elem"));
  return it->second.kind_enum_ID;
}
std::string MeshDS::FEMeshData::getElemKindEnumName (const Elem * elem) const [inline]
Returns:
the elem kind enum name
Definition at line 396 of file FEMeshData.h.
References FESystemElem::FESystemElemTypeEnum::enumName().
{
  MeshDS::FEMeshData::ElemToIDMap::const_iterator it, end;
  it = this->elem_ID_map.find(elem);
  end = this->elem_ID_map.end();
  Assert(it != end,
         MeshDS::FEMeshData::ExcPointerDoesNotExist("Elem"));
  return FESystemElem::FESystemElemTypeEnum::enumName(it->second.property_ID);
}
unsigned int MeshDS::FEMeshData::getElemPropertyID (const Elem * elem) const [inline]
Returns:
the property ID of the element
Definition at line 364 of file FEMeshData.h.
Referenced by RadiationCavityAnalysis::calculateB_Matrix(), RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution(), and RadiationCavityAnalysis::calculateEmissivityVector().
{
  MeshDS::FEMeshData::ElemToIDMap::const_iterator it, end;
  it = this->elem_ID_map.find(elem);
  end = this->elem_ID_map.end();
  Assert(it != end,
         MeshDS::FEMeshData::ExcPointerDoesNotExist("Elem"));
  return it->second.property_ID;
}
unsigned int MeshDS::FEMeshData::getForeignIDFromElem (const Elem * elem) const [inline]
Returns:
the foreign ID of the element
Definition at line 233 of file FEMeshData.h.
Referenced by GeometricModel::createWritableElemList().
{
  MeshDS::FEMeshData::ElemToIDMap::const_iterator it, end;
  it = this->elem_ID_map.find(elem);
  end = this->elem_ID_map.end();
  Assert(it != end,
         MeshDS::FEMeshData::ExcPointerDoesNotExist("Elem"));
  return it->second.foreign_ID;
}
unsigned int MeshDS::FEMeshData::getForeignIDFromNode (const Node * elem) const [inline]
Returns:
the foreign ID of the node
Definition at line 199 of file FEMeshData.h.
Referenced by RadiationCavity::createFENodeVectorAndRadiationElems(), DirectInterpolation::createLoads(), InterpolationDriver::createLoads(), GeometricModel::createWritableElemList(), and FESystemElem::StructuralElem::extractNodalTemperatureVectorFromLoads().
{
  MeshDS::FEMeshData::NodeToIDMap::const_iterator it, end;
  it = this->node_ID_map.find(node);
  end = this->node_ID_map.end();
  Assert(it != end,
         MeshDS::FEMeshData::ExcPointerDoesNotExist("Node"));
  return it->second.foreign_ID;
}
unsigned int MeshDS::FEMeshData::getInternalIDFromElem (const Elem * elem) const [inline, protected]
Returns:
the internal ID of the given element
Definition at line 276 of file FEMeshData.h.
{
  MeshDS::FEMeshData::ElemToIDMap::const_iterator it, end;
  it = this->elem_ID_map.find(elem);
  end = this->elem_ID_map.end();
  Assert(it != end,
         MeshDS::FEMeshData::ExcPointerDoesNotExist("Elem"));
  return it->second.internal_ID;
}
unsigned int MeshDS::FEMeshData::getInternalIDFromNode (const Node * node) const [inline]
Returns:
the internal ID of the given node
Definition at line 293 of file FEMeshData.h.
Referenced by Driver::AnalysisDriver::writeComplexSolutionVectorToLog(), and Driver::AnalysisDriver::writeSolutionVectorToLog().
{
  MeshDS::FEMeshData::NodeToIDMap::const_iterator it, end;
  it = this->node_ID_map.find(node);
  end = this->node_ID_map.end();
  Assert(it != end,
         MeshDS::FEMeshData::ExcPointerDoesNotExist("Node"));
  return it->second.internal_ID;
}
unsigned int MeshDS::FEMeshData::getNodeForeignIDFromInternalID (const unsigned int internal_ID) const [inline]
Returns:
the foreign ID of a node whose internal ID is given
Definition at line 337 of file FEMeshData.h.
{
  const Node* node = this->getNodeFromInternalID(internal_ID);
  return this->getForeignIDFromNode(node);
}
const Node * MeshDS::FEMeshData::getNodeFromForeignID (const unsigned int fid) const [inline]
Returns:
the node whose foreign ID is given in the input parameter
Definition at line 183 of file FEMeshData.h.
References foreign_ID_to_node_map.
Referenced by Driver::EigenProblemAnalysisDriver::applyBoundaryConditionsForCurrentAnalysis(), Driver::AnalysisDriver::applyBoundaryConditionsToMatrixForCurrentAnalysis(), Driver::AnalysisDriver::applyBoundaryConditionsToVectorForCurrentAnalysis(), RadiationCavity::createFENodeVectorAndRadiationElems(), Driver::RogerApproximationAeroelasticityDriver::createSubMatrixIndices(), Driver::EigenProblemAnalysisDriver::getSubmatrixAfterBoundaryCondition(), MeshDS::MeshList::readFromInputStream(), and GeometricModel::readGmshMeshOutput().
{
  MeshDS::FEMeshData::IDToNodeMap::const_iterator it, end;
  it = this->foreign_ID_to_node_map.find(fid);
  end = this->foreign_ID_to_node_map.end();
  Assert(it != end,
         MeshDS::FEMeshData::ExcIDDoesNotExist("Node", fid));
  return it->second;
}
const Node * MeshDS::FEMeshData::getNodeFromInternalID (const unsigned int internal_ID) const [inline]
Returns:
the node whose internal ID is given in the input parameter
Definition at line 251 of file FEMeshData.h.
{
  Assert(internal_ID < this->node_vector.size(),
         MeshDS::FEMeshData::ExcInternalIDDoesNotExist("Node", internal_ID));
  return this->node_vector[internal_ID];
}
unsigned int MeshDS::FEMeshData::getNodeInternalIDFromForeignID (const unsigned int fid) const [inline, protected]
Returns:
the internal ID of a node whose foreign ID is given
Definition at line 311 of file FEMeshData.h.
{
        const Node* node = this->getNodeFromForeignID(fid);
  return this->getInternalIDFromNode(node);
}
void MeshDS::FEMeshData::writeMeshDataToStream (std::ostream & output)
writes the mesh data to the provided output stream. The node ID, location, and the global dof IDs are written for each node
Definition at line 120 of file FEMeshData.C.
{
  // iterate over each external node ID, get the node from the mesh data for that
  // and write its data
  IDToNodeMap::const_iterator it, end;
  it = this->foreign_ID_to_node_map.begin();
  end = this->foreign_ID_to_node_map.end();
  for ( ; it != end; it++)
    {
      output << it->first << "  "
      << (*(it->second))(0) << " "
      << (*(it->second))(1) << " "
      << (*(it->second))(2) << " ";
      // now the dof indices
      // system is assumed to be zero
      for (unsigned int i=0; i<it->second->n_vars(0); i++)
        output << it->second->dof_number(0,i,0) << "  ";
      output << std::endl;
    }
}
Friends And Related Function Documentation
friend class MeshList [friend]
the MeshList class is a friend since it performs the input
Definition at line 174 of file FEMeshData.h.
Member Data Documentation
ElemToIDMap MeshDS::FEMeshData::elem_ID_map [protected]
map for storing elem IDs vs their pointers
Definition at line 159 of file FEMeshData.h.
ElemVector MeshDS::FEMeshData::elem_vector [protected]
vector of elem, where the location of the elem in the vector is its internal ID
Definition at line 166 of file FEMeshData.h.
IDToElemMap MeshDS::FEMeshData::foreign_ID_to_elem_map [protected]
map for storing elems vs their external IDs
Definition at line 153 of file FEMeshData.h.
IDToNodeMap MeshDS::FEMeshData::foreign_ID_to_node_map [protected]
map for storing nodes vs their external IDs
Definition at line 156 of file FEMeshData.h.
Referenced by getNodeFromForeignID().
const MeshDS::FEMesh& MeshDS::FEMeshData::mesh [protected]
the mesh whose data is stored in this mesh data
Definition at line 124 of file FEMeshData.h.
NodeToIDMap MeshDS::FEMeshData::node_ID_map [protected]
map for storing node IDs vs their pointers
Definition at line 162 of file FEMeshData.h.
NodeVector MeshDS::FEMeshData::node_vector [protected]
vector of nodes, where the location of the node in the vector is its internal ID
Definition at line 170 of file FEMeshData.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Mesh/FEMeshData.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Mesh/FEMeshData.C