fesystem: Solver::LinearTransientSolverInfo Class Reference
Solver::LinearTransientSolverInfo Class Reference
this is a class specifically for linear transient solvers
#include <TransientSolverInfo.h>
Public Member Functions
LinearTransientSolverInfo ()
constructor
LinearTransientSolverInfo (const unsigned int info_enum_ID, const unsigned int solver_class_enum_ID)
constructor for cases where another class derives from this class
~LinearTransientSolverInfo ()
destructor
virtual std::istream & readFromInputStream (std::istream &input)
reads from input
unsigned int getLinearSolverInfoID () const
Protected Attributes
unsigned int linear_solver_info_ID
ID of linear solver info.
Friends
std::istream & operator>> (std::istream &input, Solver::LinearTransientSolverInfo &info)
overloaded input stream operator
Detailed Description
this is a class specifically for linear transient solvers
Definition at line 126 of file TransientSolverInfo.h.
Constructor & Destructor Documentation
Solver::LinearTransientSolverInfo::LinearTransientSolverInfo ()
constructor
Definition at line 32 of file TransientSolverInfo.C.
                                                          :
Solver::TransientSolverInfoBase(Solver::LINEAR_TRANSIENT_SOLVER_INFO::num(),
                                Solver::LINEAR_TRANSIENT_SOLVER::num()),
linear_solver_info_ID(FESystemNumbers::InvalidID)
{
}
Solver::LinearTransientSolverInfo::LinearTransientSolverInfo (const unsigned int info_enum_ID, const unsigned int solver_class_enum_ID)
constructor for cases where another class derives from this class
Definition at line 42 of file TransientSolverInfo.C.
                                                                                             :
Solver::TransientSolverInfoBase(info_enum_ID,
                                solver_class),
linear_solver_info_ID(FESystemNumbers::InvalidID)
{
}
Solver::LinearTransientSolverInfo::~LinearTransientSolverInfo ()
destructor
Definition at line 53 of file TransientSolverInfo.C.
{
}
Member Function Documentation
unsigned int Solver::LinearTransientSolverInfo::getLinearSolverInfoID () const [inline]
Returns:
linear solver info ID for this solver
Definition at line 296 of file TransientSolverInfo.h.
Referenced by Solution::SolutionBase::linearTransientSolve(), and Solution::SolutionBase::nonlinearTransientSolve().
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->linear_solver_info_ID;
}
std::istream & Solver::LinearTransientSolverInfo::readFromInputStream (std::istream & input) [virtual]
reads from input
Implements Solver::TransientSolverInfoBase.
Reimplemented in Solver::NewmarkLinearTransientSolverInfo, and Solver::EulerLinearTransientSolverInfo.
Definition at line 60 of file TransientSolverInfo.C.
References FESystemIOUtility::readFromInput().
{
  std::string tag;
  FESystemIOUtility::readFromInput(input, Solver::LINEAR_TRANSIENT_SOLVER_INFO::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->ID);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "TRANSIENT_SOLVER_TYPE", tag);
  this->transient_solver_kind_enum_ID = Solver::TransientSolverKindEnum::enumID(tag);
  FESystemIOUtility::readFromInput(input, "LINEAR_SOLVER_INFO_ID", this->linear_solver_info_ID);
  FESystemIOUtility::readFromInput(input, "MAX_ITERATIONS", this->max_iterations);
  FESystemIOUtility::readFromInput(input, "INITIAL_TIME", this->initial_time);
  FESystemIOUtility::readFromInput(input, "TOTAL_DURATION", this->total_duration);
  FESystemIOUtility::readFromInput(input, "IF_ADAPTIVE_SIZE", this->adaptive_step_size);
  FESystemIOUtility::readFromInput(input, "INITIAL_STEP_SIZE", this->initial_step_size);
  FESystemIOUtility::readFromInput(input, "GLOBAL_TOLERANCE", this->global_tolerance);
  FESystemIOUtility::readFromInput(input, Solver::LINEAR_TRANSIENT_SOLVER_INFO::name());
  FESystemIOUtility::readFromInput(input, "END");
  this->initialized = true;
  return input;
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, Solver::LinearTransientSolverInfo & info) [friend]
overloaded input stream operator
Member Data Documentation
unsigned int Solver::LinearTransientSolverInfo::linear_solver_info_ID [protected]
ID of linear solver info.
Definition at line 152 of file TransientSolverInfo.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/TransientSolverInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/TransientSolverInfo.C