fesystem: Solver::LinearSolver Class Reference
Solver::LinearSolver Class Reference
#include <LinearSolver.h>
Public Member Functions
LinearSolver (const Solver::LinearSolverInfo &info, const unsigned int solver_kind)
constructor
~LinearSolver ()
destructor
virtual void clear ()
method to clear the data structures after use
unsigned int getLinearSolverKindEnumID () const
std::string getLinearSolverKindEnumName () const
const Solver::LinearSolverInfo & getSolverInfo () const
virtual void setSystemMatrix (SparseMatrix< double > &matrix)
virtual void setPreconditionerMatrix (SparseMatrix< double > &matrix)
virtual void solve (NumericVector< double > &rhs, NumericVector< double > &sol)=0
bool useSameMatricesBetweenSolves ()
Protected Attributes
const unsigned int linear_solver_kind_enum_ID
const Solver::LinearSolverInfo & solver_info
const unsigned int ksp_type_enum_ID
const unsigned int pc_type_enum_ID
SparseMatrix< double > * system_matrix
the preconditioner matrix
bool new_system_matrix
bool to check if the system matrix is new
SparseMatrix< double > * preconditioner_matrix
the preconditioner matrix
bool new_PC_matrix
bool to check if the PC matrix is new
bool same_matrices_between_solves
unsigned int n_solves_after_new_matrices
Detailed Description
Definition at line 464 of file LinearSolver.h.
Constructor & Destructor Documentation
Solver::LinearSolver::LinearSolver (const Solver::LinearSolverInfo & info, const unsigned int solver_kind)
constructor
Definition at line 8 of file LinearSolver.C.
                                                                  :
Solver::FESystemSolverBase(dynamic_cast<const Solver::SolverInfo&>(info)),
linear_solver_kind_enum_ID(solver_kind),
solver_info(info),
ksp_type_enum_ID(info.getKSPTypeEnumID()),
pc_type_enum_ID(info.getPCTypeEnumID()),
system_matrix(NULL),
new_system_matrix(false),
preconditioner_matrix(NULL),
new_PC_matrix(false),
same_matrices_between_solves(false),
n_solves_after_new_matrices(0)
{
}
Solver::LinearSolver::~LinearSolver ()
destructor
Definition at line 27 of file LinearSolver.C.
{
}
Member Function Documentation
void Solver::LinearSolver::clear () [virtual]
method to clear the data structures after use
Reimplemented from Solver::FESystemSolverBase.
Reimplemented in Solver::PetscLinearSolver.
Definition at line 44 of file LinearSolver.C.
References Solver::FESystemSolverBase::clear().
Referenced by Solver::PetscLinearSolver::clear().
{
  this->system_matrix = NULL;
  this->preconditioner_matrix = NULL;
  this->new_system_matrix = false;
  this->new_PC_matrix = false;
  this->same_matrices_between_solves = false;
  this->n_solves_after_new_matrices = 0;
  // nothing to be done, just call the parent's method
  Solver::FESystemSolverBase::clear();
}
unsigned int Solver::LinearSolver::getLinearSolverKindEnumID () const [inline]
Definition at line 540 of file LinearSolver.h.
References linear_solver_kind_enum_ID.
{
  return this->linear_solver_kind_enum_ID;
}
std::string Solver::LinearSolver::getLinearSolverKindEnumName () const [inline]
Definition at line 552 of file LinearSolver.h.
{
  return Solver::LinearSolverKindEnum::enumName(this->linear_solver_kind_enum_ID);
}
const Solver::LinearSolverInfo & Solver::LinearSolver::getSolverInfo () const [inline]
Definition at line 562 of file LinearSolver.h.
{
  return this->solver_info;
}
void Solver::LinearSolver::setPreconditionerMatrix (SparseMatrix< double > & matrix) [virtual]
Definition at line 69 of file LinearSolver.C.
Referenced by Driver::LinearAnalysisDriver::solveCurrentLoadCase(), and Driver::NonLinearAnalysisDriver::solveCurrentLoadCase().
{
  this->preconditioner_matrix = &matrix;
  this->new_PC_matrix = true;
  this->n_solves_after_new_matrices = 0;
}
void Solver::LinearSolver::setSystemMatrix (SparseMatrix< double > & matrix) [virtual]
Definition at line 59 of file LinearSolver.C.
Referenced by Driver::LinearAnalysisDriver::solveCurrentLoadCase(), and Driver::NonLinearAnalysisDriver::solveCurrentLoadCase().
{
  this->system_matrix = &matrix;
  this->new_system_matrix = true;
  this->n_solves_after_new_matrices = 0;
}
virtual void Solver::LinearSolver::solve (NumericVector< double > & rhs, NumericVector< double > & sol) [pure virtual]
this is a function that implements the solution steps. Before this function is called, the matrices and vector should already have been set.
Parameters:
rhs right hand side of the system of equations
sol vector in which solution will be stored
Implemented in Solver::PetscLinearSolver.
Referenced by Driver::LinearAnalysisDriver::solveCurrentLoadCase(), and Driver::NonLinearAnalysisDriver::solveCurrentLoadCase().
bool Solver::LinearSolver::useSameMatricesBetweenSolves ()
Definition at line 35 of file LinearSolver.C.
{
  this->same_matrices_between_solves = true;
}
Member Data Documentation
const unsigned int Solver::LinearSolver::ksp_type_enum_ID [protected]
Definition at line 505 of file LinearSolver.h.
Referenced by Solver::PetscLinearSolver::PetscLinearSolver().
const unsigned int Solver::LinearSolver::linear_solver_kind_enum_ID [protected]
Definition at line 502 of file LinearSolver.h.
Referenced by getLinearSolverKindEnumID().
unsigned int Solver::LinearSolver::n_solves_after_new_matrices [protected]
flag that the user must set to state if the same marices should be assumed between solves
Definition at line 526 of file LinearSolver.h.
bool Solver::LinearSolver::new_PC_matrix [protected]
bool to check if the PC matrix is new
Definition at line 518 of file LinearSolver.h.
bool Solver::LinearSolver::new_system_matrix [protected]
bool to check if the system matrix is new
Definition at line 512 of file LinearSolver.h.
const unsigned int Solver::LinearSolver::pc_type_enum_ID [protected]
Definition at line 506 of file LinearSolver.h.
Referenced by Solver::PetscLinearSolver::PetscLinearSolver().
SparseMatrix<double>* Solver::LinearSolver::preconditioner_matrix [protected]
the preconditioner matrix
Definition at line 515 of file LinearSolver.h.
bool Solver::LinearSolver::same_matrices_between_solves [protected]
flag that the user must set to state if the same marices should be assumed between solves
Definition at line 522 of file LinearSolver.h.
const Solver::LinearSolverInfo& Solver::LinearSolver::solver_info [protected]
Definition at line 503 of file LinearSolver.h.
SparseMatrix<double>* Solver::LinearSolver::system_matrix [protected]
the preconditioner matrix
Definition at line 509 of file LinearSolver.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/LinearSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/LinearSolver.C