fesystem: ForcedConvection_1D_ElemDataCard Class Reference
ForcedConvection_1D_ElemDataCard Class Reference
#include <ForcedConvection1DElemDataCard.h>
Public Member Functions
ForcedConvection_1D_ElemDataCard ()
virtual ~ForcedConvection_1D_ElemDataCard ()
virtual unsigned int getPropertyCardKindEnumID () const
virtual const std::string getPropertyCardKindEnumName () const
unsigned int getWallMaterialCardID () const
returns the wall material card ID for this card
unsigned int getFluidMaterialCardID () const
returns the fluid material card ID for this card
Property::PropertyCard< double > & getWallMaterialCard ()
returns the wall material card for this card
Property::PropertyCard< double > & getFluidMaterialCard ()
returns the fluid material card for this card
virtual bool checkElemAndMaterialCardGlobalParameterDependence (const unsigned int global_param_ID)
virtual bool checkElemAndMaterialCardLocalParameterDependence (const unsigned int local_param_ID)
virtual void reinitElemAndMaterialCardForLocalParameters (std::map< unsigned int, double > *value_map=NULL)
initializes the card and the material card for the given local parameters
virtual void reinitElemAndMaterialCardForGlobalParameters (std::map< unsigned int, double > &value_map)
initializes the card and the material card for the given global parameters
virtual void clearElemAndMaterialCardLocalParameterInitialization ()
clears initialization of the card and the material card for local parameters
virtual void partialClearElemAndMaterialCardLocalParameterInitialization (std::vector< unsigned int > &param_ids)
clears initialization of the card and the material card for local parameters
virtual void clearElemAndMaterialCardGlobalParameterInitialization ()
clears initialization of the card and the material card for global parameters
virtual std::istream & readFromInputStream (std::istream &input)
this method reads from the input stream
virtual void getFactor (double &factor, const unsigned int factor_enum_ID)
returns the value of the factor
virtual void getFactorSensitivityForGlobalParameter (double &factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID)
virtual void getFactorSensitivityForLocalParameter (double &factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID)
virtual void getFactor (DenseMatrix< double > &factor, const unsigned int factor_enum_ID)
returns the value of the factor
virtual void getFactorSensitivityForGlobalParameter (DenseMatrix< double > &factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID)
virtual void getFactorSensitivityForLocalParameter (DenseMatrix< double > &factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID)
virtual void getPropertyValueFromMaterialCard (const unsigned int prop_enum_ID, double &value, const unsigned int layer=0)
returns value from material card
virtual void getPropertyValueDerivativeForGlobalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int global_param_ID, double &value, const unsigned int layer=0)
returns value of the derivative of a property from the material card
virtual void getPropertyValueDerivativeForLocalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int local_param_ID, double &value, const unsigned int layer=0)
returns value of the derivative of a property from the material card
Protected Member Functions
virtual std::string getPropertyEnumName (const unsigned int enum_ID) const
virtual const unsigned int getPropertyEnumID (const std::string &enum_name) const
Protected Attributes
unsigned int fluid_material_ID
material card ID for this card
unsigned int wall_material_ID
material card ID for this card
Property::PropertyCard< double > * fluid_material_card
Property::PropertyCard< double > * wall_material_card
Friends
std::istream & operator>> (std::istream &input, ForcedConvection_1D_ElemDataCard &card)
Detailed Description
Definition at line 218 of file ForcedConvection1DElemDataCard.h.
Constructor & Destructor Documentation
ForcedConvection_1D_ElemDataCard::ForcedConvection_1D_ElemDataCard () [inline]
Definition at line 1019 of file ForcedConvection1DElemDataCard.h.
                                                                  :
ElemDataCard()
{
}
ForcedConvection_1D_ElemDataCard::~ForcedConvection_1D_ElemDataCard () [inline, virtual]
Definition at line 1026 of file ForcedConvection1DElemDataCard.h.
{
}
Member Function Documentation
bool ForcedConvection_1D_ElemDataCard::checkElemAndMaterialCardGlobalParameterDependence (const unsigned int global_param_ID) [inline, virtual]
Returns:
true if either the element data card, or the material property card are dependent on the specified global parameter
Implements ElemDataCard.
Definition at line 413 of file ForcedConvection1DElemDataCard.h.
{
  if (this->checkGlobalParameterDependence(global_param_ID) &&
      this->getFluidMaterialCard().checkGlobalParameterDependence(global_param_ID) &&
      this->getWallMaterialCard().checkGlobalParameterDependence(global_param_ID))
    return true;
  else
    return false;
}
bool ForcedConvection_1D_ElemDataCard::checkElemAndMaterialCardLocalParameterDependence (const unsigned int local_param_ID) [inline, virtual]
Returns:
true if either the element data card, or the material property card are dependent on the specified local parameter
Implements ElemDataCard.
Definition at line 429 of file ForcedConvection1DElemDataCard.h.
{
  if (this->checkLocalParameterDependence(local_param_ID) &&
      this->getFluidMaterialCard().checkLocalParameterDependence(local_param_ID) &&
      this->getWallMaterialCard().checkLocalParameterDependence(local_param_ID))
    return true;
  else
    return false;
}
void ForcedConvection_1D_ElemDataCard::clearElemAndMaterialCardGlobalParameterInitialization () [inline, virtual]
clears initialization of the card and the material card for global parameters
Implements ElemDataCard.
Definition at line 506 of file ForcedConvection1DElemDataCard.h.
References Property::PropertyCardBase::clearGlobalParameterInitialization(), getFluidMaterialCard(), and getWallMaterialCard().
{
  Property::PropertyCard<double>& fluid_property = this->getFluidMaterialCard();
  Property::PropertyCard<double>& wall_property = this->getWallMaterialCard();
  this->clearGlobalParameterInitialization();
  fluid_property.clearGlobalParameterInitialization();
  wall_property.clearGlobalParameterInitialization();
}
void ForcedConvection_1D_ElemDataCard::clearElemAndMaterialCardLocalParameterInitialization () [inline, virtual]
clears initialization of the card and the material card for local parameters
Implements ElemDataCard.
Definition at line 477 of file ForcedConvection1DElemDataCard.h.
References Property::PropertyCardBase::clearLocalParameterInitialization(), getFluidMaterialCard(), and getWallMaterialCard().
{
  Property::PropertyCard<double>& fluid_property = this->getFluidMaterialCard();
  Property::PropertyCard<double>& wall_property = this->getWallMaterialCard();
  this->clearLocalParameterInitialization();
  fluid_property.clearLocalParameterInitialization();
  wall_property.clearLocalParameterInitialization();
}
void ForcedConvection_1D_ElemDataCard::getFactor (double & factor, const unsigned int factor_enum_ID) [inline, virtual]
returns the value of the factor
Implements ElemDataCard.
Definition at line 570 of file ForcedConvection1DElemDataCard.h.
References CONVECTIVE_EXCANGE_FACTOR_ENUM_ID, FLUID_CAPACITANCE_FACTOR_ENUM_ID, FLUID_CONDUCTIVITY_FACTOR_ENUM_ID, FLUID_CONVECTIVE_FACTOR_ENUM_ID, getFluidMaterialCard(), Property::PropertyCard< double >::getPropertyValue(), getWallMaterialCard(), DENSITY::num(), SPECIFIC_HEAT::num(), THERMAL_CONDUCTIVITY::num(), WALL_CAPACITANCE_FACTOR_ENUM_ID, and WALL_CONDUCTIVITY_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& wall_property = this->getWallMaterialCard();
  Property::PropertyCard<double>& fluid_property = this->getFluidMaterialCard();
  factor = 0.0;
  static double val1, val2, val3;
  val1 = 0.0; val2 = 0.0, val3 = 0.0;
  switch (factor_enum_ID)
    {
    case FLUID_CONVECTIVE_FACTOR_ENUM_ID:
      {
        // mass_flow * cf
        fluid_property.getPropertyValue(SPECIFIC_HEAT::num(), val1);
        this->getPropertyValue(MASS_FLOW_RATE::num(), val2);
        factor = val1*val2;
      }
      break;
    case CONVECTIVE_EXCANGE_FACTOR_ENUM_ID:
      {
        // h p
        this->getPropertyValue(CONTACT_PERIMETER::num(), val1);
        this->getPropertyValue(CONVECTION_COEFFICIENT::num(), val2);
        factor = val1*val2;
      }
      break;
    case WALL_CONDUCTIVITY_FACTOR_ENUM_ID:
      {
        // kw Aw
        wall_property.getPropertyValue(THERMAL_CONDUCTIVITY::num(), val1);
        this->getPropertyValue(WALL_AREA::num(), val2);
        factor = val1*val2;
      }
      break;
    case FLUID_CONDUCTIVITY_FACTOR_ENUM_ID:
      {
        // kf Af
        fluid_property.getPropertyValue(THERMAL_CONDUCTIVITY::num(), val1);
        this->getPropertyValue(FLUID_AREA::num(), val2);
        factor = val1*val2;
      }
      break;
    case FLUID_CAPACITANCE_FACTOR_ENUM_ID:
      {
        // rhof Af Cf
        fluid_property.getPropertyValue(DENSITY::num(), val1);
        fluid_property.getPropertyValue(SPECIFIC_HEAT::num(), val3);
        this->getPropertyValue(FLUID_AREA::num(), val2);
        factor = val1 * val2 * val3;
      }
      break;
    case WALL_CAPACITANCE_FACTOR_ENUM_ID:
      {
        // rhow Aw Cw
        wall_property.getPropertyValue(DENSITY::num(), val1);
        wall_property.getPropertyValue(SPECIFIC_HEAT::num(), val3);
        this->getPropertyValue(WALL_AREA::num(), val2);
        factor = val1 * val2 * val3;
      }
      break;
default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (ForcedConvection_1D_ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
void ForcedConvection_1D_ElemDataCard::getFactor (DenseMatrix< double > & factor, const unsigned int factor_enum_ID) [inline, virtual]
returns the value of the factor
Implements ElemDataCard.
Definition at line 1042 of file ForcedConvection1DElemDataCard.h.
{
  // params not used for now
  (void) factor;
  (void) factor_enum_ID;
  Assert(false, ExcPureFunctionCalled());
}
void ForcedConvection_1D_ElemDataCard::getFactorSensitivityForGlobalParameter (double & factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID) [inline, virtual]
Implements ElemDataCard.
Definition at line 651 of file ForcedConvection1DElemDataCard.h.
References CONVECTIVE_EXCANGE_FACTOR_ENUM_ID, FLUID_CAPACITANCE_FACTOR_ENUM_ID, FLUID_CONDUCTIVITY_FACTOR_ENUM_ID, FLUID_CONVECTIVE_FACTOR_ENUM_ID, Property::PropertyCard< double >::getPropertyDerivativeForGlobalParameter(), Property::PropertyCard< double >::getPropertyValue(), DENSITY::num(), SPECIFIC_HEAT::num(), THERMAL_CONDUCTIVITY::num(), WALL_CAPACITANCE_FACTOR_ENUM_ID, and WALL_CONDUCTIVITY_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& wall_property = this->getWallMaterialCard();
  Property::PropertyCard<double>& fluid_property = this->getFluidMaterialCard();
  factor = 0.0;
  static double val1, val2, val1_sens, val2_sens, val3, val3_sens;
  val1 = 0.0; val2 = 0.0; val1_sens = 0.0; val2_sens = 0.0; val3 = 0.0; val3_sens = 0.0;
  switch (factor_enum_ID)
    {
    case FLUID_CONVECTIVE_FACTOR_ENUM_ID:
      {
        // mass_flow * cf
        fluid_property.getPropertyValue(SPECIFIC_HEAT::num(), val1);
        fluid_property.getPropertyDerivativeForGlobalParameter(SPECIFIC_HEAT::num(),
                                                               global_param_ID,
                                                               val1_sens);
        this->getPropertyValue(MASS_FLOW_RATE::num(), val2);
        this->getPropertyDerivativeForGlobalParameter(MASS_FLOW_RATE::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case CONVECTIVE_EXCANGE_FACTOR_ENUM_ID:
      {
        // h p
        this->getPropertyValue(CONTACT_PERIMETER::num(), val1);
        this->getPropertyDerivativeForGlobalParameter(CONTACT_PERIMETER::num(),
                                                      global_param_ID,
                                                      val1_sens);
        this->getPropertyValue(CONVECTION_COEFFICIENT::num(), val2);
        this->getPropertyDerivativeForGlobalParameter(CONVECTION_COEFFICIENT::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case WALL_CONDUCTIVITY_FACTOR_ENUM_ID:
      {
        // kw Aw
        wall_property.getPropertyValue(THERMAL_CONDUCTIVITY::num(), val1);
        wall_property.getPropertyDerivativeForGlobalParameter(THERMAL_CONDUCTIVITY::num(),
                                                              global_param_ID,
                                                              val1_sens);
        this->getPropertyValue(WALL_AREA::num(), val2);
        this->getPropertyDerivativeForGlobalParameter(WALL_AREA::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case FLUID_CONDUCTIVITY_FACTOR_ENUM_ID:
      {
        // kf Af
        fluid_property.getPropertyValue(THERMAL_CONDUCTIVITY::num(), val1);
        fluid_property.getPropertyDerivativeForGlobalParameter(THERMAL_CONDUCTIVITY::num(),
                                                               global_param_ID,
                                                               val1_sens);
        this->getPropertyValue(FLUID_AREA::num(), val2);
        this->getPropertyDerivativeForGlobalParameter(FLUID_AREA::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case FLUID_CAPACITANCE_FACTOR_ENUM_ID:
      {
        // rhof Af Cf
        fluid_property.getPropertyValue(DENSITY::num(), val1);
        fluid_property.getPropertyDerivativeForGlobalParameter(DENSITY::num(),
                                                               global_param_ID,
                                                               val1_sens);
        fluid_property.getPropertyValue(SPECIFIC_HEAT::num(), val3);
        fluid_property.getPropertyDerivativeForGlobalParameter(SPECIFIC_HEAT::num(),
                                                               global_param_ID,
                                                               val3_sens);
        this->getPropertyValue(FLUID_AREA::num(), val2);
        this->getPropertyDerivativeForGlobalParameter(FLUID_AREA::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1_sens * val2 * val3 + val1 * val2_sens * val3 + val1 * val2 * val3_sens;
      }
      break;
    case WALL_CAPACITANCE_FACTOR_ENUM_ID:
      {
        // rhow Aw Cw
        wall_property.getPropertyValue(DENSITY::num(), val1);
        wall_property.getPropertyDerivativeForGlobalParameter(DENSITY::num(),
                                                               global_param_ID,
                                                               val1_sens);
        wall_property.getPropertyValue(SPECIFIC_HEAT::num(), val3);
        wall_property.getPropertyDerivativeForGlobalParameter(SPECIFIC_HEAT::num(),
                                                               global_param_ID,
                                                               val3_sens);
        this->getPropertyValue(WALL_AREA::num(), val2);
        this->getPropertyDerivativeForGlobalParameter(WALL_AREA::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1_sens * val2 * val3 + val1 * val2_sens * val3 + val1 * val2 * val3_sens;
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (ForcedConvection_1D_ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
void ForcedConvection_1D_ElemDataCard::getFactorSensitivityForGlobalParameter (DenseMatrix< double > & factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID) [inline, virtual]
Implements ElemDataCard.
Definition at line 1057 of file ForcedConvection1DElemDataCard.h.
{
  // params not used here
  (void) factor;
  (void) factor_enum_ID;
  (void) global_param_ID;
  Assert(false, ExcPureFunctionCalled());
}
void ForcedConvection_1D_ElemDataCard::getFactorSensitivityForLocalParameter (double & factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID) [inline, virtual]
Implements ElemDataCard.
Definition at line 784 of file ForcedConvection1DElemDataCard.h.
References CONVECTIVE_EXCANGE_FACTOR_ENUM_ID, FLUID_CAPACITANCE_FACTOR_ENUM_ID, FLUID_CONDUCTIVITY_FACTOR_ENUM_ID, FLUID_CONVECTIVE_FACTOR_ENUM_ID, Property::PropertyCard< double >::getPropertyDerivativeForLocalParameter(), Property::PropertyCard< double >::getPropertyValue(), DENSITY::num(), SPECIFIC_HEAT::num(), THERMAL_CONDUCTIVITY::num(), WALL_CAPACITANCE_FACTOR_ENUM_ID, and WALL_CONDUCTIVITY_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& wall_property = this->getWallMaterialCard();
  Property::PropertyCard<double>& fluid_property = this->getFluidMaterialCard();
  factor = 0.0;
  static double val1, val2, val1_sens, val2_sens, val3, val3_sens;
  val1 = 0.0; val2 = 0.0; val1_sens = 0.0; val2_sens = 0.0; val3 = 0.0; val3_sens = 0.0;
  switch (factor_enum_ID)
    {
    case FLUID_CONVECTIVE_FACTOR_ENUM_ID:
      {
        // mass_flow * cf
        fluid_property.getPropertyValue(SPECIFIC_HEAT::num(), val1);
        fluid_property.getPropertyDerivativeForLocalParameter(SPECIFIC_HEAT::num(),
                                                               param_enum_ID,
                                                               val1_sens);
        this->getPropertyValue(MASS_FLOW_RATE::num(), val2);
        this->getPropertyDerivativeForLocalParameter(MASS_FLOW_RATE::num(),
                                                      param_enum_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case CONVECTIVE_EXCANGE_FACTOR_ENUM_ID:
      {
        // h p
        this->getPropertyValue(CONTACT_PERIMETER::num(), val1);
        this->getPropertyDerivativeForLocalParameter(CONTACT_PERIMETER::num(),
                                                      param_enum_ID,
                                                      val1_sens);
        this->getPropertyValue(CONVECTION_COEFFICIENT::num(), val2);
        this->getPropertyDerivativeForLocalParameter(CONVECTION_COEFFICIENT::num(),
                                                      param_enum_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case WALL_CONDUCTIVITY_FACTOR_ENUM_ID:
      {
        // kw Aw
        wall_property.getPropertyValue(THERMAL_CONDUCTIVITY::num(), val1);
        wall_property.getPropertyDerivativeForLocalParameter(THERMAL_CONDUCTIVITY::num(),
                                                              param_enum_ID,
                                                              val1_sens);
        this->getPropertyValue(WALL_AREA::num(), val2);
        this->getPropertyDerivativeForLocalParameter(WALL_AREA::num(),
                                                      param_enum_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case FLUID_CONDUCTIVITY_FACTOR_ENUM_ID:
      {
        // kf Af
        fluid_property.getPropertyValue(THERMAL_CONDUCTIVITY::num(), val1);
        fluid_property.getPropertyDerivativeForLocalParameter(THERMAL_CONDUCTIVITY::num(),
                                                               param_enum_ID,
                                                               val1_sens);
        this->getPropertyValue(FLUID_AREA::num(), val2);
        this->getPropertyDerivativeForLocalParameter(FLUID_AREA::num(),
                                                     param_enum_ID,
                                                     val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case FLUID_CAPACITANCE_FACTOR_ENUM_ID:
      {
        // rhof Af Cf
        fluid_property.getPropertyValue(DENSITY::num(), val1);
        fluid_property.getPropertyDerivativeForLocalParameter(DENSITY::num(),
                                                               param_enum_ID,
                                                               val1_sens);
        fluid_property.getPropertyValue(SPECIFIC_HEAT::num(), val3);
        fluid_property.getPropertyDerivativeForLocalParameter(SPECIFIC_HEAT::num(),
                                                               param_enum_ID,
                                                               val3_sens);
        this->getPropertyValue(FLUID_AREA::num(), val2);
        this->getPropertyDerivativeForLocalParameter(FLUID_AREA::num(),
                                                      param_enum_ID,
                                                      val2_sens);
        factor = val1_sens * val2 * val3 + val1 * val2_sens * val3 + val1 * val2 * val3_sens;
      }
      break;
    case WALL_CAPACITANCE_FACTOR_ENUM_ID:
      {
        // rhow Aw Cw
        wall_property.getPropertyValue(DENSITY::num(), val1);
        wall_property.getPropertyDerivativeForLocalParameter(DENSITY::num(),
                                                              param_enum_ID,
                                                              val1_sens);
        wall_property.getPropertyValue(SPECIFIC_HEAT::num(), val3);
        wall_property.getPropertyDerivativeForLocalParameter(SPECIFIC_HEAT::num(),
                                                              param_enum_ID,
                                                              val3_sens);
        this->getPropertyValue(WALL_AREA::num(), val2);
        this->getPropertyDerivativeForLocalParameter(WALL_AREA::num(),
                                                      param_enum_ID,
                                                      val2_sens);
        factor = val1_sens * val2 * val3 + val1 * val2_sens * val3 + val1 * val2 * val3_sens;
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (ForcedConvection_1D_ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
void ForcedConvection_1D_ElemDataCard::getFactorSensitivityForLocalParameter (DenseMatrix< double > & factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID) [inline, virtual]
Implements ElemDataCard.
Definition at line 1073 of file ForcedConvection1DElemDataCard.h.
{
  // params not used here
  (void) factor;
  (void) factor_enum_ID;
  (void) param_enum_ID;
  Assert(false, ExcPureFunctionCalled());
}
Property::PropertyCard< double > & ForcedConvection_1D_ElemDataCard::getFluidMaterialCard () [inline]
returns the fluid material card for this card
Definition at line 542 of file ForcedConvection1DElemDataCard.h.
References fluid_material_card, fluid_material_ID, Property::PropertyDatabase::getMaterialPropertyCardFromID(), and ElemDataCard::property_database.
Referenced by clearElemAndMaterialCardGlobalParameterInitialization(), clearElemAndMaterialCardLocalParameterInitialization(), getFactor(), and partialClearElemAndMaterialCardLocalParameterInitialization().
{
  if (this->fluid_material_card == NULL)
    this->fluid_material_card =
      &(this->property_database->getMaterialPropertyCardFromID<double>(this->fluid_material_ID));
  return *(this->fluid_material_card);
}
unsigned int ForcedConvection_1D_ElemDataCard::getFluidMaterialCardID () const [inline]
returns the fluid material card ID for this card
Definition at line 520 of file ForcedConvection1DElemDataCard.h.
References fluid_material_ID, and FESystemNumbers::InvalidID.
{
  Assert(this->fluid_material_ID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(this->fluid_material_ID));
  return this->fluid_material_ID;
}
unsigned int ForcedConvection_1D_ElemDataCard::getPropertyCardKindEnumID () const [inline, virtual]
Returns:
the property card kind enumeration ID
Implements Property::PropertyCardBase.
Definition at line 373 of file ForcedConvection1DElemDataCard.h.
{
  return FORCED_CONVECTION_1D_ELEM_DATA_CARD::num();
}
const std::string ForcedConvection_1D_ElemDataCard::getPropertyCardKindEnumName () const [inline, virtual]
Returns:
the property card kind enumeration name
Implements Property::PropertyCardBase.
Definition at line 384 of file ForcedConvection1DElemDataCard.h.
Referenced by readFromInputStream().
{
  return FORCED_CONVECTION_1D_ELEM_DATA_CARD::name();
}
const unsigned int ForcedConvection_1D_ElemDataCard::getPropertyEnumID (const std::string & enum_name) const [inline, protected, virtual]
Returns:
the property ID from enumeration name of the property
Implements Property::PropertyCard< double >.
Definition at line 403 of file ForcedConvection1DElemDataCard.h.
Referenced by readFromInputStream().
{
  return ForcedConvection_1D_ElemDataEnum::enumID(enum_name);
}
std::string ForcedConvection_1D_ElemDataCard::getPropertyEnumName (const unsigned int enum_ID) const [inline, protected, virtual]
Returns:
the property name from enumeration ID of the property
Implements Property::PropertyCard< double >.
Definition at line 394 of file ForcedConvection1DElemDataCard.h.
{
  return ForcedConvection_1D_ElemDataEnum::enumName(enum_ID);
}
virtual void ForcedConvection_1D_ElemDataCard::getPropertyValueDerivativeForGlobalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int global_param_ID, double & value, const unsigned int layer = 0) [inline, virtual]
returns value of the derivative of a property from the material card
Implements ElemDataCard.
Definition at line 313 of file ForcedConvection1DElemDataCard.h.
  {
    // params not used here
    (void) prop_enum_ID;
    (void) global_param_ID;
    (void) value;
    (void) layer;
    Assert(false, ExcInternalError());
  }
virtual void ForcedConvection_1D_ElemDataCard::getPropertyValueDerivativeForLocalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int local_param_ID, double & value, const unsigned int layer = 0) [inline, virtual]
returns value of the derivative of a property from the material card
Implements ElemDataCard.
Definition at line 330 of file ForcedConvection1DElemDataCard.h.
  {
    // params not used here
    (void) prop_enum_ID;
    (void) local_param_ID;
    (void) value;
    (void) layer;
    Assert(false, ExcInternalError());
  }
virtual void ForcedConvection_1D_ElemDataCard::getPropertyValueFromMaterialCard (const unsigned int prop_enum_ID, double & value, const unsigned int layer = 0) [inline, virtual]
returns value from material card
Implements ElemDataCard.
Definition at line 299 of file ForcedConvection1DElemDataCard.h.
  {
    // params not used here
    (void) prop_enum_ID;
    (void) value;
    (void) layer;
    Assert(false, ExcInternalError());
  }
Property::PropertyCard< double > & ForcedConvection_1D_ElemDataCard::getWallMaterialCard () [inline]
returns the wall material card for this card
Definition at line 556 of file ForcedConvection1DElemDataCard.h.
References Property::PropertyDatabase::getMaterialPropertyCardFromID(), ElemDataCard::property_database, wall_material_card, and wall_material_ID.
Referenced by clearElemAndMaterialCardGlobalParameterInitialization(), clearElemAndMaterialCardLocalParameterInitialization(), getFactor(), and partialClearElemAndMaterialCardLocalParameterInitialization().
{
  if (this->wall_material_card == NULL)
    this->wall_material_card =
      &(this->property_database->getMaterialPropertyCardFromID<double>(this->wall_material_ID));
  return *(this->wall_material_card);
}
unsigned int ForcedConvection_1D_ElemDataCard::getWallMaterialCardID () const [inline]
returns the wall material card ID for this card
Definition at line 530 of file ForcedConvection1DElemDataCard.h.
References FESystemNumbers::InvalidID, and wall_material_ID.
{
  Assert(this->wall_material_ID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(this->wall_material_ID));
  return this->wall_material_ID;
}
void ForcedConvection_1D_ElemDataCard::partialClearElemAndMaterialCardLocalParameterInitialization (std::vector< unsigned int > & param_ids) [inline, virtual]
clears initialization of the card and the material card for local parameters
Implements ElemDataCard.
Definition at line 492 of file ForcedConvection1DElemDataCard.h.
References getFluidMaterialCard(), getWallMaterialCard(), and Property::PropertyCardBase::partialClearLocalParameterInitialization().
{
  Property::PropertyCard<double>& fluid_property = this->getFluidMaterialCard();
  Property::PropertyCard<double>& wall_property = this->getWallMaterialCard();
  this->partialClearLocalParameterInitialization(param_ids);
  fluid_property.partialClearLocalParameterInitialization(param_ids);
  wall_property.partialClearLocalParameterInitialization(param_ids);
}
std::istream & ForcedConvection_1D_ElemDataCard::readFromInputStream (std::istream & input) [inline, virtual]
this method reads from the input stream
Implements ElemDataCard.
Definition at line 914 of file ForcedConvection1DElemDataCard.h.
References Property::PropertyCardBase::cardID, fluid_material_ID, Property::PropertyCardBase::getNParameters(), Property::PropertyCard< double >::getNProperties(), Property::PropertyCardBase::getParameterInternalID(), getPropertyCardKindEnumName(), getPropertyEnumID(), Property::PropertyCardBase::getPropertyInternalID(), FESystemNumbers::InvalidID, Property::PropertyCardBase::parameter_function_ID_table, Property::PropertyCardBase::parameter_function_value_table, Property::PropertyCardBase::property_enumID_to_internal_ID_map, Property::PropertyCard< double >::property_reference_values, FESystemIOUtility::readFromInput(), Property::PropertyCardBase::readParametersFromInputStream(), and wall_material_ID.
Referenced by operator>>().
{
  std::string tag;
  // read the beginning data of the card
  tag = this->getPropertyCardKindEnumName();
  FESystemIOUtility::readFromInput(input, tag);
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->cardID);
  FESystemIOUtility::readFromInput(input, "FLUID_MATERIAL_PROPERTY_CARD_ID", this->fluid_material_ID);
  FESystemIOUtility::readFromInput(input, "WALL_MATERIAL_PROPERTY_CARD_ID", this->wall_material_ID);
  // now read in the property base values
  {
    unsigned int n_prop = 0, prop_ID = 0;
    double value = 0.0;
    bool insert_success = false;
    FESystemIOUtility::readFromInput(input, "N_PROPERTIES", n_prop);
    Property::PropertyCard<double>::PropertyMap::iterator prop_it;
    for (unsigned int i=0; i<n_prop; i++)
      {
      tag.clear(); value = 0.0;
      input >> tag;
      prop_ID = this->getPropertyEnumID(tag);
      input >> value;
      // now insert the value in the map
      insert_success = this->property_reference_values.insert
        (Property::PropertyCard<double>::PropertyMap::value_type
         (prop_ID, value)).second;
      Assert(insert_success,
             Property::PropertyCardBase::ExcDuplicatePropertySpecified(tag));
      insert_success = this->property_enumID_to_internal_ID_map.insert
        (Property::PropertyCardBase::IDMap::value_type(prop_ID, i)).second;
      // if the previous assert was true, this one should also be true.
      Assert(insert_success,
             Property::PropertyCardBase::ExcDuplicatePropertySpecified(tag));
      }
  }
  // now read the parameters
  this->readParametersFromInputStream(input);
  // now read in the property-parameter function ID table
  {
    // first initialize the table
    unsigned int n_prop = this->getNProperties(),
    n_param = this->getNParameters();
    this->parameter_function_ID_table->reinit(n_prop, n_param);
    this->parameter_function_ID_table->reset_values(FESystemNumbers::InvalidID);
    TableIndices<3> indices(n_prop, n_param, 2);
    this->parameter_function_value_table->reinit(indices);
    this->parameter_function_value_table->reset_values(0.0);
    unsigned int n_func_IDs, prop_ID = 0, param_ID = 0, func_ID = 0,
      prop_internal_ID = 0, param_internal_ID = 0;
    FESystemIOUtility::readFromInput(input, "N_FUNCTION_IDS", n_func_IDs);
    for (unsigned int i=0; i<n_func_IDs; i++)
      {
      tag.clear();
      input >> tag;
      prop_ID = this->getPropertyEnumID(tag);
      input >> param_ID;
      input >> func_ID;
      // get the internal IDS
      prop_internal_ID = this->getPropertyInternalID(prop_ID);
      param_internal_ID = this->getParameterInternalID(param_ID);
      // and, insert the value in the table
      // first make sure that this property hasn't already been set.
      Assert((*this->parameter_function_ID_table)(prop_internal_ID, param_internal_ID)  ==
             FESystemNumbers::InvalidID,
             FESystemExceptions::ExcDuplicateID("Property Function",prop_internal_ID));
      // and, insert the value in the table
      (*this->parameter_function_ID_table)(prop_internal_ID, param_internal_ID) = func_ID;
      }
  }
  // the card should end with the END tag
  tag = this->getPropertyCardKindEnumName();
  FESystemIOUtility::readFromInput(input, tag);
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
void ForcedConvection_1D_ElemDataCard::reinitElemAndMaterialCardForGlobalParameters (std::map< unsigned int, double > & value_map) [inline, virtual]
initializes the card and the material card for the given global parameters
Implements ElemDataCard.
Definition at line 460 of file ForcedConvection1DElemDataCard.h.
References Property::PropertyCardBase::reinitGlobalParameters().
{
  Property::PropertyCard<double>& fluid_property = this->getFluidMaterialCard();
  Property::PropertyCard<double>& wall_property = this->getWallMaterialCard();
  this->reinitGlobalParameters(value_map);
  fluid_property.reinitGlobalParameters(value_map);
  wall_property.reinitGlobalParameters(value_map);
}
void ForcedConvection_1D_ElemDataCard::reinitElemAndMaterialCardForLocalParameters (std::map< unsigned int, double > * value_map = NULL) [inline, virtual]
initializes the card and the material card for the given local parameters
Implements ElemDataCard.
Definition at line 444 of file ForcedConvection1DElemDataCard.h.
References Property::PropertyCardBase::reinitLocalParameters().
{
  Property::PropertyCard<double>& fluid_property = this->getFluidMaterialCard();
  Property::PropertyCard<double>& wall_property = this->getWallMaterialCard();
  this->reinitLocalParameters(value_map);
  fluid_property.reinitLocalParameters(value_map);
  wall_property.reinitLocalParameters(value_map);
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, ForcedConvection_1D_ElemDataCard & card) [friend]
Definition at line 1033 of file ForcedConvection1DElemDataCard.h.
{
  return card.readFromInputStream(input);
}
Member Data Documentation
Property::PropertyCard<double>* ForcedConvection_1D_ElemDataCard::fluid_material_card [protected]
this is a pointer to the material property card for this element, and is stored for convenience
Definition at line 362 of file ForcedConvection1DElemDataCard.h.
Referenced by getFluidMaterialCard().
unsigned int ForcedConvection_1D_ElemDataCard::fluid_material_ID [protected]
material card ID for this card
Definition at line 355 of file ForcedConvection1DElemDataCard.h.
Referenced by getFluidMaterialCard(), getFluidMaterialCardID(), and readFromInputStream().
Property::PropertyCard<double>* ForcedConvection_1D_ElemDataCard::wall_material_card [protected]
this is a pointer to the material property card for this element, and is stored for convenience
Definition at line 366 of file ForcedConvection1DElemDataCard.h.
Referenced by getWallMaterialCard().
unsigned int ForcedConvection_1D_ElemDataCard::wall_material_ID [protected]
material card ID for this card
Definition at line 358 of file ForcedConvection1DElemDataCard.h.
Referenced by getWallMaterialCard(), getWallMaterialCardID(), and readFromInputStream().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/ForcedConvection1DElemDataCard.h