fesystem: FESystemUtility::HeaderEventData Class Reference
FESystemUtility::HeaderEventData Class Reference
this class stores the information for a header
#include <TimeLogs.h>
Public Types
enum EventStatus { RUNNING, STOPPED }
enumeration of the status for event logs
Public Member Functions
HeaderEventData ()
constructor
~HeaderEventData ()
destructor
const std::string & getCurrentEvent () const
unsigned int getEventCallCount (const std::string &event_name) const
FESystemUtility::HeaderEventData::EventStatus getCurrentStatus () const
void removeCurrentEvent (const std::string &event_name)
removes the current event
void setCurrentEvent (const std::string &event_name)
sets the current event
bool eventsExist () const
void printEventCallCount (std::ostream &output)
prints the event stack for this header
Protected Attributes
std::stack< std::string > event_stack
current event
std::map< std::string,
unsigned int > event_call_count
call count for open events
Detailed Description
this class stores the information for a header
Definition at line 188 of file TimeLogs.h.
Member Enumeration Documentation
enum FESystemUtility::HeaderEventData::EventStatus
enumeration of the status for event logs
Enumerator:
RUNNING
STOPPED
Definition at line 192 of file TimeLogs.h.
{RUNNING, STOPPED};
Constructor & Destructor Documentation
FESystemUtility::HeaderEventData::HeaderEventData ()
constructor
Definition at line 28 of file TimeLogs.C.
{
}
FESystemUtility::HeaderEventData::~HeaderEventData ()
destructor
Definition at line 37 of file TimeLogs.C.
{
  // make sure that no open events exist
  Assert(this->event_stack.empty(), ExcInternalError());
  // also, iterate on all events, and make sure that their call counters are all zero
  std::map<std::string, unsigned int>::const_iterator it, end;
  it = this->event_call_count.begin();
  end = this->event_call_count.end();
  for (; it != end; it++)
    {
    Assert(it->second == 0, ExcInternalError());
    }
}
Member Function Documentation
bool FESystemUtility::HeaderEventData::eventsExist () const
Returns:
true if some events exist in this header
Definition at line 122 of file TimeLogs.C.
{
  if (this->event_stack.empty())
    return false;
  else
    return true;
}
const std::string & FESystemUtility::HeaderEventData::getCurrentEvent () const
Returns:
current event
Definition at line 58 of file TimeLogs.C.
Referenced by FESystemUtility::TimeLogs::setEvent().
{
  return this->event_stack.top();
}
FESystemUtility::HeaderEventData::EventStatus FESystemUtility::HeaderEventData::getCurrentStatus () const
Returns:
current status
Definition at line 79 of file TimeLogs.C.
References RUNNING, and STOPPED.
Referenced by FESystemUtility::TimeLogs::setEvent().
{
  // if there is nothing in the stack, things were stopped. Else, they are running
  if (this->event_stack.empty())
    return FESystemUtility::HeaderEventData::STOPPED;
  else
    return FESystemUtility::HeaderEventData::RUNNING;
}
unsigned int FESystemUtility::HeaderEventData::getEventCallCount (const std::string & event_name) const
Returns:
call count of an event
Definition at line 67 of file TimeLogs.C.
Referenced by FESystemUtility::TimeLogs::setEvent().
{
  if (this->event_call_count.count(event_name) == 0)
    return 0;
  else
    return this->event_call_count.find(event_name)->second;
}
void FESystemUtility::HeaderEventData::printEventCallCount (std::ostream & output)
prints the event stack for this header
Definition at line 132 of file TimeLogs.C.
{
  std::map<std::string, unsigned int>::const_iterator it, end;
  it = this->event_call_count.begin();
  end = this->event_call_count.end();
  output << "Event Call Count: " << std::endl;
  for (; it != end; it++)
    {
    output << it->first << "   " << it->second << std::endl;
    }
  if (this->event_stack.size() > 0)
    output << "Top Event in Stack :  " << this->event_stack.top() << std::endl;
  else
    output << "No Event in Stack" << std::endl;
  output << std::endl;
}
void FESystemUtility::HeaderEventData::removeCurrentEvent (const std::string & event_name)
removes the current event
Definition at line 91 of file TimeLogs.C.
Referenced by FESystemUtility::TimeLogs::unsetEvent().
{
  // make sure that this is same as the current event
  Assert(this->getCurrentEvent() == event_name, ExcInternalError());
  Assert(this->event_call_count.count(event_name) > 0, ExcInternalError());
  this->event_stack.pop();
  // also decrement the counter of the event call map
  this->event_call_count[event_name] --;
}
void FESystemUtility::HeaderEventData::setCurrentEvent (const std::string & event_name)
sets the current event
Definition at line 107 of file TimeLogs.C.
Referenced by FESystemUtility::TimeLogs::setEvent().
{
  // push this event on the top of the event stack
  this->event_stack.push(event_name);
  // increment the call counter for this event
  if (this->event_call_count.count(event_name) == 0)
    this->event_call_count[event_name] = 0;
  this->event_call_count[event_name] ++;
}
Member Data Documentation
std::map<std::string, unsigned int> FESystemUtility::HeaderEventData::event_call_count [protected]
call count for open events
Definition at line 226 of file TimeLogs.h.
std::stack<std::string> FESystemUtility::HeaderEventData::event_stack [protected]
current event
Definition at line 223 of file TimeLogs.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Utilities/TimeLogs.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Utilities/TimeLogs.C