fesystem: LoadDatabase Class Reference
LoadDatabase Class Reference
#include <LoadDatabase.h>
Public Member Functions
LoadDatabase (FESystem::FESystemController &controller)
~LoadDatabase ()
void clear ()
clear the data stored in the database
FESystem::FESystemController & getFESystemController () const
std::istream & readFromInputStream (std::istream &)
function to read the load set and load case definition from a text file
template<typename LoadInfoType , typename LoadComboType >
void getLoadCombination (const LoadInfoType &load_info, LoadComboType &load_combo)
template<typename LoadInfoType , typename LoadComboType >
FESystemUtility::AutoPtrVector
< LoadComboType > getAllLoadCombinations (const LoadInfoType &load_info)
template<typename LoadInfoType >
unsigned int getLoadSetID (const LoadInfoType &load_info)
const LoadCaseBase & getLoadCaseFromID (const unsigned int) const
const LoadSetBase & getLoadSetFromID (const unsigned int) const
void addLoadSet (LoadSetBase *load_set)
void addLoadCase (LoadCaseBase *load_case)
unsigned int getAvailableLoadSetID () const
Protected Member Functions
template<typename LoadInfoType >
void getLoadFactorAndSetIDPair (const LoadInfoType &load_info, std::vector< std::pair< unsigned int, double > > &load_pair)
template<typename LoadType , typename LoadSetType , typename LoadComboType >
void getElemVolumeLoadCombination (const unsigned int load_case_ID, const unsigned int elem_ID, const unsigned int load_enum_ID, const bool if_time_dep, const double time_instant, const bool if_sensitivity, const unsigned int DV_ID, LoadComboType &load_combo)
template<typename LoadType , typename LoadSetType , typename LoadComboType >
void getNodalLoadCombination (const unsigned int load_case_ID, const unsigned int node_ID, const unsigned int load_enum_ID, const bool if_time_dep, const double time_instant, const bool if_sensitivity, const unsigned int DV_ID, LoadComboType &load_combo)
template<typename LoadType , typename LoadSetType , typename LoadComboType >
void getElemSurfaceLoadCombinationForSide (const unsigned int load_case_ID, const unsigned int elem_ID, const unsigned int side_ID, const unsigned int load_enum_ID, const bool if_time_dep, const double time_instant, const bool if_sensitivity, const unsigned int DV_ID, LoadComboType &load_combo)
template<typename LoadType , typename LoadSetType , typename LoadComboType >
FESystemUtility::AutoPtrVector
< LoadComboType > getAllNodalLoadCombination (const unsigned int load_case_ID, const unsigned int load_enum_ID, const bool if_time_dep, const double time_instant, const bool if_sensitivity, const unsigned int DV_ID)
Protected Attributes
FESystem::FESystemController & fesystem_controller
std::map< unsigned int,
LoadSetBase * > load_set_map
std::map< unsigned int,
LoadCaseBase * > load_case_map
Detailed Description
This class will store all the loads and will provide methods to obtain loads based on certain criterion, which could be load case, time instant, element ID, load tag, etc. The results for all these will be returned as a vector of Load. The idea of this class is similar to that of a database where you store all the data, perform a search on it, and return the results.
Definition at line 33 of file LoadDatabase.h.
Constructor & Destructor Documentation
LoadDatabase::LoadDatabase (FESystem::FESystemController & controller)
Definition at line 16 of file LoadDatabase.C.
                                                                :
fesystem_controller(controller)
{
}
LoadDatabase::~LoadDatabase ()
Definition at line 24 of file LoadDatabase.C.
References clear().
{
  this->clear();
}
Member Function Documentation
void LoadDatabase::addLoadCase (LoadCaseBase * load_case)
Definition at line 84 of file LoadDatabase.C.
References LoadCaseBase::getLoadCaseID(), and load_case_map.
Referenced by readFromInputStream().
{
  // make sure that the pointer is not NULL and that ID does not already exist
  assert (load_case_ptr != NULL);
  unsigned int load_case_ID = load_case_ptr->getLoadCaseID();
  // make sure that this load case does not already exist
  AssertThrow(this->load_case_map.count(load_case_ID) == 0,
              ExcInternalError());
  std::pair<std::map<unsigned int, LoadCaseBase*>::iterator, bool > insert_return_value =
  this->load_case_map.insert(std::map<unsigned int, LoadCaseBase*>::value_type
                             (load_case_ID, load_case_ptr));
  assert (insert_return_value.second);
}
void LoadDatabase::addLoadSet (LoadSetBase * load_set)
Definition at line 63 of file LoadDatabase.C.
References LoadSetBase::getLoadSetID(), and load_set_map.
Referenced by DirectInterpolation::createLoads(), InterpolationDriver::createLoads(), and readFromInputStream().
{
  // make sure that the pointer is not NULL and that ID does not already exist
  assert (load_set_ptr != NULL);
  unsigned int load_set_ID = load_set_ptr->getLoadSetID();
  assert (this->load_set_map.find(load_set_ID) ==
          this->load_set_map.end());
  std::pair<std::map<unsigned int, LoadSetBase*>::iterator, bool > insert_return_value =
  this->load_set_map.insert(std::map<unsigned int, LoadSetBase*>::value_type(load_set_ID,
                                                                             load_set_ptr));
  assert (insert_return_value.second == true);
}
void LoadDatabase::clear ()
clear the data stored in the database
Definition at line 32 of file LoadDatabase.C.
References load_case_map, and load_set_map.
Referenced by InterpolationDriver::createLoads(), and ~LoadDatabase().
{
  // iterate over all elements in the map, and delete the pointers
  std::map<unsigned int, LoadSetBase*>::iterator load_set_it = this->load_set_map.begin();
  std::map<unsigned int, LoadSetBase*>::const_iterator load_set_end = this->load_set_map.end();
  for (; load_set_it != load_set_end; load_set_it++)
    {
      delete load_set_it->second;
      load_set_it->second = NULL;
    }
  this->load_set_map.clear();
  std::map<unsigned int, LoadCaseBase*>::iterator load_case_it =
  this->load_case_map.begin();
  std::map<unsigned int, LoadCaseBase*>::const_iterator load_case_end =
  this->load_case_map.end();
  for (; load_case_it != load_case_end; load_case_it++)
    {
      delete load_case_it->second;
      load_case_it->second = NULL;
    }
  this->load_case_map.clear();
}
template<typename LoadInfoType , typename LoadComboType > FESystemUtility::AutoPtrVector<LoadComboType> LoadDatabase::getAllLoadCombinations (const LoadInfoType & load_info)
this will return all the loads from a load case for a specified time instant and tag. this is specifically for loads that are not element related, like nodal loads
Referenced by Driver::EigenProblemAnalysisDriver::applyBoundaryConditionsForCurrentAnalysis(), Driver::AnalysisDriver::applyBoundaryConditionsToMatrixForCurrentAnalysis(), Driver::AnalysisDriver::applyBoundaryConditionsToVectorForCurrentAnalysis(), Driver::RogerApproximationAeroelasticityDriver::createSubMatrixIndices(), and Driver::EigenProblemAnalysisDriver::getSubmatrixAfterBoundaryCondition().
template<typename LoadType , typename LoadSetType , typename LoadComboType > FESystemUtility::AutoPtrVector<LoadComboType> LoadDatabase::getAllNodalLoadCombination (const unsigned int load_case_ID, const unsigned int load_enum_ID, const bool if_time_dep, const double time_instant, const bool if_sensitivity, const unsigned int DV_ID) [protected]
unsigned int LoadDatabase::getAvailableLoadSetID () const
Definition at line 215 of file LoadDatabase.C.
References load_set_map.
Referenced by DirectInterpolation::createLoads().
{
  unsigned int load_set_ID = 0;
  if (this->load_set_map.size() == 0)
    load_set_ID = 1;
  else
    load_set_ID = (this->load_set_map.rbegin()->first) + 1;
  return load_set_ID;
}
template<typename LoadType , typename LoadSetType , typename LoadComboType > void LoadDatabase::getElemSurfaceLoadCombinationForSide (const unsigned int load_case_ID, const unsigned int elem_ID, const unsigned int side_ID, const unsigned int load_enum_ID, const bool if_time_dep, const double time_instant, const bool if_sensitivity, const unsigned int DV_ID, LoadComboType & load_combo) [protected]
template<typename LoadType , typename LoadSetType , typename LoadComboType > void LoadDatabase::getElemVolumeLoadCombination (const unsigned int load_case_ID, const unsigned int elem_ID, const unsigned int load_enum_ID, const bool if_time_dep, const double time_instant, const bool if_sensitivity, const unsigned int DV_ID, LoadComboType & load_combo) [protected]
FESystem::FESystemController & LoadDatabase::getFESystemController () const [inline]
Returns:
the fesystem controller
Definition at line 144 of file LoadDatabase.h.
References fesystem_controller.
Referenced by TimeDependentLoadCase::getLoadPair().
{
  return this->fesystem_controller;
}
const LoadCaseBase & LoadDatabase::getLoadCaseFromID (const unsigned int ID) const
Definition at line 182 of file LoadDatabase.C.
References load_case_map.
Referenced by DirectInterpolation::createLoads().
{
  // make sure that the load case with this ID exists
  std::map<unsigned int, LoadCaseBase* >::const_iterator load_case_it =
  this->load_case_map.find(ID);
  assert (load_case_it != this->load_case_map.end());
  return *(load_case_it->second);
}
template<typename LoadInfoType , typename LoadComboType > void LoadDatabase::getLoadCombination (const LoadInfoType & load_info, LoadComboType & load_combo)
this will return the loads acting on an element from the specified load case and time instant
template<typename LoadInfoType > void LoadDatabase::getLoadFactorAndSetIDPair (const LoadInfoType & load_info, std::vector< std::pair< unsigned int, double > > & load_pair) [protected]
const LoadSetBase & LoadDatabase::getLoadSetFromID (const unsigned int ID) const
Definition at line 199 of file LoadDatabase.C.
References load_set_map.
{
  // make sure that the load set with this ID exists
  // make sure that the load case with this ID exists
  std::map<unsigned int, LoadSetBase* >::const_iterator load_set_it =
  this->load_set_map.find(ID);
  assert (load_set_it != this->load_set_map.end());
  return *(load_set_it->second);
}
template<typename LoadInfoType > unsigned int LoadDatabase::getLoadSetID (const LoadInfoType & load_info)
returns the load set ID for the load given by the name in the load case
Parameters:
load_case number of the load case
time_instant the time instant for which load is needed
load_name name of the load for which set ID is being seeked
Referenced by InterpolationDriver::createLoads().
template<typename LoadType , typename LoadSetType , typename LoadComboType > void LoadDatabase::getNodalLoadCombination (const unsigned int load_case_ID, const unsigned int node_ID, const unsigned int load_enum_ID, const bool if_time_dep, const double time_instant, const bool if_sensitivity, const unsigned int DV_ID, LoadComboType & load_combo) [protected]
std::istream & LoadDatabase::readFromInputStream (std::istream & input)
function to read the load set and load case definition from a text file
Definition at line 106 of file LoadDatabase.C.
References addLoadCase(), addLoadSet(), createLoadCase(), createLoadSet(), FESystemIOUtility::peekFromInput(), and FESystemIOUtility::readFromInput().
{
  unsigned int num_load_set=0, num_load_case=0, enum_ID=0;
  std::string tag;
  // the data should begin with tag BEGIN_LOAD_SET_DATA
  // which should be followed by an
  // integer specifying the number of load sets
  FESystemIOUtility::readFromInput(input, "LOAD_DATABASE");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "LOAD_SET_DATA");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "N_LOAD_SETS", num_load_set);
  std::auto_ptr<LoadSetBase> load_set;
  for (unsigned int load_set_incr=0; load_set_incr < num_load_set; load_set_incr++)
    {
      tag.clear();
      FESystemIOUtility::peekFromInput(input, tag);
      enum_ID = LoadSetKindEnum::enumID(tag);
      load_set.reset(createLoadSet(enum_ID).release());
      load_set->readFromInputStream(input);
      this->addLoadSet(load_set.release());
    }
  // the load set data should end with the END tag
  FESystemIOUtility::readFromInput(input, "LOAD_SET_DATA");
  FESystemIOUtility::readFromInput(input, "END");
  // this should be followed by load case data, which will begin with the
  // tag BEGIN_LOAD_CASE_DATA, followed by an integer specifying the number
  // of load cases
  FESystemIOUtility::readFromInput(input, "LOAD_CASE_DATA");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "N_LOAD_CASES", num_load_case);
  unsigned int load_case_type_enum_ID=0;
  std::auto_ptr<LoadCaseBase> load_case_ptr;
  for (unsigned int load_case_incr=0; load_case_incr < num_load_case; load_case_incr++)
    {
      // check which kind of load case is provided
      tag.clear();
      FESystemIOUtility::peekFromInput(input, tag);
      load_case_type_enum_ID = LoadCaseKindEnum::enumID(tag);
      load_case_ptr.reset(createLoadCase(load_case_type_enum_ID, *this).release());
      load_case_ptr->readFromInputStream(input);
      this->addLoadCase(load_case_ptr.release());
    }
  // the load case data will end with an END tag
  FESystemIOUtility::readFromInput(input, "LOAD_CASE_DATA");
  FESystemIOUtility::readFromInput(input, "END");
  FESystemIOUtility::readFromInput(input, "LOAD_DATABASE");
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Member Data Documentation
FESystem::FESystemController& LoadDatabase::fesystem_controller [protected]
Definition at line 130 of file LoadDatabase.h.
Referenced by getFESystemController().
std::map<unsigned int, LoadCaseBase*> LoadDatabase::load_case_map [protected]
Definition at line 136 of file LoadDatabase.h.
Referenced by addLoadCase(), clear(), and getLoadCaseFromID().
std::map<unsigned int, LoadSetBase*> LoadDatabase::load_set_map [protected]
Definition at line 133 of file LoadDatabase.h.
Referenced by addLoadSet(), clear(), getAvailableLoadSetID(), and getLoadSetFromID().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadDatabase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadDatabase.C