fesystem: GeometricEllipticArc Class Reference
GeometricEllipticArc Class Reference
this class defines a geometric point
#include <GeometricEllipticArc.h>
Public Member Functions
GeometricEllipticArc (GeometricModel &)
constructor
virtual ~GeometricEllipticArc ()
destructor
virtual GeometricEntityType type () const
returns the type of this entity
virtual bool checkIfDuplicate (const GeometricEntity &)
method to check if this object is a duplicate of the given object
Protected Member Functions
virtual void readFromInput (std::istream &)
method to read from input
virtual void writeToOutput (std::ostream &)
method to write to output
Protected Attributes
std::vector< GeometricPoint * > points
location of this point
Detailed Description
this class defines a geometric point
Definition at line 17 of file GeometricEllipticArc.h.
Constructor & Destructor Documentation
GeometricEllipticArc::GeometricEllipticArc (GeometricModel & model)
constructor
Definition at line 15 of file GeometricEllipticArc.C.
  :GeometricLine(model)
{
}
GeometricEllipticArc::~GeometricEllipticArc () [virtual]
destructor
Definition at line 22 of file GeometricEllipticArc.C.
{
}
Member Function Documentation
bool GeometricEllipticArc::checkIfDuplicate (const GeometricEntity & arc_ref) [virtual]
method to check if this object is a duplicate of the given object
Implements GeometricLine.
Definition at line 28 of file GeometricEllipticArc.C.
References GeometricEntity::base_entity_ID, GeometricEntity::baseEntityID(), Location::coord1, Location::coord2, Location::coord3, GeometricEntity::ELLIPTIC_ARC, GeometricEntity::geometric_model, GeometricPoint::getLocation(), GeometricModel::getPointForID(), GeometricLine::getPoints(), GeometricEntity::is_duplicate, points, GeometricEntity::same_orientation_as_base_entity, and GeometricEntity::type().
{
  // make sure that the two arcs are not the same object
  assert (&arc_ref != this);
  // also, its type should be an elliptic arc
  if (arc_ref.type() != GeometricEntity::ELLIPTIC_ARC)
    return false;
  // convert this line's reference to a geometric arc
  const GeometricEllipticArc& arc = dynamic_cast<const GeometricEllipticArc&>(arc_ref);
  // get the points for this arc
  const std::vector<GeometricPoint*>& arc_points = arc.getPoints();
  // compare the point IDs of this line with that of the given line
  // the comparisons should be made only with the base entity IDs
  unsigned int this_point1 = this->points[0]->baseEntityID();
  unsigned int this_point2 = this->points[3]->baseEntityID();
  unsigned int this_center = this->points[1]->baseEntityID();
  unsigned int this_major_axis_point = this->points[2]->baseEntityID();
  // calculate the unit vector along the mahor axis
  Location center, major_axis_point;
  center = this->geometric_model.getPointForID(this_center).getLocation();
  major_axis_point = this->geometric_model.getPointForID(this_major_axis_point).getLocation();
  Point this_major_axis_unit_vec(major_axis_point.coord1 - center.coord1,
                                 major_axis_point.coord2 - center.coord2,
                                 major_axis_point.coord3 - center.coord3);
  TypeVector<double> this_unit_vec(this_major_axis_unit_vec.unit());
  unsigned int given_point1 = arc_points[0]->baseEntityID();
  unsigned int given_point2 = arc_points[3]->baseEntityID();
  unsigned int given_center = arc_points[1]->baseEntityID();
  unsigned int given_major_axis_point = arc_points[2]->baseEntityID();
  // calculate the unit vector along the major axis
  center = this->geometric_model.getPointForID(given_center).getLocation();
  major_axis_point = this->geometric_model.getPointForID(given_major_axis_point).getLocation();
  Point given_major_axis_unit_vec(major_axis_point.coord1 - center.coord1,
                                 major_axis_point.coord2 - center.coord2,
                                 major_axis_point.coord3 - center.coord3);
  TypeVector<double> given_unit_vec(given_major_axis_unit_vec.unit());
  // if the two centers are not the same, the the arcs are different
  if (this_center != given_center)
    return false;
  // next compare the unit vectors. They should be the same vectors, either parallel or
  // anti-parallel
  double dot_prod = this_unit_vec * given_unit_vec;
  double machine_eps = 1.0e-12;
  // if the two vectors do not have a unity dot product, they are not coincidental
  if ( fabs(fabs(dot_prod)-1.0) > machine_eps)
    return false;
  bool dupl = false;
  // finally compare the end points
  if (this_point1 == given_point1 && this_point2 == given_point2)
    {
      dupl = true;
      this->same_orientation_as_base_entity = true;
    }
  else if (this_point2 == given_point1 && this_point1 == given_point2)
    {
      dupl = true;
      this->same_orientation_as_base_entity = false;
    }
  if (dupl == true)
    {
      this->is_duplicate = true;
      this->base_entity_ID = arc.baseEntityID();
      return true;
    }
  else
    return false;
}
void GeometricEllipticArc::readFromInput (std::istream & input) [protected, virtual]
method to read from input
Implements GeometricLine.
Definition at line 113 of file GeometricEllipticArc.C.
References GeometricEntity::geometric_model, GeometricModel::getPointForID(), points, and GeometricEntity::unique_ID.
{
  input >> this->unique_ID;
  unsigned int point_num = 0;
  GeometricPoint* point = NULL;
  for (unsigned int i=0; i<4; i++)
    {
      input >> point_num;
      point = &(this->geometric_model.getPointForID(point_num));
      this->points.push_back(point);
    }
}
GeometricEntity::GeometricEntityType GeometricEllipticArc::type () const [inline, virtual]
returns the type of this entity
Implements GeometricLine.
Definition at line 46 of file GeometricEllipticArc.h.
References GeometricEntity::ELLIPTIC_ARC.
{
  return GeometricEntity::ELLIPTIC_ARC;
}
void GeometricEllipticArc::writeToOutput (std::ostream & output) [protected, virtual]
method to write to output
Implements GeometricLine.
Definition at line 131 of file GeometricEllipticArc.C.
References points, and GeometricEntity::unique_ID.
{
  output << this->unique_ID << "   ";
  output << this->points[0]->ID() << "   ";
  output << this->points[1]->ID() << "   ";
  output << this->points[2]->ID() << "   ";
  output << this->points[3]->ID() << std::endl;
}
Member Data Documentation
std::vector<GeometricPoint*> GeometricEllipticArc::points [protected]
location of this point
Reimplemented from GeometricLine.
Definition at line 42 of file GeometricEllipticArc.h.
Referenced by checkIfDuplicate(), readFromInput(), and writeToOutput().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricEllipticArc.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricEllipticArc.C