fesystem: Property::PropertyCardBase Class Reference
Property::PropertyCardBase Class Reference
#include <PropertyCardBase.h>
Public Member Functions
PropertyCardBase ()
default constructor
virtual ~PropertyCardBase ()
destructor
unsigned int getID () const
virtual unsigned int getNProperties () const =0
unsigned int getNParameters () const
unsigned int getNLocalParameters () const
unsigned int getNGlobalParameters () const
virtual unsigned int getPropertyCardKindEnumID () const =0
virtual const std::string getPropertyCardKindEnumName () const =0
bool checkLocalParameterDependence (const unsigned int enumID) const
bool checkGlobalParameterDependence (const unsigned int param_global_ID) const
void attachFunctionDatabase (FunctionDatabase &func_database)
attaches the function database to this card
void reinitLocalParameters (const std::map< unsigned int, double > *value_map=NULL)
void reinitGlobalParameters (const std::map< unsigned int, double > &value_map)
void clearLocalParameterInitialization ()
void partialClearLocalParameterInitialization (std::vector< unsigned int > &params_to_clear)
void clearGlobalParameterInitialization ()
Protected Types
typedef std::map< unsigned int,
Property::ParameterBase * > ParameterMap
this is a local type definition for a more readable code
typedef std::map< unsigned int,
Property::LocalParameter * > LocalParameterMap
typedef std::map< unsigned int,
Property::GlobalParameter * > GlobalParameterMap
typedef std::map< unsigned int,
unsigned int > IDMap
Protected Member Functions
unsigned int getParameterInternalID (const unsigned int exernal_ID) const
unsigned int getGlobalParameterInternalIDForGlobalID (const unsigned int external_ID) const
unsigned int getLocalParameterInternalIDForEnumID (const unsigned int enum_ID) const
unsigned int getPropertyInternalID (const unsigned int enum_ID) const
void reinitParameterFunctionValues (const std::vector< unsigned int > &param_ids)
void addLocalParameter (LocalParameter *param)
adds a global parameter to the card
void addGlobalParameter (GlobalParameter *param)
adds a local parameter to the card
std::istream & readParametersFromInputStream (std::istream &input)
reads parameters from the input
DeclException1 (ExcPropertyDoesNotExist, std::string,<< "Requested Property: "<< arg1<< " does not exist in Card.")
an internal error to define non existence of property
DeclException1 (ExcDuplicatePropertySpecified, std::string,<< "Specified Property: "<< arg1<< " already exists in Card.")
an internal error to define non existence of property
DeclException1 (ExcParameterDoesNotExist, std::string,<< "Specified Parameter: "<< arg1<< " does not exist in Card.")
DeclException1 (ExcDuplicateParameterSpecified, unsigned int,<< "Specified Parameter ID: "<< arg1<< " already exist in Card.")
DeclException1 (ExcParameterIDDoesNotExist, unsigned int,<< "Specified Parameter ID: "<< arg1<< " does not exist in Card.")
DeclException1 (ExcGlobalParameterNotSpecified, unsigned int,<< "Global Parameter: "<< arg1<< " not specified in input.")
an internal error if the global parameter is not specified in the input
Protected Attributes
unsigned int cardID
property card ID
bool local_params_initialized
if the local params are initialized or not
bool global_params_initialized
if the global params are initialized or not
FunctionDatabase * function_database
Table< 2, unsigned int > * parameter_function_ID_table
Table< 3, double > * parameter_function_value_table
a table to store the function values and sensitivity for the parameters and property
ParameterMap parameter_map
LocalParameterMap local_parameter_map
GlobalParameterMap global_parameter_map
IDMap parameter_external_to_internal_ID_map
external to internal ID map for the parameters
IDMap property_enumID_to_internal_ID_map
enumID to internal ID map for the properties
std::set< unsigned int > default_local_params
set of local param IDs that have been set to their default values
Detailed Description
The PropertyCard class that provides the necessary data structure for storage of properties in general. This is a base class, and different material/structural property cards can derive from this. Each property card can have dependence on some parameter values, which is defined through the input. If a parameter dependence has been defined, then before the parameter values can be accessed, the card needs to be initialized at some parameter values. During reinitialization, if no value has been specified for a parameter, a default value for the same is assumed. Between any two consecutive initializations, the card needs to be cleared of any previous initialization. This is needed to make sure that the card is cleared of any remnant value initializations to avoid errors. Once initialized, the value of the property can be accessed from the card.
Definition at line 41 of file PropertyCardBase.h.
Member Typedef Documentation
typedef std::map<unsigned int, Property::GlobalParameter*> Property::PropertyCardBase::GlobalParameterMap [protected]
Definition at line 210 of file PropertyCardBase.h.
typedef std::map<unsigned int, unsigned int> Property::PropertyCardBase::IDMap [protected]
Definition at line 211 of file PropertyCardBase.h.
typedef std::map<unsigned int, Property::LocalParameter*> Property::PropertyCardBase::LocalParameterMap [protected]
Definition at line 209 of file PropertyCardBase.h.
typedef std::map<unsigned int, Property::ParameterBase*> Property::PropertyCardBase::ParameterMap [protected]
this is a local type definition for a more readable code
Definition at line 208 of file PropertyCardBase.h.
Constructor & Destructor Documentation
Property::PropertyCardBase::PropertyCardBase ()
default constructor
Definition at line 9 of file PropertyCardBase.C.
References parameter_function_ID_table, and parameter_function_value_table.
                                          :
cardID(FESystemNumbers::InvalidID),
local_params_initialized(false),
global_params_initialized(false),
function_database(NULL),
parameter_function_ID_table(NULL)
{
  this->parameter_function_ID_table = new Table<2,unsigned int>;
  this->parameter_function_value_table = new Table<3, double>;
}
Property::PropertyCardBase::~PropertyCardBase () [virtual]
destructor
Definition at line 24 of file PropertyCardBase.C.
{
  // delete the function ID table
  delete this->parameter_function_ID_table;
  this->parameter_function_ID_table = NULL;
  delete this->parameter_function_value_table;
  this->parameter_function_value_table = NULL;
}
Member Function Documentation
void Property::PropertyCardBase::addGlobalParameter (Property::GlobalParameter * param) [protected]
adds a local parameter to the card
Definition at line 77 of file PropertyCardBase.C.
References Property::GlobalParameter::getGlobalParameterID(), and Property::ParameterBase::getID().
{
  Assert(param != NULL,
         ExcEmptyObject());
  unsigned int param_ID = param->getID(),
    global_ID = param->getGlobalParameterID(),
    local_ID = this->parameter_map.size();
  bool insert_success = false;
  // now insert the param in the param_map and the local_parameter map
  insert_success = this->parameter_map.insert
    (Property::PropertyCardBase::ParameterMap::value_type(local_ID, param)).second;
  // an error thrown if the insert failed, which should never happen, since the ID is
  // always chosen to be unique
  Assert(insert_success, ExcInternalError());
  // now add this to the local parameter map
  insert_success = this->global_parameter_map.insert
    (Property::PropertyCardBase::GlobalParameterMap::value_type(global_ID, param)).second;
  // if this is true, then the local parameter has been specified a 2nd time.
  Assert(insert_success,
         Property::PropertyCardBase::ExcDuplicateParameterSpecified(global_ID));
  // once this is done, insert the ID entries in the ID map.
  insert_success = this->parameter_external_to_internal_ID_map.insert
    (Property::PropertyCardBase::IDMap::value_type(param_ID, local_ID)).second;
  Assert(insert_success,
         Property::PropertyCardBase::ExcDuplicateParameterSpecified(param_ID));
}
void Property::PropertyCardBase::addLocalParameter (Property::LocalParameter * param) [protected]
adds a global parameter to the card
Definition at line 38 of file PropertyCardBase.C.
References Property::ParameterBase::getID(), and Property::LocalParameter::getLocalParameterEnumID().
{
  Assert(param != NULL,
         ExcEmptyObject());
  unsigned int param_ID = param->getID(),
    enum_ID = param->getLocalParameterEnumID(),
    local_ID = this->parameter_map.size();
  bool insert_success = false;
  // now insert the param in the param_map and the local_parameter map
  insert_success = this->parameter_map.insert
    (Property::PropertyCardBase::ParameterMap::value_type(local_ID, param)).second;
  // an error thrown if the insert failed, which should never happen, since the ID is
  // always chosen to be unique
  Assert(insert_success, ExcInternalError());
  // now add this to the local parameter map
  insert_success = this->local_parameter_map.insert
    (Property::PropertyCardBase::LocalParameterMap::value_type(enum_ID, param)).second;
  // if this is true, then the local parameter has been specified a 2nd time.
  Assert(insert_success,
         Property::PropertyCardBase::ExcDuplicateParameterSpecified(enum_ID));
  // once this is done, insert the ID entries in the ID map.
  insert_success = this->parameter_external_to_internal_ID_map.insert
    (Property::PropertyCardBase::IDMap::value_type(param_ID, local_ID)).second;
  Assert(insert_success,
         Property::PropertyCardBase::ExcDuplicateParameterSpecified(param_ID));
}
void Property::PropertyCardBase::attachFunctionDatabase (FunctionDatabase & func_database) [inline]
attaches the function database to this card
Definition at line 287 of file PropertyCardBase.h.
Referenced by Property::PropertyDatabase::readAndStoreElemDataCard(), and Property::PropertyDatabase::readAndStoreMaterialCard().
{
  this->function_database = &func_database;
}
bool Property::PropertyCardBase::checkGlobalParameterDependence (const unsigned int param_global_ID) const [inline]
Returns:
true if the card depends on the parameter
Definition at line 668 of file PropertyCardBase.h.
{
  // to check for dependence on the specified global param, look in the map
  if (this->global_parameter_map.count(param_global_ID) ==0)
    return false;
  else
    return true;
}
bool Property::PropertyCardBase::checkLocalParameterDependence (const unsigned int enumID) const [inline]
Returns:
true if the card depends on the parameter
Definition at line 656 of file PropertyCardBase.h.
{
  // to check for dependence on the specified local param, look in the map
  if (this->local_parameter_map.count(enumID) ==0)
    return false;
  else
    return true;
}
void Property::PropertyCardBase::clearGlobalParameterInitialization () [inline]
this method clears any previous initialization. This needs to be called before any reinitialization. Before re-intialization of any parameter, its value should be cleared using this function. If no input is provided, then all the values are cleared. Otherwise, only the values listed in this vector are cleared.
Definition at line 545 of file PropertyCardBase.h.
Referenced by IsotropicElemDataCard::clearElemAndMaterialCardGlobalParameterInitialization(), and ForcedConvection_1D_ElemDataCard::clearElemAndMaterialCardGlobalParameterInitialization().
{
  this->global_params_initialized = false;
}
void Property::PropertyCardBase::clearLocalParameterInitialization () [inline]
this method clears any previous initialization. This needs to be called before any reinitialization. Before re-intialization of any parameter, its value should be cleared using this function.
Definition at line 534 of file PropertyCardBase.h.
Referenced by IsotropicElemDataCard::clearElemAndMaterialCardLocalParameterInitialization(), and ForcedConvection_1D_ElemDataCard::clearElemAndMaterialCardLocalParameterInitialization().
{
  this->local_params_initialized = false;
}
Property::PropertyCardBase::DeclException1 (ExcPropertyDoesNotExist , std::string , << "Requested Property: "<< arg1<< " does not exist in Card.") [protected]
an internal error to define non existence of property
Property::PropertyCardBase::DeclException1 (ExcDuplicatePropertySpecified , std::string , << "Specified Property: "<< arg1<< " already exists in Card.") [protected]
an internal error to define non existence of property
Property::PropertyCardBase::DeclException1 (ExcParameterDoesNotExist , std::string , << "Specified Parameter: "<< arg1<< " does not exist in Card.") [protected]
an internal error if the specified parameter does not exist in the card
Property::PropertyCardBase::DeclException1 (ExcDuplicateParameterSpecified , unsigned int, << "Specified Parameter ID: "<< arg1<< " already exist in Card.") [protected]
an internal error if the specified parameter does not exist in the card
Property::PropertyCardBase::DeclException1 (ExcParameterIDDoesNotExist , unsigned int, << "Specified Parameter ID: "<< arg1<< " does not exist in Card.") [protected]
an internal error if the specified parameter does not exist in the card
Property::PropertyCardBase::DeclException1 (ExcGlobalParameterNotSpecified , unsigned int, << "Global Parameter: "<< arg1<< " not specified in input.") [protected]
an internal error if the global parameter is not specified in the input
unsigned int Property::PropertyCardBase::getGlobalParameterInternalIDForGlobalID (const unsigned int external_ID) const [inline, protected]
Returns:
parameter internal ID for a global parameter. The ID specified in the input is the global ID of the parameter in the design database.
Definition at line 582 of file PropertyCardBase.h.
References FESystemNumbers::InvalidID.
{
  // make sure that this given ID is valid
  Assert(global_ID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(global_ID));
  // now get the iterators to the ID, and make sure that the ID exists in the card
  Property::PropertyCardBase::GlobalParameterMap::const_iterator it, end;
  it = this->global_parameter_map.find(global_ID);
  end = this->global_parameter_map.end();
  Assert(it != end,
         Property::PropertyCardBase::ExcParameterIDDoesNotExist(global_ID));
  unsigned int external_ID = it->second->getID();
  return this->getParameterInternalID(external_ID);
}
unsigned int Property::PropertyCardBase::getID () const [inline]
Returns:
the id of the card
Definition at line 248 of file PropertyCardBase.h.
References cardID, and FESystemNumbers::InvalidID.
Referenced by Property::PropertyCard< double >::getPropertyDerivativeForGlobalParameter(), Property::PropertyCard< double >::getPropertyDerivativeForLocalParameter(), Property::PropertyDatabase::readAndStoreElemDataCard(), and Property::PropertyDatabase::readAndStoreMaterialCard().
{
  Assert(this->cardID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(this->cardID));
  return this->cardID;
}
unsigned int Property::PropertyCardBase::getLocalParameterInternalIDForEnumID (const unsigned int enum_ID) const [inline, protected]
Returns:
parameter internal ID for a local parameter. The ID specified in the input is the enum ID of the parameter
Definition at line 610 of file PropertyCardBase.h.
References FESystemNumbers::InvalidID.
{
  // make sure that this given ID is valid
  Assert(enum_ID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(enum_ID));
  // now get the iterators to the ID, and make sure that the ID exists in the card
  Property::PropertyCardBase::LocalParameterMap::const_iterator it, end;
  it = this->local_parameter_map.find(enum_ID);
  end = this->local_parameter_map.end();
  Assert(it != end,
         Property::PropertyCardBase::ExcParameterIDDoesNotExist(enum_ID));
  unsigned int external_ID = it->second->getID();
  return this->getParameterInternalID(external_ID);
}
unsigned int Property::PropertyCardBase::getNGlobalParameters () const [inline]
Definition at line 277 of file PropertyCardBase.h.
{
  return this->global_parameter_map.size();
}
unsigned int Property::PropertyCardBase::getNLocalParameters () const [inline]
Definition at line 268 of file PropertyCardBase.h.
{
  return this->local_parameter_map.size();
}
unsigned int Property::PropertyCardBase::getNParameters () const [inline]
Definition at line 260 of file PropertyCardBase.h.
Referenced by IsotropicElemDataCard::readFromInputStream(), and ForcedConvection_1D_ElemDataCard::readFromInputStream().
{
  return this->parameter_map.size();
}
virtual unsigned int Property::PropertyCardBase::getNProperties () const [pure virtual]
Implemented in Property::PropertyCard< double >.
unsigned int Property::PropertyCardBase::getParameterInternalID (const unsigned int exernal_ID) const [inline, protected]
Returns:
parameter internal ID for the external ID specifies in the input. This external ID is the ID of the parameter as specified in the input for the property card
Definition at line 558 of file PropertyCardBase.h.
References FESystemNumbers::InvalidID.
Referenced by IsotropicElemDataCard::readFromInputStream(), and ForcedConvection_1D_ElemDataCard::readFromInputStream().
{
  // make sure that this given ID is valid
  Assert(external_ID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(external_ID));
  // now get the iterators to the ID, and make sure that the ID exists in the card
  Property::PropertyCardBase::IDMap::const_iterator it, end;
  it = this->parameter_external_to_internal_ID_map.find(external_ID);
  end = this->parameter_external_to_internal_ID_map.end();
  Assert(it != end,
         Property::PropertyCardBase::ExcParameterIDDoesNotExist(external_ID));
  return it->second;
}
virtual unsigned int Property::PropertyCardBase::getPropertyCardKindEnumID () const [pure virtual]
Returns:
the property card kind enumeration ID
Implemented in Isotropic1D_ElemDataCard, ForcedConvection_1D_ElemDataCard, Isotropic2D_ElemDataCard, Isotropic3D_ElemDataCard, OrthotropicMaterialPropertyCard< dim >, and IsotropicMaterialPropertyCard.
virtual const std::string Property::PropertyCardBase::getPropertyCardKindEnumName () const [pure virtual]
Returns:
the property card kind enumeration name
Implemented in Isotropic1D_ElemDataCard, ForcedConvection_1D_ElemDataCard, Isotropic2D_ElemDataCard, Isotropic3D_ElemDataCard, OrthotropicMaterialPropertyCard< dim >, and IsotropicMaterialPropertyCard.
Referenced by IsotropicElemDataCard::readFromInputStream().
unsigned int Property::PropertyCardBase::getPropertyInternalID (const unsigned int enum_ID) const [inline, protected]
Returns:
property internal ID for the external ID specifies in the input
Definition at line 637 of file PropertyCardBase.h.
References FESystemNumbers::InvalidID.
Referenced by IsotropicElemDataCard::readFromInputStream(), and ForcedConvection_1D_ElemDataCard::readFromInputStream().
{
  // make sure that this given ID is valid
  Assert(external_ID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(external_ID));
  // now get the iterators to the ID, and make sure that the ID exists in the card
  Property::PropertyCardBase::IDMap::const_iterator it, end;
  it = this->property_enumID_to_internal_ID_map.find(external_ID);
  end = this->property_enumID_to_internal_ID_map.end();
  Assert(it != end,
         Property::PropertyCardBase::ExcParameterIDDoesNotExist(external_ID));
  return it->second;
}
void Property::PropertyCardBase::partialClearLocalParameterInitialization (std::vector< unsigned int > & params_to_clear) [inline]
this method clears the function value initialization for local params specified in the input. No other params are cleared.
Definition at line 516 of file PropertyCardBase.h.
Referenced by IsotropicElemDataCard::partialClearElemAndMaterialCardLocalParameterInitialization(), and ForcedConvection_1D_ElemDataCard::partialClearElemAndMaterialCardLocalParameterInitialization().
{
  // iterate over all the params specified and clear their initialization
  std::vector<unsigned int>::const_iterator it, end;
  it = params_to_clear.begin();
  end = params_to_clear.end();
  for (; it != end; it++)
    this->default_local_params.erase(*it);
  this->local_params_initialized = false;
}
std::istream & Property::PropertyCardBase::readParametersFromInputStream (std::istream & input) [protected]
reads parameters from the input
Definition at line 118 of file PropertyCardBase.C.
References FESystemIOUtility::readFromInput().
Referenced by IsotropicElemDataCard::readFromInputStream(), and ForcedConvection_1D_ElemDataCard::readFromInputStream().
{
  // read the local parameters
  {
    unsigned int n_params = 0;
    FESystemIOUtility::readFromInput(input, "N_LOCAL_PARAMETERS", n_params);
    for (unsigned int i=0; i<n_params; i++)
      {
      Property::LocalParameter *param = new Property::LocalParameter;
      input >> (*param);
      // insert the parameter in the map
      this->addLocalParameter(param);
      }
  }
  // now read the global parameters
  {
    unsigned int n_params = 0;
    FESystemIOUtility::readFromInput(input, "N_GLOBAL_PARAMETERS", n_params);
    for (unsigned int i=0; i<n_params; i++)
      {
      Property::GlobalParameter *param = new Property::GlobalParameter;
      input >> (*param);
      // insert the parameter in the map
      this->addGlobalParameter(param);
      }
  }
  return input;
}
void Property::PropertyCardBase::reinitGlobalParameters (const std::map< unsigned int, double > & value_map) [inline]
this method initializes the property card at the values specified for each parameter. This method will update all values from the input values in the parameter
Definition at line 415 of file PropertyCardBase.h.
Referenced by ForcedConvection_1D_ElemDataCard::reinitElemAndMaterialCardForGlobalParameters().
{
  // before calling this function, the user should have cleared previous initializations
  Assert(this->global_params_initialized == false,
         ExcInvalidState());
  // iterate over all the params in this card and set the current values of the params
  // that are specified in the map
  PropertyCardBase::GlobalParameterMap::iterator
    param_it, param_end;
  param_it = this->global_parameter_map.begin();
  param_end = this->global_parameter_map.end();
  double value = 0.0;
  unsigned int param_id = 0;
  std::map<unsigned int, double>::const_iterator input_param_it, input_param_end;
  input_param_end = value_map.end();
  for (; param_it != param_end; param_it++)
    {
    param_id = param_it->first;
    input_param_it = value_map.find(param_id);
    Assert(input_param_it != input_param_end,
           ExcGlobalParameterNotSpecified(param_id));
    value = input_param_it->second;
    param_it->second->setCurrentValue(value);
    }
  // once the values have been set, the functions need to be initialized
  // call the function function value initialization for the parameter IDs
  // that have just been initialized
  static std::vector<unsigned int>
    reinitialized_param_ids(this->global_parameter_map.size());
  param_it = this->global_parameter_map.begin();
  unsigned int n_param = 0;
  for (; param_it != param_end; param_it++)
    {
    reinitialized_param_ids[n_param] = param_it->second->getID();
    n_param++;
    }
  this->reinitParameterFunctionValues(reinitialized_param_ids);
  // finally, set the tag for initialization of the local params
  this->global_params_initialized = true;
}
void Property::PropertyCardBase::reinitLocalParameters (const std::map< unsigned int, double > * value_map = NULL) [inline]
this method initializes the property card at the values specified for each parameter. The input to this method is a map of the parameter and its value. For parameters whose values have not been specified in the input map, default values are used.
Definition at line 298 of file PropertyCardBase.h.
Referenced by ForcedConvection_1D_ElemDataCard::reinitElemAndMaterialCardForLocalParameters().
{
  // before calling this function, the user should have cleared previous initializations
  Assert(this->local_params_initialized == false,
         ExcInvalidState());
  static std::vector<unsigned int> reinitialized_param_ids;
  reinitialized_param_ids.clear();
  // set the values of the parameters, and calculate and store the function values
  // and their derivatives.
  // a list of all function values that are set to their default values will have be
  // stored so that there is no need to initialize them or clear them when a partial
  // clear is performed
  Property::PropertyCardBase::LocalParameterMap::iterator
  param_it, param_end;
  param_it = this->local_parameter_map.begin();
  param_end = this->local_parameter_map.end();
  double value = 0.0;
  bool insert_success = false;
  // if the map is null, then all params will have their default values
  if (value_map == NULL)
    {
    for (; param_it != param_end; param_it++)
      {
      // if the local parameter has not already been initialized to its local value,
      // initialize it
      if (this->default_local_params.count(param_it->second->getID()) == 0)
        {
        value = param_it->second->getReferenceValue();
        param_it->second->setCurrentValue(value);
        // also add this param to the set of params that have been set to their default
        // values.
        insert_success = this->default_local_params.insert(param_it->second->getID()).second;
        Assert(insert_success, FESystemExceptions::ExcDuplicateID("Local Parameter",
                                                                  param_it->second->getID()));
        reinitialized_param_ids.push_back(param_it->second->getID());
        }
      }
    }
  else
    {
    // now set the values of the parameters by syncing the parameters that have been
    // specified in the input
    unsigned int param_count_in_local_default_param_map = 0,
    param_enum_id = 0;
    std::map<unsigned int, double>::const_iterator input_param_it, input_param_end;
    input_param_end = value_map->end();
    for (; param_it != param_end; param_it++)
      {
      param_enum_id = param_it->first;
      input_param_it = value_map->find(param_enum_id);
      // check if this has been set to its default value
      param_count_in_local_default_param_map =
        this->default_local_params.count(param_it->second->getID());
      if (input_param_it == input_param_end)
        {
        // if this param has not already been initialized to its default value,
        // then do the same, and add this ID to the set.
        // otherwise, if it has already been initialized to its local value, then
        // no need to do anything
        if (param_count_in_local_default_param_map == 0)
          {
          value = param_it->second->getReferenceValue();
          // also add this param to the set of params that have been set to their default
          // values.
          insert_success = this->default_local_params.insert(param_it->second->getID()).second;
          Assert(insert_success, FESystemExceptions::ExcDuplicateID("Local Parameter",
                                                                    param_it->second->getID()));
          }
        else
          continue;
        }
      else
        {
        // we need to set the value of this param to the one specified in the input.
        // for this, we need to check if the param has been previously set to its
        // default value. If it has been, then its ID needs to be cleared from the
        // local default param set
        if (param_count_in_local_default_param_map != 0)
          this->default_local_params.erase(param_it->second->getID());
        value = input_param_it->second;
        }
      param_it->second->setCurrentValue(value);
      reinitialized_param_ids.push_back(param_it->second->getID());
      }
    }
  // once the values have been set, the functions need to be initialized
  // call the function value initialization for the parameter IDs
  // that have just been initialized
  this->reinitParameterFunctionValues(reinitialized_param_ids);
  // finally, set the tag for initialization of the local params
  this->local_params_initialized = true;
}
void Property::PropertyCardBase::reinitParameterFunctionValues (const std::vector< unsigned int > & param_ids) [inline, protected]
reinitializes the function values and the function derivatives for the parameter IDs specified in the input
Definition at line 472 of file PropertyCardBase.h.
References FESystemNumbers::InvalidID.
{
  Assert(this->function_database != NULL,
         ExcInvalidState());
  std::vector<unsigned int>::const_iterator param_it, param_end;
  param_it = param_ids.begin();
  param_end = param_ids.end();
  unsigned int func_id = 0, param_internal_id = 0, prop_it=0;
  const unsigned int  n_prop = this->getNProperties();
  double param_value = 0.0, func_value = 0.0, func_derivative = 0.0;
  for ( ; param_it != param_end; param_it++)
    {
    param_internal_id = this->getParameterInternalID(*param_it);
    param_value = this->parameter_map[param_internal_id]->getCurrentValue();
    for (prop_it=0; prop_it < n_prop; prop_it++)
      {
      // get the function ID and then the function values and its derivative wrt the
      // parameter
      func_id = (*this->parameter_function_ID_table)(prop_it, param_internal_id);
      if (func_id == FESystemNumbers::InvalidID)
        continue;
      this->function_database->getScalarFunctionValue(func_id, param_value, func_value);
      this->function_database->getScalarFunctionDerivative(func_id, param_value, func_derivative);
      // not enter the function values in the table
      (*this->parameter_function_value_table)(prop_it, param_internal_id, 0) = func_value;
      (*this->parameter_function_value_table)(prop_it, param_internal_id, 1) = func_derivative;
      }
    }
}
Member Data Documentation
unsigned int Property::PropertyCardBase::cardID [protected]
property card ID
Definition at line 148 of file PropertyCardBase.h.
Referenced by getID(), IsotropicElemDataCard::readFromInputStream(), and ForcedConvection_1D_ElemDataCard::readFromInputStream().
std::set<unsigned int> Property::PropertyCardBase::default_local_params [protected]
set of local param IDs that have been set to their default values
Definition at line 233 of file PropertyCardBase.h.
FunctionDatabase* Property::PropertyCardBase::function_database [protected]
a pointer to the function database that stores the functions defining the property-parameter relations
Definition at line 158 of file PropertyCardBase.h.
GlobalParameterMap Property::PropertyCardBase::global_parameter_map [protected]
map for storing the pointers to local parameters. These pointers, are stored for convenience. This map uses the global ID of the parameter as key
Definition at line 224 of file PropertyCardBase.h.
bool Property::PropertyCardBase::global_params_initialized [protected]
if the global params are initialized or not
Definition at line 154 of file PropertyCardBase.h.
LocalParameterMap Property::PropertyCardBase::local_parameter_map [protected]
map for storing the pointers to local parameters. These pointers, are stored for convenience. This map uses the parameter enum ID as key
Definition at line 220 of file PropertyCardBase.h.
bool Property::PropertyCardBase::local_params_initialized [protected]
if the local params are initialized or not
Definition at line 151 of file PropertyCardBase.h.
IDMap Property::PropertyCardBase::parameter_external_to_internal_ID_map [protected]
external to internal ID map for the parameters
Definition at line 227 of file PropertyCardBase.h.
Table<2, unsigned int>* Property::PropertyCardBase::parameter_function_ID_table [protected]
a table to store the IDs of the functions for definition of parameter dependence of each property. After data has been read into this card, if a paricular entry is still equal to the invalidID, then that implies that the property is not dependent on that parameter. Else, it is dependent, and the entry specifies the function defining the dependence
Definition at line 165 of file PropertyCardBase.h.
Referenced by PropertyCardBase(), IsotropicElemDataCard::readFromInputStream(), and ForcedConvection_1D_ElemDataCard::readFromInputStream().
Table<3, double>* Property::PropertyCardBase::parameter_function_value_table [protected]
a table to store the function values and sensitivity for the parameters and property
Definition at line 168 of file PropertyCardBase.h.
Referenced by PropertyCardBase(), IsotropicElemDataCard::readFromInputStream(), and ForcedConvection_1D_ElemDataCard::readFromInputStream().
ParameterMap Property::PropertyCardBase::parameter_map [protected]
The map for storing the pointers to parameters. The key used is the internal ID of the parameter. The internal IDs start from 0.
Definition at line 216 of file PropertyCardBase.h.
IDMap Property::PropertyCardBase::property_enumID_to_internal_ID_map [protected]
enumID to internal ID map for the properties
Definition at line 230 of file PropertyCardBase.h.
Referenced by IsotropicElemDataCard::readFromInputStream(), and ForcedConvection_1D_ElemDataCard::readFromInputStream().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/PropertyCardBase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/PropertyCardBase.C