fesystem: ElementDataStorage Class Reference
ElementDataStorage Class Reference
#include <ElementDataStorage.h>
Public Member Functions
ElementDataStorage ()
~ElementDataStorage ()
void clear ()
void add_element_data (const DenseMatrix< double > &, const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string &tag, const unsigned int case_ID=0)
void add_element_data (const DenseVector< double > &, const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string &tag, const unsigned int case_ID=0)
bool checkIfQtyExists (const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string &tag, const unsigned int case_ID=0)
checks if the specified quantitiy exists in the database or not
void get_element_data (DenseMatrix< double > &qty, const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string &tag, const unsigned int case_ID=0)
void get_element_data (DenseVector< double > &qty, const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string &tag, const unsigned int case_ID=0)
Private Types
typedef std::map< unsigned int,
DenseMatrix< double > * > LoadCaseIDToMatrixMap
typedef std::map< unsigned int,
DenseVector< double > * > LoadCaseIDToVectorMap
typedef std::map< const
std::string,
LoadCaseIDToMatrixMap > TagToMatrixMap
typedef std::map< const
std::string,
LoadCaseIDToVectorMap > TagToVectorMap
typedef std::map< unsigned int,
TagToMatrixMap > ElemIDToTagMatrixMap
typedef std::map< unsigned int,
TagToVectorMap > ElemIDToTagVectorMap
typedef std::map< unsigned int,
ElemIDToTagMatrixMap > DisciplineToElemIDMatrixMap
typedef std::map< unsigned int,
ElemIDToTagVectorMap > DisciplineToElemIDVectorMap
Private Member Functions
bool checkIfMatrixQtyExists (const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string &tag, const unsigned int case_ID=0)
checks if the specified quantitiy exists in the database or not
bool checkIfVectorQtyExists (const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string &tag, const unsigned int case_ID=0)
checks if the specified quantitiy exists in the database or not
Private Attributes
DisciplineToElemIDMatrixMap matrix_data
DisciplineToElemIDVectorMap vector_data
Detailed Description
this class will store all the calculated element quantities for use in the assembly and sensitivity analysis process
Definition at line 25 of file ElementDataStorage.h.
Member Typedef Documentation
typedef std::map<unsigned int, ElemIDToTagMatrixMap> ElementDataStorage::DisciplineToElemIDMatrixMap [private]
Definition at line 122 of file ElementDataStorage.h.
typedef std::map<unsigned int, ElemIDToTagVectorMap> ElementDataStorage::DisciplineToElemIDVectorMap [private]
Definition at line 123 of file ElementDataStorage.h.
typedef std::map<unsigned int, TagToMatrixMap> ElementDataStorage::ElemIDToTagMatrixMap [private]
Definition at line 120 of file ElementDataStorage.h.
typedef std::map<unsigned int, TagToVectorMap> ElementDataStorage::ElemIDToTagVectorMap [private]
Definition at line 121 of file ElementDataStorage.h.
typedef std::map<unsigned int, DenseMatrix<double>* > ElementDataStorage::LoadCaseIDToMatrixMap [private]
Definition at line 116 of file ElementDataStorage.h.
typedef std::map<unsigned int, DenseVector<double>* > ElementDataStorage::LoadCaseIDToVectorMap [private]
Definition at line 117 of file ElementDataStorage.h.
typedef std::map<const std::string , LoadCaseIDToMatrixMap> ElementDataStorage::TagToMatrixMap [private]
Definition at line 118 of file ElementDataStorage.h.
typedef std::map<const std::string , LoadCaseIDToVectorMap> ElementDataStorage::TagToVectorMap [private]
Definition at line 119 of file ElementDataStorage.h.
Constructor & Destructor Documentation
ElementDataStorage::ElementDataStorage ()
Definition at line 14 of file ElementDataStorage.C.
{
}
ElementDataStorage::~ElementDataStorage ()
Definition at line 21 of file ElementDataStorage.C.
References clear().
{
  this->clear();
}
Member Function Documentation
void ElementDataStorage::add_element_data (const DenseMatrix< double > & matrix, const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string & tag, const unsigned int case_ID = 0)
function to add the element data. This function has been overloaded to allow usage for both vector and matrix data. the DenseMatrix<double> and DenseVector<double> should be used as the data The data is stored for elem, tag, and load_case
Definition at line 116 of file ElementDataStorage.C.
References matrix_data.
{
//  // first, check if the element has been set to null. If it has been, abort
//  if (this->check_if_null(discipline_enum_ID, elem,quantity,load_case_ID) == true)
//    abort();
  // check if the discipline ID exists in the map. If not, create it.
  ElementDataStorage::DisciplineToElemIDMatrixMap::iterator discipline_tag_it =
  this->matrix_data.find(discipline_enum_ID);
  if (discipline_tag_it == this->matrix_data.end())
    {
    std::pair<ElementDataStorage::DisciplineToElemIDMatrixMap::iterator, bool>
    insert_return_value =
    this->matrix_data.insert(ElementDataStorage::DisciplineToElemIDMatrixMap::value_type
                             (discipline_enum_ID, ElementDataStorage::ElemIDToTagMatrixMap::map()));
    assert (insert_return_value.second == true);
    discipline_tag_it = insert_return_value.first;
    }
  // check if the elem ID exists, if not, creat it in the map
  ElementDataStorage::ElemIDToTagMatrixMap::iterator elem_tag_it =
    discipline_tag_it->second.find(elem);
  if (elem_tag_it == discipline_tag_it->second.end())
    {
    std::pair<ElementDataStorage::ElemIDToTagMatrixMap::iterator, bool> insert_return_value =
    discipline_tag_it->second.insert(ElementDataStorage::ElemIDToTagMatrixMap::value_type
                                     (elem, TagToMatrixMap::map()));
    assert (insert_return_value.second == true);
    elem_tag_it = insert_return_value.first;
    }
  // check if the tag exists, if not, create
  TagToMatrixMap::iterator tag_caseID_it = elem_tag_it->second.find(quantity);
  if (tag_caseID_it == elem_tag_it->second.end())
    {
    std::pair<TagToMatrixMap::iterator, bool> insert_return_value =
    elem_tag_it->second.insert(TagToMatrixMap::value_type (quantity, LoadCaseIDToMatrixMap::map()));
    assert (insert_return_value.second == true);
    tag_caseID_it = insert_return_value.first;
    }
  // check if the loadcase ID exists,
  // if it does, delete the matrix entry, and create a new one, if not, add it
  LoadCaseIDToMatrixMap::iterator caseID_matrix_it = tag_caseID_it->second.find(load_case_ID);
  if (caseID_matrix_it != tag_caseID_it->second.end())
    {
    delete caseID_matrix_it->second;
    tag_caseID_it->second.erase(caseID_matrix_it);
    }
  DenseMatrix<double>* local_matrix = new DenseMatrix<double>(matrix);
  std::pair<LoadCaseIDToMatrixMap::iterator,bool> insert_return_value =
    tag_caseID_it->second.insert(LoadCaseIDToMatrixMap::value_type(load_case_ID, local_matrix));
  assert (insert_return_value.second == true);
}
void ElementDataStorage::add_element_data (const DenseVector< double > & vector, const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string & tag, const unsigned int case_ID = 0)
Definition at line 193 of file ElementDataStorage.C.
References vector_data.
{
//  // first, check if the element has been set to null. If it has been, abort
//  if (this->check_if_null(discipline_enum_ID, elem,quantity,load_case_ID) == true)
//    abort();
  // check if the discipline ID exists in the map. If not, create it.
  ElementDataStorage::DisciplineToElemIDVectorMap::iterator discipline_tag_it =
  this->vector_data.find(discipline_enum_ID);
  if (discipline_tag_it == this->vector_data.end())
    {
    std::pair<ElementDataStorage::DisciplineToElemIDVectorMap::iterator, bool>
    insert_return_value =
    this->vector_data.insert(ElementDataStorage::DisciplineToElemIDVectorMap::value_type
                             (discipline_enum_ID, ElementDataStorage::ElemIDToTagVectorMap::map()));
    assert (insert_return_value.second == true);
    discipline_tag_it = insert_return_value.first;
    }
  // check if the elem ID exists, if not, creat it in the map
  ElementDataStorage::ElemIDToTagVectorMap::iterator elem_tag_it =
    discipline_tag_it->second.find(elem);
  if (elem_tag_it == discipline_tag_it->second.end())
    {
    std::pair<ElementDataStorage::ElemIDToTagVectorMap::iterator, bool> insert_return_value =
    discipline_tag_it->second.insert(ElementDataStorage::ElemIDToTagVectorMap::value_type
                                     (elem, TagToVectorMap::map()));
    assert (insert_return_value.second == true);
    elem_tag_it = insert_return_value.first;
    }
  // check if the tag exists, if not, create
  TagToVectorMap::iterator tag_caseID_it = elem_tag_it->second.find(quantity);
  if (tag_caseID_it == elem_tag_it->second.end())
    {
    std::pair<TagToVectorMap::iterator, bool> insert_return_value =
    elem_tag_it->second.insert(TagToVectorMap::value_type (quantity, LoadCaseIDToVectorMap::map()));
    assert (insert_return_value.second == true);
    tag_caseID_it = insert_return_value.first;
    }
  // check if the loadcase ID exists,
  // if it does, delete the vector entry, and create a new one, if not, add it
  LoadCaseIDToVectorMap::iterator caseID_vector_it = tag_caseID_it->second.find(load_case_ID);
  if (caseID_vector_it != tag_caseID_it->second.end())
    {
    delete caseID_vector_it->second;
    tag_caseID_it->second.erase(caseID_vector_it);
    }
  DenseVector<double>* local_vector = new DenseVector<double>(vector);
  std::pair<LoadCaseIDToVectorMap::iterator,bool> insert_return_value =
    tag_caseID_it->second.insert(LoadCaseIDToVectorMap::value_type(load_case_ID, local_vector));
  assert (insert_return_value.second == true);
}
bool ElementDataStorage::checkIfMatrixQtyExists (const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string & tag, const unsigned int case_ID = 0) [private]
checks if the specified quantitiy exists in the database or not
Definition at line 286 of file ElementDataStorage.C.
References matrix_data.
Referenced by checkIfQtyExists().
{
//  // first, check if the element has been set to null. If it has been, abort
//  if (this->check_if_null(discipline_enum_ID, elem,quantity,load_case_ID))
//    return true;
  // check if the element exists in the map
  ElementDataStorage::DisciplineToElemIDMatrixMap::iterator discipline_tag_it =
  this->matrix_data.find(discipline_enum_ID);
  // if the element doesn't exist in the map, return false, else check further
  if (discipline_tag_it == this->matrix_data.end())
    return false;
  else
    {
    ElementDataStorage::ElemIDToTagMatrixMap::iterator elem_tag_it =
    discipline_tag_it->second.find(elem);
    if (elem_tag_it == discipline_tag_it->second.end())
      return false;
    else
      {
      // get the iterator to the load to matrix map
      ElementDataStorage::TagToMatrixMap::iterator tag_caseID_it =
      elem_tag_it->second.find(quantity);
      if (tag_caseID_it == elem_tag_it->second.end())
        return false;
      else
        {
        // get the iterator to the load case to qty map
        ElementDataStorage::LoadCaseIDToMatrixMap::iterator caseID_matrix_it =
        tag_caseID_it->second.find(load_case_ID);
        if (caseID_matrix_it == tag_caseID_it->second.end())
          return false;
        else
          return true;
        }
      }
    }
}
bool ElementDataStorage::checkIfQtyExists (const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string & tag, const unsigned int case_ID = 0)
checks if the specified quantitiy exists in the database or not
Definition at line 270 of file ElementDataStorage.C.
References checkIfMatrixQtyExists(), and checkIfVectorQtyExists().
{
    bool in_matrix_qtys = this->checkIfMatrixQtyExists(discipline_enum_ID, elem, quantity, load_case_ID);
    bool in_vector_qtys = this->checkIfVectorQtyExists(discipline_enum_ID, elem, quantity, load_case_ID);
    // it is assumed that the qty exists either in vector or in matrix map.
    return (in_matrix_qtys + in_vector_qtys);
}
bool ElementDataStorage::checkIfVectorQtyExists (const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string & tag, const unsigned int case_ID = 0) [private]
checks if the specified quantitiy exists in the database or not
Definition at line 334 of file ElementDataStorage.C.
References vector_data.
Referenced by checkIfQtyExists().
{
//  // first, check if the element has been set to null. If it has been, abort
//  if (this->check_if_null(discipline_enum_ID, elem,quantity,load_case_ID))
//    return true;
  // check if the element exists in the map
  ElementDataStorage::DisciplineToElemIDVectorMap::iterator discipline_tag_it =
  this->vector_data.find(discipline_enum_ID);
  // if the element doesn't exist in the map, return false, else check further
  if (discipline_tag_it == this->vector_data.end())
    return false;
  else
    {
    ElementDataStorage::ElemIDToTagVectorMap::iterator elem_tag_it =
    discipline_tag_it->second.find(elem);
    if (elem_tag_it == discipline_tag_it->second.end())
      return false;
    else
      {
      // get the iterator to the load to vector map
      ElementDataStorage::TagToVectorMap::iterator tag_caseID_it =
      elem_tag_it->second.find(quantity);
      if (tag_caseID_it == elem_tag_it->second.end())
        return false;
      else
        {
        // get the iterator to the load case to qty map
        ElementDataStorage::LoadCaseIDToVectorMap::iterator caseID_vector_it =
        tag_caseID_it->second.find(load_case_ID);
        if (caseID_vector_it == tag_caseID_it->second.end())
          return false;
        else
          return true;
        }
      }
    }
}
void ElementDataStorage::clear ()
function to clear the data stored
Definition at line 27 of file ElementDataStorage.C.
References matrix_data, and vector_data.
Referenced by ~ElementDataStorage().
{
  // first iterate over all the elements, then over the tags, and then over load case IDs
  {
    ElementDataStorage::DisciplineToElemIDMatrixMap::iterator
    discipline_tag_it, discipline_tag_end;
    discipline_tag_it = this->matrix_data.begin();
    discipline_tag_end = this->matrix_data.end();
    for (; discipline_tag_it != discipline_tag_end; discipline_tag_it++)
      {
      ElementDataStorage::ElemIDToTagMatrixMap::iterator  elem_tag_it, elem_tag_end;
      elem_tag_it = discipline_tag_it->second.begin();
      elem_tag_end = discipline_tag_it->second.end();
      for (; elem_tag_it != elem_tag_end; elem_tag_it++)
        {
        ElementDataStorage::TagToMatrixMap::iterator tag_caseID_it, tag_caseID_end;
        tag_caseID_it= elem_tag_it->second.begin();
        tag_caseID_end= elem_tag_it->second.end();
        for (; tag_caseID_it != tag_caseID_end; tag_caseID_it++)
          {
          ElementDataStorage::LoadCaseIDToMatrixMap::iterator  caseID_matrix_it, caseID_matrix_end;
          caseID_matrix_it= tag_caseID_it->second.begin();
          caseID_matrix_end= tag_caseID_it->second.end();
          for (; caseID_matrix_it != caseID_matrix_end; caseID_matrix_it++)
            {
            delete caseID_matrix_it->second;
            }
          tag_caseID_it->second.clear();
          }
        elem_tag_it->second.clear();
        }
      discipline_tag_it->second.clear();
      }
    this->matrix_data.clear();
  }
  // repeat the above procedure for vector data
  {
    ElementDataStorage::DisciplineToElemIDVectorMap::iterator
    discipline_tag_it, discipline_tag_end;
    discipline_tag_it = this->vector_data.begin();
    discipline_tag_end = this->vector_data.end();
    for (; discipline_tag_it != discipline_tag_end; discipline_tag_it++)
      {
      ElementDataStorage::ElemIDToTagVectorMap::iterator  elem_tag_it, elem_tag_end;
      elem_tag_it = discipline_tag_it->second.begin();
      elem_tag_end = discipline_tag_it->second.end();
      for (; elem_tag_it != elem_tag_end; elem_tag_it++)
        {
        ElementDataStorage::TagToVectorMap::iterator tag_caseID_it, tag_caseID_end;
        tag_caseID_it= elem_tag_it->second.begin();
        tag_caseID_end= elem_tag_it->second.end();
        for (; tag_caseID_it != tag_caseID_end; tag_caseID_it++)
          {
          ElementDataStorage::LoadCaseIDToVectorMap::iterator  caseID_vector_it, caseID_vector_end;
          caseID_vector_it= tag_caseID_it->second.begin();
          caseID_vector_end= tag_caseID_it->second.end();
          for (; caseID_vector_it != caseID_vector_end; caseID_vector_it++)
            {
            delete caseID_vector_it->second;
            }
          tag_caseID_it->second.clear();
          }
        elem_tag_it->second.clear();
        }
      discipline_tag_it->second.clear();
      }
    this->vector_data.clear();
  }
}
void ElementDataStorage::get_element_data (DenseMatrix< double > & qty, const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string & tag, const unsigned int case_ID = 0)
function to get the element quantity from the stored data
Definition at line 383 of file ElementDataStorage.C.
References matrix_data.
{
//  // first, check if the element has been set to null. If it has been, abort
//  if (this->check_if_null(discipline_enum_ID, elem,quantity,load_case_ID) == true)
//    abort();
  // check if the element exists in the map
  ElementDataStorage::DisciplineToElemIDMatrixMap::iterator discipline_tag_it =
  this->matrix_data.find(discipline_enum_ID);
  Assert(discipline_tag_it != this->matrix_data.end(), ExcInternalError());
  ElementDataStorage::ElemIDToTagMatrixMap::iterator elem_tag_it =
  discipline_tag_it->second.find(elem);
  Assert(elem_tag_it != discipline_tag_it->second.end(), ExcInternalError());
  // get the iterator to the load to matrix map
  ElementDataStorage::TagToMatrixMap::iterator tag_caseID_it =
    elem_tag_it->second.find(quantity);
  Assert(tag_caseID_it != elem_tag_it->second.end(), ExcInternalError());
  // get the iterator to the load case to qty map
  ElementDataStorage::LoadCaseIDToMatrixMap::iterator caseID_matrix_it =
    tag_caseID_it->second.find(load_case_ID);
  Assert(caseID_matrix_it != tag_caseID_it->second.end(), ExcInternalError());
  qty = *(caseID_matrix_it->second);
}
void ElementDataStorage::get_element_data (DenseVector< double > & qty, const unsigned int discipline_enum_ID, const unsigned int elem_ID, const std::string & tag, const unsigned int case_ID = 0)
function to get the element quantity from the stored data
Definition at line 422 of file ElementDataStorage.C.
References vector_data.
{
//  // first, check if the element has been set to null. If it has been, abort
//  if (this->check_if_null(discipline_enum_ID, elem,quantity,load_case_ID) == true)
//    abort();
  // check if the element exists in the map
  ElementDataStorage::DisciplineToElemIDVectorMap::iterator discipline_tag_it =
  this->vector_data.find(discipline_enum_ID);
  Assert(discipline_tag_it != this->vector_data.end(), ExcInternalError());
  ElementDataStorage::ElemIDToTagVectorMap::iterator elem_tag_it =
  discipline_tag_it->second.find(elem);
  Assert(elem_tag_it != discipline_tag_it->second.end(), ExcInternalError());
  // get the iterator to the load to vector map
  ElementDataStorage::TagToVectorMap::iterator tag_caseID_it =
  elem_tag_it->second.find(quantity);
  Assert(tag_caseID_it != elem_tag_it->second.end(), ExcInternalError());
  // get the iterator to the load case to qty map
  ElementDataStorage::LoadCaseIDToVectorMap::iterator caseID_vector_it =
  tag_caseID_it->second.find(load_case_ID);
  Assert(caseID_vector_it != tag_caseID_it->second.end(), ExcInternalError());
  qty = *(caseID_vector_it->second);
}
Member Data Documentation
DisciplineToElemIDMatrixMap ElementDataStorage::matrix_data [private]
the map for matrix quantities
Definition at line 129 of file ElementDataStorage.h.
Referenced by add_element_data(), checkIfMatrixQtyExists(), clear(), and get_element_data().
DisciplineToElemIDVectorMap ElementDataStorage::vector_data [private]
the map for vector quantities
Definition at line 136 of file ElementDataStorage.h.
Referenced by add_element_data(), checkIfVectorQtyExists(), clear(), and get_element_data().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/ElementDataStorage.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/ElementDataStorage.C