fesystem: GeometricPoint Class Reference
GeometricPoint Class Reference
this class defines a geometric point
#include <GeometricPoint.h>
Public Member Functions
GeometricPoint (GeometricModel &)
constructor
virtual ~GeometricPoint ()
destructor
virtual GeometricEntityType type () const
returns the type of this entity
const Location getLocation () const
returns the coordinates of this point
virtual bool checkIfDuplicate (const GeometricEntity &)
method to check if this object is a duplicate of the given object
Protected Member Functions
virtual void readFromInput (std::istream &)
method to read from input
virtual void writeToOutput (std::ostream &)
method to write to output
Protected Attributes
Location point_coords
location of this point
Detailed Description
this class defines a geometric point
Definition at line 19 of file GeometricPoint.h.
Constructor & Destructor Documentation
GeometricPoint::GeometricPoint (GeometricModel & model)
constructor
Definition at line 13 of file GeometricPoint.C.
                                                   :
  GeometricEntity(model)
{
}
GeometricPoint::~GeometricPoint () [virtual]
destructor
Definition at line 20 of file GeometricPoint.C.
{
}
Member Function Documentation
bool GeometricPoint::checkIfDuplicate (const GeometricEntity & point_ref) [virtual]
method to check if this object is a duplicate of the given object
Implements GeometricEntity.
Definition at line 26 of file GeometricPoint.C.
References GeometricEntity::base_entity_ID, GeometricEntity::baseEntityID(), Location::coord1, Location::coord2, Location::coord3, GeometricEntity::is_duplicate, GeometricEntity::POINT, point_coords, and GeometricEntity::type().
{
  // make sure that the two points are not the same object
  assert (&point_ref != this);
  // also, the type should be a point
  if (point_ref.type() != GeometricEntity::POINT)
    return false;
  // convert this point's reference to a geometric point
  const GeometricPoint& point = dynamic_cast<const GeometricPoint&>(point_ref);
  // this is the tolerance
  double machine_eps = 1.0e-12;
  // comapre the coordinates, and if they are equal to each other, then the points are duplicate.
  double x_diff =0.0, y_diff = 0.0, z_diff = 0.0;
  x_diff = fabs(this->point_coords.coord1 - point.point_coords.coord1);
  y_diff = fabs(this->point_coords.coord2 - point.point_coords.coord2);
  z_diff = fabs(this->point_coords.coord3 - point.point_coords.coord3);
  if (x_diff <= machine_eps && y_diff <= machine_eps && z_diff <= machine_eps)
    {
      // mark this point as duplicate and set the base entity ID as the ID of the
      // given points base entity ID (since the given entity might be a duplicate
      // of another base entity)
      this->is_duplicate = true;
      this->base_entity_ID = point.baseEntityID();
      return true;
    }
  else
    return false;
}
const Location GeometricPoint::getLocation () const [inline]
returns the coordinates of this point
Definition at line 58 of file GeometricPoint.h.
References point_coords.
Referenced by GeometricEllipticArc::checkIfDuplicate().
{
  return this->point_coords;
}
void GeometricPoint::readFromInput (std::istream & input) [protected, virtual]
method to read from input
Implements GeometricEntity.
Definition at line 62 of file GeometricPoint.C.
References Location::coord1, Location::coord2, Location::coord3, point_coords, and GeometricEntity::unique_ID.
{
  input >> this->unique_ID;// ID of this point
  input >> this->point_coords.coord1; // coord1 of this point
  input >> this->point_coords.coord2; // coord2
  input >> this->point_coords.coord3; // coord3
}
GeometricEntity::GeometricEntityType GeometricPoint::type () const [inline, virtual]
returns the type of this entity
Implements GeometricEntity.
Definition at line 52 of file GeometricPoint.h.
References GeometricEntity::POINT.
{
  return GeometricEntity::POINT;
}
void GeometricPoint::writeToOutput (std::ostream & output) [protected, virtual]
method to write to output
Implements GeometricEntity.
Definition at line 71 of file GeometricPoint.C.
References Location::coord1, Location::coord2, Location::coord3, point_coords, and GeometricEntity::unique_ID.
{
  output << this->unique_ID << "   ";
  output << this->point_coords.coord1 << "   ";
  output << this->point_coords.coord2 << "   ";
  output << this->point_coords.coord3 << std::endl;
}
Member Data Documentation
Location GeometricPoint::point_coords [protected]
location of this point
Definition at line 48 of file GeometricPoint.h.
Referenced by checkIfDuplicate(), getLocation(), readFromInput(), and writeToOutput().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricPoint.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricPoint.C