fesystem: GeometricStraightLine Class Reference
GeometricStraightLine Class Reference
this class defines a geometric point
#include <GeometricStraightLine.h>
Public Member Functions
GeometricStraightLine (GeometricModel &)
constructor
virtual ~GeometricStraightLine ()
destructor
virtual GeometricEntityType type () const
returns the type of this entity
virtual bool checkIfDuplicate (const GeometricEntity &)
method to check if this iobject is a duplicate of the given object
Protected Member Functions
virtual void readFromInput (std::istream &)
method to read from input
virtual void writeToOutput (std::ostream &)
method to write to output
Protected Attributes
std::vector< GeometricPoint * > points
location of this point
Detailed Description
this class defines a geometric point
Definition at line 17 of file GeometricStraightLine.h.
Constructor & Destructor Documentation
GeometricStraightLine::GeometricStraightLine (GeometricModel & model)
constructor
Definition at line 16 of file GeometricStraightLine.C.
  :GeometricLine(model)
{
}
GeometricStraightLine::~GeometricStraightLine () [virtual]
destructor
Definition at line 23 of file GeometricStraightLine.C.
{
}
Member Function Documentation
bool GeometricStraightLine::checkIfDuplicate (const GeometricEntity & line_ref) [virtual]
method to check if this iobject is a duplicate of the given object
Implements GeometricLine.
Definition at line 29 of file GeometricStraightLine.C.
References GeometricEntity::base_entity_ID, GeometricEntity::baseEntityID(), GeometricLine::getPoints(), GeometricEntity::is_duplicate, points, GeometricEntity::same_orientation_as_base_entity, GeometricEntity::STRAIGHT_LINE, and GeometricEntity::type().
{
  // make sure that the two lines are not the same object
  assert (&line_ref != this);
  // also, this type should be a line
  if (line_ref.type() != GeometricEntity::STRAIGHT_LINE)
    return false;
  // convert this line's reference to a geometric line
  const GeometricStraightLine& line = dynamic_cast<const GeometricStraightLine&>(line_ref);
  // get the points of this line
  const std::vector<GeometricPoint*>& line_points = line.getPoints();
  // compare the points IDs of this line with that of the given line
  // the comparisons should be made only with the base_entity_IDs
  unsigned int this_point1 = this->points[0]->baseEntityID();
  unsigned int this_point2 = this->points[1]->baseEntityID();
  unsigned int given_point1 = line_points[0]->baseEntityID();
  unsigned int given_point2 = line_points[1]->baseEntityID();
  bool dupl = false;
  if (this_point1 == given_point1 && this_point2 == given_point2)
    {
      dupl = true;
      this->same_orientation_as_base_entity = true;
    }
  else if (this_point2 == given_point1 && this_point1 == given_point2)
    {
      dupl = true;
      this->same_orientation_as_base_entity = false;
    }
  if (dupl == true)
    {
      this->is_duplicate = true;
      this->base_entity_ID = line.baseEntityID();
      return true;
    }
  else
    return  false;
}
void GeometricStraightLine::readFromInput (std::istream & input) [protected, virtual]
method to read from input
Implements GeometricLine.
Definition at line 78 of file GeometricStraightLine.C.
References GeometricEntity::geometric_model, GeometricModel::getPointForID(), points, and GeometricEntity::unique_ID.
{
  input >> this->unique_ID;
  unsigned int point_num = 0;
  // first point
  input >> point_num;
  GeometricPoint  *point = &(this->geometric_model.getPointForID(point_num));
  this->points.push_back(point);
  // second point
  input >> point_num;
  point = &(this->geometric_model.getPointForID(point_num));
  this->points.push_back(point);
}
GeometricEntity::GeometricEntityType GeometricStraightLine::type () const [inline, virtual]
returns the type of this entity
Implements GeometricLine.
Definition at line 47 of file GeometricStraightLine.h.
References GeometricEntity::STRAIGHT_LINE.
{
  return GeometricEntity::STRAIGHT_LINE;
}
void GeometricStraightLine::writeToOutput (std::ostream & output) [protected, virtual]
method to write to output
Implements GeometricLine.
Definition at line 95 of file GeometricStraightLine.C.
References points, and GeometricEntity::unique_ID.
{
  output << this->unique_ID << "   ";
  output << this->points[0]->ID() << "   ";
  output << this->points[1]->ID() << std::endl;
}
Member Data Documentation
std::vector<GeometricPoint*> GeometricStraightLine::points [protected]
location of this point
Reimplemented from GeometricLine.
Definition at line 42 of file GeometricStraightLine.h.
Referenced by checkIfDuplicate(), readFromInput(), and writeToOutput().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricStraightLine.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricStraightLine.C