fesystem: Solver::PetscNonlinearTransientSolver Class Reference
Solver::PetscNonlinearTransientSolver Class Reference
#include <PetscTransientSolver.h>
Public Member Functions
PetscNonlinearTransientSolver (const Solver::NonlinearTransientSolverInfo &transient_info, const Solver::NonlinearSolverInfo &nonlinear_info, const Solver::LinearSolverInfo &linear_info)
constructor
virtual ~PetscNonlinearTransientSolver ()
virtual void clear ()
virtual void solve ()
method to solve the eigen system
virtual double getSimulatedTime ()
virtual double getCurrentTime ()
virtual double getCurrentStepSize ()
virtual unsigned int getSimulatedIterationNumber ()
virtual unsigned int getCurrentIterationNumber ()
virtual void setInitialCondition (std::vector< NumericVector< double > * > &state_vecs)
set initial conditions for the analysis
Protected Attributes
TS petsc_ts
petsc transient solver context
SNES petsc_snes
PETSc nonlinear solver context.
KSP petsc_ksp
PETSc KSP solver for the nonlinear solver.
PC petsc_pc
a PC context for the linear solver
Detailed Description
this class provides an interface to a solver for the solution of eigensystem. This inherits from the FESystemSolverBase class. It takes a pointer to the analysis driver object that owns an instantiation of this class
Definition at line 98 of file PetscTransientSolver.h.
Constructor & Destructor Documentation
Solver::PetscNonlinearTransientSolver::PetscNonlinearTransientSolver (const Solver::NonlinearTransientSolverInfo & transient_info, const Solver::NonlinearSolverInfo & nonlinear_info, const Solver::LinearSolverInfo & linear_info)
constructor
Definition at line 36 of file PetscTransientSolver.C.
References FESystem::COMM_WORLD, KSP_PRE_ONLY_ENUM_ID, NEWTON_NONLINEAR_SOLVER_CUBIC_LINE_SEARCH_ENUM_ID, NEWTON_NONLINEAR_SOLVER_NO_LINE_SEARCH_ENUM_ID, NEWTON_NONLINEAR_SOLVER_NO_NORMS_LINE_SEARCH_ENUM_ID, NEWTON_NONLINEAR_SOLVER_QUADRATIC_LINE_SEARCH_ENUM_ID, PC_LU_ENUM_ID, PETSC_BEULER_TRANSIENT_SOLVER_ENUM_ID, PETSC_CRANK_NICHOLSON_TRANSIENT_SOLVER_ENUM_ID, PETSC_FEULER_TRANSIENT_SOLVER_ENUM_ID, and PETSC_RUNGE_KUTTA_TRANSIENT_SOLVER_ENUM_ID.
                                           :
Solver::NonlinearTransientSolverBase(transient_info,
                                     nonlinear_info,
                                     linear_info)
{
  // create the SNES context and set the KSP and PC options
  PetscErrorCode ierr = 0;
  ierr = TSCreate(FESystem::COMM_WORLD, &(this->petsc_ts));
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // set the options for the SNES
  switch (this->transient_solver_info.getTransientSolverKindEnumID())
    {
    case PETSC_FEULER_TRANSIENT_SOLVER_ENUM_ID:
      {
        ierr = TSSetType(this->petsc_ts, TS_EULER);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    case PETSC_BEULER_TRANSIENT_SOLVER_ENUM_ID:
      {
        ierr = TSSetType(this->petsc_ts, TS_BEULER);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    case PETSC_CRANK_NICHOLSON_TRANSIENT_SOLVER_ENUM_ID:
      {
        ierr = TSSetType(this->petsc_ts, TS_CRANK_NICHOLSON);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    case PETSC_RUNGE_KUTTA_TRANSIENT_SOLVER_ENUM_ID:
      {
        ierr = TSSetType(this->petsc_ts, TS_RUNGE_KUTTA);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    default:
      Assert(false, ExcInternalError());
    }
  ierr = TSSetProblemType(this->petsc_ts, TS_NONLINEAR);
  CHKERRABORT(FESystem::COMM_WORLD,ierr);
  ierr = TSSetDuration(this->petsc_ts,
                       this->transient_solver_info.getMaxTimeIterations(),
                       this->transient_solver_info.getDuration());
  CHKERRABORT(FESystem::COMM_WORLD,ierr);
  ierr = TSSetInitialTimeStep(this->petsc_ts,
                              this->transient_solver_info.getInitialTime(),
                              this->transient_solver_info.getInitialTimeStep());
  CHKERRABORT(FESystem::COMM_WORLD,ierr);
  // now, set the tolerance for adaptive time stepping. However, adaptive time stepping
  // is allowed only for RK methods, and that should be assured for this
  if (this->transient_solver_info.ifAdaptiveTimeSteps())
    {
    AssertThrow (this->transient_solver_info.getTransientSolverKindEnumID() ==
                 Solver::PETSC_RUNGE_KUTTA_TRANSIENT_SOLVER::num(),
                 ExcInternalError());
    ierr = TSRKSetTolerance(this->petsc_ts,
                            this->transient_solver_info.getGlobalTolerance());
    CHKERRABORT(FESystem::COMM_WORLD,ierr);
    }
  // set the nonlinear solver options
  ierr = TSGetSNES(this->petsc_ts, &(this->petsc_snes));
  CHKERRABORT(FESystem::COMM_WORLD,ierr);
  // set the options for the SNES
  switch (this->nonlinear_solver_info.getNonlinearSolverKindEnumID())
    {
    case NEWTON_NONLINEAR_SOLVER_CUBIC_LINE_SEARCH_ENUM_ID:
      {
        // set the solver type to line search, and also set the line
        // search type
        ierr = SNESSetType(this->petsc_snes, SNESLS);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
        ierr = SNESLineSearchSet(this->petsc_snes, SNESLineSearchCubic, PETSC_NULL);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    case NEWTON_NONLINEAR_SOLVER_QUADRATIC_LINE_SEARCH_ENUM_ID:
      {
        // set the solver type to line search, and also set the line
        // search type
        ierr = SNESSetType(this->petsc_snes, SNESLS);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
        ierr = SNESLineSearchSet(this->petsc_snes, SNESLineSearchQuadratic, PETSC_NULL);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    case NEWTON_NONLINEAR_SOLVER_NO_LINE_SEARCH_ENUM_ID:
      {
        // set the solver type to line search, and also set the line
        // search type
        ierr = SNESSetType(this->petsc_snes, SNESLS);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
        ierr = SNESLineSearchSet(this->petsc_snes, SNESLineSearchNo, PETSC_NULL);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    case NEWTON_NONLINEAR_SOLVER_NO_NORMS_LINE_SEARCH_ENUM_ID:
      {
        // set the solver type to line search, and also set the line
        // search type
        ierr = SNESSetType(this->petsc_snes, SNESLS);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
        ierr = SNESLineSearchSet(this->petsc_snes, SNESLineSearchNoNorms, PETSC_NULL);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    default:
      Assert(false, ExcInternalError());
    }
    const double nonlinear_tol = this->nonlinear_solver_info.getConvergenceTolerance();
    const unsigned int nonlinear_maxits = this->nonlinear_solver_info.getMaximumIterations();
    ierr = SNESSetTolerances(this->petsc_snes, nonlinear_tol, nonlinear_tol, nonlinear_tol,
                             nonlinear_maxits, 1000);
    CHKERRABORT(FESystem::COMM_WORLD, ierr);
    // set the default monitor for the solver
    ierr = SNESSetMonitor(this->petsc_snes,
                          SNESDefaultMonitor,
                          PETSC_NULL, PETSC_NULL);
    CHKERRABORT(FESystem::COMM_WORLD,ierr);
    // get the KSP context from the SNES and set its options
    ierr = SNESGetKSP(this->petsc_snes, &(this->petsc_ksp));
    CHKERRABORT(FESystem::COMM_WORLD,ierr);
//    }
//  else if (this->transient_solver_info.getTransientProblemKindEnumID() ==
//           Solver::NONLINEAR_TRANSIENT_PROBLEM::num())
//    {
//    ierr = TSSetProblemType(this->petsc_ts, TS_LINEAR);
//    CHKERRABORT(FESystem::COMM_WORLD,ierr);
//
//    ierr = TSGetKSP(this->petsc_ts, &(this->petsc_ksp));
//    CHKERRABORT(FESystem::COMM_WORLD,ierr);
//    }
  // set the KSP type
  switch (this->linear_solver_info.getKSPTypeEnumID())
    {
    case KSP_PRE_ONLY_ENUM_ID:
      {
        ierr = KSPSetType(this->petsc_ksp , KSPPREONLY);
        CHKERRABORT(FESystem::COMM_WORLD, ierr);
      }
      break;
    default:
      Assert(false, ExcInternalError());
    }
  // set the PC to LU
  ierr = KSPGetPC(this->petsc_ksp, &(this->petsc_pc));
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  switch (this->linear_solver_info.getPCTypeEnumID())
    {
    case PC_LU_ENUM_ID:
      {
        ierr = PCSetType(this->petsc_pc , PCLU);
        CHKERRABORT(FESystem::COMM_WORLD, ierr);
      }
      break;
    default:
      Assert(false, ExcInternalError());
    }
}
Solver::PetscNonlinearTransientSolver::~PetscNonlinearTransientSolver () [virtual]
Definition at line 232 of file PetscTransientSolver.C.
References FESystem::COMM_WORLD, and petsc_ts.
{
  // destroy the TS context
  PetscErrorCode ierr = TSDestroy(this->petsc_ts);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
Member Function Documentation
void Solver::PetscNonlinearTransientSolver::clear () [virtual]
this method clears the data structures of this object. This should be called each time the used finishes using this object.
Reimplemented from Solver::NonlinearTransientSolverBase.
Definition at line 243 of file PetscTransientSolver.C.
References Solver::NonlinearTransientSolverBase::clear().
{
  Solver::NonlinearTransientSolverBase::clear();
}
unsigned int Solver::PetscNonlinearTransientSolver::getCurrentIterationNumber () [virtual]
Returns:
the current time iteration of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 331 of file PetscTransientSolver.C.
References FESystem::COMM_WORLD.
{
  PetscInt time;
  PetscErrorCode ierr;
  ierr = TSGetTimeStepNumber(this->petsc_ts, &time);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  return time;
}
double Solver::PetscNonlinearTransientSolver::getCurrentStepSize () [virtual]
Returns:
the current time step of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 316 of file PetscTransientSolver.C.
References FESystem::COMM_WORLD.
{
  double time;
  PetscErrorCode ierr;
  ierr = TSGetTimeStep(this->petsc_ts, &time);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  return time;
}
double Solver::PetscNonlinearTransientSolver::getCurrentTime () [virtual]
Returns:
the current time of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 301 of file PetscTransientSolver.C.
References FESystem::COMM_WORLD.
{
  double time;
  PetscErrorCode ierr;
  ierr = TSGetTime(this->petsc_ts, &time);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  return time;
}
virtual unsigned int Solver::PetscNonlinearTransientSolver::getSimulatedIterationNumber () [virtual]
Returns:
the current time iteration of the solver integration
Implements Solver::TransientSolverBase.
virtual double Solver::PetscNonlinearTransientSolver::getSimulatedTime () [virtual]
Returns:
the current time of the solver integration
Implements Solver::TransientSolverBase.
virtual void Solver::PetscNonlinearTransientSolver::setInitialCondition (std::vector< NumericVector< double > * > & state_vecs) [virtual]
set initial conditions for the analysis
Implements Solver::TransientSolverBase.
void Solver::PetscNonlinearTransientSolver::solve () [virtual]
method to solve the eigen system
Implements Solver::TransientSolverBase.
Definition at line 253 of file PetscTransientSolver.C.
References FESystem::COMM_WORLD, FESystemNonlinearTransientSolverRHSFunctionEvaluation(), FESystemNonlinearTransientSolverRHSJacobianEvaluation(), and FESystemTransientSolverMonitor().
{
  this->analysis_driver->getFESystemController().performance_logging->setEvent
  ("PetscNonlinearSolver::solve()", "Solver");
  Assert(this->jacobian != NULL, ExcInternalError());
  this->jacobian->close();
  solution.close();
  Mat petsc_jac = dynamic_cast<PetscMatrix<double>*>(this->jacobian)->mat();
  Vec petsc_sol = dynamic_cast<PetscVector<double>&>(solution).vec();
  PetscErrorCode ierr;
  ierr = TSSetRHSFunction(this->petsc_ts, FESystemNonlinearTransientSolverRHSFunctionEvaluation,
                          this);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = TSSetRHSJacobian(this->petsc_ts, petsc_jac, petsc_jac,
                          FESystemNonlinearTransientSolverRHSJacobianEvaluation,
                          this);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = TSSetSolution(this->petsc_ts, petsc_sol);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = TSSetMonitor(this->petsc_ts,
                      FESystemTransientSolverMonitor,
                      this, PETSC_NULL);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // now step
  PetscInt steps=0;
  double time=0.0;
  ierr = TSStep(this->petsc_ts, &steps, &time);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->analysis_driver->getFESystemController().performance_logging->unsetEvent
    ("PetscNonlinearSolver::solve()", "Solver");
}
Member Data Documentation
KSP Solver::PetscNonlinearTransientSolver::petsc_ksp [protected]
PETSc KSP solver for the nonlinear solver.
Definition at line 144 of file PetscTransientSolver.h.
PC Solver::PetscNonlinearTransientSolver::petsc_pc [protected]
a PC context for the linear solver
Definition at line 147 of file PetscTransientSolver.h.
SNES Solver::PetscNonlinearTransientSolver::petsc_snes [protected]
PETSc nonlinear solver context.
Definition at line 141 of file PetscTransientSolver.h.
TS Solver::PetscNonlinearTransientSolver::petsc_ts [protected]
petsc transient solver context
Definition at line 138 of file PetscTransientSolver.h.
Referenced by ~PetscNonlinearTransientSolver().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/PetscTransientSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/PetscTransientSolver.C