fesystem: Solver::LinearTransientSolverBase Class Reference
Solver::LinearTransientSolverBase Class Reference
#include <TransientSolver.h>
Public Member Functions
LinearTransientSolverBase (const Solver::LinearTransientSolverInfo &transient_info, const Solver::LinearSolverInfo &linear_info)
constructor
virtual ~LinearTransientSolverBase ()
void setCoefficientMatrixTimeDependence (const bool dependence)
sets if the matrices are time dependent or time independent
virtual void clear ()
Protected Attributes
const Solver::LinearSolverInfo & linear_solver_info
LinearSolverInfo that stores information about this solver.
bool time_independent_coefficient_matrices
if the matrices are dependent on time or not
Detailed Description
this class provides an interface to a solver for the solution of eigensystem. This inherits from the FESystemSolverBase class. It takes a pointer to the analysis driver object that owns an instantiation of this class
Definition at line 143 of file TransientSolver.h.
Constructor & Destructor Documentation
Solver::LinearTransientSolverBase::LinearTransientSolverBase (const Solver::LinearTransientSolverInfo & transient_info, const Solver::LinearSolverInfo & linear_info)
constructor
Definition at line 55 of file TransientSolver.C.
                                           :
Solver::TransientSolverBase(dynamic_cast<const Solver::TransientSolverInfoBase&>(transient_info)),
linear_solver_info(linear_info),
time_independent_coefficient_matrices(false)
{
}
Solver::LinearTransientSolverBase::~LinearTransientSolverBase () [virtual]
Definition at line 65 of file TransientSolver.C.
{
}
Member Function Documentation
void Solver::LinearTransientSolverBase::clear () [virtual]
this method clears the data structures of this object. This should be called each time the used finishes using this object.
Reimplemented from Solver::TransientSolverBase.
Reimplemented in Solver::EulerLinearTransientSolver, and Solver::NewmarkLinearTransientSolver.
Definition at line 73 of file TransientSolver.C.
References Solver::TransientSolverBase::clear().
Referenced by Solver::EulerLinearTransientSolver::clear(), and Solver::NewmarkLinearTransientSolver::clear().
{
  this->time_independent_coefficient_matrices = false;
  Solver::TransientSolverBase::clear();
}
void Solver::LinearTransientSolverBase::setCoefficientMatrixTimeDependence (const bool dependence)
sets if the matrices are time dependent or time independent
Definition at line 81 of file TransientSolver.C.
{
  this->time_independent_coefficient_matrices = dependence;
}
Member Data Documentation
const Solver::LinearSolverInfo& Solver::LinearTransientSolverBase::linear_solver_info [protected]
LinearSolverInfo that stores information about this solver.
Definition at line 165 of file TransientSolver.h.
bool Solver::LinearTransientSolverBase::time_independent_coefficient_matrices [protected]
if the matrices are dependent on time or not
Definition at line 168 of file TransientSolver.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/TransientSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/TransientSolver.C