fesystem: Driver::NonlinearTransientAnalysisDriver Class Reference
Driver::NonlinearTransientAnalysisDriver Class Reference
this is the base for nonlinear transient analysis drivers of various orders
#include <TransientAnalysisDriver.h>
Public Member Functions
NonlinearTransientAnalysisDriver (const unsigned int ID, FESystem::FESystemController &controller)
constructor
virtual ~NonlinearTransientAnalysisDriver ()
destructor
void getJacobianMatrix (const double time, std::vector< NumericVector< double > * > &sol_vec, SparseMatrix< double > &matrix)
void getCoefficientMatrices (const double time, std::vector< NumericVector< double > * > &sol_vec, std::vector< SparseMatrix< double > * > &matrices)
void getForceVector (const double time, std::vector< NumericVector< double > * > &vecs, NumericVector< double > &res)
void getResidualVector (const double time, std::vector< NumericVector< double > * > &vecs, NumericVector< double > &res)
virtual void getForceVector (const double time, NumericVector< double > &vec)
calculates the force vector for sensitivity analysis problems
virtual void getCoefficientMatrices (const double time, std::vector< SparseMatrix< double > * > &matrices)
Protected Member Functions
virtual void initialize ()
this method initializes itself before the solutions are started for the driver
virtual void solveCurrentLoadCase ()
this method solves for the current load case
virtual void addMatricesAndVectors ()
function will add the matrices and vectors for this analysis
Detailed Description
this is the base for nonlinear transient analysis drivers of various orders
Definition at line 237 of file TransientAnalysisDriver.h.
Constructor & Destructor Documentation
Driver::NonlinearTransientAnalysisDriver::NonlinearTransientAnalysisDriver (const unsigned int ID, FESystem::FESystemController & controller)
constructor
Definition at line 607 of file TransientAnalysisDriver.C.
                                                                     :
Driver::TransientAnalysisDriver(ID, fesys_controller,
                                NONLINEAR_TRANSIENT_ANALYSIS_DRIVER::num())
{
}
Driver::NonlinearTransientAnalysisDriver::~NonlinearTransientAnalysisDriver () [virtual]
destructor
Definition at line 616 of file TransientAnalysisDriver.C.
{
}
Member Function Documentation
void Driver::NonlinearTransientAnalysisDriver::addMatricesAndVectors () [protected, virtual]
function will add the matrices and vectors for this analysis
Implements Driver::AnalysisDriver.
Definition at line 648 of file TransientAnalysisDriver.C.
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  // add the jacobian matrix
  SparseMatrix<double>& jac = this->addMatrix(Driver::JACOBIAN_MATRIX::name());
  it->second->initMatrix(jac);
  SparseMatrix<double>& scr_mat = this->addMatrix("ScratchMatrix");
  it->second->initMatrix(scr_mat);
  NumericVector<double>& scr_vec = this->addVector("ScratchVector1");
  it->second->initVector(scr_vec);
  // add a system matrix, a solution vector and a rhs
  switch (it->second->getTransientSystemOrder())
  {
    case 2:
    {
      if (it->second->disciplineHasMatrix(Driver::TRANSIENT_C2_MATRIX::num()))
        {
          SparseMatrix<double>& mat = this->addMatrix(Driver::TRANSIENT_C2_MATRIX::name());
          it->second->initMatrix(mat);
        }
    }
    case 1:
    {
      if (it->second->disciplineHasMatrix(Driver::TRANSIENT_C1_MATRIX::num()))
        {
          SparseMatrix<double>& mat = this->addMatrix(Driver::TRANSIENT_C1_MATRIX::name());
          it->second->initMatrix(mat);
        }
      if (it->second->disciplineHasMatrix(Driver::SYSTEM_MATRIX::num()))
        {
          SparseMatrix<double>& mat = this->addMatrix(Driver::SYSTEM_MATRIX::name());
          it->second->initMatrix(mat);
        }
    }
      break;
    default:
      Assert(false, ExcInternalError());
  }
}
void Driver::NonlinearTransientAnalysisDriver::getCoefficientMatrices (const double time, std::vector< NumericVector< double > * > & sol_vec, std::vector< SparseMatrix< double > * > & matrices)
calculate the coefficient matrices. The location of the matrix is also the order of the time derivative vector
Definition at line 930 of file TransientAnalysisDriver.C.
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator discipline_it;
  discipline_it = this->analysis_discipline_map.begin();
  this->current_analysis_time = time;
  unsigned int order = discipline_it->second->getTransientSystemOrder();
  Assert(vecs.size() == (order+1), ExcInternalError());
  Assert(matrices.size() == (order+1), ExcInternalError());
  Assert(this->current_solution.size() == (order+1),ExcInternalError());
  for (unsigned int i=0; i <= order; i++)
    {
      Assert(vecs[i] != NULL, ExcInternalError());
      this->current_solution[i]->zero();
      vecs[i]->close();
      this->localizeSolution(discipline_it->second->getAnalysisDofMap(), *(vecs[i]),
                             *(this->current_solution[i]));
      this->current_solution[i]->close();
    }
  // create a map of the matrices to be requested from the system
  std::map<unsigned int, double> real_map;
  std::map<unsigned int, SparseMatrix<double>*> matrix_map;
  std::map<unsigned int, NumericVector<double>*> vector_map;
  switch (order)
  {
    case 2:
    {
      if (matrices[2] != NULL)
        {
          Assert(discipline_it->second->disciplineHasMatrix(Driver::TRANSIENT_C2_MATRIX::num()),
                 ExcInternalError());
          matrices[2]->zero(); matrices[2]->perform_intermediate_matrix_assembly();
          matrix_map[Driver::TRANSIENT_C2_MATRIX::num()] = matrices[2];
        }
    }
    case 1:
    {
      if (matrices[1] != NULL)
        {
          Assert(discipline_it->second->disciplineHasMatrix(Driver::TRANSIENT_C1_MATRIX::num()),
                 ExcInternalError());
          matrices[1]->zero(); matrices[1]->perform_intermediate_matrix_assembly();
          matrix_map[Driver::TRANSIENT_C1_MATRIX::num()] = matrices[1];
        }
      if (matrices[0] != NULL)
        {
          Assert(discipline_it->second->disciplineHasMatrix(Driver::SYSTEM_MATRIX::num()),
                 ExcInternalError());
          matrices[0]->zero(); matrices[0]->perform_intermediate_matrix_assembly();
          matrix_map[Driver::SYSTEM_MATRIX::num()] = matrices[0];
        }
    }
      break;
    default:
      Assert(false, ExcInternalError());
  }
  // fill the matrices and vectors with the required quantities
  discipline_it->second->fillQuantity(real_map, matrix_map, vector_map);
  std::map<unsigned int, SparseMatrix<double>*>::iterator it, end;
  it = matrix_map.begin();
  end = matrix_map.end();
  double time_step = dynamic_cast<Solver::TransientSolverBase*>(this->solver)->getTimeStepSize();
  unsigned int i = 0;
  for (; it != end; it++)
    {
      it->second->perform_intermediate_matrix_assembly();
      this->applyBoundaryConditionsToMatrixForCurrentAnalysis(*(it->second), pow(time_step,i), discipline_it->second->getDisciplineEnumID());
      it->second->close();
      i++;
    }
  // clear the solution vectors
  for (unsigned int i=0; i <= order; i++)
    this->current_solution[i]->zero();
  // return control back to the solver
}
void Driver::NonlinearTransientAnalysisDriver::getCoefficientMatrices (const double time, std::vector< SparseMatrix< double > * > & matrices) [virtual]
calculates the coefficient matrices for sensitivity analysis for the specified time
Implements Driver::TransientAnalysisDriver.
Definition at line 1276 of file TransientAnalysisDriver.C.
References FESystemDatabase::TimeDependentDataInfo::clear(), FESystemDatabase::GenericDataInfoBase::setDisciplineEnumID(), FESystemDatabase::GenericDataInfoBase::setLoadCase(), FESystemDatabase::GenericDataInfoBase::setName(), FESystemDatabase::TimeDependentDataInfo::setOrder(), and FESystemDatabase::TimeDependentDataInfo::setTransientIterationInfo().
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator discipline_it;
  discipline_it = this->analysis_discipline_map.begin();
  // this routine is to be used only for sensitivity analysis routines, which are linear
  Assert(this->current_analysis_kind_enum_ID == SENSITIVITY_ANALYSIS::num(),
         ExcInternalError());
  // set the analysis time, and make sure that it matches with the time in the time vector
  // for which the analysis was performed
  this->current_analysis_time = time;
  Assert(this->getCurrentAnalysisTime() ==
         this->time_values[this->getCurrentIterationNumber()-1],
         ExcInternalError());
  unsigned int order = discipline_it->second->getTransientSystemOrder();
  Assert(matrices.size() == (order+1), ExcInternalError());
  // create a map of the matrices to be requested from the system
  std::map<unsigned int, double> real_map;
  std::map<unsigned int, SparseMatrix<double>*> matrix_map;
  std::map<unsigned int, NumericVector<double>*> vector_map;
  switch (order)
  {
    case 2:
    {
      if (discipline_it->second->disciplineHasMatrix(Driver::TRANSIENT_C2_MATRIX::num()))
        {
          matrices[2]->zero(); matrices[2]->close();
          matrix_map[Driver::TRANSIENT_C2_MATRIX::num()] = matrices[2];
        }
    }
    case 1:
    {
      if (discipline_it->second->disciplineHasMatrix(Driver::TRANSIENT_C1_MATRIX::num()))
        {
          matrices[1]->zero(); matrices[1]->close();
          matrix_map[Driver::TRANSIENT_C1_MATRIX::num()] = matrices[1];
        }
      if (discipline_it->second->disciplineHasMatrix(Driver::SYSTEM_MATRIX::num()))
        {
          matrices[0]->zero(); matrices[0]->close();
          // ask for the jacobian matrix, since that is needed for nonlinear problems
          matrix_map[Driver::JACOBIAN_MATRIX::num()] = matrices[0];
        }
    }
      break;
    default:
      Assert(false, ExcInternalError());
  }
  // set the solution vectors for the current iteration
  Assert(this->current_solution.size() == (order+1),
         ExcInternalError());
  FESystemUtility::AutoPtrVector<NumericVector<double> > vecs(order+1);
  std::auto_ptr<NumericVector<double> > vec_ptr;
  for (unsigned int i=0; i <= order; i++)
    {
      // create a vector for the initial conditions, and init it to the
      // dof distribution of the discipline
      vec_ptr.reset(NumericVector<double>::build().release());
      discipline_it->second->initVector(*vec_ptr);
      vecs.reset(i, vec_ptr.release());
    }
  FESystemDatabase::TimeDependentDataInfo data_info;
  // now get the solution vectors from the database
  for (unsigned int i=0; i <= order; i++)
    {
      data_info.clear();
      data_info.setDisciplineEnumID(discipline_it->second->getDisciplineEnumID());
      data_info.setName("Solution");
      data_info.setOrder(i);
      data_info.setLoadCase(this->current_load_case);
      data_info.setTransientIterationInfo(this->getCurrentIterationNumber(),
                                          this->getCurrentAnalysisTime());
      this->fesystem_controller.global_data_storage->fillVector(data_info, *(vecs[i]));
      vecs[i]->close();
      this->current_solution[i]->zero();
      this->localizeSolution(discipline_it->second->getAnalysisDofMap(),*(vecs[i]),
                             *(this->current_solution[i]));
    }
  // fill the matrices and vectors with the required quantities
  discipline_it->second->fillQuantity(real_map, matrix_map, vector_map);
  std::map<unsigned int, SparseMatrix<double>*>::iterator it, end;
  it = matrix_map.begin();
  end = matrix_map.end();
  double time_step = dynamic_cast<Solver::TransientSolverBase*>(this->solver)->getTimeStepSize();
  unsigned int i = 0;
  for (; it != end; it++)
    {
      it->second->close();
      this->applyBoundaryConditionsToMatrixForCurrentAnalysis(*(it->second), pow(time_step,i), discipline_it->second->getDisciplineEnumID());
      it->second->close();
      i++;
    }
  // clear the solution vectors before returning
  for (unsigned int i=0; i <= order; i++)
    this->current_solution[i]->zero();
  // return control back to the solver
}
void Driver::NonlinearTransientAnalysisDriver::getForceVector (const double time, std::vector< NumericVector< double > * > & vecs, NumericVector< double > & res)
calculates the force vector at the specified time and solution vectors specified in vecs
Definition at line 1031 of file TransientAnalysisDriver.C.
References ANALYSIS_ENUM_ID, and SENSITIVITY_ANALYSIS_ENUM_ID.
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  this->current_analysis_time = time;
  unsigned int order = it->second->getTransientSystemOrder();
  Assert(vecs.size() == (order+1), ExcInternalError());
  Assert(this->current_solution.size() == (order+1),ExcInternalError());
  for (unsigned int i=0; i <= order; i++)
    {
      Assert(vecs[i] != NULL, ExcInternalError());
      this->current_solution[i]->zero();
      vecs[i]->close();
      this->localizeSolution(it->second->getAnalysisDofMap(), *(vecs[i]),
                              *(this->current_solution[i]));
      this->current_solution[i]->close();
    }
  vec.zero();
  // create a map of the matrices to be requested from the system
  std::map<unsigned int, double> real_map;
  std::map<unsigned int, SparseMatrix<double>*> matrix_map;
  std::map<unsigned int, NumericVector<double>*> vector_map;
  switch (this->current_analysis_kind_enum_ID)
  {
    case ANALYSIS_ENUM_ID:
    {
      vector_map[Driver::FORCE_VECTOR::num()] = &vec;
      it->second->fillQuantity(real_map, matrix_map, vector_map);
      this->applyBoundaryConditionsToVectorForCurrentAnalysis(vec, true, it->second->getDisciplineEnumID());
      vec.close();
    }
      break;
    case SENSITIVITY_ANALYSIS_ENUM_ID:
    default:
      Assert(false, ExcInternalError());
  }
  // clear the solution vectors
  for (unsigned int i=0; i <= order; i++)
    this->current_solution[i]->zero();
  // return control back to the solver
}
void Driver::NonlinearTransientAnalysisDriver::getForceVector (const double time, NumericVector< double > & vec) [virtual]
calculates the force vector for sensitivity analysis problems
Implements Driver::TransientAnalysisDriver.
Definition at line 1403 of file TransientAnalysisDriver.C.
References FESystemDatabase::TimeDependentDataInfo::clear(), FESystemDatabase::GenericDataInfoBase::setDisciplineEnumID(), FESystemDatabase::GenericDataInfoBase::setLoadCase(), FESystemDatabase::GenericDataInfoBase::setName(), FESystemDatabase::TimeDependentDataInfo::setOrder(), and FESystemDatabase::TimeDependentDataInfo::setTransientIterationInfo().
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  // this routine is to be used only for sensitivity analysis routines, which are linear
  Assert(this->current_analysis_kind_enum_ID == SENSITIVITY_ANALYSIS::num(),
         ExcInternalError());
  // set the analysis time, and make sure that it matches with the time in the time vector
  // for which the analysis was performed
  this->current_analysis_time = time;
  Assert(this->getCurrentAnalysisTime() ==
         this->time_values[this->getCurrentIterationNumber()-1],
         ExcInternalError());
  unsigned int order = it->second->getTransientSystemOrder();
  // set the solution vectors for the current iteration
  Assert(this->current_solution.size() == (order+1), ExcInternalError());
  FESystemUtility::AutoPtrVector<NumericVector<double> > vecs(order+1);
  std::auto_ptr<NumericVector<double> > vec_ptr;
  for (unsigned int i=0; i <= order; i++)
    {
      // create a vector for the initial conditions, and init it to the
      // dof distribution of the discipline
      vec_ptr.reset(NumericVector<double>::build().release());
      it->second->initVector(*vec_ptr);
      vecs.reset(i, vec_ptr.release());
    }
  FESystemDatabase::TimeDependentDataInfo data_info;
  // now get the solution vectors from the database
  for (unsigned int i=0; i <= order; i++)
    {
      data_info.clear();
      data_info.setDisciplineEnumID(it->second->getDisciplineEnumID());
      data_info.setName("Solution");
      data_info.setOrder(i);
      data_info.setLoadCase(this->current_load_case);
      data_info.setTransientIterationInfo(this->getCurrentIterationNumber(),
                                          this->getCurrentAnalysisTime());
      this->fesystem_controller.global_data_storage->fillVector(data_info, *(vecs[i]));
      vecs[i]->close();
      this->current_solution[i]->zero();
      this->localizeSolution(it->second->getAnalysisDofMap(),*(vecs[i]),
                             *(this->current_solution[i]));
    }
  // create a map of the matrices to be requested from the system
  std::map<unsigned int, double> real_map;
  std::map<unsigned int, SparseMatrix<double>*> matrix_map;
  std::map<unsigned int, NumericVector<double>*> vector_map;
  if (!this->haveMatrix("ScratchMatrix"))
    this->addMatrix("ScratchMatrix");
  if (!this->haveVector("ScratchVector1"))
    this->addVector("ScratchVector1");
  SparseMatrix<double>& scratch_matrix = this->getMatrix("ScratchMatrix");
  NumericVector<double>& scratch_vec1 = this->getVector("ScratchVector1");
  vec.zero(); vec.perform_intermediate_vector_assembly();
  vector_map[Driver::FORCE_VECTOR_SENSITIVITY::num()] = &vec;
  it->second->fillQuantity(real_map, matrix_map, vector_map);
  vector_map.clear();
  vec.perform_intermediate_vector_assembly();
  unsigned int qty_enum_ID = 0, qty_sensitivity_enum_ID=0;
  for (unsigned int i=0; i<= order; i++)
    {
      switch (i)
      {
        case 0:
        {
          qty_enum_ID = Driver::SYSTEM_MATRIX::num();
          qty_sensitivity_enum_ID = Driver::SYSTEM_MATRIX_SENSITIVITY::num();
        }
          break;
        case 1:
        {
          qty_enum_ID = Driver::TRANSIENT_C1_MATRIX::num();
          qty_sensitivity_enum_ID = Driver::TRANSIENT_C1_MATRIX_SENSITIVITY::num();
        }
          break;
        case 2:
        {
          qty_enum_ID = Driver::TRANSIENT_C2_MATRIX::num();
          qty_sensitivity_enum_ID = Driver::TRANSIENT_C2_MATRIX_SENSITIVITY::num();
        }
          break;
        default:
          Assert(false, ExcInternalError());
      }
      // if the matrix for this order exists, then process it, else go to the
      // next order
      if (it->second->disciplineHasMatrix(qty_enum_ID))
        {
          // get the matrix and the solution
          scratch_matrix.zero(); scratch_matrix.perform_intermediate_matrix_assembly();
          matrix_map.clear();
          matrix_map[qty_sensitivity_enum_ID] = &scratch_matrix;
          it->second->fillQuantity(real_map, matrix_map, vector_map);
          scratch_matrix.close();
          scratch_vec1.zero();
          scratch_matrix.multiply_vector(*(this->current_solution[i]), scratch_vec1);
          vec.add(-1.0, scratch_vec1);
          vec.perform_intermediate_vector_assembly();
        }
    }
  this->applyBoundaryConditionsToVectorForCurrentAnalysis(vec, false, it->second->getDisciplineEnumID());
  vec.close();
  // clear the solution vectors before returning
  for (unsigned int i=0; i <= order; i++)
    this->current_solution[i]->zero();
  // return control back to the solver
}
void Driver::NonlinearTransientAnalysisDriver::getJacobianMatrix (const double time, std::vector< NumericVector< double > * > & sol_vec, SparseMatrix< double > & matrix)
calculate the coefficient matrices. The location of the matrix is also the order of the time derivative vector
Definition at line 1213 of file TransientAnalysisDriver.C.
References ANALYSIS_ENUM_ID, and SENSITIVITY_ANALYSIS_ENUM_ID.
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  this->current_analysis_time = time;
  unsigned int order = it->second->getTransientSystemOrder();
  Assert(vecs.size() == (order+1), ExcInternalError());
  Assert(this->current_solution.size() == (order+1),ExcInternalError());
  for (unsigned int i=0; i <= order; i++)
    {
      Assert(vecs[i] != NULL, ExcInternalError());
      this->current_solution[i]->zero();
      vecs[i]->close();
      this->localizeSolution(it->second->getAnalysisDofMap(), *(vecs[i]),
                              *(this->current_solution[i]));
      this->current_solution[i]->close();
    }
  // create a map of the matrices to be requested from the system
  std::map<unsigned int, double> real_map;
  std::map<unsigned int, SparseMatrix<double>*> matrix_map;
  std::map<unsigned int, NumericVector<double>*> vector_map;
  switch (this->current_analysis_kind_enum_ID)
  {
    case ANALYSIS_ENUM_ID:
    {
      jac.zero(); jac.perform_intermediate_matrix_assembly();
      matrix_map[Driver::JACOBIAN_MATRIX::num()] = &jac;
      it->second->fillQuantity(real_map, matrix_map, vector_map);
      jac.perform_intermediate_matrix_assembly();
      this->applyBoundaryConditionsToMatrixForCurrentAnalysis(jac, 1.0, it->second->getDisciplineEnumID());
      jac.close();
    }
      break;
      // jacobian for a sensitivity analysis does not make sense, since the
      // solution is already known
    case SENSITIVITY_ANALYSIS_ENUM_ID:
    default:
      Assert(false, ExcInternalError());
  }
  // clear the solution vectors
  for (unsigned int i=0; i <= order; i++)
    this->current_solution[i]->zero();
  // return control back to the solver
}
void Driver::NonlinearTransientAnalysisDriver::getResidualVector (const double time, std::vector< NumericVector< double > * > & vecs, NumericVector< double > & res)
calculates the nonlinear residual at the specified time and solution vectors specified in vecs
Definition at line 1089 of file TransientAnalysisDriver.C.
References ANALYSIS_ENUM_ID, and SENSITIVITY_ANALYSIS_ENUM_ID.
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  this->current_analysis_time = time;
  unsigned int order = it->second->getTransientSystemOrder();
  Assert(vecs.size() == (order+1), ExcInternalError());
  Assert(this->current_solution.size() == (order+1),ExcInternalError());
  for (unsigned int i=0; i <= order; i++)
    {
      Assert(vecs[i] != NULL, ExcInternalError());
      this->current_solution[i]->zero();
      vecs[i]->close();
      this->localizeSolution(it->second->getAnalysisDofMap(), *(vecs[i]),
                              *(this->current_solution[i]));
      this->current_solution[i]->close();
    }
  vec.zero();
  // create a map of the matrices to be requested from the system
  std::map<unsigned int, double> real_map;
  std::map<unsigned int, SparseMatrix<double>*> matrix_map;
  std::map<unsigned int, NumericVector<double>*> vector_map;
  switch (this->current_analysis_kind_enum_ID)
  {
    case ANALYSIS_ENUM_ID:
    {
      SparseMatrix<double>& scratch_matrix = this->getMatrix("ScratchMatrix");
      NumericVector<double>& scratch_vec1 = this->getVector("ScratchVector1");
      double time_step = dynamic_cast<Solver::TransientSolverBase*>(this->solver)->getTimeStepSize();
      unsigned int qty_enum_ID = 0;
      for (unsigned int i=0; i<= order; i++)
        {
          switch (i)
          {
            case 0:
              qty_enum_ID = Driver::SYSTEM_MATRIX::num();
              break;
            case 1:
              qty_enum_ID = Driver::TRANSIENT_C1_MATRIX::num();
              break;
            case 2:
              qty_enum_ID = Driver::TRANSIENT_C2_MATRIX::num();
              break;
            default:
              Assert(false, ExcInternalError());
          }
          // if the matrix for this order exists, then process it, else go to the
          // next order
          if (it->second->disciplineHasMatrix(qty_enum_ID))
            {
              // get the matrix and the solution
              matrix_map.clear();
              matrix_map[qty_enum_ID] = &scratch_matrix;
              scratch_matrix.zero();
              scratch_matrix.perform_intermediate_matrix_assembly();
              it->second->fillQuantity(real_map, matrix_map, vector_map);
              // apply the boundary conditions to this matrix
              scratch_matrix.close();
              this->applyBoundaryConditionsToMatrixForCurrentAnalysis(scratch_matrix,
                                                                      pow(time_step, i), it->second->getDisciplineEnumID());
              scratch_matrix.close();
              scratch_vec1.zero();
              scratch_vec1.close();
              scratch_matrix.multiply_vector(*(vecs[i]), scratch_vec1);
              scratch_vec1.close();
              vec.add(1.0, scratch_vec1);
              vec.perform_intermediate_vector_assembly();
            }
        }
      scratch_vec1.zero();
      scratch_vec1.close();
      matrix_map.clear();
      vector_map.clear();
      vector_map[Driver::FORCE_VECTOR::num()] = &scratch_vec1;
      it->second->fillQuantity(real_map, matrix_map, vector_map);
      scratch_vec1.close();
      this->applyBoundaryConditionsToVectorForCurrentAnalysis(scratch_vec1, true, it->second->getDisciplineEnumID());
      scratch_vec1.close();
      vec.add(-1.0, scratch_vec1);
      vec.close();
      // this has been temporarily removed to check the approach to application of
      // dirichlet BCs. The BCs are applied to the coefficient matrices instead of this
      //       this->applyBoundaryConditionsToVectorForCurrentAnalysis(vec, false);
    }
      break;
    case SENSITIVITY_ANALYSIS_ENUM_ID:
    default:
      Assert(false, ExcInternalError());
  }
  // clear the solution vectors
  for (unsigned int i=0; i <= order; i++)
    this->current_solution[i]->zero();
  // return control back to the solver
}
void Driver::NonlinearTransientAnalysisDriver::initialize () [protected, virtual]
this method initializes itself before the solutions are started for the driver
Implements Driver::AnalysisDriver.
Definition at line 625 of file TransientAnalysisDriver.C.
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  // now resize the current solution vector
  Assert(this->current_solution.size() == 0,ExcInternalError());
  this->current_solution.resize(it->second->getTransientSystemOrder()+1);
  for (unsigned int i=0; i < this->current_solution.size(); i++)
    {
      this->current_solution.reset(i, NumericVector<double>::build().release());
      this->current_solution[i]->init(it->second->getAnalysisDofMap().n_dofs());
    }
  // add the matrices and vectors
  this->addMatricesAndVectors();
}
void Driver::NonlinearTransientAnalysisDriver::solveCurrentLoadCase () [protected, virtual]
this method solves for the current load case
Implements Driver::AnalysisDriver.
Definition at line 705 of file TransientAnalysisDriver.C.
References ANALYSIS_ENUM_ID, FESystemUtility::AutoPtrVector< T >::clear(), FESystemNumerics::PetscVectorBase< T >::el(), FESystemUtility::AutoPtrVector< T >::getReference(), FESystem::local_processor, FESystemUtility::AutoPtrVector< T >::reset(), FESystemNumerics::PetscSeqVector< T >::resize(), SENSITIVITY_ANALYSIS_ENUM_ID, FESystemNumerics::PetscVectorBase< T >::set(), FESystemDatabase::GenericDataInfoBase::setDisciplineEnumID(), FESystemDatabase::GenericDataInfoBase::setLoadCase(), FESystemDatabase::GenericDataInfoBase::setName(), and FESystemNumerics::PetscVectorBase< T >::size().
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  unsigned int order = it->second->getTransientSystemOrder();
  Assert(order > 0, ExcInternalError());
  // make sure that the solver is the right kind
  Assert(this->solver != NULL, ExcInternalError());
  switch (this->current_analysis_kind_enum_ID)
  {
    case ANALYSIS_ENUM_ID:
    {
      Assert(this->time_values.size() == 0, ExcInternalError());
      Assert(this->solver->getSolverClassEnumID() ==
             Solver::NONLINEAR_TRANSIENT_SOLVER::num(), ExcInternalError());
      Solver::NonlinearTransientSolverBase* nonlinear_transient_solver =
      dynamic_cast<Solver::NonlinearTransientSolverBase*>(this->solver);
      FESystemUtility::AutoPtrVector<NumericVector<double> > vecs(order);
      std::auto_ptr<NumericVector<double> > vec_ptr;
      for (unsigned int i=0; i < order; i++)
        {
          // create a vector for the initial conditions, and init it to the
          // dof distribution of the discipline
          vec_ptr.reset(NumericVector<double>::build().release());
          it->second->initVector(*vec_ptr);
          vecs.reset(i, vec_ptr.release());
        }
      this->setInitialConditionForCurrentLoadCase(vecs.getReference());
      nonlinear_transient_solver->setInitialCondition(vecs.getReference());
      SparseMatrix<double>& jac_matrix = this->getMatrix(Driver::JACOBIAN_MATRIX::name());
      jac_matrix.zero();
      nonlinear_transient_solver->attachJacobianMatrix(jac_matrix);
      // now clear the vectors, since they are not needed anymore
      vecs.clear();
      // create a vector of system matrices to be given to the solver
      std::vector<SparseMatrix<double>*> mat_vec(order+1);
      switch (order)
      {
        case 2:
        {
          if (it->second->disciplineHasMatrix(Driver::TRANSIENT_C2_MATRIX::num()))
            {
              mat_vec[2] = &(this->getMatrix(Driver::TRANSIENT_C2_MATRIX::name()));
              mat_vec[2]->zero();
            }
          else
            mat_vec[2] = NULL;
        }
        case 1:
        {
          if (it->second->disciplineHasMatrix(Driver::TRANSIENT_C1_MATRIX::num()))
            {
              mat_vec[1] = &(this->getMatrix(Driver::TRANSIENT_C1_MATRIX::name()));
              mat_vec[1]->zero();
            }
          else
            mat_vec[1] = NULL;
          if (it->second->disciplineHasMatrix(Driver::SYSTEM_MATRIX::num()))
            {
              mat_vec[0] = &(this->getMatrix(Driver::SYSTEM_MATRIX::name()));
              mat_vec[0]->zero();
            }
          else
            mat_vec[0] = NULL;
        }
          break;
        default:
          Assert(false, ExcInternalError());
      }
      nonlinear_transient_solver->attachCoefficientMatrices(mat_vec);
      // now that the matrices have been set and initialized, solve the system
      nonlinear_transient_solver->solve();
      // after the solution, store the time values at which solution was obtained
      if (FESystem::local_processor == 0)
        {
          FESystemDatabase::TimeIndependentDataInfo data_info;
          data_info.setDisciplineEnumID(it->second->getDisciplineEnumID());
          data_info.setName("TimeValues");
          data_info.setLoadCase(this->current_load_case);
          FESystemNumerics::PetscSeqVector<double> vec(this->time_values.size());
          for (unsigned int i=0; i < this->time_values.size(); i++)
            vec.set(i, this->time_values[i]);
          this->fesystem_controller.global_data_storage->storeVector(data_info, vec);
        }
    }
      break;
    case SENSITIVITY_ANALYSIS_ENUM_ID:
    {
      // the time values should already be available. If not, load them from disc
      if (this->time_values.size() == 0)
        {
          FESystemDatabase::TimeIndependentDataInfo data_info;
          data_info.setDisciplineEnumID(it->second->getDisciplineEnumID());
          data_info.setName("TimeValues");
          data_info.setLoadCase(this->current_load_case);
          FESystemNumerics::PetscSeqVector<double> vec;
          this->fesystem_controller.global_data_storage->fillVector(data_info, vec);
          this->time_values.resize(vec.size());
          for (unsigned int i=0; i < vec.size(); i++)
            this->time_values[i] = vec.el(i);
        }
      // get a pointer to the solver, and make sure it is of the right kind
      Assert(this->solver->getSolverClassEnumID() ==
             Solver::LINEAR_TRANSIENT_SOLVER::num(), ExcInternalError());
      Solver::LinearTransientSolverBase* linear_transient_solver =
      dynamic_cast<Solver::LinearTransientSolverBase*>(this->solver);
      FESystemUtility::AutoPtrVector<NumericVector<double> > vecs(order);
      std::auto_ptr<NumericVector<double> > vec_ptr;
      for (unsigned int i=0; i < order; i++)
        {
          // create a vector for the initial conditions, and init it to the
          // dof distribution of the discipline
          vec_ptr.reset(NumericVector<double>::build().release());
          it->second->initVector(*vec_ptr);
          vecs.reset(i, vec_ptr.release());
        }
      // all sensitivity analysis solutions are assumed to have a zero
      // initial condition
      this->setInitialConditionForCurrentLoadCase(vecs.getReference());
      linear_transient_solver->setInitialCondition(vecs.getReference());
      // now clear the vectors, since they are not needed anymore
      vecs.clear();
      // create a vector of system matrices to be given to the solver
      std::vector<SparseMatrix<double>*> mat_vec(order+1);
      // create the matrices and attach them to the solver
      switch (order)
      {
        case 2:
        {
          if (it->second->disciplineHasMatrix(Driver::TRANSIENT_C2_MATRIX::num()))
            {
              mat_vec[2] = &(this->getMatrix(Driver::TRANSIENT_C2_MATRIX::name()));
              mat_vec[2]->zero();
            }
          else
            mat_vec[2] = NULL;
        }
        case 1:
        {
          if (it->second->disciplineHasMatrix(Driver::TRANSIENT_C1_MATRIX::num()))
            {
              mat_vec[1] = &(this->getMatrix(Driver::TRANSIENT_C1_MATRIX::name()));
              mat_vec[1]->zero();
            }
          else
            mat_vec[1] = NULL;
          if (it->second->disciplineHasMatrix(Driver::SYSTEM_MATRIX::num()))
            {
              mat_vec[0] = &(this->getMatrix(Driver::SYSTEM_MATRIX::name()));
              mat_vec[0]->zero();
            }
          else
            mat_vec[0] = NULL;
        }
          break;
        default:
          Assert(false, ExcInternalError());
      }
      linear_transient_solver->attachCoefficientMatrices(mat_vec);
      // now that the matrices have been set and initialized, solve the system
      linear_transient_solver->solve();
    }
      break;
    default:
      abort();
      break;
  }
}
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/AnalysisDriver/TransientAnalysisDriver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/AnalysisDriver/TransientAnalysisDriver.C