fesystem: Isotropic1D_ElemDataCard Class Reference
Isotropic1D_ElemDataCard Class Reference
#include <Isotropic1DElemDataCard.h>
Public Member Functions
Isotropic1D_ElemDataCard ()
virtual ~Isotropic1D_ElemDataCard ()
virtual unsigned int getPropertyCardKindEnumID () const
virtual const std::string getPropertyCardKindEnumName () const
virtual void getFactor (double &factor, const unsigned int factor_enum_ID)
returns the value of the factor
virtual void getFactorSensitivityForGlobalParameter (double &factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID)
virtual void getFactorSensitivityForLocalParameter (double &factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID)
virtual void getFactor (DenseMatrix< double > &factor, const unsigned int factor_enum_ID)
returns the value of the factor
virtual void getFactorSensitivityForGlobalParameter (DenseMatrix< double > &factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID)
virtual void getFactorSensitivityForLocalParameter (DenseMatrix< double > &factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID)
Protected Member Functions
virtual std::string getPropertyEnumName (const unsigned int enum_ID) const
virtual const unsigned int getPropertyEnumID (const std::string &enum_name) const
Friends
std::istream & operator>> (std::istream &input, Isotropic1D_ElemDataCard &line_elem)
Detailed Description
Definition at line 230 of file Isotropic1DElemDataCard.h.
Constructor & Destructor Documentation
Isotropic1D_ElemDataCard::Isotropic1D_ElemDataCard ()
Definition at line 8 of file Isotropic1DElemDataCard.C.
                                                  :
IsotropicElemDataCard()
{
}
Isotropic1D_ElemDataCard::~Isotropic1D_ElemDataCard () [virtual]
Definition at line 17 of file Isotropic1DElemDataCard.C.
{
}
Member Function Documentation
void Isotropic1D_ElemDataCard::getFactor (double & factor, const unsigned int factor_enum_ID) [inline, virtual]
returns the value of the factor
Implements ElemDataCard.
Definition at line 302 of file Isotropic1DElemDataCard.h.
References EA_FACTOR_ENUM_ID, EIYY_FACTOR_ENUM_ID, EIZZ_FACTOR_ENUM_ID, GA_FACTOR_ENUM_ID, IsotropicElemDataCard::getMaterialCard(), Property::PropertyCard< double >::getPropertyValue(), MASS_FACTOR_ENUM_ID, DENSITY::num(), SPECIFIC_HEAT::num(), ALPHA_EXPANSION::num(), THERMAL_CONDUCTIVITY::num(), YOUNGS_MODULUS::num(), POISSONS_RATIO::num(), EMISSIVITY::num(), THERMAL_CAPACITANCE_FACTOR_ENUM_ID, THERMAL_CONDUCTANCE_FACTOR_ENUM_ID, THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID, and THERMAL_EXPANSION_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& property =this->getMaterialCard();
  factor = 0.0;
  static double val1, val2, val3;
  val1 = 0.0; val2 = 0.0; val3 = 0.0;
  switch (factor_enum_ID)
    {
    case EA_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        factor = val1*val2;
      }
      break;
    case MASS_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(DENSITY::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        factor = val1*val2;
      }
      break;
    case THERMAL_EXPANSION_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        property.getPropertyValue(ALPHA_EXPANSION::num(), val3);
        this->getPropertyValue(AREA::num(), val2);
        factor = val1*val2*val3;
      }
      break;
    case GA_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        property.getPropertyValue(POISSONS_RATIO::num(), val3);
        this->getPropertyValue(AREA::num(), val2);
        factor = (val1/ 2.0 / (1.0 + val3) ) * val2;
      }
      break;
    case EIZZ_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        this->getPropertyValue(IZZ::num(), val2);
        factor = val1*val2;
      }
      break;
    case EIYY_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        this->getPropertyValue(IYY::num(), val2);
        factor = val1*val2;
      }
      break;
    case THERMAL_CAPACITANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(DENSITY::num(), val1);
        property.getPropertyValue(SPECIFIC_HEAT::num(), val2);
        this->getPropertyValue(AREA::num(), val3);
        factor = val1 * val2 * val3;
      }
      break;
    case THERMAL_CONDUCTANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(THERMAL_CONDUCTIVITY::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        factor = val1 * val2;
      }
      break;
    case THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(EMISSIVITY::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        factor = val1 * val2;
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
void Isotropic1D_ElemDataCard::getFactor (DenseMatrix< double > & factor, const unsigned int factor_enum_ID) [virtual]
returns the value of the factor
Implements ElemDataCard.
Definition at line 35 of file Isotropic1DElemDataCard.C.
{
  // params not used
  (void) factor;
  (void) factor_enum_ID;
  Assert(false, ExcPureFunctionCalled());
}
void Isotropic1D_ElemDataCard::getFactorSensitivityForGlobalParameter (double & factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID) [inline, virtual]
Implements ElemDataCard.
Definition at line 408 of file Isotropic1DElemDataCard.h.
References EA_FACTOR_ENUM_ID, EIYY_FACTOR_ENUM_ID, EIZZ_FACTOR_ENUM_ID, G(), GA_FACTOR_ENUM_ID, MASS_FACTOR_ENUM_ID, DENSITY::num(), SPECIFIC_HEAT::num(), ALPHA_EXPANSION::num(), THERMAL_CONDUCTIVITY::num(), YOUNGS_MODULUS::num(), POISSONS_RATIO::num(), EMISSIVITY::num(), THERMAL_CAPACITANCE_FACTOR_ENUM_ID, THERMAL_CONDUCTANCE_FACTOR_ENUM_ID, THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID, and THERMAL_EXPANSION_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& property =this->getMaterialCard();
  factor = 0.0;
  static double val1, val2, val3, val1_sens, val2_sens, val3_sens;
  val1 = 0.0; val2 = 0.0; val3 = 0.0; val1_sens = 0.0; val2_sens = 0.0; val3_sens = 0.0;
  switch (factor_enum_ID)
    {
    case EA_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForGlobalParameter(YOUNGS_MODULUS::num(),
                                                         global_param_ID,
                                                         val1_sens);
        this->getPropertyDerivativeForGlobalParameter(AREA::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case MASS_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(DENSITY::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForGlobalParameter(DENSITY::num(),
                                                         global_param_ID,
                                                         val1_sens);
        this->getPropertyDerivativeForGlobalParameter(AREA::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case THERMAL_EXPANSION_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        property.getPropertyValue(ALPHA_EXPANSION::num(), val3);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForGlobalParameter(YOUNGS_MODULUS::num(),
                                                         global_param_ID,
                                                         val1_sens);
        property.getPropertyDerivativeForGlobalParameter(ALPHA_EXPANSION::num(),
                                                         global_param_ID,
                                                         val3_sens);
        this->getPropertyDerivativeForGlobalParameter(AREA::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1_sens * val2 * val3 +
          val1 * val2_sens * val3 + val1 * val2 * val3_sens ;
      }
      break;
    case GA_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        property.getPropertyValue(POISSONS_RATIO::num(), val3);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForGlobalParameter(YOUNGS_MODULUS::num(),
                                                         global_param_ID,
                                                         val1_sens);
        property.getPropertyDerivativeForGlobalParameter(POISSONS_RATIO::num(),
                                                         global_param_ID,
                                                         val3_sens);
        this->getPropertyDerivativeForGlobalParameter(AREA::num(),
                                                      global_param_ID,
                                                      val2_sens);
        static double G, G_sens;
        G = val1 / 2.0 / (1.0 + val3);
        G_sens = (val1_sens * (1.0 + val3) - val1 * val3_sens)/
          (1.0 + val3) / (1.0 + val3);
        factor = G * val2_sens + G_sens * val2;
      }
      break;
    case EIZZ_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        this->getPropertyValue(IZZ::num(), val2);
        property.getPropertyDerivativeForGlobalParameter(YOUNGS_MODULUS::num(),
                                                         global_param_ID,
                                                         val1_sens);
        this->getPropertyDerivativeForGlobalParameter(IZZ::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case EIYY_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        this->getPropertyValue(IYY::num(), val2);
        property.getPropertyDerivativeForGlobalParameter(YOUNGS_MODULUS::num(),
                                                         global_param_ID,
                                                         val1_sens);
        this->getPropertyDerivativeForGlobalParameter(IYY::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case THERMAL_CAPACITANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(SPECIFIC_HEAT::num(), val1);
        property.getPropertyValue(DENSITY::num(), val2);
        this->getPropertyValue(AREA::num(), val3);
        property.getPropertyDerivativeForGlobalParameter(SPECIFIC_HEAT::num(),
                                                         global_param_ID,
                                                         val1_sens);
        property.getPropertyDerivativeForGlobalParameter(DENSITY::num(),
                                                         global_param_ID,
                                                         val2_sens);
        this->getPropertyDerivativeForGlobalParameter(AREA::num(),
                                                      global_param_ID,
                                                      val3_sens);
        factor = val1_sens * val2 * val3 +
          val1 * val2_sens * val3 + val1 * val2 * val3_sens;
      }
      break;
    case THERMAL_CONDUCTANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(THERMAL_CONDUCTIVITY::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForGlobalParameter(THERMAL_CONDUCTIVITY::num(),
                                                        global_param_ID,
                                                        val1_sens);
        this->getPropertyDerivativeForGlobalParameter(AREA::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(EMISSIVITY::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForGlobalParameter(EMISSIVITY::num(),
                                                         global_param_ID,
                                                         val1_sens);
        this->getPropertyDerivativeForGlobalParameter(AREA::num(),
                                                      global_param_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
void Isotropic1D_ElemDataCard::getFactorSensitivityForGlobalParameter (DenseMatrix< double > & factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID) [virtual]
Implements ElemDataCard.
Definition at line 49 of file Isotropic1DElemDataCard.C.
{
  // params not used
  (void) factor;
  (void) factor_enum_ID;
  (void) global_param_ID;
  Assert(false, ExcPureFunctionCalled());
}
void Isotropic1D_ElemDataCard::getFactorSensitivityForLocalParameter (double & factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID) [inline, virtual]
Implements ElemDataCard.
Definition at line 596 of file Isotropic1DElemDataCard.h.
References EA_FACTOR_ENUM_ID, EIYY_FACTOR_ENUM_ID, EIZZ_FACTOR_ENUM_ID, G(), GA_FACTOR_ENUM_ID, MASS_FACTOR_ENUM_ID, DENSITY::num(), SPECIFIC_HEAT::num(), ALPHA_EXPANSION::num(), THERMAL_CONDUCTIVITY::num(), YOUNGS_MODULUS::num(), POISSONS_RATIO::num(), EMISSIVITY::num(), THERMAL_CAPACITANCE_FACTOR_ENUM_ID, THERMAL_CONDUCTANCE_FACTOR_ENUM_ID, THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID, and THERMAL_EXPANSION_FACTOR_ENUM_ID.
{
  Property::PropertyCard<double>& property =this->getMaterialCard();
  factor = 0.0;
  static double val1, val2, val3, val1_sens, val2_sens, val3_sens;
  val1 = 0.0; val2 = 0.0; val3 = 0.0; val1_sens = 0.0; val2_sens = 0.0; val3_sens = 0.0;
  switch (factor_enum_ID)
    {
    case EA_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForLocalParameter(YOUNGS_MODULUS::num(),
                                                         param_enum_ID,
                                                         val1_sens);
        this->getPropertyDerivativeForLocalParameter(AREA::num(),
                                                      param_enum_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case MASS_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(DENSITY::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForLocalParameter(DENSITY::num(),
                                                        param_enum_ID,
                                                        val1_sens);
        this->getPropertyDerivativeForLocalParameter(AREA::num(),
                                                     param_enum_ID,
                                                     val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case THERMAL_EXPANSION_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        property.getPropertyValue(ALPHA_EXPANSION::num(), val3);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForLocalParameter(YOUNGS_MODULUS::num(),
                                                         param_enum_ID,
                                                         val1_sens);
        property.getPropertyDerivativeForLocalParameter(ALPHA_EXPANSION::num(),
                                                         param_enum_ID,
                                                         val3_sens);
        this->getPropertyDerivativeForLocalParameter(AREA::num(),
                                                      param_enum_ID,
                                                      val2_sens);
        factor = val1_sens * val2 * val3 +
          val1 * val2_sens * val3 + val1 * val2 * val3_sens ;
      }
      break;
    case GA_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        property.getPropertyValue(POISSONS_RATIO::num(), val3);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForLocalParameter(YOUNGS_MODULUS::num(),
                                                         param_enum_ID,
                                                         val1_sens);
        property.getPropertyDerivativeForLocalParameter(POISSONS_RATIO::num(),
                                                         param_enum_ID,
                                                         val3_sens);
        this->getPropertyDerivativeForLocalParameter(AREA::num(),
                                                      param_enum_ID,
                                                      val2_sens);
        static double G, G_sens;
        G = val1 / 2.0 / (1.0 + val3);
        G_sens = (val1_sens * (1.0 + val3) - val1 * val3_sens)/
          (1.0 + val3) / (1.0 + val3);
        factor = G * val2_sens + G_sens * val2;
      }
      break;
    case EIZZ_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        this->getPropertyValue(IZZ::num(), val2);
        property.getPropertyDerivativeForLocalParameter(YOUNGS_MODULUS::num(),
                                                         param_enum_ID,
                                                         val1_sens);
        this->getPropertyDerivativeForLocalParameter(IZZ::num(),
                                                      param_enum_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case EIYY_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(YOUNGS_MODULUS::num(), val1);
        this->getPropertyValue(IYY::num(), val2);
        property.getPropertyDerivativeForLocalParameter(YOUNGS_MODULUS::num(),
                                                         param_enum_ID,
                                                         val1_sens);
        this->getPropertyDerivativeForLocalParameter(IYY::num(),
                                                      param_enum_ID,
                                                      val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case THERMAL_CAPACITANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(SPECIFIC_HEAT::num(), val1);
        property.getPropertyValue(DENSITY::num(), val2);
        this->getPropertyValue(AREA::num(), val3);
        property.getPropertyDerivativeForLocalParameter(SPECIFIC_HEAT::num(),
                                                         param_enum_ID,
                                                         val1_sens);
        property.getPropertyDerivativeForLocalParameter(DENSITY::num(),
                                                         param_enum_ID,
                                                         val2_sens);
        this->getPropertyDerivativeForLocalParameter(AREA::num(),
                                                      param_enum_ID,
                                                      val3_sens);
        factor = val1_sens * val2 * val3 +
          val1 * val2_sens * val3 + val1 * val2 * val3_sens;
      }
      break;
    case THERMAL_CONDUCTANCE_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(THERMAL_CONDUCTIVITY::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForLocalParameter(THERMAL_CONDUCTIVITY::num(),
                                                        param_enum_ID,
                                                        val1_sens);
        this->getPropertyDerivativeForLocalParameter(AREA::num(),
                                                     param_enum_ID,
                                                     val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    case THERMAL_EMITTED_LOAD_FACTOR_ENUM_ID:
      {
        property.getPropertyValue(EMISSIVITY::num(), val1);
        this->getPropertyValue(AREA::num(), val2);
        property.getPropertyDerivativeForLocalParameter(EMISSIVITY::num(),
                                                        param_enum_ID,
                                                        val1_sens);
        this->getPropertyDerivativeForLocalParameter(AREA::num(),
                                                     param_enum_ID,
                                                     val2_sens);
        factor = val1 * val2_sens + val1_sens * val2;
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (ElemDataCardFactorsEnum::enumName(factor_enum_ID)));
    }
}
void Isotropic1D_ElemDataCard::getFactorSensitivityForLocalParameter (DenseMatrix< double > & factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID) [virtual]
Implements ElemDataCard.
Definition at line 64 of file Isotropic1DElemDataCard.C.
{
  // params not used
  (void) factor;
  (void) factor_enum_ID;
  (void) param_enum_ID;
  Assert(false, ExcPureFunctionCalled());
}
unsigned int Isotropic1D_ElemDataCard::getPropertyCardKindEnumID () const [inline, virtual]
Returns:
the property card kind enumeration ID
Implements Property::PropertyCardBase.
Definition at line 281 of file Isotropic1DElemDataCard.h.
{
  return ISOTROPIC_1D_ELEM_DATA_CARD::num();
}
const std::string Isotropic1D_ElemDataCard::getPropertyCardKindEnumName () const [inline, virtual]
Returns:
the property card kind enumeration name
Implements Property::PropertyCardBase.
Definition at line 292 of file Isotropic1DElemDataCard.h.
{
  return ISOTROPIC_1D_ELEM_DATA_CARD::name();
}
const unsigned int Isotropic1D_ElemDataCard::getPropertyEnumID (const std::string & enum_name) const [inline, protected, virtual]
Returns:
the property ID from enumeration name of the property
Implements Property::PropertyCard< double >.
Definition at line 795 of file Isotropic1DElemDataCard.h.
{
  return Isotropic_1D_ElemDataEnum::enumID(enum_name);
}
std::string Isotropic1D_ElemDataCard::getPropertyEnumName (const unsigned int enum_ID) const [inline, protected, virtual]
Returns:
the property name from enumeration ID of the property
Implements Property::PropertyCard< double >.
Definition at line 786 of file Isotropic1DElemDataCard.h.
{
  return Isotropic_1D_ElemDataEnum::enumName(enum_ID);
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, Isotropic1D_ElemDataCard & line_elem) [friend]
Definition at line 28 of file Isotropic1DElemDataCard.C.
{
  return line_elem.readFromInputStream(input);
}
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/Isotropic1DElemDataCard.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/Isotropic1DElemDataCard.C