fesystem: Loads::VolumeLoadCombination Class Reference
Loads::VolumeLoadCombination Class Reference
#include <LoadCombination.h>
Public Member Functions
VolumeLoadCombination ()
virtual ~VolumeLoadCombination ()
virtual unsigned int nLoads () const
unsigned int getElemID () const
virtual void addLoad (const double factor, const VolumeLoad *load_ptr)=0
Protected Attributes
std::set< const VolumeLoad * > load_set
Detailed Description
Definition at line 398 of file LoadCombination.h.
Constructor & Destructor Documentation
Loads::VolumeLoadCombination::VolumeLoadCombination () [inline]
Definition at line 401 of file LoadCombination.h.
                             :
      LoadCombinationBase()
      {
      }
virtual Loads::VolumeLoadCombination::~VolumeLoadCombination () [inline, virtual]
Definition at line 407 of file LoadCombination.h.
      {
      }
Member Function Documentation
virtual void Loads::VolumeLoadCombination::addLoad (const double factor, const VolumeLoad * load_ptr) [pure virtual]
Implemented in Loads::ScalarVolumeLoadCombination.
unsigned int Loads::VolumeLoadCombination::getElemID () const [inline]
Definition at line 422 of file LoadCombination.h.
References load_set, and nLoads().
Referenced by Loads::ScalarVolumeLoadCombination::addLoad().
      {
        Assert(this->nLoads() > 0, ExcInternalError());
        return (*this->load_set.begin())->getElemID();
      }
virtual unsigned int Loads::VolumeLoadCombination::nLoads () const [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 417 of file LoadCombination.h.
References load_set.
Referenced by Loads::ScalarVolumeLoadCombination::addLoad(), getElemID(), and Discipline::AnalysisDisciplineBase::getElemLoads().
      {
        return this->load_set.size();
      }
Member Data Documentation
std::set<const VolumeLoad*> Loads::VolumeLoadCombination::load_set [protected]
Definition at line 432 of file LoadCombination.h.
Referenced by Loads::ScalarVolumeLoadCombination::addLoad(), Loads::ScalarVolumeLoadCombination::clear(), getElemID(), and nLoads().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCombination.h