fesystem: Solver::NewmarkNonlinearTransientSolverInfo Class Reference
Solver::NewmarkNonlinearTransientSolverInfo Class Reference
this is a class specifically for linear transient solvers
#include <NewmarkTransientSolverInfo.h>
Public Member Functions
NewmarkNonlinearTransientSolverInfo ()
constructor
~NewmarkNonlinearTransientSolverInfo ()
destructor
unsigned int getSystemOrder () const
double getConstant (const unsigned int order) const
virtual std::istream & readFromInputStream (std::istream &input)
reads from input
Protected Attributes
unsigned int order
order of the system
std::vector< double > constant_vals
vector of constants
Friends
std::istream & operator>> (std::istream &input, Solver::NewmarkNonlinearTransientSolverInfo &info)
overloaded input stream operator
Detailed Description
this is a class specifically for linear transient solvers
Definition at line 88 of file NewmarkTransientSolverInfo.h.
Constructor & Destructor Documentation
Solver::NewmarkNonlinearTransientSolverInfo::NewmarkNonlinearTransientSolverInfo ()
constructor
Definition at line 96 of file NewmarkTransientSolverInfo.C.
                                                                              :
Solver::NonlinearTransientSolverInfo(Solver::NEWMARK_NONLINEAR_TRANSIENT_SOLVER_INFO::num(),
                                     Solver::NONLINEAR_TRANSIENT_SOLVER::num()),
order(FESystemNumbers::InvalidID)
{
}
Solver::NewmarkNonlinearTransientSolverInfo::~NewmarkNonlinearTransientSolverInfo ()
destructor
Definition at line 105 of file NewmarkTransientSolverInfo.C.
{
}
Member Function Documentation
double Solver::NewmarkNonlinearTransientSolverInfo::getConstant (const unsigned int order) const
Returns:
the constant for the given order of time derivative
Definition at line 121 of file NewmarkTransientSolverInfo.C.
References FESystemNumbers::InvalidID.
{
  Assert(i < this->getSystemOrder() != FESystemNumbers::InvalidID, ExcInternalError());
  Assert(this->constant_vals.size() == this->getSystemOrder(), ExcInternalError());
  return this->constant_vals[i];
}
unsigned int Solver::NewmarkNonlinearTransientSolverInfo::getSystemOrder () const
Returns:
the order of time derivative of this system
Definition at line 112 of file NewmarkTransientSolverInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Solver::NewmarkSolver::getJacobian(), Solver::NewmarkSolver::getResidual(), and Solver::NewmarkNonlinearTransientSolver::solve().
{
  Assert(this->order != FESystemNumbers::InvalidID, ExcInternalError());
  return this->order;
}
std::istream & Solver::NewmarkNonlinearTransientSolverInfo::readFromInputStream (std::istream & input) [virtual]
reads from input
Reimplemented from Solver::NonlinearTransientSolverInfo.
Definition at line 130 of file NewmarkTransientSolverInfo.C.
References FESystemIOUtility::readFromInput().
{
  std::string tag;
  FESystemIOUtility::readFromInput(input, Solver::NEWMARK_NONLINEAR_TRANSIENT_SOLVER_INFO::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->ID);
  this->transient_solver_kind_enum_ID = Solver::NEWMARK_NONLINEAR_TRANSIENT_SOLVER::num();
  FESystemIOUtility::readFromInput(input, "NONLINEAR_SOLVER_INFO_ID", this->nonlinear_solver_info_ID);
  FESystemIOUtility::readFromInput(input, "MAX_ITERATIONS", this->max_iterations);
  FESystemIOUtility::readFromInput(input, "INITIAL_TIME", this->initial_time);
  FESystemIOUtility::readFromInput(input, "TOTAL_DURATION", this->total_duration);
  FESystemIOUtility::readFromInput(input, "IF_ADAPTIVE_SIZE", this->adaptive_step_size);
  FESystemIOUtility::readFromInput(input, "INITIAL_STEP_SIZE", this->initial_step_size);
  FESystemIOUtility::readFromInput(input, "GLOBAL_TOLERANCE", this->global_tolerance);
  FESystemIOUtility::readFromInput(input, "SYSTEM_ORDER", this->order);
  FESystemIOUtility::readFromInput(input, "CONSTANTS");
  this->constant_vals.resize(order);
  for (unsigned int i=0; i < this->order; i++)
    input >> this->constant_vals[i];
  FESystemIOUtility::readFromInput(input, Solver::NEWMARK_NONLINEAR_TRANSIENT_SOLVER_INFO::name());
  FESystemIOUtility::readFromInput(input, "END");
  this->initialized = true;
  return input;
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, Solver::NewmarkNonlinearTransientSolverInfo & info) [friend]
overloaded input stream operator
Member Data Documentation
std::vector<double> Solver::NewmarkNonlinearTransientSolverInfo::constant_vals [protected]
vector of constants
Definition at line 116 of file NewmarkTransientSolverInfo.h.
unsigned int Solver::NewmarkNonlinearTransientSolverInfo::order [protected]
order of the system
Definition at line 113 of file NewmarkTransientSolverInfo.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/NewmarkTransientSolverInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/NewmarkTransientSolverInfo.C