fesystem: Solver::NonlinearTransientSolverBase Class Reference
Solver::NonlinearTransientSolverBase Class Reference
#include <TransientSolver.h>
Public Member Functions
NonlinearTransientSolverBase (const Solver::NonlinearTransientSolverInfo &transient_info, const Solver::NonlinearSolverInfo &nonlinear_info, const Solver::LinearSolverInfo &linear_info)
constructor
virtual ~NonlinearTransientSolverBase ()
virtual void clear ()
void attachJacobianMatrix (SparseMatrix< double > &joc_mat)
this attaches the matrix to be used for jacobian evaluation
void evaluateRHSFunction (const double current_time, NumericVector< double > &sol, NumericVector< double > &res)
void evaluateRHSJacobian (const double current_time, NumericVector< double > &sol, SparseMatrix< double > &jac)
Protected Attributes
const Solver::NonlinearSolverInfo & nonlinear_solver_info
LinearSolverInfo that stores information about this solver.
const Solver::LinearSolverInfo & linear_solver_info
LinearSolverInfo that stores information about this solver.
SparseMatrix< double > * jacobian_matrix
jacobian matrix
Detailed Description
this class provides an interface to a solver for the solution of eigensystem. This inherits from the FESystemSolverBase class. It takes a pointer to the analysis driver object that owns an instantiation of this class
Definition at line 178 of file TransientSolver.h.
Constructor & Destructor Documentation
Solver::NonlinearTransientSolverBase::NonlinearTransientSolverBase (const Solver::NonlinearTransientSolverInfo & transient_info, const Solver::NonlinearSolverInfo & nonlinear_info, const Solver::LinearSolverInfo & linear_info)
constructor
Definition at line 89 of file TransientSolver.C.
                                           :
Solver::TransientSolverBase(dynamic_cast<const Solver::TransientSolverInfoBase&>(transient_info)),
nonlinear_solver_info(nonlinear_info),
linear_solver_info(linear_info),
jacobian_matrix(NULL)
{
}
Solver::NonlinearTransientSolverBase::~NonlinearTransientSolverBase () [virtual]
Definition at line 100 of file TransientSolver.C.
{
}
Member Function Documentation
void Solver::NonlinearTransientSolverBase::attachJacobianMatrix (SparseMatrix< double > & joc_mat)
this attaches the matrix to be used for jacobian evaluation
Definition at line 116 of file TransientSolver.C.
{
  this->jacobian_matrix = &jac_mat;
}
void Solver::NonlinearTransientSolverBase::clear () [virtual]
this method clears the data structures of this object. This should be called each time the used finishes using this object.
Reimplemented from Solver::TransientSolverBase.
Reimplemented in Solver::NewmarkNonlinearTransientSolver, Solver::EulerNonlinearTransientSolver, and Solver::PetscNonlinearTransientSolver.
Definition at line 107 of file TransientSolver.C.
References Solver::TransientSolverBase::clear().
Referenced by Solver::PetscNonlinearTransientSolver::clear(), Solver::EulerNonlinearTransientSolver::clear(), and Solver::NewmarkNonlinearTransientSolver::clear().
{
  this->jacobian_matrix = NULL;
  Solver::TransientSolverBase::clear();
}
void Solver::NonlinearTransientSolverBase::evaluateRHSFunction (const double current_time, NumericVector< double > & sol, NumericVector< double > & res)
evaluates the residual vector at the specified solution
Parameters:
sol vector at which the residual should be evaluated
res vector in which the residual is stored
Referenced by FESystemNonlinearTransientSolverRHSFunctionEvaluation().
void Solver::NonlinearTransientSolverBase::evaluateRHSJacobian (const double current_time, NumericVector< double > & sol, SparseMatrix< double > & jac)
evaluates the residual vector at the specified solution
Parameters:
sol vector at which the residual should be evaluated
jac matrix in which the jacobian is stored
Referenced by FESystemNonlinearTransientSolverRHSJacobianEvaluation().
Member Data Documentation
SparseMatrix<double>* Solver::NonlinearTransientSolverBase::jacobian_matrix [protected]
jacobian matrix
Definition at line 221 of file TransientSolver.h.
const Solver::LinearSolverInfo& Solver::NonlinearTransientSolverBase::linear_solver_info [protected]
LinearSolverInfo that stores information about this solver.
Definition at line 218 of file TransientSolver.h.
const Solver::NonlinearSolverInfo& Solver::NonlinearTransientSolverBase::nonlinear_solver_info [protected]
LinearSolverInfo that stores information about this solver.
Definition at line 215 of file TransientSolver.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/TransientSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/TransientSolver.C