fesystem: FESystemDatabase::GenericDataInfoBase Class Reference
FESystemDatabase::GenericDataInfoBase Class Reference
#include <DataInfo.h>
Public Member Functions
GenericDataInfoBase ()
constructor
GenericDataInfoBase (const GenericDataInfoBase &data_info)
copy constructor
virtual ~GenericDataInfoBase ()
Destructor.
virtual void clear ()
clears the data structures of this object
const std::string & getName () const
virtual const std::string getDisplayName () const =0
bool ifLoadCaseDependent () const
unsigned int getLoadCase () const
void setLoadCase (const unsigned int load_case)
sets the load case value, and also sets to true the boolean value of if_load_case_dependent
bool ifSensitivityData () const
unsigned int getDVID () const
void setDVID (const unsigned int ID)
sets the DV_ID, and also sets to true the boolean value of if_sensitivity
void setName (const std::string &qty_name)
sets the name of the quantity
const std::string & getDisciplineEnumName () const
unsigned int getDisciplineEnumID () const
void setDisciplineEnumID (const unsigned int enum_ID)
sets the discipline enum ID
virtual bool isEqual (const FESystemDatabase::GenericDataInfoBase &data_info) const
virtual std::ostream & write (std::ostream &out)
writes the data info to an output stream
Protected Attributes
unsigned int discipline_enum_ID
enum ID of the discipline
bool if_load_case_dependent
boolean to tell if this quantity is dependent on a load case or not
unsigned int load_case
load case value of the object
bool if_sensitivity
boolean to tell if this is a sensitivity quantity
unsigned int DV_ID
DV ID for this quantitiy if it is a sensitivity quantity.
std::string name
string name of the quantity
Detailed Description
this id the base class for all data info objects. The primary purpose of the data info objects is to give information about a numeric object (matrix/vector) about its kind, the time iteration and time value, nonlinear iteration, etc. and all such details that are necessary to property store the object.
Definition at line 99 of file DataInfo.h.
Constructor & Destructor Documentation
FESystemDatabase::GenericDataInfoBase::GenericDataInfoBase ()
constructor
Definition at line 14 of file DataInfo.C.
References clear().
{
  this->clear();
}
FESystemDatabase::GenericDataInfoBase::GenericDataInfoBase (const GenericDataInfoBase & data_info)
copy constructor
Definition at line 22 of file DataInfo.C.
References discipline_enum_ID, DV_ID, if_load_case_dependent, if_sensitivity, load_case, and name.
{
  this->discipline_enum_ID = data_info.discipline_enum_ID;
  this->if_load_case_dependent = data_info.if_load_case_dependent;
  this->load_case = data_info.load_case;
  this->if_sensitivity = data_info.if_sensitivity;
  this->DV_ID = data_info.DV_ID;
  this->name = data_info.name;
}
FESystemDatabase::GenericDataInfoBase::~GenericDataInfoBase () [virtual]
Destructor.
Definition at line 34 of file DataInfo.C.
{
}
Member Function Documentation
void FESystemDatabase::GenericDataInfoBase::clear () [virtual]
clears the data structures of this object
Reimplemented in FESystemDatabase::TransientDataInfoSet, FESystemDatabase::TimeDependentEigenDataInfo, FESystemDatabase::TimeIndependentEigenDataInfo, and FESystemDatabase::TimeDependentDataInfo.
Definition at line 43 of file DataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by RadiationCavityAnalysis::calculateABInvFactorMatrix(), FESystemDatabase::TimeDependentDataInfo::clear(), FESystemDatabase::TimeIndependentEigenDataInfo::clear(), FESystemDatabase::TransientDataInfoSet::clear(), GenericDataInfoBase(), Discipline::FluidAnalysis::getSolutionVector(), Discipline::StructuralAnalysis::getSolutionVector(), Discipline::ThermalAnalysis::getSolutionVector(), Solution::LinearizedBucklingEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::StructuralVibrationEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Driver::EigenProblemAnalysisDriver::solveCurrentLoadCase(), and Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
{
  this->discipline_enum_ID = FESystemNumbers::InvalidID;
  this->if_load_case_dependent = false;
  this->load_case = FESystemNumbers::InvalidID;
  this->if_sensitivity = false;
  this->DV_ID = FESystemNumbers::InvalidID;
  this->name.clear();
}
unsigned int FESystemDatabase::GenericDataInfoBase::getDisciplineEnumID () const
Returns:
the enum ID of the discipline to which this quantity belongs
Definition at line 147 of file DataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Driver::LinearAnalysisDriver::solveCurrentLoadCase(), Driver::EigenProblemAnalysisDriver::solveCurrentLoadCase(), and Driver::NonLinearAnalysisDriver::solveCurrentLoadCase().
{
  Assert(this->discipline_enum_ID != FESystemNumbers::InvalidID,
         ExcInternalError());
  return this->discipline_enum_ID;
}
const std::string & FESystemDatabase::GenericDataInfoBase::getDisciplineEnumName () const
Returns:
the name of the discipline to which this quantity belongs
Definition at line 158 of file DataInfo.C.
References FESystemNumbers::InvalidID.
{
  Assert(this->discipline_enum_ID != FESystemNumbers::InvalidID,
         ExcInternalError());
  return Discipline::AnalysisDisciplineEnum::enumName(this->discipline_enum_ID);
}
virtual const std::string FESystemDatabase::GenericDataInfoBase::getDisplayName () const [pure virtual]
Implemented in FESystemDatabase::TransientDataInfoSet, FESystemDatabase::TimeDependentEigenDataInfo, FESystemDatabase::TimeIndependentEigenDataInfo, FESystemDatabase::TimeDependentDataInfo, and FESystemDatabase::TimeIndependentDataInfo.
unsigned int FESystemDatabase::GenericDataInfoBase::getDVID () const
Returns:
the DV ID if this is a sensitivity quantity
Definition at line 111 of file DataInfo.C.
{
  // make sure that this is load case dependent. Else, this should not be called
  Assert(this->if_sensitivity, ExcInternalError());
  return this->DV_ID;
}
unsigned int FESystemDatabase::GenericDataInfoBase::getLoadCase () const
Returns:
the load case of the data
Definition at line 75 of file DataInfo.C.
{
  // make sure that this is load case dependent. Else, this should not be called
  Assert(this->if_load_case_dependent, ExcInternalError());
  return this->load_case;
}
const std::string & FESystemDatabase::GenericDataInfoBase::getName () const
Returns:
the name of the quantity with which it is referred
Definition at line 57 of file DataInfo.C.
{
  Assert(this->name != "", ExcInternalError());
  return this->name;
}
bool FESystemDatabase::GenericDataInfoBase::ifLoadCaseDependent () const
Returns:
true if the quantity is load case dependent, else false
Definition at line 66 of file DataInfo.C.
{
  return this->if_load_case_dependent;
}
bool FESystemDatabase::GenericDataInfoBase::ifSensitivityData () const
Returns:
true if the quantity is a sensitivity quantity, else false
Definition at line 102 of file DataInfo.C.
{
  return this->if_sensitivity;
}
bool FESystemDatabase::GenericDataInfoBase::isEqual (const FESystemDatabase::GenericDataInfoBase & data_info) const [virtual]
Returns:
true if the given data info object and this, point to the same data
Definition at line 199 of file DataInfo.C.
References discipline_enum_ID, DV_ID, if_load_case_dependent, if_sensitivity, load_case, and name.
Referenced by FESystemDatabase::DataInfoBase::operator==().
{
  // check each data and return the result
  if (this->discipline_enum_ID != data_info.discipline_enum_ID ||
      this->if_load_case_dependent != data_info.if_load_case_dependent ||
      this->load_case != data_info.load_case ||
      this->if_sensitivity != data_info.if_sensitivity ||
      this->DV_ID  != data_info.DV_ID ||
      this->name != data_info.name)
    return false;
  // if it gets here, means that this the two objects are same
  return true;
}
void FESystemDatabase::GenericDataInfoBase::setDisciplineEnumID (const unsigned int enum_ID)
sets the discipline enum ID
Definition at line 169 of file DataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by RadiationCavityAnalysis::calculateABInvFactorMatrix(), DirectInterpolation::createLoads(), RadiationCavityAnalysis::getBaseEpsilonVector(), Driver::NonlinearTransientAnalysisDriver::getCoefficientMatrices(), FESystemDatabase::TransientDataInfoSet::getDataInfoForAllTimeSteps(), Driver::LinearTransientAnalysisDriver::getForceVector(), Driver::NonlinearTransientAnalysisDriver::getForceVector(), Discipline::ThermalAnalysis::getSolutionVector(), RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector(), Solution::TransientStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::TransientThermalSolution::getTimeDependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::LinearizedBucklingEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::StructuralVibrationEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::ThermalSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::LinearStressSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::AeroelasticitySolution::getTimeIndependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeIndependentNodalSolutionDataInfo(), Driver::UpdatedLagrangianNonlinearStructuralAnalysisDriver::setNewIteration(), Driver::LinearAnalysisDriver::solveCurrentLoadCase(), Driver::EigenProblemAnalysisDriver::solveCurrentLoadCase(), Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase(), Driver::NonLinearAnalysisDriver::solveCurrentLoadCase(), Driver::LinearTransientAnalysisDriver::solveCurrentLoadCase(), and Driver::NonlinearTransientAnalysisDriver::solveCurrentLoadCase().
{
  // make sure that this object has been cleared
  Assert(this->discipline_enum_ID == FESystemNumbers::InvalidID,
         ExcInternalError());
  // make sure that the number is valid
  Assert(enum_ID != FESystemNumbers::InvalidID, ExcInternalError());
  this->discipline_enum_ID = enum_ID;
}
void FESystemDatabase::GenericDataInfoBase::setDVID (const unsigned int ID)
sets the DV_ID, and also sets to true the boolean value of if_sensitivity
Definition at line 122 of file DataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by FESystemDatabase::TransientDataInfoSet::getDataInfoForAllTimeSteps(), Solution::TransientStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::TransientThermalSolution::getTimeDependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::LinearizedBucklingEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::StructuralVibrationEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::ThermalSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::LinearStressSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeIndependentNodalSolutionDataInfo(), Driver::LinearAnalysisDriver::solveCurrentLoadCase(), Driver::EigenProblemAnalysisDriver::solveCurrentLoadCase(), and Driver::NonLinearAnalysisDriver::solveCurrentLoadCase().
{
  // make sure that this object does not have any other DV_ID stored. If it does,
  // the user should have called clear before calling this method
  Assert(! this->if_sensitivity, ExcInternalError());
  Assert(ID != FESystemNumbers::InvalidID, ExcInternalError());
  this->DV_ID = ID;
  this->if_sensitivity = true;
}
void FESystemDatabase::GenericDataInfoBase::setLoadCase (const unsigned int load_case)
sets the load case value, and also sets to true the boolean value of if_load_case_dependent
Definition at line 87 of file DataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by RadiationCavityAnalysis::calculateABInvFactorMatrix(), DirectInterpolation::createLoads(), RadiationCavityAnalysis::getBaseEpsilonVector(), Driver::NonlinearTransientAnalysisDriver::getCoefficientMatrices(), FESystemDatabase::TransientDataInfoSet::getDataInfoForAllTimeSteps(), Driver::LinearTransientAnalysisDriver::getForceVector(), Driver::NonlinearTransientAnalysisDriver::getForceVector(), Discipline::ThermalAnalysis::getSolutionVector(), RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector(), Solution::TransientStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::TransientThermalSolution::getTimeDependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::LinearizedBucklingEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::StructuralVibrationEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::ThermalSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::LinearStressSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::AeroelasticitySolution::getTimeIndependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeIndependentNodalSolutionDataInfo(), Driver::UpdatedLagrangianNonlinearStructuralAnalysisDriver::setNewIteration(), Driver::LinearAnalysisDriver::solveCurrentLoadCase(), Driver::EigenProblemAnalysisDriver::solveCurrentLoadCase(), Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase(), Driver::NonLinearAnalysisDriver::solveCurrentLoadCase(), Driver::LinearTransientAnalysisDriver::solveCurrentLoadCase(), and Driver::NonlinearTransientAnalysisDriver::solveCurrentLoadCase().
{
  // make sure that this object does not have any other load case stored. If it does,
  // the user should have called clear before calling this method
  Assert(! this->if_load_case_dependent, ExcInternalError());
  Assert(lcase != FESystemNumbers::InvalidID, ExcInternalError());
  this->load_case = lcase;
  this->if_load_case_dependent = true;
}
void FESystemDatabase::GenericDataInfoBase::setName (const std::string & qty_name)
sets the name of the quantity
Definition at line 136 of file DataInfo.C.
Referenced by RadiationCavityAnalysis::calculateABInvFactorMatrix(), DirectInterpolation::createLoads(), RadiationCavityAnalysis::getBaseEpsilonVector(), Driver::NonlinearTransientAnalysisDriver::getCoefficientMatrices(), FESystemDatabase::TransientDataInfoSet::getDataInfoForAllTimeSteps(), Discipline::FluidAnalysis::getDataInfoForQty(), Discipline::StructuralAnalysis::getDataInfoForQty(), Discipline::ThermalAnalysis::getDataInfoForQty(), RadiationCavityAnalysis::getDataInfoForQty(), Driver::LinearTransientAnalysisDriver::getForceVector(), Driver::NonlinearTransientAnalysisDriver::getForceVector(), Discipline::FluidAnalysis::getSolutionVector(), Discipline::StructuralAnalysis::getSolutionVector(), Discipline::ThermalAnalysis::getSolutionVector(), RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector(), Solution::TransientStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::TransientThermalSolution::getTimeDependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::ThermalSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::LinearizedBucklingEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::StructuralVibrationEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::LinearStressSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::AeroelasticitySolution::getTimeIndependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeIndependentNodalSolutionDataInfo(), Driver::UpdatedLagrangianNonlinearStructuralAnalysisDriver::setNewIteration(), Driver::LinearAnalysisDriver::solveCurrentLoadCase(), Driver::EigenProblemAnalysisDriver::solveCurrentLoadCase(), Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase(), Driver::NonLinearAnalysisDriver::solveCurrentLoadCase(), Driver::LinearTransientAnalysisDriver::solveCurrentLoadCase(), and Driver::NonlinearTransientAnalysisDriver::solveCurrentLoadCase().
{
  Assert(this->name == "", ExcInternalError());
  Assert(qty_name != "", ExcInternalError());
  this->name = qty_name;
}
std::ostream & FESystemDatabase::GenericDataInfoBase::write (std::ostream & out) [virtual]
writes the data info to an output stream
Reimplemented in FESystemDatabase::TimeDependentEigenDataInfo, FESystemDatabase::TimeIndependentEigenDataInfo, and FESystemDatabase::TimeDependentDataInfo.
Definition at line 183 of file DataInfo.C.
Referenced by FESystemDatabase::TimeDependentDataInfo::write(), and FESystemDatabase::TimeIndependentEigenDataInfo::write().
{
  out << "Discipline :   " << this->getDisciplineEnumName() << std::endl;
  if (this->ifLoadCaseDependent())
    out << "Load Case Number :   " << this->getLoadCase() << std::endl;
  if (this->ifSensitivityData())
    out << "Sensitivity for DV ID :   " << this->getDVID() << std::endl;
  out << "Qty Name :   " << this->getName() << std::endl;
  return out;
}
Member Data Documentation
unsigned int FESystemDatabase::GenericDataInfoBase::discipline_enum_ID [protected]
enum ID of the discipline
Definition at line 162 of file DataInfo.h.
Referenced by GenericDataInfoBase(), and isEqual().
unsigned int FESystemDatabase::GenericDataInfoBase::DV_ID [protected]
DV ID for this quantitiy if it is a sensitivity quantity.
Definition at line 174 of file DataInfo.h.
Referenced by GenericDataInfoBase(), and isEqual().
bool FESystemDatabase::GenericDataInfoBase::if_load_case_dependent [protected]
boolean to tell if this quantity is dependent on a load case or not
Definition at line 165 of file DataInfo.h.
Referenced by GenericDataInfoBase(), and isEqual().
bool FESystemDatabase::GenericDataInfoBase::if_sensitivity [protected]
boolean to tell if this is a sensitivity quantity
Definition at line 171 of file DataInfo.h.
Referenced by GenericDataInfoBase(), and isEqual().
unsigned int FESystemDatabase::GenericDataInfoBase::load_case [protected]
load case value of the object
Definition at line 168 of file DataInfo.h.
Referenced by GenericDataInfoBase(), and isEqual().
std::string FESystemDatabase::GenericDataInfoBase::name [protected]
string name of the quantity
Definition at line 177 of file DataInfo.h.
Referenced by GenericDataInfoBase(), and isEqual().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.C