fesystem: Discipline::AnalysisDisciplineBase Class Reference
Discipline::AnalysisDisciplineBase Class Reference
#include <AnalysisDisciplineBase.h>
Public Member Functions
AnalysisDisciplineBase (FESystem::FESystemController &controller, const Discipline::DisciplineInfo &info)
virtual ~AnalysisDisciplineBase ()
destructor
void clear ()
function to clear all data structures
unsigned int getDisciplineEnumID () const
std::string getDisciplineEnumName () const
void attachSolution (Solution::SolutionBase *sol)
sets the solution kind
const Solution::SolutionBase & getSolution () const
const Discipline::DisciplineInfo & getDisciplineInfo () const
void attachAnalysisDriver (Driver::AnalysisDriver *driver)
attaches an analysis driver to this discipline
virtual std::auto_ptr
< FESystemDatabase::DataInfoBase > getDataInfoForQty (const unsigned int qty_enum_ID)=0
unsigned int getAnalysisTypeEnumID () const
const std::string & getAnalysisTypeEnumName () const
FESystem::FESystemController & getFESystemController ()
Driver::AnalysisDriver & getAnalysisDriver ()
unsigned int getAnalysisMeshID () const
const MeshDS::FEMesh & getAnalysisMesh () const
returns the Mesh for this analysis
const MeshDS::FEMeshData & getAnalysisMeshData () const
returns the MeshData for this analysis
const MeshDS::FEDofMap & getAnalysisDofMap () const
returns the DOFMap object associated with the mesh
const std::set< Elem * > & getAnalysisDummyElemSet () const
returns the dummy elem list
unsigned int getNVars () const
unsigned int getNDofs () const
virtual unsigned int getEigenProblemKindEnumID ()=0
const std::string & getVariableName (const unsigned int i) const
unsigned short int getVariableNumber (const std::string &var) const
const FEType & getVariableType (const unsigned int i) const
const FEType & getVariableType (const std::string &var) const
bool checkPropertyDependenceOnTemperature () const
checks if the analysis is dependent on temperature
virtual std::auto_ptr
< Loads::DirichletBoundaryConditionDataInfo > getBoundaryConditionLoadInfo () const =0
returns the enum ID of the boundary condition for this disicipline
virtual unsigned int getTransientSystemOrder ()=0
virtual bool disciplineHasMatrix (const unsigned int qty_enum_ID) const =0
void fillQuantity (std::map< unsigned int, double > &real_map, std::map< unsigned int, SparseMatrix< double > * > &matrix_map, std::map< unsigned int, NumericVector< double > * > &vector_map)
void calculatePostProcessQty (const std::vector< unsigned int > &load_cases)
Elem * getPerturbedElemForShapeParameter (const unsigned int elem_ID, DesignData::DesignParameter *param)
virtual bool sameSystemMatrixForLoadCases ()=0
virtual void initMatrix (SparseMatrix< double > &mat)
this will initialize the matrix to the sparsity pattern of the discipline's mesh
virtual void initVector (NumericVector< double > &vec)
this will initialize the vector to the sparsity pattern of the discipline's mesh
void getElemDofValues (const Elem *elem, DenseVector< double > &qty, const unsigned int transient_order, const bool sensitivity)
unsigned int nDofs () const
unsigned int nLocalDofs () const
Protected Types
typedef std::map< unsigned int,
FESystemElem::FESystemElemBase * > FESystemElemMap
Protected Member Functions
void addVariable (const std::string &var, const FEType &type)
Adds the variable var to the list of variables in this analysis.
void setNSystemsForDOFObjects ()
set the number of systems for each DOFObject
virtual void addAnalysisVariables ()=0
void addAnalysisVariablesAndInitialize ()
adds variables and distributes the dofs
void getFESystemElem (const unsigned int elem_kind_enum_ID, FESystemElem::FESystemElemBase *&fesys_elem)
virtual void getElemQty (FESystemElem::FESystemElemBase *elem, std::map< unsigned int, double > &real_elem_data, std::map< unsigned int, DenseMatrix< double > > &mat_elem_data, std::map< unsigned int, DenseVector< double > > &vec_elem_data, const bool sensitivity, const unsigned int DV_ID)=0
void calculateGlobalQty (std::map< unsigned int, double > &global_real_data_map, std::map< unsigned int, SparseMatrix< double > * > &global_matrix_data_map, std::map< unsigned int, NumericVector< double > * > &global_vector_data_map, bool sensitivity)
void resizeElemMatricesForElem (FESystemElem::FESystemElemBase *fesys_elem, std::map< unsigned int, DenseMatrix< double > > &elem_matrix_data_map, std::map< unsigned int, DenseVector< double > > &elem_vector_data_map)
this method resizes the matrices and vectors if needed.
void addElemQtyToGlobalData (const Elem *elem, std::map< unsigned int, double > &global_real_data_map, std::map< unsigned int, double > &elem_real_data_map, std::map< unsigned int, SparseMatrix< double > * > &global_matrix_data_map, std::map< unsigned int, DenseMatrix< double > > &elem_matrix_data_map, std::map< unsigned int, NumericVector< double > * > &global_vector_data_map, std::map< unsigned int, DenseVector< double > > &elem_vector_data_map)
void getElemLoads (const unsigned int elem_ID, const Elem *elem, const unsigned int load_case, const bool transient, const double time, const bool sensitivity, const unsigned int DV_ID, const std::map< unsigned int, unsigned int > &volume_loads, const std::map< unsigned int, unsigned int > &surface_loads, const std::map< unsigned int, std::pair< unsigned int, unsigned int > > &nodal_loads, std::map< unsigned int, const Loads::VolumeLoadCombination * > &volume_load_map, std::map< unsigned int, std::map< unsigned int, const Loads::NodalLoadCombination * > > &nodal_load_map, std::map< unsigned int, std::map< unsigned int, const Loads::SurfaceLoadCombination * > > &surface_load_map)
this gets the loads from the load database
virtual const NumericVector
< double > & getSolutionVector (const unsigned int transient_order, const bool sensitivity)=0
virtual bool calculateTransientMatrix (const unsigned int order, bool=false)=0
virtual bool calculateK (bool=false)=0
virtual bool calculateJac ()=0
virtual bool calculateEigenProblemAMatrix (bool sensitivity=false)=0
function to calculate the A matrix for eigen problem analysis
virtual bool calculateEigenProblemBMatrix (bool sensitivity=false)=0
function to calculate the B matrix for eigen problem analysis
virtual bool calculateF (bool=false)=0
virtual void performAdditionalOperationsOnGlobalQuantities (std::map< unsigned int, SparseMatrix< double > * > &matrix_map, std::map< unsigned int, NumericVector< double > * > &vector_map)=0
Protected Attributes
FESystem::FESystemController & fesystem_controller
const Discipline::DisciplineInfo & discipline_info
bool temperature_dependent_property
dependence on temperature
const unsigned int discipline_enum_ID
discipline name enum ID
const unsigned int analysis_type_enum_ID
type of the analysis, i.e. linear, nonlinear
Solution::SolutionBase * solution_base
solution kind enum ID
Driver::AnalysisDriver * analysis_driver
pointer to the analysis driver for this discipline
const unsigned int mesh_ID
ID of mesh.
MeshDS::FEMesh * mesh
mesh data structure
MeshDS::FEMeshData * mesh_data
mesh data data-structure
MeshDS::FEDofMap * dof_map
dof map data-structure
std::set< Elem * > * dummy_element_set
FESystemUtility::LoadedSolution loaded_solution
std::vector< System::Variable * > _variables
The names of the variables associated with this analysis.
FESystemElemMap fesystem_elem_map
Detailed Description
This class provides methods to calculate the matrices and vectors related to the thermal discipline.
Definition at line 164 of file AnalysisDisciplineBase.h.
Member Typedef Documentation
typedef std::map<unsigned int, FESystemElem::FESystemElemBase*> Discipline::AnalysisDisciplineBase::FESystemElemMap [protected]
map of fesystem elements for this discipline. These are initialized using the geometric elements from libMesh to calculate element quantities. The key used here is the element type enum ID.
Definition at line 485 of file AnalysisDisciplineBase.h.
Constructor & Destructor Documentation
Discipline::AnalysisDisciplineBase::AnalysisDisciplineBase (FESystem::FESystemController & controller, const Discipline::DisciplineInfo & info)
constructor. It takes two arguements, first is a reference to the FESystemController that contains the analysis data like the meshlist, propertylist, load-database, etc. and the second is a pointer to the AnalysisDisciplineDriver that owns this object
Definition at line 33 of file AnalysisDisciplineBase.C.
                                      :
fesystem_controller(controller),
discipline_info(info),
temperature_dependent_property(info.checkLocalParameterDependence(Property::TEMPERATURE::num())),
discipline_enum_ID(info.getDisciplineEnumID()),
analysis_type_enum_ID(info.getAnalysisTypeEnumID()),
solution_base(NULL),
analysis_driver(NULL),
mesh_ID(info.getMeshID()),
mesh(NULL),
mesh_data(NULL),
dof_map(NULL),
dummy_element_set(NULL)
{
  this->mesh = this->fesystem_controller.mesh_list->getMeshFromID(this->mesh_ID);
  this->mesh_data = this->fesystem_controller.mesh_list->getMeshDataFromID(this->mesh_ID);
  this->dof_map = this->fesystem_controller.mesh_list->getDofMapFromID(this->mesh_ID);
  this->dummy_element_set = this->fesystem_controller.mesh_list->getDummyElemSetFromID(this->mesh_ID);
}
Discipline::AnalysisDisciplineBase::~AnalysisDisciplineBase () [virtual]
destructor
Definition at line 60 of file AnalysisDisciplineBase.C.
References _variables, and clear().
{
  this->clear();
  // iterate over the variables, and delete them
  std::vector<System::Variable*>::iterator it, end;
  it = this->_variables.begin();
  end = this->_variables.end();
  for ( ; it != end; it++)
    delete *it;
}
Member Function Documentation
virtual void Discipline::AnalysisDisciplineBase::addAnalysisVariables () [protected, pure virtual]
function to add analysis variables. This is an abstract function and will be implemented in the derived class
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
void Discipline::AnalysisDisciplineBase::addAnalysisVariablesAndInitialize () [protected]
adds variables and distributes the dofs
Definition at line 93 of file AnalysisDisciplineBase.C.
Referenced by Discipline::ThermalAnalysis::ThermalAnalysis().
{
  this->fesystem_controller.performance_logging->setEvent
  ("AnalysisDisciplineBase::addAnalysisVariablesAndInitialize()",
   "AnalysisDiscipline");
  // set n_systems for each DofObject (nodes and  elems)
  this->setNSystemsForDOFObjects();
  // add a variable. This will add the user defined variables, which will be specific to
  // to each discipline of analysis
  this->addAnalysisVariables();
  // ask dof_map to distribute dofs and calculate the sparsity pattern
  this->dof_map->distribute_dofs(*(this->mesh));
  // for AMR
  this->dof_map->create_dof_constraints(*(this->mesh));
  // for AMR
  //this->dof_map->process_recursive_constraints();
  this->fesystem_controller.performance_logging->setEvent
    ("AnalysisDisciplineBase::computing_sparsity",
     "AnalysisDiscipline");
  this->dof_map->compute_sparsity(*(this->mesh));
  this->fesystem_controller.performance_logging->unsetEvent
    ("AnalysisDisciplineBase::computing_sparsity",
     "AnalysisDiscipline");
  this->fesystem_controller.performance_logging->unsetEvent
    ("AnalysisDisciplineBase::addAnalysisVariablesAndInitialize()",
     "AnalysisDiscipline");
}
void Discipline::AnalysisDisciplineBase::addElemQtyToGlobalData (const Elem * elem, std::map< unsigned int, double > & global_real_data_map, std::map< unsigned int, double > & elem_real_data_map, std::map< unsigned int, SparseMatrix< double > * > & global_matrix_data_map, std::map< unsigned int, DenseMatrix< double > > & elem_matrix_data_map, std::map< unsigned int, NumericVector< double > * > & global_vector_data_map, std::map< unsigned int, DenseVector< double > > & elem_vector_data_map) [inline, protected]
function will add the element data to the appropriate locations in the global matrix.
Parameters:
global matrix
libmesh elem pointer
vector containing element quantities
Definition at line 704 of file AnalysisDisciplineBase.h.
{
  Assert(global_matrix_data_map.size() == elem_matrix_data_map.size(),
         ExcInternalError());
  Assert(global_vector_data_map.size() == elem_vector_data_map.size(),
         ExcInternalError());
  // get the dof_indices
  static std::vector<unsigned int> dof_indices;
  this->dof_map->dof_indices(elem, dof_indices);
  static std::map<unsigned int, double>::iterator real_it, real_end;
  static std::map<unsigned int, SparseMatrix<double>*>::iterator mat_it, mat_end;
  static std::map<unsigned int, NumericVector<double>*>::iterator vec_it, vec_end;
  real_it = global_real_data_map.begin();
  real_end = global_real_data_map.end();
  mat_it = global_matrix_data_map.begin();
  mat_end = global_matrix_data_map.end();
  vec_it = global_vector_data_map.begin();
  vec_end = global_vector_data_map.end();
  for ( ; real_it != real_end; real_it++)
    real_it->second += elem_real_data_map[real_it->first];
  for ( ; mat_it != mat_end; mat_it++)
    mat_it->second->add_matrix(elem_matrix_data_map[mat_it->first], dof_indices);
  for ( ; vec_it != vec_end; vec_it++)
    vec_it->second->add_vector(elem_vector_data_map[vec_it->first], dof_indices);
}
void Discipline::AnalysisDisciplineBase::addVariable (const std::string & var, const FEType & type) [protected]
Adds the variable var to the list of variables in this analysis.
Definition at line 203 of file AnalysisDisciplineBase.C.
Referenced by FEInterpolationAnalysis::addVariablesForAnalysis().
{
  System::Variable* variable = new System::Variable(var, this->_variables.size(), type);
  // Add the variable to the list
  this->_variables.push_back (variable);
  // Add the variable to the _dof_map
  this->dof_map->add_variable (*variable);
}
void Discipline::AnalysisDisciplineBase::attachAnalysisDriver (Driver::AnalysisDriver * driver)
attaches an analysis driver to this discipline
Definition at line 155 of file AnalysisDisciplineBase.C.
Referenced by Driver::AnalysisDriver::attachAnalysisDiscipline().
{
  Assert(driver != NULL, ExcEmptyObject());
  this->analysis_driver = driver;
}
void Discipline::AnalysisDisciplineBase::attachSolution (Solution::SolutionBase * sol) [inline]
sets the solution kind
Definition at line 514 of file AnalysisDisciplineBase.h.
Referenced by Solution::AeroelasticitySolution::aeroelasticSolve(), and Solution::SolutionBase::eigenSolve().
{
  Assert(sol != NULL, ExcEmptyObject());
  this->solution_base = sol;
}
virtual bool Discipline::AnalysisDisciplineBase::calculateEigenProblemAMatrix (bool sensitivity = false) [protected, pure virtual]
function to calculate the A matrix for eigen problem analysis
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
virtual bool Discipline::AnalysisDisciplineBase::calculateEigenProblemBMatrix (bool sensitivity = false) [protected, pure virtual]
function to calculate the B matrix for eigen problem analysis
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
virtual bool Discipline::AnalysisDisciplineBase::calculateF (bool = false) [protected, pure virtual]
function to calculate the force vector. First arguement is the vector to store the result in, and the second arguement is a bool to tell the function if sensitivity is desired
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
void Discipline::AnalysisDisciplineBase::calculateGlobalQty (std::map< unsigned int, double > & global_real_data_map, std::map< unsigned int, SparseMatrix< double > * > & global_matrix_data_map, std::map< unsigned int, NumericVector< double > * > & global_vector_data_map, bool sensitivity) [protected]
this function iterates over all elements and calculates the global quantity
Parameters:
global data
quantity to be calculates
whether sensitivity is required
Definition at line 487 of file AnalysisDisciplineBase.C.
References FESystemElem::FESystemElemBase::clearInitialization(), MeshDS::FEMeshData::getElemFromForeignID(), DesignData::DesignParameter::getID(), DesignData::DesignParameter::getParameterTypeEnumID(), DesignData::DesignParameter::getPerturbationStepSize(), FESystemNumbers::InvalidID, PROPERTY_PARAMETER_ENUM_ID, FESystemElem::FESystemElemBase::reinit(), FESystemElem::FESystemElemBase::reinitForPropertySensitivity(), FESystemElem::FESystemElemBase::reinitForShapeSensitivity(), and SHAPE_PARAMETER_ENUM_ID.
Referenced by FEInterpolationAnalysis::calculateF(), and FEInterpolationAnalysis::calculateK().
{
  this->fesystem_controller.performance_logging->setEvent
  ("AnalysisDisciplineBase::calculateGlobalQty()",
   "AnalysisDiscipline");
  std::map<unsigned int, double> elem_real_data_map;
  std::map<unsigned int, DenseMatrix<double> > elem_matrix_data_map;
  std::map<unsigned int, DenseVector<double> > elem_vector_data_map;
  // create the map of matrices and vectors for the quantities to be calculated
  {
    std::map<unsigned int, double>::iterator it, end;
    it = global_real_data_map.begin();
    end = global_real_data_map.end();
    for (; it != end; it++)
      {
        // zero the entries
        it->second = 0.0;
        elem_real_data_map.insert(std::map<unsigned int, double>::value_type
                                  (it->first, 0.0));
      }
  }
  {
    std::map<unsigned int, SparseMatrix<double>*>::const_iterator it, end;
    it = global_matrix_data_map.begin();
    end = global_matrix_data_map.end();
    for (; it != end; it++)
      {
      // zero the entries
      it->second->zero();
      elem_matrix_data_map.insert(std::map<unsigned int, DenseMatrix<double> >::value_type
                                  (it->first, DenseMatrix<double>()));
      }
  }
  {
    std::map<unsigned int, NumericVector<double>*>::const_iterator it, end;
    it = global_vector_data_map.begin();
    end = global_vector_data_map.end();
    for (; it != end; it++)
      {
      it->second->zero();
      elem_vector_data_map.insert(std::map<unsigned int, DenseVector<double> >::value_type
                                  (it->first, DenseVector<double>()));
      }
  }
  // if one of the quantities is a sensitivity quantitiy, then get the current
  // sensitivity parameter from the analysis driver
  const DesignData::DesignParameter* design_param = NULL;
  const MeshDS::FEMeshData* perturbed_mesh_data = NULL;
  double perturbation = 0.0;
  unsigned int des_param_ID = FESystemNumbers::InvalidID;
  if (sensitivity)
    {
    design_param = &(this->analysis_driver->getCurrentDesignParameter());
    des_param_ID = design_param->getID();
    if (design_param->getParameterTypeEnumID() == DesignData::SHAPE_PARAMETER::num())
      {
      perturbation = design_param->getPerturbationStepSize();
      unsigned int perturbed_mesh_ID =
        dynamic_cast<const DesignData::ShapeParameter*>(design_param)->
        getPerturbedMeshID(this->getDisciplineEnumID());
      perturbed_mesh_data =
        this->fesystem_controller.mesh_list->getMeshDataFromID(perturbed_mesh_ID);
      }
    }
  unsigned int elemID = 0, elem_kind_enum_ID = 0;
  unsigned int property_card_ID = 0;
  ElemDataCard* property_card = NULL;
  FESystemElem::FESystemElemBase  *fesys_elem = NULL;
  Elem* elem = NULL, *perturbed_elem = NULL;
  // loop over all the elements in the mesh.
  MeshBase::const_element_iterator           el  = mesh->active_local_elements_begin();
  const MeshBase::const_element_iterator end_el  = mesh->active_local_elements_end();
  std::set<Elem*>::iterator elem_it, elem_end;
  elem_end = this->dummy_element_set->end();
  for ( ; el != end_el ; ++el)
    {
    elem = const_cast<Elem*>(*el);
    // if this elem is not in the dummy elem set, process it, else leave it
    if (this->dummy_element_set->count(elem)>0)
      continue;
    elemID = mesh_data->getForeignIDFromElem(elem);
    elem_kind_enum_ID = this->mesh_data->getElemKindEnumID(elem);
    // get the property card for this element
    property_card_ID = this->mesh_data->getElemPropertyID(elem);
    property_card =
      &(this->fesystem_controller.property_database->getElemDataCardFromID(property_card_ID));
    // create the element object
    this->getFESystemElem(elem_kind_enum_ID, fesys_elem);
    fesys_elem->reinit(elemID, elem, property_card);
    // initialize for sensitivity if needed
    if (sensitivity)
      {
      switch (design_param->getParameterTypeEnumID())
        {
        case PROPERTY_PARAMETER_ENUM_ID:
          fesys_elem->reinitForPropertySensitivity(des_param_ID);
          break;
        case SHAPE_PARAMETER_ENUM_ID:
          {
            perturbed_elem = const_cast<Elem*>(perturbed_mesh_data->getElemFromForeignID(elemID));
            fesys_elem->reinitForShapeSensitivity(des_param_ID, perturbed_elem, perturbation);
          }
          break;
        default:
          // cannot get here
          Assert(false, ExcInternalError());
        }
      }
    // resize the matrices for this element
    this->resizeElemMatricesForElem(fesys_elem, elem_matrix_data_map, elem_vector_data_map);
    // get the element quantities corresponding to the global
    // qty in the vector
    this->getElemQty(fesys_elem, elem_real_data_map,
                     elem_matrix_data_map, elem_vector_data_map,
                     sensitivity, des_param_ID);
    // add the element quantities in the vector
    this->addElemQtyToGlobalData(elem,
                                 global_real_data_map, elem_real_data_map,
                                 global_matrix_data_map, elem_matrix_data_map,
                                 global_vector_data_map, elem_vector_data_map);
    // now that the element has been used, just clear its initialization
    fesys_elem->clearInitialization();
    }
  this->fesystem_controller.performance_logging->unsetEvent
    ("AnalysisDisciplineBase::calculateGlobalQty()",
     "AnalysisDiscipline");
}
virtual bool Discipline::AnalysisDisciplineBase::calculateJac () [protected, pure virtual]
function to calculate the Jacobian matrix. First arguement is the matrix to store the result in, and the second arguement is a bool to tell the function if sensitivity is desired
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
virtual bool Discipline::AnalysisDisciplineBase::calculateK (bool = false) [protected, pure virtual]
function to calculate the conductance matrix. First arguement is the matrix to store the result in, and the second arguement is a bool to tell the function if sensitivity is desired
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
void Discipline::AnalysisDisciplineBase::calculatePostProcessQty (const std::vector< unsigned int > & load_cases)
this function will iterate over all the elements, calculate the post process quantity, and store them in the post process quantity database
Definition at line 700 of file AnalysisDisciplineBase.C.
References PostProcessQtyDatabase::addElementPostProcessQty(), FESystemElem::FESystemElemBase::clearInitialization(), FESystemElem::FESystemElemBase::getElementPostProcessQty(), and FESystemElem::FESystemElemBase::reinit().
{
  // these are temporary data structures that will be used below
  FESystemElem::FESystemElemBase *fesys_elem = NULL;
  std::auto_ptr<ElemPostProcessQty> elem_data(NULL);
  PostProcessQtyDatabase& database =
    *(this->fesystem_controller.post_process_qty_database.get());
  // the data will be calculated for all load cases, and DVs
  //  const std::vector<unsigned int>& load_cases =
  //    this->fesystem_controller.analysis_case->getLoadCaseIDs();
  std::auto_ptr<std::vector<DesignData::DesignParameter*> > dv_vector =
    this->fesystem_controller.design_database->getParameters();
  unsigned int property_card_ID = 0;
  ElemDataCard* property_card = NULL;
  unsigned int elemID = 0, elem_kind_enum_ID = 0;
  // loop over all the elements in the mesh.
  MeshBase::const_element_iterator           el  = mesh->elements_begin();
  const MeshBase::const_element_iterator end_el  = mesh->elements_end();
  std::set<Elem*>::iterator elem_it, elem_end;
  elem_end = this->dummy_element_set->end();
  for ( ; el != end_el ; ++el)
    {
    Elem* elem = const_cast<Elem*>(*el);
    // if this elem is not in the dummy elem set, process it, else leave it
    elem_it = this->dummy_element_set->find(elem);
    if (elem_it != elem_end)
      continue;
    elemID = mesh_data->getForeignIDFromElem(elem);
    elem_kind_enum_ID = this->mesh_data->getElemKindEnumID(elem);
    // get the property card for this element
    property_card_ID = this->mesh_data->getElemPropertyID(elem);
    property_card =
      &(this->fesystem_controller.property_database->getElemDataCardFromID(property_card_ID));
    // create the element object
    this->getFESystemElem(elem_kind_enum_ID, fesys_elem);
    fesys_elem->reinit(elemID, elem, property_card);
    elem_data.reset(fesys_elem->getElementPostProcessQty(load_cases, *(dv_vector.get())).release());
    database.addElementPostProcessQty(this->getDisciplineEnumID(),
                                      elemID, elem_data);
    // now that the element has been used, just clear its initialization
    fesys_elem->clearInitialization();
    }
}
virtual bool Discipline::AnalysisDisciplineBase::calculateTransientMatrix (const unsigned int order, bool = false) [protected, pure virtual]
function to calculate the conductance matrix. First arguement is the matrix to store the result in, and the second arguement is a bool to tell the function if sensitivity is desired
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
bool Discipline::AnalysisDisciplineBase::checkPropertyDependenceOnTemperature () const [inline]
checks if the analysis is dependent on temperature
Definition at line 666 of file AnalysisDisciplineBase.h.
Referenced by RadiationCavityAnalysis::clearPropertyCardInitialization(), and RadiationCavityAnalysis::getMatrixQuantity().
{
  return this->temperature_dependent_property;
}
void Discipline::AnalysisDisciplineBase::clear ()
function to clear all data structures
Reimplemented in Discipline::PistonTheory.
Definition at line 175 of file AnalysisDisciplineBase.C.
Referenced by Solution::AeroelasticitySolution::aeroelasticSolve(), Discipline::PistonTheory::clear(), Solution::SolutionBase::eigenSolve(), Solution::SolutionBase::linearSolve(), Solution::SolutionBase::linearTransientSolve(), Solution::SolutionBase::nonlinearSolve(), Solution::SolutionBase::nonlinearTransientSolve(), and ~AnalysisDisciplineBase().
{
  // clear the pointer to the analysis driver, since a new analysis driver might
  // be attached at a later point
  this->solution_base = NULL;
  this->analysis_driver = NULL;
  // also, delete the fesystem elements in the discipline
  Discipline::AnalysisDisciplineBase::FESystemElemMap::iterator it, end;
  it = this->fesystem_elem_map.begin();
  end = this->fesystem_elem_map.end();
  for ( ; it != end; it++)
    {
    delete it->second;
    it->second = NULL;
    }
  this->fesystem_elem_map.clear();
  this->loaded_solution.clear();
}
virtual bool Discipline::AnalysisDisciplineBase::disciplineHasMatrix (const unsigned int qty_enum_ID) const [pure virtual]
Returns:
true if the specified matrix has exists for the discipline
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
Referenced by Driver::RogerApproximationAeroelasticityDriver::addMatricesAndVectors(), and Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
void Discipline::AnalysisDisciplineBase::fillQuantity (std::map< unsigned int, double > & real_map, std::map< unsigned int, SparseMatrix< double > * > & matrix_map, std::map< unsigned int, NumericVector< double > * > & vector_map)
this function fills in the matrix/vector with the quantity referred to by the second arguement
Definition at line 248 of file AnalysisDisciplineBase.C.
References EIGENPROBLEM_A_MATRIX_ENUM_ID, EIGENPROBLEM_A_MATRIX_SENSITIVITY_ENUM_ID, EIGENPROBLEM_B_MATRIX_ENUM_ID, EIGENPROBLEM_B_MATRIX_SENSITIVITY_ENUM_ID, FORCE_VECTOR_ENUM_ID, FORCE_VECTOR_SENSITIVITY_ENUM_ID, JACOBIAN_MATRIX_ENUM_ID, MODEL_MASS_ENUM_ID, MODEL_MASS_SENSITIVITY_ENUM_ID, SYSTEM_MATRIX_ENUM_ID, SYSTEM_MATRIX_SENSITIVITY_ENUM_ID, TRANSIENT_C1_MATRIX_ENUM_ID, TRANSIENT_C1_MATRIX_SENSITIVITY_ENUM_ID, TRANSIENT_C2_MATRIX_ENUM_ID, and TRANSIENT_C2_MATRIX_SENSITIVITY_ENUM_ID.
Referenced by Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
{
  // iterate over all quantities, and prepare a list of which quantities
  // need to be calculated and saved. This has to be done for both
  // the matrix and the vector quantities
  std::map<unsigned int, double> calculate_real;
  std::map<unsigned int, SparseMatrix<double>* > calculate_matrix;
  std::map<unsigned int, NumericVector<double>* > calculate_vector;
  bool sensitivity = false;
  // check if the quantity needs to be recalculated
  std::map<unsigned int, double>::const_iterator real_it, real_end;
  real_it = real_map.begin();
  real_end = real_map.end();
  for (; real_it != real_end; real_it++)
    {
      switch (real_it->first)
      {
        case MODEL_MASS_ENUM_ID:
          calculate_real[real_it->first] = 0.0;
          break;
        case MODEL_MASS_SENSITIVITY_ENUM_ID:
        {
          calculate_real[real_it->first] = 0.0;
          sensitivity = true;
        }
          break;
        default:
          ExcInternalError();
      }
    }
  std::map<unsigned int, SparseMatrix<double>* >::const_iterator mat_it, mat_end;
  mat_it = matrix_map.begin();
  mat_end = matrix_map.end();
  // check if the quantity needs to be recalculated
  for ( ; mat_it != mat_end; mat_it++)
    {
    switch (mat_it->first)
      {
      case TRANSIENT_C2_MATRIX_ENUM_ID:
        {
          if (this->calculateTransientMatrix(2))
            calculate_matrix[mat_it->first] = mat_it->second;
        }
        break;
      case TRANSIENT_C2_MATRIX_SENSITIVITY_ENUM_ID:
        {
          if (this->calculateTransientMatrix(2, true))
            calculate_matrix[mat_it->first] = mat_it->second;
          sensitivity = true;
        }
        break;
      case TRANSIENT_C1_MATRIX_ENUM_ID:
        {
          if (this->calculateTransientMatrix(1))
            calculate_matrix[mat_it->first] = mat_it->second;
        }
        break;
      case TRANSIENT_C1_MATRIX_SENSITIVITY_ENUM_ID:
        {
          if (this->calculateTransientMatrix(1, true))
            calculate_matrix[mat_it->first] = mat_it->second;
          sensitivity = true;
        }
        break;
      case SYSTEM_MATRIX_ENUM_ID:
        {
          if (this->calculateK())
            calculate_matrix[mat_it->first] = mat_it->second;
        }
        break;
      case SYSTEM_MATRIX_SENSITIVITY_ENUM_ID:
        {
          if (this->calculateK(true))
            calculate_matrix[mat_it->first] = mat_it->second;
          sensitivity = true;
        }
        break;
      case JACOBIAN_MATRIX_ENUM_ID:
        {
          if (this->calculateJac())
            calculate_matrix[mat_it->first] = mat_it->second;
        }
        break;
      case EIGENPROBLEM_A_MATRIX_ENUM_ID:
        {
          if (this->calculateEigenProblemAMatrix())
            calculate_matrix[mat_it->first] = mat_it->second;
        }
        break;
      case EIGENPROBLEM_A_MATRIX_SENSITIVITY_ENUM_ID:
        {
          if (this->calculateEigenProblemAMatrix(true))
            calculate_matrix[mat_it->first] = mat_it->second;
          sensitivity = true;
        }
        break;
      case EIGENPROBLEM_B_MATRIX_ENUM_ID:
        {
          if (this->calculateEigenProblemBMatrix())
            calculate_matrix[mat_it->first] = mat_it->second;
        }
        break;
      case EIGENPROBLEM_B_MATRIX_SENSITIVITY_ENUM_ID:
        {
          if (this->calculateEigenProblemAMatrix(true))
            calculate_matrix[mat_it->first] = mat_it->second;
          sensitivity = true;
        }
        break;
      default:
        abort();
        break;
      }
    }
  // now check the vectors
  std::map<unsigned int, NumericVector<double>* >::const_iterator vec_it, vec_end;
  vec_it = vector_map.begin();
  vec_end = vector_map.end();
  // check if the quantity needs to be recalculated
  for ( ; vec_it != vec_end; vec_it++)
    {
    switch (vec_it->first)
      {
      case FORCE_VECTOR_ENUM_ID:
        {
          if (this->calculateF())
            calculate_vector[vec_it->first] = vec_it->second;
        }
        break;
      case FORCE_VECTOR_SENSITIVITY_ENUM_ID:
        {
          if (this->calculateF(true))
            calculate_vector[vec_it->first] = vec_it->second;
          sensitivity = true;
        }
        break;
      default:
        abort();
        break;
      }
    }
  // now calculate the quantities
  this->calculateGlobalQty(calculate_real, calculate_matrix, calculate_vector, sensitivity);
  this->performAdditionalOperationsOnGlobalQuantities(calculate_matrix,
                                                      calculate_vector);
  // now, copy the values to the map
  std::map<unsigned int, double>::iterator real_it_w, real_end_w;
  real_it_w = real_map.begin();
  real_end_w = real_map.end();
  for (; real_it_w != real_end_w; real_it_w++)
    real_it_w->second = calculate_real[real_it_w->first];
  // next, save the quantities that were calculated, and others will be
  // retrieved from the database
  mat_it = matrix_map.begin();
  for ( ; mat_it != mat_end; mat_it++)
    {
    std::auto_ptr<FESystemDatabase::DataInfoBase>
    data_info(this->getDataInfoForQty(mat_it->first).release());
    mat_it->second->close();
    if (calculate_matrix.count(mat_it->first) == 0)
      // retrieve solution
      this->fesystem_controller.global_data_storage->fillMatrix
      (*data_info, *(mat_it->second));
    else
      // store solution
      this->fesystem_controller.global_data_storage->storeMatrix
      (*data_info, *(mat_it->second));
    }
  vec_it = vector_map.begin();
  for ( ; vec_it != vec_end; vec_it++)
    {
    std::auto_ptr<FESystemDatabase::DataInfoBase>
    data_info(this->getDataInfoForQty(vec_it->first).release());
    vec_it->second->close();
    switch (calculate_vector.count(vec_it->first))
      {
      case 0:
        // retrieve solution
        this->fesystem_controller.global_data_storage->fillVector
        (*data_info, *(vec_it->second));
        break;
      case 1:
        // store solution
        this->fesystem_controller.global_data_storage->storeVector
        (*data_info, *(vec_it->second));
        break;
      default:
        // cannot get here
        Assert(false, ExcInternalError());
      }
    }
}
const MeshDS::FEDofMap & Discipline::AnalysisDisciplineBase::getAnalysisDofMap () const [inline]
returns the DOFMap object associated with the mesh
Definition at line 551 of file AnalysisDisciplineBase.h.
{
  return *(this->dof_map);
}
Driver::AnalysisDriver & Discipline::AnalysisDisciplineBase::getAnalysisDriver () [inline]
Definition at line 505 of file AnalysisDisciplineBase.h.
Referenced by FEInterpolationElem::calculate_F(), RadiationCavityAnalysis::calculateA_Matrix(), RadiationCavityAnalysis::calculateB_Matrix(), and RadiationCavityAnalysis::getDataInfoForQty().
{
  Assert(this->analysis_driver != NULL, ExcEmptyObject());
  return *(this->analysis_driver);
}
const std::set< Elem * > & Discipline::AnalysisDisciplineBase::getAnalysisDummyElemSet () const [inline]
returns the dummy elem list
Definition at line 587 of file AnalysisDisciplineBase.h.
{
  return *(this->dummy_element_set);
}
const MeshDS::FEMesh & Discipline::AnalysisDisciplineBase::getAnalysisMesh () const [inline]
returns the Mesh for this analysis
Definition at line 569 of file AnalysisDisciplineBase.h.
{
  return *(this->mesh);
}
const MeshDS::FEMeshData & Discipline::AnalysisDisciplineBase::getAnalysisMeshData () const [inline]
returns the MeshData for this analysis
Definition at line 578 of file AnalysisDisciplineBase.h.
Referenced by Driver::RogerApproximationAeroelasticityDriver::createSubMatrixIndices().
{
  return *(this->mesh_data);
}
unsigned int Discipline::AnalysisDisciplineBase::getAnalysisMeshID () const [inline]
Definition at line 559 of file AnalysisDisciplineBase.h.
Referenced by FEInterpolationElem::calculate_F().
{
  return this->mesh_ID;
}
unsigned int Discipline::AnalysisDisciplineBase::getAnalysisTypeEnumID () const
Returns:
the type of analysis for this discipline, i.e. if it is linear or nonlinear
const std::string& Discipline::AnalysisDisciplineBase::getAnalysisTypeEnumName () const
Returns:
the type of analysis for this discipline, i.e. if it is linear or nonlinear
virtual std::auto_ptr<Loads::DirichletBoundaryConditionDataInfo> Discipline::AnalysisDisciplineBase::getBoundaryConditionLoadInfo () const [pure virtual]
returns the enum ID of the boundary condition for this disicipline
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
Referenced by Driver::RogerApproximationAeroelasticityDriver::createSubMatrixIndices().
virtual std::auto_ptr<FESystemDatabase::DataInfoBase> Discipline::AnalysisDisciplineBase::getDataInfoForQty (const unsigned int qty_enum_ID) [pure virtual]
Returns:
a FESystemDatabase::DataInfo pointer, which defines the quantity passed in the parameter, for the current analysis
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
unsigned int Discipline::AnalysisDisciplineBase::getDisciplineEnumID () const [inline]
Returns:
the disipline enum ID
Definition at line 524 of file AnalysisDisciplineBase.h.
Referenced by Driver::AnalysisDriver::attachAnalysisDiscipline(), FESystemElem::createFESystemElem(), and Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
{
  return this->discipline_enum_ID;
}
std::string Discipline::AnalysisDisciplineBase::getDisciplineEnumName () const [inline]
Returns:
the discipline enum name
Definition at line 533 of file AnalysisDisciplineBase.h.
{
  return Discipline::AnalysisDisciplineEnum::enumName(this->discipline_enum_ID);
}
const Discipline::DisciplineInfo & Discipline::AnalysisDisciplineBase::getDisciplineInfo () const [inline]
Returns:
the discipline info for this object
Definition at line 542 of file AnalysisDisciplineBase.h.
{
  return this->discipline_info;
}
virtual unsigned int Discipline::AnalysisDisciplineBase::getEigenProblemKindEnumID () [pure virtual]
Returns:
the eigenproblem kind for the discipline. This has to be implemented for each derived class.
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
void Discipline::AnalysisDisciplineBase::getElemDofValues (const Elem * elem, DenseVector< double > & qty, const unsigned int transient_order, const bool sensitivity) [inline]
this function will return a vector containing the dof values for the element nodes in a var major format.
Parameters:
load case ID
Definition at line 753 of file AnalysisDisciplineBase.h.
{
  static unsigned int n_nodes, dof, n_vars;
  n_nodes = elem->n_nodes();
  n_vars = this->getNVars();
  // create a quantity and resize it
  if (qty.size() != (n_nodes * n_vars))
    qty.resize(n_nodes * n_vars);
  const NumericVector<double>& sol = this->getSolutionVector(transient_order, sensitivity);
  // all computations inside the element are in a variable major mode
  for (unsigned int var_it =0; var_it < n_vars; var_it++)
    for (unsigned int node_it =0; node_it < n_nodes; node_it++)
      {
      dof = elem->get_node(node_it)->dof_number(0,var_it,0);
      qty(var_it * n_nodes + node_it) = sol(dof);
      }
}
void Discipline::AnalysisDisciplineBase::getElemLoads (const unsigned int elem_ID, const Elem * elem, const unsigned int load_case, const bool transient, const double time, const bool sensitivity, const unsigned int DV_ID, const std::map< unsigned int, unsigned int > & volume_loads, const std::map< unsigned int, unsigned int > & surface_loads, const std::map< unsigned int, std::pair< unsigned int, unsigned int > > & nodal_loads, std::map< unsigned int, const Loads::VolumeLoadCombination * > & volume_load_map, std::map< unsigned int, std::map< unsigned int, const Loads::NodalLoadCombination * > > & nodal_load_map, std::map< unsigned int, std::map< unsigned int, const Loads::SurfaceLoadCombination * > > & surface_load_map) [protected]
this gets the loads from the load database
Definition at line 783 of file AnalysisDisciplineBase.C.
References Loads::LoadCombinationBase::clear(), FESystemUtility::AutoPtrVector< T >::clear(), Loads::ElemLoadDataInfo::clear(), Loads::SurfaceLoadDataInfo::clear(), Loads::NodalLoadDataInfo::clear(), Loads::createNodalLoadCombination(), Loads::createNodalLoadDataInfo(), Loads::createSurfaceLoadCombination(), Loads::createSurfaceLoadDataInfo(), Loads::createVolumeLoadCombination(), Loads::createVolumeLoadDataInfo(), Loads::NodalLoadCombination::getNodeID(), info, Loads::NodalLoadCombination::nLoads(), Loads::SurfaceLoadCombination::nLoads(), Loads::VolumeLoadCombination::nLoads(), FESystemUtility::AutoPtrVector< T >::push_back(), Loads::LoadDataInfoBase::setDVID(), Loads::ElemLoadDataInfo::setElemID(), Loads::LoadDataInfoBase::setLoadCaseID(), Loads::LoadDataInfoBase::setLoadClassEnumID(), Loads::LoadDataInfoBase::setLoadNameEnumID(), Loads::NodalLoadDataInfo::setNDofs(), Loads::NodalLoadDataInfo::setNodeID(), Loads::SurfaceLoadDataInfo::setSurfaceID(), and Loads::LoadDataInfoBase::setTime().
{
    Assert(elem != NULL, ExcInternalError());
    // create a map of quantities that will be used in the load processing
    // this is being done to avoid creating and deleting objects for each element during the processing
    static FESystemUtility::AutoPtrVector<Loads::LoadCombinationBase> local_loads;
    static std::map<unsigned int, Loads::VolumeLoadCombination*> local_volume_load_map;
    static std::map<unsigned int, Loads::VolumeLoadCombination*> local_volume_load_sens_map;
    static std::map<unsigned int, std::map<unsigned int, Loads::NodalLoadCombination*> > local_nodal_load_map;
    static std::map<unsigned int, std::map<unsigned int, Loads::NodalLoadCombination*> > local_nodal_load_sens_map;
    static std::map<unsigned int, std::map<unsigned int, Loads::SurfaceLoadCombination*> > local_surface_load_map;
    static std::map<unsigned int, std::map<unsigned int, Loads::SurfaceLoadCombination*> > local_surface_load_sens_map;
    // these are only pointers that will be used for the appropriate map
    static std::map<unsigned int, Loads::VolumeLoadCombination*>* local_volume_load_map_ptr;
    static std::map<unsigned int, std::map<unsigned int, Loads::NodalLoadCombination*> >* local_nodal_load_map_ptr;
    static std::map<unsigned int, std::map<unsigned int, Loads::SurfaceLoadCombination*> >* local_surface_load_map_ptr;
    if (sensitivity)
      {
          local_volume_load_map_ptr = &local_volume_load_sens_map;
          local_nodal_load_map_ptr = &local_nodal_load_sens_map;
          local_surface_load_map_ptr = &local_surface_load_sens_map;
      }
    else
      {
          local_volume_load_map_ptr = &local_volume_load_map;
          local_nodal_load_map_ptr = &local_nodal_load_map;
          local_surface_load_map_ptr = &local_surface_load_map;
      }
    // these are the iterators for the loads
    static std::map<unsigned int, Loads::VolumeLoadCombination*>::iterator
    volume_combo_it, volume_combo_end;
    static std::map<unsigned int, std::map<unsigned int, Loads::SurfaceLoadCombination*> >::iterator
    surface_combo_it, surface_combo_end;
    static std::map<unsigned int, Loads::SurfaceLoadCombination*>::iterator
    local_surface_combo_it, local_surface_combo_end;
    static std::map<unsigned int, std::map<unsigned int, Loads::NodalLoadCombination*> >::iterator
    nodal_combo_it, nodal_combo_end;
    static std::map<unsigned int, Loads::NodalLoadCombination*>::iterator
    local_nodal_combo_it, local_nodal_combo_end;
    // these are the iterators for the elem node or side numbers for the different element kinds
    static std::map<unsigned int, std::map<unsigned int, const Loads::SurfaceLoadCombination*> >::iterator
    elem_surface_map_it, elem_surface_map_end;
    static std::map<unsigned int, std::map<unsigned int, const Loads::NodalLoadCombination*> >::iterator
    elem_nodal_map_it, elem_nodal_map_end;
    // this is the vector of data info that will be used to fetch loads
    static FESystemUtility::AutoPtrVector<Loads::LoadDataInfoBase> local_load_info;
    static std::map<unsigned int, Loads::VolumeLoadDataInfo*> local_volume_load_info_map;
    static std::map<unsigned int, Loads::NodalLoadDataInfo*> local_nodal_load_info_map;
    static std::map<unsigned int, Loads::SurfaceLoadDataInfo*> local_surface_load_info_map;
    static std::map<unsigned int, Loads::VolumeLoadDataInfo*>::iterator volume_info_it;
    static std::map<unsigned int, Loads::NodalLoadDataInfo*>::iterator nodal_info_it;
    static std::map<unsigned int, Loads::SurfaceLoadDataInfo*>::iterator surface_info_it;
    // the maps should be cleared before working with the loads
    volume_load_map.clear();
    nodal_load_map.clear();
    surface_load_map.clear();
    // iterate over the loads and get the loads from the load database
    static std::map<unsigned int, unsigned int>::const_iterator volume_it, volume_end;
    volume_it = volume_loads.begin();
    volume_end = volume_loads.end();
    static std::map<unsigned int, std::pair<unsigned int, unsigned int> >::const_iterator nodal_it, nodal_end;
    nodal_it = nodal_loads.begin();
    nodal_end = nodal_loads.end();
    static std::map<unsigned int, unsigned int>::const_iterator surface_it, surface_end;
    surface_it = surface_loads.begin();
    surface_end = surface_loads.end();
    bool insert_success = false;
    // first the volume loads
    // get the loads from the load database
    for ( ; volume_it != volume_end; volume_it++)
      {
          volume_info_it = local_volume_load_info_map.find(volume_it->first);
          // init the load data info for the load
          if (volume_info_it == local_volume_load_info_map.end())
            {
                std::auto_ptr<Loads::VolumeLoadDataInfo>
                info(Loads::createVolumeLoadDataInfo(volume_it->second).release());
                // add this to the vector and to the map
                volume_info_it = local_volume_load_info_map.insert
                (std::map<unsigned int, Loads::VolumeLoadDataInfo*>::value_type
                 (volume_it->first, info.get())).first;
                local_load_info.push_back(info.release());
            }
          Loads::VolumeLoadDataInfo* info = volume_info_it->second;
          info->clear();
          info->setLoadCaseID(load_case);
          info->setElemID(elem_ID);
          info->setLoadNameEnumID(volume_it->first);
          info->setLoadClassEnumID(volume_it->second);
          if (transient)
              info->setTime(time);
          if (sensitivity)
              info->setDVID(DV_ID);
          // now get the load combination data object
          volume_combo_it = local_volume_load_map_ptr->find(volume_it->first);
          if (volume_combo_it == local_volume_load_map_ptr->end())
            {
                std::auto_ptr<Loads::VolumeLoadCombination>
                load_combo(Loads::createVolumeLoadCombination(volume_it->first).release());
                // add this to the vector and to the map
                volume_combo_it = local_volume_load_map_ptr->insert
                (std::map<unsigned int, Loads::VolumeLoadCombination*>::value_type
                 (volume_it->first, load_combo.get())).first;
                local_loads.push_back(load_combo.release());
            }
          Loads::VolumeLoadCombination* load_combo = volume_combo_it->second;
          load_combo->clear();
          // now, get the load
          this->fesystem_controller.load_database->getLoadCombination(*info, *load_combo);
          // finally, if a load was found, insert this into the return volume load map
          if (load_combo->nLoads() > 0)
            {
                insert_success = volume_load_map.insert
                (std::map<unsigned int, const Loads::VolumeLoadCombination*>::value_type
                 (volume_it->first, load_combo)).second;
                Assert(insert_success, ExcInternalError());
            }
      }
    // get the loads from the load database.
    // for every load, iterate over the number of surfaces
    for ( ; surface_it != surface_end; surface_it++)
      {
          surface_info_it = local_surface_load_info_map.find(surface_it->first);
          // init the load data info for the load
          if (surface_info_it == local_surface_load_info_map.end())
            {
                std::auto_ptr<Loads::SurfaceLoadDataInfo>
                info(Loads::createSurfaceLoadDataInfo(surface_it->second).release());
                // add this to the vector and to the map
                surface_info_it = local_surface_load_info_map.insert
                (std::map<unsigned int, Loads::SurfaceLoadDataInfo*>::value_type
                 (surface_it->first, info.get())).first;
                local_load_info.push_back(info.release());
            }
          Loads::SurfaceLoadDataInfo* info = surface_info_it->second;
          // now get the load combination data object
          surface_combo_it = local_surface_load_map_ptr->find(surface_it->first);
          if (surface_combo_it == local_surface_load_map_ptr->end())
            {
                surface_combo_it =  local_surface_load_map_ptr->insert
                (std::map<unsigned int, std::map<unsigned int, Loads::SurfaceLoadCombination*> >::value_type
                 (surface_it->first, std::map<unsigned int, Loads::SurfaceLoadCombination*>())).first;
            }
          for (unsigned int i=0; i <= elem->n_sides(); i++)
            {
                local_surface_combo_it = surface_combo_it->second.find(i);
                if (local_surface_combo_it == surface_combo_it->second.end())
                  {
                      std::auto_ptr<Loads::SurfaceLoadCombination>
                      load_combo(Loads::createSurfaceLoadCombination(surface_it->second).release());
                      // add this to the vector and to the map
                      local_surface_combo_it = surface_combo_it->second.insert
                      (std::map<unsigned int, Loads::SurfaceLoadCombination*>::value_type
                       (i, load_combo.get())).first;
                      local_loads.push_back(load_combo.release());
                  }
                Loads::SurfaceLoadCombination* load_combo = local_surface_combo_it->second;
                info->clear();
                info->setLoadCaseID(load_case);
                info->setElemID(elem_ID);
                info->setSurfaceID(i);
                info->setLoadNameEnumID(surface_it->first);
                info->setLoadClassEnumID(surface_it->second);
                if (transient)
                    info->setTime(time);
                if (sensitivity)
                    info->setDVID(DV_ID);
                load_combo->clear();
                // now, get the load
                this->fesystem_controller.load_database->getLoadCombination(*info, *load_combo);
                // finally, if a load was found, insert this into the return volume load map
                if (load_combo->nLoads() > 0)
                  {
                      elem_surface_map_it = surface_load_map.find(surface_it->first);
                      if (elem_surface_map_it == surface_load_map.end())
{
                            elem_surface_map_it = surface_load_map.insert
                            (std::map< unsigned int, std::map<unsigned int, const Loads::SurfaceLoadCombination*> >::value_type
                             (surface_it->first, std::map<unsigned int, const Loads::SurfaceLoadCombination*>())).first;
                        }
                      insert_success = elem_surface_map_it->second.insert
                      (std::map<unsigned int, const Loads::SurfaceLoadCombination*>::value_type
                       (i, load_combo)).second;
                      Assert(insert_success, ExcInternalError());
                  }
            }
      }
    // get the loads from the load database.
    // for every load, iterate over the number of nodes
    for ( ; nodal_it != nodal_end; nodal_it++)
      {
          nodal_info_it = local_nodal_load_info_map.find(nodal_it->first);
          // init the load data info for the load
          if (nodal_info_it == local_nodal_load_info_map.end())
            {
                std::auto_ptr<Loads::NodalLoadDataInfo>
                info(Loads::createNodalLoadDataInfo(nodal_it->second.first).release());
                // add this to the vector and to the map
                nodal_info_it = local_nodal_load_info_map.insert
                (std::map<unsigned int, Loads::NodalLoadDataInfo*>::value_type
                 (nodal_it->first, info.get())).first;
                local_load_info.push_back(info.release());
            }
          Loads::NodalLoadDataInfo* info = nodal_info_it->second;
          // now get the load combination data object
          nodal_combo_it = local_nodal_load_map_ptr->find(nodal_it->first);
          if (nodal_combo_it == local_nodal_load_map_ptr->end())
            {
                nodal_combo_it =  local_nodal_load_map_ptr->insert
                (std::map<unsigned int, std::map<unsigned int, Loads::NodalLoadCombination*> >::value_type
                 (nodal_it->first, std::map<unsigned int, Loads::NodalLoadCombination*>())).first;
            }
          unsigned int node_id = 0;
          for (unsigned int i=0; i < elem->n_nodes(); i++)
            {
                local_nodal_combo_it = nodal_combo_it->second.find(i);
                if (local_nodal_combo_it == nodal_combo_it->second.end())
                  {
                      std::auto_ptr<Loads::NodalLoadCombination>
                      load_combo(Loads::createNodalLoadCombination(nodal_it->second.first).release());
                      // add this to the vector and to the map
                      local_nodal_combo_it = nodal_combo_it->second.insert
                      (std::map<unsigned int, Loads::NodalLoadCombination*>::value_type
                       (i, load_combo.get())).first;
                      local_loads.push_back(load_combo.release());
                  }
                Loads::NodalLoadCombination* load_combo = local_nodal_combo_it->second;
                node_id = this->mesh_data->getForeignIDFromNode(elem->get_node(i));
                info->clear();
                info->setLoadCaseID(load_case);
                info->setNodeID(node_id);
                info->setLoadNameEnumID(nodal_it->first);
                info->setLoadClassEnumID(nodal_it->second.first);
                info->setNDofs(nodal_it->second.second);
                if (transient)
                    info->setTime(time);
                if (sensitivity)
                    info->setDVID(DV_ID);
                load_combo->clear();
                // now, get the load
                this->fesystem_controller.load_database->getLoadCombination(*info, *load_combo);
                // finally, if a load was found, insert this into the return volume load map
                if (load_combo->nLoads() > 0)
                  {
                      elem_nodal_map_it = nodal_load_map.find(nodal_it->first);
                      if (elem_nodal_map_it == nodal_load_map.end())
{
                            elem_nodal_map_it = nodal_load_map.insert
                            (std::map< unsigned int, std::map<unsigned int, const Loads::NodalLoadCombination*> >::value_type
                             (nodal_it->first, std::map<unsigned int, const Loads::NodalLoadCombination*>())).first;
                        }
                      insert_success = elem_nodal_map_it->second.insert
                      (std::map<unsigned int, const Loads::NodalLoadCombination*>::value_type
                       (load_combo->getNodeID(), load_combo)).second;
                      Assert(insert_success, ExcInternalError());
                  }
            }
      }
}
virtual void Discipline::AnalysisDisciplineBase::getElemQty (FESystemElem::FESystemElemBase * elem, std::map< unsigned int, double > & real_elem_data, std::map< unsigned int, DenseMatrix< double > > & mat_elem_data, std::map< unsigned int, DenseVector< double > > & vec_elem_data, const bool sensitivity, const unsigned int DV_ID) [protected, pure virtual]
function will fill the input vector with the element quantities required for the calculation of the specified global quantity. This is an abstract function and will be implemented in the derived class
Parameters:
global quantitiy
element pointer
vector in which the quantities will be added
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, and Discipline::PistonTheory.
FESystem::FESystemController & Discipline::AnalysisDisciplineBase::getFESystemController () [inline]
Definition at line 496 of file AnalysisDisciplineBase.h.
References fesystem_controller.
{
  return this->fesystem_controller;
}
void Discipline::AnalysisDisciplineBase::getFESystemElem (const unsigned int elem_kind_enum_ID, FESystemElem::FESystemElemBase *& fesys_elem) [inline, protected]
function creates elements for the specific discipline. This is an abstract function and will be implemented in the derived class. The input arguements are
Parameters:
element ID
fesys_elem pointer to the fesystem element that will be used for analysis
Definition at line 674 of file AnalysisDisciplineBase.h.
References FESystemElem::createFESystemElem().
{
  // check if this elem kind exists in the map
  unsigned int elem_exists = this->fesystem_elem_map.count(elem_kind_enum_ID);
  // if it does not exist, create and insert the elem
  if (elem_exists == 0)
    {
    FESystemElem::FESystemElemBase* local_fesys_elem =
    FESystemElem::createFESystemElem(elem_kind_enum_ID, *this).release();
    bool insert_success =
      this->fesystem_elem_map.insert(Discipline::AnalysisDisciplineBase::FESystemElemMap::
                                     value_type(elem_kind_enum_ID, local_fesys_elem)).second;
    // this should never be false, but still, a check is introduced
    Assert(insert_success, ExcInternalError());
    }
  // now return the element
  fesys_elem = this->fesystem_elem_map[elem_kind_enum_ID];
}
unsigned int Discipline::AnalysisDisciplineBase::getNDofs () const [inline]
Returns:
the number of degrees of freedom in the analysis
Definition at line 605 of file AnalysisDisciplineBase.h.
Referenced by Driver::RogerApproximationAeroelasticityDriver::createSubMatrixIndices().
{
  return this->dof_map->n_dofs();
}
unsigned int Discipline::AnalysisDisciplineBase::getNVars () const [inline]
Returns:
the number of variables in the analysis
Definition at line 596 of file AnalysisDisciplineBase.h.
{
  return this->_variables.size();
}
Elem * Discipline::AnalysisDisciplineBase::getPerturbedElemForShapeParameter (const unsigned int elem_ID, DesignData::DesignParameter * param)
Returns:
the perturbed elem for the given elem ID and design param
Definition at line 763 of file AnalysisDisciplineBase.C.
References MeshDS::FEMeshData::getElemFromForeignID().
{
  // get mesh ID from the perturbed DV
  unsigned int perturbed_mesh_ID =
  (dynamic_cast<DesignData::ShapeParameter*>(param))->getPerturbedMeshID
  (this->getDisciplineEnumID());
  // get the perturbed mesh data
  MeshDS::FEMeshData* perturbed_mesh_data =
  this->fesystem_controller.mesh_list->getMeshDataFromID(perturbed_mesh_ID);
  // from this element ID, get the perturbed elem
  return const_cast<Elem*>(perturbed_mesh_data->getElemFromForeignID(elem_ID));
}
const Solution::SolutionBase & Discipline::AnalysisDisciplineBase::getSolution () const
Returns:
a reference to the solution
Definition at line 164 of file AnalysisDisciplineBase.C.
Referenced by Driver::RogerApproximationAeroelasticityDriver::addMatricesAndVectors(), RadiationCavityAnalysis::getDataInfoForQty(), and Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
{
  Assert(this->solution_base != NULL, ExcInternalError());
  return *(this->solution_base);
}
virtual const NumericVector<double>& Discipline::AnalysisDisciplineBase::getSolutionVector (const unsigned int transient_order, const bool sensitivity) [protected, pure virtual]
this method fills the vector with the solution vector necessary for filling the quantity for the current analysis. It checks the current status of the discipline, and apropriately loads the solution vector
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
virtual unsigned int Discipline::AnalysisDisciplineBase::getTransientSystemOrder () [pure virtual]
Returns:
the order of the transient nature of the problem
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
const std::string & Discipline::AnalysisDisciplineBase::getVariableName (const unsigned int i) const [inline]
Returns:
the name of variable i.
Definition at line 616 of file AnalysisDisciplineBase.h.
{
  assert (i < this->getNVars());
  return this->_variables[i]->name();
}
unsigned short int Discipline::AnalysisDisciplineBase::getVariableNumber (const std::string & var) const [inline]
Returns:
the variable number assoicated with the user-specified variable named var.
Definition at line 628 of file AnalysisDisciplineBase.h.
{
  for (unsigned int i=0; i<this->_variables.size(); i++)
    if (this->_variables[i]->name() == var)
      return this->_variables[i]->number();
  Assert(false, ExcInternalError());
  return NULL;
}
const FEType & Discipline::AnalysisDisciplineBase::getVariableType (const unsigned int i) const [inline]
Returns:
the finite element type variable number i.
Definition at line 641 of file AnalysisDisciplineBase.h.
{
  assert (i < this->getNVars());
  return this->_variables[i]->type();
}
const FEType & Discipline::AnalysisDisciplineBase::getVariableType (const std::string & var) const [inline]
Returns:
the finite element type for variable var.
Definition at line 652 of file AnalysisDisciplineBase.h.
{
  for (unsigned int i=0; i<this->_variables.size(); i++)
    if (this->_variables[i]->name() == var)
      return this->_variables[i]->type();
  Assert(false, ExcInternalError());
  return FEType();
}
void Discipline::AnalysisDisciplineBase::initMatrix (SparseMatrix< double > & mat) [virtual]
this will initialize the matrix to the sparsity pattern of the discipline's mesh
Definition at line 134 of file AnalysisDisciplineBase.C.
Referenced by Driver::RogerApproximationAeroelasticityDriver::addMatricesAndVectors().
{
  Assert(this->analysis_driver != NULL, ExcEmptyObject());
  mat.attach_dof_map(*(this->dof_map));
  mat.init();
}
void Discipline::AnalysisDisciplineBase::initVector (NumericVector< double > & vec) [virtual]
this will initialize the vector to the sparsity pattern of the discipline's mesh
Definition at line 145 of file AnalysisDisciplineBase.C.
Referenced by Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
{
  Assert(this->analysis_driver != NULL, ExcEmptyObject());
  vec.init(this->nDofs(), this->nLocalDofs());
}
unsigned int Discipline::AnalysisDisciplineBase::nDofs () const
Returns:
the number of dofs on the discipline
Definition at line 75 of file AnalysisDisciplineBase.C.
{
  Assert(this->dof_map != NULL, ExcInternalError());
  return this->dof_map->n_dofs();
}
unsigned int Discipline::AnalysisDisciplineBase::nLocalDofs () const
Returns:
the number of dofs on the current processor
Definition at line 84 of file AnalysisDisciplineBase.C.
References FESystem::local_processor.
{
  Assert(this->dof_map != NULL, ExcInternalError());
  return this->dof_map->n_dofs_on_processor(FESystem::local_processor);
}
virtual void Discipline::AnalysisDisciplineBase::performAdditionalOperationsOnGlobalQuantities (std::map< unsigned int, SparseMatrix< double > * > & matrix_map, std::map< unsigned int, NumericVector< double > * > & vector_map) [protected, pure virtual]
this method will perform some discipline specific operations once the global quantities have been calculated
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, and Discipline::PistonTheory.
void Discipline::AnalysisDisciplineBase::resizeElemMatricesForElem (FESystemElem::FESystemElemBase * fesys_elem, std::map< unsigned int, DenseMatrix< double > > & elem_matrix_data_map, std::map< unsigned int, DenseVector< double > > & elem_vector_data_map) [protected]
this method resizes the matrices and vectors if needed.
Definition at line 649 of file AnalysisDisciplineBase.C.
References FESystemElem::FESystemElemBase::getNDofs().
{
  static unsigned int n_dofs;
  n_dofs = fesys_elem->getNDofs();
  static std::map<unsigned int , DenseMatrix<double> >::iterator mat_it, mat_end;
  static std::map<unsigned int , DenseVector<double> >::iterator vec_it, vec_end;
  mat_it = elem_matrix_data_map.begin();
  mat_end = elem_matrix_data_map.end();
  vec_it = elem_vector_data_map.begin();
  vec_end = elem_vector_data_map.end();
  for ( ; mat_it != mat_end; mat_it++)
    {
    // it is assumed that checking only one dimension is enough.
    switch (mat_it->second.m() - n_dofs)
      {
      case 0:
        {
          // keep going
        }
        break;
      default:
        mat_it->second.resize(n_dofs, n_dofs);
      }
    }
  for ( ; vec_it != vec_end; vec_it++)
    {
    switch (vec_it->second.size() - n_dofs)
      {
      case 0:
        {
          // keep going
        }
        break;
      default:
        vec_it->second.resize(n_dofs);
      }
    }
}
virtual bool Discipline::AnalysisDisciplineBase::sameSystemMatrixForLoadCases () [pure virtual]
this method returns a boolean saying if the same system matrix can be used for each load case
Implemented in Discipline::ThermalAnalysis, Discipline::StructuralAnalysis, Discipline::FluidAnalysis, Discipline::PistonTheory, and FEInterpolationAnalysis.
void Discipline::AnalysisDisciplineBase::setNSystemsForDOFObjects () [protected]
set the number of systems for each DOFObject
Definition at line 221 of file AnalysisDisciplineBase.C.
References FESystem::total_processors.
{
  // remove the remote elements elements
  if (FESystem::total_processors > 1)
    this->mesh->delete_remote_elements();
  // set the number of systems for all nodes to 1
  MeshBase::node_iterator       node_it  = this->mesh->nodes_begin();
  const MeshBase::node_iterator node_end = this->mesh->nodes_end();
  for ( ; node_it != node_end; ++node_it)
    (*node_it)->set_n_systems(1);
  // set the number of systems for all elements to 1
  MeshBase::element_iterator       elem_it  = this->mesh->elements_begin();
  const MeshBase::element_iterator elem_end = this->mesh->elements_end();
  for ( ; elem_it != elem_end; ++elem_it)
    (*elem_it)->set_n_systems(1);
}
Member Data Documentation
std::vector<System::Variable*> Discipline::AnalysisDisciplineBase::_variables [protected]
The names of the variables associated with this analysis.
Definition at line 480 of file AnalysisDisciplineBase.h.
Referenced by ~AnalysisDisciplineBase().
Driver::AnalysisDriver* Discipline::AnalysisDisciplineBase::analysis_driver [protected]
pointer to the analysis driver for this discipline
Definition at line 457 of file AnalysisDisciplineBase.h.
Referenced by FEInterpolationAnalysis::calculateF(), FEInterpolationAnalysis::getStringNameForQty(), and FEInterpolationAnalysis::initMatricesAndVectors().
const unsigned int Discipline::AnalysisDisciplineBase::analysis_type_enum_ID [protected]
type of the analysis, i.e. linear, nonlinear
Definition at line 451 of file AnalysisDisciplineBase.h.
Referenced by FEInterpolationAnalysis::sameSystemMatrixForLoadCases(), and Discipline::ThermalAnalysis::ThermalAnalysis().
const unsigned int Discipline::AnalysisDisciplineBase::discipline_enum_ID [protected]
discipline name enum ID
Definition at line 448 of file AnalysisDisciplineBase.h.
const Discipline::DisciplineInfo& Discipline::AnalysisDisciplineBase::discipline_info [protected]
Definition at line 442 of file AnalysisDisciplineBase.h.
MeshDS::FEDofMap* Discipline::AnalysisDisciplineBase::dof_map [protected]
dof map data-structure
Definition at line 469 of file AnalysisDisciplineBase.h.
Referenced by FEInterpolationAnalysis::initMatricesAndVectors().
std::set<Elem*>* Discipline::AnalysisDisciplineBase::dummy_element_set [protected]
set of elements that do not need to be processed for element quantity calculations
Definition at line 473 of file AnalysisDisciplineBase.h.
Referenced by Discipline::ThermalAnalysis::ThermalAnalysis().
FESystem::FESystemController& Discipline::AnalysisDisciplineBase::fesystem_controller [protected]
Definition at line 440 of file AnalysisDisciplineBase.h.
Referenced by FEInterpolationAnalysis::calculateF(), FEInterpolationAnalysis::calculateK(), getFESystemController(), and Discipline::ThermalAnalysis::ThermalAnalysis().
FESystemElemMap Discipline::AnalysisDisciplineBase::fesystem_elem_map [protected]
Definition at line 486 of file AnalysisDisciplineBase.h.
FESystemUtility::LoadedSolution Discipline::AnalysisDisciplineBase::loaded_solution [protected]
this is the vector that is loaded from the database to provide the dofs to the elements when needed from a previously calculated solution
Definition at line 477 of file AnalysisDisciplineBase.h.
MeshDS::FEMesh* Discipline::AnalysisDisciplineBase::mesh [protected]
mesh data structure
Definition at line 463 of file AnalysisDisciplineBase.h.
Referenced by Discipline::ThermalAnalysis::ThermalAnalysis().
MeshDS::FEMeshData* Discipline::AnalysisDisciplineBase::mesh_data [protected]
mesh data data-structure
Definition at line 466 of file AnalysisDisciplineBase.h.
const unsigned int Discipline::AnalysisDisciplineBase::mesh_ID [protected]
ID of mesh.
Definition at line 460 of file AnalysisDisciplineBase.h.
Solution::SolutionBase* Discipline::AnalysisDisciplineBase::solution_base [protected]
solution kind enum ID
Definition at line 454 of file AnalysisDisciplineBase.h.
bool Discipline::AnalysisDisciplineBase::temperature_dependent_property [protected]
dependence on temperature
Definition at line 445 of file AnalysisDisciplineBase.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Discipline/AnalysisDisciplineBase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Discipline/AnalysisDisciplineBase.C