fesystem: LoadCaseBase Class Reference
LoadCaseBase Class Reference
#include <LoadCase.h>
Public Member Functions
LoadCaseBase (LoadDatabase &database)
constructor
virtual ~LoadCaseBase ()
destructor
virtual void clear ()
clears the data structures for this object
virtual unsigned int getLoadCaseKindEnumID () const =0
virtual void getLoadFactorLoadSetPair (const Loads::LoadDataInfoBase &load_info, std::vector< std::pair< unsigned int, double > > &load_pair) const =0
fills the vector with the load set ID and its load factor
unsigned int getLoadCaseID () const
virtual std::istream & readFromInputStream (std::istream &)=0
this method reads the load case data from the input stream
Protected Attributes
LoadDatabase & load_database
load database reference
unsigned int load_case_ID
load case ID for this LoadCase object
Detailed Description
Definition at line 70 of file LoadCase.h.
Constructor & Destructor Documentation
LoadCaseBase::LoadCaseBase (LoadDatabase & database)
constructor
Definition at line 18 of file LoadCase.C.
                                                :
  load_database(database)
{
}
LoadCaseBase::~LoadCaseBase () [virtual]
destructor
Definition at line 26 of file LoadCase.C.
{
}
Member Function Documentation
void LoadCaseBase::clear () [virtual]
clears the data structures for this object
Reimplemented in TimeDependentLoadCase, and TimeIndependentLoadCase.
Definition at line 34 of file LoadCase.C.
References FESystemNumbers::InvalidID, and load_case_ID.
{
  this->load_case_ID = FESystemNumbers::InvalidID;
}
unsigned int LoadCaseBase::getLoadCaseID () const [inline]
Returns:
the ID of this load case
Definition at line 236 of file LoadCase.h.
References load_case_ID.
Referenced by LoadDatabase::addLoadCase().
{
  return this->load_case_ID;
}
virtual unsigned int LoadCaseBase::getLoadCaseKindEnumID () const [pure virtual]
Returns:
the load case kind
Implemented in TimeDependentLoadCase, and TimeIndependentLoadCase.
virtual void LoadCaseBase::getLoadFactorLoadSetPair (const Loads::LoadDataInfoBase & load_info, std::vector< std::pair< unsigned int, double > > & load_pair) const [pure virtual]
fills the vector with the load set ID and its load factor
Implemented in TimeDependentLoadCase, and TimeIndependentLoadCase.
Referenced by LoadDatabase::getAllLoadCombinations< Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination >(), LoadDatabase::getAllLoadCombinations< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >(), LoadDatabase::getLoadCombination< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >(), LoadDatabase::getLoadCombination< Loads::SurfaceLoadDataInfo, Loads::SurfaceLoadCombination >(), and LoadDatabase::getLoadCombination< Loads::VolumeLoadDataInfo, Loads::VolumeLoadCombination >().
virtual std::istream& LoadCaseBase::readFromInputStream (std::istream &) [pure virtual]
this method reads the load case data from the input stream
Implemented in TimeDependentLoadCase, and TimeIndependentLoadCase.
Member Data Documentation
unsigned int LoadCaseBase::load_case_ID [protected]
load case ID for this LoadCase object
Definition at line 103 of file LoadCase.h.
Referenced by clear(), getLoadCaseID(), TimeIndependentLoadCase::readFromInputStream(), and TimeDependentLoadCase::readFromInputStream().
LoadDatabase& LoadCaseBase::load_database [protected]
load database reference
Definition at line 100 of file LoadCase.h.
Referenced by TimeDependentLoadCase::getLoadPair().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCase.C