fesystem: FESystemNumerics::PetscSeqVector< T > Class Template Reference
FESystemNumerics::PetscSeqVector< T > Class Template Reference
#include <PetscSeqVector.h>
Public Member Functions
PetscSeqVector (const unsigned int n=0)
constructor
PetscSeqVector (const FESystemNumerics::PetscSeqVector< T > &mat)
virtual ~PetscSeqVector ()
virtual void copy (const FESystemNumerics::VectorBase< T > &vector)
virtual void resize (const unsigned int n)
resize the matrix to the given dimensions
Detailed Description
template<typename T>
class FESystemNumerics::PetscSeqVector< T >
this class provides a base class for different kinds of matrices
Definition at line 19 of file PetscSeqVector.h.
Constructor & Destructor Documentation
template<typename T > FESystemNumerics::PetscSeqVector< T >::PetscSeqVector (const unsigned int n = 0)
constructor
Definition at line 53 of file PetscSeqVector.h.
References FESystemNumerics::PetscVectorBase< T >::petsc_vec, and FESystemNumerics::PetscVectorBase< T >::zero().
                                                                     :
FESystemNumerics::PetscVectorBase<T>()
{
  PetscErrorCode ierr=0;
  ierr = VecCreateSeq(PETSC_COMM_SELF,n,&(this->petsc_vec));
  CHKERRABORT(PETSC_COMM_SELF, ierr);
  this->zero();
}
template<typename T> FESystemNumerics::PetscSeqVector< T >::PetscSeqVector (const FESystemNumerics::PetscSeqVector< T > & mat)
Definition at line 67 of file PetscSeqVector.h.
References FESystem::COMM_WORLD, and FESystemNumerics::PetscVectorBase< T >::getVec().
                                              :
FESystemNumerics::PetscVectorBase<T>()
{
  PetscErrorCode ierr=0;
  ierr = VecDuplicate(vec.getVec(), &(this->petsc_vec));
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = VecCopy(vec.getVec(), this->petsc_vec);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > FESystemNumerics::PetscSeqVector< T >::~PetscSeqVector () [virtual]
Destructor. Empty.
Definition at line 81 of file PetscSeqVector.h.
References FESystem::COMM_WORLD.
{
  PetscErrorCode ierr=0;
  ierr = VecDestroy(this->petsc_vec);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
Member Function Documentation
template<typename T> void FESystemNumerics::PetscSeqVector< T >::copy (const FESystemNumerics::VectorBase< T > & vector) [inline, virtual]
Copies vector to this vector
Implements FESystemNumerics::VectorBase< T >.
Definition at line 118 of file PetscSeqVector.h.
References FESystem::COMM_WORLD, and FESystemNumerics::VectorBase< T >::getVectorPackage().
{
  Assert(vector.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  const FESystemNumerics::PetscVectorBase<T>& vec =
    dynamic_cast<const FESystemNumerics::PetscVectorBase<T>&>(vector);
  const_cast<FESystemNumerics::PetscVectorBase<T>&>(vec).assemble();
  // create a temporary matrix to store the result in
  PetscErrorCode ierr = 0;
  ierr = VecDestroy(this->petsc_vec);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = VecDuplicate(vec.getVec(), &(this->petsc_vec));
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = VecCopy(vec.getVec(), this->petsc_vec);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > void FESystemNumerics::PetscSeqVector< T >::resize (const unsigned int n) [virtual]
resize the matrix to the given dimensions
Implements FESystemNumerics::VectorBase< T >.
Definition at line 93 of file PetscSeqVector.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution(), RadiationCavityAnalysis::calculateEmissivityVector(), RadiationCavityAnalysis::calculateG_Matrix(), RadiationCavityAnalysis::calculateRadElemTempVector(), RadiationCavityAnalysis::getFEJacobianMatrix(), RadiationElement::getRadElemG_Vector(), Solution::TransientStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::TransientThermalSolution::getTimeDependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Discipline::ThermalAnalysis::performAdditionalOperationsOnGlobalQuantities(), and Driver::NonlinearTransientAnalysisDriver::solveCurrentLoadCase().
{
  if (this->size() == n)
    {
    this->zero();
    return;
    }
  PetscErrorCode ierr=0;
  ierr = VecDestroy(this->petsc_vec);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = VecCreateSeq(PETSC_COMM_SELF,n,&(this->petsc_vec));
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->zero();
}
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Numerics/PetscSeqVector.h