fesystem: OutputInfo Class Reference
OutputInfo Class Reference
#include <OutputInfo.h>
Public Member Functions
OutputInfo ()
~OutputInfo ()
unsigned int getOutputFormatEnumID () const
std::string getOutputFormatEnumName () const
const std::string & getOutputFileName () const
std::istream & readFromInputStream (std::istream &input)
Protected Attributes
unsigned int output_format_enum_ID
std::string output_file_name
Friends
std::istream & operator>> (std::istream &input, OutputInfo &info)
Detailed Description
Definition at line 16 of file OutputInfo.h.
Constructor & Destructor Documentation
OutputInfo::OutputInfo ()
Definition at line 9 of file OutputInfo.C.
                      :
output_format_enum_ID(FESystemNumbers::InvalidID),
output_file_name()
{
}
OutputInfo::~OutputInfo ()
Definition at line 18 of file OutputInfo.C.
{
}
Member Function Documentation
const std::string & OutputInfo::getOutputFileName () const [inline]
Definition at line 58 of file OutputInfo.h.
References output_file_name.
Referenced by GmshOutputProcessor::writeData().
{
  return this->output_file_name;
}
unsigned int OutputInfo::getOutputFormatEnumID () const [inline]
Definition at line 40 of file OutputInfo.h.
References output_format_enum_ID.
Referenced by OutputProcessor::createOutputProcessor().
{
  return this->output_format_enum_ID;
}
std::string OutputInfo::getOutputFormatEnumName () const [inline]
Definition at line 49 of file OutputInfo.h.
References output_format_enum_ID.
{
  return OutputFormatEnum::enumName(this->output_format_enum_ID);
}
std::istream & OutputInfo::readFromInputStream (std::istream & input)
Definition at line 26 of file OutputInfo.C.
References output_file_name, output_format_enum_ID, and FESystemIOUtility::readFromInput().
Referenced by operator>>().
{
  std::string tag;
  FESystemIOUtility::readFromInput(input, "OUTPUT_INFO");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "OUTPUT_FORMAT", tag);
  this->output_format_enum_ID = OutputFormatEnum::enumID(tag);
  FESystemIOUtility::readFromInput(input, "OUTPUT_FILE_NAME", this->output_file_name);
  FESystemIOUtility::readFromInput(input, "OUTPUT_INFO");
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, OutputInfo & info) [friend]
Definition at line 48 of file OutputInfo.C.
{
  info.readFromInputStream(input);
  return input;
}
Member Data Documentation
std::string OutputInfo::output_file_name [protected]
Definition at line 34 of file OutputInfo.h.
Referenced by getOutputFileName(), and readFromInputStream().
unsigned int OutputInfo::output_format_enum_ID [protected]
Definition at line 33 of file OutputInfo.h.
Referenced by getOutputFormatEnumID(), getOutputFormatEnumName(), and readFromInputStream().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/OutputProcessor/OutputInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/OutputProcessor/OutputInfo.C