fesystem: FESystemDatabase::TimeDependentDataInfo Class Reference
FESystemDatabase::TimeDependentDataInfo Class Reference
this defines a time dependent quantity
#include <DataInfo.h>
Public Member Functions
TimeDependentDataInfo ()
constructor
TimeDependentDataInfo (const TimeDependentDataInfo &data_info)
copy constructor
~TimeDependentDataInfo ()
destructor
virtual void clear ()
clears the data structures of this object
unsigned int getTransientIterationNumber () const
double getTimeValue () const
void setTransientIterationInfo (const unsigned int iter_num, const double time_val)
sets the transient iteration info
virtual unsigned int getDataInfoKindEnumID () const
void setOrder (const unsigned int i)
sets the time derivative of the solution vector
unsigned int getOrder () const
virtual const std::string getPath () const
virtual const std::string getDisplayName () const
virtual std::ostream & write (std::ostream &out)
this method writes the info to an output stream
virtual bool operator== (const FESystemDatabase::DataInfoBase &data_info) const
Protected Attributes
unsigned int transient_iteration_number
transient iteration
double time_instant
time value of this quantity
unsigned int derivative_order
time derivative order of the quantity
bool set_order
boolean to keep track of whether the order was set
Detailed Description
this defines a time dependent quantity
Definition at line 248 of file DataInfo.h.
Constructor & Destructor Documentation
FESystemDatabase::TimeDependentDataInfo::TimeDependentDataInfo ()
constructor
Definition at line 357 of file DataInfo.C.
References clear().
                                                            :
FESystemDatabase::DataInfoBase()
{
  this->clear();
}
FESystemDatabase::TimeDependentDataInfo::TimeDependentDataInfo (const TimeDependentDataInfo & data_info)
copy constructor
Definition at line 367 of file DataInfo.C.
References derivative_order, set_order, time_instant, and transient_iteration_number.
                                        :
  FESystemDatabase::DataInfoBase(data_info)
{
  this->transient_iteration_number = data_info.transient_iteration_number;
  this->time_instant = data_info.time_instant;
  this->derivative_order = data_info.derivative_order;
  this->set_order = data_info.set_order;
}
FESystemDatabase::TimeDependentDataInfo::~TimeDependentDataInfo ()
destructor
Definition at line 379 of file DataInfo.C.
{
}
Member Function Documentation
void FESystemDatabase::TimeDependentDataInfo::clear () [virtual]
clears the data structures of this object
Reimplemented from FESystemDatabase::GenericDataInfoBase.
Reimplemented in FESystemDatabase::TimeDependentEigenDataInfo.
Definition at line 389 of file DataInfo.C.
References FESystemDatabase::GenericDataInfoBase::clear(), and FESystemNumbers::InvalidID.
Referenced by FESystemDatabase::TimeDependentEigenDataInfo::clear(), Driver::NonlinearTransientAnalysisDriver::getCoefficientMatrices(), Driver::LinearTransientAnalysisDriver::getForceVector(), Driver::NonlinearTransientAnalysisDriver::getForceVector(), Discipline::ThermalAnalysis::getSolutionVector(), Driver::UpdatedLagrangianNonlinearStructuralAnalysisDriver::setNewIteration(), Driver::TransientAnalysisDriver::setNewIteration(), and TimeDependentDataInfo().
{
  this->transient_iteration_number = FESystemNumbers::InvalidID;
  this->time_instant = 0.0;
  this->derivative_order = FESystemNumbers::InvalidID;
  this->set_order = false;
  FESystemDatabase::DataInfoBase::clear();
}
unsigned int FESystemDatabase::TimeDependentDataInfo::getDataInfoKindEnumID () const [virtual]
Returns:
the enumeration ID of the kind of the data
Implements FESystemDatabase::DataInfoBase.
Reimplemented in FESystemDatabase::TimeDependentEigenDataInfo.
Definition at line 457 of file DataInfo.C.
{
  return FESystemDatabase::TIME_DEPENDENT_DATA::num();
}
const std::string FESystemDatabase::TimeDependentDataInfo::getDisplayName () const [virtual]
Implements FESystemDatabase::GenericDataInfoBase.
Reimplemented in FESystemDatabase::TimeDependentEigenDataInfo.
Definition at line 511 of file DataInfo.C.
{
  std::string full_path_name = this->getName();
  // append the derivative order
  std::ostringstream order_iter_oss;
  order_iter_oss << this->getOrder();
  full_path_name += "_OR_";
  full_path_name += order_iter_oss.str();
  // append the transient information to the name
  std::ostringstream time_iter_oss;
  time_iter_oss << this->getTransientIterationNumber();
  full_path_name += "_TIME_";
  full_path_name += time_iter_oss.str();
  // append the sensitivity information to the name
  if (this->ifSensitivityData())
    {
    std::ostringstream dv_id_oss;
    dv_id_oss << this->getDVID();
    full_path_name += "_SENS_DV_";
    full_path_name += dv_id_oss.str();
    }
  // append the load case information to the name
  if (this->ifLoadCaseDependent())
    {
    std::ostringstream lc_oss;
    lc_oss << this->getLoadCase();
    full_path_name += "_LC_";
    full_path_name += lc_oss.str();
    }
  return full_path_name;
}
unsigned int FESystemDatabase::TimeDependentDataInfo::getOrder () const
Returns:
the time derivative of the solution vector
Definition at line 431 of file DataInfo.C.
{
  Assert(this->set_order, ExcInternalError());
  return this->derivative_order;
}
const std::string FESystemDatabase::TimeDependentDataInfo::getPath () const [virtual]
Returns:
the exact path to the location of the data for this object in the database
Implements FESystemDatabase::DataInfoBase.
Reimplemented in FESystemDatabase::TimeDependentEigenDataInfo.
Definition at line 465 of file DataInfo.C.
{
  std::string full_path_name = this->getDisciplineEnumName();
  full_path_name +="_";
  full_path_name += this->getName();
  // append the derivative order
  std::ostringstream order_iter_oss;
  order_iter_oss << this->getOrder();
  full_path_name += "_ORDER_";
  full_path_name += order_iter_oss.str();
  // append the transient information to the name
  std::ostringstream time_iter_oss;
  time_iter_oss << this->getTransientIterationNumber();
  full_path_name += "_TIME_ITER_";
  full_path_name += time_iter_oss.str();
  // append the sensitivity information to the name
  if (this->ifSensitivityData())
    {
    std::ostringstream dv_id_oss;
    dv_id_oss << this->getDVID();
    full_path_name += "_SENSITIVITY_DV_";
    full_path_name += dv_id_oss.str();
    }
  // append the load case information to the name
  if (this->ifLoadCaseDependent())
    {
    std::ostringstream lc_oss;
    lc_oss << this->getLoadCase();
    full_path_name += "_LC_";
    full_path_name += lc_oss.str();
    }
  return full_path_name;
}
double FESystemDatabase::TimeDependentDataInfo::getTimeValue () const
Returns:
the time value at which this quantity is calculated
Definition at line 412 of file DataInfo.C.
References FESystemNumbers::InvalidID.
{
  Assert(this->transient_iteration_number != FESystemNumbers::InvalidID,
         ExcInternalError());
  return this->time_instant;
}
unsigned int FESystemDatabase::TimeDependentDataInfo::getTransientIterationNumber () const
Returns:
the time iteration number
Definition at line 402 of file DataInfo.C.
References FESystemNumbers::InvalidID.
{
  Assert(this->transient_iteration_number != FESystemNumbers::InvalidID,
         ExcInternalError());
  return this->transient_iteration_number;
}
bool FESystemDatabase::TimeDependentDataInfo::operator== (const FESystemDatabase::DataInfoBase & data_info) const [virtual]
Returns:
true if the given data info object and this, point to the same data
Reimplemented from FESystemDatabase::DataInfoBase.
Reimplemented in FESystemDatabase::TimeDependentEigenDataInfo.
Definition at line 572 of file DataInfo.C.
References derivative_order, time_instant, and transient_iteration_number.
{
  if (! FESystemDatabase::DataInfoBase::operator==(data_info))
    return false;
  else
    {
      const FESystemDatabase::TimeDependentDataInfo &time_data_info =
        dynamic_cast<const FESystemDatabase::TimeDependentDataInfo&>(data_info);
      // check each data and return the result
      if (this->transient_iteration_number != time_data_info.transient_iteration_number ||
          this->time_instant != time_data_info.time_instant ||
          this->derivative_order != time_data_info.derivative_order)
        return false;
    }
  // if it gets here, means that this the two objects are same
  return true;
}
void FESystemDatabase::TimeDependentDataInfo::setOrder (const unsigned int i)
sets the time derivative of the solution vector
Definition at line 422 of file DataInfo.C.
Referenced by Driver::NonlinearTransientAnalysisDriver::getCoefficientMatrices(), FESystemDatabase::TransientDataInfoSet::getDataInfoForAllTimeSteps(), Discipline::FluidAnalysis::getDataInfoForQty(), Discipline::StructuralAnalysis::getDataInfoForQty(), Discipline::ThermalAnalysis::getDataInfoForQty(), Driver::LinearTransientAnalysisDriver::getForceVector(), Driver::NonlinearTransientAnalysisDriver::getForceVector(), Discipline::ThermalAnalysis::getSolutionVector(), and Driver::UpdatedLagrangianNonlinearStructuralAnalysisDriver::setNewIteration().
{
  Assert(!this->set_order, ExcInternalError());
  this->derivative_order = i;
  this->set_order = true;
}
void FESystemDatabase::TimeDependentDataInfo::setTransientIterationInfo (const unsigned int iter_num, const double time_val)
sets the transient iteration info
Definition at line 441 of file DataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Driver::NonlinearTransientAnalysisDriver::getCoefficientMatrices(), FESystemDatabase::TransientDataInfoSet::getDataInfoForAllTimeSteps(), Discipline::FluidAnalysis::getDataInfoForQty(), Discipline::StructuralAnalysis::getDataInfoForQty(), Discipline::ThermalAnalysis::getDataInfoForQty(), Driver::LinearTransientAnalysisDriver::getForceVector(), Driver::NonlinearTransientAnalysisDriver::getForceVector(), Discipline::ThermalAnalysis::getSolutionVector(), and Driver::UpdatedLagrangianNonlinearStructuralAnalysisDriver::setNewIteration().
{
  // make sure that this object was cleared before setting new values
  Assert(this->transient_iteration_number == FESystemNumbers::InvalidID,
         ExcInternalError());
  // the given number should be valid
  Assert(iter_num > 0, ExcInternalError());
  Assert(time_val >= 0.0, ExcInternalError());
  this->transient_iteration_number = iter_num;
  this->time_instant = time_val;
}
std::ostream & FESystemDatabase::TimeDependentDataInfo::write (std::ostream & out) [virtual]
this method writes the info to an output stream
Reimplemented from FESystemDatabase::GenericDataInfoBase.
Reimplemented in FESystemDatabase::TimeDependentEigenDataInfo.
Definition at line 555 of file DataInfo.C.
References FESystemDatabase::GenericDataInfoBase::write().
Referenced by FESystemDatabase::TimeDependentEigenDataInfo::write().
{
  FESystemDatabase::GenericDataInfoBase::write(out);
  out << "Time Derivative Order :   " << this->getOrder() << std::endl;
  out << "Transient Iteration Number :   " << this->getTransientIterationNumber() << std::endl;
  out << "Time Value :   " << this->getTimeValue() << std::endl;
  return out;
}
Member Data Documentation
unsigned int FESystemDatabase::TimeDependentDataInfo::derivative_order [protected]
time derivative order of the quantity
Definition at line 306 of file DataInfo.h.
Referenced by operator==(), and TimeDependentDataInfo().
bool FESystemDatabase::TimeDependentDataInfo::set_order [protected]
boolean to keep track of whether the order was set
Definition at line 309 of file DataInfo.h.
Referenced by TimeDependentDataInfo().
double FESystemDatabase::TimeDependentDataInfo::time_instant [protected]
time value of this quantity
Definition at line 303 of file DataInfo.h.
Referenced by operator==(), and TimeDependentDataInfo().
unsigned int FESystemDatabase::TimeDependentDataInfo::transient_iteration_number [protected]
transient iteration
Definition at line 300 of file DataInfo.h.
Referenced by operator==(), and TimeDependentDataInfo().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.C