fesystem: InterpolationDriver Class Reference
InterpolationDriver Class Reference
#include <InterpolationDriver.h>
Public Member Functions
InterpolationDriver (FESystem::FESystemController &controller, InterpolationCase &interp_case)
~InterpolationDriver ()
destructor
void interpolateAndCreateLoads (const std::vector< unsigned int > &load_cases)
method to interpolate and create the loads for next analysis
FESystem::FESystemController & getFESystemController ()
returns the fesystem controller for this class
InterpolationCase & getInterpolationCase ()
returns the interpolation case for this driver
MeshDS::FEMesh * getInterpolationMesh ()
returns the interpolation mesh
MeshDS::FEMeshData * getInterpolationMeshData ()
returns the interpolation mesh data
unsigned int getInterpolationMeshID ()
returns the interpolation mesh ID
Protected Member Functions
void init ()
initialization function
void interpolate (const std::vector< unsigned int > &load_cases)
void createLoads (const std::vector< unsigned int > &load_cases)
writes loads from the interpolated values
Protected Attributes
FESystem::FESystemController & fesystem_controller
FESystemController object that owns this object.
InterpolationCase & interpolation_case
InterpolationCase for this driver.
std::auto_ptr< InterpolationBase > interpolation_base
the interpolation base that will process the interpolation
unsigned int mesh_ID
mesh ID
MeshDS::FEMesh * mesh
mesh to which data will be interpolated
MeshDS::FEMeshData * mesh_data
mesh data to which data will be interpolated
DofMap * dof_map
dofmap of the mesh to which the data will be interpolated
Detailed Description
this class will handle all aspects of interpolation. It will take the fesystem controller and the interpolation case as an argurment, and based on the interpolation kind requested it will perform the interpolation
Definition at line 35 of file InterpolationDriver.h.
Constructor & Destructor Documentation
InterpolationDriver::InterpolationDriver (FESystem::FESystemController & controller, InterpolationCase & interp_case)
constructor
Parameters:
controller the FESystemController class that owns this object #param case InterpolatinCase that this driver will solve
Definition at line 29 of file InterpolationDriver.C.
References init().
                                                                        :
fesystem_controller(controller),
interpolation_case(interp_case),
interpolation_base(NULL),
mesh(NULL),
mesh_data(NULL),
dof_map(NULL)
{
  this->init();
}
InterpolationDriver::~InterpolationDriver ()
destructor
Definition at line 45 of file InterpolationDriver.C.
{
}
Member Function Documentation
void InterpolationDriver::createLoads (const std::vector< unsigned int > & load_cases) [protected]
writes loads from the interpolated values
Definition at line 239 of file InterpolationDriver.C.
References LoadDatabase::addLoadSet(), LoadDatabase::clear(), FESystem::FESystemController::design_database, InterpolationCase::DIRECT, fesystem_controller, MeshDS::FEMeshData::getForeignIDFromNode(), LoadDatabase::getLoadSetID(), MeshDS::MeshList::getMeshDataFromID(), MeshDS::MeshList::getMeshFromID(), FESystem::FESystemController::global_data_storage, interpolation_case, FESystem::FESystemController::load_database, mesh, mesh_data, mesh_ID, FESystem::FESystemController::mesh_list, and InterpolationCase::type().
Referenced by interpolateAndCreateLoads().
{
  unsigned int load_ID = 0, load_set_ID = 0, n_nodes = 0,
  node_ID = 0, dof_number = 0, mesh_ID = 0;
  std::string interpolated_sol_name, interpolated_sol_sens_name,
  load_sens_name;
  // reference to load database and global database
  LoadDatabase& load_database =
    *(this->fesystem_controller.load_database.get());
  GlobalDataStorage& global_data_storage =
    *(this->fesystem_controller.global_data_storage.get());
  MeshDS::MeshList& mesh_list =
    *(this->fesystem_controller.mesh_list.get());
  std::auto_ptr<NumericVector<double> >
    solution(NumericVector<double>::build().release());
  // get the mesh and mesh data for the mesh to which the
  // data has been interpolated
  if (this->interpolation_case.type() == InterpolationCase::DIRECT)
    {
    interpolated_sol_name = "Thermal_Solution";
    mesh_ID = this->interpolation_case.fromMeshID();
    }
  else
    {
    interpolated_sol_name = "InterpolatedThermal_Solution";
    mesh_ID = this->interpolation_case.toMeshID();
    }
  MeshDS::FEMesh* mesh = mesh_list.getMeshFromID(mesh_ID);
  MeshDS::FEMeshData* mesh_data = mesh_list.getMeshDataFromID(mesh_ID);
//  // iterate over the load cases, and the design variables
//  // get the load case vector from the analysis load case
//  const std::vector<unsigned int>& load_cases =
//    this->fesystem_controller.analysis_case->getLoadCaseIDs();
  std::vector<unsigned int>::const_iterator load_case_it, load_case_begin,
    load_case_end;
  load_case_begin = load_cases.begin();
  load_case_end = load_cases.end();
  load_case_it = load_case_begin;
  // iterate over each load case, and get the interpolated vector from the base
  for (; load_case_it != load_case_end; load_case_it++)
    {
    // read the load vector
    global_data_storage.fillVector(*load_case_it,
                                   interpolated_sol_name,
                                   *(solution.get()));
    n_nodes = solution->size();
    // get the load case ID for this load
    // for now, this is being done for steady state
    load_set_ID = load_database.getLoadSetID(*load_case_it,
                                             0.0,
                                             NODAL_TEMPERATURE::num());
    std::stringstream load_data;
    // load set will begin with a tag and the number of nodes in it
    load_data << "BEGIN_LOAD_SET  " << n_nodes << std::endl;
    load_data << "LOAD_SET_NAME  " << NODAL_TEMPERATURE::name() << std::endl;
    load_data << "LOAD_SET_ID  " << load_set_ID << std::endl;
    load_data << "LOAD_SET_KIND  POINT_LOAD " << std::endl;
    load_data << "LOAD_SET_N_DOFS  1 " << std::endl;
    // iterate over each node in the mesh to which the
    // data is being interpolated
    load_ID = 1;
    // iterate over all nodes
    MeshBase::const_node_iterator           node  = mesh->nodes_begin();
    const MeshBase::const_node_iterator end_node  = mesh->nodes_end();
    for ( ; node != end_node; ++node)
      {
      node_ID = mesh_data->getForeignIDFromNode(*node);
      dof_number = (*node)->dof_number(0,0,0);
      load_data << load_ID << "  "
                    << node_ID << "  "
                    << std::setprecision(16) << (*solution.get())(dof_number)
                    << std::endl;
      load_ID++;
      }
    load_data << "END_LOAD_SET " << std::endl;
    // next, create a LoadSet, read it from the iostream,
    // and add it to the load_database
    std::auto_ptr<LoadSet> load_set(new LoadSet);
    load_set->readFromInputStream(load_data);
    load_ID = load_set->getLoadSetID();
    load_database.addLoadSet(load_ID,
                             load_set.release());
    }
  // now iterate over the design variables
  load_case_it = load_case_begin;
  std::auto_ptr<std::vector<DesignData::DesignParameter*> > dv_vector =
    this->fesystem_controller.design_database->getParameters();
  std::vector<DesignData::DesignParameter*>::const_iterator dv_it, dv_end;
  dv_end = dv_vector->end();
  // iterate over each load case, and ask solver to solve for it
  for (; load_case_it != load_case_end; load_case_it++)
    {
    dv_it = dv_vector->begin();
    for (; dv_it != dv_end; dv_it++)
      {
      std::ostringstream dv_ID;
      dv_ID << (*dv_it)->getID();
      // read the solution
      interpolated_sol_sens_name.clear();
      interpolated_sol_sens_name = "Thermal_dSolution";
      interpolated_sol_sens_name += "_dDV_";
      interpolated_sol_sens_name += dv_ID.str();
      global_data_storage.fillVector(*load_case_it,
                                     interpolated_sol_sens_name,
                                     *(solution.get()));
      n_nodes = solution->size();
      // get the load case ID for this load
      load_set_ID = load_database.getLoadSetIDForLoadSensitivity
        (*load_case_it, (*dv_it)->getID(), 0.0, NODAL_TEMPERATURE::num());
      std::stringstream load_data;
      load_sens_name.clear();
      load_sens_name = NODAL_TEMPERATURE::name();
      load_sens_name += "_Sens";
      // load set will begin with a tag and the number of nodes in it
      load_data << "BEGIN_LOAD_SET  " << n_nodes << std::endl;
      load_data << "LOAD_SET_NAME  " << load_sens_name << std::endl;
      load_data << "LOAD_SET_ID  " << load_set_ID << std::endl;
      load_data << "LOAD_SET_KIND  POINT_LOAD " << std::endl;
      load_data << "LOAD_SET_N_DOFS  1 " << std::endl;
      // iterate over each node in the mesh to which the
      // data is being interpolated
      load_ID = 1;
      // iterate over all nodes
      MeshBase::const_node_iterator           node  = mesh->nodes_begin();
      const MeshBase::const_node_iterator end_node  = mesh->nodes_end();
      for ( ; node != end_node; ++node)
        {
              node_ID = mesh_data->getForeignIDFromNode(*node);
              dof_number = (*node)->dof_number(0,0,0);
              load_data << load_ID << "  "
          << node_ID << "  "
          << std::setprecision(16) << (*solution.get())(dof_number)
          << std::endl;
              load_ID++;
        }
      load_data << "END_LOAD_SET " << std::endl;
      // next, create a LoadSet, read it from the iostream,
      // and add it to the load_database
      std::auto_ptr<LoadSet> load_set(new LoadSet);
      load_set->readFromInputStream(load_data);
      load_ID = load_set->getLoadSetID();
      load_database.addLoadSet(load_ID,
                               load_set.release());
      }
    }
}
FESystem::FESystemController & InterpolationDriver::getFESystemController () [inline]
returns the fesystem controller for this class
Definition at line 111 of file InterpolationDriver.h.
References fesystem_controller.
{
  return this->fesystem_controller;
}
InterpolationCase & InterpolationDriver::getInterpolationCase () [inline]
returns the interpolation case for this driver
Definition at line 119 of file InterpolationDriver.h.
References interpolation_case.
{
  return this->interpolation_case;
}
MeshDS::FEMesh * InterpolationDriver::getInterpolationMesh () [inline]
returns the interpolation mesh
Definition at line 128 of file InterpolationDriver.h.
References mesh.
{
  return this->mesh;
}
MeshDS::FEMeshData * InterpolationDriver::getInterpolationMeshData () [inline]
returns the interpolation mesh data
Definition at line 137 of file InterpolationDriver.h.
References mesh_data.
{
  return this->mesh_data;
}
unsigned int InterpolationDriver::getInterpolationMeshID () [inline]
returns the interpolation mesh ID
Definition at line 145 of file InterpolationDriver.h.
References mesh_ID.
{
  return this->mesh_ID;
}
void InterpolationDriver::init () [protected]
initialization function
Definition at line 54 of file InterpolationDriver.C.
References InterpolationCase::DIRECT, dof_map, InterpolationCase::FE, fesystem_controller, interpolation_base, interpolation_case, mesh, mesh_data, mesh_ID, FESystem::FESystemController::mesh_list, and InterpolationCase::type().
Referenced by InterpolationDriver().
{
  // the analysis here will proceede as follows
  // check the type of interpolation requested
  switch (this->interpolation_case.type())
    {
    case InterpolationCase::DIRECT:
      {
      }
      break;
    case InterpolationCase::FE:
      {
        this->interpolation_base.reset(new FEInterpolation(*this));
      }
      break;
    case InterpolationCase::LEAST_SQUARE:
      {
        //this->interpolation_base.reset
        //  (new LSInterpolation);
      }
      break;
    case InterpolationCase::SPLINE:
      {
        //      this->interpolation_base.reset
        //(new SplineInterpolation);
      }
      break;
    default:
      abort();
      break;
    }
  // init the mesh, mesh data and the dof_map for the
  // related structures, with an exception of the direct interpolation
  if (this->interpolation_case.type() == InterpolationCase::DIRECT)
    this->mesh_ID =
      this->interpolation_case.fromMeshID();
  else
    this->mesh_ID =
      this->interpolation_case.toMeshID();
  // now init the data structures
  this->mesh =
    this->fesystem_controller.mesh_list->getMeshFromID( this->mesh_ID);
  this->mesh_data =
    this->fesystem_controller.mesh_list->getMeshDataFromID( this->mesh_ID);
  this->dof_map =
    this->fesystem_controller.mesh_list->getDofMapFromID( this->mesh_ID);
}
void InterpolationDriver::interpolate (const std::vector< unsigned int > & load_cases) [protected]
interpolates the laods for all load cases and DVs and stores the interpolated solution in the database
Definition at line 130 of file InterpolationDriver.C.
References FESystem::FESystemController::design_database, fesystem_controller, FESystem::FESystemController::global_data_storage, interpolation_base, interpolation_case, and FESystem::FESystemController::mesh_list.
Referenced by interpolateAndCreateLoads().
{
  std::auto_ptr<NumericVector<double> >
  solution(NumericVector<double>::build().release()),
  interpolated_solution(NumericVector<double>::build().release());
  std::string sol_name = "Thermal_Solution",
  interpolated_sol_name = "InterpolatedThermal_Solution";
  GlobalDataStorage& global_data_storage =
    *(this->fesystem_controller.global_data_storage.get());
  DofMap& to_mesh_dof_map =
    *(this->fesystem_controller.mesh_list->getDofMapFromID
      (this->interpolation_case.toMeshID()));
//  // iterate over the load cases, and the design variables
//  // get the load case vector from the analysis load case
//  const std::vector<unsigned int>& load_cases =
//    this->fesystem_controller.analysis_case->getLoadCaseIDs();
  std::vector<unsigned int>::const_iterator load_case_it, load_case_begin,
    load_case_end;
  load_case_begin = load_cases.begin();
  load_case_end = load_cases.end();
  load_case_it = load_case_begin;
  // iterate over each load case, and get the interpolated vector from the base
  for (; load_case_it != load_case_end; load_case_it++)
    {
    // get the solution in the vector, and ask the interpolation_base
    // to return the interpolated solution
    global_data_storage.fillVector(*load_case_it,
                                   sol_name,
                                   *(solution.get()));
    if (!interpolated_solution->initialized() ||
        interpolated_solution->size() != to_mesh_dof_map.n_dofs())
      interpolated_solution->init(to_mesh_dof_map.n_dofs());
    this->interpolation_base->getInterpolatedValues((*solution.get()),
                                                    (*interpolated_solution.get()));
    // save the interpolated value
    this->fesystem_controller.global_data_storage->storeVector
      (*load_case_it,
       interpolated_sol_name,
       (*interpolated_solution.get()));
    }
  // now iterate over the design variables
  load_case_it = load_case_begin;
  std::auto_ptr<std::vector<DesignData::DesignParameter*> > dv_vector =
    this->fesystem_controller.design_database->getParameters();
  std::vector<DesignData::DesignParameter*>::const_iterator dv_it, dv_end;
  dv_end = dv_vector->end();
  std::string sol_sens_name, interpolated_sol_sens_name;
  // iterate over each load case, and ask solver to solve for it
  for (; load_case_it != load_case_end; load_case_it++)
    {
    dv_it = dv_vector->begin();
    for (; dv_it != dv_end; dv_it++)
      {
      // create the solution name
      std::ostringstream dv_ID;
      dv_ID << (*dv_it)->getID();
      sol_sens_name.clear();
      sol_sens_name = "d";
      sol_sens_name += sol_name;
      sol_sens_name += "_dDV";
      sol_sens_name += dv_ID.str();
      interpolated_sol_sens_name.clear();
      interpolated_sol_sens_name = "d";
      interpolated_sol_sens_name += interpolated_sol_name;
      interpolated_sol_sens_name += "_dDV";
      interpolated_sol_sens_name += dv_ID.str();
      // get the solution in the vector, and ask the interpolation_base
      // to return the interpolated solution
      global_data_storage.fillVector(*load_case_it,
                                     sol_sens_name,
                                     *(solution.get()));
      if (interpolated_solution->size() != to_mesh_dof_map.n_dofs())
        interpolated_solution->init(to_mesh_dof_map.n_dofs());
      this->interpolation_base->getInterpolatedValues((*solution.get()),
                                                      (*interpolated_solution.get()));
      // save the interpolated value
      this->fesystem_controller.global_data_storage->storeVector
        (*load_case_it,
         interpolated_sol_sens_name,
         (*interpolated_solution.get()));
      }
    }
}
void InterpolationDriver::interpolateAndCreateLoads (const std::vector< unsigned int > & load_cases)
method to interpolate and create the loads for next analysis
Definition at line 113 of file InterpolationDriver.C.
References createLoads(), InterpolationCase::DIRECT, interpolate(), interpolation_case, and InterpolationCase::type().
{
  // if this is not direct transfer of loads,
  // interpolate, else just create loads
  if (this->interpolation_case.type() != InterpolationCase::DIRECT)
    {
    this->interpolate(load_cases);
    }
  // create loads after interpolation is done
  this->createLoads(load_cases);
}
Member Data Documentation
DofMap* InterpolationDriver::dof_map [protected]
dofmap of the mesh to which the data will be interpolated
Definition at line 103 of file InterpolationDriver.h.
Referenced by init().
FESystem::FESystemController& InterpolationDriver::fesystem_controller [protected]
FESystemController object that owns this object.
Definition at line 85 of file InterpolationDriver.h.
Referenced by createLoads(), getFESystemController(), init(), and interpolate().
std::auto_ptr<InterpolationBase> InterpolationDriver::interpolation_base [protected]
the interpolation base that will process the interpolation
Definition at line 91 of file InterpolationDriver.h.
Referenced by init(), and interpolate().
InterpolationCase& InterpolationDriver::interpolation_case [protected]
InterpolationCase for this driver.
Definition at line 88 of file InterpolationDriver.h.
Referenced by createLoads(), getInterpolationCase(), init(), interpolate(), and interpolateAndCreateLoads().
MeshDS::FEMesh* InterpolationDriver::mesh [protected]
mesh to which data will be interpolated
Definition at line 97 of file InterpolationDriver.h.
Referenced by createLoads(), getInterpolationMesh(), and init().
MeshDS::FEMeshData* InterpolationDriver::mesh_data [protected]
mesh data to which data will be interpolated
Definition at line 100 of file InterpolationDriver.h.
Referenced by createLoads(), getInterpolationMeshData(), and init().
unsigned int InterpolationDriver::mesh_ID [protected]
mesh ID
Definition at line 94 of file InterpolationDriver.h.
Referenced by createLoads(), getInterpolationMeshID(), and init().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Interpolation/InterpolationDriver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Interpolation/InterpolationDriver.C