fesystem: Solution::ThermalSolution Class Reference
Solution::ThermalSolution Class Reference
this class provides the base functionality for all solutions
#include <ThermalSolution.h>
Public Member Functions
ThermalSolution ()
constructor
virtual ~ThermalSolution ()
destructor
virtual void solve ()
solves the problem
virtual unsigned int getDisciplineTransientNatureEnumID (const unsigned int discipline) const
virtual
FESystemUtility::AutoPtrVector
< FESystemDatabase::DataInfoBase > getTimeIndependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID)
virtual
FESystemUtility::AutoPtrVector
< FESystemDatabase::TransientDataInfoSet > getTimeDependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID)
virtual std::istream & readFromInputStream (std::istream &input)
will read from the input stream
Detailed Description
this class provides the base functionality for all solutions
Definition at line 42 of file ThermalSolution.h.
Constructor & Destructor Documentation
Solution::ThermalSolution::ThermalSolution ()
constructor
Definition at line 13 of file ThermalSolution.C.
References Solution::SolutionBase::addParticipatingDiscipline().
                                        :
Solution::SolutionBase(Solution::THERMAL_SOLUTION::num())
{
  // add the participating discipline to this solution
  this->addParticipatingDiscipline(Discipline::THERMAL_DISCIPLINE::num());
}
Solution::ThermalSolution::~ThermalSolution () [virtual]
destructor
Definition at line 22 of file ThermalSolution.C.
{
}
Member Function Documentation
unsigned int Solution::ThermalSolution::getDisciplineTransientNatureEnumID (const unsigned int discipline) const [virtual]
Returns:
the transient nature of the given discipline
Implements Solution::SolutionBase.
Definition at line 30 of file ThermalSolution.C.
References THERMAL_DISCIPLINE_ENUM_ID.
{
  unsigned int enum_ID = 0;
  switch (discipline)
    {
    case THERMAL_DISCIPLINE_ENUM_ID:
      enum_ID = Discipline::STEADY_STATE_SOLUTION::num();
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return enum_ID;
}
FESystemUtility::AutoPtrVector< FESystemDatabase::TransientDataInfoSet > Solution::ThermalSolution::getTimeDependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID) [virtual]
Returns:
the vector of SolNameInfo structures for the nodal solutions, and for the specified disciplines
Implements Solution::SolutionBase.
Definition at line 179 of file ThermalSolution.C.
{
  // unused parameter
  (void) discipline_enum_ID;
  // this solution does not have any transients. Hence, return an empty vector
  FESystemUtility::AutoPtrVector<FESystemDatabase::TransientDataInfoSet> vec;
  return vec;
}
FESystemUtility::AutoPtrVector< FESystemDatabase::DataInfoBase > Solution::ThermalSolution::getTimeIndependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID) [virtual]
Returns:
the vector of SolNameInfo structures for the nodal solutions, and for the specified disciplines
Implements Solution::SolutionBase.
Definition at line 121 of file ThermalSolution.C.
References FESystemUtility::AutoPtrVector< T >::reset(), FESystemUtility::AutoPtrVector< T >::resize(), FESystemDatabase::GenericDataInfoBase::setDisciplineEnumID(), FESystemDatabase::GenericDataInfoBase::setDVID(), FESystemDatabase::GenericDataInfoBase::setLoadCase(), FESystemDatabase::GenericDataInfoBase::setName(), and THERMAL_DISCIPLINE_ENUM_ID.
{
  FESystemUtility::AutoPtrVector<FESystemDatabase::DataInfoBase> data_info_vec;
  switch (discipline_enum_ID)
    {
    case THERMAL_DISCIPLINE_ENUM_ID:
      {
        std::auto_ptr<std::vector<DesignData::DesignParameter*> >
          dv_vector(this->fesystem_controller->design_database->getParameters().release());
        data_info_vec.resize(this->load_case_IDs.size() * (1 + dv_vector->size()));
        FESystemDatabase::DataInfoBase *data_info  = NULL;
        unsigned int location_id = 0;
        // iterate over each load case and DV and add the solutions
        for (unsigned int i=0; i < this->load_case_IDs.size(); i++)
          {
            data_info = new FESystemDatabase::TimeIndependentDataInfo;
            data_info->setDisciplineEnumID(Discipline::THERMAL_DISCIPLINE::num());
            data_info->setName("Solution");
            data_info->setLoadCase(this->load_case_IDs[i]);
            data_info_vec.reset(location_id, data_info);
            location_id++;
            data_info = NULL;
          }
        for (unsigned int i=0; i < this->load_case_IDs.size(); i++)
          for (unsigned int j=0; j < dv_vector->size(); j++)
            {
              data_info = new FESystemDatabase::TimeIndependentDataInfo;
              data_info->setDisciplineEnumID(Discipline::THERMAL_DISCIPLINE::num());
              data_info->setName("Solution");
              data_info->setLoadCase(this->load_case_IDs[i]);
              data_info->setDVID((*dv_vector)[j]->getID());
              data_info_vec.reset(location_id, data_info);
              location_id++;
        data_info = NULL;
            }
      }
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return data_info_vec;
}
std::istream & Solution::ThermalSolution::readFromInputStream (std::istream & input) [virtual]
will read from the input stream
Implements Solution::SolutionBase.
Definition at line 76 of file ThermalSolution.C.
References FESystemIOUtility::readFromInput().
{
  std::string tag;
  unsigned int num = 0;
  FESystemIOUtility::readFromInput(input, Solution::SolutionEnum::enumName(this->solution_enum_ID));
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->ID);
  // Read in the list of load cases
  unsigned int case_ID =0;
  FESystemIOUtility::readFromInput(input, "N_ANALYSIS_LOAD_CASES", num);
  for (unsigned int case_it =0; case_it < num; case_it++)
    {
    case_ID = 0;
    input >> case_ID;
    this->load_case_IDs.push_back(case_ID);
    }
  FESystemIOUtility::readFromInput(input, "N_SOLVER_INFO_ID", num);
  unsigned int solver_class = 0, info_id = 0;
  for (unsigned int i=0; i < num; i++)
    {
    tag.clear();
    input >> tag;
    solver_class = Solver::SolverClassEnum::enumID(tag);
    input >> info_id;
    this->addSolverID(solver_class, info_id);
    }
  FESystemIOUtility::readFromInput(input, Solution::SolutionEnum::enumName(this->solution_enum_ID));
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
void Solution::ThermalSolution::solve () [virtual]
solves the problem
Implements Solution::SolutionBase.
Definition at line 50 of file ThermalSolution.C.
References Discipline::DisciplineInfo::getAnalysisTypeEnumID(), info, LINEAR_ANALYSIS_ENUM_ID, and NONLINEAR_ANALYSIS_ENUM_ID.
{
  const Discipline::DisciplineInfo& info =
    this->fesystem_controller->analysis_case->getAnalysisDisciplineInfo
    (Discipline::THERMAL_DISCIPLINE::num());
  switch (info.getAnalysisTypeEnumID())
    {
    case LINEAR_ANALYSIS_ENUM_ID:
      this->linearSolve(Discipline::THERMAL_DISCIPLINE::num());
      break;
    case NONLINEAR_ANALYSIS_ENUM_ID:
      this->nonlinearSolve(Discipline::THERMAL_DISCIPLINE::num());
      break;
    default:
      Assert(false, ExcInternalError());
      break;
    }
}
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solutions/ThermalSolution.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solutions/ThermalSolution.C