fesystem: Loads::SurfaceLoadCombination Class Reference
Loads::SurfaceLoadCombination Class Reference
#include <LoadCombination.h>
Public Member Functions
SurfaceLoadCombination ()
virtual ~SurfaceLoadCombination ()
virtual unsigned int nLoads () const
unsigned int getElemID () const
unsigned int getSurfaceID () const
virtual void addLoad (const double factor, const SurfaceLoad *load_ptr)=0
Protected Attributes
std::set< const SurfaceLoad * > load_set
Detailed Description
Definition at line 151 of file LoadCombination.h.
Constructor & Destructor Documentation
Loads::SurfaceLoadCombination::SurfaceLoadCombination () [inline]
Definition at line 154 of file LoadCombination.h.
                              :
      LoadCombinationBase()
      {
      }
virtual Loads::SurfaceLoadCombination::~SurfaceLoadCombination () [inline, virtual]
Definition at line 160 of file LoadCombination.h.
      {
      }
Member Function Documentation
virtual void Loads::SurfaceLoadCombination::addLoad (const double factor, const SurfaceLoad * load_ptr) [pure virtual]
Implemented in Loads::SurfaceRadiationLoadCombination, Loads::SurfaceConvectionLoadCombination, and Loads::ScalarSurfaceLoadCombination.
unsigned int Loads::SurfaceLoadCombination::getElemID () const [inline]
Definition at line 176 of file LoadCombination.h.
References load_set, and nLoads().
Referenced by Loads::ScalarSurfaceLoadCombination::addLoad(), Loads::SurfaceConvectionLoadCombination::addLoad(), and Loads::SurfaceRadiationLoadCombination::addLoad().
      {
        Assert(this->nLoads() > 0, ExcInternalError());
        return (*this->load_set.begin())->getElemID();
      }
unsigned int Loads::SurfaceLoadCombination::getSurfaceID () const [inline]
Definition at line 182 of file LoadCombination.h.
References load_set, and nLoads().
Referenced by Loads::ScalarSurfaceLoadCombination::addLoad(), Loads::SurfaceConvectionLoadCombination::addLoad(), and Loads::SurfaceRadiationLoadCombination::addLoad().
      {
        Assert(this->nLoads() > 0, ExcInternalError());
        return (*this->load_set.begin())->getSurfaceID();
      }
virtual unsigned int Loads::SurfaceLoadCombination::nLoads () const [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 171 of file LoadCombination.h.
References load_set.
Referenced by Loads::ScalarSurfaceLoadCombination::addLoad(), getElemID(), Discipline::AnalysisDisciplineBase::getElemLoads(), and getSurfaceID().
      {
        return this->load_set.size();
      }
Member Data Documentation
std::set<const SurfaceLoad*> Loads::SurfaceLoadCombination::load_set [protected]
Definition at line 192 of file LoadCombination.h.
Referenced by Loads::ScalarSurfaceLoadCombination::addLoad(), Loads::SurfaceConvectionLoadCombination::addLoad(), Loads::SurfaceRadiationLoadCombination::addLoad(), Loads::ScalarSurfaceLoadCombination::clear(), Loads::SurfaceConvectionLoadCombination::clear(), Loads::SurfaceRadiationLoadCombination::clear(), getElemID(), getSurfaceID(), and nLoads().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCombination.h