fesystem: Loads::DirichletBoundaryConditionCombination Class Reference
Loads::DirichletBoundaryConditionCombination Class Reference
#include <LoadCombination.h>
Public Member Functions
DirichletBoundaryConditionCombination ()
virtual ~DirichletBoundaryConditionCombination ()
virtual unsigned int getLoadClassEnumID () const
void clear ()
double getValue () const
unsigned int getDofNumber () const
void addLoad (const double factor, const NodalLoad *load_ptr)
Protected Attributes
double value
Detailed Description
Definition at line 502 of file LoadCombination.h.
Constructor & Destructor Documentation
Loads::DirichletBoundaryConditionCombination::DirichletBoundaryConditionCombination () [inline]
Definition at line 505 of file LoadCombination.h.
                                             :
      NodalLoadCombination(),
      value(0.0)
      {
      }
virtual Loads::DirichletBoundaryConditionCombination::~DirichletBoundaryConditionCombination () [inline, virtual]
Definition at line 513 of file LoadCombination.h.
      {
      }
Member Function Documentation
void Loads::DirichletBoundaryConditionCombination::addLoad (const double factor, const NodalLoad * load_ptr) [inline, virtual]
Implements Loads::NodalLoadCombination.
Definition at line 539 of file LoadCombination.h.
References getDofNumber(), LoadBase::getLoadClassEnumID(), Loads::NodalLoadCombination::getNodeID(), Loads::NodalLoadCombination::load_set, Loads::NodalLoadCombination::nLoads(), and value.
      {
        Assert(load_ptr != NULL, ExcInternalError());
        Assert(load_ptr->getLoadClassEnumID() == DIRICHLET_BOUNDARY_CONDITION::num(),
               ExcInternalError());
        const DirichletBoundaryCondition* ptr =
        dynamic_cast<const DirichletBoundaryCondition*>(load_ptr);
        // set the node ID
        if (this->nLoads() > 0)
          Assert(this->getNodeID() == ptr->getNodeID() &&
                 this->getDofNumber() == ptr->getDofNumber(), ExcInternalError());
        bool insert_success = this->load_set.insert(load_ptr).second;
        // add this pointer to the set, and adjust the value of the load
        Assert(insert_success, ExcInternalError());
        this->value += factor * ptr->getValue();
      }
void Loads::DirichletBoundaryConditionCombination::clear () [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 523 of file LoadCombination.h.
References value.
Referenced by LoadDatabase::getAllLoadCombinations< Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination >().
      {
        this->value = 0.0;
      }
unsigned int Loads::DirichletBoundaryConditionCombination::getDofNumber () const [inline]
Definition at line 533 of file LoadCombination.h.
References Loads::NodalLoadCombination::load_set, and Loads::NodalLoadCombination::nLoads().
Referenced by addLoad().
      {
        Assert(this->nLoads() > 0, ExcInternalError());
        return dynamic_cast<const DirichletBoundaryCondition*>(*this->load_set.begin())->getDofNumber();
      }
virtual unsigned int Loads::DirichletBoundaryConditionCombination::getLoadClassEnumID () const [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 518 of file LoadCombination.h.
      {
        return DIRICHLET_BOUNDARY_CONDITION::num();
      }
double Loads::DirichletBoundaryConditionCombination::getValue () const [inline]
Definition at line 528 of file LoadCombination.h.
References value.
      {
        return this->value;
      }
Member Data Documentation
double Loads::DirichletBoundaryConditionCombination::value [protected]
Definition at line 563 of file LoadCombination.h.
Referenced by addLoad(), clear(), and getValue().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCombination.h