fesystem: Solution::AeroelasticitySolution Class Reference
Solution::AeroelasticitySolution Class Reference
This is the solution class of the aeroelasticity solution using the panel methods.
#include <AeroelasticitySolution.h>
Public Member Functions
AeroelasticitySolution ()
constructor
virtual ~AeroelasticitySolution ()
destructor
virtual void solve ()
this method will solve for all the load cases and sensitivity analysis
virtual unsigned int getDisciplineTransientNatureEnumID (const unsigned int discipline) const
virtual
FESystemUtility::AutoPtrVector
< FESystemDatabase::DataInfoBase > getTimeIndependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID)
virtual
FESystemUtility::AutoPtrVector
< FESystemDatabase::TransientDataInfoSet > getTimeDependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID)
virtual std::istream & readFromInputStream (std::istream &input)
will read from the input stream
bool ifIncludeGeometricEffects () const
unsigned int getSolutionMethodEnumID () const
returns the analysis driver enumeration ID to be used in the solution
unsigned int getSolutionMethodEnumName () const
returns the analysis driver enumeration name to be used in the solution
virtual unsigned int numberOfAerodynamicLagTerms () const
unsigned int getAeroelasticDriverEnumID () const
unsigned int getAerodynamicDisciplineEnumID () const
const std::vector
< Loads::FlightCondition > & getFlightConditionVector () const
Protected Member Functions
void aeroelasticSolve ()
the solution sequeunce for a generaic aeroelastic eigenvalue analyis
Protected Attributes
bool use_modal_order_reduction
whether modal order reduction is to be used
bool coupled_thermoelastic
whether coupled thermal structural analysis is to be performed (unidirectional coupling)
bool include_geometric_effects
whether thermal geometric effects should be included
bool completed_linear_solve
linear solution completed
unsigned int interpolation_case_ID
interpolation case ID for coupled thermal structural solution
unsigned int n_lag_terms
number of lag terms
unsigned int aerodynamic_discipline_enum_ID
aerodynamic discipline enumeration ID
unsigned int aeroelastic_driver_enum_ID
aeroelastic method enumeration ID
std::vector
< Loads::FlightCondition > flight_condition_vector
vector of dynamic pressures
Detailed Description
This is the solution class of the aeroelasticity solution using the panel methods.
Definition at line 50 of file AeroelasticitySolution.h.
Constructor & Destructor Documentation
Solution::AeroelasticitySolution::AeroelasticitySolution ()
constructor
Definition at line 33 of file AeroelasticitySolution.C.
References Solution::SolutionBase::addParticipatingDiscipline().
                                                      :
Solution::SolutionBase(Solution::AEROELASTICITY_SOLUTION::num()),
use_modal_order_reduction(false),
coupled_thermoelastic(false),
include_geometric_effects(false),
completed_linear_solve(false),
interpolation_case_ID(0),
n_lag_terms(0),
aerodynamic_discipline_enum_ID(0),
aeroelastic_driver_enum_ID(0)
{
  // add the participating discipline to this solution
  this->addParticipatingDiscipline(Discipline::STRUCTURAL_DISCIPLINE::num());
}
Solution::AeroelasticitySolution::~AeroelasticitySolution () [virtual]
destructor
Definition at line 50 of file AeroelasticitySolution.C.
{
}
Member Function Documentation
void Solution::AeroelasticitySolution::aeroelasticSolve () [protected]
the solution sequeunce for a generaic aeroelastic eigenvalue analyis
Definition at line 137 of file AeroelasticitySolution.C.
References Driver::AnalysisDriver::attachAnalysisDiscipline(), Discipline::AnalysisDisciplineBase::attachSolution(), Driver::AnalysisDriver::attachSolution(), Driver::AnalysisDriver::attachSolver(), Discipline::AnalysisDisciplineBase::clear(), Driver::AnalysisDriver::clear(), Solver::createEigenSolver(), Solver::createLinearSolver(), Solver::EigenSolverInfo::getLinearSolverInfoID(), Driver::AnalysisDriver::solveForLoadCases(), and Driver::AnalysisDriver::solveForLoadCaseSensitivity().
{
  // next, get the discipline and drivers for this analysis
  Discipline::AnalysisDisciplineBase * structural_discipline =
  this->fesystem_controller->getAnalysisDiscipline(Discipline::STRUCTURAL_DISCIPLINE::num());
  structural_discipline->clear();
  structural_discipline->attachSolution(this);
  Discipline::AnalysisDisciplineBase * aero_discipline =
  this->fesystem_controller->getAnalysisDiscipline(this->getAerodynamicDisciplineEnumID());
  aero_discipline->clear();
  aero_discipline->attachSolution(this);
  // get the driver and initialize it
  unsigned int driver_enum_ID = this->getAeroelasticDriverEnumID();
  Driver::AnalysisDriver *driver =
  this->fesystem_controller->getAnalysisDriver(driver_enum_ID);
  // attach the discipline and driver to each other
  driver->clear();
  driver->attachAnalysisDiscipline(structural_discipline);
  driver->attachAnalysisDiscipline(aero_discipline);
  driver->attachSolution(this);
  // get the load cases and design variables to be solved for
  std::auto_ptr<std::vector<DesignData::DesignParameter*> >
  dv_vector(this->fesystem_controller->design_database->getParameters().release());
  // next, peform the analysis
  this->fesystem_controller->initPropertyCardsForGlobalParameters();
  // attach a nonlinear solver to the driver and perform the nonlinear analysis
  unsigned int eigen_solver_info_id = this->getSolverInfoID(Solver::EIGEN_SOLVER::num());
  const Solver::EigenSolverInfo& eigen_info =
  dynamic_cast<const Solver::EigenSolverInfo&>
  (this->fesystem_controller->analysis_case->getSolverInfo(eigen_solver_info_id));
  unsigned int linear_info_ID = eigen_info.getLinearSolverInfoID();
  const Solver::LinearSolverInfo& linear_info =
  dynamic_cast<const Solver::LinearSolverInfo&>
  (this->fesystem_controller->analysis_case->getSolverInfo(linear_info_ID));
  std::auto_ptr<Solver::FESystemSolverBase>
  solver(Solver::createEigenSolver(eigen_info, linear_info).release());
  solver->clear();
  driver->attachSolver(solver.get());
  driver->solveForLoadCases(this->load_case_IDs);
  solver->clear();
  // if there are any DVs, then attach the linear solver and perform
  // sensitivity analysis
  if (dv_vector->size() > 0)
    {
      unsigned int solver_info_id = this->getSolverInfoID(Solver::LINEAR_SOLVER::num());
      const Solver::LinearSolverInfo& sol_linear_info =
      dynamic_cast<const Solver::LinearSolverInfo&>
      (this->fesystem_controller->analysis_case->getSolverInfo(solver_info_id));
      solver.reset(Solver::createLinearSolver(sol_linear_info).release());
      solver->clear();
      driver->attachSolver(solver.get());
      driver->solveForLoadCaseSensitivity(*(dv_vector.get()), this->load_case_IDs);
      solver->clear();
    }
  //  driver->postProcess();
  // now clear the initializations
  this->fesystem_controller->property_database->clearLocalParameterInitializationForAllCards();
  this->fesystem_controller->property_database->clearGlobalParameterInitializationForAllCards();
  // now clear the data structures before returning
  structural_discipline->clear();
  aero_discipline->clear();
  driver->clear();
}
unsigned int Solution::AeroelasticitySolution::getAerodynamicDisciplineEnumID () const
Returns:
the enumeration ID of the kind of aerodynamic discipline modeling to be used
Definition at line 96 of file AeroelasticitySolution.C.
Referenced by Driver::AeroelasticityAnalysisDriverBase::getAerodynamicDiscipline().
{
  return this->aerodynamic_discipline_enum_ID;
}
unsigned int Solution::AeroelasticitySolution::getAeroelasticDriverEnumID () const
Returns:
the enumeration ID of the kind of aeroelastic analysis driver
Definition at line 87 of file AeroelasticitySolution.C.
{
  return this->aeroelastic_driver_enum_ID;
}
unsigned int Solution::AeroelasticitySolution::getDisciplineTransientNatureEnumID (const unsigned int discipline) const [virtual]
Returns:
the transient nature of the given discipline
Implements Solution::SolutionBase.
Definition at line 59 of file AeroelasticitySolution.C.
References STRUCTURAL_DISCIPLINE_ENUM_ID.
{
  unsigned int enum_ID = 0;
  switch (discipline)
  {
    case STRUCTURAL_DISCIPLINE_ENUM_ID:
      enum_ID = Discipline::STEADY_STATE_SOLUTION::num();
      break;
    default:
      Assert(false, ExcInternalError());
  }
  return enum_ID;
}
const std::vector< Loads::FlightCondition > & Solution::AeroelasticitySolution::getFlightConditionVector () const
Returns:
a reference to the vector of flight conditions for which aeroelastic analysis needs to be performed
Definition at line 104 of file AeroelasticitySolution.C.
Referenced by Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
{
  return this->flight_condition_vector;
}
unsigned int Solution::AeroelasticitySolution::getSolutionMethodEnumID () const
returns the analysis driver enumeration ID to be used in the solution
unsigned int Solution::AeroelasticitySolution::getSolutionMethodEnumName () const
returns the analysis driver enumeration name to be used in the solution
FESystemUtility::AutoPtrVector< FESystemDatabase::TransientDataInfoSet > Solution::AeroelasticitySolution::getTimeDependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID) [virtual]
Returns:
the vector of SolNameInfo structures for the nodal solutions, and for the specified disciplines
Implements Solution::SolutionBase.
Definition at line 399 of file AeroelasticitySolution.C.
{
  // unused parameter
  (void) discipline_enum_ID;
  // this solution does not have any transients. Hence, return an empty vector
  FESystemUtility::AutoPtrVector<FESystemDatabase::TransientDataInfoSet> vec;
  return vec;
}
FESystemUtility::AutoPtrVector< FESystemDatabase::DataInfoBase > Solution::AeroelasticitySolution::getTimeIndependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID) [virtual]
Returns:
the vector of SolNameInfo structures for the nodal solutions, and for the specified disciplines
Implements Solution::SolutionBase.
Definition at line 311 of file AeroelasticitySolution.C.
References FESystemUtility::AutoPtrVector< T >::push_back(), FESystemDatabase::GenericDataInfoBase::setDisciplineEnumID(), FESystemDatabase::GenericDataInfoBase::setLoadCase(), FESystemDatabase::GenericDataInfoBase::setName(), and STRUCTURAL_DISCIPLINE_ENUM_ID.
{
  FESystemUtility::AutoPtrVector<FESystemDatabase::DataInfoBase> data_info_vec;
  switch (discipline_enum_ID)
  {
    case STRUCTURAL_DISCIPLINE_ENUM_ID:
    {
      std::auto_ptr<std::vector<DesignData::DesignParameter*> >
      dv_vector(this->fesystem_controller->design_database->getParameters().release());
      FESystemDatabase::TimeIndependentDataInfo eig_val_data_info;
      FESystemDatabase::DataInfoBase *data_info  = NULL;
      DenseVector<double> eig_value_real;
      const std::vector<Loads::FlightCondition>& flt_conds = this->getFlightConditionVector();
      for (unsigned int ii=0; ii<flt_conds.size(); ii++)
        {
          std::ostringstream oss_eigval_name_real;
          oss_eigval_name_real << "RogerEigenValue_Real_FltCond_" << ii;
          // first get the number of converged eigen values for this load case
          eig_val_data_info.clear();
          eig_val_data_info.setDisciplineEnumID(Discipline::STRUCTURAL_DISCIPLINE::num());
          eig_val_data_info.setName(oss_eigval_name_real.str());
          eig_val_data_info.setLoadCase(1);
          this->fesystem_controller->global_data_storage->fillVector
          (eig_val_data_info, eig_value_real);
          for (unsigned int j=0; j < eig_value_real.size(); j++)
            {
              std::ostringstream oss_str_eigvec_name_real;
              oss_str_eigvec_name_real << "EigenVector_Real_FltCond_" << ii;
              data_info = new FESystemDatabase::TimeIndependentEigenDataInfo;
              data_info->setDisciplineEnumID(Discipline::STRUCTURAL_DISCIPLINE::num());
              data_info->setName(oss_str_eigvec_name_real.str());
              data_info->setLoadCase(1);
              dynamic_cast<FESystemDatabase::TimeIndependentEigenDataInfo*>(data_info)->setModeInfo(j+1);
              data_info_vec.push_back(data_info);
              data_info = NULL;
            }
//          for (unsigned int i=0; i < this->load_case_IDs.size(); i++)
//            for (unsigned int j=0; j < dv_vector->size(); j++)
//              {
//                // first get the number of converged eigen values for this load case
//                eig_val_data_info.clear();
//                eig_val_data_info.setDisciplineEnumID(Discipline::STRUCTURAL_DISCIPLINE::num());
//                eig_val_data_info.setName("EigenValuesReal");
//                eig_val_data_info.setLoadCase(this->load_case_IDs[i]);
//                eig_val_data_info.setDVID((*dv_vector)[j]->getID());
//                this->fesystem_controller->global_data_storage->fillVector(eig_val_data_info,
//                                                                           eig_value_real);
//
//                for (unsigned int k=0; k < eig_value_real.size(); k++)
//                  {
//                    data_info = new FESystemDatabase::TimeIndependentEigenDataInfo;
//
//                    data_info->setDisciplineEnumID(Discipline::STRUCTURAL_DISCIPLINE::num());
//                    data_info->setName("EigenVector_Real");
//                    data_info->setLoadCase(this->load_case_IDs[i]);
//                    data_info->setDVID((*dv_vector)[j]->getID());
//                    dynamic_cast<FESystemDatabase::TimeIndependentEigenDataInfo*>(data_info)->setModeInfo(k+1);
//
//                    data_info_vec.push_back(data_info);
//                    data_info = NULL;
//                  }
//              }
        }
    }
      break;
    default:
      Assert(false, ExcInternalError());
  }
  return data_info_vec;
}
bool Solution::AeroelasticitySolution::ifIncludeGeometricEffects () const
Returns:
true if the geometric effects are to be included
Definition at line 111 of file AeroelasticitySolution.C.
{
  bool val = false;
  if (this->include_geometric_effects && this->completed_linear_solve)
    val = true;
  return val;
}
unsigned int Solution::AeroelasticitySolution::numberOfAerodynamicLagTerms () const [virtual]
Returns:
the number of lag terms for this solution
Definition at line 79 of file AeroelasticitySolution.C.
Referenced by Driver::RogerApproximationAeroelasticityDriver::addMatricesAndVectors(), and Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
{
  return this->n_lag_terms;
}
std::istream & Solution::AeroelasticitySolution::readFromInputStream (std::istream & input) [virtual]
will read from the input stream
Implements Solution::SolutionBase.
Definition at line 220 of file AeroelasticitySolution.C.
References FESystemIOUtility::readFromInput(), Loads::FlightCondition::setDensity(), Loads::FlightCondition::setDynamicPressure(), Loads::FlightCondition::setFluidFlowVector(), and Loads::FlightCondition::setMachNumber().
{
  std::string tag;
  unsigned int num = 0;
  FESystemIOUtility::readFromInput(input, Solution::AEROELASTICITY_SOLUTION::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->ID);
  // read the aerodynamic discipline enum
  tag.clear();
  FESystemIOUtility::readFromInput(input, "AERODYNAMIC_DISCIPLINE", tag);
  this->aerodynamic_discipline_enum_ID = Discipline::AnalysisDisciplineEnum::enumID(tag);
  // read the aeroelasticity solution kind enum
  tag.clear();
  FESystemIOUtility::readFromInput(input, "SOLUTION_METHOD", tag);
  this->aeroelastic_driver_enum_ID = Driver::AnalysisDriverTypeEnum::enumID(tag);
  FESystemIOUtility::readFromInput(input, "COUPLED_THERMAL_STRUCTURAL", this->coupled_thermoelastic);
  FESystemIOUtility::readFromInput(input, "GEOMETRIC_EFFECTS", this->include_geometric_effects);
  if (this->coupled_thermoelastic)
    {
      this->addParticipatingDiscipline(Discipline::THERMAL_DISCIPLINE::num());
      FESystemIOUtility::readFromInput(input, "INTERPOLATION_CASE_ID",
                                       this->interpolation_case_ID);
    }
  // Read in the list of load cases
  unsigned int case_ID =0;
  FESystemIOUtility::readFromInput(input, "N_ANALYSIS_LOAD_CASES", num);
  for (unsigned int case_it =0; case_it < num; case_it++)
    {
      case_ID = 0;
      input >> case_ID;
      this->load_case_IDs.push_back(case_ID);
    }
  // read the dynamic pressure and mach numbers
  double val = 0.0;
  Loads::FlightCondition flt_cond;
  Point vec;
  FESystemIOUtility::readFromInput(input, "N_FLIGHT_CONDITIONS", num);
  for (unsigned int i=0; i < num; i++)
    {
      FESystemIOUtility::readFromInput(input, "MACH_NUMBER", val);
      flt_cond.setMachNumber(val);
      FESystemIOUtility::readFromInput(input, "DENSITY", val);
      flt_cond.setDensity(val);
      FESystemIOUtility::readFromInput(input, "DYNAMIC_PRESSURE", val);
      flt_cond.setDynamicPressure(val);
      FESystemIOUtility::readFromInput(input, "FLUID_FLOW_VECTOR");
      for (unsigned int i=0; i < 3; i++)
        {
          input >> val;
          vec(i) = val;
        }
      flt_cond.setFluidFlowVector(vec);
      this->flight_condition_vector.push_back(flt_cond);
    }
  FESystemIOUtility::readFromInput(input, "N_SOLVER_INFO_ID", num);
  unsigned int solver_class = 0, info_id = 0;
  for (unsigned int i=0; i < num; i++)
    {
      tag.clear();
      input >> tag;
      solver_class = Solver::SolverClassEnum::enumID(tag);
      input >> info_id;
      this->addSolverID(solver_class, info_id);
    }
  FESystemIOUtility::readFromInput(input, Solution::AEROELASTICITY_SOLUTION::name());
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
void Solution::AeroelasticitySolution::solve () [virtual]
this method will solve for all the load cases and sensitivity analysis
Implements Solution::SolutionBase.
Definition at line 123 of file AeroelasticitySolution.C.
{
  // solve the linear system if the geometric effects are needed
  if (this->include_geometric_effects)
    this->linearSolve(Discipline::STRUCTURAL_DISCIPLINE::num());
  this->completed_linear_solve = true;
  // solve the eigen problem
  this->aeroelasticSolve();
}
Member Data Documentation
unsigned int Solution::AeroelasticitySolution::aerodynamic_discipline_enum_ID [protected]
aerodynamic discipline enumeration ID
Definition at line 125 of file AeroelasticitySolution.h.
unsigned int Solution::AeroelasticitySolution::aeroelastic_driver_enum_ID [protected]
aeroelastic method enumeration ID
Definition at line 128 of file AeroelasticitySolution.h.
bool Solution::AeroelasticitySolution::completed_linear_solve [protected]
linear solution completed
Definition at line 116 of file AeroelasticitySolution.h.
bool Solution::AeroelasticitySolution::coupled_thermoelastic [protected]
whether coupled thermal structural analysis is to be performed (unidirectional coupling)
Definition at line 110 of file AeroelasticitySolution.h.
std::vector<Loads::FlightCondition> Solution::AeroelasticitySolution::flight_condition_vector [protected]
vector of dynamic pressures
Definition at line 131 of file AeroelasticitySolution.h.
bool Solution::AeroelasticitySolution::include_geometric_effects [protected]
whether thermal geometric effects should be included
Definition at line 113 of file AeroelasticitySolution.h.
unsigned int Solution::AeroelasticitySolution::interpolation_case_ID [protected]
interpolation case ID for coupled thermal structural solution
Definition at line 119 of file AeroelasticitySolution.h.
unsigned int Solution::AeroelasticitySolution::n_lag_terms [protected]
number of lag terms
Definition at line 122 of file AeroelasticitySolution.h.
bool Solution::AeroelasticitySolution::use_modal_order_reduction [protected]
whether modal order reduction is to be used
Definition at line 107 of file AeroelasticitySolution.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solutions/AeroelasticitySolution.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solutions/AeroelasticitySolution.C