fesystem: Loads::ScalarVolumeLoadCombination Class Reference
Loads::ScalarVolumeLoadCombination Class Reference
#include <LoadCombination.h>
Public Member Functions
ScalarVolumeLoadCombination ()
virtual ~ScalarVolumeLoadCombination ()
virtual void clear ()
virtual unsigned int getLoadClassEnumID () const
double getValue () const
virtual void addLoad (const double factor, const VolumeLoad *load_ptr)
Protected Attributes
double value
Detailed Description
Definition at line 438 of file LoadCombination.h.
Constructor & Destructor Documentation
Loads::ScalarVolumeLoadCombination::ScalarVolumeLoadCombination () [inline]
Definition at line 441 of file LoadCombination.h.
                                   :
      VolumeLoadCombination(),
      value(0.0)
      {
      }
virtual Loads::ScalarVolumeLoadCombination::~ScalarVolumeLoadCombination () [inline, virtual]
Definition at line 449 of file LoadCombination.h.
      {
      }
Member Function Documentation
virtual void Loads::ScalarVolumeLoadCombination::addLoad (const double factor, const VolumeLoad * load_ptr) [inline, virtual]
Implements Loads::VolumeLoadCombination.
Definition at line 472 of file LoadCombination.h.
References Loads::VolumeLoadCombination::getElemID(), LoadBase::getLoadClassEnumID(), Loads::VolumeLoadCombination::load_set, Loads::VolumeLoadCombination::nLoads(), and value.
      {
        Assert(load_ptr != NULL, ExcInternalError());
        Assert(load_ptr->getLoadClassEnumID() == SCALAR_VOLUME_LOAD::num(),
               ExcInternalError());
        const ScalarVolumeLoad* ptr = dynamic_cast<const ScalarVolumeLoad*>(load_ptr);
        // set the node ID
        if (this->nLoads() > 0)
          Assert(this->getElemID() == ptr->getElemID(), ExcInternalError());
        bool insert_success = this->load_set.insert(load_ptr).second;
        // add this pointer to the set, and adjust the value of the load
        Assert(insert_success, ExcInternalError());
        this->value += factor * ptr->getValue();
      }
virtual void Loads::ScalarVolumeLoadCombination::clear () [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 454 of file LoadCombination.h.
References Loads::VolumeLoadCombination::load_set, and value.
      {
        this->value = 0.0;
        this->load_set.clear();
      }
virtual unsigned int Loads::ScalarVolumeLoadCombination::getLoadClassEnumID () const [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 461 of file LoadCombination.h.
      {
        return SCALAR_VOLUME_LOAD::num();
      }
double Loads::ScalarVolumeLoadCombination::getValue () const [inline]
Definition at line 467 of file LoadCombination.h.
References value.
      {
        return this->value;
      }
Member Data Documentation
double Loads::ScalarVolumeLoadCombination::value [protected]
Definition at line 494 of file LoadCombination.h.
Referenced by addLoad(), clear(), and getValue().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCombination.h