fesystem: Solver::PetscNonlinearSolver Class Reference
Solver::PetscNonlinearSolver Class Reference
#include <PetscNonlinearSolver.h>
Public Member Functions
PetscNonlinearSolver (const Solver::NonlinearSolverInfo &nonlinear_info, const Solver::LinearSolverInfo &linear_info)
constructor
~PetscNonlinearSolver ()
destructor
virtual void clear ()
virtual void solve (NumericVector< double > &solution)
virtual unsigned int getCurrentIterationNumber () const
this returns the itertion number of the solution process
Protected Attributes
SNES petsc_snes
PETSc nonlinear solver context.
KSP petsc_ksp
Petsc KSP context.
PC petsc_pc
Petsc PC context.
std::auto_ptr
< Solver::PetscLinearSolver > linear_solver
PETSc linear solver.
Detailed Description
this class provides an interface to a slover for the solution of a nonlinear set of equations. This inherits from the NonlinearSolver class. It takes a pointer to the analysis driver object that owns this object
Definition at line 94 of file PetscNonlinearSolver.h.
Constructor & Destructor Documentation
Solver::PetscNonlinearSolver::PetscNonlinearSolver (const Solver::NonlinearSolverInfo & nonlinear_info, const Solver::LinearSolverInfo & linear_info)
constructor
Definition at line 30 of file PetscNonlinearSolver.C.
References FESystem::COMM_WORLD, NEWTON_NONLINEAR_SOLVER_CUBIC_LINE_SEARCH_ENUM_ID, NEWTON_NONLINEAR_SOLVER_NO_LINE_SEARCH_ENUM_ID, NEWTON_NONLINEAR_SOLVER_NO_NORMS_LINE_SEARCH_ENUM_ID, and NEWTON_NONLINEAR_SOLVER_QUADRATIC_LINE_SEARCH_ENUM_ID.
                                           :
Solver::NonlinearSolver(nonlinear_info, linear_info)
{
  // create the SNES context and set the KSP and PC options
  PetscErrorCode ierr = 0;
  ierr = SNESCreate(FESystem::COMM_WORLD, &(this->petsc_snes));
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // set the options for the SNES
  switch (this->nonlinear_solver_info.getNonlinearSolverKindEnumID())
    {
    case NEWTON_NONLINEAR_SOLVER_CUBIC_LINE_SEARCH_ENUM_ID:
      {
        // set the solver type to line search, and also set the line
        // search type
        ierr = SNESSetType(this->petsc_snes, SNESLS);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
        ierr = SNESLineSearchSet(this->petsc_snes, SNESLineSearchCubic, PETSC_NULL);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    case NEWTON_NONLINEAR_SOLVER_QUADRATIC_LINE_SEARCH_ENUM_ID:
      {
        // set the solver type to line search, and also set the line
        // search type
        ierr = SNESSetType(this->petsc_snes, SNESLS);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
        ierr = SNESLineSearchSet(this->petsc_snes, SNESLineSearchQuadratic, PETSC_NULL);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    case NEWTON_NONLINEAR_SOLVER_NO_LINE_SEARCH_ENUM_ID:
      {
        // set the solver type to line search, and also set the line
        // search type
        ierr = SNESSetType(this->petsc_snes, SNESLS);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
        ierr = SNESLineSearchSet(this->petsc_snes, SNESLineSearchNo, PETSC_NULL);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    case NEWTON_NONLINEAR_SOLVER_NO_NORMS_LINE_SEARCH_ENUM_ID:
      {
        // set the solver type to line search, and also set the line
        // search type
        ierr = SNESSetType(this->petsc_snes, SNESLS);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
        ierr = SNESLineSearchSet(this->petsc_snes, SNESLineSearchNoNorms, PETSC_NULL);
        CHKERRABORT(FESystem::COMM_WORLD,ierr);
      }
      break;
    default:
      Assert(false, ExcInternalError());
    }
  const double nonlinear_tol = this->nonlinear_solver_info.getConvergenceTolerance();
  const unsigned int nonlinear_maxits = this->nonlinear_solver_info.getMaximumIterations();
  ierr = SNESSetTolerances(this->petsc_snes, nonlinear_tol, nonlinear_tol, nonlinear_tol,
                           nonlinear_maxits, 1000);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // set the default monitor for the solver
  ierr = SNESMonitorSet(this->petsc_snes,
                        SNESMonitorDefault,
                        PETSC_NULL, PETSC_NULL);
  CHKERRABORT(FESystem::COMM_WORLD,ierr);
  this->linear_solver.reset(new Solver::PetscLinearSolver(linear_info));
  this->petsc_ksp = linear_solver->getKSP();
  this->petsc_pc = linear_solver->getPC();
  // get the KSP context from the SNES and set its options
  ierr = SNESSetKSP(this->petsc_snes, this->petsc_ksp);
  CHKERRABORT(FESystem::COMM_WORLD,ierr);
}
Solver::PetscNonlinearSolver::~PetscNonlinearSolver ()
destructor
Definition at line 122 of file PetscNonlinearSolver.C.
References FESystem::COMM_WORLD, and petsc_snes.
{
  // destroy the nonlinear context
  PetscErrorCode ierr = SNESDestroy(this->petsc_snes);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
Member Function Documentation
void Solver::PetscNonlinearSolver::clear () [virtual]
method clear the data structures of this object. This should be called each time the user finishes using this object.
Reimplemented from Solver::NonlinearSolver.
Definition at line 134 of file PetscNonlinearSolver.C.
References Solver::NonlinearSolver::clear().
{
  Solver::NonlinearSolver::clear();
}
unsigned int Solver::PetscNonlinearSolver::getCurrentIterationNumber () const [inline, virtual]
this returns the itertion number of the solution process
Implements Solver::NonlinearSolver.
Definition at line 139 of file PetscNonlinearSolver.h.
References FESystem::COMM_WORLD, and petsc_snes.
{
  int iter_num = 0;
  PetscErrorCode ierr = SNESGetIterationNumber(this->petsc_snes, &iter_num);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  return iter_num;
}
void Solver::PetscNonlinearSolver::solve (NumericVector< double > & solution) [virtual]
function to perform solution steps.
Parameters:
solution vector in which the solution will be returned. This should be initialized to the initial guess
Implements Solver::NonlinearSolver.
Definition at line 142 of file PetscNonlinearSolver.C.
References FESystem::COMM_WORLD, FESystemNonlinearSolverFunctionEvaluation(), FESystemNonlinearSolverJacobianEvaluation(), and FESystemUtility::Parallel::PrintAll().
{
  this->analysis_driver->getFESystemController().performance_logging->setEvent
  ("PetscNonlinearSolver::solve()", "Solver");
  Assert(this->jacobian != NULL, ExcInternalError());
  Assert(this->residual != NULL, ExcInternalError());
  this->jacobian->close();
  this->residual->close();
  solution.close();
  Mat petsc_jac = dynamic_cast<PetscMatrix<double>*>(this->jacobian)->mat();
  Vec petsc_sol = dynamic_cast<PetscVector<double>&>(solution).vec();
  Vec petsc_res = dynamic_cast<PetscVector<double>*>(this->residual)->vec();
  // set the SNES function and jacobian routines
  PetscErrorCode ierr = SNESSetFunction(this->petsc_snes, petsc_res,
                                        FESystemNonlinearSolverFunctionEvaluation,
                                        this);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = SNESSetJacobian(this->petsc_snes, petsc_jac, petsc_jac,
                         FESystemNonlinearSolverJacobianEvaluation,
                         this);
  //   ierr = SNESSetJacobian(this->petsc_snes, petsc_jac, petsc_jac,
  //                     SNESDefaultComputeJacobian,
  //                     this);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // now solve the system
  ierr = SNESSolve(this->petsc_snes, PETSC_NULL, petsc_sol);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // get the convergence reason
  SNESConvergedReason reason;
  ierr = SNESGetConvergedReason(this->petsc_snes, &reason);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // print out information about convergence
  switch (reason)
    {
    case SNES_CONVERGED_FNORM_ABS: //        =  2, /* F < F_minabs */
      {
        FESystemUtility::Parallel::PrintAll(FESystem::COMM_WORLD,"SNES Converged due to F < F_minabs");
      }
      break;
    case SNES_CONVERGED_FNORM_RELATIVE:  //  =  3, /* F < F_mintol*F_initial */
      {
        FESystemUtility::Parallel::PrintAll(FESystem::COMM_WORLD,
                                            "SNES Converged due to F < F_mintol * F_initial");
      }
      break;
    case SNES_CONVERGED_PNORM_RELATIVE: //    =  4, /* step size small */
      {
        FESystemUtility::Parallel::PrintAll(FESystem::COMM_WORLD,
                                            "SNES Converged due to Small Step Size");
      }
      break;
    case SNES_CONVERGED_TR_DELTA: //        =  7,
      {
        FESystemUtility::Parallel::PrintAll(FESystem::COMM_WORLD,
                                            "SNES Converged due to TR_DELTA");
      }
      break;
      /* diverged */
    case SNES_DIVERGED_FUNCTION_DOMAIN:   // = -1,
      {
        FESystemUtility::Parallel::PrintAll(FESystem::COMM_WORLD,
                                            "SNES Diverged in function domain");
      }
      break;
    case SNES_DIVERGED_FUNCTION_COUNT: //    = -2,
      {
        FESystemUtility::Parallel::PrintAll(FESystem::COMM_WORLD,
                                            "SNES Diverged function count");
      }
      break;
    case SNES_DIVERGED_FNORM_NAN: //          = -4,
      {
        FESystemUtility::Parallel::PrintAll(FESystem::COMM_WORLD,
                                            "SNES obtained NAN ||F||");
      }
      break;
    case SNES_DIVERGED_MAX_IT: //             = -5,
      {
        FESystemUtility::Parallel::PrintAll(FESystem::COMM_WORLD,
                                            "SNES Did not converge in maximum iterations");
      }
      break;
    case SNES_DIVERGED_LS_FAILURE: //         = -6,
      {
        FESystemUtility::Parallel::PrintAll(FESystem::COMM_WORLD,
                                            "SNES Line Search Did not converge");
      }
      break;
    case SNES_DIVERGED_LOCAL_MIN: //         = -8,  /* || J^T b || is small, implies converged to local minimum of F() */
      {
        FESystemUtility::Parallel::PrintAll(FESystem::COMM_WORLD,
                                            "SNES Stuck in a local minima");
      }
      break;
    case SNES_CONVERGED_ITERATING: //         =  0
      {
        FESystemUtility::Parallel::PrintAll(FESystem::COMM_WORLD,
                                            "SNES Converged Iterating");
      }
      break;
    default:
      abort();
      break;
    }
  this->analysis_driver->getFESystemController().performance_logging->unsetEvent
    ("PetscNonlinearSolver::solve()", "Solver");
}
Member Data Documentation
std::auto_ptr<Solver::PetscLinearSolver> Solver::PetscNonlinearSolver::linear_solver [protected]
PETSc linear solver.
Definition at line 132 of file PetscNonlinearSolver.h.
KSP Solver::PetscNonlinearSolver::petsc_ksp [protected]
Petsc KSP context.
Definition at line 126 of file PetscNonlinearSolver.h.
PC Solver::PetscNonlinearSolver::petsc_pc [protected]
Petsc PC context.
Definition at line 129 of file PetscNonlinearSolver.h.
SNES Solver::PetscNonlinearSolver::petsc_snes [protected]
PETSc nonlinear solver context.
Definition at line 123 of file PetscNonlinearSolver.h.
Referenced by getCurrentIterationNumber(), and ~PetscNonlinearSolver().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/PetscNonlinearSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/PetscNonlinearSolver.C