fesystem: Driver::LinearTransientAnalysisDriver Class Reference
Driver::LinearTransientAnalysisDriver Class Reference
this is the base for nonlinear transient analysis drivers of various orders
#include <TransientAnalysisDriver.h>
Public Member Functions
LinearTransientAnalysisDriver (const unsigned int ID, FESystem::FESystemController &controller)
constructor
virtual ~LinearTransientAnalysisDriver ()
destructor
virtual void getCoefficientMatrices (const double time, std::vector< SparseMatrix< double > * > &matrices)
virtual void getForceVector (const double time, NumericVector< double > &vector)
Protected Member Functions
virtual void initialize ()
this method initializes itself before the solutions are started for the driver
virtual void solveCurrentLoadCase ()
this method solves for the current load case
virtual void addMatricesAndVectors ()
function will add the matrices and vectors for this analysis
Detailed Description
this is the base for nonlinear transient analysis drivers of various orders
Definition at line 199 of file TransientAnalysisDriver.h.
Constructor & Destructor Documentation
Driver::LinearTransientAnalysisDriver::LinearTransientAnalysisDriver (const unsigned int ID, FESystem::FESystemController & controller)
constructor
Definition at line 230 of file TransientAnalysisDriver.C.
                                                                     :
Driver::TransientAnalysisDriver(ID, fesys_controller,
                                LINEAR_TRANSIENT_ANALYSIS_DRIVER::num())
{
}
Driver::LinearTransientAnalysisDriver::~LinearTransientAnalysisDriver () [virtual]
destructor
Definition at line 239 of file TransientAnalysisDriver.C.
{
}
Member Function Documentation
void Driver::LinearTransientAnalysisDriver::addMatricesAndVectors () [protected, virtual]
function will add the matrices and vectors for this analysis
Implements Driver::AnalysisDriver.
Definition at line 257 of file TransientAnalysisDriver.C.
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  // add a system matrix, a solution vector and a rhs
  switch (it->second->getTransientSystemOrder())
  {
    case 2:
    {
      if (it->second->disciplineHasMatrix(Driver::TRANSIENT_C2_MATRIX::num()))
        {
          SparseMatrix<double>& mat = this->addMatrix(Driver::TRANSIENT_C2_MATRIX::name());
          it->second->initMatrix(mat);
        }
    }
    case 1:
    {
      if (it->second->disciplineHasMatrix(Driver::TRANSIENT_C1_MATRIX::num()))
        {
          SparseMatrix<double>& mat = this->addMatrix(Driver::TRANSIENT_C1_MATRIX::name());
          it->second->initMatrix(mat);
        }
      if (it->second->disciplineHasMatrix(Driver::SYSTEM_MATRIX::num()))
        {
          SparseMatrix<double>& mat = this->addMatrix(Driver::SYSTEM_MATRIX::name());
          it->second->initMatrix(mat);
        }
    }
      break;
    default:
      Assert(false, ExcInternalError());
  }
}
void Driver::LinearTransientAnalysisDriver::getCoefficientMatrices (const double time, std::vector< SparseMatrix< double > * > & matrices) [virtual]
calculate the coefficient matrices. The location of the matrix is also the order of the time derivative vector
Implements Driver::TransientAnalysisDriver.
Definition at line 412 of file TransientAnalysisDriver.C.
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator discipline_it;
  discipline_it = this->analysis_discipline_map.begin();
  this->current_analysis_time = time;
  unsigned int order = discipline_it->second->getTransientSystemOrder();
  Assert(matrices.size() == (order+1), ExcInternalError());
  // create a map of the matrices to be requested from the system
  std::map<unsigned int, double> real_map;
  std::map<unsigned int, SparseMatrix<double>*> matrix_map;
  std::map<unsigned int, NumericVector<double>*> vector_map;
  switch (order)
  {
    case 2:
    {
      if (discipline_it->second->disciplineHasMatrix(Driver::TRANSIENT_C2_MATRIX::num()))
        {
          matrices[2]->zero(); matrices[2]->close();
          matrix_map[Driver::TRANSIENT_C2_MATRIX::num()] = matrices[2];
        }
    }
    case 1:
    {
      if (discipline_it->second->disciplineHasMatrix(Driver::TRANSIENT_C1_MATRIX::num()))
        {
          matrices[1]->zero(); matrices[1]->close();
          matrix_map[Driver::TRANSIENT_C1_MATRIX::num()] = matrices[1];
        }
      if (discipline_it->second->disciplineHasMatrix(Driver::SYSTEM_MATRIX::num()))
        {
          matrices[0]->zero(); matrices[0]->close();
          matrix_map[Driver::SYSTEM_MATRIX::num()] = matrices[0];
        }
    }
      break;
    default:
      Assert(false, ExcInternalError());
  }
  // fill the matrices and vectors with the required quantities
  discipline_it->second->fillQuantity(real_map, matrix_map, vector_map);
  std::map<unsigned int, SparseMatrix<double>*>::iterator it, end;
  it = matrix_map.begin();
  end = matrix_map.end();
  double time_step = dynamic_cast<Solver::TransientSolverBase*>(this->solver)->getTimeStepSize();
  unsigned int i = 0;
  for (; it != end; it++)
    {
      it->second->close();
      this->applyBoundaryConditionsToMatrixForCurrentAnalysis(*(it->second), pow(time_step,i), discipline_it->second->getDisciplineEnumID());
      it->second->close();
      i++;
    }
  // return control back to the solver
}
void Driver::LinearTransientAnalysisDriver::getForceVector (const double time, NumericVector< double > & vector) [virtual]
calculate the coefficient matrices. The location of the matrix is also the order of the time derivative vector
Implements Driver::TransientAnalysisDriver.
Definition at line 487 of file TransientAnalysisDriver.C.
References ANALYSIS_ENUM_ID, FESystemDatabase::TimeDependentDataInfo::clear(), SENSITIVITY_ANALYSIS_ENUM_ID, FESystemDatabase::GenericDataInfoBase::setDisciplineEnumID(), FESystemDatabase::GenericDataInfoBase::setLoadCase(), FESystemDatabase::GenericDataInfoBase::setName(), FESystemDatabase::TimeDependentDataInfo::setOrder(), and FESystemDatabase::TimeDependentDataInfo::setTransientIterationInfo().
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  this->current_analysis_time = time;
  unsigned int order = it->second->getTransientSystemOrder();
  // create a map of the matrices to be requested from the system
  std::map<unsigned int, double> real_map;
  std::map<unsigned int, SparseMatrix<double>*> matrix_map;
  std::map<unsigned int, NumericVector<double>*> vector_map;
  switch (this->current_analysis_kind_enum_ID)
  {
    case ANALYSIS_ENUM_ID:
    {
      vec.zero(); vec.close();
      vector_map[Driver::FORCE_VECTOR::num()] = &vec;
      it->second->fillQuantity(real_map, matrix_map, vector_map);
      vec.close();
      this->applyBoundaryConditionsToVectorForCurrentAnalysis(vec, true, it->second->getDisciplineEnumID());
      vec.close();
    }
      break;
    case SENSITIVITY_ANALYSIS_ENUM_ID:
    {
      if (!this->haveMatrix("ScratchMatrix"))
        this->addMatrix("ScratchMatrix");
      if (!this->haveVector("ScratchVector1"))
        this->addVector("ScratchVector1");
      if (!this->haveVector("ScratchVector2"))
        this->addVector("ScratchVector2");
      SparseMatrix<double>& scratch_matrix = this->getMatrix("ScratchMatrix");
      NumericVector<double>& scratch_vec1 = this->getVector("ScratchVector1");
      NumericVector<double>& scratch_vec2 = this->getVector("ScratchVector2");
      vec.zero(); vec.perform_intermediate_vector_assembly();
      vector_map[Driver::FORCE_VECTOR_SENSITIVITY::num()] = &vec;
      it->second->fillQuantity(real_map, matrix_map, vector_map);
      vector_map.clear();
      vec.perform_intermediate_vector_assembly();
      FESystemDatabase::TimeDependentDataInfo data_info;
      unsigned int qty_enum_ID = 0;
      for (unsigned int i=0; i<= order; i++)
        {
          switch (i)
          {
            case 0:
              qty_enum_ID = Driver::SYSTEM_MATRIX_SENSITIVITY::num();
              break;
            case 1:
              qty_enum_ID = Driver::TRANSIENT_C1_MATRIX_SENSITIVITY::num();
              break;
            case 2:
              qty_enum_ID = Driver::TRANSIENT_C2_MATRIX_SENSITIVITY::num();
              break;
            default:
              Assert(false, ExcInternalError());
          }
          // if the matrix for this order exists, then process it, else go to the
          // next order
          if (it->second->disciplineHasMatrix(qty_enum_ID))
            {
              // get the matrix and the solution
              scratch_matrix.zero(); scratch_matrix.perform_intermediate_matrix_assembly();
              matrix_map.clear();
              matrix_map[qty_enum_ID] = &scratch_matrix;
              it->second->fillQuantity(real_map, matrix_map, vector_map);
              scratch_matrix.close();
              // create the data info object for this solution
              data_info.clear();
              data_info.setDisciplineEnumID(it->second->getDisciplineEnumID());
              data_info.setName("Solution");
              data_info.setOrder(i);
              data_info.setLoadCase(this->current_load_case);
              // this needs to be implemted, since iter_num is not available here
              Assert(false, ExcInternalError());
              data_info.setTransientIterationInfo(this->getCurrentIterationNumber(), time);
              this->fesystem_controller.global_data_storage->fillVector(data_info, scratch_vec1);
              scratch_vec1.close();
              scratch_vec2.zero();
              scratch_vec2.close();
              scratch_matrix.multiply_vector(scratch_vec1, scratch_vec2);
              vec.add(-1.0, scratch_vec2);
              vec.perform_intermediate_vector_assembly();
            }
        }
      this->applyBoundaryConditionsToVectorForCurrentAnalysis(vec, false, it->second->getDisciplineEnumID());
      vec.close();
    }
      break;
    default:
      Assert(false, ExcInternalError());
  }
  // return control back to the solver
}
void Driver::LinearTransientAnalysisDriver::initialize () [protected, virtual]
this method initializes itself before the solutions are started for the driver
Implements Driver::AnalysisDriver.
Definition at line 246 of file TransientAnalysisDriver.C.
{
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  // add the matrices and vectors
  this->addMatricesAndVectors();
}
void Driver::LinearTransientAnalysisDriver::solveCurrentLoadCase () [protected, virtual]
this method solves for the current load case
Implements Driver::AnalysisDriver.
Definition at line 305 of file TransientAnalysisDriver.C.
References ANALYSIS_ENUM_ID, Solver::TransientSolverBase::attachCoefficientMatrices(), FESystemUtility::AutoPtrVector< T >::clear(), FESystemUtility::AutoPtrVector< T >::getReference(), FESystemUtility::AutoPtrVector< T >::reset(), SENSITIVITY_ANALYSIS_ENUM_ID, FESystemNumerics::PetscVectorBase< T >::set(), FESystemDatabase::GenericDataInfoBase::setDisciplineEnumID(), Solver::TransientSolverBase::setInitialCondition(), FESystemDatabase::GenericDataInfoBase::setLoadCase(), FESystemDatabase::GenericDataInfoBase::setName(), and Solver::TransientSolverBase::solve().
{
  Assert(this->time_values.size() == 0, ExcInternalError());
  // this is a uni-discipline driver. Make sure that the number of disciplines here is one
  Assert(this->analysis_discipline_map.size() == 1, ExcInternalError());
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it;
  it = this->analysis_discipline_map.begin();
  unsigned int order = it->second->getTransientSystemOrder();
  Assert(order > 0, ExcInternalError());
  Assert(this->solver != NULL, ExcInternalError());
  Solver::LinearTransientSolverBase* linear_transient_solver =
  dynamic_cast<Solver::LinearTransientSolverBase*>(this->solver);
  switch (this->current_analysis_kind_enum_ID)
  {
    case ANALYSIS_ENUM_ID:
    case SENSITIVITY_ANALYSIS_ENUM_ID:
    {
      FESystemUtility::AutoPtrVector<NumericVector<double> > vecs(order);
      std::auto_ptr<NumericVector<double> > vec_ptr;
      for (unsigned int i=0; i < order; i++)
        {
          // create a vector for the initial conditions, and init it to the
          // dof distribution of the discipline
          vec_ptr.reset(NumericVector<double>::build().release());
          it->second->initVector(*vec_ptr);
          vecs.reset(i, vec_ptr.release());
        }
      this->setInitialConditionForCurrentLoadCase(vecs.getReference());
      linear_transient_solver->setInitialCondition(vecs.getReference());
      // now clear the vectors, since they are not needed anymore
      vecs.clear();
      // create a vector of system matrices to be given to the solver
      std::vector<SparseMatrix<double>*> mat_vec(order+1);
      switch (order)
      {
        case 2:
        {
          if (it->second->disciplineHasMatrix(Driver::TRANSIENT_C2_MATRIX::num()))
            mat_vec[2] = &(this->getMatrix(Driver::TRANSIENT_C2_MATRIX::name()));
          else
            mat_vec[2] = NULL;
        }
        case 1:
        {
          if (it->second->disciplineHasMatrix(Driver::TRANSIENT_C1_MATRIX::num()))
            mat_vec[1] = &(this->getMatrix(Driver::TRANSIENT_C1_MATRIX::name()));
          else
            mat_vec[1] = NULL;
          if (it->second->disciplineHasMatrix(Driver::SYSTEM_MATRIX::num()))
            mat_vec[0] = &(this->getMatrix(Driver::SYSTEM_MATRIX::name()));
          else
            mat_vec[0] = NULL;
        }
          break;
        default:
          Assert(false, ExcInternalError());
      }
      linear_transient_solver->attachCoefficientMatrices(mat_vec);
      linear_transient_solver->solve();
    }
      break;
    default:
      abort();
      break;
  }
  // once the solution is done, store the time values
  if (this->current_analysis_kind_enum_ID == ANALYSIS::num())
    {
      FESystemDatabase::TimeIndependentDataInfo data_info;
      data_info.setDisciplineEnumID(it->second->getDisciplineEnumID());
      data_info.setName("TimeValues");
      data_info.setLoadCase(this->current_load_case);
      FESystemNumerics::PetscSeqVector<double> vec(this->time_values.size());
      for (unsigned int i=0; i < this->time_values.size(); i++)
        vec.set(i, this->time_values[i]);
      this->fesystem_controller.global_data_storage->storeVector(data_info, vec);
    }
}
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/AnalysisDriver/TransientAnalysisDriver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/AnalysisDriver/TransientAnalysisDriver.C