fesystem: ALPHA_EXPANSION Class Reference
ALPHA_EXPANSION Class Reference
#include <MaterialPropertyNameEnums.h>
Public Member Functions
ALPHA_EXPANSION ()
Static Public Member Functions
static std::string name ()
static unsigned int num ()
Static Public Attributes
static const bool only_isotropic = false
Static Protected Attributes
static
MaterialPropertyNameBase::EnumRegistration
< ALPHA_EXPANSION > registration
Detailed Description
Definition at line 348 of file MaterialPropertyNameEnums.h.
Constructor & Destructor Documentation
ALPHA_EXPANSION::ALPHA_EXPANSION () [inline]
Definition at line 348 of file MaterialPropertyNameEnums.h.
Member Function Documentation
static std::string ALPHA_EXPANSION::name () [inline, static]
Definition at line 348 of file MaterialPropertyNameEnums.h.
static unsigned int ALPHA_EXPANSION::num () [inline, static]
Definition at line 348 of file MaterialPropertyNameEnums.h.
Referenced by Isotropic3D_ElemDataCard::getFactor(), Isotropic2D_ElemDataCard::getFactor(), Isotropic1D_ElemDataCard::getFactor(), Isotropic3D_ElemDataCard::getFactorSensitivityForGlobalParameter(), Isotropic2D_ElemDataCard::getFactorSensitivityForGlobalParameter(), Isotropic1D_ElemDataCard::getFactorSensitivityForGlobalParameter(), Isotropic3D_ElemDataCard::getFactorSensitivityForLocalParameter(), Isotropic2D_ElemDataCard::getFactorSensitivityForLocalParameter(), and Isotropic1D_ElemDataCard::getFactorSensitivityForLocalParameter().
Member Data Documentation
const bool ALPHA_EXPANSION::only_isotropic = false [static]
Definition at line 348 of file MaterialPropertyNameEnums.h.
MaterialPropertyNameBase::EnumRegistration< ALPHA_EXPANSION > ALPHA_EXPANSION::registration [static, protected]
Definition at line 348 of file MaterialPropertyNameEnums.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/MaterialPropertyNameEnums.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/FESystem/FESystemStaticMemberDefinitions.C