fesystem: FunctionBase Class Reference
FunctionBase Class Reference
#include <FunctionBase.h>
Public Member Functions
FunctionBase ()
default constructor
virtual ~FunctionBase ()
destructor
const unsigned int getID () const
virtual const unsigned int getFunctionTypeID () const =0
virtual const std::string getFunctionTypeName () const =0
virtual void getFunctionValue (const double &abcissa, double &ordinate) const =0
virtual void getFunctionDerivative (const double &abcissa, double &ordinate) const =0
Protected Member Functions
virtual std::istream & readFromInputStream (std::istream &input)=0
method to read from the function from the input stream
Protected Attributes
unsigned int ID
ID of this function object.
Detailed Description
this class defines a base class for all functions in both deal.II and FESystem, so that the can be referred to by a pointer to this base class
Definition at line 24 of file FunctionBase.h.
Constructor & Destructor Documentation
FunctionBase::FunctionBase () [inline]
default constructor
Definition at line 74 of file FunctionBase.h.
                          :
ID(FESystemNumbers::InvalidID)
{}
FunctionBase::~FunctionBase () [inline, virtual]
destructor
Definition at line 83 of file FunctionBase.h.
{}
Member Function Documentation
virtual void FunctionBase::getFunctionDerivative (const double & abcissa, double & ordinate) const [pure virtual]
Returns:
derivative of the function at the given abcissa
Parameters:
abcissa value at which the function should be evaluated
ordinate evaluated function value
Implemented in MultilinearFunction.
Referenced by FunctionDatabase::getScalarFunctionDerivative().
virtual const unsigned int FunctionBase::getFunctionTypeID () const [pure virtual]
Returns:
the type of this function as the enumeration ID of the enumeration type of this object
Implemented in MultilinearFunction.
virtual const std::string FunctionBase::getFunctionTypeName () const [pure virtual]
Returns:
the type of this function as a string
Implemented in MultilinearFunction.
virtual void FunctionBase::getFunctionValue (const double & abcissa, double & ordinate) const [pure virtual]
Returns:
value of the function at the given abcissa
Parameters:
abcissa value at which the function should be evaluated
ordinate evaluated function value
Implemented in MultilinearFunction.
Referenced by FunctionDatabase::getScalarFunctionValue().
const unsigned int FunctionBase::getID () const [inline]
Returns:
the function ID
Definition at line 90 of file FunctionBase.h.
References ID.
Referenced by FunctionDatabase::readFromInputStream().
{
  Assert (this->ID > 0, FESystemExceptions::ExcInvalidID(this->ID));
  return this->ID;
}
virtual std::istream& FunctionBase::readFromInputStream (std::istream & input) [protected, pure virtual]
method to read from the function from the input stream
Implemented in MultilinearFunction.
Member Data Documentation
unsigned int FunctionBase::ID [protected]
ID of this function object.
Definition at line 65 of file FunctionBase.h.
Referenced by getID(), and MultilinearFunction::readFromInputStream().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Numerics/FunctionBase.h