fesystem: Loads::NodalLoadDataInfo Class Reference
Loads::NodalLoadDataInfo Class Reference
#include <LoadDataInfo.h>
Public Member Functions
NodalLoadDataInfo ()
virtual ~NodalLoadDataInfo ()
virtual void clear ()
void setNodeID (const unsigned int ID)
unsigned int getNodeID () const
void setNDofs (const unsigned int ID)
unsigned int getNDofs () const
Protected Attributes
unsigned int n_dofs
unsigned int node_ID
Detailed Description
Definition at line 141 of file LoadDataInfo.h.
Constructor & Destructor Documentation
Loads::NodalLoadDataInfo::NodalLoadDataInfo ()
Definition at line 292 of file LoadDataInfo.C.
                                         :
Loads::LoadDataInfoBase(),
n_dofs(FESystemNumbers::InvalidID),
node_ID(FESystemNumbers::InvalidID)
{
}
Loads::NodalLoadDataInfo::~NodalLoadDataInfo () [virtual]
Definition at line 302 of file LoadDataInfo.C.
{
  this->clear();
}
Member Function Documentation
void Loads::NodalLoadDataInfo::clear () [virtual]
Reimplemented from Loads::LoadDataInfoBase.
Definition at line 310 of file LoadDataInfo.C.
References Loads::LoadDataInfoBase::clear(), and FESystemNumbers::InvalidID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads().
{
  this->n_dofs = FESystemNumbers::InvalidID;
  this->node_ID = FESystemNumbers::InvalidID;
  Loads::LoadDataInfoBase::clear();
}
unsigned int Loads::NodalLoadDataInfo::getNDofs () const
Definition at line 349 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
{
  Assert(this->n_dofs != FESystemNumbers::InvalidID, ExcInternalError());
  return this->n_dofs;
}
unsigned int Loads::NodalLoadDataInfo::getNodeID () const
Definition at line 330 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by LoadDatabase::getLoadCombination< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >().
{
  Assert(this->node_ID != FESystemNumbers::InvalidID, ExcInternalError());
  return this->node_ID;
}
void Loads::NodalLoadDataInfo::setNDofs (const unsigned int ID)
Definition at line 339 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads(), Discipline::FluidAnalysis::performAdditionalOperationsOnGlobalQuantities(), and Discipline::StructuralAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  Assert(ID != FESystemNumbers::InvalidID, ExcInternalError());
  Assert(this->n_dofs == FESystemNumbers::InvalidID, ExcInternalError());
  this->n_dofs = ID;
}
void Loads::NodalLoadDataInfo::setNodeID (const unsigned int ID)
Definition at line 320 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads().
{
  Assert(ID != FESystemNumbers::InvalidID, ExcInternalError());
  Assert(this->node_ID == FESystemNumbers::InvalidID, ExcInternalError());
  this->node_ID = ID;
}
Member Data Documentation
unsigned int Loads::NodalLoadDataInfo::n_dofs [protected]
Definition at line 160 of file LoadDataInfo.h.
unsigned int Loads::NodalLoadDataInfo::node_ID [protected]
Definition at line 162 of file LoadDataInfo.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadDataInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadDataInfo.C