fesystem: FESystemNumerics::PetscVectorBase< T > Class Template Reference
FESystemNumerics::PetscVectorBase< T > Class Template Reference
#include <PetscVectorBase.h>
Public Member Functions
PetscVectorBase ()
constructor
virtual ~PetscVectorBase ()
virtual unsigned int getVectorPackage () const
virtual void zero ()
virtual T el (const unsigned int i) const
virtual void set (const unsigned int i, const T val)
virtual void power (const double val)
raises each element of the vector by the given power
virtual void invertValues ()
sets each element of the vector to its reciprocal
virtual T dot (const FESystemNumerics::VectorBase< T > &vec) const
returns the dot product of this vector with the given vector
virtual void shift (const T val)
adds the value val to all elements of the vector
virtual void pointwiseMultiply (const FESystemNumerics::VectorBase< T > &vec)
sets (*this)[i] = (*this)[i] * vec[i]
virtual void set (const std::vector< unsigned int > &i, const T *val)
virtual unsigned int size () const
virtual void add (const T val, const FESystemNumerics::VectorBase< T > &vector)
virtual void add (const unsigned int i, const T val)
virtual void add (const std::vector< unsigned int > &i, const T *val)
virtual void scale (const T factor)
Vec getVec ()
returns the Petsc matrix data structure
const Vec getVec () const
void assemble ()
method to flush assemble the matrix
Protected Types
enum LastAction { ADD, INSERT, ASSEMBLE }
an enumeration to keep track of action performed
Protected Attributes
LastAction vector_last_action
Vec petsc_vec
Petsc matrix data structure.
Detailed Description
template<typename T>
class FESystemNumerics::PetscVectorBase< T >
this class provides a base class for different kinds of matrices
Definition at line 23 of file PetscVectorBase.h.
Member Enumeration Documentation
template<typename T> enum FESystemNumerics::PetscVectorBase::LastAction [protected]
an enumeration to keep track of action performed
Enumerator:
ADD
INSERT
ASSEMBLE
Definition at line 136 of file PetscVectorBase.h.
{ADD, INSERT, ASSEMBLE};
Constructor & Destructor Documentation
template<typename T > FESystemNumerics::PetscVectorBase< T >::PetscVectorBase ()
constructor
Definition at line 152 of file PetscVectorBase.h.
                                                   :
FESystemNumerics::VectorBase<T>()
{}
template<typename T > FESystemNumerics::PetscVectorBase< T >::~PetscVectorBase () [virtual]
Destructor. Empty.
Definition at line 159 of file PetscVectorBase.h.
{}
Member Function Documentation
template<typename T> void FESystemNumerics::PetscVectorBase< T >::add (const T val, const FESystemNumerics::VectorBase< T > & vector) [virtual]
Adds to this matrix
Implements FESystemNumerics::VectorBase< T >.
Definition at line 422 of file PetscVectorBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscVectorBase< T >::getVec(), and FESystemNumerics::VectorBase< T >::getVectorPackage().
Referenced by RadiationCavityAnalysis::calculateRadElemTempVector(), RadiationCavityAnalysis::getFEJacobianMatrix(), RadiationCavityAnalysis::getFENodalLoadVectorSensitivity(), RadiationElement::getRadElemG_Vector(), and RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector().
{
  Assert(vector.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
    case FESystemNumerics::PetscVectorBase<T>::ADD:
      this->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscVectorBase<T>& vec =
  dynamic_cast<const FESystemNumerics::PetscVectorBase<T>&>(vector);
  const_cast<FESystemNumerics::PetscVectorBase<T>&>(vec).assemble();
  PetscErrorCode ierr;
  ierr = VecAXPY (this->petsc_vec, val, vec.getVec());
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T> void FESystemNumerics::PetscVectorBase< T >::add (const unsigned int i, const T val) [virtual]
Adds factor to given element in the matrix.
Implements FESystemNumerics::VectorBase< T >.
Definition at line 454 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
{
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
      this->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::ADD:
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = VecSetValue (this->petsc_vec, i,
                      val, ADD_VALUES);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->vector_last_action = FESystemNumerics::PetscVectorBase<T>::ADD;
}
template<typename T> void FESystemNumerics::PetscVectorBase< T >::add (const std::vector< unsigned int > & i, const T * val) [virtual]
adds multiple elements with the indeces given in i and j. The val should be a 2-D matrix of dimensions equal to size of vectors i and j.
Implements FESystemNumerics::VectorBase< T >.
Definition at line 482 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
{
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
      this->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::ADD:
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = VecSetValues (this->petsc_vec, i.size(), (const PetscInt*) &(i[0]),
                      val, ADD_VALUES);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->vector_last_action = FESystemNumerics::PetscVectorBase<T>::ADD;
}
template<typename T > void FESystemNumerics::PetscVectorBase< T >::assemble () [inline]
method to flush assemble the matrix
Definition at line 553 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
{
  PetscErrorCode ierr;
  ierr = VecAssemblyBegin(this->petsc_vec);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = VecAssemblyEnd(this->petsc_vec);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->vector_last_action = FESystemNumerics::PetscVectorBase<T>::ASSEMBLE;
}
template<typename T> T FESystemNumerics::PetscVectorBase< T >::dot (const FESystemNumerics::VectorBase< T > & vec) const [virtual]
returns the dot product of this vector with the given vector
Implements FESystemNumerics::VectorBase< T >.
Definition at line 346 of file PetscVectorBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscVectorBase< T >::getVec(), and FESystemNumerics::VectorBase< T >::getVectorPackage().
{
  Assert(vec.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::ADD:
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
      const_cast<FESystemNumerics::PetscVectorBase<T>*>(this)->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscVectorBase<T>& pvec =
    dynamic_cast<const FESystemNumerics::PetscVectorBase<T>&>(vec);
  T val;
  PetscErrorCode ierr;
  ierr = VecDot(this->petsc_vec, pvec.getVec(), &val);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  return val;
}
template<typename T > T FESystemNumerics::PetscVectorBase< T >::el (const unsigned int i) const [virtual]
Returns:
the (i,j) element of the matrix. Since internal data representations may differ, you must redefine this function.
Implements FESystemNumerics::VectorBase< T >.
Definition at line 187 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateA_InverseMatrix(), RadiationCavityAnalysis::calculateB_InverseMatrix(), RadiationCavityAnalysis::calculateRadElemTempVector(), DirectInterpolation::createLoads(), RadiationCavityAnalysis::getFEJacobianMatrix(), RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector(), Solution::TransientThermalSolution::getTimeDependentNodalSolutionDataInfo(), Solution::TransientStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Discipline::ThermalAnalysis::performAdditionalOperationsOnGlobalQuantities(), and Driver::NonlinearTransientAnalysisDriver::solveCurrentLoadCase().
{
  // if the data has not been flushed, do that before accessing the value
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
    case FESystemNumerics::PetscVectorBase<T>::ADD:
      const_cast<FESystemNumerics::PetscVectorBase<T>*>(this)->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  PetscInt i_num = i;
  T val;
  ierr = VecGetValues (this->petsc_vec, 1, &i_num, &val);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  return val;
}
template<typename T > Vec FESystemNumerics::PetscVectorBase< T >::getVec ()
returns the Petsc matrix data structure
Definition at line 534 of file PetscVectorBase.h.
Referenced by FESystemNumerics::PetscVectorBase< T >::add(), RadiationCavityAnalysis::calculateA_InverseMatrix(), RadiationCavityAnalysis::calculateB_InverseMatrix(), FESystemNumerics::PetscVectorBase< T >::dot(), FESystemNumerics::PetscMatrixBase< T >::leftDiagonalScale(), FESystemNumerics::PetscMatrixBase< T >::leftMultiplyVector(), FESystemNumerics::PetscSeqVector< T >::PetscSeqVector(), FESystemNumerics::PetscVectorBase< T >::pointwiseMultiply(), FESystemNumerics::PetscMatrixBase< T >::rightDiagonalScale(), and FESystemNumerics::PetscMatrixBase< T >::rightMultiplyVector().
{
  return this->petsc_vec;
}
template<typename T > const Vec FESystemNumerics::PetscVectorBase< T >::getVec () const
Returns:
a constant Petsc matrix data structure
Definition at line 543 of file PetscVectorBase.h.
{
  return this->petsc_vec;
}
template<typename T > unsigned int FESystemNumerics::PetscVectorBase< T >::getVectorPackage () const [virtual]
Returns:
the matrix package
Implements FESystemNumerics::VectorBase< T >.
Definition at line 165 of file PetscVectorBase.h.
{
  return FESystem::PETSC_PACKAGE::num();
}
template<typename T > void FESystemNumerics::PetscVectorBase< T >::invertValues () [virtual]
sets each element of the vector to its reciprocal
Implements FESystemNumerics::VectorBase< T >.
Definition at line 299 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::getFEJacobianMatrix().
{
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::ADD:
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
      this->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = VecReciprocal(this->petsc_vec);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T> void FESystemNumerics::PetscVectorBase< T >::pointwiseMultiply (const FESystemNumerics::VectorBase< T > & vec) [virtual]
sets (*this)[i] = (*this)[i] * vec[i]
Implements FESystemNumerics::VectorBase< T >.
Definition at line 379 of file PetscVectorBase.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscVectorBase< T >::getVec(), and FESystemNumerics::VectorBase< T >::getVectorPackage().
Referenced by RadiationCavityAnalysis::getFEJacobianMatrix().
{
  Assert(vec.getVectorPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::ADD:
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
      this->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscVectorBase<T>& pvec =
    dynamic_cast<const FESystemNumerics::PetscVectorBase<T>&>(vec);
  PetscErrorCode ierr;
  ierr = VecPointwiseMult(this->petsc_vec, this->petsc_vec, pvec.getVec());
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > void FESystemNumerics::PetscVectorBase< T >::power (const double val) [virtual]
raises each element of the vector by the given power
Implements FESystemNumerics::VectorBase< T >.
Definition at line 267 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateRadElemTempVector(), and RadiationCavityAnalysis::getFEJacobianMatrix().
{
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::ADD:
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
      this->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  T *vec_vals;
  PetscErrorCode ierr;
  ierr = VecGetArray (this->petsc_vec, &vec_vals);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  for (unsigned int i=0; i<this->size(); i++)
    vec_vals[i] = pow(vec_vals[i], val);
  ierr = VecGetArray (this->petsc_vec, &vec_vals);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T> void FESystemNumerics::PetscVectorBase< T >::scale (const T factor) [virtual]
multiplies factor to every element in the matrix.
Implements FESystemNumerics::VectorBase< T >.
Definition at line 511 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateRadElemTempVector(), RadiationCavityAnalysis::getFEJacobianMatrix(), RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector(), and Discipline::ThermalAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
    case FESystemNumerics::PetscVectorBase<T>::ADD:
      this->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = VecScale (this->petsc_vec, factor);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T> void FESystemNumerics::PetscVectorBase< T >::set (const unsigned int i, const T val) [virtual]
sets the given element to
Implements FESystemNumerics::VectorBase< T >.
Definition at line 215 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateB_Matrix(), RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution(), RadiationCavityAnalysis::calculateEmissivityVector(), RadiationCavityAnalysis::calculateRadElemTempVector(), RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector(), Discipline::ThermalAnalysis::performAdditionalOperationsOnGlobalQuantities(), Driver::LinearTransientAnalysisDriver::solveCurrentLoadCase(), and Driver::NonlinearTransientAnalysisDriver::solveCurrentLoadCase().
{
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::ADD:
      this->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = VecSetValue (this->petsc_vec, i,
                      val, INSERT_VALUES);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->vector_last_action = FESystemNumerics::PetscVectorBase<T>::INSERT;
}
template<typename T> void FESystemNumerics::PetscVectorBase< T >::set (const std::vector< unsigned int > & i, const T * val) [virtual]
sets multiple elements with the indeces given in i and j. The val should be a 2-D matrix of dimensions equal to size of vectors i and j.
Implements FESystemNumerics::VectorBase< T >.
Definition at line 241 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
{
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::ADD:
      this->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = VecSetValues (this->petsc_vec, i.size(), (const PetscInt*) &(i[0]),
                       val, INSERT_VALUES);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->vector_last_action = FESystemNumerics::PetscVectorBase<T>::INSERT;
}
template<typename T> void FESystemNumerics::PetscVectorBase< T >::shift (const T val) [virtual]
adds the value val to all elements of the vector
Implements FESystemNumerics::VectorBase< T >.
Definition at line 323 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
{
  switch (this->vector_last_action)
    {
    case FESystemNumerics::PetscVectorBase<T>::ADD:
    case FESystemNumerics::PetscVectorBase<T>::INSERT:
      this->assemble();
      break;
    case FESystemNumerics::PetscVectorBase<T>::ASSEMBLE:
      break;
    }
  PetscErrorCode ierr;
  ierr = VecShift(this->petsc_vec, val);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > unsigned int FESystemNumerics::PetscVectorBase< T >::size () const [virtual]
Returns:
the row-dimension of the matrix.
Implements FESystemNumerics::VectorBase< T >.
Definition at line 408 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution(), RadiationCavityAnalysis::calculateEmissivityVector(), RadiationCavityAnalysis::calculateG_Matrix(), RadiationCavityAnalysis::calculateRadElemTempVector(), DirectInterpolation::createLoads(), RadiationCavityAnalysis::getFEJacobianMatrix(), RadiationCavityAnalysis::getFENodalLoadVector(), RadiationCavityAnalysis::getFENodalLoadVectorSensitivity(), RadiationElement::getRadElemG_Vector(), RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector(), Solution::TransientThermalSolution::getTimeDependentNodalSolutionDataInfo(), Solution::TransientStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Discipline::ThermalAnalysis::performAdditionalOperationsOnGlobalQuantities(), and Driver::NonlinearTransientAnalysisDriver::solveCurrentLoadCase().
{
  PetscErrorCode ierr;
  PetscInt num1=0;
  ierr = VecGetSize (this->petsc_vec, &num1);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  return num1;
}
template<typename T > void FESystemNumerics::PetscVectorBase< T >::zero () [virtual]
Set every element in the matrix to 0. You must redefine what you mean by zeroing the matrix since it depends on how your values are stored.
Implements FESystemNumerics::VectorBase< T >.
Definition at line 175 of file PetscVectorBase.h.
References FESystem::COMM_WORLD.
Referenced by RadiationCavityAnalysis::calculateA_InverseMatrix(), RadiationCavityAnalysis::calculateB_InverseMatrix(), RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution(), RadiationCavityAnalysis::calculateEmissivityVector(), RadiationCavityAnalysis::calculateRadElemTempVector(), RadiationCavityAnalysis::getFEJacobianMatrix(), RadiationCavityAnalysis::getFENodalLoadVector(), RadiationCavityAnalysis::getFENodalLoadVectorSensitivity(), RadiationElement::getRadElemG_Vector(), RadiationCavityAnalysis::getTemperatureDependentFluxCorrectionVector(), FESystemNumerics::PetscMatrixBase< T >::leftMultiplyVector(), FESystemNumerics::PetscSeqVector< T >::PetscSeqVector(), and FESystemNumerics::PetscMatrixBase< T >::rightMultiplyVector().
{
  PetscErrorCode ierr;
  ierr = VecZeroEntries(this->petsc_vec);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->assemble();
}
Member Data Documentation
template<typename T> Vec FESystemNumerics::PetscVectorBase< T >::petsc_vec [protected]
Petsc matrix data structure.
Definition at line 143 of file PetscVectorBase.h.
Referenced by FESystemNumerics::PetscSeqVector< T >::PetscSeqVector().
template<typename T> LastAction FESystemNumerics::PetscVectorBase< T >::vector_last_action [protected]
last action performed, to decide whether to flush the matrix operations or not
Definition at line 140 of file PetscVectorBase.h.
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Numerics/PetscVectorBase.h