fesystem: NameEnumerationHandler Class Reference
NameEnumerationHandler Class Reference
#include <NameEnumHandler.h>
Public Member Functions
void registerNameAndID (const unsigned int ID, const std::string &name)
unsigned int getEnumerationID (const std::string &name) const
const std::string & getEnumerationName (unsigned int ID) const
this method returns an enumeration name for the given constant
Protected Types
typedef std::map< std::string,
unsigned int > NameToIDMap
typedef std::map< unsigned int,
std::string > IDToNameMap
Protected Member Functions
DeclException2 (ExcFESystemIDAlreadyExists, unsigned int, std::string,<< " Specified ID: "<< arg1<< " for Enumeration: "<< arg2<< " already taken by another class.")
DeclException2 (ExcFESystemNameAlreadyExists, unsigned int, std::string,<< " Specified Name: "<< arg2<< " for Enumeration ID: "<< arg1<< " already taken by another class.")
DeclException1 (ExcFESystemNameDoesNotExist, std::string,<< "Requested EnumName: "<< arg1<< " does not exist in map.")
this expception is thrown if the requested name does not exist in the map
DeclException1 (ExcFESystemIDDoesNotExist, unsigned int,<< "Requested EnumID: "<< arg1<< " does not exist in map.")
this expception is thrown if the requested name does not exist in the map
Protected Attributes
NameToIDMap name_to_id_map
this stores the ID for each name
IDToNameMap id_to_name_map
this stores the name for each ID
Detailed Description
This class provides an interface to define names that can be used as enumerations. It stores the names and assigns a unique ID to each. Then, each ID can be used as an enumeration constant, with an associated name.
Definition at line 21 of file NameEnumHandler.h.
Member Typedef Documentation
typedef std::map<unsigned int, std::string> NameEnumerationHandler::IDToNameMap [protected]
Definition at line 40 of file NameEnumHandler.h.
typedef std::map<std::string, unsigned int> NameEnumerationHandler::NameToIDMap [protected]
Definition at line 39 of file NameEnumHandler.h.
Member Function Documentation
NameEnumerationHandler::DeclException1 (ExcFESystemNameDoesNotExist , std::string , << "Requested EnumName: "<< arg1<< " does not exist in map.") [protected]
this expception is thrown if the requested name does not exist in the map
NameEnumerationHandler::DeclException1 (ExcFESystemIDDoesNotExist , unsigned int, << "Requested EnumID: "<< arg1<< " does not exist in map.") [protected]
this expception is thrown if the requested name does not exist in the map
NameEnumerationHandler::DeclException2 (ExcFESystemIDAlreadyExists , unsigned int, std::string , << " Specified ID: "<< arg1<< " for Enumeration: "<< arg2<< " already taken by another class.") [protected]
this exception is thrown if the an ID for an enumeration class is already taken by another class. If this error occurs then a different ID should be chosen
NameEnumerationHandler::DeclException2 (ExcFESystemNameAlreadyExists , unsigned int, std::string , << " Specified Name: "<< arg2<< " for Enumeration ID: "<< arg1<< " already taken by another class.") [protected]
this exception is thrown if the an name for an enumeration class is already taken by another class. If this error occurs then a different name should be chosen
unsigned int NameEnumerationHandler::getEnumerationID (const std::string & name) const [inline]
this method accepts a class object, whose enumeration constant has been returned
Definition at line 108 of file NameEnumHandler.h.
References name_to_id_map.
Referenced by MaterialPropertyNameBase::enumID(), and FESystemElem::FESystemElemTypeEnum::enumID().
{
  // get the iterator from the map and return the ID
  NameEnumerationHandler::NameToIDMap::const_iterator it, end;
  it = this->name_to_id_map.find(name);
  end = this->name_to_id_map.end();
  AssertThrow(it != end, ExcFESystemNameDoesNotExist(name));
  return it->second;
}
const std::string & NameEnumerationHandler::getEnumerationName (unsigned int ID) const [inline]
this method returns an enumeration name for the given constant
Definition at line 123 of file NameEnumHandler.h.
References id_to_name_map.
Referenced by MaterialPropertyNameBase::enumName(), and FESystemElem::FESystemElemTypeEnum::enumName().
{
  // also add in the reverse id to name map. Get the iterators for this ID
  NameEnumerationHandler::IDToNameMap::const_iterator reverse_map_it, reverse_map_end;
  reverse_map_it = this->id_to_name_map.find(ID);
  reverse_map_end = this->id_to_name_map.end();
  // make sure that the value exists
  AssertThrow(reverse_map_it != reverse_map_end, ExcFESystemIDDoesNotExist(ID));
  return reverse_map_it->second;
}
void NameEnumerationHandler::registerNameAndID (const unsigned int ID, const std::string & name) [inline]
this method accepts a class object, whose name is registered in the enumeration
Definition at line 73 of file NameEnumHandler.h.
References id_to_name_map, and name_to_id_map.
Referenced by MaterialPropertyNameEnumerationHandler::registerEnumData(), and FESystemElem::FESystemElemNameEnumerationHandler::registerEnumData().
{
  // find the name in the map. If it does not exist, add it, else return the
  // id for this name
  NameEnumerationHandler::NameToIDMap::const_iterator name_it, name_end;
  name_it = this->name_to_id_map.find(name);
  name_end = this->name_to_id_map.end();
  NameEnumerationHandler::IDToNameMap::const_iterator id_it, id_end;
  id_it = this->id_to_name_map.find(ID);
  id_end = this->id_to_name_map.end();
  // make sure that the id and name are unique
  Assert(name_it == name_end, ExcFESystemNameAlreadyExists(ID, name));
  Assert(id_it == id_end, ExcFESystemIDAlreadyExists(ID, name));
  // now add the name and ID to the map
  std::pair<NameEnumerationHandler::NameToIDMap::iterator, bool>
    return_pair = this->name_to_id_map.insert
    (NameEnumerationHandler::NameToIDMap::value_type(name, ID));
  assert (return_pair.second == true);
  std::pair<NameEnumerationHandler::IDToNameMap::iterator, bool>
    reverse_map_return_pair = this->id_to_name_map.insert
    (NameEnumerationHandler::IDToNameMap::value_type(ID, name));
  assert (return_pair.second == true);
}
Member Data Documentation
IDToNameMap NameEnumerationHandler::id_to_name_map [protected]
this stores the name for each ID
Definition at line 46 of file NameEnumHandler.h.
Referenced by getEnumerationName(), and registerNameAndID().
NameToIDMap NameEnumerationHandler::name_to_id_map [protected]
this stores the ID for each name
Definition at line 43 of file NameEnumHandler.h.
Referenced by getEnumerationID(), and registerNameAndID().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Utilities/NameEnumHandler.h