fesystem: Discipline::DisciplineInfo Class Reference
Discipline::DisciplineInfo Class Reference
#include <DisciplineInfo.h>
Public Member Functions
DisciplineInfo ()
constructor
virtual ~DisciplineInfo ()
destructor
unsigned int getID () const
unsigned int getMeshID () const
virtual unsigned int getDisciplineEnumID () const =0
virtual const std::string getDisciplineEnumName () const =0
unsigned int getAnalysisTypeEnumID () const
const std::string getAnalysisTypeEnumName () const
const std::set< unsigned int > & getLocalParameterSet () const
bool checkLocalParameterDependence (const unsigned int param_enum_ID) const
virtual std::istream & readFromInputStream (std::istream &input)=0
reads from the specified input stream
Protected Attributes
unsigned int ID
ID.
unsigned int mesh_ID
mesh ID
unsigned int analysis_type
analysis type
std::set< unsigned int > local_parameters
dependence of the analysis on local parameters
Friends
std::istream & operator>> (std::istream &input, Discipline::DisciplineInfo &info)
overloaded operator to read from input stream
Detailed Description
this forms a base class for storing the information of disciplinary analysis. the basic information for all finite element disciplinary analysis is the mesh, analysis kind, parameter dependence, etc.
Definition at line 25 of file DisciplineInfo.h.
Constructor & Destructor Documentation
Discipline::DisciplineInfo::DisciplineInfo ()
constructor
Definition at line 12 of file DisciplineInfo.C.
                                        :
ID(FESystemNumbers::InvalidID),
mesh_ID(FESystemNumbers::InvalidID),
analysis_type(FESystemNumbers::InvalidID)
{
}
Discipline::DisciplineInfo::~DisciplineInfo () [virtual]
destructor
Definition at line 23 of file DisciplineInfo.C.
{
}
Member Function Documentation
bool Discipline::DisciplineInfo::checkLocalParameterDependence (const unsigned int param_enum_ID) const [inline]
Returns:
true if this discipline is dependent on this local parameter
Parameters:
param_enum_ID parameter enum ID to be checked
Definition at line 143 of file DisciplineInfo.h.
{
  if (this->local_parameters.count(param_enum_ID) == 0)
    return false;
  else
    return true;
}
unsigned int Discipline::DisciplineInfo::getAnalysisTypeEnumID () const [inline]
Returns:
the discipline analysis type enumeration ID, which can be linear or nonlinear.
Definition at line 111 of file DisciplineInfo.h.
Referenced by Solution::SolutionBase::linearSolve(), Solution::SolutionBase::linearTransientSolve(), Solution::SolutionBase::nonlinearSolve(), Solution::SolutionBase::nonlinearTransientSolve(), Solution::TransientThermalSolution::solve(), Solution::TransientStructuralSolution::solve(), Solution::LinearizedBucklingEigenSolution::solve(), Solution::LinearStressSolution::solve(), Solution::ThermalSolution::solve(), and Solution::NonlinearStaticStructuralSolution::solve().
{
  return this->analysis_type;
}
const std::string Discipline::DisciplineInfo::getAnalysisTypeEnumName () const [inline]
Returns:
the discipline analysis type enumeration name, which can be linear or nonlinear.
Definition at line 122 of file DisciplineInfo.h.
{
  return Discipline::DisciplineAnalysisTypeEnum::enumName(this->analysis_type);
}
virtual unsigned int Discipline::DisciplineInfo::getDisciplineEnumID () const [pure virtual]
Returns:
the discipline enumeration ID
Implemented in Discipline::PistonTheoryInfo, Discipline::StructuralDisciplineInfo, Discipline::StructuralDisciplineInfo, and Discipline::ThermalDisciplineInfo.
Referenced by FESystem::AnalysisCase::addAnalysisDisciplineInfo().
virtual const std::string Discipline::DisciplineInfo::getDisciplineEnumName () const [pure virtual]
Returns:
the discipline enumeration name
Implemented in Discipline::PistonTheoryInfo, Discipline::StructuralDisciplineInfo, Discipline::StructuralDisciplineInfo, and Discipline::ThermalDisciplineInfo.
unsigned int Discipline::DisciplineInfo::getID () const [inline]
Definition at line 93 of file DisciplineInfo.h.
References ID.
{
  return this->ID;
}
const std::set< unsigned int > & Discipline::DisciplineInfo::getLocalParameterSet () const [inline]
Returns:
set of local parameters on which this analysis depends
Definition at line 133 of file DisciplineInfo.h.
{
  return this->local_parameters;
}
unsigned int Discipline::DisciplineInfo::getMeshID () const [inline]
Returns:
mesh ID of for the disciplinary analysis
Definition at line 101 of file DisciplineInfo.h.
Referenced by DirectInterpolation::createLoads().
{
  return this->mesh_ID;
}
virtual std::istream& Discipline::DisciplineInfo::readFromInputStream (std::istream & input) [pure virtual]
reads from the specified input stream
Implemented in Discipline::PistonTheoryInfo, Discipline::ThermalDisciplineInfo, Discipline::StructuralDisciplineInfo, and Discipline::StructuralDisciplineInfo.
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, Discipline::DisciplineInfo & info) [friend]
overloaded operator to read from input stream
Member Data Documentation
unsigned int Discipline::DisciplineInfo::analysis_type [protected]
analysis type
Definition at line 77 of file DisciplineInfo.h.
unsigned int Discipline::DisciplineInfo::ID [protected]
ID.
Definition at line 71 of file DisciplineInfo.h.
Referenced by getID().
std::set<unsigned int> Discipline::DisciplineInfo::local_parameters [protected]
dependence of the analysis on local parameters
Definition at line 80 of file DisciplineInfo.h.
unsigned int Discipline::DisciplineInfo::mesh_ID [protected]
mesh ID
Definition at line 74 of file DisciplineInfo.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Discipline/DisciplineInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Discipline/DisciplineInfo.C