fesystem: IsotropicElemDataCard Class Reference
IsotropicElemDataCard Class Reference
#include <IsotropicElemDataCard.h>
Public Member Functions
IsotropicElemDataCard ()
virtual ~IsotropicElemDataCard ()
unsigned int getMaterialCardID () const
returns the material card ID for this card
Property::PropertyCard< double > & getMaterialCard ()
returns the material card for this card
virtual bool checkElemAndMaterialCardGlobalParameterDependence (const unsigned int global_param_ID)
virtual bool checkElemAndMaterialCardLocalParameterDependence (const unsigned int local_param_ID)
virtual void reinitElemAndMaterialCardForLocalParameters (std::map< unsigned int, double > *value_map=NULL)
initializes the card and the material card for the given local parameters
virtual void reinitElemAndMaterialCardForGlobalParameters (std::map< unsigned int, double > &value_map)
initializes the card and the material card for the given global parameters
virtual void clearElemAndMaterialCardLocalParameterInitialization ()
clears initialization of the card and the material card for local parameters
virtual void partialClearElemAndMaterialCardLocalParameterInitialization (std::vector< unsigned int > &param_ids)
clears initialization of the card and the material card for local parameters
virtual void clearElemAndMaterialCardGlobalParameterInitialization ()
clears initialization of the card and the material card for global parameters
virtual void getPropertyValueFromMaterialCard (const unsigned int prop_enum_ID, double &value, const unsigned int layer=0)
returns value from material card
virtual void getPropertyValueDerivativeForGlobalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int global_param_ID, double &value, const unsigned int layer=0)
returns value of the derivative of a property from the material card
virtual void getPropertyValueDerivativeForLocalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int local_param_ID, double &value, const unsigned int layer=0)
returns value of the derivative of a property from the material card
virtual std::istream & readFromInputStream (std::istream &input)
this method reads from the input stream
Protected Attributes
unsigned int material_ID
material card ID for this card
Property::PropertyCard< double > * material_card
convenience
Detailed Description
Definition at line 11 of file IsotropicElemDataCard.h.
Constructor & Destructor Documentation
IsotropicElemDataCard::IsotropicElemDataCard () [inline]
Definition at line 94 of file IsotropicElemDataCard.h.
                                            :
ElemDataCard(),
material_ID(FESystemNumbers::InvalidID),
material_card(NULL)
{
}
IsotropicElemDataCard::~IsotropicElemDataCard () [inline, virtual]
Definition at line 105 of file IsotropicElemDataCard.h.
{
}
Member Function Documentation
bool IsotropicElemDataCard::checkElemAndMaterialCardGlobalParameterDependence (const unsigned int global_param_ID) [inline, virtual]
Returns:
true if either the element data card, or the material property card are dependent on the specified global parameter
Implements ElemDataCard.
Definition at line 368 of file IsotropicElemDataCard.h.
{
  if (this->checkGlobalParameterDependence(global_param_ID) &&
      this->getMaterialCard().checkGlobalParameterDependence(global_param_ID))
    return true;
  else
    return false;
}
bool IsotropicElemDataCard::checkElemAndMaterialCardLocalParameterDependence (const unsigned int local_param_ID) [inline, virtual]
Returns:
true if either the element data card, or the material property card are dependent on the specified local parameter
Implements ElemDataCard.
Definition at line 383 of file IsotropicElemDataCard.h.
{
  if (this->checkLocalParameterDependence(local_param_ID) &&
      this->getMaterialCard().checkLocalParameterDependence(local_param_ID))
    return true;
  else
    return false;
}
void IsotropicElemDataCard::clearElemAndMaterialCardGlobalParameterInitialization () [inline, virtual]
clears initialization of the card and the material card for global parameters
Implements ElemDataCard.
Definition at line 172 of file IsotropicElemDataCard.h.
References Property::PropertyCardBase::clearGlobalParameterInitialization(), and getMaterialCard().
{
  Property::PropertyCard<double>& property = this->getMaterialCard();
  this->clearGlobalParameterInitialization();
  property.clearGlobalParameterInitialization();
}
void IsotropicElemDataCard::clearElemAndMaterialCardLocalParameterInitialization () [inline, virtual]
clears initialization of the card and the material card for local parameters
Implements ElemDataCard.
Definition at line 147 of file IsotropicElemDataCard.h.
References Property::PropertyCardBase::clearLocalParameterInitialization(), and getMaterialCard().
{
  Property::PropertyCard<double>& property = this->getMaterialCard();
  this->clearLocalParameterInitialization();
  property.clearLocalParameterInitialization();
}
Property::PropertyCard< double > & IsotropicElemDataCard::getMaterialCard () [inline]
returns the material card for this card
Definition at line 196 of file IsotropicElemDataCard.h.
References Property::PropertyDatabase::getMaterialPropertyCardFromID(), material_card, material_ID, and ElemDataCard::property_database.
Referenced by clearElemAndMaterialCardGlobalParameterInitialization(), clearElemAndMaterialCardLocalParameterInitialization(), Isotropic3D_ElemDataCard::getFactor(), Isotropic2D_ElemDataCard::getFactor(), Isotropic1D_ElemDataCard::getFactor(), Isotropic3D_ElemDataCard::getFactorSensitivityForGlobalParameter(), Isotropic2D_ElemDataCard::getFactorSensitivityForGlobalParameter(), Isotropic3D_ElemDataCard::getFactorSensitivityForLocalParameter(), Isotropic2D_ElemDataCard::getFactorSensitivityForLocalParameter(), getPropertyValueFromMaterialCard(), and partialClearElemAndMaterialCardLocalParameterInitialization().
{
  if (this->material_card == NULL)
    this->material_card =
      &(this->property_database->getMaterialPropertyCardFromID<double>(this->material_ID));
  return *(this->material_card);
}
unsigned int IsotropicElemDataCard::getMaterialCardID () const [inline]
returns the material card ID for this card
Definition at line 184 of file IsotropicElemDataCard.h.
References FESystemNumbers::InvalidID, and material_ID.
{
  Assert(this->material_ID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(this->material_ID));
  return this->material_ID;
}
void IsotropicElemDataCard::getPropertyValueDerivativeForGlobalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int global_param_ID, double & value, const unsigned int layer = 0) [inline, virtual]
returns value of the derivative of a property from the material card
Implements ElemDataCard.
Definition at line 226 of file IsotropicElemDataCard.h.
{
  // layer not used for an Isotropic card
  (void) layer;
  Property::PropertyCard<double>& property = this->getMaterialCard();
  property.getPropertyDerivativeForGlobalParameter(prop_enum_ID,
                                                   global_param_ID,
                                                   value);
}
void IsotropicElemDataCard::getPropertyValueDerivativeForLocalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int local_param_ID, double & value, const unsigned int layer = 0) [inline, virtual]
returns value of the derivative of a property from the material card
Implements ElemDataCard.
Definition at line 245 of file IsotropicElemDataCard.h.
{
  // layer not used for an Isotropic card
  (void) layer;
  Property::PropertyCard<double>& property = this->getMaterialCard();
  property.getPropertyDerivativeForLocalParameter(prop_enum_ID,
                                                  local_param_ID,
                                                  value);
}
void IsotropicElemDataCard::getPropertyValueFromMaterialCard (const unsigned int prop_enum_ID, double & value, const unsigned int layer = 0) [inline, virtual]
returns value from material card
Implements ElemDataCard.
Definition at line 210 of file IsotropicElemDataCard.h.
References getMaterialCard().
{
  // layer not used for an Isotropic card
  (void) layer;
  Property::PropertyCard<double>& property = this->getMaterialCard();
  property.getPropertyValue(prop_enum_ID, value);
}
void IsotropicElemDataCard::partialClearElemAndMaterialCardLocalParameterInitialization (std::vector< unsigned int > & param_ids) [inline, virtual]
clears initialization of the card and the material card for local parameters
Implements ElemDataCard.
Definition at line 160 of file IsotropicElemDataCard.h.
References getMaterialCard(), and Property::PropertyCardBase::partialClearLocalParameterInitialization().
{
  Property::PropertyCard<double>& property = this->getMaterialCard();
  this->partialClearLocalParameterInitialization(param_ids);
  property.partialClearLocalParameterInitialization(param_ids);
}
std::istream & IsotropicElemDataCard::readFromInputStream (std::istream & input) [inline, virtual]
this method reads from the input stream
Implements ElemDataCard.
Definition at line 263 of file IsotropicElemDataCard.h.
References Property::PropertyCardBase::cardID, Property::PropertyCardBase::getNParameters(), Property::PropertyCard< double >::getNProperties(), Property::PropertyCardBase::getParameterInternalID(), Property::PropertyCardBase::getPropertyCardKindEnumName(), Property::PropertyCard< double >::getPropertyEnumID(), Property::PropertyCardBase::getPropertyInternalID(), FESystemNumbers::InvalidID, material_ID, Property::PropertyCardBase::parameter_function_ID_table, Property::PropertyCardBase::parameter_function_value_table, Property::PropertyCardBase::property_enumID_to_internal_ID_map, Property::PropertyCard< double >::property_reference_values, FESystemIOUtility::readFromInput(), and Property::PropertyCardBase::readParametersFromInputStream().
Referenced by operator>>().
{
  std::string tag;
  // read the beginning data of the card
  tag = this->getPropertyCardKindEnumName();
  FESystemIOUtility::readFromInput(input, tag);
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->cardID);
  FESystemIOUtility::readFromInput(input, "MATERIAL_PROPERTY_CARD_ID", this->material_ID);
  // now read in the property base values
  {
    unsigned int n_prop = 0, prop_ID = 0;
    double value = 0.0;
    bool insert_success = false;
    FESystemIOUtility::readFromInput(input, "N_PROPERTIES", n_prop);
    Property::PropertyCard<double>::PropertyMap::iterator prop_it;
    for (unsigned int i=0; i<n_prop; i++)
      {
      tag.clear(); value = 0.0;
      input >> tag;
      prop_ID = this->getPropertyEnumID(tag);
      input >> value;
      // now insert the value in the map
      insert_success = this->property_reference_values.insert
        (Property::PropertyCard<double>::PropertyMap::value_type
         (prop_ID, value)).second;
      Assert(insert_success,
             Property::PropertyCardBase::ExcDuplicatePropertySpecified(tag));
      insert_success = this->property_enumID_to_internal_ID_map.insert
        (Property::PropertyCardBase::IDMap::value_type(prop_ID, i)).second;
      // if the previous assert was true, this one should also be true.
      Assert(insert_success,
             Property::PropertyCardBase::ExcDuplicatePropertySpecified(tag));
      }
  }
  // now read the parameters
  this->readParametersFromInputStream(input);
  // now read in the property-parameter function ID table
  {
    // first initialize the table
    unsigned int n_prop = this->getNProperties(),
    n_param = this->getNParameters();
    this->parameter_function_ID_table->reinit(n_prop, n_param);
    this->parameter_function_ID_table->reset_values(FESystemNumbers::InvalidID);
    TableIndices<3> indices(n_prop, n_param, 2);
    this->parameter_function_value_table->reinit(indices);
    this->parameter_function_value_table->reset_values(0.0);
    unsigned int n_func_IDs, prop_ID = 0, param_ID = 0, func_ID = 0,
      prop_internal_ID = 0, param_internal_ID = 0;
    FESystemIOUtility::readFromInput(input, "N_FUNCTION_IDS", n_func_IDs);
    for (unsigned int i=0; i<n_func_IDs; i++)
      {
      tag.clear();
      input >> tag;
      prop_ID = this->getPropertyEnumID(tag);
      input >> param_ID;
      input >> func_ID;
      // get the internal IDS
      prop_internal_ID = this->getPropertyInternalID(prop_ID);
      param_internal_ID = this->getParameterInternalID(param_ID);
      // and, insert the value in the table
      // first make sure that this property hasn't already been set.
      Assert((*this->parameter_function_ID_table)(prop_internal_ID, param_internal_ID)  ==
             FESystemNumbers::InvalidID,
             FESystemExceptions::ExcDuplicateID("Property Function",prop_internal_ID));
      // and, insert the value in the table
      (*this->parameter_function_ID_table)(prop_internal_ID, param_internal_ID) = func_ID;
      }
  }
  // the card should end with the END tag
  tag = this->getPropertyCardKindEnumName();
  FESystemIOUtility::readFromInput(input, tag);
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
void IsotropicElemDataCard::reinitElemAndMaterialCardForGlobalParameters (std::map< unsigned int, double > & value_map) [inline, virtual]
initializes the card and the material card for the given global parameters
Implements ElemDataCard.
Definition at line 132 of file IsotropicElemDataCard.h.
{
  Property::PropertyCard<double>& property = this->getMaterialCard();
  this->reinitGlobalParameters(value_map);
  property.reinitGlobalParameters(value_map);
}
void IsotropicElemDataCard::reinitElemAndMaterialCardForLocalParameters (std::map< unsigned int, double > * value_map = NULL) [inline, virtual]
initializes the card and the material card for the given local parameters
Implements ElemDataCard.
Definition at line 116 of file IsotropicElemDataCard.h.
{
  Property::PropertyCard<double>& property = this->getMaterialCard();
  this->reinitLocalParameters(value_map);
  property.reinitLocalParameters(value_map);
}
Member Data Documentation
Property::PropertyCard<double>* IsotropicElemDataCard::material_card [protected]
convenience
this is a pointer to the material property card for this element, and is stored for
Definition at line 85 of file IsotropicElemDataCard.h.
Referenced by getMaterialCard().
unsigned int IsotropicElemDataCard::material_ID [protected]
material card ID for this card
Definition at line 81 of file IsotropicElemDataCard.h.
Referenced by getMaterialCard(), getMaterialCardID(), and readFromInputStream().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/IsotropicElemDataCard.h