fesystem: PostProcessQty Class Reference
PostProcessQty Class Reference
#include <PostProcessQty.h>
Public Member Functions
PostProcessQty ()
virtual ~PostProcessQty ()
destructor
void addTensor (const std::string &name, const TensorValue< double > &value)
TensorValue< double > & getTensor (const std::string &name)
gets the value of the tensor
Protected Attributes
std::map< std::string,
TensorValue< double > > name_tensor_map
map in which all the tensors are stored
Detailed Description
Definition at line 17 of file PostProcessQty.h.
Constructor & Destructor Documentation
PostProcessQty::PostProcessQty ()
constructor
Parameters:
order of the tensor
Definition at line 14 of file PostProcessQty.C.
{
}
PostProcessQty::~PostProcessQty () [virtual]
destructor
Definition at line 21 of file PostProcessQty.C.
{
}
Member Function Documentation
void PostProcessQty::addTensor (const std::string & name, const TensorValue< double > & value)
add the value of tensor, stored by name
Parameters:
name of the tensor
value of the tensor
Definition at line 28 of file PostProcessQty.C.
References name_tensor_map.
Referenced by ElemPostProcessQty::addMechanicalStrainTensor(), ElemPostProcessQty::addStrainTensor(), ElemPostProcessQty::addStressTensor(), and ElemPostProcessQty::calculatePrincipalStressTensor().
{
  // check if the tensor already exists in the map or not
  std::map<std::string, TensorValue<double> >::const_iterator qty_it = this->name_tensor_map.find(name);
  assert (qty_it == this->name_tensor_map.end());
  bool insert = this->name_tensor_map.insert(std::map<std::string, TensorValue<double> >::value_type(name, value)).second;
  assert (insert == true);
}
TensorValue< double > & PostProcessQty::getTensor (const std::string & name)
gets the value of the tensor
Definition at line 42 of file PostProcessQty.C.
References name_tensor_map.
Referenced by ElemPostProcessQty::getMechanicalStrainTensor(), ElemPostProcessQty::getPrincipalStressTensor(), ElemPostProcessQty::getStrainTensor(), and ElemPostProcessQty::getStressTensor().
{
  // check if the tensor already exists in the map or not
  std::map<std::string, TensorValue<double> >::iterator qty_it = this->name_tensor_map.find(name);
  assert (qty_it != this->name_tensor_map.end());
  return (qty_it->second);
}
Member Data Documentation
std::map<std::string, TensorValue<double> > PostProcessQty::name_tensor_map [protected]
map in which all the tensors are stored
Definition at line 41 of file PostProcessQty.h.
Referenced by addTensor(), and getTensor().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/PostProcess/PostProcessQty.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/PostProcess/PostProcessQty.C