fesystem: Loads::SurfaceConvectionLoadCombination Class Reference
Loads::SurfaceConvectionLoadCombination Class Reference
#include <LoadCombination.h>
Public Member Functions
SurfaceConvectionLoadCombination ()
virtual unsigned int getLoadClassEnumID () const
double getAmbientTemperature () const
double getConvectionCoeff () const
virtual void clear ()
virtual void addLoad (const double factor, const SurfaceLoad *load_ptr)
Protected Attributes
double temperature
double convection_coeff
Detailed Description
Definition at line 264 of file LoadCombination.h.
Constructor & Destructor Documentation
Loads::SurfaceConvectionLoadCombination::SurfaceConvectionLoadCombination () [inline]
Definition at line 267 of file LoadCombination.h.
                                        :
      SurfaceLoadCombination(),
      temperature(0.0),
      convection_coeff(0.0)
      {
      }
Member Function Documentation
virtual void Loads::SurfaceConvectionLoadCombination::addLoad (const double factor, const SurfaceLoad * load_ptr) [inline, virtual]
Implements Loads::SurfaceLoadCombination.
Definition at line 298 of file LoadCombination.h.
References convection_coeff, Loads::SurfaceLoadCombination::getElemID(), LoadBase::getLoadClassEnumID(), Loads::SurfaceLoadCombination::getSurfaceID(), Loads::SurfaceLoadCombination::load_set, and temperature.
      {
        Assert(load_ptr != NULL, ExcInternalError());
        Assert(load_ptr->getLoadClassEnumID() == SURFACE_CONVECTION_LOAD::num(),
               ExcInternalError());
        const SurfaceConvectionLoad* ptr = dynamic_cast<const SurfaceConvectionLoad*>(load_ptr);
        // set the node ID
        if (this->load_set.size() > 0)
          Assert(this->getElemID() == ptr->getElemID() &&
                 this->getSurfaceID() == ptr->getSurfaceID(),
                 ExcInternalError());
        bool insert_success = this->load_set.insert(load_ptr).second;
        // add this pointer to the set, and adjust the value of the load
        Assert(insert_success, ExcInternalError());
        this->temperature += factor * ptr->getAmbientTemperature();
        this->convection_coeff += factor * ptr->getConvectionCoeff();
      }
virtual void Loads::SurfaceConvectionLoadCombination::clear () [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 291 of file LoadCombination.h.
References convection_coeff, Loads::SurfaceLoadCombination::load_set, and temperature.
      {
        this->temperature = 0.0;
        this->convection_coeff = 0.0;
        this->load_set.clear();
      }
double Loads::SurfaceConvectionLoadCombination::getAmbientTemperature () const [inline]
Definition at line 280 of file LoadCombination.h.
References temperature.
      {
        return this->temperature;
      }
double Loads::SurfaceConvectionLoadCombination::getConvectionCoeff () const [inline]
Definition at line 286 of file LoadCombination.h.
References convection_coeff.
      {
        return this->convection_coeff;
      }
virtual unsigned int Loads::SurfaceConvectionLoadCombination::getLoadClassEnumID () const [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 275 of file LoadCombination.h.
      {
        return SURFACE_CONVECTION_LOAD::num();
      }
Member Data Documentation
double Loads::SurfaceConvectionLoadCombination::convection_coeff [protected]
Definition at line 326 of file LoadCombination.h.
Referenced by addLoad(), clear(), and getConvectionCoeff().
double Loads::SurfaceConvectionLoadCombination::temperature [protected]
Definition at line 324 of file LoadCombination.h.
Referenced by addLoad(), clear(), and getAmbientTemperature().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCombination.h