fesystem: Loads::LoadDataInfoBase Class Reference
Loads::LoadDataInfoBase Class Reference
#include <LoadDataInfo.h>
Public Member Functions
LoadDataInfoBase ()
virtual ~LoadDataInfoBase ()
virtual void clear ()
void setQtyScope (const Loads::LoadDataInfoScope enum_ID)
Loads::LoadDataInfoScope getQtyScope () const
void setLoadCaseID (const unsigned int ID)
unsigned int getLoadCaseID () const
void setLoadClassEnumID (const unsigned int enum_ID)
unsigned int getLoadClassEnumID () const
void setLoadNameEnumID (const unsigned int enum_ID)
unsigned int getLoadNameEnumID () const
bool ifSensitivity () const
void setDVID (const unsigned int ID)
unsigned int getDVID () const
bool ifTimeDependent () const
void setTime (const double t_val)
double getTime () const
Protected Attributes
Loads::LoadDataInfoScope qty_scope
stated if the quantity is for a single load or the entire set of loads
unsigned int load_case_ID
load case ID
unsigned int load_name_enum_ID
enum ID of the load for the discipline
unsigned int load_type_enum_ID
enum ID of the load type that has been specified, for example, SurfaceRadiationLoad, etc.
bool if_sensitivity
boolean to check if the load specification is for sensitivity
unsigned int DV_ID
design variable of ID
bool if_time_dependent
boolean to check if the load is time dependent
double time_value
time value
Detailed Description
Definition at line 24 of file LoadDataInfo.h.
Constructor & Destructor Documentation
Loads::LoadDataInfoBase::LoadDataInfoBase ()
Definition at line 12 of file LoadDataInfo.C.
                                       :
qty_scope(Loads::INVALID_SCOPE),
load_case_ID(FESystemNumbers::InvalidID),
load_name_enum_ID(FESystemNumbers::InvalidID),
load_type_enum_ID(FESystemNumbers::InvalidID),
if_sensitivity(false),
DV_ID(FESystemNumbers::InvalidID),
if_time_dependent(false),
time_value(0.0)
{
}
Loads::LoadDataInfoBase::~LoadDataInfoBase () [virtual]
Definition at line 26 of file LoadDataInfo.C.
{
  this->clear();
}
Member Function Documentation
void Loads::LoadDataInfoBase::clear () [virtual]
Reimplemented in Loads::DirichletBoundaryConditionDataInfo, Loads::NodalLoadDataInfo, Loads::SurfaceLoadDataInfo, and Loads::ElemLoadDataInfo.
Definition at line 34 of file LoadDataInfo.C.
References Loads::INVALID_SCOPE, and FESystemNumbers::InvalidID.
Referenced by Loads::ElemLoadDataInfo::clear(), Loads::NodalLoadDataInfo::clear(), and Loads::DirichletBoundaryConditionDataInfo::clear().
{
  this->qty_scope = Loads::INVALID_SCOPE;
  this->load_case_ID = FESystemNumbers::InvalidID;
  this->load_name_enum_ID = FESystemNumbers::InvalidID;
  this->load_type_enum_ID = FESystemNumbers::InvalidID;
  this->if_sensitivity = false;
  this->DV_ID = FESystemNumbers::InvalidID;
  this->if_time_dependent = false;
  this->time_value = 0.0;
}
unsigned int Loads::LoadDataInfoBase::getDVID () const
Definition at line 144 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by TimeIndependentLoadCase::getLoadFactorLoadSetPair(), and TimeDependentLoadCase::getLoadFactorLoadSetPair().
{
  Assert(this->DV_ID != FESystemNumbers::InvalidID, ExcInternalError());
  return this->DV_ID;
}
unsigned int Loads::LoadDataInfoBase::getLoadCaseID () const
Definition at line 78 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by LoadDatabase::getAllLoadCombinations< Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination >(), LoadDatabase::getAllLoadCombinations< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >(), LoadDatabase::getLoadCombination< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >(), LoadDatabase::getLoadCombination< Loads::SurfaceLoadDataInfo, Loads::SurfaceLoadCombination >(), and LoadDatabase::getLoadCombination< Loads::VolumeLoadDataInfo, Loads::VolumeLoadCombination >().
{
  Assert(this->load_case_ID != FESystemNumbers::InvalidID, ExcInternalError());
  return this->load_case_ID;
}
unsigned int Loads::LoadDataInfoBase::getLoadClassEnumID () const
Definition at line 96 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by LoadDatabase::getAllLoadCombinations< Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination >(), and LoadDatabase::getAllLoadCombinations< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >().
{
  Assert(this->load_type_enum_ID != FESystemNumbers::InvalidID, ExcInternalError());
  return this->load_type_enum_ID;
}
unsigned int Loads::LoadDataInfoBase::getLoadNameEnumID () const
Definition at line 115 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by TimeIndependentLoadCase::getLoadFactorLoadSetPair(), TimeDependentLoadCase::getLoadFactorLoadSetPair(), LoadDatabase::getAllLoadCombinations< Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination >(), LoadDatabase::getAllLoadCombinations< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >(), LoadDatabase::getLoadCombination< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >(), LoadDatabase::getLoadCombination< Loads::SurfaceLoadDataInfo, Loads::SurfaceLoadCombination >(), and LoadDatabase::getLoadCombination< Loads::VolumeLoadDataInfo, Loads::VolumeLoadCombination >().
{
  Assert(this->load_name_enum_ID != FESystemNumbers::InvalidID, ExcInternalError());
  return this->load_name_enum_ID;
}
Loads::LoadDataInfoScope Loads::LoadDataInfoBase::getQtyScope () const
Definition at line 59 of file LoadDataInfo.C.
References Loads::INVALID_SCOPE.
{
  Assert(this->qty_scope != Loads::INVALID_SCOPE, ExcInternalError());
  return this->qty_scope;
}
double Loads::LoadDataInfoBase::getTime () const
Definition at line 174 of file LoadDataInfo.C.
Referenced by TimeDependentLoadCase::getLoadFactorLoadSetPair().
{
  Assert(this->if_time_dependent, ExcInternalError());
  return this->time_value;
}
bool Loads::LoadDataInfoBase::ifSensitivity () const
Definition at line 124 of file LoadDataInfo.C.
Referenced by TimeIndependentLoadCase::getLoadFactorLoadSetPair(), and TimeDependentLoadCase::getLoadFactorLoadSetPair().
{
  return this->if_sensitivity;
}
bool Loads::LoadDataInfoBase::ifTimeDependent () const
Definition at line 153 of file LoadDataInfo.C.
Referenced by TimeIndependentLoadCase::getLoadFactorLoadSetPair(), and TimeDependentLoadCase::getLoadFactorLoadSetPair().
{
  return this->if_time_dependent;
}
void Loads::LoadDataInfoBase::setDVID (const unsigned int ID)
Definition at line 132 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads(), Discipline::FluidAnalysis::performAdditionalOperationsOnGlobalQuantities(), and Discipline::StructuralAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  Assert(ID != FESystemNumbers::InvalidID, ExcInternalError());
  Assert(this->DV_ID == FESystemNumbers::InvalidID, ExcInternalError());
  Assert(this->if_sensitivity == false, ExcInternalError());
  this->DV_ID = ID;
  this->if_sensitivity = true;
}
void Loads::LoadDataInfoBase::setLoadCaseID (const unsigned int ID)
Definition at line 68 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads(), Discipline::FluidAnalysis::performAdditionalOperationsOnGlobalQuantities(), and Discipline::StructuralAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  Assert(ID != FESystemNumbers::InvalidID, ExcInternalError());
  Assert(this->load_case_ID == FESystemNumbers::InvalidID, ExcInternalError());
  this->load_case_ID = ID;
}
void Loads::LoadDataInfoBase::setLoadClassEnumID (const unsigned int enum_ID)
Definition at line 87 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads(), Discipline::FluidAnalysis::performAdditionalOperationsOnGlobalQuantities(), and Discipline::StructuralAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  Assert(enum_ID != FESystemNumbers::InvalidID, ExcInternalError());
  Assert(this->load_type_enum_ID == FESystemNumbers::InvalidID, ExcInternalError());
  this->load_type_enum_ID = enum_ID;
}
void Loads::LoadDataInfoBase::setLoadNameEnumID (const unsigned int enum_ID)
Definition at line 105 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads(), Discipline::FluidAnalysis::performAdditionalOperationsOnGlobalQuantities(), and Discipline::StructuralAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  Assert(enum_ID != FESystemNumbers::InvalidID, ExcInternalError());
  Assert(this->load_name_enum_ID == FESystemNumbers::InvalidID, ExcInternalError());
  this->load_name_enum_ID = enum_ID;
}
void Loads::LoadDataInfoBase::setQtyScope (const Loads::LoadDataInfoScope enum_ID)
Definition at line 49 of file LoadDataInfo.C.
References Loads::INVALID_SCOPE.
{
  Assert(enum_ID != Loads::INVALID_SCOPE, ExcInternalError());
  Assert(this->qty_scope == Loads::INVALID_SCOPE, ExcInternalError());
  this->qty_scope = enum_ID;
}
void Loads::LoadDataInfoBase::setTime (const double t_val)
Definition at line 161 of file LoadDataInfo.C.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads(), Discipline::FluidAnalysis::performAdditionalOperationsOnGlobalQuantities(), and Discipline::StructuralAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  Assert(t_val >= 0.0, ExcInternalError());
  Assert(this->time_value == 0.0, ExcInternalError());
  Assert(!this->if_time_dependent, ExcInternalError());
  this->time_value = t_val;
  this->if_time_dependent = true;
}
Member Data Documentation
unsigned int Loads::LoadDataInfoBase::DV_ID [protected]
design variable of ID
Definition at line 79 of file LoadDataInfo.h.
bool Loads::LoadDataInfoBase::if_sensitivity [protected]
boolean to check if the load specification is for sensitivity
Definition at line 76 of file LoadDataInfo.h.
bool Loads::LoadDataInfoBase::if_time_dependent [protected]
boolean to check if the load is time dependent
Definition at line 82 of file LoadDataInfo.h.
unsigned int Loads::LoadDataInfoBase::load_case_ID [protected]
load case ID
Definition at line 67 of file LoadDataInfo.h.
unsigned int Loads::LoadDataInfoBase::load_name_enum_ID [protected]
enum ID of the load for the discipline
Definition at line 70 of file LoadDataInfo.h.
unsigned int Loads::LoadDataInfoBase::load_type_enum_ID [protected]
enum ID of the load type that has been specified, for example, SurfaceRadiationLoad, etc.
Definition at line 73 of file LoadDataInfo.h.
Loads::LoadDataInfoScope Loads::LoadDataInfoBase::qty_scope [protected]
stated if the quantity is for a single load or the entire set of loads
Definition at line 64 of file LoadDataInfo.h.
double Loads::LoadDataInfoBase::time_value [protected]
time value
Definition at line 85 of file LoadDataInfo.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadDataInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadDataInfo.C