fesystem: ElemDataCard Class Reference
ElemDataCard Class Reference
#include <ElemDataCard.h>
Public Member Functions
ElemDataCard ()
~ElemDataCard ()
void attachPropertyDatabase (Property::PropertyDatabase &database)
attached the property database to this card.
virtual void reinitElemAndMaterialCardForLocalParameters (std::map< unsigned int, double > *value_map=NULL)=0
initializes the card and the material card for the given local parameters
virtual void reinitElemAndMaterialCardForGlobalParameters (std::map< unsigned int, double > &value_map)=0
initializes the card and the material card for the given global parameters
virtual void clearElemAndMaterialCardLocalParameterInitialization ()=0
clears initialization of the card and the material card for local parameters
virtual void partialClearElemAndMaterialCardLocalParameterInitialization (std::vector< unsigned int > &param_ids)=0
virtual void clearElemAndMaterialCardGlobalParameterInitialization ()=0
clears initialization of the card and the material card for global parameters
virtual bool checkElemAndMaterialCardGlobalParameterDependence (const unsigned int global_param_ID)=0
virtual bool checkElemAndMaterialCardLocalParameterDependence (const unsigned int local_param_ID)=0
virtual void getFactor (double &factor, const unsigned int factor_enum_ID)=0
returns the value of the factor
virtual void getFactorSensitivityForGlobalParameter (double &factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID)=0
virtual void getFactorSensitivityForLocalParameter (double &factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID)=0
virtual void getFactor (DenseMatrix< double > &factor, const unsigned int factor_enum_ID)=0
returns the value of the factor
virtual void getFactorSensitivityForGlobalParameter (DenseMatrix< double > &factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID)=0
virtual void getFactorSensitivityForLocalParameter (DenseMatrix< double > &factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID)=0
virtual std::istream & readFromInputStream (std::istream &input)=0
this method reads from the input stream
virtual void getPropertyValueFromMaterialCard (const unsigned int prop_enum_ID, double &value, const unsigned int layer=0)=0
returns value from material card
virtual void getPropertyValueDerivativeForGlobalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int global_param_ID, double &value, const unsigned int layer=0)=0
returns value of the derivative of a property from the material card
virtual void getPropertyValueDerivativeForLocalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int local_param_ID, double &value, const unsigned int layer=0)=0
returns value of the derivative of a property from the material card
Protected Attributes
Property::PropertyDatabase * property_database
Detailed Description
Definition at line 261 of file ElemDataCard.h.
Constructor & Destructor Documentation
ElemDataCard::ElemDataCard ()
Definition at line 7 of file ElemDataCard.C.
                          :
Property::PropertyCard<double>()
{
}
ElemDataCard::~ElemDataCard ()
Definition at line 15 of file ElemDataCard.C.
{
}
Member Function Documentation
void ElemDataCard::attachPropertyDatabase (Property::PropertyDatabase & database) [inline]
attached the property database to this card.
Definition at line 359 of file ElemDataCard.h.
References property_database.
Referenced by Property::PropertyDatabase::readAndStoreElemDataCard().
{
  this->property_database = &database;
}
virtual bool ElemDataCard::checkElemAndMaterialCardGlobalParameterDependence (const unsigned int global_param_ID) [pure virtual]
Returns:
true if either the element data card, or the material property card are dependent on the specified global parameter
Implemented in ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
virtual bool ElemDataCard::checkElemAndMaterialCardLocalParameterDependence (const unsigned int local_param_ID) [pure virtual]
Returns:
true if either the element data card, or the material property card are dependent on the specified local parameter
Implemented in ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
virtual void ElemDataCard::clearElemAndMaterialCardGlobalParameterInitialization () [pure virtual]
clears initialization of the card and the material card for global parameters
Implemented in ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
virtual void ElemDataCard::clearElemAndMaterialCardLocalParameterInitialization () [pure virtual]
clears initialization of the card and the material card for local parameters
Implemented in ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
virtual void ElemDataCard::getFactor (double & factor, const unsigned int factor_enum_ID) [pure virtual]
returns the value of the factor
Implemented in ForcedConvection_1D_ElemDataCard, Isotropic1D_ElemDataCard, Isotropic2D_ElemDataCard, and Isotropic3D_ElemDataCard.
Referenced by RadiationCavityAnalysis::calculateB_Matrix().
virtual void ElemDataCard::getFactor (DenseMatrix< double > & factor, const unsigned int factor_enum_ID) [pure virtual]
returns the value of the factor
Implemented in ForcedConvection_1D_ElemDataCard, Isotropic1D_ElemDataCard, Isotropic2D_ElemDataCard, and Isotropic3D_ElemDataCard.
virtual void ElemDataCard::getFactorSensitivityForGlobalParameter (double & factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID) [pure virtual]
Implemented in ForcedConvection_1D_ElemDataCard, Isotropic1D_ElemDataCard, Isotropic2D_ElemDataCard, and Isotropic3D_ElemDataCard.
Referenced by RadiationCavityAnalysis::calculateB_Matrix().
virtual void ElemDataCard::getFactorSensitivityForGlobalParameter (DenseMatrix< double > & factor, const unsigned int factor_enum_ID, const unsigned int global_param_ID) [pure virtual]
Implemented in ForcedConvection_1D_ElemDataCard, Isotropic1D_ElemDataCard, Isotropic2D_ElemDataCard, and Isotropic3D_ElemDataCard.
virtual void ElemDataCard::getFactorSensitivityForLocalParameter (double & factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID) [pure virtual]
Implemented in ForcedConvection_1D_ElemDataCard, Isotropic1D_ElemDataCard, Isotropic2D_ElemDataCard, and Isotropic3D_ElemDataCard.
Referenced by RadiationCavityAnalysis::calculateB_TemperatureDependentJacobianContribution().
virtual void ElemDataCard::getFactorSensitivityForLocalParameter (DenseMatrix< double > & factor, const unsigned int factor_enum_ID, const unsigned int local_param_enum_ID) [pure virtual]
Implemented in ForcedConvection_1D_ElemDataCard, Isotropic1D_ElemDataCard, Isotropic2D_ElemDataCard, and Isotropic3D_ElemDataCard.
virtual void ElemDataCard::getPropertyValueDerivativeForGlobalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int global_param_ID, double & value, const unsigned int layer = 0) [pure virtual]
returns value of the derivative of a property from the material card
Implemented in ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
virtual void ElemDataCard::getPropertyValueDerivativeForLocalParameterFromMaterialCard (const unsigned int prop_enum_ID, const unsigned int local_param_ID, double & value, const unsigned int layer = 0) [pure virtual]
returns value of the derivative of a property from the material card
Implemented in ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
virtual void ElemDataCard::getPropertyValueFromMaterialCard (const unsigned int prop_enum_ID, double & value, const unsigned int layer = 0) [pure virtual]
returns value from material card
Implemented in ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
Referenced by RadiationCavityAnalysis::calculateEmissivityVector().
virtual void ElemDataCard::partialClearElemAndMaterialCardLocalParameterInitialization (std::vector< unsigned int > & param_ids) [pure virtual]
clears initialization of the card and the material card only for local parameters specified in the input vector
Implemented in ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
Referenced by RadiationCavityAnalysis::clearPropertyCardInitialization().
virtual std::istream& ElemDataCard::readFromInputStream (std::istream & input) [pure virtual]
this method reads from the input stream
Reimplemented from Property::PropertyCard< double >.
Implemented in ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
virtual void ElemDataCard::reinitElemAndMaterialCardForGlobalParameters (std::map< unsigned int, double > & value_map) [pure virtual]
initializes the card and the material card for the given global parameters
Implemented in ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
virtual void ElemDataCard::reinitElemAndMaterialCardForLocalParameters (std::map< unsigned int, double > * value_map = NULL) [pure virtual]
initializes the card and the material card for the given local parameters
Implemented in ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
Referenced by RadiationCavityAnalysis::initializePropertyCardAtElementTemperature().
Member Data Documentation
Property::PropertyDatabase* ElemDataCard::property_database [protected]
Definition at line 350 of file ElemDataCard.h.
Referenced by attachPropertyDatabase(), ForcedConvection_1D_ElemDataCard::getFluidMaterialCard(), IsotropicElemDataCard::getMaterialCard(), and ForcedConvection_1D_ElemDataCard::getWallMaterialCard().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/ElemDataCard.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/ElemDataCard.C