fesystem: Solver::EulerLinearTransientSolver Class Reference
Solver::EulerLinearTransientSolver Class Reference
#include <EulerTransientSolver.h>
Public Member Functions
EulerLinearTransientSolver (const Solver::LinearTransientSolverInfo &transient_info, const Solver::LinearSolverInfo &linear_info)
constructor
virtual ~EulerLinearTransientSolver ()
virtual void clear ()
virtual void solve ()
method to solve the eigen system
virtual double getSimulatedTime ()
virtual double getCurrentTime ()
virtual double getCurrentStepSize ()
virtual unsigned int getSimulatedIterationNumber ()
virtual unsigned int getCurrentIterationNumber ()
virtual void setInitialCondition (std::vector< NumericVector< double > * > &state_vecs)
set initial conditions for the analysis
Protected Attributes
double simulated_time
simulated time
double current_time
current time
double time_step_size
current step size
unsigned int simulated_iteration_number
simulated iteration number
std::auto_ptr
< Solver::LinearSolver > linear_solver
linear solver
FESystemUtility::AutoPtrVector
< NumericVector< double > > current_state_vectors
Detailed Description
this class provides an interface to a solver for the solution of eigensystem. This inherits from the FESystemSolverBase class. It takes a pointer to the analysis driver object that owns an instantiation of this class
Definition at line 79 of file EulerTransientSolver.h.
Constructor & Destructor Documentation
Solver::EulerLinearTransientSolver::EulerLinearTransientSolver (const Solver::LinearTransientSolverInfo & transient_info, const Solver::LinearSolverInfo & linear_info)
constructor
Definition at line 17 of file EulerTransientSolver.C.
                                           :
Solver::LinearTransientSolverBase(transient_info, linear_info),
simulated_time(0.0),
current_time(0.0),
time_step_size(0.0),
simulated_iteration_number(0)
{
}
Solver::EulerLinearTransientSolver::~EulerLinearTransientSolver () [virtual]
Definition at line 29 of file EulerTransientSolver.C.
{
}
Member Function Documentation
void Solver::EulerLinearTransientSolver::clear () [virtual]
this method clears the data structures of this object. This should be called each time the used finishes using this object.
Reimplemented from Solver::LinearTransientSolverBase.
Definition at line 38 of file EulerTransientSolver.C.
References Solver::LinearTransientSolverBase::clear().
{
  this->simulated_time = 0.0;
  this->current_time = 0.0;
  this->time_step_size = 0.0;
  this->simulated_iteration_number = 0;
  this->current_state_vectors.clear();
  Solver::LinearTransientSolverBase::clear();
}
unsigned int Solver::EulerLinearTransientSolver::getCurrentIterationNumber () [virtual]
Returns:
the current time iteration of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 235 of file EulerTransientSolver.C.
{
  return this->simulated_iteration_number + 1;
}
double Solver::EulerLinearTransientSolver::getCurrentStepSize () [virtual]
Returns:
the current time step of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 218 of file EulerTransientSolver.C.
{
  return this->time_step_size;
}
double Solver::EulerLinearTransientSolver::getCurrentTime () [virtual]
Returns:
the current time of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 204 of file EulerTransientSolver.C.
{
  return this->current_time;
}
unsigned int Solver::EulerLinearTransientSolver::getSimulatedIterationNumber () [virtual]
Returns:
the current time iteration of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 227 of file EulerTransientSolver.C.
{
  return this->simulated_iteration_number;
}
double Solver::EulerLinearTransientSolver::getSimulatedTime () [virtual]
Returns:
the current time of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 211 of file EulerTransientSolver.C.
{
  return this->simulated_time;
}
void Solver::EulerLinearTransientSolver::setInitialCondition (std::vector< NumericVector< double > * > & state_vecs) [virtual]
set initial conditions for the analysis
Implements Solver::TransientSolverBase.
Definition at line 168 of file EulerTransientSolver.C.
{
  // make sure that the current solutions have not been initialized
  Assert(this->current_state_vectors.size() == 0, ExcInternalError());
  unsigned int system_order =
  dynamic_cast<const Solver::EulerLinearTransientSolverInfo&>(this->transient_solver_info).getSystemOrder();
  // make sure that the number of vectors provided are one less than the system order
  Assert(state_vecs.size() == system_order,
         ExcInternalError());
  this->current_state_vectors.resize(system_order+1);
  std::auto_ptr<NumericVector<double> > vec;
  for (unsigned int i=0; i < system_order; i++)
    {
      vec.reset(NumericVector<double>::build().release());
      vec->duplicate_vector(*(state_vecs[i]), true);
      vec->close();
      this->current_state_vectors.reset(i, vec.release());
    }
  // finally, insert the highest order vectors. These vectors are later calculate from
  // the initial conditions.
  vec.reset(NumericVector<double>::build().release());
  vec->duplicate_vector(*(state_vecs[0]), false);
  vec->close();
  this->current_state_vectors.reset(system_order, vec.release());
}
void Solver::EulerLinearTransientSolver::solve () [virtual]
method to solve the eigen system
Implements Solver::TransientSolverBase.
Definition at line 53 of file EulerTransientSolver.C.
References Solver::createLinearSolver(), Driver::AnalysisDriver::getFESystemController(), Solver::EulerLinearTransientSolverInfo::getSystemOrder(), and FESystem::FESystemController::performance_logging.
{
  this->linear_solver.reset(Solver::createLinearSolver(this->linear_solver_info).release());
  this->linear_solver->attachAnalysisDriver(this->analysis_driver);
  const Solver::EulerLinearTransientSolverInfo& newmark_info =
  dynamic_cast<const Solver::EulerLinearTransientSolverInfo&>(this->transient_solver_info);
  unsigned int system_order = newmark_info.getSystemOrder();
  // for now, this implementation is only for 1st order system
  Assert(system_order == 1, ExcInternalError());
  // make sure that the solver has the necessary information
  Assert(this->coefficient_matrices.size() == (system_order+1), ExcInternalError());
  Assert(this->current_state_vectors.size() == (system_order+1), ExcInternalError());
  this->analysis_driver->getFESystemController().performance_logging->setEvent
  ("EulerLinearTransientSolver::solve()", "Solver");
  // create the vectors to be used in this solution
  std::auto_ptr<NumericVector<double> >
  external_force_vector(NumericVector<double>::build().release()),
  scratch_vec1(NumericVector<double>::build().release());
  external_force_vector->duplicate_vector(*(this->current_state_vectors[0]), false);
  scratch_vec1->duplicate_vector(*(this->current_state_vectors[0]), false);
  // init the iteration data
  this->simulated_time = this->transient_solver_info.getInitialTime();
  this->current_time = this->simulated_time;
  this->simulated_iteration_number = 0;
  // the basic equation to be solved is
  // dX/dt^(n) = inv(C_(n)) * (F_0 - sum_(i=0..n-1) (C_i * dX/dt^(i)))
  while (this->getSimulatedTime() < this->transient_solver_info.getFinalTime())
    {
      if (this->simulated_iteration_number > 0)
        {
          scratch_vec1->zero();
          scratch_vec1->close();
          scratch_vec1->add(this->transient_solver_info.getInitialTimeStep(),
                            *(this->current_state_vectors[1]));
          scratch_vec1->add(1.0, *(this->current_state_vectors[0]));
          scratch_vec1->close();
          this->current_state_vectors[0]->zero();
          this->current_state_vectors[0]->close();
          this->current_state_vectors[0]->add(1.0, *scratch_vec1);
          this->current_state_vectors[0]->close();
        }
      // ask the driver to init the matrices. This needs to be done only once for a system where
      // the matrices are constant with iterations
      if (!this->time_independent_coefficient_matrices || this->simulated_iteration_number == 0)
        {
          dynamic_cast<Driver::TransientAnalysisDriver*>(this->analysis_driver)->
          getCoefficientMatrices(this->getCurrentTime(),
                                 this->coefficient_matrices);
          this->coefficient_matrices[system_order]->close();
          this->linear_solver->setSystemMatrix(*(this->coefficient_matrices[system_order]));
          this->linear_solver->setPreconditionerMatrix(*(this->coefficient_matrices[system_order]));
          this->linear_solver->useSameMatricesBetweenSolves();
        }
      // ask the driver to init the force vector;
      dynamic_cast<Driver::TransientAnalysisDriver*>(this->analysis_driver)->
      getForceVector(this->getCurrentTime(),
                     *external_force_vector);
      external_force_vector->close();
      // calculate the RHS of the linear equation
      scratch_vec1->zero();
      scratch_vec1->close();
      this->coefficient_matrices[0]->close();
      this->coefficient_matrices[0]->multiply_vector(*(this->current_state_vectors[0]),
                                                     *scratch_vec1);
      scratch_vec1->close();
      external_force_vector->add(-1.0, *scratch_vec1);
      external_force_vector->close();
      // now solve for the new iterate
      this->linear_solver->solve(*external_force_vector,
                                 *(this->current_state_vectors[1]));
      this->current_state_vectors[1]->close();
      // increment the current time and the iteration number
      this->current_time += this->transient_solver_info.getInitialTimeStep();
      this->simulated_time =
      this->getCurrentTime() - this->transient_solver_info.getInitialTimeStep();
      this->simulated_iteration_number++;
      // tell the analysis driver to record the iteration increment
      dynamic_cast<Driver::TransientAnalysisDriver*>(this->analysis_driver)->
      setNewIteration(this->getSimulatedTime(),
                      this->getSimulatedIterationNumber(),
                      this->current_state_vectors.getReference());
    }
  this->linear_solver.reset();
  this->analysis_driver->getFESystemController().performance_logging->unsetEvent
  ("EulerLinearTransientSolver::solve()", "Solver");
}
Member Data Documentation
FESystemUtility::AutoPtrVector<NumericVector<double> > Solver::EulerLinearTransientSolver::current_state_vectors [protected]
internal state vectors, arranged in increasing order of time derivative. The (n-1)th iterates are stored here
Definition at line 134 of file EulerTransientSolver.h.
double Solver::EulerLinearTransientSolver::current_time [protected]
current time
Definition at line 121 of file EulerTransientSolver.h.
std::auto_ptr<Solver::LinearSolver> Solver::EulerLinearTransientSolver::linear_solver [protected]
linear solver
Definition at line 130 of file EulerTransientSolver.h.
unsigned int Solver::EulerLinearTransientSolver::simulated_iteration_number [protected]
simulated iteration number
Definition at line 127 of file EulerTransientSolver.h.
double Solver::EulerLinearTransientSolver::simulated_time [protected]
simulated time
Definition at line 118 of file EulerTransientSolver.h.
double Solver::EulerLinearTransientSolver::time_step_size [protected]
current step size
Definition at line 124 of file EulerTransientSolver.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/EulerTransientSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/EulerTransientSolver.C