fesystem: Solution::SolutionBase Class Reference
Solution::SolutionBase Class Reference
this class provides the base functionality for all solutions
#include <SolutionBase.h>
Public Member Functions
SolutionBase (const unsigned int sol_enum_ID)
constructor
virtual ~SolutionBase ()
destructor
unsigned int getID () const
unsigned int getSolutionEnumID () const
std::string getSolutionEnumName () const
bool checkParticipatingDiscipline (const unsigned int discipline_enum_id)
virtual unsigned int getDisciplineTransientNatureEnumID (const unsigned int discipline) const =0
virtual
FESystemUtility::AutoPtrVector
< FESystemDatabase::DataInfoBase > getTimeIndependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID)=0
virtual
FESystemUtility::AutoPtrVector
< FESystemDatabase::TransientDataInfoSet > getTimeDependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID)=0
const std::vector< unsigned int > & getLoadCaseIDs () const
the vector of analysis load cases
void attachFESystemController (FESystem::FESystemController &controller)
attaches the FESystemController to this object for solution purposes
unsigned int getSolverInfoID (const unsigned int solver_class) const
virtual void solve ()=0
this method will solve for all the load cases and sensitivity analysis
virtual std::istream & readFromInputStream (std::istream &input)=0
will read from the input stream
Protected Member Functions
void addParticipatingDiscipline (const unsigned int discipline_enum_ID)
adds a participating discipline to this solution
void addSolverID (const unsigned int solver_class, const unsigned int solver_info_ID)
adds the solver ID for the solver class
void linearSolve (const unsigned int discipline_enum)
this method will solve for all the load cases and sensitivity analysis
void nonlinearSolve (const unsigned int discipline_enum)
this method will solve for all the load cases and sensitivity analysis
void eigenSolve (const unsigned int discipilne_enum)
this method will solve for all load cases and sensitivity analysis
void linearTransientSolve (const unsigned int discipline_enum)
this method will solve for all the load cases and sensitivity analysis
void nonlinearTransientSolve (const unsigned int discipline_enum)
this method will solve for all the load cases and sensitivity analysis
Protected Attributes
FESystem::FESystemController * fesystem_controller
reference to the FESystemController class
const unsigned int solution_enum_ID
enum ID of the solution
unsigned int ID
ID of this solution.
std::map< unsigned int,
unsigned int > solver_info_ID_map
solver info IDs per solver class
std::vector< unsigned int > load_case_IDs
vector of load case IDs that will be used in the analysis
std::set< unsigned int > discipline_enum_IDs
participating disciplines for this soltion
Friends
std::istream & operator>> (std::istream &input, Solution::SolutionBase &solution)
overloaded operator to read from input stream
Detailed Description
this class provides the base functionality for all solutions
Definition at line 47 of file SolutionBase.h.
Constructor & Destructor Documentation
Solution::SolutionBase::SolutionBase (const unsigned int sol_enum_ID)
constructor
Definition at line 34 of file SolutionBase.C.
                                                                :
fesystem_controller(NULL),
solution_enum_ID(sol_enum_ID),
ID(FESystemNumbers::InvalidID)
{
}
Solution::SolutionBase::~SolutionBase () [virtual]
destructor
Definition at line 43 of file SolutionBase.C.
{
}
Member Function Documentation
void Solution::SolutionBase::addParticipatingDiscipline (const unsigned int discipline_enum_ID) [protected]
adds a participating discipline to this solution
Definition at line 95 of file SolutionBase.C.
Referenced by Solution::AeroelasticitySolution::AeroelasticitySolution(), Solution::LinearizedBucklingEigenSolution::LinearizedBucklingEigenSolution(), Solution::LinearStressSolution::LinearStressSolution(), Solution::NonlinearStaticStructuralSolution::NonlinearStaticStructuralSolution(), Solution::StructuralVibrationEigenSolution::StructuralVibrationEigenSolution(), Solution::ThermalSolution::ThermalSolution(), Solution::TransientStructuralSolution::TransientStructuralSolution(), and Solution::TransientThermalSolution::TransientThermalSolution().
{
  bool insert_success =
    this->discipline_enum_IDs.insert(discipline_enum_ID).second;
  Assert(insert_success, ExcInternalError());
}
void Solution::SolutionBase::addSolverID (const unsigned int solver_class, const unsigned int solver_info_ID) [protected]
adds the solver ID for the solver class
Definition at line 121 of file SolutionBase.C.
{
  bool insert_success =
  this->solver_info_ID_map.insert(std::map<unsigned int, unsigned int>::value_type
                                  (solver_class, solver_info_ID)).second;
  Assert(insert_success,
         FESystemExceptions::ExcDuplicateID("Solver Class", solver_class));
}
void Solution::SolutionBase::attachFESystemController (FESystem::FESystemController & controller)
attaches the FESystemController to this object for solution purposes
Definition at line 65 of file SolutionBase.C.
{
  this->fesystem_controller = &controller;
}
bool Solution::SolutionBase::checkParticipatingDiscipline (const unsigned int discipline_enum_id)
Returns:
true if the specified discipline participates in the solution
Definition at line 73 of file SolutionBase.C.
{
  // first make sure that the participating disciplines have been initialized
  Assert(this->discipline_enum_IDs.size() > 0,
         ExcInternalError());
  // now check if the discipline is participating in this solution
  unsigned int n_count = this->discipline_enum_IDs.count(discipline_enum_id);
  if (n_count == 0)
    return false;
  else
    return true;
  // should never get here
  Assert(false, ExcInternalError());
  return false;
}
void Solution::SolutionBase::eigenSolve (const unsigned int discipilne_enum) [protected]
this method will solve for all load cases and sensitivity analysis
Definition at line 276 of file SolutionBase.C.
References Driver::AnalysisDriver::attachAnalysisDiscipline(), Discipline::AnalysisDisciplineBase::attachSolution(), Driver::AnalysisDriver::attachSolution(), Driver::AnalysisDriver::attachSolver(), Discipline::AnalysisDisciplineBase::clear(), Driver::AnalysisDriver::clear(), Solver::createEigenSolver(), Solver::createLinearSolver(), Solver::EigenSolverInfo::getLinearSolverInfoID(), Driver::AnalysisDriver::solveForLoadCases(), and Driver::AnalysisDriver::solveForLoadCaseSensitivity().
{
  // next, get the discipline and drivers for this analysis
  Discipline::AnalysisDisciplineBase *discipline =
    this->fesystem_controller->getAnalysisDiscipline(discipline_enum);
  discipline->clear();
  discipline->attachSolution(this);
  Driver::AnalysisDriver *driver =
    this->fesystem_controller->getAnalysisDriver(Driver::EIGENPROBLEM_ANALYSIS_DRIVER::num());
  // attach the discipline and driver to each other
  driver->clear();
  driver->attachAnalysisDiscipline(discipline);
  driver->attachSolution(this);
  // get the load cases and design variables to be solved for
  std::auto_ptr<std::vector<DesignData::DesignParameter*> >
    dv_vector(this->fesystem_controller->design_database->getParameters().release());
  // next, peform the analysis
  this->fesystem_controller->initPropertyCardsForGlobalParameters();
  // attach a nonlinear solver to the driver and perform the nonlinear analysis
  unsigned int eigen_solver_info_id = this->getSolverInfoID(Solver::EIGEN_SOLVER::num());
  const Solver::EigenSolverInfo& eigen_info =
    dynamic_cast<const Solver::EigenSolverInfo&>
    (this->fesystem_controller->analysis_case->getSolverInfo(eigen_solver_info_id));
  unsigned int linear_info_ID = eigen_info.getLinearSolverInfoID();
  const Solver::LinearSolverInfo& linear_info =
    dynamic_cast<const Solver::LinearSolverInfo&>
    (this->fesystem_controller->analysis_case->getSolverInfo(linear_info_ID));
  std::auto_ptr<Solver::FESystemSolverBase>
    solver(Solver::createEigenSolver(eigen_info, linear_info).release());
  solver->clear();
  driver->attachSolver(solver.get());
  driver->solveForLoadCases(this->load_case_IDs);
  solver->clear();
  // if there are any DVs, then attach the linear solver and perform
  // sensitivity analysis
  if (dv_vector->size() > 0)
    {
    unsigned int solver_info_id = this->getSolverInfoID(Solver::LINEAR_SOLVER::num());
    const Solver::LinearSolverInfo& sol_linear_info =
      dynamic_cast<const Solver::LinearSolverInfo&>
      (this->fesystem_controller->analysis_case->getSolverInfo(solver_info_id));
    solver.reset(Solver::createLinearSolver(sol_linear_info).release());
    solver->clear();
    driver->attachSolver(solver.get());
    driver->solveForLoadCaseSensitivity(*(dv_vector.get()), this->load_case_IDs);
    solver->clear();
    }
    //  driver->postProcess();
  // now clear the initializations
  this->fesystem_controller->property_database->clearLocalParameterInitializationForAllCards();
  this->fesystem_controller->property_database->clearGlobalParameterInitializationForAllCards();
  // now clear the data structures before returning
  discipline->clear();
  driver->clear();
}
virtual unsigned int Solution::SolutionBase::getDisciplineTransientNatureEnumID (const unsigned int discipline) const [pure virtual]
Returns:
the transient nature of the given discipline
Implemented in Solution::NonlinearStaticStructuralSolution, Solution::AeroelasticitySolution, Solution::LinearStressSolution, Solution::LinearizedBucklingEigenSolution, Solution::StructuralVibrationEigenSolution, Solution::ThermalSolution, Solution::TransientStructuralSolution, and Solution::TransientThermalSolution.
Referenced by RadiationCavityAnalysis::getDataInfoForQty().
unsigned int Solution::SolutionBase::getID () const [inline]
Returns:
the ID of this object
Definition at line 171 of file SolutionBase.h.
References ID.
Referenced by FESystem::AnalysisCase::addSolutionBase().
{
  return this->ID;
}
const std::vector< unsigned int > & Solution::SolutionBase::getLoadCaseIDs () const [inline]
the vector of analysis load cases
Definition at line 179 of file SolutionBase.h.
{
  return this->load_case_IDs;
}
unsigned int Solution::SolutionBase::getSolutionEnumID () const
Returns:
the solution enum ID for this solution
Definition at line 50 of file SolutionBase.C.
{
  return this->solution_enum_ID;
}
std::string Solution::SolutionBase::getSolutionEnumName () const
Returns:
the solution enum name for this solution
Definition at line 57 of file SolutionBase.C.
{
  return Solution::SolutionEnum::enumName(this->solution_enum_ID);
}
unsigned int Solution::SolutionBase::getSolverInfoID (const unsigned int solver_class) const
Returns:
the SolverInfo ID for the solver class solver_class enumeration ID of the solver class
Definition at line 106 of file SolutionBase.C.
{
  std::map<unsigned int, unsigned int>::const_iterator it, end;
  it = this->solver_info_ID_map.find(solver_class);
  end = this->solver_info_ID_map.end();
  Assert(it != end,
         FESystemExceptions::ExcIDDoesNotExist("Solver Class", solver_class));
  return it->second;
}
virtual FESystemUtility::AutoPtrVector<FESystemDatabase::TransientDataInfoSet> Solution::SolutionBase::getTimeDependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID) [pure virtual]
Returns:
the vector of SolNameInfo structures for the nodal solutions, and for the specified disciplines
Implemented in Solution::NonlinearStaticStructuralSolution, Solution::AeroelasticitySolution, Solution::LinearStressSolution, Solution::LinearizedBucklingEigenSolution, Solution::StructuralVibrationEigenSolution, Solution::ThermalSolution, Solution::TransientStructuralSolution, and Solution::TransientThermalSolution.
virtual FESystemUtility::AutoPtrVector<FESystemDatabase::DataInfoBase> Solution::SolutionBase::getTimeIndependentNodalSolutionDataInfo (const unsigned int discipline_enum_ID) [pure virtual]
Returns:
the vector of SolNameInfo structures for the nodal solutions, and for the specified disciplines
Implemented in Solution::NonlinearStaticStructuralSolution, Solution::AeroelasticitySolution, Solution::LinearStressSolution, Solution::LinearizedBucklingEigenSolution, Solution::StructuralVibrationEigenSolution, Solution::ThermalSolution, Solution::TransientStructuralSolution, and Solution::TransientThermalSolution.
void Solution::SolutionBase::linearSolve (const unsigned int discipline_enum) [protected]
this method will solve for all the load cases and sensitivity analysis
Definition at line 136 of file SolutionBase.C.
References Driver::AnalysisDriver::attachAnalysisDiscipline(), Driver::AnalysisDriver::attachSolution(), Driver::AnalysisDriver::attachSolver(), Discipline::AnalysisDisciplineBase::clear(), Driver::AnalysisDriver::clear(), Solver::createLinearSolver(), Discipline::DisciplineInfo::getAnalysisTypeEnumID(), info, Driver::AnalysisDriver::solveForLoadCases(), and Driver::AnalysisDriver::solveForLoadCaseSensitivity().
{
  const Discipline::DisciplineInfo& info =
  this->fesystem_controller->analysis_case->getAnalysisDisciplineInfo
  (discipline_enum);
  // first, make sure that the discipline is for a linear analysis only
  Assert(info.getAnalysisTypeEnumID() == Discipline::LINEAR_ANALYSIS::num(),
         ExcInternalError());
  // next, get the discipline and drivers for this analysis
  Discipline::AnalysisDisciplineBase *discipline =
    this->fesystem_controller->getAnalysisDiscipline(discipline_enum);
  discipline->clear();
  discipline->attachSolution(this);
  Driver::AnalysisDriver *driver =
    this->fesystem_controller->getAnalysisDriver(Driver::LINEAR_ANALYSIS_DRIVER::num());
  // attach the discipline and driver to each other
  driver->clear();
  driver->attachAnalysisDiscipline(discipline);
  driver->attachSolution(this);
  // get the load cases and design variables to be solved for
  std::auto_ptr<std::vector<DesignData::DesignParameter*> >
    dv_vector(this->fesystem_controller->design_database->getParameters().release());
  // next, peform the analysis
  this->fesystem_controller->initPropertyCardsForGlobalParameters();
  // attach a linear solver to the driver and perform the analysis
  unsigned int solver_info_id = this->getSolverInfoID(Solver::LINEAR_SOLVER::num());
  const Solver::LinearSolverInfo& linear_info = dynamic_cast<const Solver::LinearSolverInfo&>
    (this->fesystem_controller->analysis_case->getSolverInfo(solver_info_id));
  std::auto_ptr<Solver::FESystemSolverBase>
    solver(Solver::createLinearSolver(linear_info).release());
  solver->clear();
  driver->attachSolver(solver.get());
  driver->solveForLoadCases(this->load_case_IDs);
  driver->solveForLoadCaseSensitivity(*(dv_vector.get()), this->load_case_IDs);
  //  driver->postProcess();
  // now clear the initializations
  this->fesystem_controller->property_database->clearLocalParameterInitializationForAllCards();
  this->fesystem_controller->property_database->clearGlobalParameterInitializationForAllCards();
  // now clear the data structures after use
  solver->clear();
  discipline->clear();
  driver->clear();
}
void Solution::SolutionBase::linearTransientSolve (const unsigned int discipline_enum) [protected]
this method will solve for all the load cases and sensitivity analysis
Definition at line 350 of file SolutionBase.C.
References Driver::AnalysisDriver::attachAnalysisDiscipline(), Driver::AnalysisDriver::attachSolution(), Driver::AnalysisDriver::attachSolver(), Discipline::AnalysisDisciplineBase::clear(), Driver::AnalysisDriver::clear(), Solver::createLinearTransientSolver(), Discipline::DisciplineInfo::getAnalysisTypeEnumID(), Solver::LinearTransientSolverInfo::getLinearSolverInfoID(), info, Driver::AnalysisDriver::solveForLoadCases(), and Driver::AnalysisDriver::solveForLoadCaseSensitivity().
{
  const Discipline::DisciplineInfo& info =
  this->fesystem_controller->analysis_case->getAnalysisDisciplineInfo
  (discipline_enum);
  // first, make sure that the discipline is for a linear analysis only
  Assert(info.getAnalysisTypeEnumID() == Discipline::LINEAR_ANALYSIS::num(),
         ExcInternalError());
  // next, get the discipline and drivers for this analysis
  Discipline::AnalysisDisciplineBase *discipline =
    this->fesystem_controller->getAnalysisDiscipline(discipline_enum);
  discipline->clear();
  discipline->attachSolution(this);
  Driver::AnalysisDriver *driver = this->fesystem_controller->getAnalysisDriver
    (Driver::LINEAR_TRANSIENT_ANALYSIS_DRIVER::num());
  // attach the discipline and driver to each other
  driver->clear();
  driver->attachAnalysisDiscipline(discipline);
  driver->attachSolution(this);
  // get the load cases and design variables to be solved for
  std::auto_ptr<std::vector<DesignData::DesignParameter*> >
    dv_vector(this->fesystem_controller->design_database->getParameters().release());
  // next, peform the analysis
  this->fesystem_controller->initPropertyCardsForGlobalParameters();
  // attach a nonlinear solver to the driver and perform the nonlinear analysis
  unsigned int transient_solver_info_id = this->getSolverInfoID(Solver::LINEAR_TRANSIENT_SOLVER::num());
  const Solver::LinearTransientSolverInfo& transient_info =
    dynamic_cast<const Solver::LinearTransientSolverInfo&>
    (this->fesystem_controller->analysis_case->getSolverInfo(transient_solver_info_id));
  unsigned int linear_info_ID = transient_info.getLinearSolverInfoID();
  const Solver::LinearSolverInfo& linear_info =
    dynamic_cast<const Solver::LinearSolverInfo&>
    (this->fesystem_controller->analysis_case->getSolverInfo(linear_info_ID));
  std::auto_ptr<Solver::FESystemSolverBase>
    solver(Solver::createLinearTransientSolver(transient_info, linear_info).release());
  solver->clear();
  driver->attachSolver(solver.get());
  driver->solveForLoadCases(this->load_case_IDs);
  // if there are any DVs, then attach the linear solver and perform
  // sensitivity analysis
  if (dv_vector->size() > 0)
    driver->solveForLoadCaseSensitivity(*(dv_vector.get()), this->load_case_IDs);
  solver->clear();
  //  driver->postProcess();
  // now clear the initializations
  this->fesystem_controller->property_database->clearLocalParameterInitializationForAllCards();
  this->fesystem_controller->property_database->clearGlobalParameterInitializationForAllCards();
  // now clear the data structures before returning
  discipline->clear();
  driver->clear();
}
void Solution::SolutionBase::nonlinearSolve (const unsigned int discipline_enum) [protected]
this method will solve for all the load cases and sensitivity analysis
Definition at line 195 of file SolutionBase.C.
References Driver::AnalysisDriver::attachAnalysisDiscipline(), Driver::AnalysisDriver::attachSolution(), Driver::AnalysisDriver::attachSolver(), Discipline::AnalysisDisciplineBase::clear(), Driver::AnalysisDriver::clear(), Solver::createLinearSolver(), Solver::createNonlinearSolver(), Discipline::DisciplineInfo::getAnalysisTypeEnumID(), Solver::NonlinearSolverInfo::getLinearSolverInfoID(), info, Driver::AnalysisDriver::solveForLoadCases(), and Driver::AnalysisDriver::solveForLoadCaseSensitivity().
{
  const Discipline::DisciplineInfo& info =
  this->fesystem_controller->analysis_case->getAnalysisDisciplineInfo
  (discipline_enum);
  // first, make sure that the discipline is for a linear analysis only
  Assert(info.getAnalysisTypeEnumID() == Discipline::NONLINEAR_ANALYSIS::num(),
         ExcInternalError());
  // next, get the discipline and drivers for this analysis
  Discipline::AnalysisDisciplineBase *discipline =
    this->fesystem_controller->getAnalysisDiscipline(discipline_enum);
  discipline->clear();
  discipline->attachSolution(this);
  Driver::AnalysisDriver *driver =
    this->fesystem_controller->getAnalysisDriver(Driver::NONLINEAR_ANALYSIS_DRIVER::num());
  // attach the discipline and driver to each other
  driver->clear();
  driver->attachAnalysisDiscipline(discipline);
  driver->attachSolution(this);
  // get the load cases and design variables to be solved for
  std::auto_ptr<std::vector<DesignData::DesignParameter*> >
    dv_vector(this->fesystem_controller->design_database->getParameters().release());
  // next, peform the analysis
  this->fesystem_controller->initPropertyCardsForGlobalParameters();
  // attach a nonlinear solver to the driver and perform the nonlinear analysis
  unsigned int nonlinear_solver_info_id = this->getSolverInfoID(Solver::NONLINEAR_SOLVER::num());
  const Solver::NonlinearSolverInfo& nonlinear_info =
    dynamic_cast<const Solver::NonlinearSolverInfo&>
    (this->fesystem_controller->analysis_case->getSolverInfo(nonlinear_solver_info_id));
  unsigned int linear_info_ID = nonlinear_info.getLinearSolverInfoID();
  const Solver::LinearSolverInfo& linear_info =
    dynamic_cast<const Solver::LinearSolverInfo&>
    (this->fesystem_controller->analysis_case->getSolverInfo(linear_info_ID));
  std::auto_ptr<Solver::FESystemSolverBase>
    solver(Solver::createNonlinearSolver(nonlinear_info, linear_info).release());
  solver->clear();
  driver->attachSolver(solver.get());
  driver->solveForLoadCases(this->load_case_IDs);
  solver->clear();
  // if there are any DVs, then attach the linear solver and perform
  // sensitivity analysis
  if (dv_vector->size() > 0)
    {
    linear_info_ID = this->getSolverInfoID(Solver::LINEAR_SOLVER::num());
    const Solver::LinearSolverInfo& sol_linear_info =
      dynamic_cast<const Solver::LinearSolverInfo&>
      (this->fesystem_controller->analysis_case->getSolverInfo(linear_info_ID));
    solver.reset(Solver::createLinearSolver(sol_linear_info).release());
    solver->clear();
    driver->attachSolver(solver.get());
    driver->solveForLoadCaseSensitivity(*(dv_vector.get()), this->load_case_IDs);
    solver->clear();
    }
    //  driver->postProcess();
  // now clear the initializations
  this->fesystem_controller->property_database->clearLocalParameterInitializationForAllCards();
  this->fesystem_controller->property_database->clearGlobalParameterInitializationForAllCards();
  // now clear the data structures before returning
  discipline->clear();
  driver->clear();
}
void Solution::SolutionBase::nonlinearTransientSolve (const unsigned int discipline_enum) [protected]
this method will solve for all the load cases and sensitivity analysis
Definition at line 422 of file SolutionBase.C.
References Driver::AnalysisDriver::attachAnalysisDiscipline(), Driver::AnalysisDriver::attachSolution(), Driver::AnalysisDriver::attachSolver(), Discipline::AnalysisDisciplineBase::clear(), Driver::AnalysisDriver::clear(), Solver::createLinearTransientSolver(), Solver::createNonlinearTransientSolver(), Discipline::DisciplineInfo::getAnalysisTypeEnumID(), Solver::NonlinearSolverInfo::getLinearSolverInfoID(), Solver::LinearTransientSolverInfo::getLinearSolverInfoID(), Solver::NonlinearTransientSolverInfo::getNonlinearSolverInfoID(), info, Driver::AnalysisDriver::solveForLoadCases(), and Driver::AnalysisDriver::solveForLoadCaseSensitivity().
{
  const Discipline::DisciplineInfo& info =
  this->fesystem_controller->analysis_case->getAnalysisDisciplineInfo
  (discipline_enum);
  // first, make sure that the discipline is for a linear analysis only
  Assert(info.getAnalysisTypeEnumID() == Discipline::NONLINEAR_ANALYSIS::num(),
         ExcInternalError());
  // next, get the discipline and drivers for this analysis
  Discipline::AnalysisDisciplineBase *discipline =
    this->fesystem_controller->getAnalysisDiscipline(discipline_enum);
  discipline->clear();
  discipline->attachSolution(this);
  Driver::AnalysisDriver *driver = this->fesystem_controller->getAnalysisDriver
    (Driver::NONLINEAR_TRANSIENT_ANALYSIS_DRIVER::num());
  // attach the discipline and driver to each other
  driver->clear();
  driver->attachAnalysisDiscipline(discipline);
  driver->attachSolution(this);
  // get the load cases and design variables to be solved for
  std::auto_ptr<std::vector<DesignData::DesignParameter*> >
    dv_vector(this->fesystem_controller->design_database->getParameters().release());
  // next, peform the analysis
  this->fesystem_controller->initPropertyCardsForGlobalParameters();
  // attach a nonlinear solver to the driver and perform the nonlinear analysis
  unsigned int transient_solver_info_id =
    this->getSolverInfoID(Solver::NONLINEAR_TRANSIENT_SOLVER::num());
  const Solver::NonlinearTransientSolverInfo& transient_info =
    dynamic_cast<const Solver::NonlinearTransientSolverInfo&>
    (this->fesystem_controller->analysis_case->getSolverInfo(transient_solver_info_id));
  unsigned int nonlinear_info_ID = transient_info.getNonlinearSolverInfoID();
  const Solver::NonlinearSolverInfo& nonlinear_info =
    dynamic_cast<const Solver::NonlinearSolverInfo&>
    (this->fesystem_controller->analysis_case->getSolverInfo(nonlinear_info_ID));
  unsigned int linear_info_ID = nonlinear_info.getLinearSolverInfoID();
  const Solver::LinearSolverInfo& linear_info =
    dynamic_cast<const Solver::LinearSolverInfo&>
    (this->fesystem_controller->analysis_case->getSolverInfo(linear_info_ID));
  std::auto_ptr<Solver::FESystemSolverBase>
    solver(Solver::createNonlinearTransientSolver(transient_info, nonlinear_info, linear_info).release());
  solver->clear();
  driver->attachSolver(solver.get());
  driver->solveForLoadCases(this->load_case_IDs);
  // if there are any DVs, then attach the linear solver and perform
  // sensitivity analysis
  if (dv_vector->size() > 0)
    {
      // get the linear solver info ID
      unsigned int linear_transient_info_ID =
      this->getSolverInfoID(Solver::LINEAR_TRANSIENT_SOLVER::num());
      // get the solver info
      const Solver::LinearTransientSolverInfo& linear_transient_info =
      dynamic_cast<const Solver::LinearTransientSolverInfo&>
      (this->fesystem_controller->analysis_case->getSolverInfo(linear_transient_info_ID));
      // get the linear solver info for this solver
      linear_info_ID = linear_transient_info.getLinearSolverInfoID();
      // get the linear solver info
      const Solver::LinearSolverInfo& linear_info2 =
      dynamic_cast<const Solver::LinearSolverInfo&>
      (this->fesystem_controller->analysis_case->getSolverInfo(linear_info_ID));
      // create the solver object
      solver.reset(Solver::createLinearTransientSolver(linear_transient_info,
                                                       linear_info2).release());
      solver->clear();
      // get a linear transient analysi driver.
      driver->attachSolver(solver.get());
      driver->solveForLoadCaseSensitivity(*(dv_vector.get()), this->load_case_IDs);
      solver->clear();
    }
  solver->clear();
  //  driver->postProcess();
  // now clear the initializations
  this->fesystem_controller->property_database->clearLocalParameterInitializationForAllCards();
  this->fesystem_controller->property_database->clearGlobalParameterInitializationForAllCards();
  // now clear the data structures before returning
  discipline->clear();
  driver->clear();
}
virtual std::istream& Solution::SolutionBase::readFromInputStream (std::istream & input) [pure virtual]
will read from the input stream
Implemented in Solution::NonlinearStaticStructuralSolution, Solution::AeroelasticitySolution, Solution::LinearStressSolution, Solution::LinearizedBucklingEigenSolution, Solution::StructuralVibrationEigenSolution, Solution::ThermalSolution, Solution::TransientStructuralSolution, and Solution::TransientThermalSolution.
virtual void Solution::SolutionBase::solve () [pure virtual]
this method will solve for all the load cases and sensitivity analysis
Implemented in Solution::NonlinearStaticStructuralSolution, Solution::AeroelasticitySolution, Solution::LinearizedBucklingEigenSolution, Solution::LinearStressSolution, Solution::StructuralVibrationEigenSolution, Solution::ThermalSolution, Solution::TransientStructuralSolution, and Solution::TransientThermalSolution.
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, Solution::SolutionBase & solution) [friend]
overloaded operator to read from input stream
Definition at line 104 of file SolutionBase.h.
    {
      solution.readFromInputStream(input);
      return input;
    }
Member Data Documentation
std::set<unsigned int> Solution::SolutionBase::discipline_enum_IDs [protected]
participating disciplines for this soltion
Definition at line 160 of file SolutionBase.h.
FESystem::FESystemController* Solution::SolutionBase::fesystem_controller [protected]
reference to the FESystemController class
Definition at line 145 of file SolutionBase.h.
unsigned int Solution::SolutionBase::ID [protected]
ID of this solution.
Definition at line 151 of file SolutionBase.h.
Referenced by getID().
std::vector<unsigned int> Solution::SolutionBase::load_case_IDs [protected]
vector of load case IDs that will be used in the analysis
Definition at line 157 of file SolutionBase.h.
const unsigned int Solution::SolutionBase::solution_enum_ID [protected]
enum ID of the solution
Definition at line 148 of file SolutionBase.h.
std::map<unsigned int, unsigned int> Solution::SolutionBase::solver_info_ID_map [protected]
solver info IDs per solver class
Definition at line 154 of file SolutionBase.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solutions/SolutionBase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solutions/SolutionBase.C