fesystem: MultilinearFunction Class Reference
MultilinearFunction Class Reference
#include <MultilinearFunction.h>
Public Member Functions
MultilinearFunction ()
MultilinearFunction (const std::map< double, double > &values_table)
virtual ~MultilinearFunction ()
destructor
const unsigned int getFunctionTypeID () const
const std::string getFunctionTypeName () const
returns the type of this function as a string
void reinit (const std::map< double, double > &values_table)
void getFunctionValue (const double &x, double &ordinate) const
void getFunctionDerivative (const double &x, double &ordinate) const
Protected Types
typedef std::map< double, double > ValueMap
local type definitions
Protected Member Functions
virtual std::istream & readFromInputStream (std::istream &input)
method to read from the function from the input stream
DeclException1 (ExcDuplicateAbcissa, double,<< "Duplicate abcissa value: "<< arg1<< " specified for the function")
Protected Attributes
bool if_initialized
if the method has been initialized or not
ValueMap value_table
table of abcissa-ordinate values for this function
Friends
std::istream & operator>> (std::istream &input, MultilinearFunction &function)
overloaded input stream operator
Detailed Description
this class defines a 1-D function that is an assortment of linear functions over adjacent intervals. This is used to define, for example, the dependence of a material property on a parameter, which is available as a table of ordinate values at discrete abssicas. This method asserts that only one function value be specified at a given abcissa
Definition at line 40 of file MultilinearFunction.h.
Member Typedef Documentation
typedef std::map<double, double> MultilinearFunction::ValueMap [protected]
local type definitions
Definition at line 102 of file MultilinearFunction.h.
Constructor & Destructor Documentation
MultilinearFunction::MultilinearFunction ()
constructor. This is the default constructor, and if this is used, then the function should be reinitialized with the data table before calling any of the methods to obtain the values from the function.
Definition at line 7 of file MultilinearFunction.C.
                                        :
if_initialized(false)
{
}
MultilinearFunction::MultilinearFunction (const std::map< double, double > & values_table)
constructor. This takes the table of values as input and initializes the data structures, so that methods to obtain the values of the function can be called directly after this
Definition at line 16 of file MultilinearFunction.C.
References reinit().
                                                                                  :
if_initialized(false)
{
  this->reinit(values_table);
}
MultilinearFunction::~MultilinearFunction () [virtual]
destructor
Definition at line 24 of file MultilinearFunction.C.
{
}
Member Function Documentation
MultilinearFunction::DeclException1 (ExcDuplicateAbcissa , double , << "Duplicate abcissa value: "<< arg1<< " specified for the function") [protected]
this exception will be thrown if two same abcissa values are specified in the input
void MultilinearFunction::getFunctionDerivative (const double & x, double & ordinate) const [inline, virtual]
Returns:
derivative of the function at the given abcissa
Parameters:
abcissa value at which the function should be evaluated
ordinate evaluated function value
Implements FunctionBase.
Definition at line 204 of file MultilinearFunction.h.
References FESystemNumbers::Epsilon, if_initialized, and value_table.
{
  Assert(this->if_initialized ,ExcNotInitialized());
  // find the iterator whose abcissa value is less than the given abcissa value
  MultilinearFunction::ValueMap::const_iterator it, end;
  MultilinearFunction::ValueMap::const_reverse_iterator rit;
  it = this->value_table.begin();
  end = this->value_table.end();
  rit = this->value_table.rbegin();
  double lower_x = 0.0 , upper_x = 0.0, lower_y = 0.0, upper_y = 0.0, delta_x = 0.0;
  if ( x <= it->first)
    {
    lower_x = it->first; lower_y = it->second;
    it++;
    upper_x = it->first; upper_y = it->second;
    }
  else if (x > rit->first)
    {
    upper_x = rit->first; upper_y = rit->second;
    rit++;
    lower_x = rit->first; lower_y = rit->second;
    }
  else
    {
    // now find the iterator whose value is greater than the given abcissa
    it++;
    for (; it != end; it++)
      {
      if (x <= it->first)
        // x lies between the previous and this iterator
        {
              upper_x = it->first; upper_y = it->second;
              it--;
              lower_x = it->first; lower_y = it->second;
          break;
        }
      }
    }
  // now calculate the ordinate value and return
  delta_x = upper_x-lower_x;
  Assert(fabs(delta_x) > FESystemNumbers::Epsilon,
         ExcDivideByZero());
  func_derivative = (upper_y-lower_y)/delta_x;
}
const unsigned int MultilinearFunction::getFunctionTypeID () const [inline, virtual]
returns the type of this function as the enumeration ID of the enumeration type of this object
Implements FunctionBase.
Definition at line 116 of file MultilinearFunction.h.
{
  return MULTILINEAR_FUNCTION::num();
}
const std::string MultilinearFunction::getFunctionTypeName () const [inline, virtual]
returns the type of this function as a string
Implements FunctionBase.
Definition at line 124 of file MultilinearFunction.h.
{
  return MULTILINEAR_FUNCTION::name();
}
void MultilinearFunction::getFunctionValue (const double & x, double & ordinate) const [inline, virtual]
method returns the value of the function at the specified point. If the value of abcissa in the input parameter is outside the bounds of where the function is defined, then linear extrapolation is used.
Implements FunctionBase.
Definition at line 147 of file MultilinearFunction.h.
References FESystemNumbers::Epsilon, if_initialized, and value_table.
{
  Assert (this->if_initialized ,ExcNotInitialized());
  // find the iterator whose abcissa value is less than the given abcissa value
  MultilinearFunction::ValueMap::const_iterator it, end;
  MultilinearFunction::ValueMap::const_reverse_iterator rit;
  it = this->value_table.begin();
  end = this->value_table.end();
  rit = this->value_table.rbegin();
  double lower_x = 0.0 , upper_x = 0.0, lower_y = 0.0, upper_y = 0.0, delta_x = 0.0;
  if ( x <= it->first)
    {
      lower_x = it->first; lower_y = it->second;
      it++;
      upper_x = it->first; upper_y = it->second;
    }
  else if (x > rit->first)
    {
      upper_x = rit->first; upper_y = rit->second;
      rit++;
      lower_x = rit->first; lower_y = rit->second;
    }
  else
    {
      // now find the iterator whose value is greater than the given abcissa
      it++;
      for (; it != end; it++)
        {
          if (x <= it->first)
            // x lies between the previous and this iterator
            {
              upper_x = it->first; upper_y = it->second;
              it--;
              lower_x = it->first; lower_y = it->second;
        break;
      }
        }
    }
  // now calculate the ordinate value and return
  delta_x = upper_x-lower_x;
  if (fabs(delta_x) <= FESystemNumbers::Epsilon)
    func_value = lower_y;
  else
    func_value = (lower_y + (upper_y-lower_y)/delta_x * (x-lower_x));
}
std::istream & MultilinearFunction::readFromInputStream (std::istream & input) [protected, virtual]
method to read from the function from the input stream
Implements FunctionBase.
Definition at line 31 of file MultilinearFunction.C.
References FunctionBase::ID, FESystemIOUtility::readFromInput(), and reinit().
{
  unsigned int n_values = 0;
  double value1 = 0.0, value2 = 0.0;
  FESystemIOUtility::readFromInput(input, MULTILINEAR_FUNCTION::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->ID);
  FESystemIOUtility::readFromInput(input, "N_PAIRS", n_values);
  MultilinearFunction::ValueMap value_map;
  bool insert_success = 0.0;
  for (unsigned int i=0; i < n_values; i++)
    {
    value1 = 0.0; value2 = 0.0;
    input >> value1; input >> value2;
    insert_success = value_map.insert(MultilinearFunction::ValueMap::value_type
                                      (value1, value2)).second;
    Assert(insert_success,
           MultilinearFunction::ExcDuplicateAbcissa(value1));
    }
  // now initialize this function using these value
  this->reinit(value_map);
  FESystemIOUtility::readFromInput(input, MULTILINEAR_FUNCTION::name());
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
void MultilinearFunction::reinit (const std::map< double, double > & values_table) [inline]
this method re-initializes this object to the new data set. The data should have atleast two data points
Definition at line 132 of file MultilinearFunction.h.
References if_initialized, and value_table.
Referenced by MultilinearFunction(), and readFromInputStream().
{
  unsigned int n_points = values_table.size();
  // perform a sanity check on the data.
  Assert(n_points > 1, ExcLowerRange(n_points, 2));
  this->value_table.clear();
  this->value_table = values_table;
  this->if_initialized = true;
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, MultilinearFunction & function) [friend]
overloaded input stream operator
Definition at line 71 of file MultilinearFunction.C.
{
  function.readFromInputStream(input);
  return input;
}
Member Data Documentation
bool MultilinearFunction::if_initialized [protected]
if the method has been initialized or not
Definition at line 99 of file MultilinearFunction.h.
Referenced by getFunctionDerivative(), getFunctionValue(), and reinit().
ValueMap MultilinearFunction::value_table [protected]
table of abcissa-ordinate values for this function
Definition at line 105 of file MultilinearFunction.h.
Referenced by getFunctionDerivative(), getFunctionValue(), and reinit().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Numerics/MultilinearFunction.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Numerics/MultilinearFunction.C