fesystem: Driver::AnalysisDriver Class Reference
Driver::AnalysisDriver Class Reference
#include <AnalysisDriver.h>
Public Member Functions
AnalysisDriver (const unsigned int ID, FESystem::FESystemController &controller, const unsigned int driver_type_id)
virtual ~AnalysisDriver ()
destructor
FESystem::FESystemController & getFESystemController ()
unsigned int getID () const
unsigned int getAnalysisDriverTypeEnumID ()
Discipline::AnalysisDisciplineBase & getAnalysisDiscipline ()
Solver::FESystemSolverBase & getSolver ()
void attachSolver (Solver::FESystemSolverBase *solver)
ataches the solver to this driver for analysis solutions
void attachSolution (Solution::SolutionBase *sol)
attaches a solution to this driver
NumericVector< double > & addVector (const std::string &vec_name)
Adds the vector vec_name. All vectors are inititialized to zero.
NumericVector< double > & getVector (const std::string &vec_name)
bool haveVector (const std::string &vec_name) const
SparseMatrix< double > & addMatrix (const std::string &mat_name)
Adds the additional matrix mat_name to this analysis.
SparseMatrix< double > & getMatrix (const std::string &mat_name) const
bool haveMatrix (const std::string &mat_name) const
unsigned int getCurrentLoadCase () const
returns the current load case number
const DesignData::DesignParameter & getCurrentDesignParameter () const
returns the current design variable
NumericVector< double > & getCurrentSolution (const unsigned int transient_order)
unsigned int getCurrentAnalysisKind () const
void attachAnalysisDiscipline (Discipline::AnalysisDisciplineBase *discipline)
attaches analysis discipline for solution
virtual void clear ()
clears the data structure
void solveForLoadCases (const std::vector< unsigned int > &load_cases)
this will loop over all load cases, and perform basic analysis for each
void solveForLoadCaseSensitivity (const std::vector< DesignData::DesignParameter * > &design_params, const std::vector< unsigned int > &load_cases)
virtual void postProcess (const std::vector< unsigned int > &load_cases, unsigned int disciplin_enum_ID)
this method performs the post process operations
Protected Member Functions
virtual void initialize ()=0
this method initializes itself before the solutions are started for the driver
void writeSolutionVectorToLog (FESystemDatabase::GenericDataInfoBase &data_info, const NumericVector< double > &sol, unsigned int disciplin_enum_ID)
writes a vector to the output stream
void writeComplexSolutionVectorToLog (FESystemDatabase::GenericDataInfoBase &data_info, const NumericVector< double > &real_sol, const NumericVector< double > &img_sol, unsigned int disciplin_enum_ID)
writes a vector to the output stream
void applyBoundaryConditionsToVectorForCurrentAnalysis (NumericVector< double > &vec, const bool if_apply_bc_vals, unsigned int disciplin_enum_ID)
void applyBoundaryConditionsToMatrixForCurrentAnalysis (SparseMatrix< double > &mat, double val, unsigned int disciplin_enum_ID)
void localizeSolution (const DofMap &dof_map, NumericVector< double > &source_vec, NumericVector< double > &localized_vec)
virtual void solveCurrentLoadCase ()=0
this method solves the system for the current load case and analysis kind
virtual void addMatricesAndVectors ()=0
adds matrices and vectors to this analysis driver
DeclException0 (ExcInitBeforeClear)
DeclException0 (ExcInvalidSolver)
this exception is thrown when an invalid solver is specified in the input
DeclException2 (ExcObjectNameDoesNotExist, std::string &, std::string &,<< arg1<< " Name: "<< arg2<< "does not exist.")
Protected Attributes
const unsigned int driver_ID
a number to identify this driver
FESystem::FESystemController & fesystem_controller
refernce to the FESystemController that owns this object
const unsigned int analysis_driver_type_enum_ID
analysis discipline for this driver
Solver::FESystemSolverBase * solver
solver that the analysis driver will use
Solution::SolutionBase * solution_base
solution for this analysis driver for the current analysis
unsigned int current_load_case
load case for the analysis
DesignData::DesignParameter * current_DV
FESystemUtility::AutoPtrVector
< NumericVector< double > > current_solution
unsigned int current_analysis_kind_enum_ID
analysis being performed
std::map< std::string,
NumericVector< double > * > vectors
std::map< std::string,
SparseMatrix< double > * > matrices
Some systems need an arbitrary number of matrices.
std::map< unsigned int,
Discipline::AnalysisDisciplineBase * > analysis_discipline_map
map of analysis disciplines used in this driver
Detailed Description
Definition at line 321 of file AnalysisDriver.h.
Constructor & Destructor Documentation
Driver::AnalysisDriver::AnalysisDriver (const unsigned int ID, FESystem::FESystemController & controller, const unsigned int driver_type_id)
consturctor
Parameters:
controller fesystem controller that owns this object
discipline discipline for this driver
Definition at line 30 of file AnalysisDriver.C.
                                                                         :
driver_ID(ID),
fesystem_controller(fesys_controller),
analysis_driver_type_enum_ID(driver_type_id),
solver(NULL),
solution_base(NULL),
current_load_case(0),
current_DV(NULL),
current_analysis_kind_enum_ID(FESystemNumbers::InvalidID)
{
}
Driver::AnalysisDriver::~AnalysisDriver () [virtual]
destructor
Definition at line 50 of file AnalysisDriver.C.
{
  this->clear();
}
Member Function Documentation
virtual void Driver::AnalysisDriver::addMatricesAndVectors () [protected, pure virtual]
adds matrices and vectors to this analysis driver
Implemented in Driver::NonlinearTransientAnalysisDriver, Driver::LinearTransientAnalysisDriver, Driver::NonLinearAnalysisDriver, Driver::RogerApproximationAeroelasticityDriver, Driver::EigenProblemAnalysisDriver, and Driver::LinearAnalysisDriver.
SparseMatrix< double > & Driver::AnalysisDriver::addMatrix (const std::string & mat_name)
Adds the additional matrix mat_name to this analysis.
Definition at line 288 of file AnalysisDriver.C.
{
  // Return the matrix if it is already there.
  if (this->haveMatrix(mat_name))
    return *(this->matrices[mat_name]);
  // Otherwise build the matrix and return it.
  SparseMatrix<double>* buf = SparseMatrix<double>::build().release();
  this->matrices.insert (std::make_pair (mat_name, buf));
  return *buf;
}
NumericVector< double > & Driver::AnalysisDriver::addVector (const std::string & vec_name)
Adds the vector vec_name. All vectors are inititialized to zero.
Definition at line 267 of file AnalysisDriver.C.
{
  // Return the vector if it is already there.
  if (this->haveVector(vec_name))
    {
      return *(this->vectors[vec_name]);
    }
  // Otherwise build the vector and return it.
  NumericVector<double>* buf = NumericVector<double>::build().release();
  this->vectors.insert (std::make_pair (vec_name, buf));
  return *buf;
}
void Driver::AnalysisDriver::applyBoundaryConditionsToMatrixForCurrentAnalysis (SparseMatrix< double > & mat, double val, unsigned int disciplin_enum_ID) [protected]
this applies the dirichlet boundary condition the matrix. The matrix columns and rows corresponding to the dofs with dirichlet BCs are zeroed, and the value specified in the second arguement is set at the diagonal of all those dofs.
Definition at line 482 of file AnalysisDriver.C.
References FESystemUtility::AutoPtrVector< T >::get(), LoadDatabase::getAllLoadCombinations(), and MeshDS::FEMeshData::getNodeFromForeignID().
{
  // make sure that this discipline exists in the map
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it, end;
  it = this->analysis_discipline_map.find(discipline_enum_ID);
  end = this->analysis_discipline_map.end();
  Assert(it != end, Driver::AnalysisDriver::ExcInitBeforeClear());
  LoadDatabase& load_database = *(this->fesystem_controller.load_database.get());
  const MeshDS::FEMeshData& mesh_data = it->second->getAnalysisMeshData();
  // get the boundary conditions
  std::auto_ptr<Loads::DirichletBoundaryConditionDataInfo>
  load_info(it->second->getBoundaryConditionLoadInfo().release());
  FESystemUtility::AutoPtrVector<Loads::DirichletBoundaryConditionCombination>
  bcond(load_database.getAllLoadCombinations
        <Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination>
        (*load_info).release());
  // to apply the boundary condition, get the global dof_number for each
  // constrained dof and use the penalty method to apply the boundary condition
  std::vector<Loads::DirichletBoundaryConditionCombination*>::const_iterator bc_it, bc_end;
  bc_it = bcond.get()->begin();
  bc_end = bcond.get()->end();
  std::vector<unsigned int> bc_rows;
  unsigned int constrained_node, constrained_dof, dof;
  for (; bc_it != bc_end ; bc_it++)
    {
      constrained_node =  (**bc_it).getNodeID();
      constrained_dof = (**bc_it).getDofNumber();
      dof =
      (mesh_data.getNodeFromForeignID(constrained_node))->dof_number(0,(constrained_dof-1),0);
      //matrix.add(dof,dof,penalty);
      bc_rows.push_back(dof);
    }
  mat.zero_rows(bc_rows, value);
}
void Driver::AnalysisDriver::applyBoundaryConditionsToVectorForCurrentAnalysis (NumericVector< double > & vec, const bool if_apply_bc_vals, unsigned int disciplin_enum_ID) [protected]
apply dirichlet boundary condition to vector. The second arguement specifies if the value of the BC should be applied to the DOF or if it should be zeroed. If true, the value will be applied.
Definition at line 428 of file AnalysisDriver.C.
References FESystemUtility::AutoPtrVector< T >::get(), LoadDatabase::getAllLoadCombinations(), and MeshDS::FEMeshData::getNodeFromForeignID().
{
  // make sure that this discipline exists in the map
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it, end;
  it = this->analysis_discipline_map.find(discipline_enum_ID);
  end = this->analysis_discipline_map.end();
  Assert(it != end, Driver::AnalysisDriver::ExcInitBeforeClear());
  LoadDatabase& load_database = *(this->fesystem_controller.load_database.get());
  const MeshDS::FEMeshData& mesh_data = it->second->getAnalysisMeshData();
  // get the boundary conditions
  std::auto_ptr<Loads::DirichletBoundaryConditionDataInfo>
  load_info(it->second->getBoundaryConditionLoadInfo().release());
  FESystemUtility::AutoPtrVector<Loads::DirichletBoundaryConditionCombination>
  bcond(load_database.getAllLoadCombinations
        <Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination>
        (*load_info).release());
  // to apply the boundary condition, get the global dof_number for each
  // constrained dof and use the penalty method to apply the boundary condition
  std::vector<Loads::DirichletBoundaryConditionCombination*>::const_iterator bc_it, bc_end;
  bc_it = bcond.get()->begin();
  bc_end = bcond.get()->end();
  unsigned int constrained_node, constrained_dof, dof;
  double value = 0.0;
  for (; bc_it != bc_end ; bc_it++)
    {
      constrained_node =  (**bc_it).getNodeID();
      constrained_dof = (**bc_it).getDofNumber();
      dof =
      (mesh_data.getNodeFromForeignID(constrained_node))->dof_number(0,constrained_dof-1,0);
      if (if_apply_bc_vals)
        {
          value =  (**bc_it).getValue();
          vec.set(dof, value);
        }
      else
        vec.set(dof, 0.0);
    }
}
void Driver::AnalysisDriver::attachAnalysisDiscipline (Discipline::AnalysisDisciplineBase * discipline)
attaches analysis discipline for solution
Definition at line 131 of file AnalysisDriver.C.
References Discipline::AnalysisDisciplineBase::attachAnalysisDriver(), and Discipline::AnalysisDisciplineBase::getDisciplineEnumID().
Referenced by Solution::AeroelasticitySolution::aeroelasticSolve(), Solution::SolutionBase::eigenSolve(), Solution::SolutionBase::linearSolve(), Solution::SolutionBase::linearTransientSolve(), Solution::SolutionBase::nonlinearSolve(), and Solution::SolutionBase::nonlinearTransientSolve().
{
  Assert(discipline != NULL, ExcEmptyObject());
  // copy the pointer, but make sure that a discipline has not already been attached
  // for this
  unsigned int enum_ID = discipline->getDisciplineEnumID();
  Assert(this->analysis_discipline_map.count(enum_ID) == 0,
         Driver::AnalysisDriver::ExcInitBeforeClear());
  this->analysis_discipline_map.insert(std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::
                                       value_type(enum_ID, discipline));
  // attach itself to the discipline
  discipline->attachAnalysisDriver(this);
}
void Driver::AnalysisDriver::attachSolution (Solution::SolutionBase * sol) [inline]
attaches a solution to this driver
Definition at line 524 of file AnalysisDriver.h.
References solution_base.
Referenced by Solution::AeroelasticitySolution::aeroelasticSolve(), Solution::SolutionBase::eigenSolve(), Solution::SolutionBase::linearSolve(), Solution::SolutionBase::linearTransientSolve(), Solution::SolutionBase::nonlinearSolve(), and Solution::SolutionBase::nonlinearTransientSolve().
{
  Assert(sol != NULL, ExcEmptyObject());
  this->solution_base = sol;
}
void Driver::AnalysisDriver::attachSolver (Solver::FESystemSolverBase * solver)
ataches the solver to this driver for analysis solutions
Definition at line 119 of file AnalysisDriver.C.
References Solver::FESystemSolverBase::attachAnalysisDriver().
Referenced by Solution::AeroelasticitySolution::aeroelasticSolve(), Solution::SolutionBase::eigenSolve(), Solution::SolutionBase::linearSolve(), Solution::SolutionBase::linearTransientSolve(), Solution::SolutionBase::nonlinearSolve(), and Solution::SolutionBase::nonlinearTransientSolve().
{
  Assert(solver_base != NULL, ExcInternalError());
  this->solver = solver_base;
  this->solver->attachAnalysisDriver(this);
}
void Driver::AnalysisDriver::clear () [virtual]
clears the data structure
Reimplemented in Driver::TransientAnalysisDriver, and Driver::NonLinearAnalysisDriver.
Definition at line 61 of file AnalysisDriver.C.
References FESystemNumbers::InvalidID.
Referenced by Solution::AeroelasticitySolution::aeroelasticSolve(), FEInterpolationElem::calculate_F(), Driver::NonLinearAnalysisDriver::clear(), Driver::TransientAnalysisDriver::clear(), Solution::SolutionBase::eigenSolve(), Solution::SolutionBase::linearSolve(), Solution::SolutionBase::linearTransientSolve(), Solution::SolutionBase::nonlinearSolve(), and Solution::SolutionBase::nonlinearTransientSolve().
{
  // this will need clearing all the data structures:
  this->solver = NULL;
  this->analysis_discipline_map.clear();
  this->solution_base = NULL;
  this->current_load_case = FESystemNumbers::InvalidID;
  this->current_DV = NULL;
  this->current_solution.clear();
  this->current_analysis_kind_enum_ID = FESystemNumbers::InvalidID;
  // -- delete the vectors
  {
    // get the iterators
    std::map<std::string, NumericVector<double>* >::iterator pos = this->vectors.begin();
    std::map<std::string, NumericVector<double>* >::const_iterator end = this->vectors.end();
    for (; pos != end; ++pos)
      {
        // if the pointer is not null, clear the data, and delete it
        if (pos->second != NULL)
          {
            pos->second->clear();
            delete pos->second;
            pos->second = NULL;
          }
      }
  }
  // delete matrices
  {
    // get the iterators
    std::map<std::string, SparseMatrix<double>* >::iterator pos = this->matrices.begin();
    std::map<std::string, SparseMatrix<double>* >::const_iterator end = this->matrices.end();
    for (; pos != end; ++pos)
      {
        // if the pointer is not already null, clear the data, and delete it
        if (pos->second != NULL)
          {
            pos->second->clear ();
            delete pos->second;
            pos->second = NULL;
          }
      }
  }
}
Driver::AnalysisDriver::DeclException0 (ExcInitBeforeClear) [protected]
this exception is thrown if an analysis discipline is attached without clearing the object.
Driver::AnalysisDriver::DeclException0 (ExcInvalidSolver) [protected]
this exception is thrown when an invalid solver is specified in the input
Driver::AnalysisDriver::DeclException2 (ExcObjectNameDoesNotExist , std::string & , std::string & , << arg1<< " Name: "<< arg2<< "does not exist.") [protected]
Discipline::AnalysisDisciplineBase& Driver::AnalysisDriver::getAnalysisDiscipline () [inline]
Returns:
the discipline
unsigned int Driver::AnalysisDriver::getAnalysisDriverTypeEnumID () [inline]
Returns:
the analysis driver type enum ID
Definition at line 552 of file AnalysisDriver.h.
{
  return this->analysis_driver_type_enum_ID;
}
unsigned int Driver::AnalysisDriver::getCurrentAnalysisKind () const [inline]
Returns:
the kind of analysis being performed
Definition at line 657 of file AnalysisDriver.h.
{
  return this->current_analysis_kind_enum_ID;
}
const DesignData::DesignParameter & Driver::AnalysisDriver::getCurrentDesignParameter () const [inline]
returns the current design variable
Definition at line 647 of file AnalysisDriver.h.
Referenced by RadiationCavityAnalysis::calculateA_Matrix(), RadiationCavityAnalysis::calculateB_Matrix(), RadiationCavityAnalysis::getDataInfoForQty(), and FEInterpolationAnalysis::getStringNameForQty().
{
  return *(this->current_DV);
}
unsigned int Driver::AnalysisDriver::getCurrentLoadCase () const [inline]
returns the current load case number
Definition at line 637 of file AnalysisDriver.h.
Referenced by FEInterpolationAnalysis::calculateF(), and RadiationCavityAnalysis::getDataInfoForQty().
{
  return this->current_load_case;
}
NumericVector< double > & Driver::AnalysisDriver::getCurrentSolution (const unsigned int transient_order)
Returns:
the current solution vector for the system
Definition at line 153 of file AnalysisDriver.C.
{
  Assert(transient_order < this->current_solution.size(), ExcInternalError());
  Assert(this->current_solution[transient_order] != NULL, ExcEmptyObject());
  return *(this->current_solution[transient_order]);
}
FESystem::FESystemController & Driver::AnalysisDriver::getFESystemController () [inline]
Returns:
the FESystemController class that owns this object
Definition at line 534 of file AnalysisDriver.h.
Referenced by Solver::EulerLinearTransientSolver::solve(), Solver::NewmarkLinearTransientSolver::solve(), and Solver::NewmarkNonlinearTransientSolver::solve().
{
  return this->fesystem_controller;
}
unsigned int Driver::AnalysisDriver::getID () const [inline]
Returns:
the ID of this driver
Definition at line 543 of file AnalysisDriver.h.
{
  return this->driver_ID;
}
SparseMatrix< double > & Driver::AnalysisDriver::getMatrix (const std::string & mat_name) const [inline]
Returns:
a const reference to this system's matrix named mat_name.
Definition at line 611 of file AnalysisDriver.h.
Referenced by FEInterpolationAnalysis::initMatricesAndVectors().
{
  // Make sure the matrix exists
  std::map<std::string, SparseMatrix<double>* >::const_iterator pos = this->matrices.find (mat_name);
  Assert(pos != this->matrices.end(),
         Driver::AnalysisDriver::ExcObjectNameDoesNotExist("Matrix", mat_name));
  return *(pos->second);
}
Solver::FESystemSolverBase & Driver::AnalysisDriver::getSolver () [inline]
Returns:
the solver
Definition at line 574 of file AnalysisDriver.h.
{
  Assert(this->solver != NULL,
         ExcEmptyObject());
  return *(this->solver);
}
NumericVector< double > & Driver::AnalysisDriver::getVector (const std::string & vec_name) [inline]
Returns:
a writeable reference to the vector named vec_name.
Definition at line 584 of file AnalysisDriver.h.
Referenced by FEInterpolation::getInterpolatedValues(), and FEInterpolationAnalysis::initMatricesAndVectors().
{
  // Make sure the vector exists
  std::map<std::string, NumericVector<double>* >::iterator pos = this->vectors.find(vec_name);
  Assert(pos != this->vectors.end(),
         Driver::AnalysisDriver::ExcObjectNameDoesNotExist("Vector", vec_name));
  return *(pos->second);
}
bool Driver::AnalysisDriver::haveMatrix (const std::string & mat_name) const [inline]
Returns:
true if this AnalysisDriver has a matrix associated with the given name, false otherwise.
Definition at line 627 of file AnalysisDriver.h.
{
  return (this->matrices.count(mat_name));
}
bool Driver::AnalysisDriver::haveVector (const std::string & vec_name) const [inline]
Returns:
true if this AnalysisDriver has a vector associated with the given name, false otherwise.
Definition at line 601 of file AnalysisDriver.h.
{
  return (this->vectors.count(vec_name));
}
virtual void Driver::AnalysisDriver::initialize () [protected, pure virtual]
this method initializes itself before the solutions are started for the driver
Implemented in Driver::NonlinearTransientAnalysisDriver, Driver::LinearTransientAnalysisDriver, Driver::NonLinearAnalysisDriver, Driver::RogerApproximationAeroelasticityDriver, Driver::EigenProblemAnalysisDriver, and Driver::LinearAnalysisDriver.
void Driver::AnalysisDriver::localizeSolution (const DofMap & dof_map, NumericVector< double > & source_vec, NumericVector< double > & localized_vec) [protected]
localizes the solution vector. The first arguement is the vector from which the solution will be localized, and the second arguement will contain the localized solution
Definition at line 532 of file AnalysisDriver.C.
{
  // make sure that the source vec and the localized vec have the correct dimensions
  Assert(source_vec.size() == dof_map.n_dofs(), ExcInternalError());
  Assert(source_vec.size() == localized_vec.size(), ExcInternalError());
  // get the send list from the dofmap
  const std::vector<unsigned int>& send_list = dof_map.get_send_list();
  source_vec.close();
  localized_vec.zero();
  localized_vec.close();
  source_vec.localize(localized_vec, send_list);
}
void Driver::AnalysisDriver::postProcess (const std::vector< unsigned int > & load_cases, unsigned int disciplin_enum_ID) [virtual]
this method performs the post process operations
Definition at line 163 of file AnalysisDriver.C.
{
  // make sure that this discipline exists in the map
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator it, end;
  it = this->analysis_discipline_map.find(disciplin_enum_ID);
  end = this->analysis_discipline_map.end();
  Assert(it != end, Driver::AnalysisDriver::ExcInitBeforeClear());
  // ask the analysis discipline to calculate and store the post
  // process quantity
  it->second->calculatePostProcessQty(load_cases);
}
virtual void Driver::AnalysisDriver::solveCurrentLoadCase () [protected, pure virtual]
this method solves the system for the current load case and analysis kind
Implemented in Driver::NonlinearTransientAnalysisDriver, Driver::LinearTransientAnalysisDriver, Driver::NonLinearAnalysisDriver, Driver::RogerApproximationAeroelasticityDriver, Driver::EigenProblemAnalysisDriver, and Driver::LinearAnalysisDriver.
void Driver::AnalysisDriver::solveForLoadCases (const std::vector< unsigned int > & load_cases)
this will loop over all load cases, and perform basic analysis for each
Definition at line 180 of file AnalysisDriver.C.
References FESystemNumbers::InvalidID.
Referenced by Solution::AeroelasticitySolution::aeroelasticSolve(), Solution::SolutionBase::eigenSolve(), Solution::SolutionBase::linearSolve(), Solution::SolutionBase::linearTransientSolve(), Solution::SolutionBase::nonlinearSolve(), and Solution::SolutionBase::nonlinearTransientSolve().
{
  // make sure that the solver has been set
  Assert(this->solver != NULL, ExcInternalError());
  this->initialize();
  // set the analysis type
  this->current_analysis_kind_enum_ID = Driver::ANALYSIS::num();
  std::vector<unsigned int>::const_iterator load_case_it = load_cases.begin();
  std::vector<unsigned int>::const_iterator load_case_end = load_cases.end();
  // iterate over each load case, and ask solver to solve for it
  for (; load_case_it != load_case_end; load_case_it++)
    {
      // set current load case
      this->current_load_case = *load_case_it;
      // tell solver to solve for the load case
      this->solveCurrentLoadCase();
    }
  // now that the solution has been completed, reset the local data
  this->current_load_case = FESystemNumbers::InvalidID;
  this->current_solution.clear();
  this->current_analysis_kind_enum_ID = FESystemNumbers::InvalidID;
}
void Driver::AnalysisDriver::solveForLoadCaseSensitivity (const std::vector< DesignData::DesignParameter * > & design_params, const std::vector< unsigned int > & load_cases)
this will loop over all load cases, and perform sensitivity analysis for each
Definition at line 215 of file AnalysisDriver.C.
References FESystemNumbers::InvalidID.
Referenced by Solution::AeroelasticitySolution::aeroelasticSolve(), Solution::SolutionBase::eigenSolve(), Solution::SolutionBase::linearSolve(), Solution::SolutionBase::linearTransientSolve(), Solution::SolutionBase::nonlinearSolve(), and Solution::SolutionBase::nonlinearTransientSolve().
{
  // if there are no DVs, just return
  if (design_params.size() == 0)
    return;
  // make sure that the solver has been set
  Assert(this->solver != NULL, ExcInternalError());
  this->initialize();
  // set the analysis kind to sensitivity analysis
  this->current_analysis_kind_enum_ID = Driver::SENSITIVITY_ANALYSIS::num();
  std::vector<unsigned int>::const_iterator load_case_it = load_cases.begin();
  std::vector<unsigned int>::const_iterator load_case_end = load_cases.end();
  std::vector<DesignData::DesignParameter*>::const_iterator dv_it, dv_end;
  dv_end = design_params.end();
  // iterate over each load case, and ask solver to solve for it
  for (; load_case_it != load_case_end; load_case_it++)
    {
      dv_it = design_params.begin();
      for (; dv_it != dv_end; dv_it++)
        {
          // set current load case
          this->current_load_case = *load_case_it;
          this->current_DV = *dv_it;
          // solve for this sensitivity analysis
          this->solveCurrentLoadCase();
        }
    }
  // now that the solution has been completed, reset the local data
  this->current_load_case = FESystemNumbers::InvalidID;
  this->current_solution.clear();
  this->current_analysis_kind_enum_ID = FESystemNumbers::InvalidID;
  this->current_DV = NULL;
}
void Driver::AnalysisDriver::writeComplexSolutionVectorToLog (FESystemDatabase::GenericDataInfoBase & data_info, const NumericVector< double > & real_sol, const NumericVector< double > & img_sol, unsigned int disciplin_enum_ID) [protected]
writes a vector to the output stream
Definition at line 366 of file AnalysisDriver.C.
References MeshDS::FEMeshData::getInternalIDFromNode(), and FESystem::local_processor.
{
  // make sure that this discipline exists in the map
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator discipline_it, discipline_end;
  discipline_it = this->analysis_discipline_map.find(discipline_enum_ID);
  discipline_end = this->analysis_discipline_map.end();
  Assert(discipline_it != discipline_end, Driver::AnalysisDriver::ExcInitBeforeClear());
  const MeshDS::FEMesh& mesh = discipline_it->second->getAnalysisMesh();
  const MeshDS::FEMeshData& mesh_data = discipline_it->second->getAnalysisMeshData();
  if (FESystem::local_processor == 0)
    this->fesystem_controller.log_file->write2(data_info);
  std::vector<double> localized_vector_real;
  real_sol.localize_to_one(localized_vector_real, 0);
  std::vector<double> localized_vector_img;
  img_sol.localize_to_one(localized_vector_img, 0);
  if (FESystem::local_processor == 0)
    {
      // now write the dofs to the file
      MeshBase::const_node_iterator           node  = mesh.nodes_begin();
      const MeshBase::const_node_iterator end_node  = mesh.nodes_end();
      unsigned int node_id = 0, dof_number=0;
      unsigned int n_vars = discipline_it->second->getNVars();
      std::ostringstream values;
      for ( ; node != end_node ; ++node)
        {
          node_id = mesh_data.getInternalIDFromNode(*node);
          values << node_id << "  " ;
          for (unsigned int i=0;i<3; i++)
            values << std::setprecision(16) << std::showpoint << (**node)(i) << "  ";
          for (unsigned int var_it =0; var_it < n_vars; var_it++)
            {
              dof_number = (*node)->dof_number(0,var_it,0);
              values << std::showpoint
              << localized_vector_real[dof_number] << "  + i "
              << localized_vector_img[dof_number] ;
            }
          values << std::endl;
        }
      const std::string& val_str = values.str();
      this->fesystem_controller.log_file->write(val_str);
    }
}
void Driver::AnalysisDriver::writeSolutionVectorToLog (FESystemDatabase::GenericDataInfoBase & data_info, const NumericVector< double > & sol, unsigned int disciplin_enum_ID) [protected]
writes a vector to the output stream
Definition at line 310 of file AnalysisDriver.C.
References MeshDS::FEMeshData::getInternalIDFromNode(), and FESystem::local_processor.
{
  // make sure that this discipline exists in the map
  std::map<unsigned int, Discipline::AnalysisDisciplineBase*>::iterator discipline_it, discipline_end;
  discipline_it = this->analysis_discipline_map.find(discipline_enum_ID);
  discipline_end = this->analysis_discipline_map.end();
  Assert(discipline_it != discipline_end, Driver::AnalysisDriver::ExcInitBeforeClear());
  const MeshDS::FEMesh& mesh = discipline_it->second->getAnalysisMesh();
  const MeshDS::FEMeshData& mesh_data = discipline_it->second->getAnalysisMeshData();
  if (FESystem::local_processor == 0)
    this->fesystem_controller.log_file->write2(data_info);
  std::vector<double> localized_vector;
  sol.localize_to_one(localized_vector, 0);
  if (FESystem::local_processor == 0)
    {
      // now write the dofs to the file
      MeshBase::const_node_iterator           node  = mesh.nodes_begin();
      const MeshBase::const_node_iterator end_node  = mesh.nodes_end();
      unsigned int node_id = 0, dof_number=0;
      unsigned int n_vars = discipline_it->second->getNVars();
      std::ostringstream values;
      for ( ; node != end_node ; ++node)
        {
          node_id = mesh_data.getInternalIDFromNode(*node);
          values << node_id << "  " ;
          for (unsigned int i=0;i<3; i++)
            values << std::setprecision(16) << std::showpoint << (**node)(i) << "  ";
          for (unsigned int var_it =0; var_it < n_vars; var_it++)
            {
              dof_number = (*node)->dof_number(0,var_it,0);
              values << std::showpoint << localized_vector[dof_number] << "  ";
            }
          values << std::endl;
        }
      const std::string& val_str = values.str();
      this->fesystem_controller.log_file->write(val_str);
    }
}
Member Data Documentation
std::map<unsigned int, Discipline::AnalysisDisciplineBase*> Driver::AnalysisDriver::analysis_discipline_map [protected]
map of analysis disciplines used in this driver
Definition at line 515 of file AnalysisDriver.h.
const unsigned int Driver::AnalysisDriver::analysis_driver_type_enum_ID [protected]
analysis discipline for this driver
Definition at line 482 of file AnalysisDriver.h.
unsigned int Driver::AnalysisDriver::current_analysis_kind_enum_ID [protected]
analysis being performed
Definition at line 503 of file AnalysisDriver.h.
DesignData::DesignParameter* Driver::AnalysisDriver::current_DV [protected]
design variable variable for which sensitivity analysis is being performed
Definition at line 495 of file AnalysisDriver.h.
unsigned int Driver::AnalysisDriver::current_load_case [protected]
load case for the analysis
Definition at line 491 of file AnalysisDriver.h.
FESystemUtility::AutoPtrVector<NumericVector<double> > Driver::AnalysisDriver::current_solution [protected]
this stores the current iterate for different (nonlinear/transient) analysis. for transient solutions, the time derivative of the solution is stored in the location in the vector equal to its derivative order.
Definition at line 500 of file AnalysisDriver.h.
const unsigned int Driver::AnalysisDriver::driver_ID [protected]
a number to identify this driver
Definition at line 476 of file AnalysisDriver.h.
FESystem::FESystemController& Driver::AnalysisDriver::fesystem_controller [protected]
refernce to the FESystemController that owns this object
Definition at line 479 of file AnalysisDriver.h.
std::map<std::string, SparseMatrix<double>* > Driver::AnalysisDriver::matrices [protected]
Some systems need an arbitrary number of matrices.
Definition at line 512 of file AnalysisDriver.h.
Solution::SolutionBase* Driver::AnalysisDriver::solution_base [protected]
solution for this analysis driver for the current analysis
Definition at line 488 of file AnalysisDriver.h.
Referenced by attachSolution().
Solver::FESystemSolverBase* Driver::AnalysisDriver::solver [protected]
solver that the analysis driver will use
Definition at line 485 of file AnalysisDriver.h.
std::map<std::string, NumericVector<double>* > Driver::AnalysisDriver::vectors [protected]
Some systems need an arbitrary number of vectors. This map allows names to be associated with arbitrary vectors. All the vectors in this map will be distributed in the same way as the solution vector.
Definition at line 509 of file AnalysisDriver.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/AnalysisDriver/AnalysisDriver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/AnalysisDriver/AnalysisDriver.C