fesystem: TimeIndependentLoadCase Class Reference
TimeIndependentLoadCase Class Reference
#include <LoadCase.h>
Public Member Functions
TimeIndependentLoadCase (LoadDatabase &database)
constructor
virtual ~TimeIndependentLoadCase ()
destructor
virtual void clear ()
clears the data structures for this object
virtual unsigned int getLoadCaseKindEnumID () const
virtual void getLoadFactorLoadSetPair (const Loads::LoadDataInfoBase &load_info, std::vector< std::pair< unsigned int, double > > &load_pair) const
fills the vector with the load set ID and its load factor
virtual std::istream & readFromInputStream (std::istream &)
this method reads the load case data from the input stream
void addLoadSetID (const unsigned int load_enum_ID, const unsigned int load_set_ID, const double load_factor, const unsigned int DV_ID)
this will add a loadset with its reference tag.
Protected Member Functions
void getLoadPair (const unsigned int load_enum_ID, const unsigned int DV_ID, std::vector< std::pair< unsigned int, double > > &load_pair) const
fills the vector with the load set ID, load factor value pair
Protected Attributes
LoadEnumIDToDVLoadFactorValueMap load_map
Detailed Description
Definition at line 117 of file LoadCase.h.
Constructor & Destructor Documentation
TimeIndependentLoadCase::TimeIndependentLoadCase (LoadDatabase & database)
constructor
Definition at line 40 of file LoadCase.C.
                                                                      :
LoadCaseBase(database)
{
}
TimeIndependentLoadCase::~TimeIndependentLoadCase () [virtual]
destructor
Definition at line 47 of file LoadCase.C.
References clear().
{
  this->clear();
  LoadCaseBase::clear();
}
Member Function Documentation
void TimeIndependentLoadCase::addLoadSetID (const unsigned int load_enum_ID, const unsigned int load_set_ID, const double load_factor, const unsigned int DV_ID)
this will add a loadset with its reference tag.
Definition at line 72 of file LoadCase.C.
References load_map.
Referenced by readFromInputStream().
{
  // get the iterator for the specified time instant
  LoadEnumIDToDVLoadFactorValueMap::iterator load_enum_it, load_enum_end;
  load_enum_it = this->load_map.find(load_enum_ID);
  load_enum_end = this->load_map.end();
  if(load_enum_it == load_enum_end)
    load_enum_it = this->load_map.insert
      (LoadEnumIDToDVLoadFactorValueMap::value_type(load_enum_ID, DVToLoadFactorValuePairMap::map())).first;
  // get the iterators for the load enum from this
  DVToLoadFactorValuePairMap::iterator DV_it, DV_end;
  DV_it = load_enum_it->second.find(DV_ID);
  DV_end = load_enum_it->second.end();
  AssertThrow(DV_it == DV_end,  FESystemExceptions::ExcDuplicateID("Design Variable for Load Set",
                                                                   DV_ID));
  load_enum_it->second.insert
    (DVToLoadFactorValuePairMap::value_type(DV_ID, std::pair<unsigned int, double>
                                            (load_set_ID, load_factor)));
}
void TimeIndependentLoadCase::clear () [virtual]
clears the data structures for this object
Reimplemented from LoadCaseBase.
Definition at line 56 of file LoadCase.C.
References load_map.
Referenced by ~TimeIndependentLoadCase().
{
  this->load_map.clear();
  LoadCaseBase::clear();
}
unsigned int TimeIndependentLoadCase::getLoadCaseKindEnumID () const [virtual]
Returns:
the load case kind
Implements LoadCaseBase.
Definition at line 64 of file LoadCase.C.
{
  return STATIC_LOAD_CASE::num();
}
void TimeIndependentLoadCase::getLoadFactorLoadSetPair (const Loads::LoadDataInfoBase & load_info, std::vector< std::pair< unsigned int, double > > & load_pair) const [virtual]
fills the vector with the load set ID and its load factor
Implements LoadCaseBase.
Definition at line 103 of file LoadCase.C.
References Loads::LoadDataInfoBase::getDVID(), Loads::LoadDataInfoBase::getLoadNameEnumID(), Loads::LoadDataInfoBase::ifSensitivity(), Loads::LoadDataInfoBase::ifTimeDependent(), and FESystemNumbers::InvalidID.
{
  Assert(!load_info.ifTimeDependent(), ExcInternalError());
  load_pair.clear();
  unsigned int DV_ID = FESystemNumbers::InvalidID;
  if (load_info.ifSensitivity())
    DV_ID = load_info.getDVID();
  this->getLoadPair(load_info.getLoadNameEnumID(), DV_ID,
                    load_pair);
}
void TimeIndependentLoadCase::getLoadPair (const unsigned int load_enum_ID, const unsigned int DV_ID, std::vector< std::pair< unsigned int, double > > & load_pair) const [protected]
fills the vector with the load set ID, load factor value pair
Definition at line 122 of file LoadCase.C.
{
  load_pair.clear();
  // find where the load exists: in the time loads, or the load factor loads
  // first check in the load factor based load
  // get the iterator for the specified time instant
  LoadEnumIDToDVLoadFactorValueMap::const_iterator load_enum_it, load_enum_end;
  load_enum_it = this->load_map.find(load_enum_ID);
  load_enum_end = this->load_map.end();
  if (load_enum_it != load_enum_end) // implies that the load exists in this map
    {
    // check for the DV
    DVToLoadFactorValuePairMap::const_iterator DV_it, DV_end;
    DV_it = load_enum_it->second.find(DV_ID);
    DV_end = load_enum_it->second.end();
    if (DV_it == DV_end)
      return;
    // If the code gets here, then a valid iterator has been found
    load_pair.push_back(std::pair<unsigned int, double>(DV_it->second.first,
                                                        DV_it->second.second));
    }
}
std::istream & TimeIndependentLoadCase::readFromInputStream (std::istream & input) [virtual]
this method reads the load case data from the input stream
Implements LoadCaseBase.
Definition at line 154 of file LoadCase.C.
References addLoadSetID(), FESystemNumbers::InvalidID, LoadCaseBase::load_case_ID, and FESystemIOUtility::readFromInput().
{
  std::string tag;
  unsigned int  n_load_sets=0, n_DV=0, load_set_ID;
  double load_factor = 0.0;
  // the input should begin with BEGIN
  FESystemIOUtility::readFromInput(input, STATIC_LOAD_CASE::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  // read in the load case ID
  FESystemIOUtility::readFromInput(input, "ID", this->load_case_ID);
  // read in the number of time instants and the number of loadsets defined for
  // each time instant. The same loads will have to be redefined at each time instant
  FESystemIOUtility::readFromInput(input, "N_DESIGN_VARIABLES", n_DV);
  // for each time instant, read in the time value, the loadset tags and IDs
  unsigned int load_enum_ID = 0, DV_ID =FESystemNumbers::InvalidID;
  for (unsigned int dv_it= 0; dv_it <= n_DV; dv_it++)
    {
    // apart from the first data set, all other will be for a specific design variable
    if (dv_it > 0)
      {
        FESystemIOUtility::readFromInput(input, "DESIGN_VARIABLE", DV_ID);
        // no given IDs should equal the invalid ID of FESystem
        AssertThrow(DV_ID != FESystemNumbers::InvalidID, ExcInternalError());
      }
      FESystemIOUtility::readFromInput(input, "N_LOAD_SETS", n_load_sets);
      for (unsigned int load_set_incr=0; load_set_incr < n_load_sets; load_set_incr++)
        {
        input >> tag; //load set name
        load_enum_ID = LoadNameEnum::enumID(tag);
        input >> load_factor;
        input >> load_set_ID; // load set ID
        this->addLoadSetID(load_enum_ID, load_set_ID, load_factor, DV_ID);
        tag.clear();
        }
    }
  // the input should end with END
  FESystemIOUtility::readFromInput(input, STATIC_LOAD_CASE::name());
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Member Data Documentation
LoadEnumIDToDVLoadFactorValueMap TimeIndependentLoadCase::load_map [protected]
this will store the LoadSetIDs for each time instant. At each time instant, multiple kinds of loads can exist. The LoadSetIDMap stores these as a tag to LoadSetID map
Definition at line 161 of file LoadCase.h.
Referenced by addLoadSetID(), and clear().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCase.C