fesystem: FESystemDatabase::TimeDependentEigenDataInfo Class Reference
FESystemDatabase::TimeDependentEigenDataInfo Class Reference
this defines a time independent eigen quantity
#include <DataInfo.h>
Public Member Functions
TimeDependentEigenDataInfo ()
constructor
TimeDependentEigenDataInfo (const TimeDependentEigenDataInfo &data_info)
copy constructor
~TimeDependentEigenDataInfo ()
destructor
virtual void clear ()
clears the data structures of this object
unsigned int getModeNumber () const
void setModeInfo (const unsigned int mode_num)
sets the modal information for this quantity
virtual unsigned int getDataInfoKindEnumID () const
virtual std::ostream & write (std::ostream &out)
this method writes the info to an output stream
virtual const std::string getPath () const
virtual const std::string getDisplayName () const
virtual bool operator== (const FESystemDatabase::DataInfoBase &data_info) const
Protected Attributes
unsigned int mode_number
transient iteration
Detailed Description
this defines a time independent eigen quantity
Definition at line 365 of file DataInfo.h.
Constructor & Destructor Documentation
FESystemDatabase::TimeDependentEigenDataInfo::TimeDependentEigenDataInfo ()
constructor
Definition at line 783 of file DataInfo.C.
References clear().
                                                                      :
FESystemDatabase::TimeDependentDataInfo()
{
  this->clear();
}
FESystemDatabase::TimeDependentEigenDataInfo::TimeDependentEigenDataInfo (const TimeDependentEigenDataInfo & data_info)
copy constructor
Definition at line 793 of file DataInfo.C.
References mode_number.
                                             :
  FESystemDatabase::TimeDependentDataInfo(data_info)
{
  this->mode_number = data_info.mode_number;
}
FESystemDatabase::TimeDependentEigenDataInfo::~TimeDependentEigenDataInfo ()
destructor
Definition at line 802 of file DataInfo.C.
{
}
Member Function Documentation
void FESystemDatabase::TimeDependentEigenDataInfo::clear () [virtual]
clears the data structures of this object
Reimplemented from FESystemDatabase::TimeDependentDataInfo.
Definition at line 811 of file DataInfo.C.
References FESystemDatabase::TimeDependentDataInfo::clear(), and FESystemNumbers::InvalidID.
Referenced by TimeDependentEigenDataInfo().
{
  this->mode_number = FESystemNumbers::InvalidID;
  FESystemDatabase::TimeDependentDataInfo::clear();
}
unsigned int FESystemDatabase::TimeDependentEigenDataInfo::getDataInfoKindEnumID () const [virtual]
Returns:
the enumeration ID of the kind of the data
Reimplemented from FESystemDatabase::TimeDependentDataInfo.
Definition at line 850 of file DataInfo.C.
{
  return FESystemDatabase::TIME_INDEPENDENT_EIGEN_DATA::num();
}
const std::string FESystemDatabase::TimeDependentEigenDataInfo::getDisplayName () const [virtual]
Reimplemented from FESystemDatabase::TimeDependentDataInfo.
Definition at line 907 of file DataInfo.C.
{
  std::string full_path_name = this->getName();
  // append the mode information to the name
  std::ostringstream mode_num_oss;
  mode_num_oss << this->getModeNumber();
  full_path_name += "_MODE_";
  full_path_name += mode_num_oss.str();
  // append the transient information to the name
  std::ostringstream time_iter_oss;
  time_iter_oss << this->getTransientIterationNumber();
  full_path_name += "_TIME_";
  full_path_name += time_iter_oss.str();
  // append the sensitivity information to the name
  if (this->ifSensitivityData())
    {
    std::ostringstream dv_id_oss;
    dv_id_oss << this->getDVID();
    full_path_name += "_SENS_DV_";
    full_path_name += dv_id_oss.str();
    }
  // append the load case information to the name
  if (this->ifLoadCaseDependent())
    {
    std::ostringstream lc_oss;
    lc_oss << this->getLoadCase();
    full_path_name += "_LC_";
    full_path_name += lc_oss.str();
    }
  return full_path_name;
}
unsigned int FESystemDatabase::TimeDependentEigenDataInfo::getModeNumber () const
Returns:
the time iteration number
Definition at line 822 of file DataInfo.C.
References FESystemNumbers::InvalidID.
{
  // make sure that this was set by the user
  Assert(this->mode_number != FESystemNumbers::InvalidID, ExcInternalError());
  return this->mode_number;
}
const std::string FESystemDatabase::TimeDependentEigenDataInfo::getPath () const [virtual]
Returns:
the exact path to the location of the data for this object in the database
Reimplemented from FESystemDatabase::TimeDependentDataInfo.
Definition at line 860 of file DataInfo.C.
{
  std::string full_path_name = this->getDisciplineEnumName();
  full_path_name +="_";
  full_path_name += this->getName();
  // append the mode information to the name
  std::ostringstream mode_num_oss;
  mode_num_oss << this->getModeNumber();
  full_path_name += "_MODE_NUM_";
  full_path_name += mode_num_oss.str();
  // append the transient information to the name
  std::ostringstream time_iter_oss;
  time_iter_oss << this->getTransientIterationNumber();
  full_path_name += "_TIME_ITER_";
  full_path_name += time_iter_oss.str();
  // append the sensitivity information to the name
  if (this->ifSensitivityData())
    {
    std::ostringstream dv_id_oss;
    dv_id_oss << this->getDVID();
    full_path_name += "_SENSITIVITY_DV_";
    full_path_name += dv_id_oss.str();
    }
  // append the load case information to the name
  if (this->ifLoadCaseDependent())
    {
    std::ostringstream lc_oss;
    lc_oss << this->getLoadCase();
    full_path_name += "_LC_";
    full_path_name += lc_oss.str();
    }
  return full_path_name;
}
bool FESystemDatabase::TimeDependentEigenDataInfo::operator== (const FESystemDatabase::DataInfoBase & data_info) const [virtual]
Returns:
true if the given data info object and this, point to the same data
Reimplemented from FESystemDatabase::TimeDependentDataInfo.
Definition at line 963 of file DataInfo.C.
References mode_number.
{
  if (! FESystemDatabase::TimeDependentDataInfo::operator==(data_info))
    return false;
  else
    {
      const FESystemDatabase::TimeDependentEigenDataInfo &eigen_data_info =
        dynamic_cast<const FESystemDatabase::TimeDependentEigenDataInfo&>(data_info);
      // check each data and return the result
      if (this->mode_number != eigen_data_info.mode_number)
        return false;
    }
  // if it gets here, means that this the two objects are same
  return true;
}
void FESystemDatabase::TimeDependentEigenDataInfo::setModeInfo (const unsigned int mode_num)
sets the modal information for this quantity
Definition at line 834 of file DataInfo.C.
References FESystemNumbers::InvalidID.
{
  // make sure that this object was cleared
  Assert(this->mode_number == FESystemNumbers::InvalidID, ExcInternalError());
  // make sure that the number provided is correct
  Assert(mode_num != FESystemNumbers::InvalidID, ExcInternalError());
  this->mode_number = mode_num;
}
std::ostream & FESystemDatabase::TimeDependentEigenDataInfo::write (std::ostream & out) [virtual]
this method writes the info to an output stream
Reimplemented from FESystemDatabase::TimeDependentDataInfo.
Definition at line 950 of file DataInfo.C.
References FESystemDatabase::TimeDependentDataInfo::write().
{
  FESystemDatabase::TimeDependentDataInfo::write(out);
  out << "Mode Number :   " << this->getModeNumber() << std::endl;
  return out;
}
Member Data Documentation
unsigned int FESystemDatabase::TimeDependentEigenDataInfo::mode_number [protected]
transient iteration
Definition at line 408 of file DataInfo.h.
Referenced by operator==(), and TimeDependentEigenDataInfo().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.C