fesystem: RadiationElementPair Class Reference
RadiationElementPair Class Reference
#include <RadiationElementPair.h>
Public Types
enum ShapeFactorMethod {
AUTOMATIC, DOUBLE_AREA_INT, CONTOUR_INT, MITALAS_CONTOUR_INT,
ANALYTIC
}
enum describing the method to be used
Public Member Functions
RadiationElementPair ()
constructor
~RadiationElementPair ()
destructor
void reinit (RadiationElement *el1, RadiationElement *el2)
initializes the pair with two elements
void clear ()
clears the initialization
std::pair< double, double > getShapeFactor (ShapeFactorMethod method)
Protected Member Functions
std::pair< double, double > analyticShapeFactor ()
calculates and returns the analytic shape factor
std::pair< double, double > doubleAreaIntShapeFactor ()
calculates and returns the double area integration shape factor
std::pair< double, double > contourIntShapeFactor ()
calculates and returns the contour integration shape factor
std::pair< double, double > mitalasContourIntShapeFactor ()
calculates and returns the shape factors using mitalas' method of intgration
std::auto_ptr< Elem > createLocalElem (Elem *elem, std::vector< Node > &nodes)
Protected Attributes
bool initialized
boolean to keep track of whether the pair has been initialized
RadiationElement * rad_elem1
RadiationElement * rad_elem2
Detailed Description
Definition at line 28 of file RadiationElementPair.h.
Member Enumeration Documentation
enum RadiationElementPair::ShapeFactorMethod
enum describing the method to be used
Enumerator:
AUTOMATIC
DOUBLE_AREA_INT
CONTOUR_INT
MITALAS_CONTOUR_INT
ANALYTIC
Definition at line 32 of file RadiationElementPair.h.
    {
      AUTOMATIC,
      DOUBLE_AREA_INT,
      CONTOUR_INT,
      MITALAS_CONTOUR_INT,
      ANALYTIC
    };
Constructor & Destructor Documentation
RadiationElementPair::RadiationElementPair ()
constructor
Definition at line 33 of file RadiationElementPair.C.
                                          :
initialized(false),
rad_elem1(NULL),
rad_elem2(NULL)
#ifdef WITH_MATHEMATICA
,mathematica_link(NULL)
#endif
{
}
RadiationElementPair::~RadiationElementPair ()
destructor
Definition at line 47 of file RadiationElementPair.C.
{
}
Member Function Documentation
std::pair< double, double > RadiationElementPair::analyticShapeFactor () [protected]
calculates and returns the analytic shape factor
Definition at line 145 of file RadiationElementPair.C.
References RadiationElement::FeElementFaceID(), RadiationElement::getArea(), RadiationElement::getRadiationGeometricElem(), RadiationElement::getSurfaceNormal(), rad_elem1, and rad_elem2.
Referenced by getShapeFactor().
{
  // get the geometric element for this element pair, and call the librarry function
  // to get the shape factors
  Elem* elem1 = this->rad_elem1->getRadiationGeometricElem();
  Elem* elem2 = this->rad_elem2->getRadiationGeometricElem();
  double factor_12 = 0.0, factor_21 = 0.0;
  const unsigned int n_nodes1 = elem1->n_nodes();
  const unsigned int n_nodes2 = elem2->n_nodes();
  double * node1_coords[3];
  double * node2_coords[3];
  // create the matrices for passing to the FormFactor routine
//  double *x_coords1 = new double[n_nodes1], *y_coords1 = new double[n_nodes1],
//  *z_coords1 = new double[n_nodes1];
//  double *x_coords2 = new double[n_nodes2], *y_coords2 = new double[n_nodes2],
//  *z_coords2 = new double[n_nodes2];
//  for (unsigned int i=0; i < n_nodes1; i++)
//    std::cout << elem1->point(i);
//
//  std::cout << " \n \n";
//
//  for (unsigned int i=0; i < n_nodes2; i++)
//    std::cout << elem2->point(i);
  for (unsigned int j=0; j < 3; j++)
    {
      node1_coords[j] = new double[n_nodes1];
      node2_coords[j] = new double[n_nodes2];
      for (unsigned int i=0; i < n_nodes1; i++)
        {
          if (this->rad_elem1->FeElementFaceID() < 0)
            node1_coords[j][n_nodes1-1-i] = (elem1->point(i))(j);
          else
            node1_coords[j][i] = (elem1->point(i))(j);
        }
      for (unsigned int i=0; i < n_nodes2; i++)
        {
          if (this->rad_elem2->FeElementFaceID() < 0)
            node1_coords[j][n_nodes2-1-i] = (elem2->point(i))(j);
          else
            node1_coords[j][i] = (elem2->point(i))(j);
        }
    }
//  for (unsigned int i=0; i < n_nodes1; i++)
//    for (unsigned int j=0; j < 3; j++)
//      {
//      if (this->rad_elem1->FeElementFaceID() < 0)
//        elem1_points[((n_nodes1-1)-i)*3+j] = (elem1->point(i))(j);
//      else
//        elem1_points[i*3+j] = (elem1->point(i))(j);
//      }
//  for (unsigned int i=0; i < n_nodes2; i++)
//    for (unsigned int j=0; j < 3; j++)
//      {
//      if (this->rad_elem2->FeElementFaceID() < 0)
//        elem2_points[((n_nodes2-1)-i)*3+j] = (elem2->point(i))(j);
//      else
//        elem2_points[i*3+j] = (elem2->point(i))(j);
//      }
  Assert(false, ExcInternalError());
//      FormFactor(node1_coords, n_nodes1, node2_coords, n_nodes2,
//                  &factor_12, &factor_21);
#ifdef WITH_MATHEMATICA
  // get the factor from mathematica
  double factor = MathematicaFormFactor(this->rad_elem1, this->rad_elem2, this->mathematica_link);
  //  factor_12 = factor / this->rad_elem1->getArea();
//  factor_21 = factor / this->rad_elem2->getArea();
  std::cout << factor_12 <<  "  " << factor / this->rad_elem1->getArea()
    << "  " << factor_21 << "  " << factor / this->rad_elem2->getArea() << std::endl;
  //  std::cout << factor_12 <<  "  " << factor << std::endl;
#endif
  if (factor_12 < 0)
    factor_12 = 0.0;
  if (factor_21 < 0)
    factor_21 = 0.0;
  // if the factor is 1.0, then certain checks need to be made, since the
  // analytic method is unable to catch the error of surfaces lying on top
  // of each other, but with opposite orientation, in which case, the factor
  // is 0.
  if (fabs(factor_12 -1.0) <= 1.0e-10)
    {
      const Point& normal1 = this->rad_elem1->getSurfaceNormal(),
        normal2 = this->rad_elem2->getSurfaceNormal();
      if (normal1 * normal2 < 0.0)
        {
          factor_12 = 0.0;
          // also, check the other shape factor for the pair.
          if (fabs(factor_21 -1.0) <= 1.0e-10)
                factor_21 = 0.0;
        }
    }
  for (unsigned int j=0; j < 3; j++)
    {
      delete[] node1_coords[j];
      delete[] node2_coords[j];
    }
  return std::pair<double, double>(factor_12, factor_21);
}
void RadiationElementPair::clear () [inline]
clears the initialization
Definition at line 156 of file RadiationElementPair.h.
References initialized, rad_elem1, and rad_elem2.
Referenced by RadiationCavityAnalysis::calculateShapeFactorMatrix().
{
  // this element should be initialized
  this->rad_elem1 = NULL;
  this->rad_elem2 = NULL;
  this->initialized = false;
}
std::pair< double, double > RadiationElementPair::contourIntShapeFactor () [protected]
calculates and returns the contour integration shape factor
Definition at line 379 of file RadiationElementPair.C.
References EdgeFactor(), FESystemNumbers::Epsilon, RadiationElement::getArea(), RadiationElement::getRadiationGeometricElem(), RadiationElement::getSurfaceNormal(), FESystemNumbers::Pi, rad_elem1, and rad_elem2.
Referenced by getShapeFactor().
{
  static double factor;
  static unsigned int n_sides1, n_sides2, j1, j2;
  factor = 0.0;
  Point& normal1 = this->rad_elem1->getSurfaceNormal();
  Point& normal2 = this->rad_elem2->getSurfaceNormal();
  // since the cavity is assumed to be convex, if the normals are parallel,
  // and if the dot product of the normals is not negative, then they lie in
  // the same plane, and their shape factor should be zero.
  if (fabs(normal1 * normal2 - 1.0) <= FESystemNumbers::Epsilon)
    return std::pair<double, double>(0.0, 0.0);
  // get the elems from the rad elems
  const Elem* elem1 = this->rad_elem1->getRadiationGeometricElem();
  const Elem* elem2 = this->rad_elem2->getRadiationGeometricElem();
  n_sides1 = elem1->n_sides();
  n_sides2 = elem2->n_sides();
  for (unsigned int i=0; i < n_sides1; i++)
    {
    // get the nodes for this side
    if (i == (n_sides1-1))
      j1 = 0;
    else
      j1 = i + 1;
    const Point& p1 = elem1->point(i);
    const Point& q1 = elem1->point(j1);
    for (unsigned int j=0; j < elem2->n_sides(); j++)
      {
      if (j == (n_sides2-1))
        j2 = 0;
      else
        j2 = j + 1;
      const Point& p2 = elem2->point(j);
      const Point& q2 = elem2->point(j2);
      factor += EdgeFactor(p1, q1, p2, q2);
      }
    }
  factor /= (2.0 * FESystemNumbers::Pi);
  double area1 = this->rad_elem1->getArea(),
    area2 = this->rad_elem2->getArea();
  if (factor < 0.0)
    factor = 0.0;
  return std::pair<double, double>(factor/area1, factor/area2);
}
std::auto_ptr< Elem > RadiationElementPair::createLocalElem (Elem * elem, std::vector< Node > & nodes) [protected]
returns the elem in its local coordinated
Parameters:
elem the elem in global space for which local mesh has to be created
nodes nodes for the elem will be returned in this vector of nodes
Definition at line 55 of file RadiationElementPair.C.
{
  //get the four nodes of this elem
  const Point& point0 = elem->point(0);
  const Point& point1 = elem->point(1);
  const Point& point2 = elem->point(2);
  const Point& point3 = elem->point(3);
  //calculate the position vectors from point 0
  Point vector01, vector02, vector03, tmp_vector1, tmp_vector2;
  vector01.assign(point1 - point0);
  vector02.assign(point2 - point0);
  vector03.assign(point3 - point0);
  Point new_unit_vec_x = vector01.unit();
  tmp_vector1.assign(new_unit_vec_x.cross(vector03));
  tmp_vector2 = tmp_vector1.unit();
  Point new_unit_vec_y = tmp_vector2.cross(new_unit_vec_x);
  //create a new element and set its two nodes at the
  //origin and the elem length
  Point new_point0(0. ,0. ,0. );
  Point new_point1(vector01.size() ,0. ,0.);
  Point new_point2(vector02 * new_unit_vec_x,
                   vector02 * new_unit_vec_y,
                   0.);
  Point new_point3(vector03 * new_unit_vec_x,
                   vector03 * new_unit_vec_y,
                   0.);
  nodes.push_back(Node(new_point0, 0));
  nodes.push_back(Node(new_point1, 1));
  nodes.push_back(Node(new_point2, 2));
  nodes.push_back(Node(new_point3, 3));
  // now create the local element and set its nodes
  std::auto_ptr<Elem> local_elem(new Quad4);
  local_elem->set_node(0) = &(nodes[0]);
  local_elem->set_node(1) = &(nodes[1]);
  local_elem->set_node(2) = &(nodes[2]);
  local_elem->set_node(3) = &(nodes[3]);
  return local_elem;
}
std::pair< double, double > RadiationElementPair::doubleAreaIntShapeFactor () [protected]
calculates and returns the double area integration shape factor
Definition at line 265 of file RadiationElementPair.C.
References FESystemNumbers::Epsilon, RadiationElement::getArea(), RadiationElement::getLocalRadiationGeometricElem(), RadiationElement::getRadiationGeometricElem(), RadiationElement::getSurfaceNormal(), initialized, FESystemNumbers::Pi, rad_elem1, and rad_elem2.
Referenced by getShapeFactor().
{
  bool initialized = false;
  FEType fetype(FIRST, LAGRANGE);
//  std::auto_ptr<Elem> local_elem1(NULL), local_elem2(NULL);
//  std::vector<Node> local_elem1_nodes, local_elem2_nodes;
  std::auto_ptr<FEBase >
    fe_elem1(FEBase::build(2,fetype).release()),
    fe_elem2(FEBase::build(2,fetype).release());
  std::auto_ptr<QBase>
    qbase_elem1(QBase::build(QGAUSS, 2, ELEVENTH).release()),
    qbase_elem2(QBase::build(QGAUSS, 2, ELEVENTH).release());
  // get the elems from the rad elems
  Elem* elem1 = this->rad_elem1->getRadiationGeometricElem();
  Elem* elem2 = this->rad_elem2->getRadiationGeometricElem();
  Point& normal1 = this->rad_elem1->getSurfaceNormal();
  Point& normal2 = this->rad_elem2->getSurfaceNormal();
  // since the cavity is assumed to be convex, if the normals are parallel,
  // and if the dot product of the normals is not negative, then they lie in
  // the same plane, and their shape factor should be zero.
  if (fabs(normal1 * normal2 - 1.0) <= FESystemNumbers::Epsilon)
    return std::pair<double, double>(0.0, 0.0);
  // now, initialize the elements
        if (!initialized)
    {
    fe_elem1->attach_quadrature_rule(qbase_elem1.get());
    fe_elem2->attach_quadrature_rule(qbase_elem2.get());
    initialized = true;
    }
  // this has been commented out, since the local element is now being
  // obtained from the radiation element
//  // now create local elements
//  local_elem1.reset(this->createLocalElem(elem1,
//                                        local_elem1_nodes).release());
//
//  local_elem2.reset(this->createLocalElem(elem2,
//                                        local_elem2_nodes).release());
  fe_elem1->reinit(this->rad_elem1->getLocalRadiationGeometricElem());
  fe_elem2->reinit(this->rad_elem2->getLocalRadiationGeometricElem());
  double factor = 0.0, area1 = 0.0, area2 = 0.0;
  double length = 0.0, cos_theta1 = 0.0, cos_theta2 = 0.0;
  Point point1, point2, point12;
  area1 = this->rad_elem1->getArea();
  area2 = this->rad_elem2->getArea();
  const std::vector<Real>& JxW1 = fe_elem1->get_JxW();
  const std::vector<std::vector<Real> >& phi1 = fe_elem1->get_phi();
  const std::vector<Real>& JxW2 = fe_elem2->get_JxW();
  const std::vector<std::vector<Real> >& phi2 = fe_elem2->get_phi();
  // get the location of the nodes of the two elements
  // this is available from the local_elem_node pointers
  // iterate  over the quadrature points of both the elements
  for (unsigned int qp1=0; qp1<qbase_elem1->n_points(); qp1++)
    {
      point1.zero();
    for (unsigned int node_it=0; node_it<phi1.size(); node_it++)
      for (unsigned int coord_it=0; coord_it<3; coord_it++)
        point1(coord_it) +=
              phi1[node_it][qp1] * (elem1->point(node_it))(coord_it);
    for (unsigned int qp2=0; qp2<qbase_elem2->n_points(); qp2++)
      {
      point2.zero();
      point12.zero(); length = 0.0; cos_theta1 = 0.0; cos_theta2= 0.0;
      // get location of the quadrature points 1 and 2 using the nodal location
      // and shape function values at the quadrature points
      for (unsigned int node_it=0; node_it<phi2.size(); node_it++)
        for (unsigned int coord_it=0; coord_it<3; coord_it++)
          point2(coord_it) +=
          phi2[node_it][qp2] * (elem2->point(node_it))(coord_it);
      // calculate the vector from point 1 to 2
      point12.assign(point2);
      point12 -= point1;
      length = point12.size();
      // calculate the value of cos(theta) at point 1 and 2
      if (length >  1.0e-12)
        {
        cos_theta1 = fabs((normal1) * point12) / length;
        cos_theta2 = fabs((normal2) * point12) / length;
        factor += (cos_theta1 * cos_theta2)/(FESystemNumbers::Pi* length * length) *
          JxW1[qp1] * JxW2[qp2];
        }
      }
    }
    if (factor < 0.0)
      factor = 0.0;
    return std::pair<double, double>(factor/area1, factor/area2);
}
std::pair< double, double > RadiationElementPair::getShapeFactor (ShapeFactorMethod method)
returns the shape factors between the elements as a pair, first element is F1->2, and the second is F2->1
Definition at line 107 of file RadiationElementPair.C.
References ANALYTIC, analyticShapeFactor(), CONTOUR_INT, contourIntShapeFactor(), DOUBLE_AREA_INT, doubleAreaIntShapeFactor(), MITALAS_CONTOUR_INT, and mitalasContourIntShapeFactor().
Referenced by RadiationCavityAnalysis::calculateShapeFactorMatrix().
{
  switch (method)
    {
    case DOUBLE_AREA_INT:
      {
        return this->doubleAreaIntShapeFactor();
      }
      break;
    case ANALYTIC:
      {
        return this->analyticShapeFactor();
      }
      break;
    case CONTOUR_INT:
      {
        return this->contourIntShapeFactor();
      }
      break;
    case MITALAS_CONTOUR_INT:
      {
        return this->mitalasContourIntShapeFactor();
      }
      break;
    default:
      abort();
    }
}
std::pair< double, double > RadiationElementPair::mitalasContourIntShapeFactor () [protected]
calculates and returns the shape factors using mitalas' method of intgration
Definition at line 443 of file RadiationElementPair.C.
References FESystemNumbers::Epsilon, RadiationElement::FeElementFaceID(), RadiationElement::getArea(), RadiationElement::getRadiationGeometricElem(), RadiationElement::getSurfaceNormal(), MitalasEdgeFactor(), FESystemNumbers::Pi, rad_elem1, and rad_elem2.
Referenced by getShapeFactor().
{
  static double factor;
  static unsigned int n_sides1, n_sides2, j1, j2;
  factor = 0.0;
//  double val1, val2;
  Point& normal1 = this->rad_elem1->getSurfaceNormal();
  Point& normal2 = this->rad_elem2->getSurfaceNormal();
  // since the cavity is assumed to be convex, if the normals are parallel,
  // and if the dot product of the normals is not negative, then they lie in
  // the same plane, and their shape factor should be zero.
  if (fabs(normal1 * normal2 - 1.0) <= FESystemNumbers::Epsilon)
    return std::pair<double, double>(0.0, 0.0);
  // get the elems from the rad elems
  const Elem* elem1 = this->rad_elem1->getRadiationGeometricElem();
  const Elem* elem2 = this->rad_elem2->getRadiationGeometricElem();
  n_sides1 = elem1->n_sides();
  n_sides2 = elem2->n_sides();
//  for (unsigned int i=0; i < elem1->n_nodes(); i++)
//    std::cout << elem1->point(i);
//  std::cout << std::endl;
//  for (unsigned int i=0; i < elem2->n_nodes(); i++)
//    std::cout << elem2->point(i);
//  std::cout << std::endl;
  for (unsigned int i=0; i < n_sides1; i++)
    {
    // get the nodes for this side
    if (i == (n_sides1-1))
      j1 = 0;
    else
      j1 = i + 1;
    const Point& p1 = elem1->point(i);
    const Point& q1 = elem1->point(j1);
    for (unsigned int j=0; j < n_sides2; j++)
      {
      if (j == (n_sides2-1))
        j2 = 0;
      else
        j2 = j + 1;
      const Point& p2 = elem2->point(j);
      const Point& q2 = elem2->point(j2);
//      val1 = MitalasEdgeFactor(p1, q1, p2, q2);
//      val2 = NumIntEdgeFactor(p1, q1, p2, q2);
//      if (fabs(val1 - val2) > 1.0e-5)
//        {
//        std::cout << p1 << q1;
//        std::cout << p2 << q2;
//        std::cout << "milatas : " << val1 << "  numeric: " <<  val2<< std::endl;
//        }
      factor += MitalasEdgeFactor(p1, q1, p2, q2);
      }
    }
  if (this->rad_elem1->FeElementFaceID() < 0)
    factor *= -1.0;
  if (this->rad_elem2->FeElementFaceID() < 0)
    factor *= -1.0;
  factor /= (2.0 * FESystemNumbers::Pi);
  double area1 = this->rad_elem1->getArea(),
    area2 = this->rad_elem2->getArea();
//  std::cout << this->rad_elem1->FeElementID() << "," <<
//    this->rad_elem2->FeElementID() << " : " <<
//    factor/area1 << "," << factor/area2 << std::endl;
  //  std::cout << "factor : " << factor << std::endl;
//  std::cout << std::endl;
  if (factor < 0.0)
    factor = 0.0;
  return std::pair<double, double>(factor/area1, factor/area2);
}
void RadiationElementPair::reinit (RadiationElement * el1, RadiationElement * el2) [inline]
initializes the pair with two elements
Definition at line 104 of file RadiationElementPair.h.
References RadiationElement::FeElementID(), RadiationElement::getRadiationGeometricElem(), RadiationElement::getSurfaceNormal(), initialized, rad_elem1, and rad_elem2.
Referenced by RadiationCavityAnalysis::calculateShapeFactorMatrix().
{
  // this element should be initialized
  Assert(!this->initialized, ExcInternalError());
  Assert(el1 != NULL, ExcInternalError());
  Assert(el2 != NULL, ExcInternalError());
  this->rad_elem1 = el1;
  this->rad_elem2 = el2;
#ifdef DEBUG
  // make sure that the elements "see" each other
  // for this, the dot product of the surface normal of an element
  // to any vector to the other surface should be positive
  const Point& normal1 = this->rad_elem1->getSurfaceNormal();
  const Point& normal2 = this->rad_elem2->getSurfaceNormal();
  // calculate the vector from node 0 of element 1 to node 0 of elem 2
  static Point vec;
  vec.assign(this->rad_elem2->getRadiationGeometricElem()->point(0));
  vec -= (this->rad_elem1->getRadiationGeometricElem()->point(0));
  const double eps_num = 1.0e-11;
  if ((vec * normal1 + eps_num) < 0)
    {
    std::cout << "(vec * normal1) >= 0.0 violated: " << (vec * normal1) << std::endl;
    std::cout << "normal 1: " << normal1 << std::endl;
    std::cout << "normal 2: " << normal2 << std::endl;
    std::cout << "rad elem 1 FE_ID: " << this->rad_elem1->FeElementID() << "  rad elem 2 FE_ID: " << this->rad_elem2->FeElementID() << std::endl;
    }
  if ((vec * normal2 - eps_num) > 0)
    {
    std::cout << "(vec * normal2) <= 0.0 violated: " << (vec * normal2) << std::endl;
    std::cout << "normal 1: " << normal1 << std::endl;
    std::cout << "normal 2: " << normal2 << std::endl;
    std::cout << "rad elem 1 FE_ID: " << this->rad_elem1->FeElementID() << "  rad elem 2 FE_ID: " << this->rad_elem2->FeElementID() << std::endl;
    }
  AssertThrow((vec * normal1 + eps_num) >= 0 , ExcInternalError());
  AssertThrow((vec * normal2 - eps_num) <= 0 , ExcInternalError());
#endif
  this->initialized = true;
}
Member Data Documentation
bool RadiationElementPair::initialized [protected]
boolean to keep track of whether the pair has been initialized
Definition at line 85 of file RadiationElementPair.h.
Referenced by clear(), doubleAreaIntShapeFactor(), and reinit().
RadiationElement* RadiationElementPair::rad_elem1 [protected]
Definition at line 88 of file RadiationElementPair.h.
Referenced by analyticShapeFactor(), clear(), contourIntShapeFactor(), doubleAreaIntShapeFactor(), mitalasContourIntShapeFactor(), and reinit().
RadiationElement* RadiationElementPair::rad_elem2 [protected]
Definition at line 91 of file RadiationElementPair.h.
Referenced by analyticShapeFactor(), clear(), contourIntShapeFactor(), doubleAreaIntShapeFactor(), mitalasContourIntShapeFactor(), and reinit().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Radiation/RadiationElementPair.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Radiation/RadiationElementPair.C