fesystem: Loads::ScalarSurfaceLoadCombination Class Reference
Loads::ScalarSurfaceLoadCombination Class Reference
#include <LoadCombination.h>
Public Member Functions
ScalarSurfaceLoadCombination ()
virtual ~ScalarSurfaceLoadCombination ()
virtual void clear ()
virtual unsigned int getLoadClassEnumID () const
double getValue () const
virtual void addLoad (const double factor, const SurfaceLoad *load_ptr)
Protected Attributes
double value
Detailed Description
Definition at line 199 of file LoadCombination.h.
Constructor & Destructor Documentation
Loads::ScalarSurfaceLoadCombination::ScalarSurfaceLoadCombination () [inline]
Definition at line 202 of file LoadCombination.h.
                                    :
      SurfaceLoadCombination(),
      value(0.0)
      {
      }
virtual Loads::ScalarSurfaceLoadCombination::~ScalarSurfaceLoadCombination () [inline, virtual]
Definition at line 209 of file LoadCombination.h.
      {
      }
Member Function Documentation
virtual void Loads::ScalarSurfaceLoadCombination::addLoad (const double factor, const SurfaceLoad * load_ptr) [inline, virtual]
Implements Loads::SurfaceLoadCombination.
Definition at line 233 of file LoadCombination.h.
References Loads::SurfaceLoadCombination::getElemID(), LoadBase::getLoadClassEnumID(), Loads::SurfaceLoadCombination::getSurfaceID(), Loads::SurfaceLoadCombination::load_set, Loads::SurfaceLoadCombination::nLoads(), and value.
      {
        Assert(load_ptr != NULL, ExcInternalError());
        Assert(load_ptr->getLoadClassEnumID() == SCALAR_SURFACE_LOAD::num(),
               ExcInternalError());
        const ScalarSurfaceLoad* ptr = dynamic_cast<const ScalarSurfaceLoad*>(load_ptr);
        // set the node ID
        if (this->nLoads() > 0)
          Assert(this->getElemID() == ptr->getElemID() &&
                 this->getSurfaceID() == ptr->getSurfaceID(),
                 ExcInternalError());
        bool insert_success = this->load_set.insert(load_ptr).second;
        // add this pointer to the set, and adjust the value of the load
        Assert(insert_success, ExcInternalError());
        this->value += factor * ptr->getValue();
      }
virtual void Loads::ScalarSurfaceLoadCombination::clear () [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 215 of file LoadCombination.h.
References Loads::SurfaceLoadCombination::load_set, and value.
      {
        this->value = 0.0;
        this->load_set.clear();
      }
virtual unsigned int Loads::ScalarSurfaceLoadCombination::getLoadClassEnumID () const [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 221 of file LoadCombination.h.
      {
        return SCALAR_SURFACE_LOAD::num();
      }
double Loads::ScalarSurfaceLoadCombination::getValue () const [inline]
Definition at line 227 of file LoadCombination.h.
References value.
      {
        return this->value;
      }
Member Data Documentation
double Loads::ScalarSurfaceLoadCombination::value [protected]
Definition at line 257 of file LoadCombination.h.
Referenced by addLoad(), clear(), and getValue().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCombination.h