fesystem: Solver::NewmarkNonlinearTransientSolver Class Reference
Solver::NewmarkNonlinearTransientSolver Class Reference
#include <NewmarkTransientSolver.h>
Public Member Functions
NewmarkNonlinearTransientSolver (const Solver::NonlinearTransientSolverInfo &transient_info, const Solver::NonlinearSolverInfo &nonlinear_info, const Solver::LinearSolverInfo &linear_info)
constructor
virtual ~NewmarkNonlinearTransientSolver ()
virtual void clear ()
virtual void solve ()
method to solve the eigen system
virtual double getSimulatedTime ()
virtual double getCurrentTime ()
virtual double getCurrentStepSize ()
virtual unsigned int getSimulatedIterationNumber ()
virtual unsigned int getCurrentIterationNumber ()
virtual void setInitialCondition (std::vector< NumericVector< double > * > &state_vecs)
set initial conditions for the analysis
Protected Attributes
double simulated_time
simulated time
double current_time
current time
double time_step_size
current step size
unsigned int simulated_iteration_number
simulated iteration number
std::auto_ptr
< Solver::NonlinearSolver > nonlinear_solver
nonlinear solver
std::vector< double > newmark_constants
FESystemUtility::AutoPtrVector
< NumericVector< double > > last_iter_state_vectors
FESystemUtility::AutoPtrVector
< NumericVector< double > > current_state_vectors
FESystemUtility::AutoPtrVector
< NumericVector< double > > new_state_vectors
Friends
void Solver::NewmarkSolver::getResidual (NumericVector< double > &sol, NumericVector< double > &res, void *ctx)
void Solver::NewmarkSolver::getJacobian (NumericVector< double > &sol, SparseMatrix< double > &jac, void *ctx)
Detailed Description
this class provides an interface to a solver for the solution of eigensystem. This inherits from the FESystemSolverBase class. It takes a pointer to the analysis driver object that owns an instantiation of this class
Definition at line 149 of file NewmarkTransientSolver.h.
Constructor & Destructor Documentation
Solver::NewmarkNonlinearTransientSolver::NewmarkNonlinearTransientSolver (const Solver::NonlinearTransientSolverInfo & transient_info, const Solver::NonlinearSolverInfo & nonlinear_info, const Solver::LinearSolverInfo & linear_info)
constructor
Definition at line 307 of file NewmarkTransientSolver.C.
                                           :
Solver::NonlinearTransientSolverBase(transient_info, nonlinear_info,
                                     linear_info),
simulated_time(0.0),
current_time(0.0),
time_step_size(0.0),
simulated_iteration_number(0)
{
}
Solver::NewmarkNonlinearTransientSolver::~NewmarkNonlinearTransientSolver () [virtual]
Definition at line 321 of file NewmarkTransientSolver.C.
{
}
Member Function Documentation
void Solver::NewmarkNonlinearTransientSolver::clear () [virtual]
this method clears the data structures of this object. This should be called each time the used finishes using this object.
Reimplemented from Solver::NonlinearTransientSolverBase.
Definition at line 330 of file NewmarkTransientSolver.C.
References Solver::NonlinearTransientSolverBase::clear().
{
  this->simulated_time = 0.0;
  this->current_time = 0.0;
  this->time_step_size = 0.0;
  this->simulated_iteration_number = 0;
  this->last_iter_state_vectors.clear();
  this->current_state_vectors.clear();
  this->new_state_vectors.clear();
  Solver::NonlinearTransientSolverBase::clear();
}
unsigned int Solver::NewmarkNonlinearTransientSolver::getCurrentIterationNumber () [virtual]
Returns:
the current time iteration of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 704 of file NewmarkTransientSolver.C.
{
  return this->simulated_iteration_number + 1;
}
double Solver::NewmarkNonlinearTransientSolver::getCurrentStepSize () [virtual]
Returns:
the current time step of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 687 of file NewmarkTransientSolver.C.
{
  return this->time_step_size;
}
double Solver::NewmarkNonlinearTransientSolver::getCurrentTime () [virtual]
Returns:
the current time of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 673 of file NewmarkTransientSolver.C.
Referenced by Solver::NewmarkSolver::getJacobian(), and Solver::NewmarkSolver::getResidual().
{
  return this->current_time;
}
unsigned int Solver::NewmarkNonlinearTransientSolver::getSimulatedIterationNumber () [virtual]
Returns:
the current time iteration of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 696 of file NewmarkTransientSolver.C.
{
  return this->simulated_iteration_number;
}
double Solver::NewmarkNonlinearTransientSolver::getSimulatedTime () [virtual]
Returns:
the current time of the solver integration
Implements Solver::TransientSolverBase.
Definition at line 680 of file NewmarkTransientSolver.C.
{
  return this->simulated_time;
}
void Solver::NewmarkNonlinearTransientSolver::setInitialCondition (std::vector< NumericVector< double > * > & state_vecs) [virtual]
set initial conditions for the analysis
Implements Solver::TransientSolverBase.
Definition at line 615 of file NewmarkTransientSolver.C.
{
  // make sure that the current solutions have not been initialized
  Assert(this->current_state_vectors.size() == 0, ExcInternalError());
  Assert(this->new_state_vectors.size() == 0, ExcInternalError());
  unsigned int system_order =
  dynamic_cast<const Solver::NewmarkNonlinearTransientSolverInfo&>(this->transient_solver_info).getSystemOrder();
  // make sure that the number of vectors provided are one less than the system order
  Assert(state_vecs.size() == system_order,
         ExcInternalError());
  this->current_state_vectors.resize(system_order+1);
  this->last_iter_state_vectors.resize(system_order+1);
  this->new_state_vectors.resize(system_order+1);
  std::auto_ptr<NumericVector<double> > vec;
  for (unsigned int i=0; i < system_order; i++)
    {
      vec.reset(NumericVector<double>::build().release());
      vec->duplicate_vector(*(state_vecs[i]), false);
      vec->close();
      this->last_iter_state_vectors.reset(i, vec.release());
      vec.reset(NumericVector<double>::build().release());
      vec->duplicate_vector(*(state_vecs[i]), true);
      vec->close();
      this->current_state_vectors.reset(i, vec.release());
      vec.reset(NumericVector<double>::build().release());
      vec->duplicate_vector(*(state_vecs[i]), false);
      vec->close();
      this->new_state_vectors.reset(i, vec.release());
    }
  // finally, insert the highest order vectors
  vec.reset(NumericVector<double>::build().release());
  vec->duplicate_vector(*(state_vecs[0]), false);
  vec->close();
  this->last_iter_state_vectors.reset(system_order, vec.release());
  vec.reset(NumericVector<double>::build().release());
  vec->duplicate_vector(*(state_vecs[0]), false);
  vec->close();
  this->current_state_vectors.reset(system_order, vec.release());
  vec.reset(NumericVector<double>::build().release());
  vec->duplicate_vector(*(state_vecs[0]), false);
  vec->close();
  this->new_state_vectors.reset(system_order, vec.release());
}
void Solver::NewmarkNonlinearTransientSolver::solve () [virtual]
method to solve the eigen system
Implements Solver::TransientSolverBase.
Definition at line 347 of file NewmarkTransientSolver.C.
References Driver::TransientAnalysisDriver::clear(), Solver::createLinearSolver(), Solver::createNonlinearSolver(), Driver::AnalysisDriver::getFESystemController(), Solver::NewmarkSolver::getJacobian(), Solver::NewmarkSolver::getResidual(), Solver::NewmarkNonlinearTransientSolverInfo::getSystemOrder(), Solver::NewmarkSolver::initNewmarkConstants(), FESystem::FESystemController::performance_logging, and Solver::NewmarkSolver::updateStateVectors().
{
  this->nonlinear_solver.reset
  (Solver::createNonlinearSolver(this->nonlinear_solver_info,
                                 this->linear_solver_info).release());
  const Solver::NewmarkNonlinearTransientSolverInfo& newmark_info =
  dynamic_cast<const Solver::NewmarkNonlinearTransientSolverInfo&>(this->transient_solver_info);
  unsigned int system_order = newmark_info.getSystemOrder();
  // make sure that the solver has the necessary information
  Assert(this->coefficient_matrices.size() == (system_order+1), ExcInternalError());
  Assert(this->current_state_vectors.size() == (system_order+1), ExcInternalError());
  Assert(this->new_state_vectors.size() == (system_order+1), ExcInternalError());
  Assert(this->jacobian_matrix != NULL, ExcInternalError());
  this->analysis_driver->getFESystemController().performance_logging->setEvent
  ("NewmarkNonlinearTransientSolver::solve()", "Solver");
  // create the vectors to be used in this solution
  std::auto_ptr<NumericVector<double> >
  res_vec(NumericVector<double>::build().release()),
  nonlinear_sol_vec(NumericVector<double>::build().release());
  res_vec->duplicate_vector(*(this->current_state_vectors[0]), false);
  nonlinear_sol_vec->duplicate_vector(*(this->current_state_vectors[0]), false);
  // init the constants
  Solver::NewmarkSolver::initNewmarkConstants(newmark_info,
                                              this->newmark_constants);
  // init the iteration data
  this->simulated_time = this->transient_solver_info.getInitialTime();
  this->simulated_iteration_number = 0;
  // calculate the highest order derivative at initial time from the initial conditions
  // the basic equation to be solved is
  // dX/dt^(n) = inv(C_(n)) * (F_0 - sum_(i=0..n-1) (C_i * dX/dt^(i)))
  dynamic_cast<Driver::NonlinearTransientAnalysisDriver*>(this->analysis_driver)->
  getCoefficientMatrices(this->transient_solver_info.getInitialTime(),
                         this->current_state_vectors.getReference(),
                         this->coefficient_matrices);
  dynamic_cast<Driver::NonlinearTransientAnalysisDriver*>(this->analysis_driver)->
  getForceVector(this->transient_solver_info.getInitialTime(),
                 this->current_state_vectors.getReference(),
                 *res_vec);
  res_vec->close();
  // calculate the RHS of the linear equation
  for (unsigned int i=0; i < system_order; i++)
    {
      nonlinear_sol_vec->zero();
      nonlinear_sol_vec->close();
      this->coefficient_matrices[i]->close();
      this->coefficient_matrices[i]->multiply_vector(*(this->current_state_vectors[i]),
                                                     *nonlinear_sol_vec);
      nonlinear_sol_vec->close();
      res_vec->add(-1.0, *nonlinear_sol_vec);
    }
  res_vec->close();
  // tell the linear solver to factorize this matrix
  this->coefficient_matrices[system_order]->close();
  // initialize the linear solver and solve for the derivative
  std::auto_ptr<Solver::LinearSolver> linear_solver;
  linear_solver.reset
  (Solver::createLinearSolver(this->linear_solver_info).release());
  linear_solver->attachAnalysisDriver(this->analysis_driver);
  linear_solver->setSystemMatrix(*(this->coefficient_matrices[system_order]));
  linear_solver->setPreconditionerMatrix(*(this->coefficient_matrices[system_order]));
  linear_solver->solve(*res_vec,
                       *(this->current_state_vectors[system_order]));
  this->current_state_vectors[system_order]->close();
  // now clear the vectors that were used
  res_vec->zero();
  res_vec->close();
  nonlinear_sol_vec->zero();
  nonlinear_sol_vec->close();
  // and clear the linear solver
  linear_solver.reset();
  // now, increment the iteration number to 1, for which the vectors will be stored
  this->simulated_iteration_number++;
  // tell the driver of the 1st iterate, which will be the initial conditions
  dynamic_cast<Driver::NonlinearTransientAnalysisDriver*>(this->analysis_driver)->
  setNewIteration(this->getSimulatedTime(),
                  this->getSimulatedIterationNumber(),
                  this->current_state_vectors.getReference());
  // also copy the initial conditions to the last iteration vector
  for (unsigned int i = 0; i <= system_order; i++)
    {
      *(this->last_iter_state_vectors[i]) = *(this->current_state_vectors[i]);
      this->last_iter_state_vectors[i]->close();
    }
  this->nonlinear_solver->clear();
  this->nonlinear_solver->attachAnalysisDriver(this->analysis_driver);
  this->nonlinear_solver->setFunctions(Solver::NewmarkSolver::getResidual,
                                       Solver::NewmarkSolver::getJacobian,
                                       (void *) this);
  this->nonlinear_solver->attachMatrixAndVector(*jacobian_matrix, *res_vec);
  while (this->getSimulatedTime() < this->transient_solver_info.getFinalTime())
    {
      this->current_time = this->simulated_time + this->transient_solver_info.getInitialTimeStep();
      nonlinear_sol_vec->zero();
      //    *nonlinear_sol_vec = *(this->last_iter_state_vectors[0]);
      //    nonlinear_sol_vec->close();
      this->nonlinear_solver->solve(*nonlinear_sol_vec);
      // copy the vector
      *(this->new_state_vectors[0]) = *(this->last_iter_state_vectors[0]);
      this->new_state_vectors[0]->add(1.0,  *nonlinear_sol_vec);
      this->new_state_vectors[0]->close();
      // calculate the new derivatives
      Solver::NewmarkSolver::updateStateVectors
      (newmark_info,
       this->newmark_constants,
       this->last_iter_state_vectors.getReference(),
       this->new_state_vectors.getReference());
      // increment the current time and the iteration number
      this->simulated_time = this->getCurrentTime();
      this->simulated_iteration_number++;
      // tell the analysis driver to record the iteration increment
      dynamic_cast<Driver::NonlinearTransientAnalysisDriver*>(this->analysis_driver)->
      setNewIteration(this->getSimulatedTime(),
                      this->getSimulatedIterationNumber(),
                      this->last_iter_state_vectors.getReference());
    }
  this->nonlinear_solver.reset();
  this->analysis_driver->getFESystemController().performance_logging->unsetEvent
  ("NewmarkNonlinearTransientSolver::solve()", "Solver");
}
Friends And Related Function Documentation
void Solver::NewmarkSolver::getJacobian (NumericVector< double > & sol, SparseMatrix< double > & jac, void * ctx) [friend]
void Solver::NewmarkSolver::getResidual (NumericVector< double > & sol, NumericVector< double > & res, void * ctx) [friend]
Member Data Documentation
FESystemUtility::AutoPtrVector<NumericVector<double> > Solver::NewmarkNonlinearTransientSolver::current_state_vectors [protected]
internal state vectors, arranged in increasing order of time derivative. The (n-1)th iterates are stored here
Definition at line 220 of file NewmarkTransientSolver.h.
Referenced by Solver::NewmarkSolver::getJacobian(), and Solver::NewmarkSolver::getResidual().
double Solver::NewmarkNonlinearTransientSolver::current_time [protected]
current time
Definition at line 201 of file NewmarkTransientSolver.h.
FESystemUtility::AutoPtrVector<NumericVector<double> > Solver::NewmarkNonlinearTransientSolver::last_iter_state_vectors [protected]
internal state vectors, arranged in increasing order of time derivative. The (n-1)th iterates are stored here
Definition at line 216 of file NewmarkTransientSolver.h.
Referenced by Solver::NewmarkSolver::getJacobian(), and Solver::NewmarkSolver::getResidual().
FESystemUtility::AutoPtrVector<NumericVector<double> > Solver::NewmarkNonlinearTransientSolver::new_state_vectors [protected]
internal state vectors, arranged in increasing order of time derivative. The nth iterates are stored here
Definition at line 224 of file NewmarkTransientSolver.h.
Referenced by Solver::NewmarkSolver::getJacobian(), and Solver::NewmarkSolver::getResidual().
std::vector<double> Solver::NewmarkNonlinearTransientSolver::newmark_constants [protected]
Definition at line 212 of file NewmarkTransientSolver.h.
Referenced by Solver::NewmarkSolver::getJacobian(), and Solver::NewmarkSolver::getResidual().
std::auto_ptr<Solver::NonlinearSolver> Solver::NewmarkNonlinearTransientSolver::nonlinear_solver [protected]
nonlinear solver
Definition at line 210 of file NewmarkTransientSolver.h.
unsigned int Solver::NewmarkNonlinearTransientSolver::simulated_iteration_number [protected]
simulated iteration number
Definition at line 207 of file NewmarkTransientSolver.h.
double Solver::NewmarkNonlinearTransientSolver::simulated_time [protected]
simulated time
Definition at line 198 of file NewmarkTransientSolver.h.
double Solver::NewmarkNonlinearTransientSolver::time_step_size [protected]
current step size
Definition at line 204 of file NewmarkTransientSolver.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/NewmarkTransientSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/NewmarkTransientSolver.C