fesystem: Property::PropertyCard< double > Class Template Reference
Property::PropertyCard< double > Class Template Reference
this is a specialization of the class for property values that are stored as double
#include <PropertyCard.h>
Public Member Functions
PropertyCard ()
~PropertyCard ()
virtual unsigned int getNProperties () const
virtual void getPropertyValue (const unsigned int enum_id, double &value) const
this method returns the value of a property
virtual void getPropertyDerivativeForGlobalParameter (const unsigned int enum_ID, const unsigned int param_ID, double &value) const
virtual void getPropertyDerivativeForLocalParameter (const unsigned int enum_ID, const unsigned int param_ID, double &value) const
Protected Types
typedef std::map< unsigned int,
double > PropertyMap
Protected Member Functions
virtual void getPropertyDerivative (const unsigned int enum_ID, const unsigned int param_ID, double &value) const
virtual std::string getPropertyEnumName (const unsigned int enum_ID) const =0
virtual const unsigned int getPropertyEnumID (const std::string &enum_name) const =0
std::istream & readFromInputStream (std::istream &input)
this method reads from the input stream
Protected Attributes
PropertyMap property_reference_values
Detailed Description
template<>
class Property::PropertyCard< double >
this is a specialization of the class for property values that are stored as double
Definition at line 28 of file PropertyCard.h.
Member Typedef Documentation
typedef std::map<unsigned int, double> Property::PropertyCard< double >::PropertyMap [protected]
Definition at line 89 of file PropertyCard.h.
Constructor & Destructor Documentation
Property::PropertyCard< double >::PropertyCard () [inline]
Definition at line 99 of file PropertyCard.h.
                                          :
PropertyCardBase()
{
}
Property::PropertyCard< double >::~PropertyCard () [inline]
Definition at line 108 of file PropertyCard.h.
{
  // delete the parameters since they were created using the new operator
  Property::PropertyCardBase::ParameterMap::iterator param_it, param_end;
  param_it = this->parameter_map.begin();
  param_end = this->parameter_map.end();
  for (; param_it != param_end; param_it++)
    {
    delete param_it->second;
    param_it->second = NULL;
    }
}
Member Function Documentation
unsigned int Property::PropertyCard< double >::getNProperties () const [inline, virtual]
Implements Property::PropertyCardBase.
Definition at line 127 of file PropertyCard.h.
Referenced by IsotropicElemDataCard::readFromInputStream(), and ForcedConvection_1D_ElemDataCard::readFromInputStream().
{
  return this->property_reference_values.size();
}
void Property::PropertyCard< double >::getPropertyDerivative (const unsigned int enum_ID, const unsigned int param_ID, double & value) const [inline, protected, virtual]
this method returns the derivative of a property value with respect to a specified parameter. the parameter values at which the derivatives should be calculated is obtained from the initialization of the property card. The parameter ID is the external ID of the parameter in the card. This method should not be used by the user, since the external IDs are particular only to the card. The user can access the public methods for global and local parameters
Definition at line 180 of file PropertyCard.h.
{
  // check if the data has been initialized
  Assert (this->local_params_initialized == true,
          ExcInvalidState());
  Assert (this->global_params_initialized == true,
          ExcInvalidState());
  // make sure that the property name asked for, exists, and if it
  // does, get the value of derivative for same
  Property::PropertyCard<double>::PropertyMap::const_iterator property_it =
    this->property_reference_values.find(enum_ID);
  AssertThrow(property_it != this->property_reference_values.end(),
         Property::PropertyCardBase::ExcPropertyDoesNotExist
         (this->getPropertyEnumName(enum_ID)));
  value = 0.0;
  const unsigned int param_internal_ID = this->getParameterInternalID(param_ID),
    prop_int_ID = this->getPropertyInternalID(enum_ID);
  double func_value = 0.0;
  func_value = (*this->parameter_function_value_table)(prop_int_ID, param_internal_ID, 1);
  value += func_value;
}
void Property::PropertyCard< double >::getPropertyDerivativeForGlobalParameter (const unsigned int enum_ID, const unsigned int param_ID, double & value) const [inline, virtual]
this method returns the derivative of a property value with respect to a specified global parameter, whose global ID in the design database is specified the parameter values at which the derivatives should be calculated are obtained from the initialization of the property card.
Definition at line 217 of file PropertyCard.h.
References Property::PropertyCardBase::getID().
Referenced by Isotropic2D_ElemDataCard::getFactorSensitivityForGlobalParameter(), and ForcedConvection_1D_ElemDataCard::getFactorSensitivityForGlobalParameter().
{
  // make sure that this parameter is a global param
  Property::PropertyCardBase::GlobalParameterMap::const_iterator it, end;
  it = this->global_parameter_map.find(param_ID);
  end = this->global_parameter_map.end();
  // if the property card is not dependent on this parameter, then the sensitivity
  // should be zero
  if(it == end)
    {
    value = 0.0;
    return;
    }
  unsigned int param_external_ID = it->second->getID();
  this->getPropertyDerivative(enum_ID, param_external_ID, value);
}
void Property::PropertyCard< double >::getPropertyDerivativeForLocalParameter (const unsigned int enum_ID, const unsigned int param_ID, double & value) const [inline, virtual]
this method returns the derivative of a property value with respect to a specified local parameter, whose enum ID is specified the parameter values at which the derivatives should be calculated are obtained from the initialization of the property card.
Definition at line 245 of file PropertyCard.h.
References Property::PropertyCardBase::getID().
Referenced by Isotropic2D_ElemDataCard::getFactorSensitivityForLocalParameter(), and ForcedConvection_1D_ElemDataCard::getFactorSensitivityForLocalParameter().
{
  // make sure that this parameter is a global param
  Property::PropertyCardBase::LocalParameterMap::const_iterator it, end;
  it = this->local_parameter_map.find(param_ID);
  end = this->local_parameter_map.end();
  // if the property card is not dependent on this parameter, then the sensitivity
  // should be zero
  if(it == end)
    {
    value = 0.0;
    return;
    }
  unsigned int param_external_ID = it->second->getID();
  this->getPropertyDerivative(enum_ID, param_external_ID, value);
}
virtual const unsigned int Property::PropertyCard< double >::getPropertyEnumID (const std::string & enum_name) const [protected, pure virtual]
Returns:
the property ID from enumeration name of the property
Implemented in ForcedConvection_1D_ElemDataCard, Isotropic1D_ElemDataCard, Isotropic2D_ElemDataCard, Isotropic3D_ElemDataCard, and IsotropicMaterialPropertyCard.
Referenced by IsotropicElemDataCard::readFromInputStream().
virtual std::string Property::PropertyCard< double >::getPropertyEnumName (const unsigned int enum_ID) const [protected, pure virtual]
Returns:
the property name from enumeration ID of the property
Implemented in ForcedConvection_1D_ElemDataCard, Isotropic1D_ElemDataCard, Isotropic2D_ElemDataCard, Isotropic3D_ElemDataCard, and IsotropicMaterialPropertyCard.
void Property::PropertyCard< double >::getPropertyValue (const unsigned int enum_id, double & value) const [inline, virtual]
this method returns the value of a property
Definition at line 139 of file PropertyCard.h.
Referenced by Isotropic2D_ElemDataCard::getFactor(), Isotropic1D_ElemDataCard::getFactor(), ForcedConvection_1D_ElemDataCard::getFactor(), Isotropic2D_ElemDataCard::getFactorSensitivityForGlobalParameter(), ForcedConvection_1D_ElemDataCard::getFactorSensitivityForGlobalParameter(), Isotropic2D_ElemDataCard::getFactorSensitivityForLocalParameter(), and ForcedConvection_1D_ElemDataCard::getFactorSensitivityForLocalParameter().
{
  // check if the param has been initialized
  Assert (this->local_params_initialized == true,
          ExcInvalidState());
  Assert (this->global_params_initialized == true,
          ExcInvalidState());
  // make sure that the property name asked for, exists, and if it
  // does, get the value for same
  Property::PropertyCard<double>::PropertyMap::const_iterator
    property_it = this->property_reference_values.find(enumID);
  static std::string name;
  name.clear(); name = this->getPropertyEnumName(enumID);
  AssertThrow(property_it != this->property_reference_values.end(),
         Property::PropertyCardBase::ExcPropertyDoesNotExist
         (name));
  // now get the value, and add the contributions from the parameter functions
  //  static DataType prop_value;
  value = property_it->second;
  const unsigned int n_params = this->parameter_map.size(),
    prop_int_ID = this->getPropertyInternalID(enumID);
  double func_value = 0.0;
  for (unsigned int param_it = 0; param_it < n_params; param_it++)
    {
    func_value = (*this->parameter_function_value_table)(prop_int_ID, param_it, 0);
    value += func_value;
    }
}
std::istream & Property::PropertyCard< double >::readFromInputStream (std::istream & input) [inline, protected]
this method reads from the input stream
Reimplemented in ElemDataCard, ForcedConvection_1D_ElemDataCard, and IsotropicElemDataCard.
Definition at line 273 of file PropertyCard.h.
References FESystemNumbers::InvalidID, and FESystemIOUtility::readFromInput().
Referenced by operator>>().
{
  std::string tag;
  // read the beginning data of the card
  tag = this->getPropertyCardKindEnumName();
  FESystemIOUtility::readFromInput(input, tag);
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->cardID);
  // now read in the property base values
  {
    unsigned int n_prop = 0, prop_ID = 0;
    double value = 0.0;
    bool insert_success = false;
    FESystemIOUtility::readFromInput(input, "N_PROPERTIES", n_prop);
    Property::PropertyCard<double>::PropertyMap::iterator prop_it;
    for (unsigned int i=0; i<n_prop; i++)
      {
      tag.clear(); value = 0.0;
      input >> tag;
      prop_ID = this->getPropertyEnumID(tag);
      input >> value;
      // now insert the value in the map, and also in the external to
      // internal ID map
      insert_success = this->property_reference_values.insert
        (Property::PropertyCard<double>::PropertyMap::value_type
         (prop_ID, value)).second;
      AssertThrow(insert_success,
             Property::PropertyCardBase::ExcDuplicatePropertySpecified(tag));
      insert_success = this->property_enumID_to_internal_ID_map.insert
        (Property::PropertyCardBase::IDMap::value_type(prop_ID, i)).second;
      // if the previous assert was true, this one should also be true.
      AssertThrow(insert_success,
             Property::PropertyCardBase::ExcDuplicatePropertySpecified(tag));
      }
  }
  // now read the parameters
  this->readParametersFromInputStream(input);
  // now read in the property-parameter function ID table
  {
    // first initialize the table
    unsigned int n_prop = this->getNProperties(),
    n_param = this->getNParameters();
    this->parameter_function_ID_table->reinit(n_prop, n_param);
    this->parameter_function_ID_table->reset_values(FESystemNumbers::InvalidID);
    TableIndices<3> indices(n_prop, n_param, 2);
    this->parameter_function_value_table->reinit(indices);
    this->parameter_function_value_table->reset_values(0.0);
    unsigned int n_func_IDs, prop_ID = 0, param_ID = 0, func_ID = 0,
      prop_internal_ID = 0, param_internal_ID = 0;
    FESystemIOUtility::readFromInput(input, "N_FUNCTION_IDS", n_func_IDs);
    for (unsigned int i=0; i<n_func_IDs; i++)
      {
      tag.clear();
      input >> tag;
      prop_ID = this->getPropertyEnumID(tag);
      input >> param_ID;
      input >> func_ID;
      // get the internal IDS
      prop_internal_ID = this->getPropertyInternalID(prop_ID);
      param_internal_ID = this->getParameterInternalID(param_ID);
      // and, insert the value in the table
      // first make sure that this property hasn't already been set.
      AssertThrow((*this->parameter_function_ID_table)(prop_internal_ID, param_internal_ID)  ==
                  FESystemNumbers::InvalidID,
                  FESystemExceptions::ExcDuplicateID("Property Function",prop_internal_ID));
      (*this->parameter_function_ID_table)(prop_internal_ID, param_internal_ID) = func_ID;
      }
  }
  // the card should end with the END tag
  tag = this->getPropertyCardKindEnumName();
  FESystemIOUtility::readFromInput(input, tag);
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Member Data Documentation
PropertyMap Property::PropertyCard< double >::property_reference_values [protected]
Definition at line 91 of file PropertyCard.h.
Referenced by IsotropicElemDataCard::readFromInputStream(), and ForcedConvection_1D_ElemDataCard::readFromInputStream().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/PropertyCard.h