fesystem: GeometricSurface Class Reference
GeometricSurface Class Reference
#include <GeometricSurface.h>
Public Member Functions
GeometricSurface (GeometricModel &)
constructor
virtual ~GeometricSurface ()
destructor
virtual GeometricEntityType type () const
returns the type of this entity
const std::vector
< LineAndOrientationPair > & getLines () const
returns the lines of this surface
virtual bool checkIfDuplicate (const GeometricEntity &)
method to check if this object is a duplicate of the given object
Protected Member Functions
virtual void readFromInput (std::istream &)
method to read from input
virtual void writeToOutput (std::ostream &)
method to write to output
Protected Attributes
std::vector
< LineAndOrientationPair > lines
location of this point
Detailed Description
this class defines a geometric surface, that is composed of lines. It could be 3 or 4 sided surface
Definition at line 21 of file GeometricSurface.h.
Constructor & Destructor Documentation
GeometricSurface::GeometricSurface (GeometricModel & model)
constructor
Definition at line 14 of file GeometricSurface.C.
  :GeometricEntity(model)
{
}
GeometricSurface::~GeometricSurface () [virtual]
destructor
Definition at line 21 of file GeometricSurface.C.
{
}
Member Function Documentation
bool GeometricSurface::checkIfDuplicate (const GeometricEntity & surf_ref) [virtual]
method to check if this object is a duplicate of the given object
Implements GeometricEntity.
Definition at line 26 of file GeometricSurface.C.
References GeometricEntity::base_entity_ID, GeometricEntity::baseEntityID(), getLines(), GeometricEntity::is_duplicate, lines, GeometricEntity::same_orientation_as_base_entity, GeometricEntity::SURFACE, and GeometricEntity::type().
{
  // make sure that the two surfaces are not the same object
  assert (&surf_ref != this);
  const unsigned int n_lines = this->lines.size();
  // also, its type should be a surface
  if (surf_ref.type() != GeometricEntity::SURFACE)
    return false;
  // convert this entity's reference to a geometric surface
  const GeometricSurface& surf = dynamic_cast<const GeometricSurface&>(surf_ref);
  // get the lines for the given surface
  const std::vector<LineAndOrientationPair>& surf_lines = surf.getLines();
  if (n_lines != surf_lines.size())
    return false;
  // get the line IDs for the two surfaces, and take into account the orientation.
  // the tests for now will be simple enough where it is assumed that for the two surfaces, if the
  // bounding lines are the same, they are duplicate. Then, if that is the case, then the orientation
  // of one of the lines in bot surfaces will give the orientation of the surface. i.e., if line 1 has ID 45
  // in surface 1 and -45 in surface 2, then the two orientations are the opposite in direction.
  unsigned int id_sum=0;
  for (unsigned int i=0; i < n_lines; i++)
    for (unsigned int j=0; j < n_lines; j++)
      {
        if (this->lines[i].first->baseEntityID() == surf_lines[j].first->baseEntityID())
          id_sum++;
      }
  if (id_sum > n_lines)
    abort(); // a surface cannot have multiple lines by same ID
  else if (id_sum < n_lines)
    return false; // the two surfaces do not share the same boundary
  else
    {
      // this implies that id_sum == n_lines
      // now set the base entity ID and return
      this->is_duplicate = true;
      this->base_entity_ID = surf.baseEntityID();
      // check the orientation of any one line to establish the orientation of this surface
      // with respect to the given surface
      for (unsigned int j=0; j < n_lines; j++)
        if (this->lines[0].first->baseEntityID() == surf_lines[j].first->baseEntityID())
          {
            if (this->lines[0].second == surf_lines[j].second)
              this->same_orientation_as_base_entity = true;
            else
              this->same_orientation_as_base_entity = false;
            break;
          }
      return false;
    }
}
const std::vector< LineAndOrientationPair > & GeometricSurface::getLines () const [inline]
returns the lines of this surface
Definition at line 61 of file GeometricSurface.h.
References lines.
Referenced by checkIfDuplicate().
{
  return this->lines;
}
void GeometricSurface::readFromInput (std::istream & input) [protected, virtual]
method to read from input
Implements GeometricEntity.
Definition at line 90 of file GeometricSurface.C.
References GeometricEntity::geometric_model, GeometricModel::getLineForID(), lines, and GeometricEntity::unique_ID.
{
  input >> this->unique_ID;
  unsigned int n_lines = 0;
  int line_num=0;
  input >> n_lines;
  GeometricLine* line = NULL;
  for (unsigned int i=0; i<n_lines; i++)
    {
      input >> line_num;
      line = &(this->geometric_model.getLineForID(line_num));
      if (line_num > 0) // same orientation
        this->lines.push_back(std::make_pair<GeometricLine*, bool>(line,true));
      else // opposite orientation
        this->lines.push_back(std::make_pair<GeometricLine*, bool>(line,false));
    }
}
GeometricEntity::GeometricEntityType GeometricSurface::type () const [inline, virtual]
returns the type of this entity
Implements GeometricEntity.
Definition at line 54 of file GeometricSurface.h.
References GeometricEntity::SURFACE.
{
  return GeometricEntity::SURFACE;
}
void GeometricSurface::writeToOutput (std::ostream & output) [protected, virtual]
method to write to output
Implements GeometricEntity.
Definition at line 113 of file GeometricSurface.C.
References lines, and GeometricEntity::unique_ID.
{
  output << this->unique_ID << "   ";
  unsigned int n_lines = this->lines.size();
  int line_num = 0;
  for (unsigned int i=0; i < n_lines; i++)
    {
      line_num = this->lines[i].first->ID();
      if (this->lines[i].second == false)
        line_num *= -1;
      output << line_num << "   ";
    }
  output << std::endl;
}
Member Data Documentation
std::vector<LineAndOrientationPair> GeometricSurface::lines [protected]
location of this point
Definition at line 49 of file GeometricSurface.h.
Referenced by checkIfDuplicate(), getLines(), readFromInput(), and writeToOutput().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricSurface.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricSurface.C