fesystem: FESystemUtility::AutoPtrVector< T > Class Template Reference
FESystemUtility::AutoPtrVector< T > Class Template Reference
#include <AutoptrVector.h>
Public Member Functions
AutoPtrVector ()
AutoPtrVector (const unsigned int n)
AutoPtrVector (FESystemUtility::AutoPtrVector< T > &auto_vec)
AutoPtrVector (std::vector< T * > *vec_ptr)
~AutoPtrVector ()
unsigned int size ()
void clear ()
clears all the elements in the vector, and reduces its size to zero
void reset (std::vector< T * > *new_vec)
std::vector< T * > * release ()
void resize (const unsigned int n)
void push_back (T *elem)
this attaches another pointer to this end of the vector
T * operator[] (const unsigned int n)
this returns the nth element from the vector.
void reset (unsigned int i, T *ptr)
this resets the data at the ith location of the vector
const std::vector< T * > * get ()
this returns a constant pointer to the vector of this object.
std::vector< T * > & getReference ()
this returns a reference to the vector of this object.
Protected Attributes
std::vector< T * > * vec
the pointer of vector for this object
Detailed Description
template<typename T>
class FESystemUtility::AutoPtrVector< T >
Definition at line 14 of file AutoptrVector.h.
Constructor & Destructor Documentation
template<typename T> FESystemUtility::AutoPtrVector< T >::AutoPtrVector () [inline]
Definition at line 17 of file AutoptrVector.h.
                     :
        vec(NULL)
        {
          vec = new std::vector<T*>();
        }
template<typename T> FESystemUtility::AutoPtrVector< T >::AutoPtrVector (const unsigned int n) [inline]
Definition at line 24 of file AutoptrVector.h.
                                         :
        vec(NULL)
        {
          vec = new std::vector<T*>();
          vec->resize(n);
        }
template<typename T> FESystemUtility::AutoPtrVector< T >::AutoPtrVector (FESystemUtility::AutoPtrVector< T > & auto_vec) [inline]
Definition at line 34 of file AutoptrVector.h.
                                                              :
        vec(NULL)
        {
          Assert(auto_vec.get() != NULL, ExcInternalError());
          this->vec = auto_vec.release();
        }
template<typename T> FESystemUtility::AutoPtrVector< T >::AutoPtrVector (std::vector< T * > * vec_ptr) [inline]
Definition at line 43 of file AutoptrVector.h.
                                           :
        vec(NULL)
        {
          Assert(vec_ptr != NULL, ExcInternalError());
          this->vec = vec_ptr;
        }
template<typename T> FESystemUtility::AutoPtrVector< T >::~AutoPtrVector () [inline]
Definition at line 52 of file AutoptrVector.h.
        {
          if (this->vec != NULL)
            {
              // iterate over all elements and delete them
              for (unsigned int i=0; i < this->vec->size(); i++)
                delete (*this->vec)[i];
              // now delete the vector
              delete this->vec;
              this->vec = NULL;
            }
        }
Member Function Documentation
template<typename T> void FESystemUtility::AutoPtrVector< T >::clear () [inline]
clears all the elements in the vector, and reduces its size to zero
Definition at line 77 of file AutoptrVector.h.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads(), LoadDatabase::getAllLoadCombinations< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >(), FESystemUtility::AutoPtrVector< NumericVector< double > >::reset(), FESystemUtility::AutoPtrVector< NumericVector< double > >::resize(), Driver::LinearTransientAnalysisDriver::solveCurrentLoadCase(), Driver::NonlinearTransientAnalysisDriver::solveCurrentLoadCase(), and GmshOutputProcessor::writeNodalData().
        {
          // this cannot be called if the vector has been released
          Assert (this->vec != NULL, ExcInternalError());
          // iterate over all elements and delete them
          for (unsigned int i=0; i < this->vec->size(); i++)
            delete (*this->vec)[i];
          this->vec->clear();
        }
template<typename T> const std::vector<T*>* FESystemUtility::AutoPtrVector< T >::get () [inline]
this returns a constant pointer to the vector of this object.
Definition at line 162 of file AutoptrVector.h.
Referenced by Driver::EigenProblemAnalysisDriver::applyBoundaryConditionsForCurrentAnalysis(), Driver::AnalysisDriver::applyBoundaryConditionsToMatrixForCurrentAnalysis(), Driver::AnalysisDriver::applyBoundaryConditionsToVectorForCurrentAnalysis(), FESystemUtility::AutoPtrVector< NumericVector< double > >::AutoPtrVector(), Driver::RogerApproximationAeroelasticityDriver::createSubMatrixIndices(), Driver::EigenProblemAnalysisDriver::getSubmatrixAfterBoundaryCondition(), Discipline::FluidAnalysis::performAdditionalOperationsOnGlobalQuantities(), Discipline::StructuralAnalysis::performAdditionalOperationsOnGlobalQuantities(), and GmshOutputProcessor::writeNodalData().
        {
          return this->vec;
        }
template<typename T> std::vector<T*>& FESystemUtility::AutoPtrVector< T >::getReference () [inline]
this returns a reference to the vector of this object.
Definition at line 169 of file AutoptrVector.h.
Referenced by Solver::NewmarkSolver::getJacobian(), Solver::NewmarkSolver::getResidual(), Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase(), Driver::LinearTransientAnalysisDriver::solveCurrentLoadCase(), and Driver::NonlinearTransientAnalysisDriver::solveCurrentLoadCase().
        {
          return *(this->vec);
        }
template<typename T> T* FESystemUtility::AutoPtrVector< T >::operator[] (const unsigned int n) [inline]
this returns the nth element from the vector.
Definition at line 138 of file AutoptrVector.h.
        {
          Assert(this->vec != NULL, ExcInternalError());
          Assert(n < this->vec->size(), ExcInternalError());
          return (*this->vec)[n];
        }
template<typename T> void FESystemUtility::AutoPtrVector< T >::push_back (T * elem) [inline]
this attaches another pointer to this end of the vector
Definition at line 128 of file AutoptrVector.h.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads(), Solution::TransientThermalSolution::getTimeDependentNodalSolutionDataInfo(), Solution::TransientStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::LinearizedBucklingEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::StructuralVibrationEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::AeroelasticitySolution::getTimeIndependentNodalSolutionDataInfo(), and GmshOutputProcessor::writeNodalData().
        {
          Assert(this->vec != NULL, ExcInternalError());
          Assert(elem != NULL, ExcInternalError());
          this->vec->push_back(elem);
        }
template<typename T> std::vector<T*>* FESystemUtility::AutoPtrVector< T >::release () [inline]
this releases the ownership of the vector from this object, and sets the pointer of this object to NULL
Definition at line 107 of file AutoptrVector.h.
Referenced by FESystemUtility::AutoPtrVector< NumericVector< double > >::AutoPtrVector().
        {
          Assert(this->vec != NULL, ExcInternalError());
          std::vector<T*>* new_vec = this->vec;
          this->vec = NULL;
          return new_vec;
        }
template<typename T> void FESystemUtility::AutoPtrVector< T >::reset (std::vector< T * > * new_vec) [inline]
if the vector was released from this object, this method can be used to attach another vector to this object
Definition at line 91 of file AutoptrVector.h.
Referenced by FESystemDatabase::TransientDataInfoSet::getDataInfoForAllTimeSteps(), Solution::LinearizedBucklingEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::ThermalSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::LinearStressSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeIndependentNodalSolutionDataInfo(), LoadDatabase::getAllLoadCombinations< Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination >(), LoadDatabase::getAllLoadCombinations< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >(), Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase(), Driver::LinearTransientAnalysisDriver::solveCurrentLoadCase(), Driver::NonlinearTransientAnalysisDriver::solveCurrentLoadCase(), and GmshOutputProcessor::writeNodalData().
        {
          Assert(new_vec != NULL, ExcInternalError());
          if (this->vec != NULL)
            {
              this->clear();
              delete this->vec;
            }
          this->vec = new_vec;
        }
template<typename T> void FESystemUtility::AutoPtrVector< T >::reset (unsigned int i, T * ptr) [inline]
this resets the data at the ith location of the vector
Definition at line 148 of file AutoptrVector.h.
        {
          Assert(i < this->size(), ExcInternalError());
          Assert(ptr != NULL, ExcInternalError());
          Assert(this->vec != NULL, ExcInternalError());
          if ((*this->vec)[i] != NULL)
            delete (*this->vec)[i];
          (*this->vec)[i] = ptr;
        }
template<typename T> void FESystemUtility::AutoPtrVector< T >::resize (const unsigned int n) [inline]
this clears the contents of the vector and resizes it to the given dimensions. This cannot be called if the vector has been released
Definition at line 119 of file AutoptrVector.h.
Referenced by Solution::LinearizedBucklingEigenSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::ThermalSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::LinearStressSolution::getTimeIndependentNodalSolutionDataInfo(), Solution::NonlinearStaticStructuralSolution::getTimeIndependentNodalSolutionDataInfo(), and GmshOutputProcessor::writeNodalData().
        {
          Assert(this->vec != NULL, ExcInternalError());
          this->clear();
          this->vec->resize(n);
        }
template<typename T> unsigned int FESystemUtility::AutoPtrVector< T >::size () [inline]
returns the number of elements in the vector. This cannot be called if the vector has been released from this object.
Definition at line 69 of file AutoptrVector.h.
Referenced by FESystemUtility::AutoPtrVector< NumericVector< double > >::reset(), and GmshOutputProcessor::writeNodalData().
        {
          Assert(this->vec != NULL, ExcInternalError());
          return this->vec->size();
        }
Member Data Documentation
template<typename T> std::vector<T*>* FESystemUtility::AutoPtrVector< T >::vec [protected]
the pointer of vector for this object
Definition at line 177 of file AutoptrVector.h.
Referenced by FESystemUtility::AutoPtrVector< NumericVector< double > >::AutoPtrVector(), FESystemUtility::AutoPtrVector< NumericVector< double > >::clear(), FESystemUtility::AutoPtrVector< NumericVector< double > >::get(), FESystemUtility::AutoPtrVector< NumericVector< double > >::getReference(), FESystemUtility::AutoPtrVector< NumericVector< double > >::operator[](), FESystemUtility::AutoPtrVector< NumericVector< double > >::push_back(), FESystemUtility::AutoPtrVector< NumericVector< double > >::release(), FESystemUtility::AutoPtrVector< NumericVector< double > >::reset(), FESystemUtility::AutoPtrVector< NumericVector< double > >::resize(), FESystemUtility::AutoPtrVector< NumericVector< double > >::size(), and FESystemUtility::AutoPtrVector< NumericVector< double > >::~AutoPtrVector().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Utilities/AutoptrVector.h