fesystem: FESystemDatabase::TransientDataInfoSet Class Reference
FESystemDatabase::TransientDataInfoSet Class Reference
#include <DataInfo.h>
Public Member Functions
TransientDataInfoSet ()
~TransientDataInfoSet ()
void clear ()
clears the data structures of this object
virtual const std::string getDisplayName () const
unsigned int getNDataInfo () const
void setOrder (const unsigned int order)
unsigned int getOrder () const
FESystemUtility::AutoPtrVector
< FESystemDatabase::TimeDependentDataInfo > getDataInfoForAllTimeSteps () const
void setTransientIterationTimeVector (const std::vector< double > &time_vals)
Protected Attributes
unsigned int derivative_order
derivative order of the solution
bool set_order
boolean to track if the derivative order was set
std::vector< double > time_values
vector of time values
Detailed Description
this is a class to define a set of solutions in a transient. It will create and return the DataInfoBase objects for the solutions in the set
Definition at line 414 of file DataInfo.h.
Constructor & Destructor Documentation
FESystemDatabase::TransientDataInfoSet::TransientDataInfoSet ()
Definition at line 984 of file DataInfo.C.
References clear().
                                                          :
  FESystemDatabase::GenericDataInfoBase(),
derivative_order(0)
{
  this->clear();
}
FESystemDatabase::TransientDataInfoSet::~TransientDataInfoSet ()
Definition at line 993 of file DataInfo.C.
{
  this->clear();
}
Member Function Documentation
void FESystemDatabase::TransientDataInfoSet::clear () [virtual]
clears the data structures of this object
Reimplemented from FESystemDatabase::GenericDataInfoBase.
Definition at line 1001 of file DataInfo.C.
References FESystemDatabase::GenericDataInfoBase::clear().
Referenced by TransientDataInfoSet().
{
  this->derivative_order = 0;
  this->set_order = false;
  this->time_values.clear();
  FESystemDatabase::GenericDataInfoBase::clear();
}
FESystemUtility::AutoPtrVector< FESystemDatabase::TimeDependentDataInfo > FESystemDatabase::TransientDataInfoSet::getDataInfoForAllTimeSteps () const
Definition at line 1039 of file DataInfo.C.
References info, n, FESystemUtility::AutoPtrVector< T >::reset(), FESystemDatabase::GenericDataInfoBase::setDisciplineEnumID(), FESystemDatabase::GenericDataInfoBase::setDVID(), FESystemDatabase::GenericDataInfoBase::setLoadCase(), FESystemDatabase::GenericDataInfoBase::setName(), FESystemDatabase::TimeDependentDataInfo::setOrder(), and FESystemDatabase::TimeDependentDataInfo::setTransientIterationInfo().
{
  unsigned int n = this->getNDataInfo();
  FESystemUtility::AutoPtrVector<FESystemDatabase::TimeDependentDataInfo>
    data_info_vec(n);
  FESystemDatabase::TimeDependentDataInfo *info=NULL;
  for (unsigned int i=0; i < n; i++)
    {
      info = new FESystemDatabase::TimeDependentDataInfo();
      info->setDisciplineEnumID(this->getDisciplineEnumID());
      info->setName(this->getName());
      if (this->ifLoadCaseDependent())
        info->setLoadCase(this->getLoadCase());
      if (this->ifSensitivityData())
        info->setDVID(this->getDVID());
      info->setTransientIterationInfo(i+1, this->time_values[i]);
      info->setOrder(this->getOrder());
      data_info_vec.reset(i, info);
      info = NULL;
    }
  return data_info_vec;
}
const std::string FESystemDatabase::TransientDataInfoSet::getDisplayName () const [virtual]
Implements FESystemDatabase::GenericDataInfoBase.
Definition at line 1082 of file DataInfo.C.
{
  std::string full_path_name = this->getName();
  // append the sensitivity information to the name
  if (this->ifSensitivityData())
    {
    std::ostringstream dv_id_oss;
    dv_id_oss << this->getDVID();
    full_path_name += "_SENS_DV_";
    full_path_name += dv_id_oss.str();
    }
  // append the load case information to the name
  if (this->ifLoadCaseDependent())
    {
    std::ostringstream lc_oss;
    lc_oss << this->getLoadCase();
    full_path_name += "_LC_";
    full_path_name += lc_oss.str();
    }
  return full_path_name;
}
unsigned int FESystemDatabase::TransientDataInfoSet::getNDataInfo () const
Definition at line 1029 of file DataInfo.C.
{
  Assert(this->time_values.size() > 0, ExcInternalError());
  return this->time_values.size();
}
unsigned int FESystemDatabase::TransientDataInfoSet::getOrder () const
Definition at line 1021 of file DataInfo.C.
{
  Assert(this->set_order, ExcInternalError());
  return this->derivative_order;
}
void FESystemDatabase::TransientDataInfoSet::setOrder (const unsigned int order)
Definition at line 1012 of file DataInfo.C.
Referenced by Solution::TransientStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::TransientThermalSolution::getTimeDependentNodalSolutionDataInfo(), and Solution::NonlinearStaticStructuralSolution::getTimeDependentNodalSolutionDataInfo().
{
  Assert(!this->set_order, ExcInternalError());
  this->derivative_order = i;
  this->set_order = true;
}
void FESystemDatabase::TransientDataInfoSet::setTransientIterationTimeVector (const std::vector< double > & time_vals)
Definition at line 1072 of file DataInfo.C.
Referenced by Solution::TransientStructuralSolution::getTimeDependentNodalSolutionDataInfo(), Solution::TransientThermalSolution::getTimeDependentNodalSolutionDataInfo(), and Solution::NonlinearStaticStructuralSolution::getTimeDependentNodalSolutionDataInfo().
{
  Assert(this->time_values.size() == 0, ExcInternalError());
  Assert(time_vals.size() > 0, ExcInternalError());
  this->time_values = time_vals;
}
Member Data Documentation
unsigned int FESystemDatabase::TransientDataInfoSet::derivative_order [protected]
derivative order of the solution
Definition at line 439 of file DataInfo.h.
bool FESystemDatabase::TransientDataInfoSet::set_order [protected]
boolean to track if the derivative order was set
Definition at line 442 of file DataInfo.h.
std::vector<double> FESystemDatabase::TransientDataInfoSet::time_values [protected]
vector of time values
Definition at line 445 of file DataInfo.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/DataInfo.C