fesystem: FESystemNumerics::PetscSeqDenseMatrix< T > Class Template Reference
FESystemNumerics::PetscSeqDenseMatrix< T > Class Template Reference
#include <PetscSeqDenseMatrix.h>
Public Member Functions
PetscSeqDenseMatrix (const unsigned int m=0, const unsigned int n=0)
constructor
PetscSeqDenseMatrix (const FESystemNumerics::PetscSeqDenseMatrix< T > &mat)
virtual ~PetscSeqDenseMatrix ()
virtual void copy (const FESystemNumerics::MatrixBase< T > &matrix)
virtual void leftMultiply (const FESystemNumerics::MatrixBase< T > &matrix)
virtual void leftMultiplyTranspose (const FESystemNumerics::MatrixBase< T > &matrix)
virtual void rightMultiply (const FESystemNumerics::MatrixBase< T > &matrix)
virtual void resize (const unsigned int m, const unsigned int n)
resize the matrix to the given dimensions
Detailed Description
template<typename T>
class FESystemNumerics::PetscSeqDenseMatrix< T >
this class provides a base class for different kinds of matrices
Definition at line 19 of file PetscSeqDenseMatrix.h.
Constructor & Destructor Documentation
template<typename T > FESystemNumerics::PetscSeqDenseMatrix< T >::PetscSeqDenseMatrix (const unsigned int m = 0, const unsigned int n = 0)
constructor
Definition at line 76 of file PetscSeqDenseMatrix.h.
References FESystemNumerics::PetscMatrixBase< T >::petsc_mat, and FESystemNumerics::PetscMatrixBase< T >::zero().
                                                                                   :
FESystemNumerics::PetscMatrixBase<T>()
{
  PetscErrorCode ierr=0;
  ierr = MatCreateSeqDense(PETSC_COMM_SELF,m,n,PETSC_NULL,&(this->petsc_mat));
  CHKERRABORT(PETSC_COMM_SELF, ierr);
  this->zero();
}
template<typename T > FESystemNumerics::PetscSeqDenseMatrix< T >::PetscSeqDenseMatrix (const FESystemNumerics::PetscSeqDenseMatrix< T > & mat)
Definition at line 91 of file PetscSeqDenseMatrix.h.
References FESystem::COMM_WORLD, and FESystemNumerics::PetscMatrixBase< T >::getMat().
                                                   :
FESystemNumerics::PetscMatrixBase<T>()
{
  PetscErrorCode ierr=0;
  ierr = MatDuplicate(mat.getMat(),MAT_COPY_VALUES, &(this->petsc_mat));
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > FESystemNumerics::PetscSeqDenseMatrix< T >::~PetscSeqDenseMatrix () [virtual]
Destructor. Empty.
Definition at line 102 of file PetscSeqDenseMatrix.h.
References FESystem::COMM_WORLD.
{
  PetscErrorCode ierr=0;
  ierr = MatDestroy(this->petsc_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
Member Function Documentation
template<typename T > void FESystemNumerics::PetscSeqDenseMatrix< T >::copy (const FESystemNumerics::MatrixBase< T > & matrix) [inline, virtual]
Copies to this matrix
Implements FESystemNumerics::MatrixBase< T >.
Definition at line 141 of file PetscSeqDenseMatrix.h.
References FESystem::COMM_WORLD, and FESystemNumerics::MatrixBase< T >::getMatrixPackage().
Referenced by RadiationCavityAnalysis::getFEJacobianMatrix().
{
  Assert(matrix.getMatrixPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  const FESystemNumerics::PetscMatrixBase<T>& mat =
    dynamic_cast<const FESystemNumerics::PetscMatrixBase<T>&>(matrix);
  const_cast<FESystemNumerics::PetscMatrixBase<T>&>(mat).finalAssemble();
  // create a temporary matrix to store the result in
  PetscErrorCode ierr = 0;
  ierr = MatDestroy(this->petsc_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = MatDuplicate(mat.getMat(),MAT_COPY_VALUES, &(this->petsc_mat));
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
template<typename T > void FESystemNumerics::PetscSeqDenseMatrix< T >::leftMultiply (const FESystemNumerics::MatrixBase< T > & matrix) [inline, virtual]
Performs the operation: (*this) <- M2 * (*this). This is reimplemented for the dense matrix class since it needs a different handling of one parameter
Reimplemented from FESystemNumerics::PetscMatrixBase< T >.
Definition at line 169 of file PetscSeqDenseMatrix.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscMatrixBase< T >::getMat(), and FESystemNumerics::MatrixBase< T >::getMatrixPackage().
Referenced by RadiationCavityAnalysis::getFEJacobianMatrix().
{
  Assert(matrix.getMatrixPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscMatrixBase<T>& mat =
    dynamic_cast<const FESystemNumerics::PetscMatrixBase<T>&>(matrix);
  const_cast<FESystemNumerics::PetscMatrixBase<T>&>(mat).finalAssemble();
  // create a temporary matrix to store the result in
  Mat result_mat;
  PetscErrorCode ierr = 0;
  ierr = MatMatMult (mat.getMat(), this->petsc_mat, MAT_INITIAL_MATRIX, 1.0,
                     &result_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // since Petsc will itself create the result matrix, we can destroy the matrix
  // of this object, and store the pointer of result_mat
  ierr = MatDestroy(this->petsc_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->petsc_mat = result_mat;
}
template<typename T > void FESystemNumerics::PetscSeqDenseMatrix< T >::leftMultiplyTranspose (const FESystemNumerics::MatrixBase< T > & matrix) [inline, virtual]
Performs the operation: (*this) <- M2^T * (*this). This is reimplemented for the dense matrix class since it needs a different handling of one parameter
Reimplemented from FESystemNumerics::PetscMatrixBase< T >.
Definition at line 213 of file PetscSeqDenseMatrix.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscMatrixBase< T >::getMat(), and FESystemNumerics::MatrixBase< T >::getMatrixPackage().
Referenced by RadiationCavityAnalysis::getFEJacobianMatrix().
{
  Assert(matrix.getMatrixPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscMatrixBase<T>& mat =
    dynamic_cast<const FESystemNumerics::PetscMatrixBase<T>&>(matrix);
  const_cast<FESystemNumerics::PetscMatrixBase<T>&>(mat).finalAssemble();
  // create a temporary matrix to store the result in
  Mat result_mat;
  PetscErrorCode ierr = 0;
  ierr = MatMatMultTranspose(mat.getMat(), this->petsc_mat,
                             MAT_INITIAL_MATRIX, 1.0, &result_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // since Petsc will itself create the result matrix, we can destroy the matrix
  // of this object, and store the pointer of result_mat
  ierr = MatDestroy(this->petsc_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->petsc_mat = result_mat;
}
template<typename T > void FESystemNumerics::PetscSeqDenseMatrix< T >::resize (const unsigned int m, const unsigned int n) [virtual]
resize the matrix to the given dimensions
Implements FESystemNumerics::PetscMatrixBase< T >.
Definition at line 114 of file PetscSeqDenseMatrix.h.
References FESystem::COMM_WORLD, and n.
Referenced by RadiationCavityAnalysis::calculateA_InverseMatrix(), RadiationCavityAnalysis::calculateA_Matrix(), RadiationCavityAnalysis::calculateB_InverseMatrix(), RadiationCavityAnalysis::calculateB_Matrix(), RadiationCavityAnalysis::calculateG_Matrix(), RadiationCavityAnalysis::calculateShapeFactorMatrix(), and Discipline::ThermalAnalysis::performAdditionalOperationsOnGlobalQuantities().
{
  if (this->m() == m && this->n() == n)
    {
    this->zero();
    return;
    }
  PetscErrorCode ierr=0;
  ierr = MatDestroy(this->petsc_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  ierr = MatCreateSeqDense(PETSC_COMM_SELF,m,n,PETSC_NULL,&(this->petsc_mat));
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->zero();
}
template<typename T > void FESystemNumerics::PetscSeqDenseMatrix< T >::rightMultiply (const FESystemNumerics::MatrixBase< T > & matrix) [inline, virtual]
Performs the operation: (*this) <- (*this) * M3. This is reimplemented for the dense matrix class since it needs a different handling of one parameter
Reimplemented from FESystemNumerics::PetscMatrixBase< T >.
Definition at line 258 of file PetscSeqDenseMatrix.h.
References FESystem::COMM_WORLD, FESystemNumerics::PetscMatrixBase< T >::getMat(), and FESystemNumerics::MatrixBase< T >::getMatrixPackage().
{
  Assert(matrix.getMatrixPackage() == FESystem::PETSC_PACKAGE::num(),
         ExcInternalError());
  switch (this->matrix_last_action)
    {
    case FESystemNumerics::PetscMatrixBase<T>::ADD:
    case FESystemNumerics::PetscMatrixBase<T>::INSERT:
    case FESystemNumerics::PetscMatrixBase<T>::FLUSH_ASSEMBLE:
      this->finalAssemble();
      break;
    case FESystemNumerics::PetscMatrixBase<T>::FINAL_ASSEMBLE:
      break;
    }
  const FESystemNumerics::PetscMatrixBase<T>& mat =
    dynamic_cast<const FESystemNumerics::PetscMatrixBase<T>&>(matrix);
  const_cast<FESystemNumerics::PetscMatrixBase<T>&>(mat).finalAssemble();
  // create a temporary matrix to store the result in
  Mat result_mat;
  PetscErrorCode ierr = 0;
  ierr = MatMatMult (this->petsc_mat, mat.getMat(), MAT_INITIAL_MATRIX, 1.0, &result_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  // since Petsc will itself create the result matrix, we can destroy the matrix
  // of this object, and store the pointer of result_mat
  ierr = MatDestroy(this->petsc_mat);
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->petsc_mat = result_mat;
}
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Numerics/PetscSeqDenseMatrix.h