fesystem: FEInterpolationAnalysis Class Reference
FEInterpolationAnalysis Class Reference
#include <FEInterpolationAnalysis.h>
Public Member Functions
FEInterpolationAnalysis (FESystem::FESystemController &controller, Discipline::InterpolationDisciplineInfo &info)
~FEInterpolationAnalysis ()
destructor
virtual bool sameSystemMatrixForLoadCases ()
returns if same system matrix can be used for all load cases
void initMatricesAndVectors ()
function will initialize the matrices and vectors for this anlysis
Protected Member Functions
virtual void addVariablesForAnalysis ()
function to add analysis variables
std::string getStringNameForQty (const unsigned int qty_enum_ID, bool sensitivity)
void getElemQty (const unsigned int qty_enum_ID, FESystemElem::FESystemElemBase *elem, std::vector< DenseMatrix< double > * > *qty_vector)
void getElemQty (const unsigned int qty_enum_ID, FESystemElem::FESystemElemBase *elem, std::vector< DenseVector< double > * > *qty_vector)
void calculateK (SparseMatrix< double > &, bool=false)
void calculateJac (SparseMatrix< double > &)
void calculateF (NumericVector< double > &, bool=false)
Detailed Description
This class provides methods to calculate the matrices and vectors related to the thermal discipline. this is a problem with this class. It adds a variable to the mesh/dofmap, in addition to the ones already added by the structural/thermal disciplines, hence distorts the dof numbering, etc. Hence, these variables should be added to an independent dofmap, without messing with the thermal/structural mesh. It basically needs a separate dofmap structure.
Definition at line 54 of file FEInterpolationAnalysis.h.
Constructor & Destructor Documentation
FEInterpolationAnalysis::FEInterpolationAnalysis (FESystem::FESystemController & controller, Discipline::InterpolationDisciplineInfo & info)
constructor. It takes two arguements, the arguement is a pointer to the AnalysisDriver that owns this object
Definition at line 31 of file FEInterpolationAnalysis.C.
                                                                                             :
Discipline::AnalysisDisciplineBase(controller, info)
{
}
FEInterpolationAnalysis::~FEInterpolationAnalysis ()
destructor
Definition at line 40 of file FEInterpolationAnalysis.C.
{
}
Member Function Documentation
void FEInterpolationAnalysis::addVariablesForAnalysis () [protected, virtual]
function to add analysis variables
Definition at line 46 of file FEInterpolationAnalysis.C.
References Discipline::AnalysisDisciplineBase::addVariable().
{
  FEType fetype(FIRST, LAGRANGE);
  // add a temperature variable to the analysis driver
  this->addVariable("Variable", fetype);
}
void FEInterpolationAnalysis::calculateF (NumericVector< double > & vector, bool sensitivity = false) [protected]
function to calculate the force vector. First arguement is the vector to store the result in, and the second arguement is a bool to tell the function if sensitivity is desired
Definition at line 181 of file FEInterpolationAnalysis.C.
References Discipline::AnalysisDisciplineBase::analysis_driver, Discipline::AnalysisDisciplineBase::calculateGlobalQty(), Discipline::AnalysisDisciplineBase::fesystem_controller, Driver::AnalysisDriver::getCurrentLoadCase(), getStringNameForQty(), and FESystem::FESystemController::global_data_storage.
{
  unsigned int load_case = this->analysis_driver->getCurrentLoadCase();
  // get the name by which the quantity will be referred
  std::string name = this->getStringNameForQty(Driver::FORCE_VECTOR::num(), sensitivity);
  // check if the vector exists in the database
  bool Force_vector_present =
    this->fesystem_controller.global_data_storage->checkIfVectorExists(load_case, name);
  // if not, calculate and save it
  if (! Force_vector_present)
    {
    unsigned int qty_enum_ID;
    if (!sensitivity)
      qty_enum_ID = Driver::FORCE_VECTOR::num();
    else
      qty_enum_ID = Driver::FORCE_VECTOR_SENSITIVITY::num();
    // calculate the matrix, save it and return
    this->calculateGlobalQty(vector, qty_enum_ID);
    this->fesystem_controller.global_data_storage->storeVector(load_case,name,vector);
    }
  else
    {
      // get the matrix from the database, and return
      this->fesystem_controller.global_data_storage->fillVector(load_case,name,vector);
    }
}
void FEInterpolationAnalysis::calculateJac (SparseMatrix< double > & matrix) [protected]
function to calculate the Jacobian matrix. First arguement is the matrix to store the result in
Definition at line 170 of file FEInterpolationAnalysis.C.
{
  // nothing to be done here since the analysis is not nonlinear
  abort();
}
void FEInterpolationAnalysis::calculateK (SparseMatrix< double > & matrix, bool sensitivity = false) [protected]
function to calculate the conductance matrix. First arguement is the matrix to store the result in, and the second arguement is a bool to tell the function if sensitivity is desired
Definition at line 134 of file FEInterpolationAnalysis.C.
References Discipline::AnalysisDisciplineBase::calculateGlobalQty(), Discipline::AnalysisDisciplineBase::fesystem_controller, getStringNameForQty(), and FESystem::FESystemController::global_data_storage.
{
  // get the name by which the quantity will be referred
  std::string name = this->getStringNameForQty(Driver::SYSTEM_MATRIX::num(), sensitivity);
  // check if the K matrix exists in the database
  // this matrix is independent of load case
  bool K_matrix_present =
    this->fesystem_controller.global_data_storage->checkIfMatrixExists(name);
  // if not, calculate and save it
  if (! K_matrix_present)
    {
    unsigned int qty_enum_ID;
    if (!sensitivity)
      qty_enum_ID = Driver::SYSTEM_MATRIX::num();
    else
      qty_enum_ID = Driver::SYSTEM_MATRIX_SENSITIVITY::num();
      // calculate the matrix, save it and return
      this->calculateGlobalQty(matrix, qty_enum_ID);
      this->fesystem_controller.global_data_storage->storeMatrix(name, matrix);
    }
  else
    {
    // get the matrix from the database, and return
    this->fesystem_controller.global_data_storage->fillMatrix(name, matrix);
    }
}
void FEInterpolationAnalysis::getElemQty (const unsigned int qty_enum_ID, FESystemElem::FESystemElemBase * elem, std::vector< DenseMatrix< double > * > * qty_vector) [protected]
function will fill the input vector with the element quantities required for the calculation of the specified global quantity. This is an abstract function and will be implemented in the derived class
Parameters:
global quantitiy
element pointer
vector in which the quantities will be added
Definition at line 280 of file FEInterpolationAnalysis.C.
References FORCE_VECTOR_ENUM_ID, FORCE_VECTOR_SENSITIVITY_ENUM_ID, FESystemElem::FESystemElemBase::getElementAssembledQty(), FESystemElem::FESystemElemBase::getElementAssembledQtySensitivity(), JACOBIAN_MATRIX_ENUM_ID, SYSTEM_MATRIX_ENUM_ID, and SYSTEM_MATRIX_SENSITIVITY_ENUM_ID.
{
  // make sure that valid pointer have been given
  assert (elem != NULL);
  assert (elem_data != NULL);
  static DenseMatrix<double> matrix;
  elem_data->clear();
  switch(qty)
    {
    case SYSTEM_MATRIX_ENUM_ID:
      {
        // get K matrix
        elem->getElementAssembledQty(FE_INTERPOLATION_ELEM_K_MATRIX::num(),
                                     &matrix);
        elem_data->push_back(&matrix);
      }
      break;
    case SYSTEM_MATRIX_SENSITIVITY_ENUM_ID:
      {
        // get K matrix sensitivity
        elem->getElementAssembledQtySensitivity(FE_INTERPOLATION_ELEM_K_MATRIX::num(),
                                                &matrix);
        elem_data->push_back(&matrix);
      }
      break;
    case JACOBIAN_MATRIX_ENUM_ID:
    case FORCE_VECTOR_ENUM_ID:
    case FORCE_VECTOR_SENSITIVITY_ENUM_ID:
    default:
      abort();
      break;
    }
}
void FEInterpolationAnalysis::getElemQty (const unsigned int qty_enum_ID, FESystemElem::FESystemElemBase * elem, std::vector< DenseVector< double > * > * qty_vector) [protected]
function will fill the input vector with the element quantities required for the calculation of the specified global quantity. This is an abstract function and will be implemented in the derived class
Parameters:
global quantitiy
element pointer
vector in which the quantities will be added
Definition at line 325 of file FEInterpolationAnalysis.C.
References FORCE_VECTOR_ENUM_ID, FORCE_VECTOR_SENSITIVITY_ENUM_ID, FESystemElem::FESystemElemBase::getElementAssembledQty(), FESystemElem::FESystemElemBase::getElementAssembledQtySensitivity(), JACOBIAN_MATRIX_ENUM_ID, SYSTEM_MATRIX_ENUM_ID, and SYSTEM_MATRIX_SENSITIVITY_ENUM_ID.
{
  // make sure that valid pointer have been given
  assert (elem != NULL);
  assert (elem_data != NULL);
  static DenseVector<double> vector;
  elem_data->clear();
  switch(qty)
    {
    case FORCE_VECTOR_ENUM_ID:
      {
        // get F
        elem->getElementAssembledQty(FE_INTERPOLATION_ELEM_F_VECTOR::num(),
                                     &vector);
        elem_data->push_back(&vector);
      }
      break;
    case FORCE_VECTOR_SENSITIVITY_ENUM_ID:
      {
        // get F  sensitivity
        elem->getElementAssembledQtySensitivity(FE_INTERPOLATION_ELEM_F_VECTOR::num(),
                                                &vector);
        elem_data->push_back(&vector);
      }
      break;
    case SYSTEM_MATRIX_ENUM_ID:
    case JACOBIAN_MATRIX_ENUM_ID:
    case SYSTEM_MATRIX_SENSITIVITY_ENUM_ID:
    default:
      abort();
      break;
    }
}
std::string FEInterpolationAnalysis::getStringNameForQty (const unsigned int qty_enum_ID, bool sensitivity) [protected]
function will return a string name for the quantity
Parameters:
quantity enum name
bool saying if the quantity is for sensitiivty or not
Definition at line 90 of file FEInterpolationAnalysis.C.
References Discipline::AnalysisDisciplineBase::analysis_driver, FORCE_VECTOR_ENUM_ID, Driver::AnalysisDriver::getCurrentDesignParameter(), DesignData::DesignParameter::getID(), JACOBIAN_MATRIX_ENUM_ID, and SYSTEM_MATRIX_ENUM_ID.
Referenced by calculateF(), and calculateK().
{
  std::string name;
  switch (qty_enum_ID)
    {
    case SYSTEM_MATRIX_ENUM_ID:
      name = "Interpolation_K_matrix";
      break;
    case FORCE_VECTOR_ENUM_ID:
      name = "Interpolation_F_vector";
      break;
    case JACOBIAN_MATRIX_ENUM_ID:
    default:
      abort();
      break;
    }
  if (!sensitivity)
    {
    return name;
    }
  if (sensitivity)
    {
    // if sensitivity is being calculated, the DV ID will be appended to the name of the quantity
    std::string sensitivity_name = "d";
      sensitivity_name += name;
      sensitivity_name += "_dDV_";
      std::ostringstream dv_ID;
      dv_ID << this->analysis_driver->getCurrentDesignParameter().getID();
      sensitivity_name += dv_ID.str();
      return sensitivity_name;
    }
}
void FEInterpolationAnalysis::initMatricesAndVectors ()
function will initialize the matrices and vectors for this anlysis
Definition at line 55 of file FEInterpolationAnalysis.C.
References Discipline::AnalysisDisciplineBase::analysis_driver, Discipline::AnalysisDisciplineBase::dof_map, Driver::AnalysisDriver::getMatrix(), and Driver::AnalysisDriver::getVector().
{
  // the dof map used here will be the one for the secondary mesh, which is the one
  // on which the variable has to be interpolated
  // hence, from the analysis case, get the interpolaton analysis mesh ID, and
  // from the analysis driver, get the analysis dof map.
  Assert(this->analysis_driver != NULL,
         ExcEmptyObject());
  unsigned int n_dofs = this->dof_map->n_dofs();
  // initialize the system matrix to the dof_map connectivity
  SparseMatrix<double>& system_matrix = this->analysis_driver->getMatrix("SystemMatrix");
  system_matrix.attach_dof_map(*(this->dof_map));
  system_matrix.init();
  NumericVector<double>& sol_vec = this->analysis_driver->getVector("Solution");
  NumericVector<double>& rhs_vec = this->analysis_driver->getVector("RHS");
  sol_vec.init(n_dofs);
  rhs_vec.init(n_dofs);
}
bool FEInterpolationAnalysis::sameSystemMatrixForLoadCases () [inline, virtual]
returns if same system matrix can be used for all load cases
Implements Discipline::AnalysisDisciplineBase.
Definition at line 128 of file FEInterpolationAnalysis.h.
References Discipline::AnalysisDisciplineBase::analysis_type_enum_ID, LINEAR_ANALYSIS_ENUM_ID, and NONLINEAR_ANALYSIS_ENUM_ID.
{
  switch (this->analysis_type_enum_ID)
    {
    case LINEAR_ANALYSIS_ENUM_ID:
      return true;
      break;
    case NONLINEAR_ANALYSIS_ENUM_ID:
      abort();
      break;
    default:
      abort();
      break;
    }
}
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Interpolation/FEInterpolationAnalysis.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Interpolation/FEInterpolationAnalysis.C