fesystem: Solver::FESystemSolverBase Class Reference
Solver::FESystemSolverBase Class Reference
#include <FESystemSolverBase.h>
Public Member Functions
FESystemSolverBase (const Solver::SolverInfo &info)
virtual ~FESystemSolverBase ()=0
destructor fuction
virtual void clear ()
unsigned int getSolverClassEnumID () const
returns the solver type
std::string getSolverClassEnumName () const
void attachAnalysisDriver (Driver::AnalysisDriver *driver)
Driver::AnalysisDriver & getAnalysisDriver ()
Protected Attributes
Driver::AnalysisDriver * analysis_driver
analysis driver pointer
unsigned int solver_class_enum_ID
Detailed Description
this class will provide an interface to various solution algorithms available in the solver package. It can also be used to create an algorithm that is unavailable in the solver package, and can still have a uniform interface through the class methods each solver object will need a set of matrices and vectors for the solution process, which will vary depending upon the solver type. Before each solver step, pointers to these matrices and vectors will have to be set.
Definition at line 46 of file FESystemSolverBase.h.
Constructor & Destructor Documentation
Solver::FESystemSolverBase::FESystemSolverBase (const Solver::SolverInfo & info)
creator function will need a pointer to the AnalysisDriver that owns the instantiation of this class.
Definition at line 27 of file FESystemSolverBase.C.
                                                                        :
analysis_driver(NULL),
solver_class_enum_ID(info.getSolverClassEnumID())
{
}
Solver::FESystemSolverBase::~FESystemSolverBase () [pure virtual]
destructor fuction
Definition at line 37 of file FESystemSolverBase.C.
{
}
Member Function Documentation
void Solver::FESystemSolverBase::attachAnalysisDriver (Driver::AnalysisDriver * driver)
Definition at line 51 of file FESystemSolverBase.C.
Referenced by Driver::AnalysisDriver::attachSolver().
{
  Assert(driver != NULL, ExcInternalError());
  this->analysis_driver = driver;
}
void Solver::FESystemSolverBase::clear () [virtual]
Reimplemented in Solver::ArpackEigenSolver, Solver::LinearSolver, Solver::NonlinearTransientSolverBase, Solver::NewmarkNonlinearTransientSolver, Solver::LinearTransientSolverBase, Solver::EulerNonlinearTransientSolver, Solver::SlepcEigenSolver, Solver::PetscNonlinearTransientSolver, Solver::PetscNonlinearSolver, Solver::EulerLinearTransientSolver, Solver::NewmarkLinearTransientSolver, Solver::TransientSolverBase, Solver::NonlinearSolver, Solver::PetscLinearSolver, and Solver::NewtonNonlinearSolver.
Definition at line 44 of file FESystemSolverBase.C.
Referenced by Solver::NonlinearSolver::clear(), Solver::TransientSolverBase::clear(), Solver::SlepcEigenSolver::clear(), Solver::LinearSolver::clear(), and Solver::ArpackEigenSolver::clear().
{
  this->analysis_driver = NULL;
}
Driver::AnalysisDriver & Solver::FESystemSolverBase::getAnalysisDriver ()
Definition at line 61 of file FESystemSolverBase.C.
Referenced by FESystemTransientSolverMonitor().
{
  Assert(this->analysis_driver != NULL, ExcInternalError());
  return *(this->analysis_driver);
}
unsigned int Solver::FESystemSolverBase::getSolverClassEnumID () const [inline]
returns the solver type
Definition at line 114 of file FESystemSolverBase.h.
References solver_class_enum_ID.
{
  return this->solver_class_enum_ID;
}
std::string Solver::FESystemSolverBase::getSolverClassEnumName () const [inline]
Definition at line 125 of file FESystemSolverBase.h.
{
  return Solver::SolverClassEnum::enumName(this->solver_class_enum_ID);
}
Member Data Documentation
Driver::AnalysisDriver* Solver::FESystemSolverBase::analysis_driver [protected]
analysis driver pointer
Definition at line 77 of file FESystemSolverBase.h.
Referenced by Solver::NewmarkSolver::getJacobian(), and Solver::NewmarkSolver::getResidual().
unsigned int Solver::FESystemSolverBase::solver_class_enum_ID [protected]
Definition at line 79 of file FESystemSolverBase.h.
Referenced by getSolverClassEnumID().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/FESystemSolverBase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/FESystemSolverBase.C