fesystem: Loads::NodalPointLoadCombination Class Reference
Loads::NodalPointLoadCombination Class Reference
#include <LoadCombination.h>
Public Member Functions
NodalPointLoadCombination ()
virtual ~NodalPointLoadCombination ()
virtual unsigned int getLoadClassEnumID () const
virtual void clear ()
unsigned int getNDofs () const
double getValue (const unsigned int i) const
virtual void addLoad (const double factor, const NodalLoad *load_ptr)
Protected Attributes
std::vector< double > values
Detailed Description
Definition at line 79 of file LoadCombination.h.
Constructor & Destructor Documentation
Loads::NodalPointLoadCombination::NodalPointLoadCombination () [inline]
Definition at line 82 of file LoadCombination.h.
                                 :
      NodalLoadCombination()
      {
      }
virtual Loads::NodalPointLoadCombination::~NodalPointLoadCombination () [inline, virtual]
Definition at line 87 of file LoadCombination.h.
      { }
Member Function Documentation
virtual void Loads::NodalPointLoadCombination::addLoad (const double factor, const NodalLoad * load_ptr) [inline, virtual]
Implements Loads::NodalLoadCombination.
Definition at line 113 of file LoadCombination.h.
References LoadBase::getLoadClassEnumID(), getNDofs(), Loads::NodalLoadCombination::getNodeID(), Loads::NodalLoadCombination::load_set, and values.
      {
        Assert(load_ptr != NULL, ExcInternalError());
        Assert(load_ptr->getLoadClassEnumID() == NODAL_POINT_LOAD::num(),
               ExcInternalError());
        const NodalPointLoad* ptr = dynamic_cast<const NodalPointLoad*>(load_ptr);
        // set the node ID
        if (this->load_set.size() == 0)
          {
            this->values.resize(ptr->getNDofs());
            for (unsigned int i=0; i < ptr->getNDofs(); i++)
              this->values[i] = 0.0;
          }
        else
          Assert(this->getNodeID() == ptr->getNodeID() &&
                 this->getNDofs() == ptr->getNDofs(), ExcInternalError());
        bool insert_success = this->load_set.insert(load_ptr).second;
        // add this pointer to the set, and adjust the value of the load
        Assert(insert_success, ExcInternalError());
        for (unsigned int i=0; i < this->getNDofs(); i++)
          this->values[i] += factor * ptr->getValue(i);
      }
virtual void Loads::NodalPointLoadCombination::clear () [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 95 of file LoadCombination.h.
References Loads::NodalLoadCombination::load_set, and values.
      {
        this->load_set.clear();
        this->values.clear();
      }
virtual unsigned int Loads::NodalPointLoadCombination::getLoadClassEnumID () const [inline, virtual]
Implements Loads::LoadCombinationBase.
Definition at line 90 of file LoadCombination.h.
      {
        return NODAL_POINT_LOAD::num();
      }
unsigned int Loads::NodalPointLoadCombination::getNDofs () const [inline]
Definition at line 101 of file LoadCombination.h.
References Loads::NodalLoadCombination::load_set, and Loads::NodalLoadCombination::nLoads().
Referenced by addLoad(), and getValue().
      {
        Assert(this->nLoads() > 0, ExcInternalError());
        return dynamic_cast<const NodalPointLoad*>(*this->load_set.begin())->getNDofs();
      }
double Loads::NodalPointLoadCombination::getValue (const unsigned int i) const [inline]
Definition at line 107 of file LoadCombination.h.
References getNDofs(), and values.
Referenced by Discipline::FluidAnalysis::performAdditionalOperationsOnGlobalQuantities(), and Discipline::StructuralAnalysis::performAdditionalOperationsOnGlobalQuantities().
      {
        Assert( i < this->getNDofs(), ExcInternalError());
        return this->values[i];
      }
Member Data Documentation
std::vector<double> Loads::NodalPointLoadCombination::values [protected]
Definition at line 143 of file LoadCombination.h.
Referenced by addLoad(), clear(), and getValue().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadCombination.h