fesystem: FESystemElem::FESystemElemBase Class Reference
FESystemElem::FESystemElemBase Class Reference
#include <FESystemElem.h>
Public Member Functions
FESystemElemBase (const unsigned int dim, const unsigned int elem_enum_ID, Discipline::AnalysisDisciplineBase &discipline)
virtual ~FESystemElemBase ()
unsigned int getID () const
unsigned int getNNodes ()
virtual unsigned int getNDofs ()=0
virtual unsigned int getTransientSystemOrder () const =0
unsigned int getFESystemElemTypeEnumID () const
const Elem * getElem (const unsigned int design_point_enum_ID) const
const std::string getFESystemElemTypeEnumName () const
returns the element enum ID
void reinit (const unsigned int elem_ID, Elem *elem, ElemDataCard *elem_data_card)
void reinitForShapeSensitivity (const unsigned int param_ID, Elem *perturb_elem, const double perturb_value)
void reinitForPropertySensitivity (const unsigned int param_ID)
reinitializes element for shape sensitivity
void clearInitialization ()
this method clears any previous initialization of the element.
void clearElemInitialization ()
this method clears the local data that has been created for various purposes
void clearSensitivityInitialization ()
this method clears any previous initialization of the element.
void setDofValues (std::vector< DenseVector< double > * > &dofs, std::vector< DenseVector< double > * > &dof_sens)
void setElementLoads (std::map< unsigned int, const Loads::VolumeLoadCombination * > *vol_loads, std::map< unsigned int, std::map< unsigned int, const Loads::SurfaceLoadCombination * > > *surf_loads, std::map< unsigned int, std::map< unsigned int, const Loads::NodalLoadCombination * > > *nod_loads, std::map< unsigned int, const Loads::VolumeLoadCombination * > *vol_load_sens, std::map< unsigned int, std::map< unsigned int, const Loads::SurfaceLoadCombination * > > *surf_load_sens, std::map< unsigned int, std::map< unsigned int, const Loads::NodalLoadCombination * > > *nod_load_sens)
virtual void getElementAssembledQty (const unsigned int name_enum_ID, DenseVector< double > *qty)=0
returns the assembled quantitiy for the element
virtual void getElementAssembledQty (const unsigned int name_enum_ID, DenseMatrix< double > *qty)=0
virtual void getElementAssembledQtySensitivity (const unsigned int name_enum_ID, DenseVector< double > *qty)=0
virtual void getElementAssembledQtySensitivity (const unsigned int name_enum_ID, DenseMatrix< double > *qty)=0
template<class QtyType >
void getFESystemElemQty (const unsigned int name_enum_ID, QtyType *qty, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily &family)
template<class QtyType >
void getFESystemElemQtyShapeSensitivity (const unsigned int name_enum_ID, QtyType *qty, const unsigned int domain_enum_ID, const FEFamily &family)
virtual std::auto_ptr
< ElemPostProcessQty > getElementPostProcessQty (std::vector< unsigned int > load_cases, std::vector< DesignData::DesignParameter * >design_variables)=0
double getElementMass (bool sensitivity)
calculates and returns the value of weight of the element
void clearLoadAndDofs ()
this clears the property element loads and dof values
void clearDofValues ()
clears the dof values that were set for the element
Protected Member Functions
void deleteElemLocalData (const unsigned int design_point_enum_ID)
deletes the local data for the element at the specified design point
virtual void getFETypes (std::vector< FEType > &fetypes)=0
virtual void getQuadratureRules (std::map< FEFamily, std::pair< QuadratureType, Order > > &quadratures)=0
inserts the quadrature rules to be used for the different elements
void initializeFEAndQuadratureDataStructures ()
initializes the set of elements to be used for this element
void calculateFESystemElemQty (DenseMatrix< double > *qty, const unsigned int name_enum_ID, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily &family)
void calculateFESystemElemQty (DenseVector< double > *qty, const unsigned int name_enum_ID, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily &family)
void calculateShapeFunctionFactors (DenseMatrix< double > *matrix, const unsigned int qty_name_enum_ID, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily &family)
void calculateShapeFunctionFactors (DenseVector< double > *vector, const unsigned int qty_name_enum_ID, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily &family)
unsigned int getSideNumberFromDomainEnum (const unsigned int side) const
unsigned int getDomainEnumFromSideNumber (unsigned int side) const
std::string getStringNameForFESystemElemQty (const unsigned int name_enum_ID, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily &family)
this function returns the name of the given quantity
std::string getStringNameForFESystemElemQtySensitivity (const unsigned int name_enum_ID, unsigned int DV_num, const unsigned int domain_enum_ID, const FEFamily &family)
this function returns the name of the sensitivity of the specified quantity
void calculateSurfaceNormal (DenseVector< double > *vector, const unsigned int design_point_enum_ID, const unsigned int side_enum_ID)
void calculate_T_matrix (DenseMatrix< double > *, const unsigned int design_point_enum_ID)
void initialize_element (const unsigned int design_point_enum_ID, const std::vector< Point > *=NULL)
void initialize_element_side (unsigned int, const unsigned int design_point_enum_ID)
initialized the element side given by the side number passed in the arguement
virtual void initPropertyCard ()=0
initializes the property cards for local parameters
virtual void clearPropertyCardInitialization ()=0
this clears the temperature initialization only for the property cards.
void create_local_elem (const unsigned int design_point_enum_ID)
void create_local_1D_elem (const unsigned int design_point_enum_ID)
this function creates a local element in 1-D space for line elements
void create_local_2D_elem (const unsigned int design_point_enum_ID)
this function creates a local element in 2-D space for quad or tri elements
DeclException0 (ExcInvalidElemGiven)
this exception is thrown when an invalid elem is called
Protected Attributes
Discipline::AnalysisDisciplineBase & analysis_discipline
the discipline that owns this element
const unsigned int dimension
dimension of the element
const unsigned int elem_type_enum_ID
enumID of the element kind
const unsigned int discipline_enumID
discipline of the element
unsigned int elem_ID
ID of the element.
unsigned int sensitivity_parameter_ID
ID of the sensitivity parameter.
unsigned int sensitivity_parameter
type of the sensitivity parameter
double perturbation
perturbation for a finite difference calculation
bool fe_quadrature_data_initialized
bool elem_is_initialized_for_property_sensitivity
boolean for keeping track of whether this element is initialized or not
bool property_card_initialized
boolean for keeping track of whether the property card was initialized
ElemDataCard * elem_property_card
card that stores the information for this element
ElementDataStorage * elem_data_storage
database for storing element quantities
std::map< unsigned int, const
Loads::VolumeLoadCombination * > * volume_loads
map of element loads
std::map< unsigned int,
std::map< unsigned int, const
Loads::SurfaceLoadCombination * > > * surface_loads
std::map< unsigned int,
std::map< unsigned int, const
Loads::NodalLoadCombination * > > * nodal_loads
std::map< unsigned int, const
Loads::VolumeLoadCombination * > * volume_load_sens
std::map< unsigned int,
std::map< unsigned int, const
Loads::SurfaceLoadCombination * > > * surface_load_sens
std::map< unsigned int,
std::map< unsigned int, const
Loads::NodalLoadCombination * > > * nodal_load_sens
std::map< unsigned int, Elem * > geometric_elems_for_DV_map
std::map< unsigned int, Elem * > local_elem_for_DV_map
std::map< unsigned int, Node ** > local_elem_nodes_for_DV_map
nodes created for the local element. These are stored for each DV
std::map< unsigned int, bool > elem_is_initialized_for_DV_map
std::map< unsigned int, bool > local_elem_is_initialized_for_DV_map
boolean for keeping track of whether this element is initialized or not
std::map< unsigned int, int > initialized_side_for_DV_map
keeps track of the initialized side that was initialized. This is stored for each design point.
std::vector< DenseVector
< double > > dof_values_vec
vector of element dof values
std::vector< DenseVector
< double > > dof_value_sensitivity_vec
vector of element dof values
std::map< unsigned int,
std::map< FEFamily, FEBase * > > fe_base_map_for_DV
finite element object for the element domain. This is stored for each design point.
std::map< unsigned int,
std::map< FEFamily, FEBase * > > fe_side_map_for_DV
finite element object for the side. This is stored for each design point.
std::map< unsigned int,
std::map< FEFamily, QBase * > > qbase_map_for_DV
quadrature rule for the element volume integration. This is stored for each design point.
std::map< unsigned int,
std::map< FEFamily, QBase * > > qbase_side_map_for_DV
quadrature rule for the side integration. This is stored for each design point.
Detailed Description
this is a finite element base class for elements that will know how to calculate their element quantities, like the stiffness, mass matrices, etc. and store them in the FESystem element data storage object.
Definition at line 448 of file FESystemElem.h.
Constructor & Destructor Documentation
FESystemElem::FESystemElemBase::FESystemElemBase (const unsigned int dim, const unsigned int elem_enum_ID, Discipline::AnalysisDisciplineBase & discipline)
constructor
Parameters:
pointer to the analysis driver that is controlling the sequence of operations
nodes created for the local element
boolean for keeping track of whether this element is initialized or not
boolean for keeping track of whether this element is initialized or not
keeps track of the initialized side that was initialized. This is stored for each design point.
finite element object for the element domain. This is stored for each design point.
finite element object for the side. This is stored for each design point.
quadrature rule for the element volume integration. This is stored for each design point.
quadrature rule for the side integration. This is stored for each design point.
Definition at line 50 of file FESystemElem.C.
                                              :
analysis_discipline(discipline),
dimension(dim),
elem_type_enum_ID(elem_enum_ID),
discipline_enumID(discipline.getDisciplineEnumID()),
elem_ID(FESystemNumbers::InvalidID),
sensitivity_parameter_ID(FESystemNumbers::InvalidID),
sensitivity_parameter(FESystemNumbers::InvalidID),
perturbation(0.0),
fe_quadrature_data_initialized(false),
elem_is_initialized_for_property_sensitivity(false),
property_card_initialized(false),
//elem_is_initialized_for_post_processing(false),
elem_property_card(NULL),
elem_data_storage(NULL),
volume_loads(NULL),
surface_loads(NULL),
nodal_loads(NULL),
volume_load_sens(NULL),
surface_load_sens(NULL),
nodal_load_sens(NULL)
{
  // set the element qty database
  this->elem_data_storage =
    this->analysis_discipline.getFESystemController().element_data_storage.get();
  // now initialize the maps
  // the global axis geometric elements
  this->geometric_elems_for_DV_map[FESystemElem::BASE_ELEM::num()] =
    NULL;
  this->geometric_elems_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] =
    NULL;
  // the local axis geometric elements
  this->local_elem_for_DV_map[FESystemElem::BASE_ELEM::num()] =
    NULL;
  this->local_elem_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] =
    NULL;
  /// nodes created for the local element
  this->local_elem_nodes_for_DV_map[FESystemElem::BASE_ELEM::num()] =
    NULL;
  this->local_elem_nodes_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] =
    NULL;
  /// boolean for keeping track of whether this element is initialized or not
  this->elem_is_initialized_for_DV_map[FESystemElem::BASE_ELEM::num()] =
    false;
  this->elem_is_initialized_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] =
    false;
  /// boolean for keeping track of whether this element is initialized or not
  this->local_elem_is_initialized_for_DV_map[FESystemElem::BASE_ELEM::num()] =
    false;
  this->local_elem_is_initialized_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] =
    false;
  /// keeps track of the initialized side that was initialized. This is stored for each design point.
  this->initialized_side_for_DV_map[FESystemElem::BASE_ELEM::num()] = -1;
  this->initialized_side_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] = -1;
  /// finite element object for the element domain. This is stored for each design point.
  this->fe_base_map_for_DV[FESystemElem::BASE_ELEM::num()] =
    std::map<FEFamily, FEBase*>();
  this->fe_base_map_for_DV[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] =
    std::map<FEFamily, FEBase*>();
  /// finite element object for the side. This is stored for each design point.
  this->fe_side_map_for_DV[FESystemElem::BASE_ELEM::num()] =
    std::map<FEFamily, FEBase*>();
  this->fe_side_map_for_DV[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] =
    std::map<FEFamily, FEBase*>();
  /// quadrature rule for the element volume integration. This is stored for each design point.
  this->qbase_map_for_DV[FESystemElem::BASE_ELEM::num()] =
    std::map<FEFamily, QBase*>();
  this->qbase_map_for_DV[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] =
    std::map<FEFamily, QBase*>();
  /// quadrature rule for the side integration. This is stored for each design point.
  this->qbase_side_map_for_DV[FESystemElem::BASE_ELEM::num()] =
    std::map<FEFamily, QBase*>();
  this->qbase_side_map_for_DV[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] =
    std::map<FEFamily, QBase*>();
//  /// vector of JxW for all quadrature points on the volume of this element.
//  /// This is stored for each design point.
//  this->JxW_map_for_DV[FESystemElem::BASE_ELEM::num()] =
//    std::map<FEFamily, QBase*>();
//  this->JxW_map_for_DV[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] =
//    std::map<FEFamily, QBase*>();
//  std::map<unsigned int, std::map<FEFamily, std::vector<Real>*> > JxW_map_for_DV;
//
//  /// vector of shape functions for this element at all quadrature points.
//  /// This is stored for each design point.
//  std::map<unsigned int, std::map<FEFamily, std::vector<std::vector<Real> >*> > phi_map_for_DV;
//
//  /// vector of gradient of shape functions at all quadrature points.
//  /// This is stored for each design point.
//  std::map<unsigned int, std::map<FEFamily, std::vector<std::vector<RealGradient> >* > > dphi_map_for_DV;
//
//  /// vector of shape functions on the element side. This is stored for each design point.
//  std::map<unsigned int, std::map<FEFamily, std::vector<std::vector<Real> >* > > phi_face_map_for_DV;
//
//  /// vector of JxW on the element side. This is stored for each design point.
//  std::map<unsigned int, std::map<FEFamily, std::vector<Real>*> > JxW_face_map_for_DV;
}
FESystemElem::FESystemElemBase::~FESystemElemBase () [virtual]
destructor
Definition at line 163 of file FESystemElem.C.
References clearElemInitialization(), clearSensitivityInitialization(), deleteElemLocalData(), fe_base_map_for_DV, fe_side_map_for_DV, qbase_map_for_DV, and qbase_side_map_for_DV.
{
  // delete the elem only if it is not 3-D, since, in that case
  // the elem and local_elem pointers are same, and deleting the local
  // elem will delete elem, which will mess with mesh.
  this->clearSensitivityInitialization();
  this->clearElemInitialization();
  this->deleteElemLocalData(FESystemElem::BASE_ELEM::num());
  this->deleteElemLocalData(FESystemElem::BASE_PLUS_DELTA_ELEM::num());
  // now iterate over all the fe and qbase maps and delete the objects
  {
    std::map<unsigned int, std::map<FEFamily, FEBase*> >::iterator it, end;
    it = this->fe_base_map_for_DV.begin();
    end = this->fe_base_map_for_DV.end();
    std::map<FEFamily, FEBase*>::iterator fe_it, fe_end;
    for ( ; it != end; it++)
      {
      fe_it = it->second.begin();
      fe_end = it->second.end();
      for (; fe_it != fe_end; fe_it++)
        {if (fe_it->second != NULL) {delete fe_it->second; fe_it->second = NULL;}}
      }
    // now repeat the same for element sides
    it = this->fe_side_map_for_DV.begin();
    end = this->fe_side_map_for_DV.end();
    for ( ; it != end; it++)
      {
      fe_it = it->second.begin();
      fe_end = it->second.end();
      for (; fe_it != fe_end; fe_it++)
        {if (fe_it->second != NULL) {delete fe_it->second; fe_it->second = NULL;}}
      }
  }
  {
    std::map<unsigned int, std::map<FEFamily, QBase*> >::iterator it, end;
    it = this->qbase_map_for_DV.begin();
    end = this->qbase_map_for_DV.end();
    std::map<FEFamily, QBase*>::iterator qit, qend;
    for ( ; it != end; it++)
      {
      qit = it->second.begin();
      qend = it->second.end();
      for (; qit != qend; qit++)
        {if (qit->second != NULL) {delete qit->second; qit->second = NULL;}}
      }
    // now repeat the same for element sides
    it = this->qbase_side_map_for_DV.begin();
    end = this->qbase_side_map_for_DV.end();
    for ( ; it != end; it++)
      {
      qit = it->second.begin();
      qend = it->second.end();
      for (; qit != qend; qit++)
        {if (qit->second != NULL) {delete qit->second; qit->second = NULL;}}
      }
  }
}
Member Function Documentation
void FESystemElem::FESystemElemBase::calculate_T_matrix (DenseMatrix< double > * T_mat, const unsigned int design_point_enum_ID) [protected]
function to calculate and return the transformation matrix. the arguement will be resized and filled by the matrix entries. The transformation matrix is defined by the relation Q_ij = e_local_i . e_global_j, so that e_local_i = Q_ij . e_local_j
Definition at line 537 of file FESystemElem.C.
{
  assert (T_mat != NULL);
  // initialize the element if it is not already initialized
  if (!this->local_elem_is_initialized_for_DV_map[design_point_enum_ID])
      this->initialize_element(design_point_enum_ID);
  static Elem* local_elem;
  local_elem = this->geometric_elems_for_DV_map[design_point_enum_ID];
  static unsigned int n_nodes;
  n_nodes = this->getNNodes();
  switch (T_mat->m() + T_mat->n() - 2 * (n_nodes * 3))
    {
    case 0:
      {
        // keep going
      }
      break;
    default:
      T_mat->resize(n_nodes * 3, n_nodes * 3);
      break;
    }
  T_mat->zero();
  switch (local_elem->type())
    {
    case EDGE2:
      {
        const Point& point0 = local_elem->point(0);
        const Point& point1 = local_elem->point(1);
        //calculate the length
        static Point local_x, local_y, local_z, tmp_vector1;
        local_x.assign(point1 - point0); // this is the local x
        local_x = (local_x.unit());
        // choose a local y axis
        // if the local_x is parallel to the x-axis, then choose
        if ( fabs(Point(1.,0.,0.)*local_x - 1.0) <= 1.0e-12 )
          {
          // if this is true, then local-x and x are parallel
          // and choose y as the temp vector
          tmp_vector1.assign(Point(0.,1.,0.));
          }
        else
          {
          tmp_vector1.assign(Point(1.,0.,0.));
          }
        local_y.assign(local_x.cross(tmp_vector1));
        local_z.assign(local_x.cross(local_y));
        // now set the transformation matrix T_mat
        // the dofs are arranged as
        // (u1,u2,v1,v2,w1,w2,theta_x1,theta_x2,theta_y1,theta_y2,theta_z1,theta_z2)
        (*T_mat)(0,0) = local_x(0); (*T_mat)(0,2) = local_x(1); (*T_mat)(0,4) = local_x(2);
        (*T_mat)(1,1) = local_x(0); (*T_mat)(1,3) = local_x(1); (*T_mat)(1,5) = local_x(2);
        (*T_mat)(2,0) = local_y(0); (*T_mat)(2,2) = local_y(1); (*T_mat)(2,4) = local_y(2);
        (*T_mat)(3,1) = local_y(0); (*T_mat)(3,3) = local_y(1); (*T_mat)(3,5) = local_y(2);
        (*T_mat)(4,0) = local_z(0); (*T_mat)(4,2) = local_z(1); (*T_mat)(4,4) = local_z(2);
        (*T_mat)(5,1) = local_z(0); (*T_mat)(5,3) = local_z(1); (*T_mat)(5,5) = local_z(2);
      }
      break;
    case TRI3:
      {
        //get the three nodes of this elem
        const Point& point0 = local_elem->point(0);
        const Point& point1 = local_elem->point(1);
        const Point& point2 = local_elem->point(2);
        //calculate the position vectors from point 0
        static Point vector01, vector02, tmp_vector1, tmp_vector2,
          new_unit_vec_x, new_unit_vec_y, new_unit_vec_z;
        vector01.assign(point1 - point0);
        vector02.assign(point2 - point0);
        new_unit_vec_x = vector01.unit();
        tmp_vector1.assign(new_unit_vec_x.cross(vector02));
        tmp_vector2 = tmp_vector1.unit();
        new_unit_vec_y = tmp_vector2.cross(new_unit_vec_x);
        new_unit_vec_z = new_unit_vec_x.cross(new_unit_vec_y);
        // now set the transformation matrix T_mat
        (*T_mat)(0,0) = new_unit_vec_x(0); (*T_mat)(0,3) = new_unit_vec_x(1); (*T_mat)(0,6) = new_unit_vec_x(2);
        (*T_mat)(1,1) = new_unit_vec_x(0); (*T_mat)(1,4) = new_unit_vec_x(1); (*T_mat)(1,7) = new_unit_vec_x(2);
        (*T_mat)(2,2) = new_unit_vec_x(0); (*T_mat)(2,5) = new_unit_vec_x(1); (*T_mat)(2,8) = new_unit_vec_x(2);
        (*T_mat)(3,0) = new_unit_vec_y(0); (*T_mat)(3,3) = new_unit_vec_y(1); (*T_mat)(3,6) = new_unit_vec_y(2);
        (*T_mat)(4,1) = new_unit_vec_y(0); (*T_mat)(4,4) = new_unit_vec_y(1); (*T_mat)(4,7) = new_unit_vec_y(2);
        (*T_mat)(5,2) = new_unit_vec_y(0); (*T_mat)(5,5) = new_unit_vec_y(1); (*T_mat)(5,8) = new_unit_vec_y(2);
        (*T_mat)(6,0) = new_unit_vec_z(0); (*T_mat)(6,3) = new_unit_vec_z(1); (*T_mat)(6,6) = new_unit_vec_z(2);
        (*T_mat)(7,1) = new_unit_vec_z(0); (*T_mat)(7,4) = new_unit_vec_z(1); (*T_mat)(7,7) = new_unit_vec_z(2);
        (*T_mat)(8,2) = new_unit_vec_z(0); (*T_mat)(8,5) = new_unit_vec_z(1); (*T_mat)(8,8) = new_unit_vec_z(2);
      }
      break;
    case QUAD4:
      {
        //get the four nodes of this elem
        const Point& point0 = local_elem->point(0);
        const Point& point1 = local_elem->point(1);
        const Point& point2 = local_elem->point(2);
        const Point& point3 = local_elem->point(3);
        //calculate the position vectors from point 0
        static Point vector01, vector02, vector03, tmp_vector1, tmp_vector2,
          new_unit_vec_x, new_unit_vec_y, new_unit_vec_z;
        vector01.assign(point1 - point0);
        vector02.assign(point2 - point0);
        vector03.assign(point3 - point0);
        new_unit_vec_x = vector01.unit();
        tmp_vector1.assign(new_unit_vec_x.cross(vector03));
        tmp_vector2 = tmp_vector1.unit();
        new_unit_vec_y = tmp_vector2.cross(new_unit_vec_x);
        new_unit_vec_z = new_unit_vec_x.cross(new_unit_vec_y);
        (*T_mat)(0,0) = new_unit_vec_x(0); (*T_mat)(0,4) = new_unit_vec_x(1); (*T_mat)(0,8) = new_unit_vec_x(2);
        (*T_mat)(1,1) = new_unit_vec_x(0); (*T_mat)(1,5) = new_unit_vec_x(1); (*T_mat)(1,9) = new_unit_vec_x(2);
        (*T_mat)(2,2) = new_unit_vec_x(0); (*T_mat)(2,6) = new_unit_vec_x(1); (*T_mat)(2,10) = new_unit_vec_x(2);
        (*T_mat)(3,3) = new_unit_vec_x(0); (*T_mat)(3,7) = new_unit_vec_x(1); (*T_mat)(3,11) = new_unit_vec_x(2);
        (*T_mat)(4,0) = new_unit_vec_y(0); (*T_mat)(4,4) = new_unit_vec_y(1); (*T_mat)(4,8) = new_unit_vec_y(2);
        (*T_mat)(5,1) = new_unit_vec_y(0); (*T_mat)(5,5) = new_unit_vec_y(1); (*T_mat)(5,9) = new_unit_vec_y(2);
        (*T_mat)(6,2) = new_unit_vec_y(0); (*T_mat)(6,6) = new_unit_vec_y(1); (*T_mat)(6,10) = new_unit_vec_y(2);
        (*T_mat)(7,3) = new_unit_vec_y(0); (*T_mat)(7,7) = new_unit_vec_y(1); (*T_mat)(7,11) = new_unit_vec_y(2);
        (*T_mat)(8,0) = new_unit_vec_z(0); (*T_mat)(8,4) = new_unit_vec_z(1); (*T_mat)(8,8) = new_unit_vec_z(2);
        (*T_mat)(9,1) = new_unit_vec_z(0); (*T_mat)(9,5) = new_unit_vec_z(1); (*T_mat)(9,9) = new_unit_vec_z(2);
        (*T_mat)(10,2) = new_unit_vec_z(0); (*T_mat)(10,6) = new_unit_vec_z(1); (*T_mat)(10,10) = new_unit_vec_z(2);
        (*T_mat)(11,3) = new_unit_vec_z(0); (*T_mat)(11,7) = new_unit_vec_z(1); (*T_mat)(11,11) = new_unit_vec_z(2);
      }
      break;
    default:
      //nothing to be done if not a 1-D OR 2-D
      break;
    }
}
void FESystemElem::FESystemElemBase::calculateFESystemElemQty (DenseMatrix< double > * qty, const unsigned int name_enum_ID, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily & family) [protected]
this method is an interface to the specific functions to calculate element quantities. It calls the method that performs the calculations and returns the quantity in the first arguement.
Definition at line 1510 of file FESystemElem.C.
References N_N_FACTOR_ENUM_ID, N_X_N_FACTOR_ENUM_ID, N_X_N_X_FACTOR_ENUM_ID, N_X_N_Y_FACTOR_ENUM_ID, N_Y_N_FACTOR_ENUM_ID, N_Y_N_Y_FACTOR_ENUM_ID, N_Y_N_Z_FACTOR_ENUM_ID, N_Z_N_FACTOR_ENUM_ID, N_Z_N_X_FACTOR_ENUM_ID, N_Z_N_Z_FACTOR_ENUM_ID, and TRANSFORM_MATRIX_ENUM_ID.
{
  assert (qty != NULL);
  switch(name)
    {
    case  TRANSFORM_MATRIX_ENUM_ID:
      {
        this->calculate_T_matrix(qty, design_point_enum_ID);
      }
      break;
    case  N_N_FACTOR_ENUM_ID:
    case  N_X_N_X_FACTOR_ENUM_ID:
    case  N_Y_N_Y_FACTOR_ENUM_ID:
    case  N_Z_N_Z_FACTOR_ENUM_ID:
    case  N_X_N_Y_FACTOR_ENUM_ID:
    case  N_Y_N_Z_FACTOR_ENUM_ID:
    case  N_Z_N_X_FACTOR_ENUM_ID:
    case  N_X_N_FACTOR_ENUM_ID:
    case  N_Y_N_FACTOR_ENUM_ID:
    case  N_Z_N_FACTOR_ENUM_ID:
      {
        this->calculateShapeFunctionFactors(qty, name, design_point_enum_ID, domain, family);
      }
      break;
    default:
      abort();
      break;
    }
}
void FESystemElem::FESystemElemBase::calculateFESystemElemQty (DenseVector< double > * qty, const unsigned int name_enum_ID, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily & family) [protected]
this method is an interface to the specific functions to calculate element quantities. It calls the method that performs the calculations and returns the quantity in the first arguement.
Definition at line 1553 of file FESystemElem.C.
References N_FACTOR_ENUM_ID, and SURFACE_NORMAL_ENUM_ID.
{
  assert (quantity != NULL);
  switch(qty_name)
    {
    case  SURFACE_NORMAL_ENUM_ID:
      {
        this->calculateSurfaceNormal(quantity, design_point_enum_ID, domain);
      }
      break;
    case N_FACTOR_ENUM_ID:
      {
        this->calculateShapeFunctionFactors(quantity, qty_name, design_point_enum_ID,
                                            domain, family);
      }
      break;
    default:
      abort();
      break;
    }
}
void FESystemElem::FESystemElemBase::calculateShapeFunctionFactors (DenseMatrix< double > * matrix, const unsigned int qty_name_enum_ID, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily & family) [protected]
this method calculates the quantities based on the shape functions and returns it in the first arguement
Definition at line 706 of file FESystemElem.C.
References ELEM_VOLUME_ENUM_ID, N_N_FACTOR_ENUM_ID, N_X_N_FACTOR_ENUM_ID, N_X_N_X_FACTOR_ENUM_ID, N_X_N_Y_FACTOR_ENUM_ID, N_Y_N_FACTOR_ENUM_ID, N_Y_N_Y_FACTOR_ENUM_ID, N_Y_N_Z_FACTOR_ENUM_ID, N_Z_N_FACTOR_ENUM_ID, N_Z_N_X_FACTOR_ENUM_ID, N_Z_N_Z_FACTOR_ENUM_ID, SIDE_FIVE_ENUM_ID, SIDE_FOUR_ENUM_ID, SIDE_ONE_ENUM_ID, SIDE_THREE_ENUM_ID, SIDE_TWO_ENUM_ID, and SIDE_ZERO_ENUM_ID.
{
  assert (matrix != NULL);
  // also, make sure that the family exists in the map. It is assumed that
  // if this family exists in one map, then it should exist in all maps in this elem.
  Assert(this->fe_base_map_for_DV[design_point_enum_ID].find(family)
         != this->fe_base_map_for_DV[design_point_enum_ID].end(),
         ExcInternalError());
  if (!this->local_elem_is_initialized_for_DV_map[design_point_enum_ID])
    this->initialize_element(design_point_enum_ID);
  // this needs to be called after the function has been initialized
  static unsigned int n_shape_funcs;
  n_shape_funcs =
    this->fe_base_map_for_DV[design_point_enum_ID][family]->n_shape_functions();
  if (matrix->m() + matrix->n() != 2 * n_shape_funcs)
    matrix->resize(n_shape_funcs, n_shape_funcs);
  matrix->zero();
  // phi is the quantity that will store the
  static FEBase *fe_base_local;
  static QBase *qbase_local;
  fe_base_local = NULL;
  qbase_local = NULL;
  static Elem* local_elem;
  local_elem = this->local_elem_for_DV_map[design_point_enum_ID];
  // initialize the element if it is not already initialized
  switch(domain)
    {
    case ELEM_VOLUME_ENUM_ID:
      {
        // now init the fe and quadrature pointers
        switch (local_elem->dim())
          {
          case 1:
            {
              // nothing to be done here, since the quantities have
              // been calculated explicitly
            }
            break;
          case 2:
          case 3:
            {
              fe_base_local = this->fe_base_map_for_DV[design_point_enum_ID][family];
              qbase_local = this->qbase_map_for_DV[design_point_enum_ID][family];
            }
            break;
          default:
            abort();
            break;
          }
      }
      break;
    case SIDE_ZERO_ENUM_ID:
    case SIDE_ONE_ENUM_ID:
    case SIDE_TWO_ENUM_ID:
    case SIDE_THREE_ENUM_ID:
    case SIDE_FOUR_ENUM_ID:
    case SIDE_FIVE_ENUM_ID:
      {
        unsigned int elem_side =
        this->getSideNumberFromDomainEnum(domain);
        // now init the fe and quadrature pointers
        switch (local_elem->dim())
          {
          case 1:
            {
              // this does not need to be set, since it
              // can be explicitly evaluated for a 1-D element
            }
            break;
          case 2:
          case 3:
            {
              this->initialize_element_side(elem_side,
                                            design_point_enum_ID);
              fe_base_local = this->fe_side_map_for_DV[design_point_enum_ID][family];
              qbase_local = this->qbase_side_map_for_DV[design_point_enum_ID][family];
            }
            break;
          default:
            abort();
            break;
          }
      }
      break;
    default:
      abort();
      break;
    }
  // phi_1 and phi_2 are the quantities that will store the
  // the shape functions or their derivatives for calculation purposes
  const std::vector<std::vector<Real> > *phi_1 = NULL, *phi_2 = NULL;
  const std::vector<Real>* JxW = NULL;
  unsigned int n_quad_points= 0;
  switch(local_elem->dim())
    {
    case 1:
      {
        const Point& point0 = local_elem->point(0);
        const Point& point1 = local_elem->point(1);
        static Point vec;
        vec = point1;
        vec -= point0;
        double length = vec.size();
        // set the entries in the matrix and return
        switch (qty_name)
          {
          case N_X_N_X_FACTOR_ENUM_ID:
            {
              switch (local_elem->type())
                {
                case EDGE2:
                  {
                    (*matrix)(0,0) = 1.0;   (*matrix)(0,1) = -1.0;
                    (*matrix)(1,0) = -1.0;   (*matrix)(1,1) = 1.0;
                    switch(domain)
                      {
                      case ELEM_VOLUME_ENUM_ID:
{
                          matrix->scale(1.0 / length);
                        }
                        break;
                      case SIDE_ZERO_ENUM_ID:
                      case SIDE_ONE_ENUM_ID:
{
                          matrix->scale(1.0  / length / length);
                        }
                        break;
                      default:
                        abort();
                        break;
                      }
                  }
                  break;
                case EDGE3:
                  {
                    // has not been implemented yet.
                    abort();
                  }
                  break;
                default:
                  abort();
                  break;
                }
            }
            break;
          case N_X_N_FACTOR_ENUM_ID:
            {
              switch (local_elem->type())
                {
                case EDGE2:
                  {
                    switch(domain)
                      {
                      case ELEM_VOLUME_ENUM_ID:
{
                          (*matrix)(0,0) = -0.5;   (*matrix)(0,1) = -0.5;
                          (*matrix)(1,0) = 0.5;   (*matrix)(1,1) = 0.5;
                        }
                        break;
                      case SIDE_ZERO_ENUM_ID:
{
                          (*matrix)(0,0) = -1.0;   (*matrix)(0,1) = 0.0;
                          (*matrix)(1,0) = 1.0;   (*matrix)(1,1) = 0.0;
                          matrix->scale(1.0 / length);
                        }
                        break;
                      case SIDE_ONE_ENUM_ID:
{
                          (*matrix)(0,0) = 0.0;   (*matrix)(0,1) = -1.0;
                          (*matrix)(1,0) = 0.0;   (*matrix)(1,1) = 1.0;
                          matrix->scale(1.0 / length);
                        }
                        break;
                      default:
                        abort();
                        break;
                      }
                  }
                  break;
                case EDGE3:
                  {
                    // has not been implemented yet.
                    abort();
                  }
                  break;
                default:
                  abort();
                  break;
                }
            }
            break;
          case N_N_FACTOR_ENUM_ID:
            {
              switch (local_elem->type())
                {
                case EDGE2:
                  {
                    switch(domain)
                      {
                      case ELEM_VOLUME_ENUM_ID:
{
                          (*matrix)(0,0) = 2.0/3.0; (*matrix)(0,1) = 1.0/3.0;
                          (*matrix)(1,0) = 1.0/3.0; (*matrix)(1,1) = 2.0/3.0;
                          matrix->scale(0.5 * length);
                        }
                        break;
                      case SIDE_ZERO_ENUM_ID:
{
                          (*matrix)(0,0) = 1.0;
                        }
                        break;
                      case SIDE_ONE_ENUM_ID:
{
                          (*matrix)(1,1) = 1.0;
                        }
                        break;
                      default:
                        abort();
                        break;
                      }
                  }
                  break;
                case EDGE3:
                  {
                    // has not been implemented yet.
                    abort();
                  }
                  break;
                default:
                  abort();
                  break;
                }
            }
            break;
          case N_Y_N_Y_FACTOR_ENUM_ID:
          case N_Z_N_Z_FACTOR_ENUM_ID:
          case N_X_N_Y_FACTOR_ENUM_ID:
          case N_Y_N_Z_FACTOR_ENUM_ID:
          case N_Z_N_X_FACTOR_ENUM_ID:
          case N_Y_N_FACTOR_ENUM_ID:
          case N_Z_N_FACTOR_ENUM_ID:
          default:
            abort();
            break;
          }
        // now we return since for 1-D, nothing else needs to be done.
        return;
      }
      break;
    case 2:
    case 3:
      {
        // phi_1 and phi_2 are the quantities that will store the
        // the shape functions or their derivatives for calculation purposes
        JxW = &(fe_base_local->get_JxW());
        n_quad_points= qbase_local->n_points();
        switch (qty_name)
          {
          case N_X_N_X_FACTOR_ENUM_ID:
            {
              phi_1 = &(fe_base_local->get_dphidx());
              phi_2 = &(fe_base_local->get_dphidx());
            }
            break;
          case N_Y_N_Y_FACTOR_ENUM_ID:
            {
              phi_1 =  &(fe_base_local->get_dphidy());
              phi_2 =  &(fe_base_local->get_dphidy());
            }
            break;
          case N_Z_N_Z_FACTOR_ENUM_ID:
            {
              phi_1 =  &(fe_base_local->get_dphidz());
              phi_2 =  &(fe_base_local->get_dphidz());
            }
            break;
          case N_X_N_Y_FACTOR_ENUM_ID:
            {
              phi_1 =  &(fe_base_local->get_dphidx());
              phi_2 =  &(fe_base_local->get_dphidy());
            }
            break;
          case N_Y_N_Z_FACTOR_ENUM_ID:
            {
              phi_1 =  &(fe_base_local->get_dphidy());
              phi_2 =  &(fe_base_local->get_dphidz());
            }
            break;
          case N_Z_N_X_FACTOR_ENUM_ID:
            {
              phi_1 =  &(fe_base_local->get_dphidz());
              phi_2 =  &(fe_base_local->get_dphidx());
            }
            break;
          case N_X_N_FACTOR_ENUM_ID:
            {
              phi_1 = &(fe_base_local->get_dphidx());
              phi_2 = &(fe_base_local->get_phi());
            }
            break;
          case N_Y_N_FACTOR_ENUM_ID:
            {
              phi_1 = &(fe_base_local->get_dphidy());
              phi_2 = &(fe_base_local->get_phi());
            }
            break;
          case N_Z_N_FACTOR_ENUM_ID:
            {
              phi_1 = &(fe_base_local->get_dphidz());
              phi_2 = &(fe_base_local->get_phi());
            }
            break;
          case N_N_FACTOR_ENUM_ID:
            {
              phi_1 = &(fe_base_local->get_phi());
              phi_2 = &(fe_base_local->get_phi());
            }
            break;
          default:
            abort();
            break;
          }
      }
      break;
    default:
      abort();
      break;
    }
  for (unsigned int qp=0; qp<n_quad_points; qp++)
    for (unsigned int i=0; i<n_shape_funcs; i++)
      for (unsigned int j=0; j<n_shape_funcs; j++)
        (*matrix)(i,j) += (*JxW)[qp] * (*phi_1)[i][qp] * (*phi_2)[j][qp];
}
void FESystemElem::FESystemElemBase::calculateShapeFunctionFactors (DenseVector< double > * vector, const unsigned int qty_name_enum_ID, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily & family) [protected]
this method calculates the quantities based on the shape functions and returns it in the first arguement
Definition at line 1110 of file FESystemElem.C.
References ELEM_VOLUME_ENUM_ID, N_FACTOR_ENUM_ID, SIDE_FIVE_ENUM_ID, SIDE_FOUR_ENUM_ID, SIDE_ONE_ENUM_ID, SIDE_THREE_ENUM_ID, SIDE_TWO_ENUM_ID, and SIDE_ZERO_ENUM_ID.
{
  assert (vector != NULL);
  // also, make sure that the family exists in the map. It is assumed that
  // if this family exists in one map, then it should exist in all maps in this elem.
  Assert(this->fe_base_map_for_DV[design_point_enum_ID].find(family)
         != this->fe_base_map_for_DV[design_point_enum_ID].end(),
         ExcInternalError());
 if (!this->local_elem_is_initialized_for_DV_map[design_point_enum_ID])
   this->initialize_element(design_point_enum_ID);
  // this needs to be called after the function has been initialized
  static unsigned int n_shape_funcs;
  n_shape_funcs =
    this->fe_base_map_for_DV[design_point_enum_ID][family]->n_shape_functions();
  if (vector->size() != n_shape_funcs)
    vector->resize(n_shape_funcs);
        vector->zero();
  // phi is the quantity that will store the
  static FEBase *fe_base_local;
  static QBase *qbase_local;
  fe_base_local = NULL;
  qbase_local = NULL;
  static Elem* local_elem;
  local_elem = this->local_elem_for_DV_map[design_point_enum_ID];
  // initialize the element if it is not already initialized
  switch(domain)
    {
    case ELEM_VOLUME_ENUM_ID:
      {
        // now init the fe and quadrature pointers
        switch (local_elem->dim())
          {
          case 1:
            {
              // nothing to be done here, since the quantities have
              // been calculated explicitly
            }
            break;
          case 2:
          case 3:
            {
              fe_base_local = this->fe_base_map_for_DV[design_point_enum_ID][family];
              qbase_local = this->qbase_map_for_DV[design_point_enum_ID][family];
            }
            break;
          default:
            abort();
            break;
          }
      }
      break;
    case SIDE_ZERO_ENUM_ID:
    case SIDE_ONE_ENUM_ID:
    case SIDE_TWO_ENUM_ID:
    case SIDE_THREE_ENUM_ID:
    case SIDE_FOUR_ENUM_ID:
    case SIDE_FIVE_ENUM_ID:
      {
        unsigned int elem_side =
        this->getSideNumberFromDomainEnum(domain);
        // now init the fe and quadrature pointers
        switch (local_elem->dim())
          {
          case 1:
            {
              // this does not need to be set, since it
              // can be explicitly evaluated for a 1-D element
            }
            break;
          case 2:
          case 3:
            {
              this->initialize_element_side(elem_side,
                                            design_point_enum_ID);
              fe_base_local = this->fe_side_map_for_DV[design_point_enum_ID][family];
              qbase_local = this->qbase_side_map_for_DV[design_point_enum_ID][family];
            }
            break;
          default:
            abort();
            break;
          }
      }
      break;
    default:
      abort();
      break;
    }
  const std::vector<std::vector<Real> > *phi = NULL;
  const std::vector<Real>* JxW = NULL;
  unsigned int n_quad_points= 0;
  switch(local_elem->dim())
    {
    case 1:
      {
        const Point& point0 = local_elem->point(0);
        const Point& point1 = local_elem->point(1);
        static Point vec;
        vec = point1;
        vec -= point0;
        double length = vec.size();
        // set the entries in the matrix and return
        switch (qty_name)
          {
          case N_FACTOR_ENUM_ID:
            {
              switch (local_elem->type())
                {
                case EDGE2:
                  {
                    switch(domain)
                      {
                      case ELEM_VOLUME_ENUM_ID:
{
                          (*vector)(0) = 0.5 * length;
                          (*vector)(1) = 0.5 * length;
                        }
                        break;
                      case SIDE_ZERO_ENUM_ID:
{
                          (*vector)(0) = 1.0;
                        }
                        break;
                      case SIDE_ONE_ENUM_ID:
{
                          (*vector)(1) = 1.0;
                        }
                        break;
                      default:
                        abort();
                        break;
                      }
                  }
                  break;
                case EDGE3:
                  {
                    // has not been implemented yet.
                    abort();
                  }
                  break;
                default:
                  abort();
                  break;
                }
            }
            break;
          default:
            abort();
            break;
          }
        // now we return since for 1-D, nothing else needs to be done.
        return;
      }
      break;
    case 2:
    case 3:
      {
        JxW = &(fe_base_local->get_JxW());
        n_quad_points= qbase_local->n_points();
        switch (qty_name)
          {
          case N_FACTOR_ENUM_ID:
            {
              phi = &(fe_base_local->get_phi());
            }
            break;
          default:
            abort();
            break;
          }
      }
      break;
    default:
      abort();
      break;
    }
  for (unsigned int qp=0; qp<n_quad_points; qp++)
    for (unsigned int i=0; i<n_shape_funcs; i++)
      {
      (*(vector))(i) += (*JxW)[qp] * (*phi)[i][qp];
      }
}
void FESystemElem::FESystemElemBase::calculateSurfaceNormal (DenseVector< double > * vector, const unsigned int design_point_enum_ID, const unsigned int side_enum_ID) [protected]
this function caluclates the surface normal for the element side
Parameters:
vector vector in which the normal will be returned
side side for which the normal has to be calculated
Definition at line 1343 of file FESystemElem.C.
{
  // the normal will be calculated for a side of the local_elem
  // get a pointer to the local elem, and
  // initialize the element if it is not already initialized
  if (!this->local_elem_is_initialized_for_DV_map[design_point_enum_ID])
      this->initialize_element(design_point_enum_ID);
  // this needs to be called after the function has been initialized
  switch (vector->size())
    {
    case 3:
      {
        // keep going
      }
      break;
    default:
      vector->resize(3);
      break;
    }
        vector->zero();
  static bool load_on_elem_face;
  load_on_elem_face = false;
  unsigned int side_num =
    this->getSideNumberFromDomainEnum(domain);
  static Point normal;
  normal.zero();
  static Elem* local_elem;
  local_elem = this->local_elem_for_DV_map[design_point_enum_ID];
  Assert(side_num <= local_elem->n_sides(),
         ExcInternalError());
  switch (local_elem->n_sides() - side_num)
    {
    case 0:
      // then the load is on the element face of a quad element
      load_on_elem_face = true;
      break;
    default:
      {
        // nothing to be done, since the load is not on elem face
      }
    }
  switch (local_elem->dim())
    {
    case 1:
      {
        // calculate the vector along the length of the element from 0->1
        const Point& point0 = local_elem->point(0);
        const Point& point1 = local_elem->point(1);
        static Point vector01;
        vector01.assign(point1 - point0);
        normal.assign(vector01.unit());
        switch (side_num)
          {
          case 0:
            {
              // scale the vector by -1.0
              normal *= -1.0;
            }
            break;
          case 1:
            break;
          default:
            libmesh_error();
            break;
          }
      }
      break;
    case 2:
      {
        switch (load_on_elem_face)
          {
          case true:
            {
              // calculate the vector along 0->1 and 0->2. The cross product of these two will give the
              // surface normal
              const Point& point0 = local_elem->point(0);
              const Point& point1 = local_elem->point(1);
              const Point& point2 = local_elem->point(2);
              //calculate the position vectors from point 0
              static Point vector01, vector02, tmp_vector;
              vector01.assign(point1 - point0);
              vector02.assign(point2 - point0);
              // calculate the cross product and scale it by the side (for +ve or -ve)
              tmp_vector.assign(vector01.cross(vector02));
              normal.assign(tmp_vector.unit());
            }
            break;
          case false:
          default:
            {
              // calculate the vector along the length of this side
              // the surface normal will be the cross-product of this vector with the z-vector
              // calculate the vector along the length of the element from 0->1
              std::auto_ptr<Elem> side_elem(local_elem->build_side(side_num).release());
              const Point& point0 = side_elem->point(0);
              const Point& point1 = side_elem->point(1);
              static Point vector01, z_vector, tmp_vector;
              z_vector.zero();
              z_vector(2) =  1.0;
              vector01.assign(point1 - point0);
              tmp_vector.assign(vector01.cross(z_vector));
              normal.assign(tmp_vector.unit());
            }
            break;
          }
      }
      break;
    case 3:
      {
        // get the side of this element, and follow the same procedure as the one for load_on_face
        std::auto_ptr<Elem> side_elem(local_elem->build_side(side_num).release());
        const Point& point0 = side_elem->point(0);
        const Point& point1 = side_elem->point(1);
        const Point& point2 = side_elem->point(2);
        //calculate the position vectors from point 0
        static Point vector01, vector02, tmp_vector;
        vector01.assign(point1 - point0);
        vector02.assign(point2 - point0);
        // calculate the cross product and scale it by the side (for +ve or -ve)
        tmp_vector.assign(vector01.cross(vector02));
        normal.assign(tmp_vector.unit());
      }
      break;
    }
  // now copy the normal vector components
  for (unsigned int i=0; i<3; i++)
    (*vector)(i)  = normal(i);
}
void FESystemElem::FESystemElemBase::clearDofValues () [inline]
clears the dof values that were set for the element
Definition at line 1329 of file FESystemElem.h.
Referenced by Discipline::FluidAnalysis::getElemQty(), and Discipline::StructuralAnalysis::getElemQty().
{
  for (unsigned int i=0; i <= this->getTransientSystemOrder(); i++)
    {
    this->dof_values_vec[i].zero();
    this->dof_value_sensitivity_vec[i].zero();
    }
}
void FESystemElem::FESystemElemBase::clearElemInitialization () [inline]
this method clears the local data that has been created for various purposes
Definition at line 1342 of file FESystemElem.h.
References FESystemNumbers::InvalidID.
Referenced by ~FESystemElemBase().
{
  // the necessary flags are set, so that the element will have to be reinitialized
  // for any sort of calculation
  this->elem_ID = FESystemNumbers::InvalidID;
  this->geometric_elems_for_DV_map[FESystemElem::BASE_ELEM::num()] = NULL;
  this->elem_property_card = NULL;
  // next, set the initialization flags to false
  this->elem_is_initialized_for_DV_map[FESystemElem::BASE_ELEM::num()] = false;
  this->local_elem_is_initialized_for_DV_map[FESystemElem::BASE_ELEM::num()] = false;
  this->initialized_side_for_DV_map[FESystemElem::BASE_ELEM::num()] = -1;
  //  this->elem_is_initialized_for_post_processing = false;
}
void FESystemElem::FESystemElemBase::clearInitialization () [inline]
this method clears any previous initialization of the element.
Definition at line 1287 of file FESystemElem.h.
Referenced by Discipline::AnalysisDisciplineBase::calculateGlobalQty(), and Discipline::AnalysisDisciplineBase::calculatePostProcessQty().
{
  // clear the property card initialization
  this->clearPropertyCardInitialization();
  // first clear any sensitivity data
  this->clearSensitivityInitialization();
  // clear the local data
  this->clearElemInitialization();
  // clear element load and dof data
  this->clearLoadAndDofs();
}
void FESystemElem::FESystemElemBase::clearLoadAndDofs () [inline]
this clears the property element loads and dof values
Reimplemented in FESystemElem::PistonTheoryElem.
Definition at line 1308 of file FESystemElem.h.
Referenced by FESystemElem::PistonTheoryElem::clearLoadAndDofs(), Discipline::PistonTheory::getElemQty(), Discipline::FluidAnalysis::getElemQty(), Discipline::StructuralAnalysis::getElemQty(), and Discipline::ThermalAnalysis::getElemQty().
{
  for (unsigned int i=0; i <= this->getTransientSystemOrder(); i++)
    {
    this->dof_values_vec[i].zero();
    this->dof_value_sensitivity_vec[i].zero();
    }
  this->volume_loads = NULL;
  this->surface_loads = NULL;
  this->nodal_loads = NULL;
  this->volume_load_sens = NULL;
  this->surface_load_sens = NULL;
  this->nodal_load_sens = NULL;
}
virtual void FESystemElem::FESystemElemBase::clearPropertyCardInitialization () [protected, pure virtual]
this clears the temperature initialization only for the property cards.
Implemented in FESystemElem::ThermalElem, FESystemElem::StructuralElem, FESystemElem::FluidElem, and FESystemElem::PistonTheoryElem.
void FESystemElem::FESystemElemBase::clearSensitivityInitialization () [inline]
this method clears any previous initialization of the element.
Definition at line 1362 of file FESystemElem.h.
References FESystemNumbers::InvalidID.
Referenced by ~FESystemElemBase().
{
  this->sensitivity_parameter_ID = FESystemNumbers::InvalidID;
  this->perturbation = 0.0;
  this->sensitivity_parameter = FESystemNumbers::InvalidID;
  // this is needed for shape parameters only, however, they are still set to false,
  // since it does not harm anything.
  this->geometric_elems_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] = NULL;
  this->elem_is_initialized_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] = false;
  this->local_elem_is_initialized_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] = false;
  this->initialized_side_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] = -1;
  // next, set the initialized bools to false
  this->elem_is_initialized_for_property_sensitivity = false;
}
void FESystemElem::FESystemElemBase::create_local_1D_elem (const unsigned int design_point_enum_ID) [protected]
this function creates a local element in 1-D space for line elements
Definition at line 328 of file FESystemElem.C.
{
  Elem* elem = this->geometric_elems_for_DV_map[design_point_enum_ID];
  // check if the element was previously created or now. If not, create the element,
  // otherwise, simply change the nodal coordinates of the previous element
  Node **local_nodes = NULL;
  Elem *local_elem = NULL;
  switch (this->local_elem_for_DV_map[design_point_enum_ID] == NULL)
    {
    case true:
      {
        static const Point zero_point(0. , 0. , 0.);
        // create and set the nodes
        local_nodes = new Node*[elem->n_nodes()];
        this->local_elem_nodes_for_DV_map[design_point_enum_ID] = local_nodes;
        local_elem = Elem::build(elem->type()).release();
        this->local_elem_for_DV_map[design_point_enum_ID] = local_elem;
        for (unsigned int i=0; i < elem->n_nodes(); i++)
          {
          local_nodes[i] = new Node(zero_point, i);
          local_elem->set_node(i) = local_nodes[i];
          }
      }
      break;
    case false:
    default:
      {
        // use the same nodes and element
        local_nodes = this->local_elem_nodes_for_DV_map[design_point_enum_ID];
        local_elem = this->local_elem_for_DV_map[design_point_enum_ID];
      }
      break;
    }
  switch (elem->type())
    {
    case EDGE2:
      {
        //get the two nodes of this elem
        const Point& point0 = elem->point(0);
        const Point& point1 = elem->point(1);
        //calculate the length
        static Point vector01;
        vector01.assign(point1 - point0);
        //create a new element and set its two nodes at the
        //origin and the elem length
        static Point new_point0, new_point1;
        new_point0.zero(); new_point1.zero();
        new_point1(0) = vector01.size();
        *(local_nodes[0]) = new_point0;
        *(local_nodes[1]) = new_point1;
        // now create the local element and set its nodes
        local_elem->set_node(0) = local_nodes[0];
        local_elem->set_node(1) = local_nodes[1];
      }
      break;
    default:
      // cases of EDGE3, EDGE4 are not handled here
      abort();
      break;
    }
}
void FESystemElem::FESystemElemBase::create_local_2D_elem (const unsigned int design_point_enum_ID) [protected]
this function creates a local element in 2-D space for quad or tri elements
Definition at line 407 of file FESystemElem.C.
{
  Elem* elem = this->geometric_elems_for_DV_map[design_point_enum_ID];
  // initialize the local nodes and elem pointers
  Node **local_nodes = NULL;
  Elem *local_elem = NULL;
  switch (this->local_elem_for_DV_map[design_point_enum_ID] == NULL)
    {
    case true:
      {
        static const Point zero_point(0. , 0. , 0.);
        // create and set the nodes
        local_nodes = new Node*[elem->n_nodes()];
        this->local_elem_nodes_for_DV_map[design_point_enum_ID] = local_nodes;
        local_elem = Elem::build(elem->type()).release();
        this->local_elem_for_DV_map[design_point_enum_ID] = local_elem;
        for (unsigned int i=0; i < elem->n_nodes(); i++)
          {
          local_nodes[i] = new Node(zero_point, i);
          local_elem->set_node(i) = local_nodes[i];
          }
      }
      break;
    case false:
    default:
      {
        // use the same nodes and element
        local_nodes = this->local_elem_nodes_for_DV_map[design_point_enum_ID];
        local_elem = this->local_elem_for_DV_map[design_point_enum_ID];
      }
      break;
    }
  // now initialize the nodes
  switch (elem->type())
    {
    case TRI3:
      {
        //get the three nodes of this elem
        const Point& point0 = elem->point(0);
        const Point& point1 = elem->point(1);
        const Point& point2 = elem->point(2);
        //calculate the position vectors from point 0
        static Point vector01, vector02, tmp_vector1, tmp_vector2,
          new_unit_vec_x, new_unit_vec_y;
        vector01.assign(point1 - point0);
        vector02.assign(point2 - point0);
        new_unit_vec_x = vector01.unit();
        tmp_vector1.assign(new_unit_vec_x.cross(vector02));
        tmp_vector2 = tmp_vector1.unit();
        new_unit_vec_y = tmp_vector2.cross(new_unit_vec_x);
        //create a new element and set its two nodes at the
        //origin and the elem length
        static Point new_point0, new_point1, new_point2;
        new_point0.zero(); new_point1.zero(); new_point2.zero();
        new_point1(0)  = vector01.size();
        new_point2(0) = vector02 * new_unit_vec_x;
        new_point2(1) = vector02 * new_unit_vec_y;
        *(local_nodes[0]) = new_point0;
        *(local_nodes[1]) = new_point1;
        *(local_nodes[2]) = new_point2;
      }
      break;
    case QUAD4:
      {
        //get the four nodes of this elem
        const Point& point0 = elem->point(0);
        const Point& point1 = elem->point(1);
        const Point& point2 = elem->point(2);
        const Point& point3 = elem->point(3);
        //calculate the position vectors from point 0
        static Point vector01, vector02, vector03, tmp_vector1, tmp_vector2,
          new_unit_vec_x, new_unit_vec_y;
        vector01.assign(point1 - point0);
        vector02.assign(point2 - point0);
        vector03.assign(point3 - point0);
        new_unit_vec_x = vector01.unit();
        tmp_vector1.assign(new_unit_vec_x.cross(vector03));
        tmp_vector2 = tmp_vector1.unit();
        new_unit_vec_y = tmp_vector2.cross(new_unit_vec_x);
        //create a new element and set its two nodes at the
        //origin and the elem length
        static Point new_point0, new_point1, new_point2, new_point3;
        new_point0.zero(); new_point1.zero(); new_point2.zero(); new_point3.zero();
        new_point1(0) = vector01.size();
        new_point2(0) = vector02 * new_unit_vec_x;
        new_point2(1) = vector02 * new_unit_vec_y;
        new_point3(0) = vector03 * new_unit_vec_x;
        new_point3(1) = vector03 * new_unit_vec_y;
        *(local_nodes[0]) = new_point0;
        *(local_nodes[1]) = new_point1;
        *(local_nodes[2]) = new_point2;
        *(local_nodes[3]) = new_point3;
      }
      break;
    default:
      // cases for TRI6, QUAD8, QUAD9 are not handled
      abort();
      break;
    }
}
void FESystemElem::FESystemElemBase::create_local_elem (const unsigned int design_point_enum_ID) [protected]
this function creates a local elem for this general element in 3-D space. The local element pointer is then stored in the _local_elem pointer. This is a generic method, and accesses the respective method for 1-D and 2-D depending on the dimension of the element
Definition at line 298 of file FESystemElem.C.
{
  // check the dimension of the element
  // and call the appropriate function
  switch (this->geometric_elems_for_DV_map[design_point_enum_ID]->dim())
    {
    case 1:
      this->create_local_1D_elem(design_point_enum_ID);
      break;
    case 2:
      this->create_local_2D_elem(design_point_enum_ID);
      break;
    case 3:
      this->local_elem_for_DV_map[design_point_enum_ID] =
      this->geometric_elems_for_DV_map[design_point_enum_ID];
      break;
    default:
      abort();
      break;
    }
}
FESystemElem::FESystemElemBase::DeclException0 (ExcInvalidElemGiven) [protected]
this exception is thrown when an invalid elem is called
void FESystemElem::FESystemElemBase::deleteElemLocalData (const unsigned int design_point_enum_ID) [inline, protected]
deletes the local data for the element at the specified design point
Definition at line 1233 of file FESystemElem.h.
Referenced by ~FESystemElemBase().
{
  unsigned int n_nodes;
  // clear the base element data
  // first release the local elem pointer in case it is 3D, since for that case
  //  the local element is just a pointer to the base elem
  switch (this->local_elem_for_DV_map[design_point_enum_ID] == NULL)
    {
    case true:
      {
        // nothing to be done here, since the element was not created.
      }
      break;
    case false:
    default:
      {
        switch (this->local_elem_for_DV_map[design_point_enum_ID]->dim())
          {
          case 3:
            this->local_elem_for_DV_map[design_point_enum_ID] = NULL;
            break;
          default:
            {
              // delete the element
              n_nodes = this->local_elem_for_DV_map[design_point_enum_ID]->n_nodes();
              delete this->local_elem_for_DV_map[design_point_enum_ID];
              this->local_elem_for_DV_map[design_point_enum_ID] = NULL;
              // and then delete the nodes. it is assumed that if the local elem was created,
              // the nodes too will be present, and need to be deleted
              for (unsigned int i = 0; i< n_nodes; i++)
                delete this->local_elem_nodes_for_DV_map[design_point_enum_ID][i];
              // finally, delete the array that was created to store the nodes.
              delete[] this->local_elem_nodes_for_DV_map[design_point_enum_ID];
              this->local_elem_nodes_for_DV_map[design_point_enum_ID] = NULL;
            }
            break;
          }
      }
    }
  // next, set the initialized bools to false
  this->local_elem_is_initialized_for_DV_map[design_point_enum_ID] = false;
}
unsigned int FESystemElem::FESystemElemBase::getDomainEnumFromSideNumber (unsigned int side) const [inline, protected]
this method returns the side number associated with the domain specified in the arguement list
Definition at line 975 of file FESystemElem.h.
{
  if (side == this->geometric_elems_for_DV_map.find(FESystemElem::BASE_ELEM::num())->second->n_sides())
    return FESystemElem::ELEM_VOLUME::num();
  switch (side)
    {
    case 0:
      return FESystemElem::SIDE_ZERO::num();
      break;
    case 1:
      return FESystemElem::SIDE_ONE::num();
      break;
    case 2:
      return FESystemElem::SIDE_TWO::num();
      break;
    case 3:
      return FESystemElem::SIDE_THREE::num();
      break;
    case 4:
      return FESystemElem::SIDE_FOUR::num();
      break;
    case 5:
      return FESystemElem::SIDE_FIVE::num();
      break;
    default:
      abort();
      break;
    }
}
const Elem * FESystemElem::FESystemElemBase::getElem (const unsigned int design_point_enum_ID) const [inline]
Returns:
the geometric element for the unperturbed mesh
Definition at line 908 of file FESystemElem.h.
Referenced by Discipline::PistonTheory::getElemQty(), Discipline::FluidAnalysis::getElemQty(), Discipline::StructuralAnalysis::getElemQty(), and Discipline::ThermalAnalysis::getElemQty().
{
  const Elem* return_elem = NULL;
  switch(this->elem_is_initialized_for_DV_map.find(design_point_enum_ID)->second)
    {
    case true:
      return_elem = this->geometric_elems_for_DV_map.find(design_point_enum_ID)->second;
      break;
    case false:
    default:
      Assert(false, ExcInvalidState());
    }
  return return_elem;
}
virtual void FESystemElem::FESystemElemBase::getElementAssembledQty (const unsigned int name_enum_ID, DenseVector< double > * qty) [pure virtual]
returns the assembled quantitiy for the element
Implemented in FESystemElem::ThermalElem, FESystemElem::StructuralElem, FESystemElem::FluidElem, FESystemElem::PistonTheoryElem, and FEInterpolationElem.
Referenced by FEInterpolationAnalysis::getElemQty(), Discipline::PistonTheory::getElemQty(), Discipline::FluidAnalysis::getElemQty(), Discipline::StructuralAnalysis::getElemQty(), and Discipline::ThermalAnalysis::getElemQty().
virtual void FESystemElem::FESystemElemBase::getElementAssembledQty (const unsigned int name_enum_ID, DenseMatrix< double > * qty) [pure virtual]
Implemented in FESystemElem::ThermalElem, FESystemElem::StructuralElem, FESystemElem::FluidElem, FESystemElem::PistonTheoryElem, and FEInterpolationElem.
virtual void FESystemElem::FESystemElemBase::getElementAssembledQtySensitivity (const unsigned int name_enum_ID, DenseVector< double > * qty) [pure virtual]
Implemented in FESystemElem::ThermalElem, FESystemElem::StructuralElem, FESystemElem::PistonTheoryElem, FESystemElem::FluidElem, and FEInterpolationElem.
Referenced by FEInterpolationAnalysis::getElemQty(), Discipline::PistonTheory::getElemQty(), Discipline::FluidAnalysis::getElemQty(), Discipline::StructuralAnalysis::getElemQty(), and Discipline::ThermalAnalysis::getElemQty().
virtual void FESystemElem::FESystemElemBase::getElementAssembledQtySensitivity (const unsigned int name_enum_ID, DenseMatrix< double > * qty) [pure virtual]
Implemented in FESystemElem::ThermalElem, FESystemElem::StructuralElem, FESystemElem::PistonTheoryElem, FESystemElem::FluidElem, and FEInterpolationElem.
double FESystemElem::FESystemElemBase::getElementMass (bool sensitivity)
calculates and returns the value of weight of the element
Definition at line 1752 of file FESystemElem.C.
References PROPERTY_PARAMETER_ENUM_ID, and SHAPE_PARAMETER_ENUM_ID.
Referenced by Discipline::StructuralAnalysis::getElemQty(), and Discipline::ThermalAnalysis::getElemQty().
{
  // then, check about the property card
  if (!this->property_card_initialized)
    this->initPropertyCard();
  double factor = 0.0, factor_sens = 0.0, vol = 0.0;
  DenseVector<double> vector;
  // get the mass factor from the element data card
  switch (this->dimension)
  {
    case 1:
    case 3:
      this->elem_property_card->getFactor(factor, MASS_FACTOR::num());
      break;
    case 2:
      this->elem_property_card->getFactor(factor, MEMBRANE_MASS_FACTOR::num());
      break;
    default:
      ExcInternalError();
  }
  // get the value of volume
  switch (this->dimension)
  {
    case 1:
    {
      static Elem* elem;
      elem = this->geometric_elems_for_DV_map[FESystemElem::BASE_ELEM::num()];
      // calculate the length of the element
      const Point& point0 = elem->point(0);
      const Point& point1 = elem->point(1);
      static double dx, dy, dz;
      dx = point0(0)-point1(0);
      dy = point0(1)-point1(1);
      dz = point0(2)-point1(2);
      vol = pow((dx*dx+dy*dy+dz*dz),0.5);
    }
      break;
    case 2:
    case 3:
    {
      this->getFESystemElemQty(FESystemElem::N_FACTOR::num(), &vector,
                               FESystemElem::BASE_ELEM::num(),
                               FESystemElem::ELEM_VOLUME::num(), LAGRANGE);
      for (unsigned int i=0; i < vector.size(); i++)
        vol += vector.el(i);
    }
    default:
      ExcInternalError();
  }
  // check for property sensitivity
  if (sensitivity &&
      this->sensitivity_parameter == DesignData::PROPERTY_PARAMETER::num())
    {
      if (!this->elem_property_card->checkElemAndMaterialCardGlobalParameterDependence
          (this->sensitivity_parameter_ID))
        return 0.0;
      switch (this->dimension)
      {
        case 1:
        case 3:
          this->elem_property_card->getFactorSensitivityForGlobalParameter
          (factor_sens, MASS_FACTOR::num(), this->sensitivity_parameter_ID);
          break;
        case 2:
          this->elem_property_card->getFactorSensitivityForGlobalParameter
          (factor_sens, MEMBRANE_MASS_FACTOR::num(), this->sensitivity_parameter_ID);
          break;
        default:
          ExcInternalError();
      }
    }
  // to get the jacobian factor, get the N_FACTOR integrated over the volume
  // and then add all the elements of the vector
  if (sensitivity)
    {
      switch (this->sensitivity_parameter)
      {
        case PROPERTY_PARAMETER_ENUM_ID:
          vol *= factor_sens;
          break;
        case SHAPE_PARAMETER_ENUM_ID:
        {
          // this will set the sensitivity value of volume of element
          switch (this->dimension)
          {
            case 1:
            {
              static Elem* perturbed_elem;
              perturbed_elem =
              this->geometric_elems_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()];
              // calculate the length for the perturbed element, and find the sensitivity
              // calculate the length of the element
              const Point& point0 = perturbed_elem->point(0);
              const Point& point1 = perturbed_elem->point(1);
              static double dx, dy, dz;
              dx = point0(0)-point1(0);
              dy = point0(1)-point1(1);
              dz = point0(2)-point1(2);
              vol -= pow((dx*dx+dy*dy+dz*dz),0.5);
              vol /= -0.5;
            }
              break;
            case 2:
            case 3:
            {
              this->getFESystemElemQtyShapeSensitivity(FESystemElem::N_FACTOR::num(), &vector,
                                                       FESystemElem::ELEM_VOLUME::num(),
                                                       LAGRANGE);
              vol = 0.0;
              for (unsigned int i=0; i < vector.size(); i++)
                vol += vector.el(i);
            }
            default:
              ExcInternalError();
          }
          // multiply with the mass factor to get the mass
          vol *= factor;
        }
          break;
        default:
          abort();
          break;
      }
    }
  else
    vol *= factor;
  return vol;
}
virtual std::auto_ptr<ElemPostProcessQty> FESystemElem::FESystemElemBase::getElementPostProcessQty (std::vector< unsigned int > load_cases, std::vector< DesignData::DesignParameter * > design_variables) [pure virtual]
calculates and returns the element post process quantity
Parameters:
vector of load cases for which the quantities will be calculated
vector of design variables for which the quantities will be calculated
Implemented in FESystemElem::ThermalElem, FESystemElem::StructuralElem, FESystemElem::PlateDKBatoz, FESystemElem::PistonTheoryElem, FESystemElem::FluidElem, FEInterpolationElem, FESystemElem::PlateVonKarman, and FESystemElem::Membrane.
Referenced by Discipline::AnalysisDisciplineBase::calculatePostProcessQty().
template<class QtyType > void FESystemElem::FESystemElemBase::getFESystemElemQty (const unsigned int name_enum_ID, QtyType * qty, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily & family)
this method returns the quantity specified in the arguement list. This has been templatized so that the template can be used in derived element types. This element class will provide its element quantity and calculation routines.
Parameters:
name enum ID of the quantity to be returned
qty data structure in which the quantity will be removed
design_point_enum_ID enum ID of the design point for which the quantity is requested
side_num number of the side if this is a side quantity
family enum ID of the family of FE for which the quantity is needed
Definition at line 1019 of file FESystemElem.h.
Referenced by FEInterpolationElem::calculate_K(), and FESystemElem::getPlateDKBatozQty().
{
  assert (qty != NULL);
  // get the string name for the quantity
  static std::string qty_string_name;
  qty_string_name.clear();
  qty_string_name = this->getStringNameForFESystemElemQty(name,
                                                          design_point_enum_ID,
                                                          domain, family);
  // check if the quantity exists in the map element database or not
  // if not, calculate and store it
  if (this->elem_data_storage->checkIfQtyExists
      (this->discipline_enumID, this->elem_ID, qty_string_name))
    {
    // get the factor the database
    this->elem_data_storage->get_element_data(*qty, this->discipline_enumID,
                                              this->elem_ID, qty_string_name);
    }
  else
    {
    this->calculateFESystemElemQty(qty, name, design_point_enum_ID,
                                   domain, family);
    this->elem_data_storage->add_element_data(*qty, this->discipline_enumID,
                                              this->elem_ID, qty_string_name);
    }
}
template<class QtyType > void FESystemElem::FESystemElemBase::getFESystemElemQtyShapeSensitivity (const unsigned int name_enum_ID, QtyType * qty, const unsigned int domain_enum_ID, const FEFamily & family)
this method returns the shape sensitivity of quantity specified in the arguement list. This has been templatized so that the template can be used in derived element types. This element class will provide its element quantity and calculation routines.
Parameters:
name name of the quantity to be returned
qty data structure in which the quantity will be removed
side_num number of the side if this is a side quantity
Definition at line 1059 of file FESystemElem.h.
Referenced by FESystemElem::getPlateDKBatozQty().
{
  Assert(this->elem_is_initialized_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()],
         ExcInvalidState());
  assert (qty != NULL);
  // create quantities for the perturbed and base elements
  static QtyType  base_qty;
  // get the string name for the quantity
  static std::string qty_string_name, qty_sensitivity_string_name;
  qty_string_name.clear();  qty_sensitivity_string_name.clear();
  qty_string_name = this->getStringNameForFESystemElemQty(name,
                                                          FESystemElem::BASE_ELEM::num(),
                                                          domain, family);
  qty_sensitivity_string_name =
    this->getStringNameForFESystemElemQtySensitivity(name,
                                                     this->sensitivity_parameter_ID,
                                                     domain,
                                                     family);
  // check if the quantity exists in the element database or not
  // if not, calculate and store it
  if (this->elem_data_storage->checkIfQtyExists
      (this->discipline_enumID, this->elem_ID, qty_sensitivity_string_name))
    {
    // get the factor from the database
    this->elem_data_storage->get_element_data(*qty,
                                              this->discipline_enumID, this->elem_ID,
                                              qty_sensitivity_string_name);
    }
  else
    {
    // next, obtain the quantity for the perturbed element
    this->calculateFESystemElemQty(qty, name,
                                   FESystemElem::BASE_PLUS_DELTA_ELEM::num(),
                                   domain, family);
    // also, obtain the quantity for the base element. The base quantity also needs to
    // be evaluated at the same load case, dof_value for sensitivity calculation
    base_qty.zero();
    this->getFESystemElemQty(name, &base_qty,  FESystemElem::BASE_ELEM::num(),
                             domain, family);
    qty->add(-1.0, base_qty);
    qty->scale(1.0/this->perturbation);
    this->elem_data_storage->add_element_data(*qty,
                                              this->discipline_enumID, this->elem_ID,
                                              qty_sensitivity_string_name);
    }
}
unsigned int FESystemElem::FESystemElemBase::getFESystemElemTypeEnumID () const [inline]
Returns:
the element enum ID
Definition at line 889 of file FESystemElem.h.
Referenced by Discipline::PistonTheory::getElemQty().
{
  return this->elem_type_enum_ID;
}
const std::string FESystemElem::FESystemElemBase::getFESystemElemTypeEnumName () const [inline]
returns the element enum ID
Definition at line 899 of file FESystemElem.h.
References FESystemElem::FESystemElemTypeEnum::enumName().
{
  return FESystemElem::FESystemElemTypeEnum::enumName(this->elem_type_enum_ID);
}
virtual void FESystemElem::FESystemElemBase::getFETypes (std::vector< FEType > & fetypes) [protected, pure virtual]
inserts the finite element types to be used for this element in the input parameters
Implemented in FESystemElem::ThermalElem, FESystemElem::PlateDKBatoz, FESystemElem::PistonTheoryElem, FESystemElem::FluidElem, FEInterpolationElem, FESystemElem::PlateVonKarman, and FESystemElem::Membrane.
unsigned int FESystemElem::FESystemElemBase::getID () const [inline]
Returns:
the element ID
Definition at line 868 of file FESystemElem.h.
References elem_ID, and elem_is_initialized_for_DV_map.
Referenced by Discipline::PistonTheory::getElemQty(), Discipline::FluidAnalysis::getElemQty(), Discipline::StructuralAnalysis::getElemQty(), and Discipline::ThermalAnalysis::getElemQty().
{
  Assert(this->elem_is_initialized_for_DV_map.find(FESystemElem::BASE_ELEM::num())->second,
         ExcInvalidState());
  return this->elem_ID;
}
virtual unsigned int FESystemElem::FESystemElemBase::getNDofs () [pure virtual]
Returns:
the number of dofs for this element
Implemented in FESystemElem::StructuralElem, and FESystemElem::PistonTheoryElem.
Referenced by Discipline::AnalysisDisciplineBase::resizeElemMatricesForElem().
unsigned int FESystemElem::FESystemElemBase::getNNodes () [inline]
Returns:
the number of nodes for this elem.
Definition at line 880 of file FESystemElem.h.
Referenced by FEInterpolationElem::getElementAssembledQty(), FEInterpolationElem::getElementAssembledQtySensitivity(), FESystemElem::PistonTheoryElem::getNDofs(), FESystemElem::StructuralElem::getNDofs(), FESystemElem::getPlateDKBatozQty(), and FESystemElem::PlateVonKarman::getPlateVonKarmanQty().
{
  return this->geometric_elems_for_DV_map[FESystemElem::BASE_ELEM::num()]->n_nodes();
}
virtual void FESystemElem::FESystemElemBase::getQuadratureRules (std::map< FEFamily, std::pair< QuadratureType, Order > > & quadratures) [protected, pure virtual]
inserts the quadrature rules to be used for the different elements
Implemented in FESystemElem::ThermalElem, FESystemElem::PlateDKBatoz, FESystemElem::PistonTheoryElem, FESystemElem::FluidElem, FEInterpolationElem, FESystemElem::PlateVonKarman, and FESystemElem::Membrane.
unsigned int FESystemElem::FESystemElemBase::getSideNumberFromDomainEnum (const unsigned int side) const [inline, protected]
this method returns the side number associated with the domain specified in the arguement list
Definition at line 931 of file FESystemElem.h.
References ELEM_VOLUME_ENUM_ID, SIDE_FIVE_ENUM_ID, SIDE_FOUR_ENUM_ID, SIDE_ONE_ENUM_ID, SIDE_THREE_ENUM_ID, SIDE_TWO_ENUM_ID, and SIDE_ZERO_ENUM_ID.
{
  switch (side)
    {
    case ELEM_VOLUME_ENUM_ID:
      return this->geometric_elems_for_DV_map.find(FESystemElem::BASE_ELEM::num())->second->n_sides();
      break;
    case SIDE_ZERO_ENUM_ID:
      return 0;
      break;
    case SIDE_ONE_ENUM_ID:
      return 1;
      break;
    case SIDE_TWO_ENUM_ID:
      return 2;
      break;
    case SIDE_THREE_ENUM_ID:
      return 3;
      break;
    case SIDE_FOUR_ENUM_ID:
      return 4;
      break;
    case SIDE_FIVE_ENUM_ID:
      return 5;
      break;
    default:
      abort();
      break;
    }
}
std::string FESystemElem::FESystemElemBase::getStringNameForFESystemElemQty (const unsigned int name_enum_ID, const unsigned int design_point_enum_ID, const unsigned int domain_enum_ID, const FEFamily & family) [protected]
this function returns the name of the given quantity
Definition at line 1590 of file FESystemElem.C.
{
  std::string name;
  // the name is used only for valid FE names, since otherwise the quantitiy
  // is independent of the FE type.
  if (family != INVALID_FE)
    name = Utility::enum_to_string<FEFamily>(family);
  name += "_";
  name += FESystemElem::FESystemElemQtyEnum::enumName(quantity);
  name += "_";
  name += FESystemElem::DesignPointElemEnum::enumName(design_point_enum_ID);
  name += "_";
  name += FESystemElem::IntegrationDomainEnum::enumName(domain);
  return name;
}
std::string FESystemElem::FESystemElemBase::getStringNameForFESystemElemQtySensitivity (const unsigned int name_enum_ID, unsigned int DV_num, const unsigned int domain_enum_ID, const FEFamily & family) [protected]
this function returns the name of the sensitivity of the specified quantity
Definition at line 1616 of file FESystemElem.C.
{
  // get the name for this qty
  std::string qty_name, qty_sensitivity_name;
  // the sensitivities are always calculated at the base element. Hence, the name
  // will be referred to the base elem
  qty_name = this->getStringNameForFESystemElemQty(quantity,
                                                   FESystemElem::BASE_ELEM::num(),
                                                   domain, family);
  // create the string and append the DV number
  qty_sensitivity_name = "d";
  qty_sensitivity_name += qty_name;
  qty_sensitivity_name += "_dDV";
  std::ostringstream DV_number_to_string;
  DV_number_to_string << DV_num;
  qty_sensitivity_name += DV_number_to_string.str();
  return qty_sensitivity_name;
}
virtual unsigned int FESystemElem::FESystemElemBase::getTransientSystemOrder () const [pure virtual]
Returns:
the transient system order for the elem equations
Implemented in FESystemElem::ThermalElem, FESystemElem::StructuralElem, FESystemElem::FluidElem, and FESystemElem::PistonTheoryElem.
void FESystemElem::FESystemElemBase::initialize_element (const unsigned int design_point_enum_ID, const std::vector< Point > * points = NULL) [protected]
initializes the element and the respective data structures like phi, dphi, etc. If the input arguement is NULL, the element is initialized at the quandrature points otherwise, it is initialized at the points specifies in the input parameter. It used the _local_elem pointer to initialize this element.
Definition at line 239 of file FESystemElem.C.
Referenced by FEInterpolationElem::calculate_F(), and FESystemElem::PlateVonKarman::getPlateVonKarmanQty().
{
  // create local element
  this->create_local_elem(design_point_enum_ID);
  // reinit fe with this local element
  std::map<FEFamily, FEBase*>::iterator it, end;
  it = this->fe_base_map_for_DV[design_point_enum_ID].begin();
  end = this->fe_base_map_for_DV[design_point_enum_ID].end();
  for (; it != end; it++)
    it->second->reinit(this->local_elem_for_DV_map[design_point_enum_ID], points);
  this->local_elem_is_initialized_for_DV_map[design_point_enum_ID] = true;
}
void FESystemElem::FESystemElemBase::initialize_element_side (unsigned int side_num, const unsigned int design_point_enum_ID) [protected]
initialized the element side given by the side number passed in the arguement
Definition at line 260 of file FESystemElem.C.
{
  // make sure that the element is initialized, otherwise initialize it
  if(!this->local_elem_is_initialized_for_DV_map[design_point_enum_ID])
      this->initialize_element(design_point_enum_ID);
  static Elem* local_elem;
  local_elem = this->local_elem_for_DV_map[design_point_enum_ID];
  switch (local_elem->dim())
    {
    case 1:
      {
        abort();
      }
      break;
    case 2:
    case 3:
      {
        std::map<FEFamily, FEBase*>::iterator it, end;
        it = this->fe_side_map_for_DV[design_point_enum_ID].begin();
        end = this->fe_side_map_for_DV[design_point_enum_ID].end();
        for (; it != end; it++)
          it->second->reinit(this->local_elem_for_DV_map[design_point_enum_ID], side_num);
        this->initialized_side_for_DV_map[design_point_enum_ID] = side_num;
      }
      break;
    }
}
void FESystemElem::FESystemElemBase::initializeFEAndQuadratureDataStructures () [protected]
initializes the set of elements to be used for this element
Definition at line 1646 of file FESystemElem.C.
{
  Assert(!this->fe_quadrature_data_initialized,
         ExcInvalidState());
  // get the FETypes for this element
  std::vector<FEType> fetypes;
  std::map<FEFamily, std::pair<QuadratureType, Order> > quadratures;
  this->getFETypes(fetypes);
  this->getQuadratureRules(quadratures);
  // now initialize the data
  // first of all, create and initialize all the finite elements needed for this element
  std::vector<FEType>::const_iterator it, end;
  it = fetypes.begin();
  end = fetypes.end();
  std::map<FEFamily, std::pair<QuadratureType, Order> >::const_iterator
    qend = quadratures.end();
  std::auto_ptr<FEBase> fe;
  std::auto_ptr<QBase> qbase;
  bool insert_success = false;
  // create and insert the data structures necessary
  for (; it != end; it++)
    {
    // get the quadrature rule definintion for this elem type
    std::map<FEFamily, std::pair<QuadratureType, Order> >::const_iterator
    qit = quadratures.find((*it).family);
    Assert(qit != qend, ExcInternalError());
    // now iterate over all the maps fe and qbase maps for all design points
    // and add the data structures
    std::map<unsigned int, std::map<FEFamily, FEBase*> >::iterator fe_it, fe_end;
    // insert the fe first
    fe_it = this->fe_base_map_for_DV.begin();
    fe_end = this->fe_base_map_for_DV.end();
    // iterate over all design points and add the data structs
    for ( ; fe_it != fe_end; fe_it++)
      {
      // add the fe
      fe.reset(FEBase::build(this->dimension, *it).release());
      insert_success = fe_it->second.insert(std::map<FEFamily, FEBase*>::value_type
                                            (fe->get_family(), fe.get())).second;
      Assert(insert_success,
             FESystemExceptions::ExcDuplicateID("FEFamily", fe->get_family()));
      // now add the quadrature rule
      qbase.reset(QBase::build(qit->second.first, this->dimension, qit->second.second).release());
      // the insert for this is not checked since it will be true if it passed the previous test
      // it is assumed that there will be a set of qrules per design point. Hence, the size of
      // the fe and the qrule map should be same.
      this->qbase_map_for_DV[fe_it->first].insert(std::map<FEFamily, QBase*>::value_type
                                                  (fe->get_family(), qbase.get()));
      // attach the quad rule
      fe->attach_quadrature_rule(qbase.get());
      // release the pointers
      fe.release();
      qbase.release();
      // this is repeated for the data structs for the side elems.
      // add the fe
      fe.reset(FEBase::build(this->dimension, *it).release());
      this->fe_side_map_for_DV[fe_it->first].insert(std::map<FEFamily, FEBase*>::value_type
                                                    (fe->get_family(), fe.get()));
      // now add the quadrature rule
      qbase.reset(QBase::build(qit->second.first,
                               (this->dimension - 1), qit->second.second).release());
      // the insert for this is not checked since it will be true if it passed the previous test
      // it is assumed that there will be a set of qrules per design point. Hence, the size of
      // the fe and the qrule map should be same.
      this->qbase_side_map_for_DV[fe_it->first].insert(std::map<FEFamily, QBase*>::value_type
                                                       (fe->get_family(), qbase.get()));
      // attach the quad rule
      fe->attach_quadrature_rule(qbase.get());
      // release the pointers
      fe.release();
      qbase.release();
      }
//    this->JxW_map[fe->get_family()] =
//      const_cast<std::vector<Real>*>(&(fe->get_JxW()));
//    this->phi_map[fe->get_family()] =
//      const_cast<std::vector<std::vector<Real> >*>(&(fe->get_phi()));
//    this->dphi_map[fe->get_family()] =
//      const_cast<std::vector<std::vector<RealGradient> >*>(&(fe->get_dphi()));
    }
  this->fe_quadrature_data_initialized = true;
}
virtual void FESystemElem::FESystemElemBase::initPropertyCard () [protected, pure virtual]
initializes the property cards for local parameters
Implemented in FESystemElem::ThermalElem, FESystemElem::StructuralElem, FESystemElem::FluidElem, and FESystemElem::PistonTheoryElem.
void FESystemElem::FESystemElemBase::reinit (const unsigned int elem_ID, Elem * elem, ElemDataCard * elem_data_card) [inline]
reinitializes an element for a new geometric element. The element specified here is the element at base design point
Definition at line 1119 of file FESystemElem.h.
References FESystemElem::FESystemElemTypeEnum::elemType().
Referenced by Discipline::AnalysisDisciplineBase::calculateGlobalQty(), and Discipline::AnalysisDisciplineBase::calculatePostProcessQty().
{
  // first make sure that this element has been cleared of any previous
  // initializations
  Assert(!this->elem_is_initialized_for_DV_map[FESystemElem::BASE_ELEM::num()], ExcInvalidState());
  Assert(!this->elem_is_initialized_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()],
         ExcInvalidState());
  Assert(!this->elem_is_initialized_for_property_sensitivity, ExcInvalidState());
  // now make sure that the pointers are not NULL
  Assert(elem != NULL, ExcEmptyObject());
  Assert(data_card != NULL, ExcEmptyObject());
  // make sure that the provided element is of the same kind as this elem will handle
  Assert(elem->type() == FESystemElem::FESystemElemTypeEnum::elemType(this->elem_type_enum_ID),
         ExcInternalError());
  // finally, store the data provided
  this->elem_ID = ID;
  this->geometric_elems_for_DV_map[FESystemElem::BASE_ELEM::num()] = elem;
  this->elem_property_card = data_card;
  // the fe and quad data structures need to be initialized once for this finite element
  if (!this->fe_quadrature_data_initialized)
    this->initializeFEAndQuadratureDataStructures();
  // also, resize the dof vectors if that has not already been done
  static const unsigned int n_dofs = this->getNDofs();
  if (this->dof_values_vec.size() != (this->getTransientSystemOrder()+1))
    {
    this->dof_values_vec.clear();
    this->dof_value_sensitivity_vec.clear();
    for (unsigned int i=0; i <= this->getTransientSystemOrder(); i++)
      {
      this->dof_values_vec.push_back(DenseVector<double>(n_dofs));
      this->dof_values_vec[i].zero();
      this->dof_value_sensitivity_vec.push_back(DenseVector<double>(n_dofs));
      this->dof_value_sensitivity_vec[i].zero();
      }
    }
  this->elem_is_initialized_for_DV_map[FESystemElem::BASE_ELEM::num()] = true;
}
void FESystemElem::FESystemElemBase::reinitForPropertySensitivity (const unsigned int param_ID) [inline]
reinitializes element for shape sensitivity
Definition at line 1209 of file FESystemElem.h.
Referenced by Discipline::AnalysisDisciplineBase::calculateGlobalQty().
{
  // first make sure that this element has been cleared of any previous
  // initializations
  Assert(this->elem_is_initialized_for_DV_map[FESystemElem::BASE_ELEM::num()],
         ExcInvalidState());
  Assert(!this->elem_is_initialized_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()],
         ExcInvalidState());
  Assert(!this->elem_is_initialized_for_property_sensitivity, ExcInvalidState());
  // now make sure that the pointers are not NULL
  this->sensitivity_parameter_ID = param_ID;
  this->sensitivity_parameter = DesignData::PROPERTY_PARAMETER::num();
  this->elem_is_initialized_for_property_sensitivity = true;
}
void FESystemElem::FESystemElemBase::reinitForShapeSensitivity (const unsigned int param_ID, Elem * perturb_elem, const double perturb_value) [inline]
reinitializes element for shape sensitivity. The element specified here is the perturbed element. The forward finite dofferencing is used for this.
Definition at line 1173 of file FESystemElem.h.
References FESystemElem::FESystemElemTypeEnum::elemType(), and FESystemNumbers::Epsilon.
Referenced by Discipline::AnalysisDisciplineBase::calculateGlobalQty().
{
  // first make sure that this element has been cleared of any previous
  // initializations
  Assert(this->elem_is_initialized_for_DV_map[FESystemElem::BASE_ELEM::num()],
         ExcInvalidState());
  Assert(!this->elem_is_initialized_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()],
         ExcInvalidState());
  Assert(!this->elem_is_initialized_for_property_sensitivity, ExcInvalidState());
  // now make sure that the pointers are not NULL
  Assert(perturb_elem != NULL, ExcEmptyObject());
  Assert(fabs(perturb_value) > FESystemNumbers::Epsilon, ExcInternalError());
  // make sure that the provided element is of the same kind as this elem will handle
  Assert(perturb_elem->type() ==
         FESystemElem::FESystemElemTypeEnum::elemType(this->elem_type_enum_ID),
         ExcInternalError());
  // finally, store the data provided
  this->sensitivity_parameter_ID = param_ID;
  this->geometric_elems_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] = perturb_elem;
  this->perturbation = perturb_value;
  this->sensitivity_parameter = DesignData::SHAPE_PARAMETER::num();
  this->elem_is_initialized_for_DV_map[FESystemElem::BASE_PLUS_DELTA_ELEM::num()] = true;
}
void FESystemElem::FESystemElemBase::setDofValues (std::vector< DenseVector< double > * > & dofs, std::vector< DenseVector< double > * > & dof_sens) [inline]
this method sets the values of the dofs for the element. The vectors containing the dof values are placed in the arguements according to their time derivative. If a derivative order is not needed, its pointer is left to NULL.
Definition at line 1383 of file FESystemElem.h.
Referenced by Discipline::FluidAnalysis::getElemQty(), Discipline::StructuralAnalysis::getElemQty(), and Discipline::ThermalAnalysis::getElemQty().
{
  Assert(this->dof_values_vec.size() == (this->getTransientSystemOrder()+1), ExcInternalError());
  Assert(this->dof_value_sensitivity_vec.size() == (this->getTransientSystemOrder()+1),
         ExcInternalError());
  Assert(dofs.size() == (this->getTransientSystemOrder()+1), ExcInternalError());
  Assert(dof_sens.size() == (this->getTransientSystemOrder()+1), ExcInternalError());
  Assert(dofs[0] != NULL, ExcInternalError());
  for (unsigned int i=0; i <= this->getTransientSystemOrder(); i++)
    {
    if (dofs[i] != NULL)
      this->dof_values_vec[i] = *dofs[i];
    else
      this->dof_values_vec[i].zero();
    if (dof_sens[i] != NULL)
      this->dof_value_sensitivity_vec[i] = *dof_sens[i];
    else
      this->dof_value_sensitivity_vec[i].zero();
    }
}
void FESystemElem::FESystemElemBase::setElementLoads (std::map< unsigned int, const Loads::VolumeLoadCombination * > * vol_loads, std::map< unsigned int, std::map< unsigned int, const Loads::SurfaceLoadCombination * > > * surf_loads, std::map< unsigned int, std::map< unsigned int, const Loads::NodalLoadCombination * > > * nod_loads, std::map< unsigned int, const Loads::VolumeLoadCombination * > * vol_load_sens, std::map< unsigned int, std::map< unsigned int, const Loads::SurfaceLoadCombination * > > * surf_load_sens, std::map< unsigned int, std::map< unsigned int, const Loads::NodalLoadCombination * > > * nod_load_sens) [inline]
this method sets the values of the element loads
Parameters:
loads map of loads for this element
load_sens sensitivities of the loads specified in the loads parameter. This is optional. For shape sensitivity, the loads are assumed for the perturned element, for a forward difference sensitivity calculation.
Definition at line 1413 of file FESystemElem.h.
Referenced by Discipline::PistonTheory::getElemQty(), Discipline::FluidAnalysis::getElemQty(), Discipline::StructuralAnalysis::getElemQty(), and Discipline::ThermalAnalysis::getElemQty().
{
  Assert(vol_loads != NULL, ExcInternalError());
  Assert(surf_loads != NULL, ExcInternalError());
  Assert(nod_loads != NULL, ExcInternalError());
  this->volume_loads = vol_loads;
  this->surface_loads = surf_loads;
  this->nodal_loads = nod_loads;
  if (vol_load_sens != NULL || surf_load_sens != NULL || nod_load_sens != NULL)
    {
      Assert(vol_load_sens != NULL, ExcInternalError());
      Assert(surf_load_sens != NULL, ExcInternalError());
      Assert(nod_load_sens != NULL, ExcInternalError());
      this->volume_load_sens = vol_load_sens;
      this->surface_load_sens = surf_load_sens;
      this->nodal_load_sens = nod_load_sens;
    }
}
Member Data Documentation
Discipline::AnalysisDisciplineBase& FESystemElem::FESystemElemBase::analysis_discipline [protected]
the discipline that owns this element
Definition at line 739 of file FESystemElem.h.
Referenced by FEInterpolationElem::calculate_F().
const unsigned int FESystemElem::FESystemElemBase::dimension [protected]
dimension of the element
Definition at line 742 of file FESystemElem.h.
Referenced by FEInterpolationElem::calculate_F().
const unsigned int FESystemElem::FESystemElemBase::discipline_enumID [protected]
discipline of the element
Definition at line 748 of file FESystemElem.h.
std::vector<DenseVector<double> > FESystemElem::FESystemElemBase::dof_value_sensitivity_vec [protected]
vector of element dof values
Definition at line 824 of file FESystemElem.h.
std::vector<DenseVector<double> > FESystemElem::FESystemElemBase::dof_values_vec [protected]
vector of element dof values
Definition at line 821 of file FESystemElem.h.
ElementDataStorage* FESystemElem::FESystemElemBase::elem_data_storage [protected]
database for storing element quantities
Definition at line 779 of file FESystemElem.h.
unsigned int FESystemElem::FESystemElemBase::elem_ID [protected]
ID of the element.
Definition at line 751 of file FESystemElem.h.
Referenced by getID().
std::map<unsigned int, bool> FESystemElem::FESystemElemBase::elem_is_initialized_for_DV_map [protected]
boolean for keeping track of whether this element is initialized or not. This keeps track of each specific element for design points
Definition at line 806 of file FESystemElem.h.
Referenced by getID().
bool FESystemElem::FESystemElemBase::elem_is_initialized_for_property_sensitivity [protected]
boolean for keeping track of whether this element is initialized or not
Definition at line 767 of file FESystemElem.h.
ElemDataCard* FESystemElem::FESystemElemBase::elem_property_card [protected]
card that stores the information for this element
Definition at line 776 of file FESystemElem.h.
const unsigned int FESystemElem::FESystemElemBase::elem_type_enum_ID [protected]
enumID of the element kind
Definition at line 745 of file FESystemElem.h.
std::map<unsigned int, std::map<FEFamily, FEBase*> > FESystemElem::FESystemElemBase::fe_base_map_for_DV [protected]
finite element object for the element domain. This is stored for each design point.
Definition at line 827 of file FESystemElem.h.
Referenced by FEInterpolationElem::calculate_F(), and ~FESystemElemBase().
bool FESystemElem::FESystemElemBase::fe_quadrature_data_initialized [protected]
boolean for keeping track of whether the FEBase and QBase data structres have been initialized or not
Definition at line 764 of file FESystemElem.h.
std::map<unsigned int, std::map<FEFamily, FEBase*> > FESystemElem::FESystemElemBase::fe_side_map_for_DV [protected]
finite element object for the side. This is stored for each design point.
Definition at line 830 of file FESystemElem.h.
Referenced by ~FESystemElemBase().
std::map<unsigned int, Elem*> FESystemElem::FESystemElemBase::geometric_elems_for_DV_map [protected]
pointer to the base (unperturbed) element. There is one elem for each design point, including the base point and the perturbed points.
Definition at line 794 of file FESystemElem.h.
Referenced by FEInterpolationElem::calculate_F().
std::map<unsigned int, int > FESystemElem::FESystemElemBase::initialized_side_for_DV_map [protected]
keeps track of the initialized side that was initialized. This is stored for each design point.
boolean for keeping track of wheter this element is initialized for post processing or not
Definition at line 817 of file FESystemElem.h.
std::map<unsigned int, Elem*> FESystemElem::FESystemElemBase::local_elem_for_DV_map [protected]
local geometric element created in the element local axis. This is stored for each DV point, including the base design point, and all the perturbed DVs. This is essential for shape sensitivity
Definition at line 799 of file FESystemElem.h.
std::map<unsigned int, bool> FESystemElem::FESystemElemBase::local_elem_is_initialized_for_DV_map [protected]
boolean for keeping track of whether this element is initialized or not
Definition at line 809 of file FESystemElem.h.
Referenced by FEInterpolationElem::calculate_F(), and FESystemElem::PlateVonKarman::getPlateVonKarmanQty().
std::map<unsigned int, Node**> FESystemElem::FESystemElemBase::local_elem_nodes_for_DV_map [protected]
nodes created for the local element. These are stored for each DV
Definition at line 802 of file FESystemElem.h.
std::map<unsigned int, std::map<unsigned int, const Loads::NodalLoadCombination*> >* FESystemElem::FESystemElemBase::nodal_load_sens [protected]
Definition at line 790 of file FESystemElem.h.
std::map<unsigned int, std::map<unsigned int, const Loads::NodalLoadCombination*> >* FESystemElem::FESystemElemBase::nodal_loads [protected]
Definition at line 784 of file FESystemElem.h.
double FESystemElem::FESystemElemBase::perturbation [protected]
perturbation for a finite difference calculation
Definition at line 760 of file FESystemElem.h.
Referenced by FESystemElem::PlateVonKarman::getPlateVonKarmanQty().
bool FESystemElem::FESystemElemBase::property_card_initialized [protected]
boolean for keeping track of whether the property card was initialized
Definition at line 770 of file FESystemElem.h.
std::map<unsigned int, std::map<FEFamily, QBase*> > FESystemElem::FESystemElemBase::qbase_map_for_DV [protected]
quadrature rule for the element volume integration. This is stored for each design point.
Definition at line 833 of file FESystemElem.h.
Referenced by ~FESystemElemBase().
std::map<unsigned int, std::map<FEFamily, QBase*> > FESystemElem::FESystemElemBase::qbase_side_map_for_DV [protected]
quadrature rule for the side integration. This is stored for each design point.
Definition at line 836 of file FESystemElem.h.
Referenced by ~FESystemElemBase().
unsigned int FESystemElem::FESystemElemBase::sensitivity_parameter [protected]
type of the sensitivity parameter
Definition at line 757 of file FESystemElem.h.
Referenced by FEInterpolationElem::calculate_K(), and FESystemElem::PlateVonKarman::getPlateVonKarmanQty().
unsigned int FESystemElem::FESystemElemBase::sensitivity_parameter_ID [protected]
ID of the sensitivity parameter.
Definition at line 754 of file FESystemElem.h.
std::map<unsigned int, std::map<unsigned int, const Loads::SurfaceLoadCombination*> >* FESystemElem::FESystemElemBase::surface_load_sens [protected]
Definition at line 789 of file FESystemElem.h.
std::map<unsigned int, std::map<unsigned int, const Loads::SurfaceLoadCombination*> >* FESystemElem::FESystemElemBase::surface_loads [protected]
Definition at line 783 of file FESystemElem.h.
std::map<unsigned int, const Loads::VolumeLoadCombination*>* FESystemElem::FESystemElemBase::volume_load_sens [protected]
map of element load sensitivity for the current design variable for which computations are being done.
Definition at line 788 of file FESystemElem.h.
std::map<unsigned int, const Loads::VolumeLoadCombination*>* FESystemElem::FESystemElemBase::volume_loads [protected]
map of element loads
Definition at line 782 of file FESystemElem.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/FESystem/FESystemElem.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/FESystem/FESystemElem.C