fesystem: Solver::EigenSolverInfo Class Reference
Solver::EigenSolverInfo Class Reference
#include <EigenSolverInfo.h>
Public Member Functions
EigenSolverInfo ()
constructor
virtual ~EigenSolverInfo ()
destructor
unsigned int getEigenProblemKindEnumID () const
std::string getEigenProblemKindEnumName () const
unsigned int getEigenSolverKindEnumID () const
std::string getEigenSolverKindEnumName () const
unsigned int getLinearSolverInfoID () const
unsigned int getNEigenPairsToSolve () const
unsigned int getEigenSolverShiftKind () const
double getEigenSolverShiftValue () const
bool calculateEigenVectors () const
unsigned int getEigenSpectrumToCompute () const
double getTolerance () const
unsigned int getMaxAllowableIterations () const
bool ifSwapMatrices () const
virtual std::istream & readFromInputStream (std::istream &input)
reads from input
Protected Attributes
unsigned int problem_kind_enum_ID
kind of eigen problem
unsigned int eigen_solver_kind_enum_ID
kind of eigen solver
unsigned int linear_solver_info_ID
ID of linear solver info.
unsigned int n_eigen_pairs
number of eigen pairs to compute
bool calculate_eigen_vectors
if eigen vectors should also be computed
unsigned int solver_shift_kind_enum_ID
type of shift to apply to the solver
double solver_shift_value
value of shift
unsigned int eigen_spectrum_end
spectrum of eigen values to compute
double tolerance_value
value of tolerance
unsigned int maximum_iterations
value of tolerance
bool swtich_A_and_B_matrices
whether to switch the A and B matrices or not
Friends
std::istream & operator>> (std::istream &input, Solver::EigenSolverInfo &info)
overloaded input stream operator
Detailed Description
stores the information about an eigen solver. This information is used to configure the eigen solver
Definition at line 37 of file EigenSolverInfo.h.
Constructor & Destructor Documentation
Solver::EigenSolverInfo::EigenSolverInfo ()
constructor
Definition at line 10 of file EigenSolverInfo.C.
                                      :
Solver::SolverInfo(EIGEN_SOLVER_INFO::num(),
                   EIGEN_SOLVER::num()),
problem_kind_enum_ID(FESystemNumbers::InvalidID),
eigen_solver_kind_enum_ID(FESystemNumbers::InvalidID),
linear_solver_info_ID(0),
n_eigen_pairs(0),
calculate_eigen_vectors(false),
solver_shift_kind_enum_ID(FESystemNumbers::InvalidID),
solver_shift_value(0.0),
eigen_spectrum_end(FESystemNumbers::InvalidID),
tolerance_value(0.0),
maximum_iterations(FESystemNumbers::InvalidID),
swtich_A_and_B_matrices(false)
{
}
Solver::EigenSolverInfo::~EigenSolverInfo () [virtual]
destructor
Definition at line 29 of file EigenSolverInfo.C.
{
}
Member Function Documentation
bool Solver::EigenSolverInfo::calculateEigenVectors () const [inline]
Returns:
true/false if the eigen vectors should be calculated
Definition at line 198 of file EigenSolverInfo.h.
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->calculate_eigen_vectors;
}
unsigned int Solver::EigenSolverInfo::getEigenProblemKindEnumID () const [inline]
Returns:
problem kind enum ID
Definition at line 135 of file EigenSolverInfo.h.
References Solver::SolverInfo::initialized, and problem_kind_enum_ID.
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->problem_kind_enum_ID;
}
std::string Solver::EigenSolverInfo::getEigenProblemKindEnumName () const [inline]
Returns:
problem kind enum name
Definition at line 146 of file EigenSolverInfo.h.
{
  Assert(this->initialized,
         ExcInvalidState());
  return Solver::EigenProblemKindEnum::enumName(this->problem_kind_enum_ID);
}
unsigned int Solver::EigenSolverInfo::getEigenSolverKindEnumID () const [inline]
Returns:
eigen solver kind enum ID
Definition at line 156 of file EigenSolverInfo.h.
Referenced by Solver::createEigenSolver().
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->eigen_solver_kind_enum_ID;
}
std::string Solver::EigenSolverInfo::getEigenSolverKindEnumName () const [inline]
Returns:
eigen solver kind enum name
Definition at line 167 of file EigenSolverInfo.h.
{
  Assert(this->initialized,
         ExcInvalidState());
  return Solver::EigenSolverKindEnum::enumName(this->eigen_solver_kind_enum_ID);
}
unsigned int Solver::EigenSolverInfo::getEigenSolverShiftKind () const [inline]
Returns:
the type of shift to apply to the eigen solver
Definition at line 220 of file EigenSolverInfo.h.
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->solver_shift_kind_enum_ID;
}
double Solver::EigenSolverInfo::getEigenSolverShiftValue () const [inline]
Returns:
the value of the eigen solver shift
Definition at line 231 of file EigenSolverInfo.h.
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->solver_shift_value;
}
unsigned int Solver::EigenSolverInfo::getEigenSpectrumToCompute () const [inline]
Returns:
the eigen spectrum end to compute
Definition at line 209 of file EigenSolverInfo.h.
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->eigen_spectrum_end;
}
unsigned int Solver::EigenSolverInfo::getLinearSolverInfoID () const [inline]
Returns:
linear solver info ID for this solver
Definition at line 177 of file EigenSolverInfo.h.
Referenced by Solution::AeroelasticitySolution::aeroelasticSolve(), and Solution::SolutionBase::eigenSolve().
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->linear_solver_info_ID;
}
unsigned int Solver::EigenSolverInfo::getMaxAllowableIterations () const [inline]
Returns:
the tolerance of the solver
Definition at line 251 of file EigenSolverInfo.h.
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->maximum_iterations;
}
unsigned int Solver::EigenSolverInfo::getNEigenPairsToSolve () const [inline]
Returns:
number of eigen pairs to solve
Definition at line 188 of file EigenSolverInfo.h.
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->n_eigen_pairs;
}
double Solver::EigenSolverInfo::getTolerance () const [inline]
Returns:
the tolerance of the solver
Definition at line 241 of file EigenSolverInfo.h.
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->tolerance_value;
}
bool Solver::EigenSolverInfo::ifSwapMatrices () const [inline]
Returns:
boolean stating whether the A and B matrices should be switched before using the other parameters that the user has set for the solver
Definition at line 261 of file EigenSolverInfo.h.
{
  Assert(this->initialized,
         ExcInvalidState());
  return this->swtich_A_and_B_matrices;
}
std::istream & Solver::EigenSolverInfo::readFromInputStream (std::istream & input) [virtual]
reads from input
Implements Solver::SolverInfo.
Definition at line 36 of file EigenSolverInfo.C.
References FESystemIOUtility::readFromInput().
{
  std::string tag;
  FESystemIOUtility::readFromInput(input, EIGEN_SOLVER_INFO::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->ID);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "EIGEN_SOLVER_TYPE", tag);
  this->eigen_solver_kind_enum_ID = Solver::EigenSolverKindEnum::enumID(tag);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "EIGEN_PROBLEM_TYPE", tag);
  this->problem_kind_enum_ID = Solver::EigenProblemKindEnum::enumID(tag);
  FESystemIOUtility::readFromInput(input, "SWAP_A_AND_B_MATRICES",
                                   this->swtich_A_and_B_matrices);
  FESystemIOUtility::readFromInput(input, "LINEAR_SOLVER_INFO_ID", this->linear_solver_info_ID);
  FESystemIOUtility::readFromInput(input, "N_EIGEN_PAIRS", this->n_eigen_pairs);
  FESystemIOUtility::readFromInput(input, "CALCULATE_EIGEN_VECTORS", this->calculate_eigen_vectors);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "EIGEN_SHIFT_TYPE", tag);
  this->solver_shift_kind_enum_ID = Solver::EigenSolutionShiftKindEnum::enumID(tag);
  FESystemIOUtility::readFromInput(input, "EIGEN_SHIFT_VALUE", this->solver_shift_value);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "EIGEN_SPECTRUM_END_TO_CALCULATE", tag);
  this->eigen_spectrum_end = Solver::EigenSolutionSpectrumKindEnum::enumID(tag);
  FESystemIOUtility::readFromInput(input, "TOLERANCE", this->tolerance_value);
  FESystemIOUtility::readFromInput(input, "MAX_ITERATIONS", this->maximum_iterations);
  FESystemIOUtility::readFromInput(input, EIGEN_SOLVER_INFO::name());
  FESystemIOUtility::readFromInput(input, "END");
  this->initialized = true;
  return input;
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, Solver::EigenSolverInfo & info) [friend]
overloaded input stream operator
Member Data Documentation
bool Solver::EigenSolverInfo::calculate_eigen_vectors [protected]
if eigen vectors should also be computed
Definition at line 109 of file EigenSolverInfo.h.
unsigned int Solver::EigenSolverInfo::eigen_solver_kind_enum_ID [protected]
kind of eigen solver
Definition at line 100 of file EigenSolverInfo.h.
unsigned int Solver::EigenSolverInfo::eigen_spectrum_end [protected]
spectrum of eigen values to compute
Definition at line 118 of file EigenSolverInfo.h.
unsigned int Solver::EigenSolverInfo::linear_solver_info_ID [protected]
ID of linear solver info.
Definition at line 103 of file EigenSolverInfo.h.
unsigned int Solver::EigenSolverInfo::maximum_iterations [protected]
value of tolerance
Definition at line 124 of file EigenSolverInfo.h.
unsigned int Solver::EigenSolverInfo::n_eigen_pairs [protected]
number of eigen pairs to compute
Definition at line 106 of file EigenSolverInfo.h.
unsigned int Solver::EigenSolverInfo::problem_kind_enum_ID [protected]
kind of eigen problem
Definition at line 97 of file EigenSolverInfo.h.
Referenced by getEigenProblemKindEnumID().
unsigned int Solver::EigenSolverInfo::solver_shift_kind_enum_ID [protected]
type of shift to apply to the solver
Definition at line 112 of file EigenSolverInfo.h.
double Solver::EigenSolverInfo::solver_shift_value [protected]
value of shift
Definition at line 115 of file EigenSolverInfo.h.
bool Solver::EigenSolverInfo::swtich_A_and_B_matrices [protected]
whether to switch the A and B matrices or not
Definition at line 127 of file EigenSolverInfo.h.
double Solver::EigenSolverInfo::tolerance_value [protected]
value of tolerance
Definition at line 121 of file EigenSolverInfo.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/EigenSolverInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/EigenSolverInfo.C