fesystem: Solver::NonlinearSolverInfo Class Reference
Solver::NonlinearSolverInfo Class Reference
this class stores the information for initialization of a nonlinear solver.
#include <NonlinearSolverInfo.h>
Public Member Functions
NonlinearSolverInfo ()
constructor
virtual ~NonlinearSolverInfo ()
destructor
virtual unsigned int getNonlinearSolverKindEnumID () const
virtual const std::string getNonlinearSolverKindEnumName () const
unsigned int getLinearSolverInfoID () const
unsigned int getMaximumIterations () const
double getConvergenceTolerance () const
virtual std::istream & readFromInputStream (std::istream &input)
reads from the input stream
Protected Attributes
unsigned int nonlinear_solver_kind_enum_ID
solver kind enum ID
unsigned int linear_solver_info_ID
LinearSolverInfo ID.
unsigned int max_iters
max iterations
double tolerance
tolerance
Friends
std::istream & operator>> (std::istream &input, Solver::NonlinearSolverInfo &info)
overloaded stream input operator for this class
Detailed Description
this class stores the information for initialization of a nonlinear solver.
Definition at line 32 of file NonlinearSolverInfo.h.
Constructor & Destructor Documentation
Solver::NonlinearSolverInfo::NonlinearSolverInfo ()
constructor
Definition at line 10 of file NonlinearSolverInfo.C.
                                              :
Solver::SolverInfo(NONLINEAR_SOLVER_INFO::num(),
                   NONLINEAR_SOLVER::num()),
nonlinear_solver_kind_enum_ID(FESystemNumbers::InvalidID),
linear_solver_info_ID(FESystemNumbers::InvalidID),
max_iters(FESystemNumbers::InvalidID),
tolerance(0.0)
{
}
Solver::NonlinearSolverInfo::~NonlinearSolverInfo () [virtual]
destructor
Definition at line 22 of file NonlinearSolverInfo.C.
{
}
Member Function Documentation
double Solver::NonlinearSolverInfo::getConvergenceTolerance () const [inline]
Returns:
the maximum tolerance to define convergence of this solver
Definition at line 116 of file NonlinearSolverInfo.h.
{
  return this->tolerance;
}
unsigned int Solver::NonlinearSolverInfo::getLinearSolverInfoID () const [inline]
Returns:
the solver info ID for LinearSolver to be used for this NonlinearSolver
Definition at line 100 of file NonlinearSolverInfo.h.
Referenced by Solution::SolutionBase::nonlinearSolve(), and Solution::SolutionBase::nonlinearTransientSolve().
{
  return this->linear_solver_info_ID;
}
unsigned int Solver::NonlinearSolverInfo::getMaximumIterations () const [inline]
Returns:
the maximum number of iterations for this solver
Definition at line 108 of file NonlinearSolverInfo.h.
{
  return this->max_iters;
}
unsigned int Solver::NonlinearSolverInfo::getNonlinearSolverKindEnumID () const [inline, virtual]
Returns:
enum ID of the nonlinear solver kind
Definition at line 83 of file NonlinearSolverInfo.h.
References nonlinear_solver_kind_enum_ID.
Referenced by Solver::createNonlinearSolver().
{
  return this->nonlinear_solver_kind_enum_ID;
}
const std::string Solver::NonlinearSolverInfo::getNonlinearSolverKindEnumName () const [inline, virtual]
Returns:
enum name of the nonlinear solver kind
Definition at line 92 of file NonlinearSolverInfo.h.
{
  return Solver::NonlinearSolverKindEnum::enumName(this->nonlinear_solver_kind_enum_ID);
}
std::istream & Solver::NonlinearSolverInfo::readFromInputStream (std::istream & input) [virtual]
reads from the input stream
Implements Solver::SolverInfo.
Definition at line 29 of file NonlinearSolverInfo.C.
References FESystemIOUtility::readFromInput().
{
  std::string tag;
  FESystemIOUtility::readFromInput(input, NONLINEAR_SOLVER_INFO::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "ID", this->ID);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "SOLVER_TYPE", tag);
  this->nonlinear_solver_kind_enum_ID = Solver::NonlinearSolverKindEnum::enumID(tag);
  FESystemIOUtility::readFromInput(input, "LINEAR_SOLVER_INFO_ID",
                                   this->linear_solver_info_ID);
  FESystemIOUtility::readFromInput(input, "MAXIMUM_ITERATIONS",
                                   this->max_iters);
  FESystemIOUtility::readFromInput(input, "CONVERGENCE_TOLERANCE",
                                   this->tolerance);
  FESystemIOUtility::readFromInput(input, NONLINEAR_SOLVER_INFO::name());
  FESystemIOUtility::readFromInput(input, "END");
  this->initialized = true;
  return input;
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, Solver::NonlinearSolverInfo & info) [friend]
overloaded stream input operator for this class
Member Data Documentation
unsigned int Solver::NonlinearSolverInfo::linear_solver_info_ID [protected]
LinearSolverInfo ID.
Definition at line 71 of file NonlinearSolverInfo.h.
unsigned int Solver::NonlinearSolverInfo::max_iters [protected]
max iterations
Definition at line 74 of file NonlinearSolverInfo.h.
unsigned int Solver::NonlinearSolverInfo::nonlinear_solver_kind_enum_ID [protected]
solver kind enum ID
Definition at line 68 of file NonlinearSolverInfo.h.
Referenced by getNonlinearSolverKindEnumID().
double Solver::NonlinearSolverInfo::tolerance [protected]
tolerance
Definition at line 77 of file NonlinearSolverInfo.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/NonlinearSolverInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/NonlinearSolverInfo.C