fesystem: ElemPostProcessQty Class Reference
ElemPostProcessQty Class Reference
#include <ElemPostProcessQty.h>
Public Member Functions
ElemPostProcessQty (unsigned int elem_ID)
~ElemPostProcessQty ()
destructor
unsigned int getElemID () const
get the element ID of the quantity
void addStressTensor (TensorValue< double > &value, unsigned int load_case, unsigned int DV_ID=0)
void addStrainTensor (TensorValue< double > &value, unsigned int load_case, unsigned int DV_ID=0)
void addMechanicalStrainTensor (TensorValue< double > &value, unsigned int load_case, unsigned int DV_ID=0)
TensorValue< double > & getStressTensor (unsigned int load_case, unsigned int DV_ID=0)
TensorValue< double > & getStrainTensor (unsigned int load_case, unsigned int DV_ID=0)
TensorValue< double > & getMechanicalStrainTensor (unsigned int load_case, unsigned int DV_ID=0)
TensorValue< double > & getPrincipalStressTensor (unsigned int load_case, unsigned int DV_ID=0)
double getStrainEnergyDensity (unsigned int load_case, unsigned int DV_ID=0)
double getVonMisesStress (unsigned int load_case, unsigned int DV_ID=0)
Protected Member Functions
void calculatePrincipalStressTensor (unsigned int load_case, unsigned int DV_ID=0)
Protected Attributes
bool calculated_principal_stress
bool, whether the principal stresses have been calculated or not
unsigned int elem_ID
elem ID
Detailed Description
Definition at line 19 of file ElemPostProcessQty.h.
Constructor & Destructor Documentation
ElemPostProcessQty::ElemPostProcessQty (unsigned int elem_ID)
constructor
Parameters:
element ID
Definition at line 15 of file ElemPostProcessQty.C.
                                                        :
  PostProcessQty(),
  calculated_principal_stress(false),
  elem_ID(el_ID)
{
}
ElemPostProcessQty::~ElemPostProcessQty ()
destructor
Definition at line 24 of file ElemPostProcessQty.C.
{
}
Member Function Documentation
void ElemPostProcessQty::addMechanicalStrainTensor (TensorValue< double > & value, unsigned int load_case, unsigned int DV_ID = 0)
adds mechanical strain tensor + T
Parameters:
tensor to be stored
load case ID for which the value is being stored
Design variable ID if the value is sensitivity
Definition at line 81 of file ElemPostProcessQty.C.
References PostProcessQty::addTensor().
{
  std::string name;
  name = "MechanicalStrain";
  std::ostringstream stream;
  stream << "_lc_" << load_case;
  if (DV_ID != 0)
    {
      stream <<  "_dv_" << DV_ID;
    }
  name += stream.str();
  this->addTensor(name, value);
}
void ElemPostProcessQty::addStrainTensor (TensorValue< double > & value, unsigned int load_case, unsigned int DV_ID = 0)
adds strain tensor
Parameters:
tensor to be stored
load case ID for which the value is being stored
Design variable ID if the value is sensitivity
Definition at line 61 of file ElemPostProcessQty.C.
References PostProcessQty::addTensor().
{
  std::string name;
  name = "Strain";
  std::ostringstream stream;
  stream << "_lc_" << load_case;
  if (DV_ID != 0)
    {
      stream <<  "_dv_" << DV_ID;
    }
  name += stream.str();
  this->addTensor(name, value);
}
void ElemPostProcessQty::addStressTensor (TensorValue< double > & value, unsigned int load_case, unsigned int DV_ID = 0)
adds stress tensor
Parameters:
tensor to be stored
load case ID for which the value is being stored
Design variable ID if the value is sensitivity
Definition at line 40 of file ElemPostProcessQty.C.
References PostProcessQty::addTensor().
{
  std::string name;
  name = "Stress";
  std::ostringstream stream;
  stream << "_lc_" << load_case;
  if (DV_ID != 0)
    {
      stream <<  "_dv_" << DV_ID;
    }
  name += stream.str();
  this->addTensor(name, value);
}
void ElemPostProcessQty::calculatePrincipalStressTensor (unsigned int load_case, unsigned int DV_ID = 0) [protected]
calculates the principal stress
Parameters:
load case ID for which the value is being stored
Design variable ID if the value is sensitivity
Definition at line 142 of file ElemPostProcessQty.C.
References PostProcessQty::addTensor(), calculated_principal_stress, and getStressTensor().
Referenced by getPrincipalStressTensor().
{
  std::string name;
  name = "PrincipalStress";
  std::ostringstream stream;
  stream << "_lc_" << load_case;
  if (DV_ID != 0)
    {
      stream <<  "_dv_" << DV_ID;
    }
  name += stream.str();
  // for now, do this for a case without sensitivity
  assert (DV_ID == 0);
  TensorValue<double>& stress =
    this->getStressTensor(load_case);
  TensorValue<double> value;
  value(0,0) = (stress(0,0) + stress(1,1))*0.5 +
    pow( pow((stress(0,0) - stress(1,1))*0.5, 2) + stress(0,1)*stress(0,1), 0.5);
  value(1,1) = (stress(0,0) + stress(1,1))*0.5 -
    pow( pow((stress(0,0) - stress(1,1))*0.5, 2) + stress(0,1)*stress(0,1), 0.5);
  this->addTensor(name, value);
  this->calculated_principal_stress = true;
}
unsigned int ElemPostProcessQty::getElemID () const
get the element ID of the quantity
Definition at line 32 of file ElemPostProcessQty.C.
References elem_ID.
{
  return this->elem_ID;
}
TensorValue< double > & ElemPostProcessQty::getMechanicalStrainTensor (unsigned int load_case, unsigned int DV_ID = 0)
gets mechanical strain tensor
Parameters:
load case ID for which the value is being stored
Design variable ID if the value is sensitivity
Definition at line 202 of file ElemPostProcessQty.C.
References PostProcessQty::getTensor().
Referenced by getStrainEnergyDensity().
{
  std::string name;
  name = "MechanicalStrain";
  std::ostringstream stream;
  stream << "_lc_" << load_case;
  if (DV_ID != 0)
    {
      stream <<  "_dv_" << DV_ID;
    }
  name += stream.str();
  return this->getTensor(name);
}
TensorValue< double > & ElemPostProcessQty::getPrincipalStressTensor (unsigned int load_case, unsigned int DV_ID = 0)
returns the principal stress tensor
Parameters:
load case ID for which the value is being stored
Design variable ID if the value is sensitivity
Definition at line 177 of file ElemPostProcessQty.C.
References calculated_principal_stress, calculatePrincipalStressTensor(), and PostProcessQty::getTensor().
Referenced by getVonMisesStress().
{
  if (!this->calculated_principal_stress)
    this->calculatePrincipalStressTensor(load_case, DV_ID);
  std::string name;
  name = "PrincipalStress";
  std::ostringstream stream;
  stream << "_lc_" << load_case;
  if (DV_ID != 0)
    {
      stream <<  "_dv_" << DV_ID;
    }
  name += stream.str();
  return this->getTensor(name);
}
double ElemPostProcessQty::getStrainEnergyDensity (unsigned int load_case, unsigned int DV_ID = 0)
returns the strain energy density
Parameters:
load case ID for which the value is being stored
Design variable ID if the value is sensitivity
Definition at line 222 of file ElemPostProcessQty.C.
References getMechanicalStrainTensor(), and getStressTensor().
{
  // get the stress and mechanical strain.
  if (DV_ID == 0)
    {
      TensorValue<double>& stress = this->getStressTensor(load_case);
      TensorValue<double>& strain = this->getMechanicalStrainTensor(load_case);
      // multiply the two to get the strain energy
      double strain_energy_density = 0.0;
      for (unsigned int i=0; i<2; i++)
        for (unsigned int j=0; j<2; j++)
          strain_energy_density += stress(i,j)*strain(i,j) ;
      return strain_energy_density * 0.5;
    }
  else
    {
      // get the sensitivity and strain
      TensorValue<double>& stress = this->getStressTensor(load_case);
      TensorValue<double>& strain = this->getMechanicalStrainTensor(load_case);
      TensorValue<double>& stress_sens = this->getStressTensor(load_case, DV_ID);
      TensorValue<double>& strain_sens = this->getMechanicalStrainTensor(load_case, DV_ID);
      double strain_energy_density_sens = 0.0;
      for (unsigned int i=0; i<2; i++)
        for (unsigned int j=0; j<2; j++)
          strain_energy_density_sens += stress_sens(i,j)*strain(i,j) +
            stress(i,j) * strain_sens(i,j);
      return strain_energy_density_sens * 0.5;
    }
}
TensorValue< double > & ElemPostProcessQty::getStrainTensor (unsigned int load_case, unsigned int DV_ID = 0)
gets strain tensor
Parameters:
load case ID for which the value is being stored
Design variable ID if the value is sensitivity
Definition at line 122 of file ElemPostProcessQty.C.
References PostProcessQty::getTensor().
{
  std::string name;
  name = "Strain";
  std::ostringstream stream;
  stream << "_lc_" << load_case;
  if (DV_ID != 0)
    {
      stream <<  "_dv_" << DV_ID;
    }
  name += stream.str();
  return this->getTensor(name);
}
TensorValue< double > & ElemPostProcessQty::getStressTensor (unsigned int load_case, unsigned int DV_ID = 0)
gets stress tensor
Parameters:
load case ID for which the value is being stored
Design variable ID if the value is sensitivity
Definition at line 102 of file ElemPostProcessQty.C.
References PostProcessQty::getTensor().
Referenced by calculatePrincipalStressTensor(), and getStrainEnergyDensity().
{
  std::string name;
  name = "Stress";
  std::ostringstream stream;
  stream << "_lc_" << load_case;
  if (DV_ID != 0)
    {
      stream <<  "_dv_" << DV_ID;
    }
  name += stream.str();
  return this->getTensor(name);
}
double ElemPostProcessQty::getVonMisesStress (unsigned int load_case, unsigned int DV_ID = 0)
returns the vonmises stress
Parameters:
load case ID for which the value is being stored
Design variable ID if the value is sensitivity
Definition at line 261 of file ElemPostProcessQty.C.
References getPrincipalStressTensor().
{
  // for now, this is only for a case without sensitiity. Hence, make sure that
  // DV_ID = 0;
  assert (DV_ID == 0);
  TensorValue<double>& principal = this->getPrincipalStressTensor(load_case);
  double von_mises = 0.0;
  von_mises =
    pow( principal(0,0) - principal(1,1) , 2) +
    principal(0,0)*principal(0,0) +
    principal(1,1)*principal(1,1);
  von_mises = pow(von_mises*0.5, 0.5);
  return von_mises;
}
Member Data Documentation
bool ElemPostProcessQty::calculated_principal_stress [protected]
bool, whether the principal stresses have been calculated or not
Definition at line 97 of file ElemPostProcessQty.h.
Referenced by calculatePrincipalStressTensor(), and getPrincipalStressTensor().
unsigned int ElemPostProcessQty::elem_ID [protected]
elem ID
Definition at line 100 of file ElemPostProcessQty.h.
Referenced by getElemID().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/PostProcess/ElemPostProcessQty.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/PostProcess/ElemPostProcessQty.C