fesystem: FESystem::AnalysisCase Class Reference
FESystem::AnalysisCase Class Reference
#include <AnalysisCase.h>
Public Member Functions
AnalysisCase ()
constructor
~AnalysisCase ()
destructor
const std::string & getTitle () const
const Discipline::DisciplineInfo & getAnalysisDisciplineInfo (const unsigned int discipline) const
std::vector
< Discipline::DisciplineInfo * > & getAnalysisDisciplineInfos ()
std::vector
< Solution::SolutionBase * > getSolutions ()
double getRealParameter (const std::string &name) const
unsigned int getIntegerParameter (const std::string &name) const
std::string getStringParameter (const std::string &name) const
std::istream & readFromInputStream (std::istream &input)
reads from the input stream
const OutputInfo & getOutputInfo () const
const Solver::SolverInfo & getSolverInfo (const unsigned int ID) const
const InterpolationCase & getInterpolationCase (const unsigned int case_ID) const
Protected Types
typedef std::map< unsigned int,
Solver::SolverInfo * > IDToSolverInfoMap
typedef std::map< std::string,
unsigned int > IntegerParameterMap
typedef std::map< std::string,
double > RealParameterMap
typedef std::map< std::string,
std::string > StringParameterMap
typedef std::map< unsigned int,
Discipline::DisciplineInfo * > DisciplineInfoMap
typedef std::map< unsigned int,
Solution::SolutionBase * > SolutionBaseMap
Protected Member Functions
void addInterpolationCase (InterpolationCase *ipcase)
adds the InterpolationCase to this object
void addSolverInfo (Solver::SolverInfo *info)
adds the SolverInfo to this object
void addAnalysisDisciplineInfo (Discipline::DisciplineInfo *info)
adds the AnalysisDiscipline to this object
void addSolutionBase (Solution::SolutionBase *info)
adds the SolutionBase to this object
DeclException1 (ExcParameterNameDoesNotExist, std::string &,<< "Parameter Name: "<< arg1<< "does not exist.")
DeclException1 (ExcDuplicateParameterName, std::string &,<< "Parameter Name: "<< arg1<< "already exists.")
Protected Attributes
std::string analysis_title
title of the analysis
OutputInfo * output_info
output format
std::map< unsigned int,
InterpolationCase * > interpolation_case_map
interpolation case
DisciplineInfoMap discipline_info_map
map of discipline info for each discipline
IDToSolverInfoMap ID_to_solver_info_map
map of ID to solver info
SolutionBaseMap solution_base_map
map of solutions
IntegerParameterMap integer_params
integer parameter map
RealParameterMap float_params
real parameter map
StringParameterMap string_params
string parameters
Detailed Description
Definition at line 40 of file AnalysisCase.h.
Member Typedef Documentation
typedef std::map<unsigned int, Discipline::DisciplineInfo*> FESystem::AnalysisCase::DisciplineInfoMap [protected]
Definition at line 121 of file AnalysisCase.h.
typedef std::map<unsigned int, Solver::SolverInfo*> FESystem::AnalysisCase::IDToSolverInfoMap [protected]
Definition at line 117 of file AnalysisCase.h.
typedef std::map<std::string, unsigned int> FESystem::AnalysisCase::IntegerParameterMap [protected]
Definition at line 118 of file AnalysisCase.h.
typedef std::map<std::string, double> FESystem::AnalysisCase::RealParameterMap [protected]
Definition at line 119 of file AnalysisCase.h.
typedef std::map<unsigned int, Solution::SolutionBase*> FESystem::AnalysisCase::SolutionBaseMap [protected]
Definition at line 122 of file AnalysisCase.h.
typedef std::map<std::string, std::string> FESystem::AnalysisCase::StringParameterMap [protected]
Definition at line 120 of file AnalysisCase.h.
Constructor & Destructor Documentation
FESystem::AnalysisCase::AnalysisCase ()
constructor
Definition at line 15 of file AnalysisCase.C.
                                  :
analysis_title (),
output_info(NULL)
{
}
FESystem::AnalysisCase::~AnalysisCase ()
destructor
Definition at line 27 of file AnalysisCase.C.
{
  // delete the info data structs
  if (this->output_info != NULL)
    {
    delete this->output_info;
    this->output_info = NULL;
    }
//  if (this->interpolation_case != NULL)
//    {
//    delete this->interpolation_case;
//    this->interpolation_case = NULL;
//    }
  {
    // and also the solver info in the map
    FESystem::AnalysisCase::IDToSolverInfoMap::iterator it, end;
    it = this->ID_to_solver_info_map.begin();
    end = this->ID_to_solver_info_map.end();
    for (; it != end; it++)
      {
      delete it->second;
      it->second = NULL;
      }
    this->ID_to_solver_info_map.clear();
  }
  {
    // and also the solver info in the map
    FESystem::AnalysisCase::DisciplineInfoMap::iterator it, end;
    it = this->discipline_info_map.begin();
    end = this->discipline_info_map.end();
    for (; it != end; it++)
      {
      delete it->second;
      it->second = NULL;
      }
    this->discipline_info_map.clear();
  }
  {
    // and also the solver info in the map
    FESystem::AnalysisCase::SolutionBaseMap::iterator it, end;
    it = this->solution_base_map.begin();
    end = this->solution_base_map.end();
    for (; it != end; it++)
      {
      delete it->second;
      it->second = NULL;
      }
    this->solution_base_map.clear();
  }
}
Member Function Documentation
void FESystem::AnalysisCase::addAnalysisDisciplineInfo (Discipline::DisciplineInfo * info) [protected]
adds the AnalysisDiscipline to this object
Definition at line 325 of file AnalysisCase.C.
References Discipline::DisciplineInfo::getDisciplineEnumID().
{
  unsigned int ID = info->getDisciplineEnumID();
  bool insert_success = this->discipline_info_map.insert
    (FESystem::AnalysisCase::DisciplineInfoMap::value_type(ID, info)).second;
  Assert(insert_success, FESystemExceptions::ExcDuplicateID("Discipline", ID));
}
void FESystem::AnalysisCase::addInterpolationCase (InterpolationCase * ipcase) [protected]
adds the InterpolationCase to this object
Definition at line 339 of file AnalysisCase.C.
References InterpolationCase::ID().
{
  unsigned int ID = ipcase->ID();
  bool insert_success = this->interpolation_case_map.insert
    (std::map<unsigned int, InterpolationCase*>::value_type(ID, ipcase)).second;
  Assert(insert_success, FESystemExceptions::ExcDuplicateID("InterpolationCase", ID));
}
void FESystem::AnalysisCase::addSolutionBase (Solution::SolutionBase * info) [protected]
adds the SolutionBase to this object
Definition at line 366 of file AnalysisCase.C.
References Solution::SolutionBase::getID().
{
  unsigned int ID = info->getID();
  bool insert_success = this->solution_base_map.insert
    (FESystem::AnalysisCase::SolutionBaseMap::value_type(ID, info)).second;
  Assert(insert_success, FESystemExceptions::ExcDuplicateID("Solution", ID));
}
void FESystem::AnalysisCase::addSolverInfo (Solver::SolverInfo * info) [protected]
adds the SolverInfo to this object
Definition at line 353 of file AnalysisCase.C.
References Solver::SolverInfo::getID().
{
  unsigned int ID = info->getID();
  bool insert_success = this->ID_to_solver_info_map.insert
    (FESystem::AnalysisCase::IDToSolverInfoMap::value_type(ID, info)).second;
  Assert(insert_success, FESystemExceptions::ExcDuplicateID("Solver", ID));
}
FESystem::AnalysisCase::DeclException1 (ExcParameterNameDoesNotExist , std::string & , << "Parameter Name: "<< arg1<< "does not exist.") [protected]
FESystem::AnalysisCase::DeclException1 (ExcDuplicateParameterName , std::string & , << "Parameter Name: "<< arg1<< "already exists.") [protected]
const Discipline::DisciplineInfo & FESystem::AnalysisCase::getAnalysisDisciplineInfo (const unsigned int discipline) const [inline]
Returns:
the analysis discipline
Definition at line 162 of file AnalysisCase.h.
{
  FESystem::AnalysisCase::DisciplineInfoMap::const_iterator it, end;
  it = this->discipline_info_map.find(discipline);
  end = this->discipline_info_map.end();
  Assert(it != end, FESystemExceptions::ExcIDDoesNotExist("Discipline", discipline));
  return *(it->second);
}
std::vector< Discipline::DisciplineInfo * > & FESystem::AnalysisCase::getAnalysisDisciplineInfos ()
Returns:
all analysis disciplines
Definition at line 88 of file AnalysisCase.C.
{
  static std::vector<Discipline::DisciplineInfo*> infos;
  if (infos.size() == 0)
  {
  FESystem::AnalysisCase::DisciplineInfoMap::iterator it, end;
  it = this->discipline_info_map.begin();
  end = this->discipline_info_map.end();
  for ( ; it != end; it++)
    infos.push_back(it->second);
  }
  return infos;
}
unsigned int FESystem::AnalysisCase::getIntegerParameter (const std::string & name) const [inline]
Returns:
the integer parameter with the given name
Parameters:
name name of the parameter
Definition at line 196 of file AnalysisCase.h.
{
  FESystem::AnalysisCase::IntegerParameterMap::const_iterator
  param_it = this->integer_params.find(name);
  Assert(param_it != this->integer_params.end(),
         FESystem::AnalysisCase::ExcParameterNameDoesNotExist(name));
  return param_it->second;
}
const InterpolationCase & FESystem::AnalysisCase::getInterpolationCase (const unsigned int case_ID) const [inline]
Returns:
the interpolation case referenced by the ID
Definition at line 259 of file AnalysisCase.h.
{
  std::map<unsigned int, InterpolationCase*>::const_iterator it, end;
  it = this->interpolation_case_map.find(case_ID);
  end = this->interpolation_case_map.end();
  AssertThrow(it != end, ExcInternalError());
  return *(it->second);
}
const OutputInfo & FESystem::AnalysisCase::getOutputInfo () const [inline]
Returns:
reference to the output info data structure
Definition at line 228 of file AnalysisCase.h.
{
  Assert(this->output_info != NULL,
         ExcEmptyObject());
  return *(this->output_info);
}
double FESystem::AnalysisCase::getRealParameter (const std::string & name) const [inline]
Returns:
the real parameter with the given name
Parameters:
name name of the parameter
Definition at line 180 of file AnalysisCase.h.
{
  FESystem::AnalysisCase::RealParameterMap::const_iterator
  param_it = this->float_params.find(name);
  Assert(param_it != this->float_params.end(),
         FESystem::AnalysisCase::ExcParameterNameDoesNotExist(name));
  return param_it->second;
}
std::vector< Solution::SolutionBase * > FESystem::AnalysisCase::getSolutions ()
Returns:
a vector containing the solutions for analysis
Definition at line 108 of file AnalysisCase.C.
{
  std::vector<Solution::SolutionBase*> vec;
  FESystem::AnalysisCase::SolutionBaseMap::iterator it, end;
  it = this->solution_base_map.begin();
  end = this->solution_base_map.end();
  for (; it != end; it++)
    vec.push_back(it->second);
  return vec;
}
const Solver::SolverInfo & FESystem::AnalysisCase::getSolverInfo (const unsigned int ID) const [inline]
Returns:
the solver info for the given ID
Definition at line 241 of file AnalysisCase.h.
{
  FESystem::AnalysisCase::IDToSolverInfoMap::const_iterator
  param_it = this->ID_to_solver_info_map.find(ID);
  Assert(param_it != this->ID_to_solver_info_map.end(),
         ExcInternalError());
        Assert(param_it->second != NULL,
         ExcEmptyObject());
  return *(param_it->second);
}
std::string FESystem::AnalysisCase::getStringParameter (const std::string & name) const [inline]
Returns:
the file name
Parameters:
name name of the parameter for which file name is to be obtained
Definition at line 213 of file AnalysisCase.h.
{
  FESystem::AnalysisCase::StringParameterMap::const_iterator
  param_it = this->string_params.find(name);
  Assert(param_it != this->string_params.end(),
         FESystem::AnalysisCase::ExcParameterNameDoesNotExist(name));
  return param_it->second;
}
const std::string & FESystem::AnalysisCase::getTitle () const [inline]
Returns:
the title for analysis
Definition at line 152 of file AnalysisCase.h.
References analysis_title.
{
  return this->analysis_title;
}
std::istream & FESystem::AnalysisCase::readFromInputStream (std::istream & input)
reads from the input stream
Definition at line 125 of file AnalysisCase.C.
References Discipline::createDisciplineInfo(), Solution::createSolutionBase(), Solver::createSolverInfo(), info, FESystemIOUtility::peekFromInput(), FESystemIOUtility::readFromInput(), and InterpolationCase::readFromInputStream().
{
  std::string tag;
  unsigned int num = 0;
  unsigned int enum_ID = 0;
  bool insert_success = false;
  // this will begin with BEGIN_ANALYSIS_CASE
  FESystemIOUtility::readFromInput(input, "ANALYSIS_CASE");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  // read  in the title
  FESystemIOUtility::readFromInput(input, "ANALYSIS_TITLE", this->analysis_title);
  // now read the analysis discipline
  FESystemIOUtility::readFromInput(input, "N_ANALYSIS_DISCIPLINE_INFO", num);
  for (unsigned int i = 0; i < num; i++)
    {
    tag.clear();
    FESystemIOUtility::peekFromInput(input, tag);
    enum_ID = Discipline::DisciplineInfoTypeEnum::enumID(tag);
    Discipline::DisciplineInfo *info =
      Discipline::createDisciplineInfo(enum_ID).release();
    input >> (*info);
    this->addAnalysisDisciplineInfo(info);
    }
  // now read the solutions to be performed
  FESystemIOUtility::readFromInput(input, "N_SOLUTIONS", num);
  for (unsigned int i = 0; i < num; i++)
    {
    tag.clear();
    FESystemIOUtility::peekFromInput(input, tag);
    enum_ID = Solution::SolutionEnum::enumID(tag);
    Solution::SolutionBase *solution =
      Solution::createSolutionBase(enum_ID).release();
    input >> (*solution);
    this->addSolutionBase(solution);
    }
  // read the solver info
  Solver::SolverInfo* solver_info = NULL;
  FESystemIOUtility::readFromInput(input, "SOLVER_INFO");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "N_SOLVER_INFO", num);
  for (unsigned int i=0; i < num; i++)
    {
    tag.clear();
    FESystemIOUtility::peekFromInput(input, tag);
    enum_ID = Solver::SolverInfoEnum::enumID(tag);
    solver_info = Solver::createSolverInfo(enum_ID).release();
    input >> (*solver_info);
    this->addSolverInfo(solver_info);
    }
  FESystemIOUtility::readFromInput(input, "SOLVER_INFO");
  FESystemIOUtility::readFromInput(input, "END");
  // read the interpolation cases
  InterpolationCase* interpol_case = NULL;
  FESystemIOUtility::readFromInput(input, "INTERPOLATION_CASES");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "N_INTERPOLATION_CASES", num);
  for (unsigned int i=0; i < num; i++)
    {
    interpol_case = new InterpolationCase;
    interpol_case->readFromInputStream(input);
    this->addInterpolationCase(interpol_case);
    }
  FESystemIOUtility::readFromInput(input, "INTERPOLATION_CASES");
  FESystemIOUtility::readFromInput(input, "END");
  // read solver parameters
  // first read the integer parameters
  FESystemIOUtility::readFromInput(input, "INTEGER_PARAMETERS");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  unsigned int n_params = 0, int_param=0;
  FESystemIOUtility::readFromInput(input, "N_INTEGER_PARAMETERS", n_params);
  for (unsigned int i=0; i < n_params; i++)
    {
    tag.clear();
    input >> tag;
    input >> int_param;
    insert_success =
      this->integer_params.insert(AnalysisCase::IntegerParameterMap::value_type
                                  (tag, int_param)).second;
    Assert(insert_success,
           AnalysisCase::ExcDuplicateParameterName(tag));
    }
  n_params = 0;
  FESystemIOUtility::readFromInput(input, "INTEGER_PARAMETERS");
  FESystemIOUtility::readFromInput(input, "END");
  // first read the real parameters
  FESystemIOUtility::readFromInput(input, "REAL_PARAMETERS");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  double real_param=0;
  FESystemIOUtility::readFromInput(input, "N_REAL_PARAMETERS", n_params);
  for (unsigned int i=0; i < n_params; i++)
    {
    tag.clear();
    input >> tag;
    input >> real_param;
    insert_success =
      this->float_params.insert(AnalysisCase::RealParameterMap::value_type
                                (tag, real_param)).second;
    Assert(insert_success,
           AnalysisCase::ExcDuplicateParameterName(tag));
    }
  n_params = 0;
  FESystemIOUtility::readFromInput(input, "REAL_PARAMETERS");
  FESystemIOUtility::readFromInput(input, "END");
  // first read the string parameters
  FESystemIOUtility::readFromInput(input, "STRING_PARAMETERS");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  std::string str_param;
  FESystemIOUtility::readFromInput(input, "N_STRING_PARAMETERS", n_params);
  for (unsigned int i=0; i < n_params; i++)
    {
    tag.clear();
    input >> tag;
    input >> str_param;
    insert_success =
      this->string_params.insert(AnalysisCase::StringParameterMap::value_type
                                 (tag, str_param)).second;
    Assert(insert_success,
           AnalysisCase::ExcDuplicateParameterName(tag));
    }
  n_params = 0;
  FESystemIOUtility::readFromInput(input, "STRING_PARAMETERS");
  FESystemIOUtility::readFromInput(input, "END");
  // read in the output info
  this->output_info = new OutputInfo;
  input >> *(this->output_info);
  // this will end with END_ANALYSIS_CASE
  FESystemIOUtility::readFromInput(input, "ANALYSIS_CASE");
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Member Data Documentation
std::string FESystem::AnalysisCase::analysis_title [protected]
title of the analysis
Definition at line 108 of file AnalysisCase.h.
Referenced by getTitle().
DisciplineInfoMap FESystem::AnalysisCase::discipline_info_map [protected]
map of discipline info for each discipline
Definition at line 125 of file AnalysisCase.h.
RealParameterMap FESystem::AnalysisCase::float_params [protected]
real parameter map
Definition at line 138 of file AnalysisCase.h.
IDToSolverInfoMap FESystem::AnalysisCase::ID_to_solver_info_map [protected]
map of ID to solver info
Definition at line 129 of file AnalysisCase.h.
IntegerParameterMap FESystem::AnalysisCase::integer_params [protected]
integer parameter map
Definition at line 135 of file AnalysisCase.h.
std::map<unsigned int, InterpolationCase*> FESystem::AnalysisCase::interpolation_case_map [protected]
interpolation case
Definition at line 114 of file AnalysisCase.h.
OutputInfo* FESystem::AnalysisCase::output_info [protected]
output format
Definition at line 111 of file AnalysisCase.h.
SolutionBaseMap FESystem::AnalysisCase::solution_base_map [protected]
map of solutions
Definition at line 132 of file AnalysisCase.h.
StringParameterMap FESystem::AnalysisCase::string_params [protected]
string parameters
Definition at line 141 of file AnalysisCase.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/FESystem/AnalysisCase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/FESystem/AnalysisCase.C