fesystem: VolumeLoadSet Class Reference
VolumeLoadSet Class Reference
#include <LoadSet.h>
Public Member Functions
VolumeLoadSet ()
virtual ~VolumeLoadSet ()
virtual unsigned int getLoadSetKindEnumID () const
void getLoadsForElement (const unsigned int, std::vector< const VolumeLoad * > &loads) const
void getAllLoads (std::vector< const VolumeLoad * > &loads) const
virtual std::istream & readFromInputStream (std::istream &input)
Protected Attributes
std::multimap< unsigned int,
VolumeLoad * > elem_ID_to_load_map
Detailed Description
Definition at line 153 of file LoadSet.h.
Constructor & Destructor Documentation
VolumeLoadSet::VolumeLoadSet ()
Definition at line 56 of file LoadSet.C.
                            :
  LoadSetBase()
{
}
VolumeLoadSet::~VolumeLoadSet () [virtual]
Definition at line 64 of file LoadSet.C.
References elem_ID_to_load_map.
{
  // iterate over all loads and delete them
  std::multimap<unsigned int, VolumeLoad*>::iterator it, end;
  it = this->elem_ID_to_load_map.begin();
  end = this->elem_ID_to_load_map.end();
  for (; it != end; it++)
    {
      delete it->second;
      it->second = NULL;
    }
  this->elem_ID_to_load_map.clear();
}
Member Function Documentation
void VolumeLoadSet::getAllLoads (std::vector< const VolumeLoad * > & loads) const
Definition at line 106 of file LoadSet.C.
References elem_ID_to_load_map.
{
  std::multimap<unsigned int, VolumeLoad*>::const_iterator it, end;
  it = this->elem_ID_to_load_map.begin();
  end = this->elem_ID_to_load_map.end();
  loads.resize(this->elem_ID_to_load_map.size());
  unsigned int i=0;
  for (; it != end; it++)
    {
      loads[i] = it->second;
      i++;
    }
}
unsigned int VolumeLoadSet::getLoadSetKindEnumID () const [virtual]
Implements LoadSetBase.
Definition at line 83 of file LoadSet.C.
{
  return VOLUME_LOAD_SET::num();
}
void VolumeLoadSet::getLoadsForElement (const unsigned int elem_ID, std::vector< const VolumeLoad * > & loads) const
This will search the loads in this set and add create a vector containing loads that act on an element
Definition at line 92 of file LoadSet.C.
References elem_ID_to_load_map.
Referenced by LoadDatabase::getLoadCombination< Loads::VolumeLoadDataInfo, Loads::VolumeLoadCombination >().
{
  std::multimap<unsigned int, VolumeLoad*>::const_iterator it, end;
  it = this->elem_ID_to_load_map.lower_bound(elem_ID);
  end = this->elem_ID_to_load_map.upper_bound(elem_ID);
  for ( ; it != end; it++)
    loads.push_back(it->second);
}
std::istream & VolumeLoadSet::readFromInputStream (std::istream & input) [virtual]
Implements LoadSetBase.
Definition at line 123 of file LoadSet.C.
References createVolumeLoad(), elem_ID_to_load_map, getLoadClassEnumIDForLoadName(), LoadSetBase::load_kind_enum_ID, LoadSetBase::load_set_ID, FESystemIOUtility::readFromInput(), and LoadSetBase::set_tag.
{
  std::string tag;
  unsigned int n_loads=0, elem_ID=0, load_class_enum_ID = 0;
  // the load set should begin with the BEGIN tag, and followed by
  // the number of loads in the set
  FESystemIOUtility::readFromInput(input, VOLUME_LOAD_SET::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  // next, it should contain the name, ID and kind, and number of DOFs of load
  FESystemIOUtility::readFromInput(input, "NAME", this->set_tag);
  FESystemIOUtility::readFromInput(input, "ID", this->load_set_ID);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "KIND", tag);
  this->load_kind_enum_ID = LoadNameEnum::enumID(tag);
  load_class_enum_ID = getLoadClassEnumIDForLoadName(this->load_kind_enum_ID);
  FESystemIOUtility::readFromInput(input, "N_LOADS", n_loads);
  std::auto_ptr<VolumeLoad> load;
  for (unsigned int load_incr=0; load_incr < n_loads; load_incr++)
    {
      load.reset(createVolumeLoad(load_class_enum_ID).release());
      load->readFromInputStream(input);
      elem_ID = load->getLoadID();
      this->elem_ID_to_load_map.insert
        (std::multimap<unsigned int, VolumeLoad*>::value_type
         (elem_ID, load.release()));
    }
  FESystemIOUtility::readFromInput(input, VOLUME_LOAD_SET::name());
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Member Data Documentation
std::multimap<unsigned int, VolumeLoad*> VolumeLoadSet::elem_ID_to_load_map [protected]
Definition at line 175 of file LoadSet.h.
Referenced by getAllLoads(), getLoadsForElement(), readFromInputStream(), and ~VolumeLoadSet().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadSet.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadSet.C