fesystem: InterpolationCase Class Reference
InterpolationCase Class Reference
#include <InterpolationCase.h>
Public Types
enum InterpolationType { DIRECT, FE, INVALID_INTERPOLATION_TYPE }
Public Member Functions
InterpolationCase ()
constructor
~InterpolationCase ()
destructor
std::istream & readFromInputStream (std::istream &input)
InterpolationCase::InterpolationType type () const
returns the type of interpolation used for this case
unsigned int ID () const
returns case ID
unsigned int fromDiscipline () const
returns the mesh from which the data is interpolated
unsigned int toDiscipline () const
returns the mesh to which the data is interpolated
Protected Attributes
unsigned int interpolation_case_ID
case ID
InterpolationType interpolation_type
Interpolation type.
unsigned int to_discipline_enum_ID
to mesh ID
unsigned int from_discipline_enum_ID
from mesh ID
Detailed Description
this defines an interpolation case that will contain the necessary data to interpolate the data from a mesh to another
Definition at line 21 of file InterpolationCase.h.
Member Enumeration Documentation
enum InterpolationCase::InterpolationType
Enumerator:
DIRECT
FE
INVALID_INTERPOLATION_TYPE
Definition at line 24 of file InterpolationCase.h.
{
    DIRECT,
    FE,
    INVALID_INTERPOLATION_TYPE
  };
Constructor & Destructor Documentation
InterpolationCase::InterpolationCase ()
constructor
Definition at line 16 of file InterpolationCase.C.
                                    :
interpolation_case_ID(0),
interpolation_type(INVALID_INTERPOLATION_TYPE),
to_discipline_enum_ID(0),
from_discipline_enum_ID(0)
{
}
InterpolationCase::~InterpolationCase ()
destructor
Definition at line 26 of file InterpolationCase.C.
{
}
Member Function Documentation
unsigned int InterpolationCase::fromDiscipline () const [inline]
returns the mesh from which the data is interpolated
Definition at line 104 of file InterpolationCase.h.
References from_discipline_enum_ID.
Referenced by DirectInterpolation::createLoads().
{
  return this->from_discipline_enum_ID;
}
unsigned int InterpolationCase::ID () const [inline]
returns case ID
Definition at line 88 of file InterpolationCase.h.
References interpolation_case_ID.
Referenced by FESystem::AnalysisCase::addInterpolationCase().
{
  return this->interpolation_case_ID;
}
std::istream & InterpolationCase::readFromInputStream (std::istream & input)
method to read from an input stream
Parameters:
input input stream from which the data is read
Definition at line 32 of file InterpolationCase.C.
References DIRECT, FE, from_discipline_enum_ID, interpolation_case_ID, interpolation_type, FESystemIOUtility::readFromInput(), and to_discipline_enum_ID.
Referenced by FESystem::AnalysisCase::readFromInputStream().
{
  std::string tag;
  // should begin with a begin InterpolationCase tag
  FESystemIOUtility::readFromInput(input, "INTERPOLATION_CASE");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  // read the interpolation case ID
  FESystemIOUtility::readFromInput(input, "INTERPOLATION_CASE_ID",
                                   this->interpolation_case_ID);
  // read the interpolation type
  tag.clear();
  FESystemIOUtility::readFromInput(input, "INTERPOLATION_TYPE", tag);
  if (tag == "DIRECT")
    this->interpolation_type = InterpolationCase::DIRECT;
  else if (tag == "FE")
    this->interpolation_type = InterpolationCase::FE;
  else
    abort();
  // read the mesh IDs
  tag.clear();
  FESystemIOUtility::readFromInput(input, "FROM_DISCIPLINE_ENUM_ID", tag);
  this->from_discipline_enum_ID = Discipline::AnalysisDisciplineEnum::enumID(tag);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "TO_DISCIPLINE_ENUM_ID", tag);
  this->to_discipline_enum_ID = Discipline::AnalysisDisciplineEnum::enumID(tag);
  AssertThrow(this->from_discipline_enum_ID != this->to_discipline_enum_ID,
              ExcInternalError());
//  // read the to element pairs
//  unsigned int n_elem_sets = 0, elem_set_1 = 0, elem_set_2 = 0;
//
//  FESystemIOUtility::readFromInput(input, "ELEMENT_SET_PAIRS");
//  FESystemIOUtility::readFromInput(input, "BEGIN");
//  FESystemIOUtility::readFromInput(input, "N_ELEM_SETS", n_elem_sets);
//
//  for (unsigned int i=0; i<n_elem_sets; i++)
//    {
//      input >> elem_set_1;
//      input >> elem_set_2;
//      this->elem_set_pairs.push_back(std::pair<unsigned int, unsigned int>
//                                   (elem_set_1, elem_set_2));
//    }
//
//  // read the to mesh ID
//  FESystemIOUtility::readFromInput(input, "ELEMENT_SET_PAIRS");
//  FESystemIOUtility::readFromInput(input, "END");
  // end with the end interpolation tag
  FESystemIOUtility::readFromInput(input, "INTERPOLATION_CASE");
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
unsigned int InterpolationCase::toDiscipline () const [inline]
returns the mesh to which the data is interpolated
Definition at line 111 of file InterpolationCase.h.
References to_discipline_enum_ID.
Referenced by DirectInterpolation::createLoads().
{
  return this->to_discipline_enum_ID;
}
InterpolationCase::InterpolationType InterpolationCase::type () const [inline]
returns the type of interpolation used for this case
Definition at line 80 of file InterpolationCase.h.
References interpolation_type.
Referenced by InterpolationDriver::createLoads(), InterpolationDriver::init(), and InterpolationDriver::interpolateAndCreateLoads().
{
  return this->interpolation_type;
}
Member Data Documentation
unsigned int InterpolationCase::from_discipline_enum_ID [protected]
from mesh ID
Definition at line 70 of file InterpolationCase.h.
Referenced by fromDiscipline(), and readFromInputStream().
unsigned int InterpolationCase::interpolation_case_ID [protected]
case ID
Definition at line 61 of file InterpolationCase.h.
Referenced by ID(), and readFromInputStream().
InterpolationType InterpolationCase::interpolation_type [protected]
Interpolation type.
Definition at line 64 of file InterpolationCase.h.
Referenced by readFromInputStream(), and type().
unsigned int InterpolationCase::to_discipline_enum_ID [protected]
to mesh ID
Definition at line 67 of file InterpolationCase.h.
Referenced by readFromInputStream(), and toDiscipline().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Interpolation/InterpolationCase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Interpolation/InterpolationCase.C