fesystem: Solver::TransientSolverBase Class Reference
Solver::TransientSolverBase Class Reference
#include <TransientSolver.h>
Public Member Functions
TransientSolverBase (const Solver::TransientSolverInfoBase &info)
constructor
virtual ~TransientSolverBase ()
virtual void clear ()
virtual void solve ()=0
method to solve the eigen system
virtual double getSimulatedTime ()=0
virtual double getCurrentTime ()=0
virtual double getCurrentStepSize ()=0
virtual unsigned int getSimulatedIterationNumber ()=0
virtual unsigned int getCurrentIterationNumber ()=0
void attachCoefficientMatrices (std::vector< SparseMatrix< double > * > &matrices)
this attaches the matrix to be used for jacobian evaluation
double getTimeStepSize () const
virtual void setInitialCondition (std::vector< NumericVector< double > * > &state_vecs)=0
set initial conditions for the analysis
Protected Attributes
const
Solver::TransientSolverInfoBase & transient_solver_info
TransientSolverInfo that stores information about this solver.
std::vector< SparseMatrix
< double > * > coefficient_matrices
Detailed Description
this class provides an interface to a solver for the solution of eigensystem. This inherits from the FESystemSolverBase class. It takes a pointer to the analysis driver object that owns an instantiation of this class
Definition at line 69 of file TransientSolver.h.
Constructor & Destructor Documentation
Solver::TransientSolverBase::TransientSolverBase (const Solver::TransientSolverInfoBase & info)
constructor
Definition at line 10 of file TransientSolver.C.
                                           :
Solver::FESystemSolverBase(dynamic_cast<const Solver::SolverInfo&>(info)),
transient_solver_info(info)
{
}
Solver::TransientSolverBase::~TransientSolverBase () [virtual]
Definition at line 19 of file TransientSolver.C.
{
}
Member Function Documentation
void Solver::TransientSolverBase::attachCoefficientMatrices (std::vector< SparseMatrix< double > * > & matrices)
this attaches the matrix to be used for jacobian evaluation
Definition at line 37 of file TransientSolver.C.
Referenced by Driver::LinearTransientAnalysisDriver::solveCurrentLoadCase().
{
  Assert(this->coefficient_matrices.size() == 0, ExcInternalError());
  Assert(matrices.size() != 0, ExcInternalError());
  this->coefficient_matrices = matrices;
}
void Solver::TransientSolverBase::clear () [virtual]
this method clears the data structures of this object. This should be called each time the used finishes using this object.
Reimplemented from Solver::FESystemSolverBase.
Reimplemented in Solver::NonlinearTransientSolverBase, Solver::NewmarkNonlinearTransientSolver, Solver::LinearTransientSolverBase, Solver::EulerNonlinearTransientSolver, Solver::PetscNonlinearTransientSolver, Solver::EulerLinearTransientSolver, and Solver::NewmarkLinearTransientSolver.
Definition at line 26 of file TransientSolver.C.
References Solver::FESystemSolverBase::clear().
Referenced by Solver::LinearTransientSolverBase::clear(), and Solver::NonlinearTransientSolverBase::clear().
{
  this->coefficient_matrices.clear();
  Solver::FESystemSolverBase::clear();
}
virtual unsigned int Solver::TransientSolverBase::getCurrentIterationNumber () [pure virtual]
Returns:
the current time iteration of the solver integration
Implemented in Solver::NewmarkNonlinearTransientSolver, Solver::EulerNonlinearTransientSolver, Solver::PetscNonlinearTransientSolver, Solver::EulerLinearTransientSolver, and Solver::NewmarkLinearTransientSolver.
virtual double Solver::TransientSolverBase::getCurrentStepSize () [pure virtual]
Returns:
the current time step of the solver integration
Implemented in Solver::NewmarkNonlinearTransientSolver, Solver::EulerNonlinearTransientSolver, Solver::PetscNonlinearTransientSolver, Solver::EulerLinearTransientSolver, and Solver::NewmarkLinearTransientSolver.
virtual double Solver::TransientSolverBase::getCurrentTime () [pure virtual]
Returns:
the current time of the solver integration
Implemented in Solver::NewmarkNonlinearTransientSolver, Solver::EulerNonlinearTransientSolver, Solver::PetscNonlinearTransientSolver, Solver::EulerLinearTransientSolver, and Solver::NewmarkLinearTransientSolver.
virtual unsigned int Solver::TransientSolverBase::getSimulatedIterationNumber () [pure virtual]
Returns:
the current time iteration of the solver integration
Implemented in Solver::NewmarkNonlinearTransientSolver, Solver::EulerNonlinearTransientSolver, Solver::PetscNonlinearTransientSolver, Solver::EulerLinearTransientSolver, and Solver::NewmarkLinearTransientSolver.
virtual double Solver::TransientSolverBase::getSimulatedTime () [pure virtual]
Returns:
the current time of the solver integration
Implemented in Solver::NewmarkNonlinearTransientSolver, Solver::EulerNonlinearTransientSolver, Solver::PetscNonlinearTransientSolver, Solver::EulerLinearTransientSolver, and Solver::NewmarkLinearTransientSolver.
double Solver::TransientSolverBase::getTimeStepSize () const
Returns:
the time step size of the solver
Definition at line 47 of file TransientSolver.C.
{
  // Note that this will change when adaptive time steps are added
  return this->transient_solver_info.getInitialTimeStep();
}
virtual void Solver::TransientSolverBase::setInitialCondition (std::vector< NumericVector< double > * > & state_vecs) [pure virtual]
set initial conditions for the analysis
Implemented in Solver::NewmarkNonlinearTransientSolver, Solver::EulerNonlinearTransientSolver, Solver::PetscNonlinearTransientSolver, Solver::EulerLinearTransientSolver, and Solver::NewmarkLinearTransientSolver.
Referenced by Driver::LinearTransientAnalysisDriver::solveCurrentLoadCase().
virtual void Solver::TransientSolverBase::solve () [pure virtual]
method to solve the eigen system
Implemented in Solver::NewmarkNonlinearTransientSolver, Solver::EulerNonlinearTransientSolver, Solver::PetscNonlinearTransientSolver, Solver::EulerLinearTransientSolver, and Solver::NewmarkLinearTransientSolver.
Referenced by Driver::LinearTransientAnalysisDriver::solveCurrentLoadCase().
Member Data Documentation
std::vector<SparseMatrix<double>*> Solver::TransientSolverBase::coefficient_matrices [protected]
coefficient matrices stored according to the order of the time derivative of the solution vector for which they act as coefficient
Definition at line 129 of file TransientSolver.h.
Referenced by Solver::NewmarkSolver::getJacobian().
const Solver::TransientSolverInfoBase& Solver::TransientSolverBase::transient_solver_info [protected]
TransientSolverInfo that stores information about this solver.
Definition at line 125 of file TransientSolver.h.
Referenced by Solver::NewmarkSolver::getJacobian(), and Solver::NewmarkSolver::getResidual().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/TransientSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/TransientSolver.C