fesystem: FESystemNumerics::VectorBase< T > Class Template Reference
FESystemNumerics::VectorBase< T > Class Template Reference
#include <VectorBase.h>
Public Member Functions
VectorBase ()
constructor
virtual ~VectorBase ()
virtual unsigned int getVectorPackage () const =0
void operator= (const FESystemNumerics::VectorBase< T > &vector)
virtual void copy (const FESystemNumerics::VectorBase< T > &vector)=0
virtual void resize (const unsigned int n)=0
virtual void zero ()=0
virtual T el (const unsigned int i) const =0
virtual void power (const double val)=0
raises each element of the vector by the given power
virtual void invertValues ()=0
sets each element of the vector to its reciprocal
virtual T dot (const FESystemNumerics::VectorBase< T > &vec) const =0
returns the dot product of this vector with the given vector
virtual void shift (const T val)=0
adds the value val to all elements of the vector
virtual void pointwiseMultiply (const FESystemNumerics::VectorBase< T > &vec)=0
sets (*this)[i] = (*this)[i] * vec[i]
virtual void set (const unsigned int i, const T val)=0
virtual void set (const std::vector< unsigned int > &i, const T *val)=0
virtual unsigned int size () const =0
virtual void add (const T val, const FESystemNumerics::VectorBase< T > &vector)=0
virtual void add (const unsigned int i, const T val)=0
virtual void add (const std::vector< unsigned int > &i, const T *val)=0
virtual void scale (const T factor)=0
virtual void print (std::ostream &output)
Detailed Description
template<typename T>
class FESystemNumerics::VectorBase< T >
this class provides a base class for different kinds of matrices
Definition at line 14 of file VectorBase.h.
Constructor & Destructor Documentation
template<typename T > FESystemNumerics::VectorBase< T >::VectorBase ()
constructor
Definition at line 144 of file VectorBase.h.
{}
template<typename T > FESystemNumerics::VectorBase< T >::~VectorBase () [virtual]
Destructor. Empty.
Definition at line 150 of file VectorBase.h.
{}
Member Function Documentation
template<typename T> virtual void FESystemNumerics::VectorBase< T >::add (const T val, const FESystemNumerics::VectorBase< T > & vector) [pure virtual]
Adds to this matrix
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T> virtual void FESystemNumerics::VectorBase< T >::add (const unsigned int i, const T val) [pure virtual]
Adds factor to given element in the matrix.
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T> virtual void FESystemNumerics::VectorBase< T >::add (const std::vector< unsigned int > & i, const T * val) [pure virtual]
adds multiple elements with the indeces given in i and j. The val should be a 2-D matrix of dimensions equal to size of vectors i and j.
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T> virtual void FESystemNumerics::VectorBase< T >::copy (const FESystemNumerics::VectorBase< T > & vector) [pure virtual]
Copies vector to this vector
Implemented in FESystemNumerics::PetscSeqVector< T >, and FESystemNumerics::PetscSeqVector< double >.
template<typename T> virtual T FESystemNumerics::VectorBase< T >::dot (const FESystemNumerics::VectorBase< T > & vec) const [pure virtual]
returns the dot product of this vector with the given vector
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T> virtual T FESystemNumerics::VectorBase< T >::el (const unsigned int i) const [pure virtual]
Returns:
the (i,j) element of the matrix. Since internal data representations may differ, you must redefine this function.
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T> virtual unsigned int FESystemNumerics::VectorBase< T >::getVectorPackage () const [pure virtual]
Returns:
the matrix package
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
Referenced by FESystemNumerics::PetscVectorBase< T >::add(), FESystemNumerics::PetscSeqVector< T >::copy(), FESystemNumerics::PetscMatrixBase< T >::diagonalAdd(), FESystemNumerics::PetscVectorBase< T >::dot(), FESystemNumerics::PetscMatrixBase< T >::getDiagonal(), FESystemNumerics::PetscMatrixBase< T >::getRow(), FESystemNumerics::PetscMatrixBase< T >::leftDiagonalScale(), FESystemNumerics::PetscMatrixBase< T >::leftMultiplyVector(), FESystemNumerics::PetscVectorBase< T >::pointwiseMultiply(), FESystemNumerics::PetscMatrixBase< T >::rightDiagonalScale(), and FESystemNumerics::PetscMatrixBase< T >::rightMultiplyVector().
template<typename T> virtual void FESystemNumerics::VectorBase< T >::invertValues () [pure virtual]
sets each element of the vector to its reciprocal
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T> void FESystemNumerics::VectorBase< T >::operator= (const FESystemNumerics::VectorBase< T > & vector) [inline]
Copies vector to this vector
Definition at line 34 of file VectorBase.h.
      {Assert(false, ExcInternalError());}
template<typename T> virtual void FESystemNumerics::VectorBase< T >::pointwiseMultiply (const FESystemNumerics::VectorBase< T > & vec) [pure virtual]
sets (*this)[i] = (*this)[i] * vec[i]
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T> virtual void FESystemNumerics::VectorBase< T >::power (const double val) [pure virtual]
raises each element of the vector by the given power
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T > void FESystemNumerics::VectorBase< T >::print (std::ostream & output) [virtual]
prints the values of the vector to the output
Definition at line 156 of file VectorBase.h.
{
  unsigned int m= this->size();
  for (unsigned int i=0; i< m; i++)
    output << this->el(i) << std::endl;
}
template<typename T> virtual void FESystemNumerics::VectorBase< T >::resize (const unsigned int n) [pure virtual]
Set every element in the matrix to 0. You must redefine what you mean by zeroing the matrix since it depends on how your values are stored.
Implemented in FESystemNumerics::PetscSeqVector< T >, and FESystemNumerics::PetscSeqVector< double >.
template<typename T> virtual void FESystemNumerics::VectorBase< T >::scale (const T factor) [pure virtual]
multiplies factor to every element in the matrix.
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T> virtual void FESystemNumerics::VectorBase< T >::set (const unsigned int i, const T val) [pure virtual]
sets the given element to
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T> virtual void FESystemNumerics::VectorBase< T >::set (const std::vector< unsigned int > & i, const T * val) [pure virtual]
sets multiple elements with the indeces given in i and j. The val should be a 2-D matrix of dimensions equal to size of vectors i and j.
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T> virtual void FESystemNumerics::VectorBase< T >::shift (const T val) [pure virtual]
adds the value val to all elements of the vector
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
template<typename T> virtual unsigned int FESystemNumerics::VectorBase< T >::size () const [pure virtual]
Returns:
the row-dimension of the matrix.
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
Referenced by FESystemNumerics::PetscMatrixBase< T >::diagonalAdd(), FESystemNumerics::PetscMatrixBase< T >::getDiagonal(), and FESystemNumerics::PetscMatrixBase< T >::getRow().
template<typename T> virtual void FESystemNumerics::VectorBase< T >::zero () [pure virtual]
Set every element in the matrix to 0. You must redefine what you mean by zeroing the matrix since it depends on how your values are stored.
Implemented in FESystemNumerics::PetscVectorBase< T >, and FESystemNumerics::PetscVectorBase< double >.
Referenced by FESystemNumerics::PetscMatrixBase< T >::getRow().
The documentation for this class was generated from the following file:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Numerics/VectorBase.h