fesystem: GeometricCircularArc Class Reference
GeometricCircularArc Class Reference
this class defines a geometric point
#include <GeometricCircularArc.h>
Public Member Functions
GeometricCircularArc (GeometricModel &)
constructor
virtual ~GeometricCircularArc ()
destructor
virtual GeometricEntityType type () const
returns the type of this entity
virtual bool checkIfDuplicate (const GeometricEntity &)
method to check if this object is a duplicate of the given object
Protected Member Functions
virtual void readFromInput (std::istream &)
method to read from input
virtual void writeToOutput (std::ostream &)
method to write to output
Protected Attributes
std::vector< GeometricPoint * > points
location of this point
Detailed Description
this class defines a geometric point
Definition at line 17 of file GeometricCircularArc.h.
Constructor & Destructor Documentation
GeometricCircularArc::GeometricCircularArc (GeometricModel & model)
constructor
Definition at line 13 of file GeometricCircularArc.C.
  :GeometricLine(model)
{
}
GeometricCircularArc::~GeometricCircularArc () [virtual]
destructor
Definition at line 20 of file GeometricCircularArc.C.
{
}
Member Function Documentation
bool GeometricCircularArc::checkIfDuplicate (const GeometricEntity & arc_ref) [virtual]
method to check if this object is a duplicate of the given object
Implements GeometricLine.
Definition at line 26 of file GeometricCircularArc.C.
References GeometricEntity::base_entity_ID, GeometricEntity::baseEntityID(), GeometricEntity::CIRCULAR_ARC, GeometricLine::getPoints(), GeometricEntity::is_duplicate, points, GeometricEntity::same_orientation_as_base_entity, and GeometricEntity::type().
{
  // make sure that the two arcs are not the same object
  assert (&arc_ref != this);
  // also, its type should be a circular arc
  if (arc_ref.type() != GeometricEntity::CIRCULAR_ARC)
    return false;
  // convert this line's reference to a geometric arc
  const GeometricCircularArc& arc = dynamic_cast<const GeometricCircularArc&>(arc_ref);
  // get the points for this arc
  const std::vector<GeometricPoint*>& arc_points = arc.getPoints();
  // compare the point IDs of this line with that of the given line
  // the comparisons should be made only with the base_entity_IDs
  unsigned int this_point1 = this->points[0]->baseEntityID();
  unsigned int this_point2 = this->points[2]->baseEntityID();
  unsigned int this_center = this->points[1]->baseEntityID();
  unsigned int given_point1 = arc_points[0]->baseEntityID();
  unsigned int given_point2 = arc_points[2]->baseEntityID();
  unsigned int given_center = arc_points[1]->baseEntityID();
  // if the two centers are not the same, then the arcs are different
  if (this_center != given_center)
    return false;
  bool dupl = false;
  // next compare the two ends, which would be the same as comparing a straight line
  if (this_point1 == given_point1 && this_point2 == given_point2)
    {
      dupl = true;
      this->same_orientation_as_base_entity = true;
    }
  else if (this_point2 == given_point1 && this_point1 == given_point2)
    {
      dupl = true;
      this->same_orientation_as_base_entity = false;
    }
  if (dupl == true)
    {
      this->is_duplicate = true;
      this->base_entity_ID = arc.baseEntityID();
      return true;
    }
  else
    return false;
}
void GeometricCircularArc::readFromInput (std::istream & input) [protected, virtual]
method to read from input
Implements GeometricLine.
Definition at line 83 of file GeometricCircularArc.C.
References GeometricEntity::geometric_model, GeometricModel::getPointForID(), points, and GeometricEntity::unique_ID.
{
  input >> this->unique_ID;
  unsigned int point_num = 0;
  GeometricPoint* point = NULL;
  for (unsigned int i=0; i<3; i++)
    {
      input >> point_num;
      point = &(this->geometric_model.getPointForID(point_num));
      this->points.push_back(point);
    }
}
GeometricEntity::GeometricEntityType GeometricCircularArc::type () const [inline, virtual]
returns the type of this entity
Implements GeometricLine.
Definition at line 47 of file GeometricCircularArc.h.
References GeometricEntity::CIRCULAR_ARC.
{
  return GeometricEntity::CIRCULAR_ARC;
}
void GeometricCircularArc::writeToOutput (std::ostream & output) [protected, virtual]
method to write to output
Implements GeometricLine.
Definition at line 101 of file GeometricCircularArc.C.
References points, and GeometricEntity::unique_ID.
{
  output << this->unique_ID << "   ";
  output << this->points[0]->ID() << "   ";
  output << this->points[1]->ID() << "   ";
  output << this->points[2]->ID() << std::endl;
}
Member Data Documentation
std::vector<GeometricPoint*> GeometricCircularArc::points [protected]
location of this point
Reimplemented from GeometricLine.
Definition at line 42 of file GeometricCircularArc.h.
Referenced by checkIfDuplicate(), readFromInput(), and writeToOutput().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricCircularArc.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Geometry/GeometricCircularArc.C