fesystem: BoundaryConditionLoadSet Class Reference
BoundaryConditionLoadSet Class Reference
#include <LoadSet.h>
Public Member Functions
BoundaryConditionLoadSet ()
~BoundaryConditionLoadSet ()
virtual unsigned int getLoadSetKindEnumID () const
void getLoadsForNode (const unsigned int node_id, std::vector< const DirichletBoundaryCondition * > &loads) const
void getAllLoads (std::vector< const DirichletBoundaryCondition * > &loads) const
virtual std::istream & readFromInputStream (std::istream &)
Protected Attributes
std::multimap< unsigned int,
DirichletBoundaryCondition * > node_ID_to_load_map
Detailed Description
Definition at line 248 of file LoadSet.h.
Constructor & Destructor Documentation
BoundaryConditionLoadSet::BoundaryConditionLoadSet ()
Definition at line 286 of file LoadSet.C.
                                                  :
  LoadSetBase()
{
}
BoundaryConditionLoadSet::~BoundaryConditionLoadSet ()
Definition at line 294 of file LoadSet.C.
References node_ID_to_load_map.
{
  // iterate over all loads and delete them
  std::multimap<unsigned int, DirichletBoundaryCondition*>::iterator it, end;
  it = this->node_ID_to_load_map.begin();
  end = this->node_ID_to_load_map.end();
  for (; it != end; it++)
    {
      delete it->second;
      it->second = NULL;
    }
  this->node_ID_to_load_map.clear();
}
Member Function Documentation
void BoundaryConditionLoadSet::getAllLoads (std::vector< const DirichletBoundaryCondition * > & loads) const
Definition at line 336 of file LoadSet.C.
References node_ID_to_load_map.
Referenced by LoadDatabase::getAllLoadCombinations< Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination >().
{
  std::multimap<unsigned int, DirichletBoundaryCondition*>::const_iterator it, end;
  it = this->node_ID_to_load_map.begin();
  end = this->node_ID_to_load_map.end();
  loads.resize(this->node_ID_to_load_map.size());
  unsigned int i=0;
  for (; it != end; it++)
    {
      loads[i] = it->second;
      i++;
    }
}
unsigned int BoundaryConditionLoadSet::getLoadSetKindEnumID () const [virtual]
Implements LoadSetBase.
Definition at line 313 of file LoadSet.C.
{
  return BOUNDARY_CONDITION_LOAD_SET::num();
}
void BoundaryConditionLoadSet::getLoadsForNode (const unsigned int node_id, std::vector< const DirichletBoundaryCondition * > & loads) const
This will search the loads in this set and add create a vector containing loads that act on a node
Definition at line 322 of file LoadSet.C.
References node_ID_to_load_map.
{
  std::multimap<unsigned int, DirichletBoundaryCondition*>::const_iterator it, end;
  it = this->node_ID_to_load_map.lower_bound(elem_ID);
  end = this->node_ID_to_load_map.upper_bound(elem_ID);
  for ( ; it != end; it++)
    loads.push_back(it->second);
}
std::istream & BoundaryConditionLoadSet::readFromInputStream (std::istream & input) [virtual]
Implements LoadSetBase.
Definition at line 353 of file LoadSet.C.
References createBoundaryConditionLoad(), getLoadClassEnumIDForLoadName(), LoadSetBase::load_kind_enum_ID, LoadSetBase::load_set_ID, node_ID_to_load_map, FESystemIOUtility::readFromInput(), and LoadSetBase::set_tag.
{
  std::string tag;
  unsigned int n_loads=0, node_ID = 0, load_class_enum_ID = 0;
  // the load set should begin with the BEGIN tag, and followed by
  // the number of loads in the set
  FESystemIOUtility::readFromInput(input, BOUNDARY_CONDITION_LOAD_SET::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  // next, it should contain the name, ID and kind, and number of DOFs of load
  FESystemIOUtility::readFromInput(input, "NAME", this->set_tag);
  FESystemIOUtility::readFromInput(input, "ID", this->load_set_ID);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "KIND", tag);
  this->load_kind_enum_ID = LoadNameEnum::enumID(tag);
  load_class_enum_ID = getLoadClassEnumIDForLoadName(this->load_kind_enum_ID);
  FESystemIOUtility::readFromInput(input, "N_LOADS", n_loads);
  std::auto_ptr<DirichletBoundaryCondition> load;
  for (unsigned int load_incr=0; load_incr < n_loads; load_incr++)
    {
      load.reset(createBoundaryConditionLoad(load_class_enum_ID).release());
      load->readFromInputStream(input);
      node_ID = load->getNodeID();
      this->node_ID_to_load_map.insert
        (std::multimap<unsigned int, DirichletBoundaryCondition*>::value_type
         (node_ID, load.release()));
    }
  FESystemIOUtility::readFromInput(input, BOUNDARY_CONDITION_LOAD_SET::name());
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Member Data Documentation
std::multimap<unsigned int, DirichletBoundaryCondition*> BoundaryConditionLoadSet::node_ID_to_load_map [protected]
Definition at line 268 of file LoadSet.h.
Referenced by getAllLoads(), getLoadsForNode(), readFromInputStream(), and ~BoundaryConditionLoadSet().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadSet.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadSet.C