fesystem: Solver::NonlinearSolver Class Reference
Solver::NonlinearSolver Class Reference
#include <NonlinearSolver.h>
Public Member Functions
NonlinearSolver (const Solver::NonlinearSolverInfo &nonlinear_info, const Solver::LinearSolverInfo &linear_info)
constructor
~NonlinearSolver ()
destructor
virtual void clear ()
method to clear the data structures of this class
unsigned int getNonlinearSolverKindEnumID () const
std::string getNonlinearSolverKindEnumName () const
void attachMatrixAndVector (SparseMatrix< double > &joc_mat, NumericVector< double > &res_vec)
virtual void solve (NumericVector< double > &solution)=0
virtual unsigned int getCurrentIterationNumber () const =0
this returns the itertion number of the solution process
void evaluateResidual (NumericVector< double > &sol, NumericVector< double > &res)
void evaluateJacobian (NumericVector< double > &sol, SparseMatrix< double > &jac)
void setFunctions (void(*res_func)(NumericVector< double > &sol, NumericVector< double > &res, void *ctx), void(*jac_func)(NumericVector< double > &sol, SparseMatrix< double > &jac, void *ctx), void *ctx)
Protected Attributes
const unsigned int nonlinear_solver_kind_enum_ID
const Solver::NonlinearSolverInfo & nonlinear_solver_info
const Solver::LinearSolverInfo & linear_solver_info
SparseMatrix< double > * jacobian
NumericVector< double > * residual
void(* jacobian_function)(NumericVector< double > &sol, SparseMatrix< double > &jac, void *ctx)
void(* residual_function)(NumericVector< double > &sol, NumericVector< double > &res, void *ctx)
void * context
Detailed Description
Definition at line 47 of file NonlinearSolver.h.
Constructor & Destructor Documentation
Solver::NonlinearSolver::NonlinearSolver (const Solver::NonlinearSolverInfo & nonlinear_info, const Solver::LinearSolverInfo & linear_info)
constructor
Definition at line 10 of file NonlinearSolver.C.
                                                                                   :
Solver::FESystemSolverBase(dynamic_cast<const Solver::SolverInfo&>(nonlinear_info)),
nonlinear_solver_kind_enum_ID(nonlinear_info.getNonlinearSolverKindEnumID()),
nonlinear_solver_info(nonlinear_info),
linear_solver_info(linear_info),
jacobian(NULL),
residual(NULL),
jacobian_function(NULL),
residual_function(NULL),
context(NULL)
{
}
Solver::NonlinearSolver::~NonlinearSolver ()
destructor
Definition at line 28 of file NonlinearSolver.C.
{
}
Member Function Documentation
void Solver::NonlinearSolver::attachMatrixAndVector (SparseMatrix< double > & joc_mat, NumericVector< double > & res_vec) [inline]
Definition at line 151 of file NonlinearSolver.h.
Referenced by Driver::NonLinearAnalysisDriver::solveCurrentLoadCase().
{
  this->jacobian = &jac_mat;
  this->residual = &res_vec;
}
void Solver::NonlinearSolver::clear () [virtual]
method to clear the data structures of this class
Reimplemented from Solver::FESystemSolverBase.
Reimplemented in Solver::PetscNonlinearSolver, and Solver::NewtonNonlinearSolver.
Definition at line 35 of file NonlinearSolver.C.
References Solver::FESystemSolverBase::clear().
Referenced by Solver::NewtonNonlinearSolver::clear(), and Solver::PetscNonlinearSolver::clear().
{
  // first clear the data structures for this class and then call the
  // parent class' method
  this->jacobian = NULL;
  this->residual = NULL;
  this->jacobian_function = NULL;
  this->residual_function = NULL;
  this->context = NULL;
  Solver::FESystemSolverBase::clear();
}
void Solver::NonlinearSolver::evaluateJacobian (NumericVector< double > & sol, SparseMatrix< double > & jac)
evaluates the residual vector at the specified solution
Parameters:
sol vector at which the residual should be evaluated
jac matrix in which the jacobian is stored
Definition at line 96 of file NonlinearSolver.C.
References Driver::NonLinearAnalysisDriver::getJacobianAtVector().
Referenced by FESystemNonlinearSolverJacobianEvaluation().
{
  this->analysis_driver->getFESystemController().performance_logging->setEvent
  ("NonlinearSolver::evaluateJacobian()", "Solver");
  if (this->jacobian_function == NULL)
    {
    Driver::NonLinearAnalysisDriver* driver =
    dynamic_cast<Driver::NonLinearAnalysisDriver*>(this->analysis_driver);
    driver->getJacobianAtVector(sol, jac);
    }
  else
    this->jacobian_function(sol, jac, this->context);
  this->analysis_driver->getFESystemController().performance_logging->unsetEvent
    ("NonlinearSolver::evaluateJacobian()", "Solver");
}
void Solver::NonlinearSolver::evaluateResidual (NumericVector< double > & sol, NumericVector< double > & res)
evaluates the residual vector at the specified solution
Parameters:
sol vector at which the residual should be evaluated
res vector in which the residual is stored
Definition at line 73 of file NonlinearSolver.C.
References Driver::NonLinearAnalysisDriver::getResidualAtVector().
Referenced by FESystemNonlinearSolverFunctionEvaluation().
{
  this->analysis_driver->getFESystemController().performance_logging->setEvent
  ("NonlinearSolver::evaluateResidual()", "Solver");
  if (this->jacobian_function == NULL)
    {
    Driver::NonLinearAnalysisDriver* driver =
    dynamic_cast<Driver::NonLinearAnalysisDriver*>(this->analysis_driver);
    driver->getResidualAtVector(sol, res);
    }
  else
    this->residual_function(sol,res, this->context);
  this->analysis_driver->getFESystemController().performance_logging->unsetEvent
    ("NonlinearSolver::evaluateResidual()", "Solver");
}
virtual unsigned int Solver::NonlinearSolver::getCurrentIterationNumber () const [pure virtual]
this returns the itertion number of the solution process
Implemented in Solver::PetscNonlinearSolver, and Solver::NewtonNonlinearSolver.
unsigned int Solver::NonlinearSolver::getNonlinearSolverKindEnumID () const [inline]
Definition at line 130 of file NonlinearSolver.h.
References nonlinear_solver_kind_enum_ID.
{
  return this->nonlinear_solver_kind_enum_ID;
}
std::string Solver::NonlinearSolver::getNonlinearSolverKindEnumName () const [inline]
Definition at line 142 of file NonlinearSolver.h.
{
  return Solver::NonlinearSolverKindEnum::enumName(this->nonlinear_solver_kind_enum_ID);
}
void Solver::NonlinearSolver::setFunctions (void(*)(NumericVector< double > &sol, NumericVector< double > &res, void *ctx) res_func, void(*)(NumericVector< double > &sol, SparseMatrix< double > &jac, void *ctx) jac_func, void * ctx)
this function can be used to set the functions that are called by the nonlinear solver to calculate the jacobian and the residual. if this is not done, then the solver uses the default functions that ask the analysis driver for the information.
Definition at line 51 of file NonlinearSolver.C.
{
  Assert(this->residual_function == NULL, ExcInternalError());
  Assert(this->jacobian_function == NULL, ExcInternalError());
  Assert(this->context == NULL, ExcInternalError());
  Assert(res_func != NULL, ExcInternalError());
  Assert(jac_func != NULL, ExcInternalError());
  this->residual_function = res_func;
  this->jacobian_function = jac_func;
  this->context = ctx;
}
virtual void Solver::NonlinearSolver::solve (NumericVector< double > & solution) [pure virtual]
function to perform solution steps.
Parameters:
solution vector in which the solution will be returned. This should be initialized to the initial guess
Implemented in Solver::PetscNonlinearSolver, and Solver::NewtonNonlinearSolver.
Referenced by Driver::NonLinearAnalysisDriver::solveCurrentLoadCase().
Member Data Documentation
void* Solver::NonlinearSolver::context [protected]
Definition at line 120 of file NonlinearSolver.h.
SparseMatrix<double>* Solver::NonlinearSolver::jacobian [protected]
Definition at line 108 of file NonlinearSolver.h.
void(* Solver::NonlinearSolver::jacobian_function)(NumericVector< double > &sol, SparseMatrix< double > &jac, void *ctx) [protected]
Definition at line 112 of file NonlinearSolver.h.
const Solver::LinearSolverInfo& Solver::NonlinearSolver::linear_solver_info [protected]
Definition at line 106 of file NonlinearSolver.h.
const Solver::NonlinearSolverInfo& Solver::NonlinearSolver::nonlinear_solver_info [protected]
Definition at line 105 of file NonlinearSolver.h.
const unsigned int Solver::NonlinearSolver::nonlinear_solver_kind_enum_ID [protected]
Definition at line 104 of file NonlinearSolver.h.
Referenced by getNonlinearSolverKindEnumID().
NumericVector<double>* Solver::NonlinearSolver::residual [protected]
Definition at line 110 of file NonlinearSolver.h.
void(* Solver::NonlinearSolver::residual_function)(NumericVector< double > &sol, NumericVector< double > &res, void *ctx) [protected]
Definition at line 116 of file NonlinearSolver.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/NonlinearSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/NonlinearSolver.C