fesystem: SurfaceLoadSet Class Reference
SurfaceLoadSet Class Reference
#include <LoadSet.h>
Public Member Functions
SurfaceLoadSet ()
~SurfaceLoadSet ()
virtual unsigned int getLoadSetKindEnumID () const
void getLoadsForElement (const unsigned int, std::vector< const SurfaceLoad * > &loads) const
void getLoadsForElementSide (const unsigned int, const unsigned int, std::vector< const SurfaceLoad * > &loads) const
This will find loads for the specified side of an element.
void getAllLoads (std::vector< const SurfaceLoad * > &loads) const
virtual std::istream & readFromInputStream (std::istream &input)
Protected Attributes
std::multimap< unsigned int,
SurfaceLoad * > elem_ID_to_load_map
Detailed Description
Definition at line 183 of file LoadSet.h.
Constructor & Destructor Documentation
SurfaceLoadSet::SurfaceLoadSet ()
Definition at line 400 of file LoadSet.C.
                              :
  LoadSetBase()
{
}
SurfaceLoadSet::~SurfaceLoadSet ()
Definition at line 408 of file LoadSet.C.
References elem_ID_to_load_map.
{
  // iterate over all loads and delete them
  std::multimap<unsigned int, SurfaceLoad*>::iterator it, end;
  it = this->elem_ID_to_load_map.begin();
  end = this->elem_ID_to_load_map.end();
  for (; it != end; it++)
    {
      delete it->second;
      it->second = NULL;
    }
  this->elem_ID_to_load_map.clear();
}
Member Function Documentation
void SurfaceLoadSet::getAllLoads (std::vector< const SurfaceLoad * > & loads) const
Definition at line 469 of file LoadSet.C.
References elem_ID_to_load_map.
{
  std::multimap<unsigned int, SurfaceLoad*>::const_iterator it, end;
  it = this->elem_ID_to_load_map.begin();
  end = this->elem_ID_to_load_map.end();
  loads.resize(this->elem_ID_to_load_map.size());
  unsigned int i=0;
  for (; it != end; it++)
    {
      loads[i] = it->second;
      i++;
    }
}
unsigned int SurfaceLoadSet::getLoadSetKindEnumID () const [virtual]
Implements LoadSetBase.
Definition at line 427 of file LoadSet.C.
{
  return SURFACE_LOAD_SET::num();
}
void SurfaceLoadSet::getLoadsForElement (const unsigned int elem_ID, std::vector< const SurfaceLoad * > & loads) const
This will search the loads in this set and add create a vector containing loads that act on an element
Definition at line 436 of file LoadSet.C.
References elem_ID_to_load_map.
{
  std::pair<std::multimap<unsigned int, SurfaceLoad*>::const_iterator,
    std::multimap<unsigned int, SurfaceLoad*>::const_iterator> it;
  it = this->elem_ID_to_load_map.equal_range(elem_ID);
  for (; it.first != it.second; it.first++)
    loads.push_back(it.first->second);
}
void SurfaceLoadSet::getLoadsForElementSide (const unsigned int elem_ID, const unsigned int side_num, std::vector< const SurfaceLoad * > & loads) const
This will find loads for the specified side of an element.
Definition at line 450 of file LoadSet.C.
References elem_ID_to_load_map.
Referenced by LoadDatabase::getLoadCombination< Loads::SurfaceLoadDataInfo, Loads::SurfaceLoadCombination >().
{
  std::pair<std::multimap<unsigned int, SurfaceLoad*>::const_iterator,
    std::multimap<unsigned int, SurfaceLoad*>::const_iterator> it;
  it = this->elem_ID_to_load_map.equal_range(elem_ID);
  for (; it.first != it.second; it.first++)
    {
      if (it.first->second->getSurfaceID() == side_num)
        loads.push_back(it.first->second);
    }
}
std::istream & SurfaceLoadSet::readFromInputStream (std::istream & input) [virtual]
Implements LoadSetBase.
Definition at line 486 of file LoadSet.C.
References createSurfaceLoad(), elem_ID_to_load_map, getLoadClassEnumIDForLoadName(), LoadSetBase::load_kind_enum_ID, LoadSetBase::load_set_ID, FESystemIOUtility::readFromInput(), and LoadSetBase::set_tag.
{
  std::string tag;
  unsigned int n_loads=0,  elem_ID = 0, load_class_enum_ID = 0;
  // the load set should begin with the BEGIN tag, and followed by
  // the number of loads in the set
  FESystemIOUtility::readFromInput(input, SURFACE_LOAD_SET::name());
  FESystemIOUtility::readFromInput(input, "BEGIN");
  // next, it should contain the name, ID and kind, and number of DOFs of load
  FESystemIOUtility::readFromInput(input, "NAME", this->set_tag);
  FESystemIOUtility::readFromInput(input, "ID", this->load_set_ID);
  tag.clear();
  FESystemIOUtility::readFromInput(input, "KIND", tag);
  this->load_kind_enum_ID = LoadNameEnum::enumID(tag);
  load_class_enum_ID = getLoadClassEnumIDForLoadName(this->load_kind_enum_ID);
  FESystemIOUtility::readFromInput(input, "N_LOADS", n_loads);
  std::auto_ptr<SurfaceLoad> load;
  for (unsigned int load_incr=0; load_incr < n_loads; load_incr++)
    {
      load.reset(createSurfaceLoad(load_class_enum_ID).release());
      load->readFromInputStream(input);
      elem_ID = load->getElemID();
      this->elem_ID_to_load_map.insert
        (std::multimap<unsigned int, SurfaceLoad*>::value_type
         (elem_ID, load.release()));
    }
  FESystemIOUtility::readFromInput(input, SURFACE_LOAD_SET::name());
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Member Data Documentation
std::multimap<unsigned int, SurfaceLoad*> SurfaceLoadSet::elem_ID_to_load_map [protected]
Definition at line 211 of file LoadSet.h.
Referenced by getAllLoads(), getLoadsForElement(), getLoadsForElementSide(), readFromInputStream(), and ~SurfaceLoadSet().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadSet.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadSet.C