fesystem: FESystemElem::FESystemElemNameEnumerationHandler Class Reference
FESystemElem::FESystemElemNameEnumerationHandler Class Reference
#include <FESystemElemTypeEnumHandler.h>
Public Member Functions
void registerEnumData (const unsigned int ID, const std::string &name, const ElemType elem_type)
ElemType getElemType (const unsigned int ID) const
Protected Types
typedef std::map< unsigned int,
ElemType > ElemKindMapType
Static Protected Attributes
static ElemKindMapType elem_kind_map
Detailed Description
Definition at line 20 of file FESystemElemTypeEnumHandler.h.
Member Typedef Documentation
typedef std::map<unsigned int, ElemType> FESystemElem::FESystemElemNameEnumerationHandler::ElemKindMapType [protected]
map for storing extra information about the elements, about which kind of geometric element they depend on
Definition at line 33 of file FESystemElemTypeEnumHandler.h.
Member Function Documentation
ElemType FESystemElem::FESystemElemNameEnumerationHandler::getElemType (const unsigned int ID) const [inline]
Definition at line 66 of file FESystemElemTypeEnumHandler.h.
References elem_kind_map.
Referenced by FESystemElem::FESystemElemTypeEnum::elemType().
    {
      // get the iterator from the map and return the ID
      FESystemElemNameEnumerationHandler::ElemKindMapType::const_iterator it, end;
      it = this->elem_kind_map.find(ID);
      end = this->elem_kind_map.end();
      Assert(it != end, ExcFESystemIDDoesNotExist(ID));
      return it->second;
    }
void FESystemElem::FESystemElemNameEnumerationHandler::registerEnumData (const unsigned int ID, const std::string & name, const ElemType elem_type) [inline]
Definition at line 40 of file FESystemElemTypeEnumHandler.h.
References elem_kind_map, and NameEnumerationHandler::registerNameAndID().
Referenced by FESystemElem::FESystemElemTypeEnum::EnumRegistration< EnumClass >::EnumRegistration().
    {
      this->registerNameAndID(ID, name);
      // find the name in the map. If it does not exist, add it, else return the
      // id for this name
      FESystemElemNameEnumerationHandler::ElemKindMapType::const_iterator it, end;
      it = this->elem_kind_map.find(ID);
      end = this->elem_kind_map.end();
      // make sure that the id and name are unique
      Assert(it == end, ExcFESystemNameAlreadyExists(ID, name));
      // now add the ID to the map
      std::pair<FESystemElem::FESystemElemNameEnumerationHandler::ElemKindMapType::iterator, bool>
        return_pair = this->elem_kind_map.insert
        (FESystemElemNameEnumerationHandler::ElemKindMapType::value_type(ID, elem_type));
      assert (return_pair.second == true);
    }
Member Data Documentation
FESystemElem::FESystemElemNameEnumerationHandler::ElemKindMapType FESystemElem::FESystemElemNameEnumerationHandler::elem_kind_map [static, protected]
Definition at line 34 of file FESystemElemTypeEnumHandler.h.
Referenced by getElemType(), and registerEnumData().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/FESystem/FESystemElemTypeEnumHandler.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/FESystem/FESystemStaticMemberDefinitions.C