fesystem: DesignData::DesignDatabase Class Reference
DesignData::DesignDatabase Class Reference
#include <DesignDatabase.h>
Public Member Functions
DesignDatabase ()
~DesignDatabase ()
std::auto_ptr< std::vector
< DesignData::DesignParameter * > > getParameters () const
returns the vector of all parameters
std::auto_ptr< std::vector
< DesignData::PropertyParameter * > > getPropertyParameters () const
returns the vector of property parameters
std::auto_ptr< std::vector
< DesignData::ShapeParameter * > > getShapeParameters () const
returns the vector of shape parameters
DesignParameter & getParameterForID (const unsigned int ID) const
returns a writable reference to parameter for the given ID
const unsigned int getNParams () const
returns the number of parameters
std::istream & readFromInputStream (std::istream &input)
Protected Types
typedef std::map< unsigned int,
DesignData::DesignParameter * > IDToParameterMap
local type definitions
Protected Member Functions
DeclException1 (ExcFESystemIDDoesNotExist, unsigned int,<< "Requested Parameter ID: "<< arg1<< " does not exist in map.")
this expception is thrown if the requested name does not exist in the map
DeclException1 (ExcDuplicateParameterID, unsigned int,<< "Parameter ID: "<< arg1<< " already exists in map.")
Protected Attributes
std::map< unsigned int,
DesignData::DesignParameter * > ID_to_design_parameter_map
vector of DVs
Private Member Functions
void addParameterToDatabase (DesignData::DesignParameter *param)
adds a parameter to the map. This method should be used only by this class
Friends
std::istream & operator>> (std::istream &input, DesignData::DesignDatabase &database)
overloaded operator to read from the input stream
Detailed Description
Definition at line 21 of file DesignDatabase.h.
Member Typedef Documentation
typedef std::map<unsigned int, DesignData::DesignParameter*> DesignData::DesignDatabase::IDToParameterMap [protected]
local type definitions
Definition at line 57 of file DesignDatabase.h.
Constructor & Destructor Documentation
DesignData::DesignDatabase::DesignDatabase ()
Definition at line 7 of file DesignDatabase.C.
{
}
DesignData::DesignDatabase::~DesignDatabase ()
Definition at line 15 of file DesignDatabase.C.
{
  // iterate over all the parameters and delete them, since they were created using
  // the new operator
  DesignData::DesignDatabase::IDToParameterMap::iterator param_it, param_end;
  param_it = this->ID_to_design_parameter_map.begin();
  param_end = this->ID_to_design_parameter_map.end();
  for (; param_it != param_end; param_it++)
    {
    delete param_it->second;
    param_it->second = NULL;
    }
}
Member Function Documentation
void DesignData::DesignDatabase::addParameterToDatabase (DesignData::DesignParameter * param) [inline, private]
adds a parameter to the map. This method should be used only by this class
Definition at line 183 of file DesignDatabase.h.
References DesignData::DesignParameter::getID().
{
  Assert(param != NULL,
         FESystemExceptions::ExcNullPointer());
  // make sure that the ID does not already exists
  unsigned int ID = param->getID();
  if (this->ID_to_design_parameter_map.find(ID) !=
      this->ID_to_design_parameter_map.end())
    {
    delete param; param = NULL;
    Assert(false, DesignData::DesignDatabase::ExcDuplicateParameterID(ID));
    }
  bool insert_success =
  this->ID_to_design_parameter_map.insert(DesignData::DesignDatabase::IDToParameterMap::
                                         value_type(ID, param)).second;
  Assert(insert_success, FESystemExceptions::ExcInsertUnsuccessful());
}
DesignData::DesignDatabase::DeclException1 (ExcFESystemIDDoesNotExist , unsigned int, << "Requested Parameter ID: "<< arg1<< " does not exist in map.") [protected]
this expception is thrown if the requested name does not exist in the map
DesignData::DesignDatabase::DeclException1 (ExcDuplicateParameterID , unsigned int, << "Parameter ID: "<< arg1<< " already exists in map.") [protected]
const unsigned int DesignData::DesignDatabase::getNParams () const [inline]
returns the number of parameters
Definition at line 173 of file DesignDatabase.h.
{
  return this->ID_to_design_parameter_map.size();
}
DesignData::DesignParameter & DesignData::DesignDatabase::getParameterForID (const unsigned int ID) const [inline]
returns a writable reference to parameter for the given ID
Definition at line 156 of file DesignDatabase.h.
{
  // search the map for the existence of this ID, if found, return the param reference
  // pointer
  DesignData::DesignDatabase::IDToParameterMap::const_iterator param_it =
  this->ID_to_design_parameter_map.find(ID);
  Assert(param_it != this->ID_to_design_parameter_map.end(),
         DesignData::DesignDatabase::ExcFESystemIDDoesNotExist(ID));
  return *(param_it->second);
}
std::auto_ptr< std::vector< DesignData::DesignParameter * > > DesignData::DesignDatabase::getParameters () const [inline]
returns the vector of all parameters
Definition at line 78 of file DesignDatabase.h.
References ID_to_design_parameter_map.
{
  // iterate over all the params in the map, add it to the vector
  std::auto_ptr<std::vector<DesignData::DesignParameter*> >
  vector(new std::vector<DesignData::DesignParameter*>());
  DesignData::DesignDatabase::IDToParameterMap::const_iterator param_it, param_end;
  param_it = this->ID_to_design_parameter_map.begin();
  param_end = this->ID_to_design_parameter_map.end();
  for (; param_it != param_end; param_it++)
    {
    vector->push_back(param_it->second);
    }
  return vector;
}
std::auto_ptr< std::vector< DesignData::PropertyParameter * > > DesignData::DesignDatabase::getPropertyParameters () const [inline]
returns the vector of property parameters
Definition at line 100 of file DesignDatabase.h.
{
  // iterate over all the DVs in the map, if type == property DV, add it to the vector
  std::auto_ptr<std::vector<DesignData::PropertyParameter*> >
  vector(new std::vector<DesignData::PropertyParameter*>());
  DesignData::DesignDatabase::IDToParameterMap::const_iterator param_it, param_end;
  param_it = this->ID_to_design_parameter_map.begin();
  param_end = this->ID_to_design_parameter_map.end();
  for (; param_it != param_end; param_it++)
    {
    if (param_it->second->getParameterTypeEnumID() ==
        DesignData::PROPERTY_PARAMETER::num())
      {
      DesignData::PropertyParameter* ptr =
      dynamic_cast<DesignData::PropertyParameter*>(param_it->second);
      vector->push_back(ptr);
      }
    }
  return vector;
}
std::auto_ptr< std::vector< DesignData::ShapeParameter * > > DesignData::DesignDatabase::getShapeParameters () const [inline]
returns the vector of shape parameters
Definition at line 128 of file DesignDatabase.h.
{
  // iterate over all the DVs in the map, if type == property DV, add it to the vector
  std::auto_ptr<std::vector<DesignData::ShapeParameter*> >
  vector(new std::vector<DesignData::ShapeParameter*>());
  DesignData::DesignDatabase::IDToParameterMap::const_iterator param_it, param_end;
  param_it = this->ID_to_design_parameter_map.begin();
  param_end = this->ID_to_design_parameter_map.end();
  for (; param_it != param_end; param_it++)
    {
    if (param_it->second->getParameterTypeEnumID() ==
        DesignData::SHAPE_PARAMETER::num())
      {
      DesignData::ShapeParameter* ptr =
      dynamic_cast<DesignData::ShapeParameter*>(param_it->second);
      vector->push_back(ptr);
      }
    }
  return vector;
}
std::istream & DesignData::DesignDatabase::readFromInputStream (std::istream & input)
Definition at line 33 of file DesignDatabase.C.
References FESystemIOUtility::peekFromInput(), PROPERTY_PARAMETER_ENUM_ID, FESystemIOUtility::readFromInput(), and SHAPE_PARAMETER_ENUM_ID.
{
  std::string tag;
  unsigned int num = 0, param_kind =0;
  DesignParameter *param = NULL;
  FESystemIOUtility::readFromInput(input, "DESIGN_DATABASE");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  // read in the list of design variables
  FESystemIOUtility::readFromInput(input, "DESIGN_PARAMETERS");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  FESystemIOUtility::readFromInput(input, "N_PARAMETERS", num);
  for (unsigned int param_it=0; param_it < num; param_it++)
    {
    tag.clear();
    FESystemIOUtility::peekFromInput(input, tag);
    param_kind = DesignParameterTypeEnum::enumID(tag);
    switch(param_kind)
      {
      case PROPERTY_PARAMETER_ENUM_ID:
        {
          PropertyParameter *prop_param = new DesignData::PropertyParameter;
          input >> (*prop_param);
          param = prop_param;
        }
        break;
      case SHAPE_PARAMETER_ENUM_ID:
        {
          ShapeParameter *shape_param = new DesignData::ShapeParameter;
          input >> (*shape_param);
          param = shape_param;
        }
        break;
      }
    this->addParameterToDatabase(param);
    }
  FESystemIOUtility::readFromInput(input, "DESIGN_PARAMETERS");
  FESystemIOUtility::readFromInput(input, "END");
  FESystemIOUtility::readFromInput(input, "DESIGN_DATABASE");
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, DesignData::DesignDatabase & database) [friend]
overloaded operator to read from the input stream
Member Data Documentation
std::map<unsigned int, DesignData::DesignParameter*> DesignData::DesignDatabase::ID_to_design_parameter_map [protected]
vector of DVs
Definition at line 60 of file DesignDatabase.h.
Referenced by getParameters().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/DesignData/DesignDatabase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/DesignData/DesignDatabase.C