fesystem: Solver::PetscLinearSolver Class Reference
Solver::PetscLinearSolver Class Reference
#include <PetscLinearSolver.h>
Public Member Functions
PetscLinearSolver (const LinearSolverInfo &info)
~PetscLinearSolver ()
virtual void clear ()
method to clear the data structures
virtual void solve (NumericVector< double > &rhs, NumericVector< double > &sol)
KSP getKSP ()
PC getPC ()
Protected Member Functions
void createSolverContext ()
DeclException1 (ExcInvalidKSPType, std::string,<< "Invalid KSP type : "<< arg1<< " specified")
Protected Attributes
KSP ksp
the krylov solver context
KSPType ksptype
the type of KSP solver being used
PC pc
the PC context that will handle all the factoring of the matrices
PCType pctype
type of the PC to be used
PetscDrawLG petsc_draw
Detailed Description
Definition at line 48 of file PetscLinearSolver.h.
Constructor & Destructor Documentation
Solver::PetscLinearSolver::PetscLinearSolver (const LinearSolverInfo & info)
Definition at line 22 of file PetscLinearSolver.cpp.
References createSolverContext(), KSP_BCGS_ENUM_ID, KSP_BICG_ENUM_ID, KSP_CG_ENUM_ID, KSP_CGS_ENUM_ID, KSP_CHEBYCHEV_ENUM_ID, KSP_CR_ENUM_ID, KSP_GMRES_ENUM_ID, KSP_LSQR_ENUM_ID, KSP_PRE_ONLY_ENUM_ID, KSP_RICHARDSON_ENUM_ID, KSP_TCQMR_ENUM_ID, KSP_TFQMR_ENUM_ID, Solver::LinearSolver::ksp_type_enum_ID, ksptype, PC_ASM_ENUM_ID, PC_BJACOBI_ENUM_ID, PC_CHOLESKY_ENUM_ID, PC_EISENSTAT_ENUM_ID, PC_ICC_ENUM_ID, PC_ILU_ENUM_ID, PC_JACOBI_ENUM_ID, PC_KSP_ENUM_ID, PC_LU_ENUM_ID, PC_NONE_ENUM_ID, PC_SOR_ENUM_ID, Solver::LinearSolver::pc_type_enum_ID, and pctype.
                                                                      :
Solver::LinearSolver(info, PETSC_LINEAR_SOLVER::num()),
ksp(PETSC_NULL),
ksptype(PETSC_NULL),
pc(PETSC_NULL),
pctype(PETSC_NULL),
petsc_draw(PETSC_NULL)
{
    // set the pc type
  switch(this->pc_type_enum_ID)
  {
    case PC_LU_ENUM_ID:
      this->pctype = PCLU;
      break;
    case PC_JACOBI_ENUM_ID:
      this->pctype = PCJACOBI;
      break;
    case PC_BJACOBI_ENUM_ID:
      this->pctype = PCBJACOBI;
      break;
    case PC_SOR_ENUM_ID:
      this->pctype = PCSOR;
      break;
    case PC_EISENSTAT_ENUM_ID:
      this->pctype = PCEISENSTAT;
      break;
    case PC_ICC_ENUM_ID:
      this->pctype = PCICC;
      break;
    case PC_ILU_ENUM_ID:
      this->pctype = PCILU;
      break;
    case PC_ASM_ENUM_ID:
      this->pctype = PCASM;
      break;
    case PC_KSP_ENUM_ID:
      this->pctype = PCKSP;
      break;
    case PC_CHOLESKY_ENUM_ID:
      this->pctype = PCCHOLESKY;
      break;
    case PC_NONE_ENUM_ID:
      this->pctype = PCNONE;
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (Solver::PCTypeEnum::enumName(this->pc_type_enum_ID)));
  }
// set the ksp type
  switch(this->ksp_type_enum_ID)
  {
    case KSP_RICHARDSON_ENUM_ID:
      this->ksptype = KSPRICHARDSON;
      break;
    case KSP_CHEBYCHEV_ENUM_ID:
      this->ksptype = KSPCHEBYCHEV;
      break;
    case KSP_CG_ENUM_ID:
      this->ksptype = KSPCG;
      break;
    case KSP_GMRES_ENUM_ID:
      this->ksptype = KSPGMRES;
      break;
    case KSP_TCQMR_ENUM_ID:
      this->ksptype = KSPTCQMR;
      break;
    case KSP_BCGS_ENUM_ID:
      this->ksptype = KSPBCGS;
      break;
    case KSP_CGS_ENUM_ID:
      this->ksptype = KSPCGS;
      break;
    case KSP_TFQMR_ENUM_ID:
      this->ksptype = KSPTFQMR;
      break;
    case KSP_CR_ENUM_ID:
      this->ksptype = KSPCR;
      break;
    case KSP_LSQR_ENUM_ID:
      this->ksptype = KSPLSQR;
      break;
    case KSP_BICG_ENUM_ID:
      this->ksptype = KSPBICG;
      break;
    case KSP_PRE_ONLY_ENUM_ID:
      this->ksptype = KSPPREONLY;
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (Solver::KSPTypeEnum::enumName(this->ksp_type_enum_ID)));
  }
  this->createSolverContext();
}
Solver::PetscLinearSolver::~PetscLinearSolver ()
Definition at line 147 of file PetscLinearSolver.cpp.
References FESystem::COMM_WORLD, and FESystem::local_processor.
{
    PetscErrorCode ierr=0;
  // the petsc draw context is to be deleted only on the 0 processor
  if (FESystem::local_processor == 0)
    {
      if (this->petsc_draw != PETSC_NULL)
        {
          ierr = KSPMonitorLGDestroy(this->petsc_draw);
          CHKERRABORT(FESystem::COMM_WORLD, ierr);
          this->petsc_draw = PETSC_NULL;
        }
    }
  // delete the PC and KSP contexts if they have been created
  if (this->pc != PETSC_NULL)
  {
    ierr = PCDestroy(this->pc);
    CHKERRABORT(FESystem::COMM_WORLD, ierr);
    this->pc = PETSC_NULL;
  }
  if (this->ksp != PETSC_NULL)
  {
    ierr = KSPDestroy(this->ksp);
    CHKERRABORT(FESystem::COMM_WORLD, ierr);
    this->ksp = PETSC_NULL;
  }
}
Member Function Documentation
void Solver::PetscLinearSolver::clear () [virtual]
method to clear the data structures
Reimplemented from Solver::LinearSolver.
Definition at line 257 of file PetscLinearSolver.cpp.
References Solver::LinearSolver::clear().
{
  Solver::LinearSolver::clear();
}
void Solver::PetscLinearSolver::createSolverContext () [protected]
Definition at line 182 of file PetscLinearSolver.cpp.
References FESystem::COMM_WORLD, and FESystem::local_processor.
Referenced by PetscLinearSolver().
{
  PetscErrorCode ierr = 0;
  // the petsc draw context is to be deleted only on the 0 processor
  if (FESystem::local_processor == 0)
    {
      if (this->petsc_draw != PETSC_NULL)
        {
          ierr = KSPMonitorLGDestroy(this->petsc_draw);
          CHKERRABORT(FESystem::COMM_WORLD, ierr);
          this->petsc_draw = PETSC_NULL;
        }
    }
  if (this->pc != PETSC_NULL)
    {
      ierr = PCDestroy(this->pc);
      CHKERRABORT(FESystem::COMM_WORLD, ierr);
      this->pc = PETSC_NULL;
    }
  if (this->ksp != PETSC_NULL)
    {
      ierr = KSPDestroy(this->ksp);
      CHKERRABORT(FESystem::COMM_WORLD, ierr);
      this->ksp = PETSC_NULL;
    }
  {
    ierr = KSPCreate(FESystem::COMM_WORLD, &(this->ksp));
    CHKERRABORT(FESystem::COMM_WORLD, ierr);
    ierr = KSPSetType(this->ksp, this->ksptype);
    CHKERRABORT(FESystem::COMM_WORLD, ierr);
    if (this->pc_type_enum_ID != Solver::PC_NONE::num())
      {
        ierr = PCCreate(FESystem::COMM_WORLD, &(this->pc));
        CHKERRABORT(FESystem::COMM_WORLD, ierr);
        ierr = PCSetType(this->pc, this->pctype);
        CHKERRABORT(FESystem::COMM_WORLD, ierr);
        ierr = KSPSetPC(this->ksp, this->pc);
        CHKERRABORT(FESystem::COMM_WORLD, ierr);
      }
  }
//  ierr = KSPMonitorLGTrueResidualNormCreate
//  (FESystem::COMM_WORLD, PETSC_NULL, "residual norm", 0, 0, 500, 500, &(this->petsc_draw));
//  CHKERRABORT(FESystem::COMM_WORLD, ierr);
}
Solver::PetscLinearSolver::DeclException1 (ExcInvalidKSPType , std::string , << "Invalid KSP type : "<< arg1<< " specified") [protected]
KSP Solver::PetscLinearSolver::getKSP ()
Returns:
the Petsc KSP object
Definition at line 239 of file PetscLinearSolver.cpp.
{
  return this->ksp;
}
PC Solver::PetscLinearSolver::getPC ()
Returns:
the Petsc PC object
Definition at line 248 of file PetscLinearSolver.cpp.
{
  return this->pc;
}
void Solver::PetscLinearSolver::solve (NumericVector< double > & rhs, NumericVector< double > & sol) [virtual]
this is a function that implements the solution steps. Before this function is called, the matrices should already have been set.
Parameters:
rhs right hand side of the system of equations
sol vector in which solution will be stored
Implements Solver::LinearSolver.
Definition at line 269 of file PetscLinearSolver.cpp.
References FESystem::COMM_WORLD.
{
  this->analysis_driver->getFESystemController().performance_logging->setEvent
  ("DirectLinearSolver::solve()", "Solver");
  PetscErrorCode ierr = 0;
  // next, solve
  PetscVector<double>& rhs_ref = dynamic_cast<PetscVector<double>& >(rhs);
  PetscVector<double>& sol_ref = dynamic_cast<PetscVector<double>& >(sol);
  MatStructure petsc_pc_option;
  // if the same matrix option between solves is false, then new matrices must
  // be specified, otherwise, there should be no change between the solves
  if (this->same_matrices_between_solves)
  {
    if (this->new_PC_matrix || this->new_system_matrix)
    {
      // if same matrix is to be used, and new ones have been specified, then
      // the number of time these have been used should be zero
      Assert (this->n_solves_after_new_matrices == 0, ExcInternalError());
    }
    else
    {
      // if new matrices have not been given, then these must have been used
      Assert (this->n_solves_after_new_matrices > 0, ExcInternalError());
    }
    petsc_pc_option = SAME_PRECONDITIONER;
  }
  else
  {
    // if new matrices have to be given at each iteration, then
    // the number of solves after new matrices should be 0
    Assert (this->n_solves_after_new_matrices == 0, ExcInternalError());
    petsc_pc_option = DIFFERENT_NONZERO_PATTERN;
  }
  // attach the matrices to the solver before solving if new ones have been specified
  if (this->new_system_matrix || this->new_PC_matrix)
  {
    this->createSolverContext();
    Assert(this->system_matrix != NULL, ExcInternalError());
    this->system_matrix->close();
    Mat sys_mat = (dynamic_cast<PetscMatrix<double>* >(this->system_matrix))->mat();
    if (this->pc_type_enum_ID != Solver::PC_NONE::num())
    {
      Assert(this->preconditioner_matrix != NULL, ExcInternalError());
      this->preconditioner_matrix->close();
      Mat pc_mat = (dynamic_cast<PetscMatrix<double>* >(this->preconditioner_matrix))->mat();
      ierr = KSPSetOperators(this->ksp, sys_mat, pc_mat, petsc_pc_option);
    }
    else
      ierr = KSPSetOperators(this->ksp, sys_mat, sys_mat, petsc_pc_option);
    CHKERRABORT(FESystem::COMM_WORLD, ierr);
    ierr = KSPSetUp(this->ksp);
    CHKERRABORT(FESystem::COMM_WORLD, ierr);
  }
  rhs_ref.close();
  sol_ref.close();
  ierr = KSPSolve(this->ksp, rhs_ref.vec(), sol_ref.vec());
  CHKERRABORT(FESystem::COMM_WORLD, ierr);
  this->n_solves_after_new_matrices += 1;
  // the matrices now are no longer new
  this->new_system_matrix = false;
  this->new_PC_matrix = false;
  this->analysis_driver->getFESystemController().performance_logging->unsetEvent
  ("DirectLinearSolver::solve()", "Solver");
}
Member Data Documentation
KSP Solver::PetscLinearSolver::ksp [protected]
the krylov solver context
Definition at line 81 of file PetscLinearSolver.h.
KSPType Solver::PetscLinearSolver::ksptype [protected]
the type of KSP solver being used
Definition at line 84 of file PetscLinearSolver.h.
Referenced by PetscLinearSolver().
PC Solver::PetscLinearSolver::pc [protected]
the PC context that will handle all the factoring of the matrices
Definition at line 87 of file PetscLinearSolver.h.
PCType Solver::PetscLinearSolver::pctype [protected]
type of the PC to be used
Definition at line 90 of file PetscLinearSolver.h.
Referenced by PetscLinearSolver().
PetscDrawLG Solver::PetscLinearSolver::petsc_draw [protected]
Definition at line 92 of file PetscLinearSolver.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/PetscLinearSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/PetscLinearSolver.cpp