fesystem: Solver::EigenSolverBase Class Reference
Solver::EigenSolverBase Class Reference
#include <EigenSolver.h>
Public Member Functions
EigenSolverBase (const Solver::EigenSolverInfo &eigen_info, const Solver::LinearSolverInfo &linear_info)
constructor
virtual ~EigenSolverBase ()
virtual unsigned int getNConvergedEigenPairs ()=0
virtual void getEigenValue (unsigned int eigen_index, double *real_value, double *img_value)=0
virtual void getEigenPair (unsigned int pair_index, double *real_value, double *img_value, NumericVector< double > &real_vec, NumericVector< double > &img_vec)=0
virtual void getInvariantSubspace (std::vector< NumericVector< double > * > &vectors)=0
virtual double getEigenPairResidualError (const unsigned int index)=0
virtual double getEigenPairRelativeError (const unsigned int index)=0
virtual void solve (SparseMatrix< double > *A_mat, SparseMatrix< double > *B_mat=NULL)=0
method to solve the eigen system
virtual double getResidualForEigenPair (const unsigned int i)=0
this method calculates a residual for the given eigen value and returns it
Protected Attributes
const Solver::EigenSolverInfo & eigen_solver_info
EigenSolverInfo that stores information about this solver.
const Solver::LinearSolverInfo & linear_solver_info
LinearSolverInfo that stores information about this solver.
Detailed Description
this class provides an interface to a solver for the solution of eigensystem. This inherits from the FESystemSolverBase class. It takes a pointer to the analysis driver object that owns an instantiation of this class
Definition at line 317 of file EigenSolver.h.
Constructor & Destructor Documentation
Solver::EigenSolverBase::EigenSolverBase (const Solver::EigenSolverInfo & eigen_info, const Solver::LinearSolverInfo & linear_info)
constructor
Definition at line 11 of file EigenSolver.C.
                                                                                   :
Solver::FESystemSolverBase(dynamic_cast<const Solver::SolverInfo&>(eigen_info)),
eigen_solver_info(eigen_info),
linear_solver_info(linear_info)
{
}
Solver::EigenSolverBase::~EigenSolverBase () [virtual]
Definition at line 20 of file EigenSolver.C.
{
}
Member Function Documentation
virtual void Solver::EigenSolverBase::getEigenPair (unsigned int pair_index, double * real_value, double * img_value, NumericVector< double > & real_vec, NumericVector< double > & img_vec) [pure virtual]
this method returns the eigen pair
Parameters:
pair_index index of the requested eigenpair
real_value real part of the eigenvalue
img_value imaginary part of the eigenvalue
real_vec real part of the eigenvector
img_vec imaginary part of the eigenvector
Implemented in Solver::ArpackEigenSolver, and Solver::SlepcEigenSolver.
Referenced by Driver::EigenProblemAnalysisDriver::solveCurrentLoadCase(), and Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
virtual double Solver::EigenSolverBase::getEigenPairRelativeError (const unsigned int index) [pure virtual]
this method computes and returns the relative error for the specified eigen value index. This is only for Hermitian problems
Implemented in Solver::ArpackEigenSolver, and Solver::SlepcEigenSolver.
virtual double Solver::EigenSolverBase::getEigenPairResidualError (const unsigned int index) [pure virtual]
this method computes and returns the residual error for the specified eigen value index. This is only for Hermitian problems
Implemented in Solver::ArpackEigenSolver, and Solver::SlepcEigenSolver.
virtual void Solver::EigenSolverBase::getEigenValue (unsigned int eigen_index, double * real_value, double * img_value) [pure virtual]
this method returns the eigen valie
Parameters:
pair_index index of the requested eigenvalue
real_value real part of the eigenvalue
img_value imaginary part of the eigenvalue
Implemented in Solver::ArpackEigenSolver, and Solver::SlepcEigenSolver.
virtual void Solver::EigenSolverBase::getInvariantSubspace (std::vector< NumericVector< double > * > & vectors) [pure virtual]
Implemented in Solver::ArpackEigenSolver, and Solver::SlepcEigenSolver.
Referenced by Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
virtual unsigned int Solver::EigenSolverBase::getNConvergedEigenPairs () [pure virtual]
Returns:
the number of converged eigen pairs
Implemented in Solver::ArpackEigenSolver, and Solver::SlepcEigenSolver.
Referenced by Driver::EigenProblemAnalysisDriver::solveCurrentLoadCase(), and Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
virtual double Solver::EigenSolverBase::getResidualForEigenPair (const unsigned int i) [pure virtual]
this method calculates a residual for the given eigen value and returns it
Implemented in Solver::ArpackEigenSolver, and Solver::SlepcEigenSolver.
virtual void Solver::EigenSolverBase::solve (SparseMatrix< double > * A_mat, SparseMatrix< double > * B_mat = NULL) [pure virtual]
method to solve the eigen system
Implemented in Solver::ArpackEigenSolver, and Solver::SlepcEigenSolver.
Referenced by Driver::EigenProblemAnalysisDriver::solveCurrentLoadCase(), and Driver::RogerApproximationAeroelasticityDriver::solveCurrentLoadCase().
Member Data Documentation
const Solver::EigenSolverInfo& Solver::EigenSolverBase::eigen_solver_info [protected]
EigenSolverInfo that stores information about this solver.
Definition at line 377 of file EigenSolver.h.
const Solver::LinearSolverInfo& Solver::EigenSolverBase::linear_solver_info [protected]
LinearSolverInfo that stores information about this solver.
Definition at line 380 of file EigenSolver.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/EigenSolver.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Solvers/EigenSolver.C