fesystem: FunctionDatabase Class Reference
FunctionDatabase Class Reference
#include <FunctionDatabase.h>
Public Member Functions
FunctionDatabase ()
constructor
~FunctionDatabase ()
Destructor.
void getScalarFunctionValue (const unsigned int func_ID, const double input, double &func_value) const
void getScalarFunctionDerivative (const unsigned int func_ID, const double input, double &func_value) const
const FunctionBase & getFunction (const unsigned int ID) const
this method returns a constant reference to the function base object defined by the ID
std::istream & readFromInputStream (std::istream &input)
reads from the input stream
Protected Types
typedef std::map< unsigned int,
FunctionBase * > FunctionMapType
local type definitions
Protected Member Functions
DeclException1 (ExcFunctionIDDoesNotExist, unsigned int,<< " Requested ID: "<< arg1<< " does not exist in FunctionDatabase")
this exception is thrown if an ID requested by the user does not exist in the database
Protected Attributes
FunctionMapType id_to_function_map
map that stores the functions against their ID
Friends
std::istream & operator>> (std::istream &input, FunctionDatabase &obj)
this operator reads the card from an input stream
Detailed Description
this class provides the functionality of an interface to the different function classes, in deal.II and FESystem. This is needed since deal.II has multiple classes for functions, i.e. Polynomial and Function, which provide the same basic functionality. One way would have been to create a base class named FunctionBase and derive all these classes out of that so that all of them could be stored as a single pointer. However, they are implemented with different method names and hence, inheritence would have been confusing. Hence, this helper class was conceived to hangle the hetrogeniety in these functions, but still provide a uniform interface. This class is more like a database of functions, and will store all functions with an ID associated with them. Then, each function can be accessed from this database, or the interface of this class can be used to access the methods of each individual class
Definition at line 29 of file FunctionDatabase.h.
Member Typedef Documentation
typedef std::map<unsigned int, FunctionBase*> FunctionDatabase::FunctionMapType [protected]
local type definitions
Definition at line 102 of file FunctionDatabase.h.
Constructor & Destructor Documentation
FunctionDatabase::FunctionDatabase ()
constructor
Definition at line 15 of file FunctionDatabase.C.
{
}
FunctionDatabase::~FunctionDatabase ()
Destructor.
Definition at line 20 of file FunctionDatabase.C.
References id_to_function_map.
{
  // iterate over all the function objects and delete them
  FunctionDatabase::FunctionMapType::iterator it, end;
  it = this->id_to_function_map.begin();
  end = this->id_to_function_map.end();
  for (; it != end; it++)
    {
      delete it->second;
      it->second = NULL;
    }
}
Member Function Documentation
FunctionDatabase::DeclException1 (ExcFunctionIDDoesNotExist , unsigned int, << " Requested ID: "<< arg1<< " does not exist in FunctionDatabase") [protected]
this exception is thrown if an ID requested by the user does not exist in the database
const FunctionBase & FunctionDatabase::getFunction (const unsigned int ID) const [inline]
this method returns a constant reference to the function base object defined by the ID
Definition at line 112 of file FunctionDatabase.h.
References id_to_function_map, and FESystemNumbers::InvalidID.
{
  // make sure that this ID is valid
  Assert(ID != FESystemNumbers::InvalidID,
         FESystemExceptions::ExcInvalidID(ID));
  // make sure that this function ID exists in the map, and if it does, return it
  FunctionDatabase::FunctionMapType::const_iterator it, end;
  it = this->id_to_function_map.find(ID);
  end = this->id_to_function_map.end();
  Assert(it != end,
         FunctionDatabase::ExcFunctionIDDoesNotExist(ID));
  return *(it->second);
}
void FunctionDatabase::getScalarFunctionDerivative (const unsigned int func_ID, const double input, double & func_value) const [inline]
returns the derivative value of the function whose ID has been specified. The coordinates where the function derivative needs to be evaluated is also specified in the input. This method returns the calculated data in created objects, and hence, has to create it each time the function is called. Hence, to save on computational cost, the more specialized functions in the API should be called.
Definition at line 147 of file FunctionDatabase.h.
References FunctionBase::getFunctionDerivative().
{
  const FunctionBase & func_base = this->getFunction(func_ID);
  func_base.getFunctionDerivative(input, value);
}
void FunctionDatabase::getScalarFunctionValue (const unsigned int func_ID, const double input, double & func_value) const [inline]
returns the value of the function whose ID has been specified. The coordinates where the function needs to be evaluated is also specified in the input. This method returns the calculated data in created objects, and hence, has to create it each time the function is called. Hence, to save on computational cost, the more specialized functions in the API should be called.
Definition at line 135 of file FunctionDatabase.h.
References FunctionBase::getFunctionValue().
{
  const FunctionBase & func_base = this->getFunction(func_ID);
  func_base.getFunctionValue(input, value);
}
std::istream & FunctionDatabase::readFromInputStream (std::istream & input)
reads from the input stream
Definition at line 40 of file FunctionDatabase.C.
References FunctionBase::getID(), id_to_function_map, MULTILINEAR_FUNCTION_ENUM_ID, FESystemIOUtility::peekFromInput(), and FESystemIOUtility::readFromInput().
Referenced by operator>>().
{
  std::string tag;
  unsigned int num = 0, enumID =0;
  // beginning of function cards
  FESystemIOUtility::readFromInput(input, "FUNCTION_DATABASE");
  FESystemIOUtility::readFromInput(input, "BEGIN");
  // number of function cards
  FESystemIOUtility::readFromInput(input, "N_FUNCTIONS", num);
  FunctionBase *func_base = NULL;
  bool insert_success = false;
  for (unsigned int i=0; i < num; i++)
    {
    tag.clear();
    // input the type of function card
    FESystemIOUtility::peekFromInput(input, tag);
    enumID = FunctionTypeEnum::enumID(tag);
    switch (enumID)
      {
      case  MULTILINEAR_FUNCTION_ENUM_ID:
        {
          MultilinearFunction *func = new MultilinearFunction;
          input >> (*func);
          func_base = func;
        }
        break;
      default:
        {
          Assert(false, FESystemExceptions::ExcEnumCaseNotImplemented(tag));
        }
        break;
      }
    // now add the function to the map
    insert_success = this->id_to_function_map.insert(FunctionDatabase::FunctionMapType::value_type
                                                     (func_base->getID(), func_base)).second;
    }
  // make sure it ends right
  FESystemIOUtility::readFromInput(input, "FUNCTION_DATABASE");
  FESystemIOUtility::readFromInput(input, "END");
  return input;
}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & input, FunctionDatabase & obj) [friend]
this operator reads the card from an input stream
Definition at line 100 of file FunctionDatabase.C.
{
  obj.readFromInputStream(input);
  return input;
}
Member Data Documentation
FunctionMapType FunctionDatabase::id_to_function_map [protected]
map that stores the functions against their ID
Definition at line 105 of file FunctionDatabase.h.
Referenced by getFunction(), readFromInputStream(), and ~FunctionDatabase().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/FunctionDatabase.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Database/FunctionDatabase.C