fesystem: FESystemUtility::TimeLogs Class Reference
FESystemUtility::TimeLogs Class Reference
#include <TimeLogs.h>
Public Member Functions
TimeLogs ()
constructor
~TimeLogs ()
destructor
void setEvent (const std::string &event_name, const std::string &header)
void unsetEvent (const std::string &event_name, const std::string &header)
Protected Attributes
std::auto_ptr
< FESystemUtility::PerformanceLogging > performance_logging
the performance log object
std::map< std::string,
FESystemUtility::HeaderEventData * > event_map
map of headers and events
Detailed Description
this class builds on top of the libmesh FESystemUtility::PerformanceLogging class, and provides some additional functionality
Definition at line 231 of file TimeLogs.h.
Constructor & Destructor Documentation
FESystemUtility::TimeLogs::TimeLogs ()
constructor
Definition at line 155 of file TimeLogs.C.
                                 :
performance_logging(new FESystemUtility::PerformanceLogging("FESystem Run Time Log", true))
{
}
FESystemUtility::TimeLogs::~TimeLogs ()
destructor
Definition at line 163 of file TimeLogs.C.
{
  // iterate and delete the header event data
  std::map<std::string, FESystemUtility::HeaderEventData*>::iterator it, end;
  it = this->event_map.begin();
  end = this->event_map.end();
  for (; it != end; it++)
    delete it->second;
  this->event_map.clear();
}
Member Function Documentation
void FESystemUtility::TimeLogs::setEvent (const std::string & event_name, const std::string & header)
this method sets the event under the given header. This behaves in the following way:
-- if no other event is being logged in the given header, then this event defines the first event and is started
-- if the current event in the header being logged is the same as the given event, then it checks if the event was paused or not. If it was paused, it restarts the event. Otherwise, it adds to the call counter of the event
-- if the current event in the header is different, then if the event is not already paused, it pauses the event, and sets the current logged event to the given event
Definition at line 178 of file TimeLogs.C.
References FESystemUtility::HeaderEventData::getCurrentEvent(), FESystemUtility::HeaderEventData::getCurrentStatus(), FESystemUtility::HeaderEventData::getEventCallCount(), FESystemUtility::HeaderEventData::RUNNING, FESystemUtility::HeaderEventData::setCurrentEvent(), and FESystemUtility::HeaderEventData::STOPPED.
{
  if (this->event_map.count(header) == 0)
    this->event_map[header] = new HeaderEventData;
  FESystemUtility::HeaderEventData& header_data = *(this->event_map[header]);
  switch (header_data.getCurrentStatus())
    {
    case FESystemUtility::HeaderEventData::RUNNING:
      {
        if (header_data.getCurrentEvent() == event_name)
          header_data.setCurrentEvent(event_name);
        else
          {
          this->performance_logging->pause_event(header_data.getCurrentEvent(),
                                                 header);
          header_data.setCurrentEvent(event_name);
          // if the event has been called multiple times, it will be restarted, instead
          // of being started, since that means that the event was paused earlier
          if (header_data.getEventCallCount(header_data.getCurrentEvent()) > 1)
            this->performance_logging->restart_event(header_data.getCurrentEvent(),
                                                     header);
          else
            this->performance_logging->start_event(header_data.getCurrentEvent(),
                                                   header);
          }
      }
      break;
    case FESystemUtility::HeaderEventData::STOPPED:
      {
        // there is no logging being performed, and hence, the first event
        // is being started now.
        header_data.setCurrentEvent(event_name);
        this->performance_logging->start_event(header_data.getCurrentEvent(),
                                               header);
      }
      break;
    }
}
void FESystemUtility::TimeLogs::unsetEvent (const std::string & event_name, const std::string & header)
this method unsets the current event and switches the event back to the one that was being logged before the current event. It is an error to unset an event if it is not currently being logged.
Definition at line 226 of file TimeLogs.C.
References FESystemUtility::HeaderEventData::removeCurrentEvent().
{
  Assert(this->event_map.count(header) > 0, ExcInternalError());
  FESystemUtility::HeaderEventData& header_data = *(this->event_map[header]);
  Assert (header_data.getCurrentEvent() == event_name, ExcInternalError());
  header_data.removeCurrentEvent(event_name);
  // if the next event is also the same as the event just stopped, then do not stop logging
  if (header_data.eventsExist())
    {
    // even after removing this event, if the call count is still zero for it,
    // then pause the event, and do not stop it
    if (header_data.getEventCallCount(event_name) > 0)
      this->performance_logging->pause_event(event_name, header);
    else
      this->performance_logging->stop_event(event_name, header);
    // next, simply restart the current event.
    this->performance_logging->restart_event(header_data.getCurrentEvent(), header);
    }
  else
    this->performance_logging->stop_event(event_name, header);
}
Member Data Documentation
std::map<std::string, FESystemUtility::HeaderEventData*> FESystemUtility::TimeLogs::event_map [protected]
map of headers and events
Definition at line 267 of file TimeLogs.h.
std::auto_ptr<FESystemUtility::PerformanceLogging> FESystemUtility::TimeLogs::performance_logging [protected]
the performance log object
Definition at line 264 of file TimeLogs.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Utilities/TimeLogs.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Utilities/TimeLogs.C