fesystem: Loads::ElemLoadDataInfo Class Reference
Loads::ElemLoadDataInfo Class Reference
#include <LoadDataInfo.h>
Public Member Functions
ElemLoadDataInfo ()
virtual ~ElemLoadDataInfo ()
virtual void clear ()
void setElemID (const unsigned int ID)
unsigned int getElemID () const
Protected Attributes
unsigned int elem_ID
Detailed Description
Definition at line 89 of file LoadDataInfo.h.
Constructor & Destructor Documentation
Loads::ElemLoadDataInfo::ElemLoadDataInfo ()
Definition at line 184 of file LoadDataInfo.C.
                                       :
Loads::LoadDataInfoBase(),
elem_ID(FESystemNumbers::InvalidID)
{
}
Loads::ElemLoadDataInfo::~ElemLoadDataInfo () [virtual]
Definition at line 193 of file LoadDataInfo.C.
{
  this->clear();
}
Member Function Documentation
void Loads::ElemLoadDataInfo::clear () [virtual]
Reimplemented from Loads::LoadDataInfoBase.
Reimplemented in Loads::SurfaceLoadDataInfo.
Definition at line 202 of file LoadDataInfo.C.
References Loads::LoadDataInfoBase::clear(), and FESystemNumbers::InvalidID.
Referenced by Loads::SurfaceLoadDataInfo::clear(), and Discipline::AnalysisDisciplineBase::getElemLoads().
{
  this->elem_ID = FESystemNumbers::InvalidID;
  Loads::LoadDataInfoBase::clear();
}
unsigned int Loads::ElemLoadDataInfo::getElemID () const
Definition at line 221 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by LoadDatabase::getLoadCombination< Loads::SurfaceLoadDataInfo, Loads::SurfaceLoadCombination >(), and LoadDatabase::getLoadCombination< Loads::VolumeLoadDataInfo, Loads::VolumeLoadCombination >().
{
  Assert(this->elem_ID  != FESystemNumbers::InvalidID, ExcInternalError());
  return this->elem_ID;
}
void Loads::ElemLoadDataInfo::setElemID (const unsigned int ID)
Definition at line 211 of file LoadDataInfo.C.
References FESystemNumbers::InvalidID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads().
{
  Assert(ID  != FESystemNumbers::InvalidID, ExcInternalError());
  Assert(this->elem_ID  == FESystemNumbers::InvalidID, ExcInternalError());
  this->elem_ID = ID;
}
Member Data Documentation
unsigned int Loads::ElemLoadDataInfo::elem_ID [protected]
Definition at line 105 of file LoadDataInfo.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadDataInfo.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/LoadDataInfo.C