fesystem: FESystemElem::FESystemElemTypeEnum Class Reference
FESystemElem::FESystemElemTypeEnum Class Reference
#include <FESystemElemTypeEnumHandler.h>
Classes
struct EnumRegistration
Public Member Functions
FESystemElemTypeEnum (unsigned int ID, const std::string &name, const ElemType type)
unsigned int enumID () const
const std::string & enumName () const
ElemType elemType () const
Static Public Member Functions
static const std::string & enumName (const unsigned int enum_id)
static unsigned int enumID (const std::string &name)
static ElemType elemType (const unsigned int ID)
returns whether the enumeration is only an isotropic quantity
static ElemType elemType (const std::string &name)
returns whether the enumeration is only an isotropic quantity
Protected Attributes
const unsigned int enum_id
enumeration ID of this object
const std::string enum_name
enumeration name of this object
const ElemType elem_type
whether this property is a pure isotropic quantity, in any dimensional space
Static Protected Attributes
static
FESystemElemNameEnumerationHandler enum_handler
this stores the enumeration constants for all derived classes
Detailed Description
this class provides a way to define property names anywhere in the code, and still be used by the PropertyCard to store values in a map. This is an abstract class, hence the property names will be derived from this class.
Definition at line 81 of file FESystemElemTypeEnumHandler.h.
Constructor & Destructor Documentation
FESystemElem::FESystemElemTypeEnum::FESystemElemTypeEnum (unsigned int ID, const std::string & name, const ElemType type) [inline]
constructor.
Parameters:
ID the enumeration ID of this class
name the enumeration name of this class
type ElemType from libmesh defining which geometric element this is based on
Definition at line 150 of file FESystemElemTypeEnumHandler.h.
                                                                             :
enum_id(ID),
enum_name(name),
elem_type(type)
{}
Member Function Documentation
ElemType FESystemElem::FESystemElemTypeEnum::elemType (const unsigned int ID) [inline, static]
returns whether the enumeration is only an isotropic quantity
Definition at line 181 of file FESystemElemTypeEnumHandler.h.
References enum_handler, and FESystemElem::FESystemElemNameEnumerationHandler::getElemType().
{return FESystemElem::FESystemElemTypeEnum::enum_handler.getElemType(ID);}
ElemType FESystemElem::FESystemElemTypeEnum::elemType (const std::string & name) [inline, static]
returns whether the enumeration is only an isotropic quantity
Definition at line 188 of file FESystemElemTypeEnumHandler.h.
References elemType(), and enumID().
{
  unsigned int ID = FESystemElem::FESystemElemTypeEnum::enumID(name);
  return FESystemElem::FESystemElemTypeEnum::elemType(ID);
}
ElemType FESystemElem::FESystemElemTypeEnum::elemType () const [inline]
Returns:
if the quantity is isotropic or not
Definition at line 215 of file FESystemElemTypeEnumHandler.h.
Referenced by elemType(), MeshDS::MeshList::readFromInputStream(), FESystemElem::FESystemElemBase::reinit(), and FESystemElem::FESystemElemBase::reinitForShapeSensitivity().
{return this->elem_type;}
unsigned int FESystemElem::FESystemElemTypeEnum::enumID (const std::string & name) [inline, static]
this provides a method to obtain the enum id of the enumeration when the string name is provided
Definition at line 173 of file FESystemElemTypeEnumHandler.h.
References enum_handler, and NameEnumerationHandler::getEnumerationID().
{return FESystemElem::FESystemElemTypeEnum::enum_handler.getEnumerationID(name);}
unsigned int FESystemElem::FESystemElemTypeEnum::enumID () const [inline]
Returns:
the enum id of this object
Definition at line 199 of file FESystemElemTypeEnumHandler.h.
Referenced by elemType(), and MeshDS::MeshList::readFromInputStream().
{return this->enum_id;}
const std::string & FESystemElem::FESystemElemTypeEnum::enumName (const unsigned int enum_id) [inline, static]
this provides a method to obtain the string name of the enumeration with the enum id is provided
Parameters:
enum_id integer ID of the enumeration
Definition at line 164 of file FESystemElemTypeEnumHandler.h.
References enum_handler, and NameEnumerationHandler::getEnumerationName().
{return FESystemElem::FESystemElemTypeEnum::enum_handler.getEnumerationName(enum_id);}
const std::string & FESystemElem::FESystemElemTypeEnum::enumName () const [inline]
Returns:
the enum name of this object
Definition at line 206 of file FESystemElemTypeEnumHandler.h.
Referenced by MeshDS::FEMeshData::getElemKindEnumName(), and FESystemElem::FESystemElemBase::getFESystemElemTypeEnumName().
{return this->enum_name;}
Member Data Documentation
const ElemType FESystemElem::FESystemElemTypeEnum::elem_type [protected]
whether this property is a pure isotropic quantity, in any dimensional space
Definition at line 126 of file FESystemElemTypeEnumHandler.h.
FESystemElem::FESystemElemNameEnumerationHandler FESystemElem::FESystemElemTypeEnum::enum_handler [static, protected]
this stores the enumeration constants for all derived classes
Definition at line 129 of file FESystemElemTypeEnumHandler.h.
Referenced by elemType(), enumID(), enumName(), and FESystemElem::FESystemElemTypeEnum::EnumRegistration< EnumClass >::EnumRegistration().
const unsigned int FESystemElem::FESystemElemTypeEnum::enum_id [protected]
enumeration ID of this object
Definition at line 120 of file FESystemElemTypeEnumHandler.h.
const std::string FESystemElem::FESystemElemTypeEnum::enum_name [protected]
enumeration name of this object
Definition at line 123 of file FESystemElemTypeEnumHandler.h.
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/FESystem/FESystemElemTypeEnumHandler.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/FESystem/FESystemStaticMemberDefinitions.C