fesystem: MaterialPropertyNameBase Class Reference
MaterialPropertyNameBase Class Reference
#include <MaterialPropertyNameEnums.h>
Classes
struct EnumRegistration
Public Member Functions
MaterialPropertyNameBase (unsigned int ID, const std::string &name, bool only_isotropic)
unsigned int enumID () const
const std::string & enumName () const
bool ifOnlyIsotropic () const
Static Public Member Functions
static const std::string & enumName (const unsigned int enum_id)
static unsigned int enumID (const std::string &name)
static bool ifOnlyIsotropic (const unsigned int ID)
returns whether the enumeration is only an isotropic quantity
static bool ifOnlyIsotropic (const std::string &name)
returns whether the enumeration is only an isotropic quantity
Protected Attributes
const unsigned int enum_id
enumeration ID of this object
const std::string enum_name
enumeration name of this object
const bool if_only_isotropic
whether this property is a pure isotropic quantity, in any dimensional space
Static Protected Attributes
static
MaterialPropertyNameEnumerationHandler enum_handler
this stores the enumeration constants for all derived classes
Detailed Description
this class provides a way to define property names anywhere in the code, and still be used by the PropertyCard to store values in a map. This is an abstract class, hence the property names will be derived from this class.
Definition at line 77 of file MaterialPropertyNameEnums.h.
Constructor & Destructor Documentation
MaterialPropertyNameBase::MaterialPropertyNameBase (unsigned int ID, const std::string & name, bool only_isotropic) [inline]
constructor.
Parameters:
ID the enumeration ID of this class
name the enumeration name of this class
Definition at line 144 of file MaterialPropertyNameEnums.h.
                                                                        :
enum_id(ID),
enum_name(name),
if_only_isotropic(isotropic)
{}
Member Function Documentation
unsigned int MaterialPropertyNameBase::enumID (const std::string & name) [inline, static]
this provides a method to obtain the enum id of the enumeration when the string name is provided
Definition at line 167 of file MaterialPropertyNameEnums.h.
References enum_handler, and NameEnumerationHandler::getEnumerationID().
{return MaterialPropertyNameBase::enum_handler.getEnumerationID(name);}
unsigned int MaterialPropertyNameBase::enumID () const [inline]
Returns:
the enum id of this object
Definition at line 193 of file MaterialPropertyNameEnums.h.
References enum_id.
Referenced by IsotropicMaterialPropertyCard::getPropertyEnumID(), and ifOnlyIsotropic().
{return this->enum_id;}
const std::string & MaterialPropertyNameBase::enumName (const unsigned int enum_id) [inline, static]
this provides a method to obtain the string name of the enumeration with the enum id is provided
Parameters:
enum_id integer ID of the enumeration
Definition at line 158 of file MaterialPropertyNameEnums.h.
References enum_handler, and NameEnumerationHandler::getEnumerationName().
{return MaterialPropertyNameBase::enum_handler.getEnumerationName(enum_id);}
const std::string & MaterialPropertyNameBase::enumName () const [inline]
Returns:
the enum name of this object
Definition at line 200 of file MaterialPropertyNameEnums.h.
References enum_name.
Referenced by IsotropicMaterialPropertyCard::getPropertyEnumName().
{return this->enum_name;}
bool MaterialPropertyNameBase::ifOnlyIsotropic (const unsigned int ID) [inline, static]
returns whether the enumeration is only an isotropic quantity
Definition at line 175 of file MaterialPropertyNameEnums.h.
References enum_handler, and MaterialPropertyNameEnumerationHandler::ifOnlyIsotropic().
{return MaterialPropertyNameBase::enum_handler.ifOnlyIsotropic(ID);}
bool MaterialPropertyNameBase::ifOnlyIsotropic (const std::string & name) [inline, static]
returns whether the enumeration is only an isotropic quantity
Definition at line 182 of file MaterialPropertyNameEnums.h.
References enum_handler, enumID(), and MaterialPropertyNameEnumerationHandler::ifOnlyIsotropic().
{
  unsigned int ID = MaterialPropertyNameBase::enumID(name);
  return MaterialPropertyNameBase::enum_handler.ifOnlyIsotropic(ID);
}
bool MaterialPropertyNameBase::ifOnlyIsotropic () const [inline]
Returns:
if the quantity is isotropic or not
Definition at line 208 of file MaterialPropertyNameEnums.h.
References if_only_isotropic.
{return this->if_only_isotropic;}
Member Data Documentation
MaterialPropertyNameEnumerationHandler MaterialPropertyNameBase::enum_handler [static, protected]
this stores the enumeration constants for all derived classes
Definition at line 124 of file MaterialPropertyNameEnums.h.
Referenced by enumID(), enumName(), MaterialPropertyNameBase::EnumRegistration< SPRING_CONSTANT >::EnumRegistration(), and ifOnlyIsotropic().
const unsigned int MaterialPropertyNameBase::enum_id [protected]
enumeration ID of this object
Definition at line 115 of file MaterialPropertyNameEnums.h.
Referenced by enumID().
const std::string MaterialPropertyNameBase::enum_name [protected]
enumeration name of this object
Definition at line 118 of file MaterialPropertyNameEnums.h.
Referenced by enumName().
const bool MaterialPropertyNameBase::if_only_isotropic [protected]
whether this property is a pure isotropic quantity, in any dimensional space
Definition at line 121 of file MaterialPropertyNameEnums.h.
Referenced by ifOnlyIsotropic().
The documentation for this class was generated from the following files:
/Users/manav/Documents/codes/FESystemOld/FESystem/src/Properties/MaterialPropertyNameEnums.h
/Users/manav/Documents/codes/FESystemOld/FESystem/src/FESystem/FESystemStaticMemberDefinitions.C