fesystem: /Users/manav/Documents/codes/FESystemOld/FESystem/src/Radiation/ShapeFactors/ff.h File Reference
ff.h File Reference
Defines
#define NO_FF_ERROR 0
#define INCONSISTENT_K 1
#define OUT_OF_RANGE_K 2
#define ALLCOEFF 21 /* length of c array */
Functions
float IDilogf (float z[2])
double IDilog (double z[2])
float Gf (float a, float b, float c, float t)
double G (double a, double b, double c, double t)
float Hf (float a, float b, float c, float t)
double H (double a, double b, double c, double t)
void Pairf (float(*c)[2], float p1[3], float p2[3], float q1[3], float q2[3])
void Pair (double(*c)[2], double p1[3], double p2[3], double q1[3], double q2[3])
float Areaf (float(*p)[3], int np)
double Area (double(*p)[3], int np)
int Bilinearf (float(*c)[2])
int Bilinear (double(*c)[2])
float IntegralPlanarf (float(*c)[2])
double IntegralPlanar (double(*c)[2])
int Lcisf (float xax[2], float yax[2], float rad[2], float cnt[2])
int Lcis (double xax[2], double yax[2], double rad[2], double cnt[2])
int LogSelectf (float rad[2], float cnt[2], float psi[2])
int LogSelect (double rad[2], double cnt[2], double psi[2])
float RMf (float z[2])
double RM (double z[2])
float IDilogPathf (int k, float rad[2], float cnt[2], float(*c)[2])
double IDilogPath (int k, double rad[2], double cnt[2], double(*c)[2])
float ILogPartf (int p1, float z[2], float(*c)[2])
double ILogPart (int p1, double z[2], double(*c)[2])
float ILogIntegralf (float(*c)[2], float s)
double ILogIntegral (double(*c)[2], double s)
float Integralf (float(*c)[2])
double Integral (double(*c)[2])
void FormFactorf (float(*p)[3], int np, float(*q)[3], int nq, float *factor12, float *factor21)
void FormFactor (double(*p)[3], int np, double(*q)[3], int nq, double *factor12, double *factor21)
Variables
int fferror
Define Documentation
#define ALLCOEFF 21 /* length of c array */
Definition at line 59 of file ff.h.
Referenced by FormFactor().
#define INCONSISTENT_K 1
Definition at line 52 of file ff.h.
#define NO_FF_ERROR 0
Definition at line 51 of file ff.h.
#define OUT_OF_RANGE_K 2
Definition at line 53 of file ff.h.
Function Documentation
double Area (double(*) p[3], int np)
Definition at line 285 of file ffp.c.
References add, cross, diff, HALF, and real.
Referenced by FormFactor().
{
  int i, ii;
  real d1[3], d2[3];
  real a[3];
  real c[3];
  a[0] = a[1] = a[2] = 0;
  for( i = 1, ii = 2; ii < np; i++, ii++ ){
    diff( d1, p[i], p[0] );
    diff( d2, p[ii], p[0] );
    cross( c, d1, d2 );
    add( a, a, c );
  }
  return sqrt( a[0] * a[0] + a[1] * a[1] + a[2] * a[2] ) * HALF;
}
float Areaf (float(*) p[3], int np)
int Bilinear (double(*) c[2])
Referenced by Integral().
int Bilinearf (float(*) c[2])
void FormFactor (double(*) p[3], int np, double(*) q[3], int nq, double * factor12, double * factor21)
Definition at line 888 of file ffp.c.
References ALLCOEFF, Area(), Integral(), M_PIF, mach, Pair(), real, and X.
{
  int i, j, ii, jj;
  real ff = 0;
  real c[ALLCOEFF][2];
  for( i = 0, ii = 1; i < np; i++, ii = ( i + 1 ) % np ){
    for( j = 0, jj = 1; j < nq; j++, jj = ( j + 1 ) % nq ){
      Pair( c, p[i], p[ii], q[j], q[jj] );
      if( fabs( c[1][X] ) > mach[2] ){
        ff -= c[1][X] * Integral( c );
      }
    }
  }
  /*  return ff / ( ( ( real )( M_PIF * 8 ) ) * Area( p, np ) );*/
  *factor12 = ff / ( ( ( real )( M_PIF * 8 ) ) * Area( p, np ) );
  *factor21 = ff / ( ( ( real )( M_PIF * 8 ) ) * Area( q, nq ) );
}
void FormFactorf (float(*) p[3], int np, float(*) q[3], int nq, float * factor12, float * factor21)
double G (double a, double b, double c, double t)
Definition at line 204 of file ffp.c.
References d, and real.
Referenced by Isotropic1D_ElemDataCard::getFactorSensitivityForGlobalParameter(), and Isotropic1D_ElemDataCard::getFactorSensitivityForLocalParameter().
{
  real qt = ( a * t + b ) * t + c;
  real qpt = 2 * a * t + b;
  real d = sqrt( 4 * a * c - b * b );
  return qpt / ( 2 * a ) * log( qt ) - 2 * t + d / a * atan( qpt / d );
}
float Gf (float a, float b, float c, float t)
double H (double a, double b, double c, double t)
Definition at line 214 of file ffp.c.
References d, and real.
{
  real at = a * t;
  real qt = ( at + b ) * t + c;
  real twoa = 2 * a;
  real qpt = twoa * t + b;
  real d = sqrt( 4 * a * c - b * b );
  return ( ( at * t + c ) * twoa - b * b ) / ( twoa * twoa ) * log( qt )
    - t * ( at - b ) / twoa - b * d / ( twoa * a ) * atan( qpt / d );
}
float Hf (float a, float b, float c, float t)
double IDilog (double z[2])
Definition at line 186 of file ffp.c.
References ATAN2, claussen(), HALF, hypot, real, X, and Y.
Referenced by IDilogPath().
{
  real r = hypot( z[X], z[Y] );
  real omega = 2 * ATAN2( z[Y], 1 - z[X] );
  real theta = 2 * ATAN2( z[Y], z[X] );
  real result = 0;
  if( r != 0 ){
    result = HALF * ( omega * log( r ) +
                     claussen( omega ) +
                     claussen( theta ) -
                     claussen( theta + omega ) );
  }
  return result;
}
float IDilogf (float z[2])
double IDilogPath (int k, double rad[2], double cnt[2], double(*) c[2])
Referenced by ILogPart().
float IDilogPathf (int k, float rad[2], float cnt[2], float(*) c[2])
double ILogIntegral (double(*) c[2], double s)
Referenced by Integral().
float ILogIntegralf (float(*) c[2], float s)
double ILogPart (int p1, double z[2], double(*) c[2])
Referenced by ILogIntegral().
float ILogPartf (int p1, float z[2], float(*) c[2])
double Integral (double(*) c[2])
Referenced by FormFactor().
float Integralf (float(*) c[2])
double IntegralPlanar (double(*) c[2])
Referenced by Integral().
float IntegralPlanarf (float(*) c[2])
int Lcis (double xax[2], double yax[2], double rad[2], double cnt[2])
Definition at line 372 of file ffp.c.
References cmagsqr, HUGE, real, X, XSOL, Y, and YSOL.
Referenced by IDilogPath(), and LogSelect().
{
  /*
   * see whether a circle at c with radius r
   * intersects the x or y axis
   */
  real cabs = cmagsqr( cnt );
  real rabs = cmagsqr( rad );
  real xdisc = cnt[X] * cnt[X] - cabs + rabs;
  real ydisc = cnt[Y] * cnt[Y] - cabs + rabs;
  int ret = 0;
  if( xdisc >= 0 ){
    xdisc = sqrt( xdisc );
    xax[0] = cnt[X] + xdisc;
    xax[1] = cnt[X] - xdisc;
    ret |= XSOL;
  }else{
    xax[0] = xax[1] = HUGE;
  }
  if( ydisc >= 0 ){
    ydisc = sqrt( ydisc );
    yax[0] = cnt[Y] + ydisc;
    yax[1] = cnt[Y] - ydisc;
    ret |= YSOL;
  }else{
    yax[0] = yax[1] = HUGE;
  }
  return ret;
}
int Lcisf (float xax[2], float yax[2], float rad[2], float cnt[2])
int LogSelect (double rad[2], double cnt[2], double psi[2])
Definition at line 427 of file ffp.c.
References Lcis(), real, seghitx, seghity, XSOL, and YSOL.
Referenced by ILogIntegral(), and ILogPart().
{
  real tmp; /* seghit() needs this one */
  real xax[2], yax[2];
  int sl;
  /*
   * get intersections, if any and return the index of the
   * particular extension of the logarithm to be used
   */
  /*
   * there is some debate whether the below should use
   * <= (>=) or < (>) depending on whether atan(0,0) is
   * considered a well defined point (it is not, but in
   * practice 0 is returned and that seems to work...)
   */
  sl = Lcis( xax, yax, rad, cnt );
  if( !( ( sl & XSOL ) &&
        ( ( ( xax[0] <= 0 ) && seghitx( xax[0], psi ) ) ||
         ( ( xax[1] <= 0 ) && seghitx( xax[1], psi ) ) ) ) ){
    return 0;
  }else if( !( ( sl & YSOL ) &&
              ( ( ( yax[0] <= 0 ) && seghity( yax[0], psi ) ) ||
               ( ( yax[1] <= 0 ) && seghity( yax[1], psi ) ) ) ) ){
    return 1;
  }else if( !( ( sl & YSOL ) &&
              ( ( ( yax[0] >= 0 ) && seghity( yax[0], psi ) ) ||
               ( ( yax[1] >= 0 ) && seghity( yax[1], psi ) ) ) ) ){
    return 3;
  }else if( !( ( sl & XSOL ) &&
              ( ( ( xax[0] >= 0 ) && seghitx( xax[0], psi ) ) ||
               ( ( xax[1] >= 0 ) && seghitx( xax[1], psi ) ) ) ) ){
    return 2;
  }else{
    assert( 0 );
    return 0;
  }
}
int LogSelectf (float rad[2], float cnt[2], float psi[2])
void Pair (double(*) c[2], double p1[3], double p2[3], double q1[3], double q2[3])
Referenced by FormFactor().
void Pairf (float(*) c[2], float p1[3], float p2[3], float q1[3], float q2[3])
double RM (double z[2])
Definition at line 470 of file ffp.c.
References cmagsqr, cmulx, ONEEIGHTTH, ONEQUARTER, ONETHIRTYSECOND, real, sqrx, sqry, X, and Y.
{
  real t2_1[2]; /* conj(t^2 - 1) */
  real t2_1_2[2]; /* conj(t^2 - 1)^2 */
  real t_1[2], tp1[2]; /* t-1, t+1 */
  real quot;
  t2_1[X] = sqrx( z ) - 1; t2_1[Y] = -sqry( z );
  t2_1_2[X] = sqrx( t2_1 ); t2_1_2[Y] = sqry( t2_1 );
  quot = 1 / cmagsqr( t2_1 );
  t_1[X] = z[X] - 1; t_1[Y] = z[Y];
  tp1[X] = z[X] + 1; tp1[Y] = z[Y];
  return ONEQUARTER * cmulx( z, t2_1_2 ) * quot * quot +
      ONEEIGHTTH * cmulx( z, t2_1 ) * quot +
        ONETHIRTYSECOND * log( cmagsqr( t_1 ) / cmagsqr( tp1 ) );
}
float RMf (float z[2])
Variable Documentation
int fferror
Definition at line 83 of file ffp.c.