fesystem: /Users/manav/Documents/codes/FESystemOld/FESystem/src/Loads/load.h File Reference
load.h File Reference
#include <iostream>
#include <set>
#include <vector>
#include <memory>
#include "Utilities/NameEnumHandler.h"
#include "FESystem/FESystemNumbers.h"
#include "FESystem/FESystemExceptions.h"
Classes
class LoadBase
class NodalLoad
class NodalPointLoad
class ElemLoad
class SurfaceLoad
class ScalarSurfaceLoad
class SurfaceConvectionLoad
class SurfaceRadiationLoad
class VolumeLoad
class ScalarVolumeLoad
class DirichletBoundaryCondition
Defines
#define NODAL_POINT_LOAD_ENUM_ID 1
#define NODAL_POINT_LOAD_ENUM_NAME "NODAL_POINT_LOAD"
#define DIRICHLET_BOUNDARY_CONDITION_ENUM_ID 2
#define DIRICHLET_BOUNDARY_CONDITION_ENUM_NAME "DIRICHLET_BOUNDARY_CONDITION"
#define SCALAR_VOLUME_LOAD_ENUM_ID 3
#define SCALAR_VOLUME_LOAD_ENUM_NAME "SCALAR_VOLUME_LOAD"
#define SURFACE_RADIATION_LOAD_ENUM_ID 4
#define SURFACE_RADIATION_LOAD_ENUM_NAME "SURFACE_RADIATION_LOAD"
#define SCALAR_SURFACE_LOAD_ENUM_ID 5
#define SCALAR_SURFACE_LOAD_ENUM_NAME "SCALAR_SURFACE_LOAD"
#define SURFACE_CONVECTION_LOAD_ENUM_ID 6
#define SURFACE_CONVECTION_LOAD_ENUM_NAME "SURFACE_CONVECTION_LOAD"
#define VECTOR_VOLUME_LOAD_ENUM_ID 7
#define VECTOR_VOLUME_LOAD_ENUM_NAME "VECTOR_VOLUME_LOAD"
Functions
DeclareEnumClass (LoadClassEnum)
DeclareEnumClass (LoadNameEnum)
DeclareEnumName (NODAL_POINT_LOAD, LoadClassEnum, 1,"NODAL_POINT_LOAD")
DeclareEnumName (DIRICHLET_BOUNDARY_CONDITION, LoadClassEnum, 2,"DIRICHLET_BOUNDARY_CONDITION")
DeclareEnumName (SCALAR_VOLUME_LOAD, LoadClassEnum, 3,"SCALAR_VOLUME_LOAD")
DeclareEnumName (VECTOR_VOLUME_LOAD, LoadClassEnum, 7,"VECTOR_VOLUME_LOAD")
DeclareEnumName (SURFACE_RADIATION_LOAD, LoadClassEnum, 4,"SURFACE_RADIATION_LOAD")
DeclareEnumName (SCALAR_SURFACE_LOAD, LoadClassEnum, 5,"SCALAR_SURFACE_LOAD")
DeclareEnumName (SURFACE_CONVECTION_LOAD, LoadClassEnum, 6,"SURFACE_CONVECTION_LOAD")
std::auto_ptr< SurfaceLoad > createSurfaceLoad (const unsigned int load_kind_enum_ID)
std::auto_ptr< NodalLoad > createNodalLoad (const unsigned int nodal_load_kind_enum_ID, const unsigned int dim)
std::auto_ptr< VolumeLoad > createVolumeLoad (const unsigned int volume_load_kind_enum_ID)
std::auto_ptr
< DirichletBoundaryCondition > createBoundaryConditionLoad (const unsigned int bc_load_kind_enum_ID)
unsigned int getLoadClassEnumIDForLoadName (unsigned int load_name_enum_ID)
Define Documentation
#define DIRICHLET_BOUNDARY_CONDITION_ENUM_ID 2
Definition at line 69 of file load.h.
Referenced by createBoundaryConditionLoad(), and Loads::createDirichletBoundaryConditionCombination().
#define DIRICHLET_BOUNDARY_CONDITION_ENUM_NAME "DIRICHLET_BOUNDARY_CONDITION"
Definition at line 75 of file load.h.
#define NODAL_POINT_LOAD_ENUM_ID 1
Definition at line 56 of file load.h.
Referenced by createNodalLoad(), and Loads::createNodalLoadCombination().
#define NODAL_POINT_LOAD_ENUM_NAME "NODAL_POINT_LOAD"
Definition at line 62 of file load.h.
#define SCALAR_SURFACE_LOAD_ENUM_ID 5
Definition at line 108 of file load.h.
Referenced by createSurfaceLoad(), and Loads::createSurfaceLoadCombination().
#define SCALAR_SURFACE_LOAD_ENUM_NAME "SCALAR_SURFACE_LOAD"
Definition at line 114 of file load.h.
#define SCALAR_VOLUME_LOAD_ENUM_ID 3
Definition at line 82 of file load.h.
Referenced by createVolumeLoad(), and Loads::createVolumeLoadCombination().
#define SCALAR_VOLUME_LOAD_ENUM_NAME "SCALAR_VOLUME_LOAD"
Definition at line 88 of file load.h.
#define SURFACE_CONVECTION_LOAD_ENUM_ID 6
Definition at line 122 of file load.h.
Referenced by createSurfaceLoad(), and Loads::createSurfaceLoadCombination().
#define SURFACE_CONVECTION_LOAD_ENUM_NAME "SURFACE_CONVECTION_LOAD"
Definition at line 128 of file load.h.
#define SURFACE_RADIATION_LOAD_ENUM_ID 4
Definition at line 95 of file load.h.
Referenced by createSurfaceLoad(), and Loads::createSurfaceLoadCombination().
#define SURFACE_RADIATION_LOAD_ENUM_NAME "SURFACE_RADIATION_LOAD"
Definition at line 101 of file load.h.
#define VECTOR_VOLUME_LOAD_ENUM_ID 7
Definition at line 135 of file load.h.
#define VECTOR_VOLUME_LOAD_ENUM_NAME "VECTOR_VOLUME_LOAD"
Definition at line 141 of file load.h.
Function Documentation
std::auto_ptr<DirichletBoundaryCondition> createBoundaryConditionLoad (const unsigned int bc_load_kind_enum_ID)
Definition at line 135 of file load.C.
References DIRICHLET_BOUNDARY_CONDITION_ENUM_ID.
Referenced by BoundaryConditionLoadSet::readFromInputStream().
{
  std::auto_ptr<DirichletBoundaryCondition> load;
  switch (bc_load_kind_enum_ID)
    {
    case DIRICHLET_BOUNDARY_CONDITION_ENUM_ID:
      load.reset(new DirichletBoundaryCondition);
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return load;
}
std::auto_ptr<NodalLoad> createNodalLoad (const unsigned int nodal_load_kind_enum_ID, const unsigned int dim)
Definition at line 89 of file load.C.
References NODAL_POINT_LOAD_ENUM_ID, and NodalPointLoad::setNDofs().
Referenced by NodalLoadSet::readFromInputStream().
{
  std::auto_ptr<NodalLoad> load;
  switch (nodal_load_kind_enum_ID)
    {
    case NODAL_POINT_LOAD_ENUM_ID:
      {
        NodalPointLoad *ptr = new NodalPointLoad;
        ptr->setNDofs(dim);
        load.reset(ptr);
      }
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return load;
}
std::auto_ptr<SurfaceLoad> createSurfaceLoad (const unsigned int load_kind_enum_ID)
Definition at line 62 of file load.C.
References SCALAR_SURFACE_LOAD_ENUM_ID, SURFACE_CONVECTION_LOAD_ENUM_ID, and SURFACE_RADIATION_LOAD_ENUM_ID.
Referenced by SurfaceLoadSet::readFromInputStream().
{
  std::auto_ptr<SurfaceLoad> load;
  switch (load_kind_enum_ID)
    {
    case SURFACE_RADIATION_LOAD_ENUM_ID:
      load.reset(new SurfaceRadiationLoad);
      break;
    case SCALAR_SURFACE_LOAD_ENUM_ID:
      load.reset(new ScalarSurfaceLoad);
      break;
    case SURFACE_CONVECTION_LOAD_ENUM_ID:
      load.reset(new SurfaceConvectionLoad);
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return load;
}
std::auto_ptr<VolumeLoad> createVolumeLoad (const unsigned int volume_load_kind_enum_ID)
Definition at line 114 of file load.C.
References SCALAR_VOLUME_LOAD_ENUM_ID.
Referenced by VolumeLoadSet::readFromInputStream().
{
  std::auto_ptr<VolumeLoad> load;
  switch (volume_load_kind_enum_ID)
    {
    case SCALAR_VOLUME_LOAD_ENUM_ID:
      load.reset(new ScalarVolumeLoad);
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return load;
}
DeclareEnumClass (LoadClassEnum)
DeclareEnumClass (LoadNameEnum)
DeclareEnumName (NODAL_POINT_LOAD , LoadClassEnum , 1 , "NODAL_POINT_LOAD")
DeclareEnumName (DIRICHLET_BOUNDARY_CONDITION , LoadClassEnum , 2 , "DIRICHLET_BOUNDARY_CONDITION")
DeclareEnumName (SCALAR_VOLUME_LOAD , LoadClassEnum , 3 , "SCALAR_VOLUME_LOAD")
DeclareEnumName (VECTOR_VOLUME_LOAD , LoadClassEnum , 7 , "VECTOR_VOLUME_LOAD")
DeclareEnumName (SURFACE_RADIATION_LOAD , LoadClassEnum , 4 , "SURFACE_RADIATION_LOAD")
DeclareEnumName (SCALAR_SURFACE_LOAD , LoadClassEnum , 5 , "SCALAR_SURFACE_LOAD")
DeclareEnumName (SURFACE_CONVECTION_LOAD , LoadClassEnum , 6 , "SURFACE_CONVECTION_LOAD")
unsigned int getLoadClassEnumIDForLoadName (unsigned int load_name_enum_ID)
Definition at line 15 of file load.C.
References DISPLACEMENT_BOUNDARY_CONDITION_ENUM_ID, FESystemNumbers::InvalidID, NODAL_FORCE_ENUM_ID, NODAL_HEAT_LOAD_ENUM_ID, NODAL_TEMPERATURE_ENUM_ID, PISTON_THEORY_SURFACE_ENUM_ID, SURFACE_CONVECTION_HEAT_LOAD_ENUM_ID, SURFACE_HEAT_LOAD_ENUM_ID, SURFACE_PRESSURE_ENUM_ID, SURFACE_RADIATION_HEAT_LOAD_ENUM_ID, TEMPERATURE_BOUNDARY_CONDITION_ENUM_ID, and VOLUME_HEAT_LOAD_ENUM_ID.
Referenced by VolumeLoadSet::readFromInputStream(), SurfaceLoadSet::readFromInputStream(), NodalLoadSet::readFromInputStream(), and BoundaryConditionLoadSet::readFromInputStream().
{
  unsigned int load_class_enum_ID = FESystemNumbers::InvalidID;
  switch (load_name_enum_ID)
    {
    case NODAL_FORCE_ENUM_ID:
    case NODAL_TEMPERATURE_ENUM_ID:
    case NODAL_HEAT_LOAD_ENUM_ID:
      load_class_enum_ID = NODAL_POINT_LOAD::num();
      break;
    case SURFACE_PRESSURE_ENUM_ID:
      load_class_enum_ID = SCALAR_SURFACE_LOAD::num();
      break;
    case DISPLACEMENT_BOUNDARY_CONDITION_ENUM_ID:
    case TEMPERATURE_BOUNDARY_CONDITION_ENUM_ID:
      load_class_enum_ID = DIRICHLET_BOUNDARY_CONDITION::num();
      break;
    case VOLUME_HEAT_LOAD_ENUM_ID:
      load_class_enum_ID = SCALAR_VOLUME_LOAD::num();
      break;
    case SURFACE_HEAT_LOAD_ENUM_ID:
      case PISTON_THEORY_SURFACE_ENUM_ID:
      load_class_enum_ID = SCALAR_SURFACE_LOAD::num();
      break;
    case SURFACE_RADIATION_HEAT_LOAD_ENUM_ID:
      load_class_enum_ID = SURFACE_RADIATION_LOAD::num();
      break;
    case SURFACE_CONVECTION_HEAT_LOAD_ENUM_ID:
      load_class_enum_ID = SURFACE_CONVECTION_LOAD::num();
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return load_class_enum_ID;
}