fesystem: Solver::NewmarkSolver Namespace Reference
Solver::NewmarkSolver Namespace Reference
Functions
void getResidual (NumericVector< double > &sol, NumericVector< double > &res, void *ctx)
function to be called by the nonlinear solver for the residual function
void getJacobian (NumericVector< double > &sol, SparseMatrix< double > &jac, void *ctx)
function to be called by the nonlinear solver for a jacobian matrix
template<typename NewmarkInfoType >
void initNewmarkConstants (const NewmarkInfoType &solver_info, std::vector< double > &constants_vector)
template<typename NewmarkInfoType >
void initNewmarkStiffnessMatrix (const NewmarkInfoType &solver_info, std::vector< double > &constants_vector, std::vector< SparseMatrix< double > * > &coeff_matrices, SparseMatrix< double > &newmark_stiff_matrix)
given all constants, this calculates the LHS matrix of the linear dynamic system
template<typename NewmarkInfoType >
void initNewmarkForceVector (const NewmarkInfoType &solver_info, std::vector< double > &constant_vector, std::vector< SparseMatrix< double > * > &coeff_matrices, std::vector< NumericVector< double > * > &state_vectors, NumericVector< double > &external_force_vec, NumericVector< double > &scratch_vec1, NumericVector< double > &scratch_vec2, NumericVector< double > &newmark_force_vec)
template<typename NewmarkInfoType >
void updateStateVectors (const NewmarkInfoType &solver_info, std::vector< double > &constant_vector, std::vector< NumericVector< double > * > &previous_state_vector, std::vector< NumericVector< double > * > &new_state_vector)
Function Documentation
void Solver::NewmarkSolver::getJacobian (NumericVector< double > & sol, SparseMatrix< double > & jac, void * ctx)
function to be called by the nonlinear solver for a jacobian matrix
Definition at line 544 of file NewmarkTransientSolver.C.
References Solver::FESystemSolverBase::analysis_driver, Solver::TransientSolverBase::coefficient_matrices, Solver::NewmarkNonlinearTransientSolver::current_state_vectors, Solver::NewmarkNonlinearTransientSolver::getCurrentTime(), FESystemUtility::AutoPtrVector< T >::getReference(), Solver::NewmarkNonlinearTransientSolverInfo::getSystemOrder(), Solver::NewmarkNonlinearTransientSolver::last_iter_state_vectors, Solver::NewmarkNonlinearTransientSolver::new_state_vectors, Solver::NewmarkNonlinearTransientSolver::newmark_constants, Solver::TransientSolverBase::transient_solver_info, and updateStateVectors().
Referenced by Solver::NewmarkNonlinearTransientSolver::solve().
{
  Solver::NewmarkNonlinearTransientSolver* solver =
  static_cast<Solver::NewmarkNonlinearTransientSolver*> (ctx);
  const Solver::NewmarkNonlinearTransientSolverInfo& newmark_info =
  dynamic_cast<const Solver::NewmarkNonlinearTransientSolverInfo&>(solver->transient_solver_info);
  unsigned int system_order = newmark_info.getSystemOrder();
  // copy the previous iteration solutions needef for calculation of new state vectors
  for (unsigned int i=0; i <= system_order; i++)
    {
      *(solver->current_state_vectors[i]) = *(solver->last_iter_state_vectors[i]);
      solver->current_state_vectors[i]->close();
    }
  // now copy the new approximation and calculate the residual
  sol.close();
  *(solver->new_state_vectors[0]) = *(solver->last_iter_state_vectors[0]);
  solver->new_state_vectors[0]->add(1.0, sol);
  solver->new_state_vectors[0]->close();
  // calculate the new derivatives
  Solver::NewmarkSolver::updateStateVectors
  (newmark_info,
   solver->newmark_constants,
   solver->current_state_vectors.getReference(),
   solver->new_state_vectors.getReference());
  dynamic_cast<Driver::NonlinearTransientAnalysisDriver*>(solver->analysis_driver)->
  getJacobianMatrix(solver->getCurrentTime(),
                    solver->current_state_vectors.getReference(),
                    jac);
  jac.close();
  // now, get the coefficient matrices to add to the jacobian
  std::vector<SparseMatrix<double>*> coeff_mats(system_order + 1);
  switch (system_order)
  {
    case 1:
    {
      // only the C1 matrix is needed
      coeff_mats[0] = NULL;
      coeff_mats[1] = solver->coefficient_matrices[1];
      dynamic_cast<Driver::NonlinearTransientAnalysisDriver*>(solver->analysis_driver)->
      getCoefficientMatrices(solver->getCurrentTime(),
                             solver->current_state_vectors.getReference(),
                             coeff_mats);
      coeff_mats[1]->close();
      jac.add(solver->newmark_constants[0], *(coeff_mats[1]));
      jac.close();
    }
      break;
    default:
      Assert(false, ExcInternalError());
  }
}
void Solver::NewmarkSolver::getResidual (NumericVector< double > & sol, NumericVector< double > & res, void * ctx)
function to be called by the nonlinear solver for the residual function
Definition at line 502 of file NewmarkTransientSolver.C.
References Solver::FESystemSolverBase::analysis_driver, Solver::NewmarkNonlinearTransientSolver::current_state_vectors, Solver::NewmarkNonlinearTransientSolver::getCurrentTime(), FESystemUtility::AutoPtrVector< T >::getReference(), Solver::NewmarkNonlinearTransientSolverInfo::getSystemOrder(), Solver::NewmarkNonlinearTransientSolver::last_iter_state_vectors, Solver::NewmarkNonlinearTransientSolver::new_state_vectors, Solver::NewmarkNonlinearTransientSolver::newmark_constants, Solver::TransientSolverBase::transient_solver_info, and updateStateVectors().
Referenced by Solver::NewmarkNonlinearTransientSolver::solve().
{
  Solver::NewmarkNonlinearTransientSolver* solver =
  static_cast<Solver::NewmarkNonlinearTransientSolver*> (ctx);
  const Solver::NewmarkNonlinearTransientSolverInfo& newmark_info =
  dynamic_cast<const Solver::NewmarkNonlinearTransientSolverInfo&>(solver->transient_solver_info);
  unsigned int system_order = newmark_info.getSystemOrder();
  // copy the previous iteration solutions needef for calculation of new state vectors
  for (unsigned int i=0; i <= system_order; i++)
    {
      *(solver->current_state_vectors[i]) = *(solver->last_iter_state_vectors[i]);
      solver->current_state_vectors[i]->close();
    }
  // now copy the new approximation and calculate the residual
  sol.close();
  *(solver->new_state_vectors[0]) = *(solver->last_iter_state_vectors[0]);
  solver->new_state_vectors[0]->add(1.0, sol);
  solver->new_state_vectors[0]->close();
  // calculate the new derivatives
  Solver::NewmarkSolver::updateStateVectors
  (newmark_info,
   solver->newmark_constants,
   solver->current_state_vectors.getReference(),
   solver->new_state_vectors.getReference());
  dynamic_cast<Driver::NonlinearTransientAnalysisDriver*>(solver->analysis_driver)->
  getResidualVector(solver->getCurrentTime(),
                    solver->current_state_vectors.getReference(),
                    res);
}
template<typename NewmarkInfoType > void Solver::NewmarkSolver::initNewmarkConstants (const NewmarkInfoType & solver_info, std::vector< double > & constants_vector)
this calculates the constants of the Newmark solver. The order of the solver and the input constants are obtained from the solver_info object.
Referenced by Solver::NewmarkLinearTransientSolver::solve(), and Solver::NewmarkNonlinearTransientSolver::solve().
template<typename NewmarkInfoType > void Solver::NewmarkSolver::initNewmarkForceVector (const NewmarkInfoType & solver_info, std::vector< double > & constant_vector, std::vector< SparseMatrix< double > * > & coeff_matrices, std::vector< NumericVector< double > * > & state_vectors, NumericVector< double > & external_force_vec, NumericVector< double > & scratch_vec1, NumericVector< double > & scratch_vec2, NumericVector< double > & newmark_force_vec)
given all other matrices and vectors, this calculated the RHS of the linear dynamic system
Referenced by Solver::NewmarkLinearTransientSolver::solve().
template<typename NewmarkInfoType > void Solver::NewmarkSolver::initNewmarkStiffnessMatrix (const NewmarkInfoType & solver_info, std::vector< double > & constants_vector, std::vector< SparseMatrix< double > * > & coeff_matrices, SparseMatrix< double > & newmark_stiff_matrix)
given all constants, this calculates the LHS matrix of the linear dynamic system
Referenced by Solver::NewmarkLinearTransientSolver::solve().
template<typename NewmarkInfoType > void Solver::NewmarkSolver::updateStateVectors (const NewmarkInfoType & solver_info, std::vector< double > & constant_vector, std::vector< NumericVector< double > * > & previous_state_vector, std::vector< NumericVector< double > * > & new_state_vector)
this initializes the state vector derivatives at the new iterate. This method is to be called after the new zeroth order vector has been calculated, so that all new derivtives can be calculated. The new zeroth order vector should be passed as the first element of the new_state_vector. When this function returns, the previous state vector will be updated with the new state vectors, and the new state vectors will all be zeroed
Referenced by getJacobian(), getResidual(), Solver::NewmarkLinearTransientSolver::solve(), and Solver::NewmarkNonlinearTransientSolver::solve().