fesystem: FESystemElem Namespace Reference
FESystemElem Namespace Reference
Classes
class FESystemElemBase
class FESystemElemNameEnumerationHandler
class FESystemElemTypeEnum
class FluidElem
class PistonTheoryElem
class Membrane
class PlateDKBatoz
class PlateVonKarman
class StructuralElem
class ThermalElem
Functions
DeclareEnumClass (FESystemElemQtyEnum)
DeclareEnumName (TRANSFORM_MATRIX, FESystemElemQtyEnum, 1,"TRANSFORM_MATRIX")
DeclareEnumName (N_N_FACTOR, FESystemElemQtyEnum, 2,"N_N_FACTOR")
DeclareEnumName (N_X_N_X_FACTOR, FESystemElemQtyEnum, 3,"N_X_N_X_FACTOR")
DeclareEnumName (N_Y_N_Y_FACTOR, FESystemElemQtyEnum, 4,"N_Y_N_Y_FACTOR")
DeclareEnumName (N_Z_N_Z_FACTOR, FESystemElemQtyEnum, 5,"N_Z_N_Z_FACTOR")
DeclareEnumName (N_X_N_Y_FACTOR, FESystemElemQtyEnum, 6,"N_X_N_Y_FACTOR")
DeclareEnumName (N_Y_N_Z_FACTOR, FESystemElemQtyEnum, 7,"N_Y_N_Z_FACTOR")
DeclareEnumName (N_Z_N_X_FACTOR, FESystemElemQtyEnum, 8,"N_Z_N_X_FACTOR")
DeclareEnumName (N_X_N_FACTOR, FESystemElemQtyEnum, 9,"N_X_N_FACTOR")
DeclareEnumName (N_Y_N_FACTOR, FESystemElemQtyEnum, 10,"N_Y_N_FACTOR")
DeclareEnumName (N_Z_N_FACTOR, FESystemElemQtyEnum, 11,"N_Z_N_FACTOR")
DeclareEnumName (N_FACTOR, FESystemElemQtyEnum, 12,"N_FACTOR")
DeclareEnumName (SURFACE_NORMAL, FESystemElemQtyEnum, 13,"SURFACE_NORMAL")
DeclareEnumClass (IntegrationDomainEnum)
DeclareEnumName (ELEM_VOLUME, IntegrationDomainEnum, 1,"ELEM_VOLUME")
DeclareEnumName (SIDE_ZERO, IntegrationDomainEnum, 2,"SIDE_ZERO")
DeclareEnumName (SIDE_ONE, IntegrationDomainEnum, 3,"SIDE_ONE")
DeclareEnumName (SIDE_TWO, IntegrationDomainEnum, 4,"SIDE_TWO")
DeclareEnumName (SIDE_THREE, IntegrationDomainEnum, 5,"SIDE_THREE")
DeclareEnumName (SIDE_FOUR, IntegrationDomainEnum, 6,"SIDE_FOUR")
DeclareEnumName (SIDE_FIVE, IntegrationDomainEnum, 7,"SIDE_FIVE")
DeclareEnumClass (DesignPointElemEnum)
DeclareEnumName (BASE_ELEM, DesignPointElemEnum, 1,"BASE_ELEM")
DeclareEnumName (BASE_PLUS_DELTA_ELEM, DesignPointElemEnum, 2,"BASE_PLUS_DELTA_ELEM")
std::auto_ptr
< FESystemElem::FESystemElemBase > createFESystemElem (const unsigned int elem_kind_enum_ID, Discipline::AnalysisDisciplineBase &discipline_base)
DeclareEnumClass (FluidElemQtyEnum)
DeclareEnumName (FLUID_INVISCID_JACOBIAN_MATRIX, FESystemElem::FluidElemQtyEnum, 1,"FLUID_INVISCID_JACOBIAN_MATRIX")
DeclareEnumName (FLUID_VISCOUS_JACOBIAN_MATRIX, FESystemElem::FluidElemQtyEnum, 2,"FLUID_VISCOUS_JACOBIAN_MATRIX")
DeclareEnumName (FLUID_F_VECTOR, FESystemElem::FluidElemQtyEnum, 3,"FLUID_F_VECTOR")
DeclareEnumClass (PistonTheoryElemQtyEnum)
DeclareEnumName (PISTON_THEORY_K_MATRIX, FESystemElem::PistonTheoryElemQtyEnum, 1,"PISTON_THEORY_K_MATRIX")
DeclareEnumName (PISTON_THEORY_C1_MATRIX, FESystemElem::PistonTheoryElemQtyEnum, 2,"PISTON_THEORY_C2_MATRIX")
DeclareEnumClass (PlateDKBatozQtyEnum)
DeclareEnumName (PLATE_DK_BATOZ_HX_HX_FACTOR, PlateDKBatozQtyEnum, 1,"PLATE_DK_BATOZ_HX_HX_FACTOR")
DeclareEnumName (PLATE_DK_BATOZ_HY_HY_FACTOR, PlateDKBatozQtyEnum, 2,"PLATE_DK_BATOZ_HY_HY_FACTOR")
DeclareEnumName (PLATE_DK_BATOZ_HXX_HXX_FACTOR, PlateDKBatozQtyEnum, 3,"PLATE_DK_BATOZ_HXX_HXX_FACTOR")
DeclareEnumName (PLATE_DK_BATOZ_HYY_HYY_FACTOR, PlateDKBatozQtyEnum, 4,"PLATE_DK_BATOZ_HYY_HYY_FACTOR")
DeclareEnumName (PLATE_DK_BATOZ_HXX_HYY_FACTOR, PlateDKBatozQtyEnum, 5,"PLATE_DK_BATOZ_HXX_HYY_FACTOR")
DeclareEnumName (PLATE_DK_BATOZ_HXY_HXY_FACTOR, PlateDKBatozQtyEnum, 6,"PLATE_DK_BATOZ_HXY_HXY_FACTOR")
DeclareEnumName (PLATE_DK_BATOZ_HYX_HXY_FACTOR, PlateDKBatozQtyEnum, 7,"PLATE_DK_BATOZ_HYX_HXY_FACTOR")
DeclareEnumName (PLATE_DK_BATOZ_HYX_HYX_FACTOR, PlateDKBatozQtyEnum, 8,"PLATE_DK_BATOZ_HYX_HYX_FACTOR")
template<class QtyType >
void getPlateDKBatozQty (FESystemElem::FESystemElemBase *elem, const unsigned int name, QtyType *qty, const unsigned int design_point_enum_ID, const unsigned int domain, const bool sensitivity)
DeclareEnumClass (PlateVonKarmanQtyEnum)
DeclareEnumName (PLATE_VON_KARMAN_NONLINEAR_STIFFNESS_COMPONENT, PlateVonKarmanQtyEnum, 1,"PLATE_VON_KARMAN_NONLINEAR_STIFFNESS_COMPONENT")
DeclareEnumClass (StructuralElemQtyEnum)
DeclareEnumName (STRUCTURAL_M_MATRIX, FESystemElem::StructuralElemQtyEnum, 1,"STRUCTURAL_M_MATRIX")
DeclareEnumName (STRUCTURAL_C_MATRIX, FESystemElem::StructuralElemQtyEnum, 2,"STRUCTURAL_C_MATRIX")
DeclareEnumName (STRUCTURAL_K_MATRIX, FESystemElem::StructuralElemQtyEnum, 3,"STRUCTURAL_K_MATRIX")
DeclareEnumName (STRUCTURAL_K_G_MATRIX, FESystemElem::StructuralElemQtyEnum, 7,"STRUCTURAL_K_G_MATRIX")
DeclareEnumName (STRUCTURAL_F_T_VECTOR, FESystemElem::StructuralElemQtyEnum, 4,"STRUCTURAL_F_T_VECTOR")
DeclareEnumName (STRUCTURAL_F_PRESSURE_VECTOR, FESystemElem::StructuralElemQtyEnum, 5,"STRUCTURAL_F_PRESSURE_VECTOR")
DeclareEnumName (STRUCTURAL_STRAIN_OPERATOR, FESystemElem::StructuralElemQtyEnum, 6,"STRUCTURAL_STRAIN_OPERATOR")
DeclareEnumClass (ThermalElemQtyEnum)
DeclareEnumName (THERMAL_C_MATRIX, FESystemElem::ThermalElemQtyEnum, 1,"THERMAL_C_MATRIX")
DeclareEnumName (THERMAL_K_C_MATRIX, FESystemElem::ThermalElemQtyEnum, 2,"THERMAL_K_C_MATRIX")
DeclareEnumName (THERMAL_K_H_MATRIX, FESystemElem::ThermalElemQtyEnum, 3,"THERMAL_K_H_MATRIX")
DeclareEnumName (THERMAL_F_H_VECTOR, FESystemElem::ThermalElemQtyEnum, 4,"THERMAL_F_H_VECTOR")
DeclareEnumName (THERMAL_F_VOL_VECTOR, FESystemElem::ThermalElemQtyEnum, 5,"THERMAL_F_VOL_VECTOR")
DeclareEnumName (THERMAL_F_Q_SURF_VECTOR, FESystemElem::ThermalElemQtyEnum, 6,"THERMAL_F_Q_SURF_VECTOR")
DeclareEnumName (THERMAL_F_EMITTED_RAD_VECTOR, FESystemElem::ThermalElemQtyEnum, 7,"THERMAL_F_EMITTED_RAD_VECTOR")
DeclareEnumName (THERMAL_EMITTED_RAD_JAC_MATRIX, FESystemElem::ThermalElemQtyEnum, 8,"THERMAL_EMITTED_RAD_JAC_MATRIX")
DeclareEnumName (THERMAL_F_SIGMA_FACTOR, FESystemElem::ThermalElemQtyEnum, 9,"THERMAL_F_SIGMA_FACTOR")
DeclareEnumName (THERMAL_K_C_JAC_MATRIX, FESystemElem::ThermalElemQtyEnum, 10,"THERMAL_K_C_JAC_MATRIX")
DeclareEnumName (THERMAL_C_JAC_MATRIX, FESystemElem::ThermalElemQtyEnum, 11,"THERMAL_C_JAC_MATRIX")
Detailed Description
a base class for defining the structural elements
Function Documentation
std::auto_ptr< FESystemElem::FESystemElemBase > FESystemElem::createFESystemElem (const unsigned int elem_kind_enum_ID, Discipline::AnalysisDisciplineBase & discipline_base)
Definition at line 1904 of file FESystemElem.C.
References Discipline::AnalysisDisciplineBase::getDisciplineEnumID(), PISTON_THEORY_ENUM_ID, STRUCTURAL_BAR_EDGE2_ENUM_ID, STRUCTURAL_BEAM_EDGE2_ENUM_ID, STRUCTURAL_DISCIPLINE_ENUM_ID, STRUCTURAL_LINEAR_SPRING_EDGE2_ENUM_ID, STRUCTURAL_MEMBRANE_QUAD4_ENUM_ID, STRUCTURAL_MEMBRANE_TRI3_ENUM_ID, STRUCTURAL_PLATE_DKT_ENUM_ID, STRUCTURAL_PLATE_MITC4_QUAD4_ENUM_ID, STRUCTURAL_TRI3_VON_KARMAN_ENUM_ID, THERMAL_CONDUCTION_EDGE2_ENUM_ID, THERMAL_CONDUCTION_HEX8_ENUM_ID, THERMAL_CONDUCTION_PRISM6_ENUM_ID, THERMAL_CONDUCTION_QUAD4_ENUM_ID, THERMAL_CONDUCTION_TRI3_ENUM_ID, THERMAL_DISCIPLINE_ENUM_ID, and THERMAL_FORCED_CONVECTION_EDGE2_ENUM_ID.
Referenced by Discipline::AnalysisDisciplineBase::getFESystemElem().
{
  std::auto_ptr<FESystemElem::FESystemElemBase> elem(NULL);
  switch (discipline_base.getDisciplineEnumID())
  {
    case PISTON_THEORY_ENUM_ID:
      switch (elem_kind_enum_ID)
    {
      case STRUCTURAL_PLATE_DKT_ENUM_ID:
      case STRUCTURAL_TRI3_VON_KARMAN_ENUM_ID:
      {
        elem.reset(new FESystemElem::PistonTheoryTri3(discipline_base));
        return elem;
      }
        break;
    }
    case STRUCTURAL_DISCIPLINE_ENUM_ID:
      switch (elem_kind_enum_ID)
    {
      case STRUCTURAL_BAR_EDGE2_ENUM_ID:
        elem.reset(new FESystemElem::Bar(discipline_base));
        break;
      case STRUCTURAL_BEAM_EDGE2_ENUM_ID:
        elem.reset(new FESystemElem::Beam2(discipline_base));
        break;
      case STRUCTURAL_LINEAR_SPRING_EDGE2_ENUM_ID:
        elem.reset(new FESystemElem::LinearSpring(discipline_base));
        break;
      case STRUCTURAL_MEMBRANE_QUAD4_ENUM_ID:
        elem.reset(new FESystemElem::MembraneQuad4(discipline_base));
        break;
      case STRUCTURAL_MEMBRANE_TRI3_ENUM_ID:
        elem.reset(new FESystemElem::MembraneTri3(discipline_base));
        break;
      case STRUCTURAL_PLATE_MITC4_QUAD4_ENUM_ID:
        elem.reset(new FESystemElem::PlateMITC4(discipline_base));
        break;
      case STRUCTURAL_PLATE_DKT_ENUM_ID:
        elem.reset(new FESystemElem::PlateDKT(discipline_base));
        break;
      case STRUCTURAL_TRI3_VON_KARMAN_ENUM_ID:
        elem.reset(new FESystemElem::Tri3VonKarman(discipline_base));
        break;
      default:
        Assert(false, ExcInternalError());
        break;
    }
      break;
    case THERMAL_DISCIPLINE_ENUM_ID:
      switch (elem_kind_enum_ID)
    {
      case THERMAL_CONDUCTION_EDGE2_ENUM_ID:
        elem.reset(new FESystemElem::Conduction_1D(discipline_base));
        break;
      case THERMAL_CONDUCTION_HEX8_ENUM_ID:
        elem.reset(new FESystemElem::Conduction_Hex8(discipline_base));
        break;
      case THERMAL_CONDUCTION_PRISM6_ENUM_ID:
        elem.reset(new FESystemElem::Conduction_Prism6(discipline_base));
        break;
      case THERMAL_CONDUCTION_QUAD4_ENUM_ID:
        elem.reset(new FESystemElem::Conduction_Quad4(discipline_base));
        break;
      case THERMAL_CONDUCTION_TRI3_ENUM_ID:
        elem.reset(new FESystemElem::Conduction_Tri3(discipline_base));
        break;
      case THERMAL_FORCED_CONVECTION_EDGE2_ENUM_ID:
        elem.reset(new FESystemElem::ForcedConvection_1D(discipline_base));
        break;
      default:
        Assert(false, ExcInternalError());
        break;
    }
      break;
    default:
      Assert(false, ExcInternalError());
  }
  return elem;
}
FESystemElem::DeclareEnumClass (PlateVonKarmanQtyEnum)
FESystemElem::DeclareEnumClass (PistonTheoryElemQtyEnum)
FESystemElem::DeclareEnumClass (FluidElemQtyEnum)
FESystemElem::DeclareEnumClass (PlateDKBatozQtyEnum)
FESystemElem::DeclareEnumClass (StructuralElemQtyEnum)
FESystemElem::DeclareEnumClass (ThermalElemQtyEnum)
FESystemElem::DeclareEnumClass (FESystemElemQtyEnum)
this defines the quantity named pertinent to this class. This class provides methods to calculate these methods.
Referenced by DeclareFESystemElemTypeEnumName().
FESystemElem::DeclareEnumClass (IntegrationDomainEnum)
FESystemElem::DeclareEnumClass (DesignPointElemEnum)
FESystemElem::DeclareEnumName (PLATE_VON_KARMAN_NONLINEAR_STIFFNESS_COMPONENT , PlateVonKarmanQtyEnum , 1 , "PLATE_VON_KARMAN_NONLINEAR_STIFFNESS_COMPONENT")
FESystemElem::DeclareEnumName (PISTON_THEORY_K_MATRIX , FESystemElem::PistonTheoryElemQtyEnum , 1 , "PISTON_THEORY_K_MATRIX")
FESystemElem::DeclareEnumName (FLUID_INVISCID_JACOBIAN_MATRIX , FESystemElem::FluidElemQtyEnum , 1 , "FLUID_INVISCID_JACOBIAN_MATRIX")
FESystemElem::DeclareEnumName (PISTON_THEORY_C1_MATRIX , FESystemElem::PistonTheoryElemQtyEnum , 2 , "PISTON_THEORY_C2_MATRIX")
FESystemElem::DeclareEnumName (FLUID_VISCOUS_JACOBIAN_MATRIX , FESystemElem::FluidElemQtyEnum , 2 , "FLUID_VISCOUS_JACOBIAN_MATRIX")
FESystemElem::DeclareEnumName (FLUID_F_VECTOR , FESystemElem::FluidElemQtyEnum , 3 , "FLUID_F_VECTOR")
FESystemElem::DeclareEnumName (PLATE_DK_BATOZ_HX_HX_FACTOR , PlateDKBatozQtyEnum , 1 , "PLATE_DK_BATOZ_HX_HX_FACTOR")
FESystemElem::DeclareEnumName (STRUCTURAL_M_MATRIX , FESystemElem::StructuralElemQtyEnum , 1 , "STRUCTURAL_M_MATRIX")
FESystemElem::DeclareEnumName (PLATE_DK_BATOZ_HY_HY_FACTOR , PlateDKBatozQtyEnum , 2 , "PLATE_DK_BATOZ_HY_HY_FACTOR")
FESystemElem::DeclareEnumName (STRUCTURAL_C_MATRIX , FESystemElem::StructuralElemQtyEnum , 2 , "STRUCTURAL_C_MATRIX")
FESystemElem::DeclareEnumName (PLATE_DK_BATOZ_HXX_HXX_FACTOR , PlateDKBatozQtyEnum , 3 , "PLATE_DK_BATOZ_HXX_HXX_FACTOR")
FESystemElem::DeclareEnumName (STRUCTURAL_K_MATRIX , FESystemElem::StructuralElemQtyEnum , 3 , "STRUCTURAL_K_MATRIX")
FESystemElem::DeclareEnumName (PLATE_DK_BATOZ_HYY_HYY_FACTOR , PlateDKBatozQtyEnum , 4 , "PLATE_DK_BATOZ_HYY_HYY_FACTOR")
FESystemElem::DeclareEnumName (STRUCTURAL_K_G_MATRIX , FESystemElem::StructuralElemQtyEnum , 7 , "STRUCTURAL_K_G_MATRIX")
FESystemElem::DeclareEnumName (STRUCTURAL_F_T_VECTOR , FESystemElem::StructuralElemQtyEnum , 4 , "STRUCTURAL_F_T_VECTOR")
FESystemElem::DeclareEnumName (PLATE_DK_BATOZ_HXX_HYY_FACTOR , PlateDKBatozQtyEnum , 5 , "PLATE_DK_BATOZ_HXX_HYY_FACTOR")
FESystemElem::DeclareEnumName (STRUCTURAL_F_PRESSURE_VECTOR , FESystemElem::StructuralElemQtyEnum , 5 , "STRUCTURAL_F_PRESSURE_VECTOR")
FESystemElem::DeclareEnumName (PLATE_DK_BATOZ_HXY_HXY_FACTOR , PlateDKBatozQtyEnum , 6 , "PLATE_DK_BATOZ_HXY_HXY_FACTOR")
FESystemElem::DeclareEnumName (STRUCTURAL_STRAIN_OPERATOR , FESystemElem::StructuralElemQtyEnum , 6 , "STRUCTURAL_STRAIN_OPERATOR")
FESystemElem::DeclareEnumName (PLATE_DK_BATOZ_HYX_HXY_FACTOR , PlateDKBatozQtyEnum , 7 , "PLATE_DK_BATOZ_HYX_HXY_FACTOR")
FESystemElem::DeclareEnumName (PLATE_DK_BATOZ_HYX_HYX_FACTOR , PlateDKBatozQtyEnum , 8 , "PLATE_DK_BATOZ_HYX_HYX_FACTOR")
FESystemElem::DeclareEnumName (THERMAL_C_MATRIX , FESystemElem::ThermalElemQtyEnum , 1 , "THERMAL_C_MATRIX")
FESystemElem::DeclareEnumName (THERMAL_K_C_MATRIX , FESystemElem::ThermalElemQtyEnum , 2 , "THERMAL_K_C_MATRIX")
FESystemElem::DeclareEnumName (THERMAL_K_H_MATRIX , FESystemElem::ThermalElemQtyEnum , 3 , "THERMAL_K_H_MATRIX")
FESystemElem::DeclareEnumName (THERMAL_F_H_VECTOR , FESystemElem::ThermalElemQtyEnum , 4 , "THERMAL_F_H_VECTOR")
FESystemElem::DeclareEnumName (THERMAL_F_VOL_VECTOR , FESystemElem::ThermalElemQtyEnum , 5 , "THERMAL_F_VOL_VECTOR")
FESystemElem::DeclareEnumName (THERMAL_F_Q_SURF_VECTOR , FESystemElem::ThermalElemQtyEnum , 6 , "THERMAL_F_Q_SURF_VECTOR")
FESystemElem::DeclareEnumName (THERMAL_F_EMITTED_RAD_VECTOR , FESystemElem::ThermalElemQtyEnum , 7 , "THERMAL_F_EMITTED_RAD_VECTOR")
FESystemElem::DeclareEnumName (THERMAL_EMITTED_RAD_JAC_MATRIX , FESystemElem::ThermalElemQtyEnum , 8 , "THERMAL_EMITTED_RAD_JAC_MATRIX")
FESystemElem::DeclareEnumName (THERMAL_F_SIGMA_FACTOR , FESystemElem::ThermalElemQtyEnum , 9 , "THERMAL_F_SIGMA_FACTOR")
FESystemElem::DeclareEnumName (THERMAL_K_C_JAC_MATRIX , FESystemElem::ThermalElemQtyEnum , 10 , "THERMAL_K_C_JAC_MATRIX")
FESystemElem::DeclareEnumName (THERMAL_C_JAC_MATRIX , FESystemElem::ThermalElemQtyEnum , 11 , "THERMAL_C_JAC_MATRIX")
FESystemElem::DeclareEnumName (TRANSFORM_MATRIX , FESystemElemQtyEnum , 1 , "TRANSFORM_MATRIX")
Referenced by DeclareFESystemElemTypeEnumName().
FESystemElem::DeclareEnumName (N_N_FACTOR , FESystemElemQtyEnum , 2 , "N_N_FACTOR")
FESystemElem::DeclareEnumName (N_X_N_X_FACTOR , FESystemElemQtyEnum , 3 , "N_X_N_X_FACTOR")
FESystemElem::DeclareEnumName (N_Y_N_Y_FACTOR , FESystemElemQtyEnum , 4 , "N_Y_N_Y_FACTOR")
FESystemElem::DeclareEnumName (N_Z_N_Z_FACTOR , FESystemElemQtyEnum , 5 , "N_Z_N_Z_FACTOR")
FESystemElem::DeclareEnumName (N_X_N_Y_FACTOR , FESystemElemQtyEnum , 6 , "N_X_N_Y_FACTOR")
FESystemElem::DeclareEnumName (N_Y_N_Z_FACTOR , FESystemElemQtyEnum , 7 , "N_Y_N_Z_FACTOR")
FESystemElem::DeclareEnumName (N_Z_N_X_FACTOR , FESystemElemQtyEnum , 8 , "N_Z_N_X_FACTOR")
FESystemElem::DeclareEnumName (N_X_N_FACTOR , FESystemElemQtyEnum , 9 , "N_X_N_FACTOR")
FESystemElem::DeclareEnumName (N_Y_N_FACTOR , FESystemElemQtyEnum , 10 , "N_Y_N_FACTOR")
FESystemElem::DeclareEnumName (N_Z_N_FACTOR , FESystemElemQtyEnum , 11 , "N_Z_N_FACTOR")
FESystemElem::DeclareEnumName (N_FACTOR , FESystemElemQtyEnum , 12 , "N_FACTOR")
FESystemElem::DeclareEnumName (SURFACE_NORMAL , FESystemElemQtyEnum , 13 , "SURFACE_NORMAL")
FESystemElem::DeclareEnumName (ELEM_VOLUME , IntegrationDomainEnum , 1 , "ELEM_VOLUME")
FESystemElem::DeclareEnumName (SIDE_ZERO , IntegrationDomainEnum , 2 , "SIDE_ZERO")
FESystemElem::DeclareEnumName (SIDE_ONE , IntegrationDomainEnum , 3 , "SIDE_ONE")
FESystemElem::DeclareEnumName (SIDE_TWO , IntegrationDomainEnum , 4 , "SIDE_TWO")
FESystemElem::DeclareEnumName (SIDE_THREE , IntegrationDomainEnum , 5 , "SIDE_THREE")
FESystemElem::DeclareEnumName (SIDE_FOUR , IntegrationDomainEnum , 6 , "SIDE_FOUR")
FESystemElem::DeclareEnumName (SIDE_FIVE , IntegrationDomainEnum , 7 , "SIDE_FIVE")
FESystemElem::DeclareEnumName (BASE_ELEM , DesignPointElemEnum , 1 , "BASE_ELEM")
FESystemElem::DeclareEnumName (BASE_PLUS_DELTA_ELEM , DesignPointElemEnum , 2 , "BASE_PLUS_DELTA_ELEM")
template<class QtyType > void FESystemElem::getPlateDKBatozQty (FESystemElem::FESystemElemBase * elem, const unsigned int name, QtyType * qty, const unsigned int design_point_enum_ID, const unsigned int domain, const bool sensitivity)
this method returns the quantity specified in the arguement list. This has been templatized so that the template can be used in derived element types. This element class will provide its element quantity and calculation routines.
Parameters:
name name of the quantity to be returned
qty data structure in which the quantity will be removed
side_num number of the side if this is a side quantity
Definition at line 235 of file PlateDKBatoz.h.
References FESystemElem::FESystemElemBase::getFESystemElemQty(), FESystemElem::FESystemElemBase::getFESystemElemQtyShapeSensitivity(), FESystemElem::FESystemElemBase::getNNodes(), PLATE_DK_BATOZ_HX_HX_FACTOR_ENUM_ID, PLATE_DK_BATOZ_HXX_HXX_FACTOR_ENUM_ID, PLATE_DK_BATOZ_HXX_HYY_FACTOR_ENUM_ID, PLATE_DK_BATOZ_HXY_HXY_FACTOR_ENUM_ID, PLATE_DK_BATOZ_HY_HY_FACTOR_ENUM_ID, PLATE_DK_BATOZ_HYX_HXY_FACTOR_ENUM_ID, PLATE_DK_BATOZ_HYX_HYX_FACTOR_ENUM_ID, and PLATE_DK_BATOZ_HYY_HYY_FACTOR_ENUM_ID.
Referenced by FESystemElem::PlateVonKarman::calculate_K(), and FESystemElem::PlateDKBatoz::calculate_K().
{
  assert (qty != NULL);
  // the quantity here is extracted from the shape function factors obtained
  // from the base class FESystemElemBase. A static matrix is declared for that
  static unsigned int n_nodes;
  n_nodes = elem->getNNodes();
  static DenseMatrix<double> matrix(n_nodes * 6, n_nodes * 6);
  if (qty->m() != (n_nodes * 3) || qty->n() != (n_nodes * 3))
    qty->resize(n_nodes * 3, n_nodes * 3);
  matrix.zero();
  qty->zero();
  // first get the factors from the FESystemElemBase
  // row and column store the information of where the block containing the
  // desired quantitiy start in the shape factor matrix.
  static unsigned int row, column;
  switch (sensitivity)
    {
    case false:
      {
        switch(name)
          {
          case PLATE_DK_BATOZ_HX_HX_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQty(FESystemElem::N_N_FACTOR::num(), &matrix,
                                       design_point_enum_ID,
                                       domain, BATOZ);
              row = 0;
              column = 0;
            }
            break;
          case PLATE_DK_BATOZ_HY_HY_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQty(FESystemElem::N_N_FACTOR::num(), &matrix,
                                       design_point_enum_ID,
                                       domain, BATOZ);
              row = n_nodes * 3;
              column = n_nodes * 3;
            }
            break;
          case PLATE_DK_BATOZ_HXX_HXX_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQty(FESystemElem::N_X_N_X_FACTOR::num(), &matrix,
                                       design_point_enum_ID,
                                       domain, BATOZ);
              row = 0;
              column = 0;
            }
            break;
          case PLATE_DK_BATOZ_HYX_HYX_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQty(FESystemElem::N_X_N_X_FACTOR::num(), &matrix,
                                       design_point_enum_ID,
                                       domain, BATOZ);
              row = n_nodes * 3;
              column = n_nodes * 3;
            }
            break;
          case PLATE_DK_BATOZ_HYY_HYY_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQty(FESystemElem::N_Y_N_Y_FACTOR::num(), &matrix,
                                       design_point_enum_ID,
                                       domain, BATOZ);
              row = n_nodes * 3;
              column = n_nodes * 3;
            }
            break;
          case PLATE_DK_BATOZ_HXY_HXY_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQty(FESystemElem::N_Y_N_Y_FACTOR::num(), &matrix,
                                       design_point_enum_ID,
                                       domain, BATOZ);
              row = 0;
              column = 0;
            }
            break;
          case PLATE_DK_BATOZ_HXX_HYY_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQty(FESystemElem::N_X_N_Y_FACTOR::num(), &matrix,
                                       design_point_enum_ID,
                                       domain, BATOZ);
              row = 0;
              column = n_nodes * 3;
            }
            break;
          case PLATE_DK_BATOZ_HYX_HXY_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQty(FESystemElem::N_X_N_Y_FACTOR::num(), &matrix,
                                       design_point_enum_ID,
                                       domain, BATOZ);
              row = n_nodes * 3;
              column = 0;
            }
            break;
          default:
            Assert(false, FESystemExceptions::ExcEnumCaseNotImplemented
                   (FESystemElem::PlateDKBatozQtyEnum::enumName(name)));
          }
      }
      break;
    case true:
    default:
      {
        switch(name)
          {
          case PLATE_DK_BATOZ_HX_HX_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQtyShapeSensitivity(FESystemElem::N_N_FACTOR::num(),
                                                       &matrix, domain, BATOZ);
              row = 0;
              column = 0;
            }
            break;
          case PLATE_DK_BATOZ_HY_HY_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQtyShapeSensitivity(FESystemElem::N_N_FACTOR::num(),
                                                       &matrix, domain, BATOZ);
              row = n_nodes * 3;
              column = n_nodes * 3;
            }
            break;
          case PLATE_DK_BATOZ_HXX_HXX_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQtyShapeSensitivity(FESystemElem::N_X_N_X_FACTOR::num(),
                                                       &matrix, domain, BATOZ);
              row = 0;
              column = 0;
            }
            break;
          case PLATE_DK_BATOZ_HYX_HYX_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQtyShapeSensitivity(FESystemElem::N_X_N_X_FACTOR::num(),
                                                       &matrix, domain, BATOZ);
              row = n_nodes * 3;
              column = n_nodes * 3;
            }
            break;
          case PLATE_DK_BATOZ_HYY_HYY_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQtyShapeSensitivity(FESystemElem::N_Y_N_Y_FACTOR::num(),
                                                       &matrix, domain, BATOZ);
              row = n_nodes * 3;
              column = n_nodes * 3;
            }
            break;
          case PLATE_DK_BATOZ_HXY_HXY_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQtyShapeSensitivity(FESystemElem::N_Y_N_Y_FACTOR::num(),
                                                       &matrix, domain, BATOZ);
              row = 0;
              column = 0;
            }
            break;
          case PLATE_DK_BATOZ_HXX_HYY_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQtyShapeSensitivity(FESystemElem::N_X_N_Y_FACTOR::num(),
                                                       &matrix, domain, BATOZ);
              row = 0;
              column = n_nodes * 3;
            }
            break;
          case PLATE_DK_BATOZ_HYX_HXY_FACTOR_ENUM_ID:
            {
              elem->getFESystemElemQtyShapeSensitivity(FESystemElem::N_X_N_Y_FACTOR::num(),
                                                       &matrix, domain, BATOZ);
              row = n_nodes * 3;
              column = 0;
            }
            break;
          default:
            Assert(false, FESystemExceptions::ExcEnumCaseNotImplemented
                   (FESystemElem::PlateDKBatozQtyEnum::enumName(name)));
          }
      }
    }
  // next, copy the data to the matrix
  for (unsigned int i=0; i < n_nodes * 3; i++)
    for (unsigned int j = 0; j < n_nodes * 3; j++)
      (*qty)(i,j) = matrix(row + i, column + j);
}