fesystem: Loads Namespace Reference
Loads Namespace Reference
Classes
class FlightCondition
class LoadCombinationBase
class NodalLoadCombination
class NodalPointLoadCombination
class SurfaceLoadCombination
class ScalarSurfaceLoadCombination
class SurfaceConvectionLoadCombination
class SurfaceRadiationLoadCombination
class VolumeLoadCombination
class ScalarVolumeLoadCombination
class DirichletBoundaryConditionCombination
class LoadDataInfoBase
class ElemLoadDataInfo
class VolumeLoadDataInfo
class SurfaceLoadDataInfo
class NodalLoadDataInfo
class DirichletBoundaryConditionDataInfo
Enumerations
enum LoadDataInfoScope { SINGLE, ALL, INVALID_SCOPE }
Functions
std::auto_ptr
< Loads::VolumeLoadCombination > createVolumeLoadCombination (const unsigned int load_type_enum_ID)
std::auto_ptr
< Loads::NodalLoadCombination > createNodalLoadCombination (const unsigned int load_type_enum_ID)
std::auto_ptr
< Loads::DirichletBoundaryConditionCombination > createDirichletBoundaryConditionCombination (const unsigned int load_type_enum_ID)
std::auto_ptr
< Loads::SurfaceLoadCombination > createSurfaceLoadCombination (const unsigned int load_type_enum_ID)
std::auto_ptr
< Loads::VolumeLoadDataInfo > createVolumeLoadDataInfo (const unsigned int load_type_enum_ID)
std::auto_ptr
< Loads::NodalLoadDataInfo > createNodalLoadDataInfo (const unsigned int load_type_enum_ID)
std::auto_ptr
< Loads::SurfaceLoadDataInfo > createSurfaceLoadDataInfo (const unsigned int load_type_enum_ID)
Enumeration Type Documentation
enum Loads::LoadDataInfoScope
Enumerator:
SINGLE
ALL
INVALID_SCOPE
Definition at line 16 of file LoadDataInfo.h.
    {
      SINGLE,
      ALL,
      INVALID_SCOPE
    };
Function Documentation
std::auto_ptr< Loads::DirichletBoundaryConditionCombination > Loads::createDirichletBoundaryConditionCombination (const unsigned int load_type_enum_ID)
Definition at line 49 of file LoadCombination.C.
References DIRICHLET_BOUNDARY_CONDITION_ENUM_ID.
Referenced by LoadDatabase::getAllLoadCombinations< Loads::DirichletBoundaryConditionDataInfo, Loads::DirichletBoundaryConditionCombination >().
{
  std::auto_ptr<Loads::DirichletBoundaryConditionCombination> return_ptr;
  switch (load_type_enum_ID)
    {
    case DIRICHLET_BOUNDARY_CONDITION_ENUM_ID:
      return_ptr.reset(new Loads::DirichletBoundaryConditionCombination);
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return return_ptr;
}
std::auto_ptr< Loads::NodalLoadCombination > Loads::createNodalLoadCombination (const unsigned int load_type_enum_ID)
Definition at line 29 of file LoadCombination.C.
References NODAL_POINT_LOAD_ENUM_ID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads(), and LoadDatabase::getAllLoadCombinations< Loads::NodalLoadDataInfo, Loads::NodalLoadCombination >().
{
  std::auto_ptr<Loads::NodalLoadCombination> return_ptr;
  switch (load_type_enum_ID)
    {
    case NODAL_POINT_LOAD_ENUM_ID:
      return_ptr.reset(new Loads::NodalPointLoadCombination);
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return return_ptr;
}
std::auto_ptr< Loads::NodalLoadDataInfo > Loads::createNodalLoadDataInfo (const unsigned int load_type_enum_ID)
Definition at line 411 of file LoadDataInfo.C.
Referenced by DirectInterpolation::createLoads(), and Discipline::AnalysisDisciplineBase::getElemLoads().
{
  std::auto_ptr<Loads::NodalLoadDataInfo> return_ptr(new Loads::NodalLoadDataInfo);
  return_ptr->setLoadClassEnumID(load_type_enum_ID);
  return return_ptr;
}
std::auto_ptr< Loads::SurfaceLoadCombination > Loads::createSurfaceLoadCombination (const unsigned int load_type_enum_ID)
Definition at line 68 of file LoadCombination.C.
References SCALAR_SURFACE_LOAD_ENUM_ID, SURFACE_CONVECTION_LOAD_ENUM_ID, and SURFACE_RADIATION_LOAD_ENUM_ID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads().
{
  std::auto_ptr<Loads::SurfaceLoadCombination> return_ptr;
  switch (load_type_enum_ID)
    {
    case SCALAR_SURFACE_LOAD_ENUM_ID:
      return_ptr.reset(new Loads::ScalarSurfaceLoadCombination);
      break;
    case SURFACE_CONVECTION_LOAD_ENUM_ID:
      return_ptr.reset(new Loads::SurfaceConvectionLoadCombination);
      break;
    case SURFACE_RADIATION_LOAD_ENUM_ID:
      return_ptr.reset(new Loads::SurfaceRadiationLoadCombination);
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return return_ptr;
}
std::auto_ptr< Loads::SurfaceLoadDataInfo > Loads::createSurfaceLoadDataInfo (const unsigned int load_type_enum_ID)
Definition at line 420 of file LoadDataInfo.C.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads().
{
  std::auto_ptr<Loads::SurfaceLoadDataInfo> return_ptr(new Loads::SurfaceLoadDataInfo);
  return_ptr->setLoadClassEnumID(load_type_enum_ID);
  return return_ptr;
}
std::auto_ptr< Loads::VolumeLoadCombination > Loads::createVolumeLoadCombination (const unsigned int load_type_enum_ID)
Definition at line 10 of file LoadCombination.C.
References SCALAR_VOLUME_LOAD_ENUM_ID.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads().
{
  std::auto_ptr<Loads::VolumeLoadCombination> return_ptr;
  switch (load_type_enum_ID)
    {
    case SCALAR_VOLUME_LOAD_ENUM_ID:
      return_ptr.reset(new Loads::ScalarVolumeLoadCombination);
      break;
    default:
      Assert(false, ExcInternalError());
    }
  return return_ptr;
}
std::auto_ptr< Loads::VolumeLoadDataInfo > Loads::createVolumeLoadDataInfo (const unsigned int load_type_enum_ID)
Definition at line 402 of file LoadDataInfo.C.
Referenced by Discipline::AnalysisDisciplineBase::getElemLoads().
{
  std::auto_ptr<Loads::VolumeLoadDataInfo> return_ptr(new Loads::VolumeLoadDataInfo);
  return_ptr->setLoadClassEnumID(load_type_enum_ID);
  return return_ptr;
}