fesystem: Solver Namespace Reference
Solver Namespace Reference
Namespaces
namespace EulerSolver
namespace NewmarkSolver
Classes
class ArpackEigenSolver
class EigenSolverBase
class EigenSolverInfo
class EulerLinearTransientSolver
class EulerNonlinearTransientSolver
class EulerLinearTransientSolverInfo
this is a class specifically for linear transient solvers
class EulerNonlinearTransientSolverInfo
this is a class specifically for linear transient solvers
class FESystemSolverBase
class LinearSolver
class LinearSolverInfo
class NewmarkLinearTransientSolver
class NewmarkNonlinearTransientSolver
class NewmarkLinearTransientSolverInfo
this is a class specifically for linear transient solvers
class NewmarkNonlinearTransientSolverInfo
this is a class specifically for linear transient solvers
class NewtonNonlinearSolver
class NonlinearSolver
class NonlinearSolverInfo
this class stores the information for initialization of a nonlinear solver.
class PetscLinearSolver
class PetscNonlinearSolver
class PetscNonlinearTransientSolver
class SlepcEigenSolver
class SolverInfo
class TransientSolverBase
class LinearTransientSolverBase
class NonlinearTransientSolverBase
class TransientSolverInfoBase
class LinearTransientSolverInfo
this is a class specifically for linear transient solvers
class NonlinearTransientSolverInfo
this is a class specifically for linear transient solvers
Functions
DeclareEnumName (ARPACK_EIGEN_SOLVER, Solver::EigenSolverKindEnum, 7,"ARPACK_EIGEN_SOLVER")
DeclareEnumName (EIGEN_SOLVER, Solver::SolverClassEnum, 3,"EIGEN_SOLVER")
DeclareEnumClass (EigenProblemKindEnum)
DeclareEnumName (HERMITIAN_EIGENPROBLEM, Solver::EigenProblemKindEnum, 1,"HERMITIAN_EIGENPROBLEM")
DeclareEnumName (GENERALIZED_HERMITIAN_EIGENPROBLEM, Solver::EigenProblemKindEnum, 2,"GENERALIZED_HERMITIAN_EIGENPROBLEM")
DeclareEnumName (NON_HERMITIAN_EIGENPROBLEM, Solver::EigenProblemKindEnum, 3,"NON_HERMITIAN_EIGENPROBLEM")
DeclareEnumName (GENERALIZED_NON_HERMITIAN_EIGENPROBLEM, Solver::EigenProblemKindEnum, 4,"GENERALIZED_NON_HERMITIAN_EIGENPROBLEM")
DeclareEnumClass (EigenSolutionSpectrumKindEnum)
DeclareEnumName (LARGEST_MAGNITUDE, Solver::EigenSolutionSpectrumKindEnum, 1,"LARGEST_MAGNITUDE")
DeclareEnumName (SMALLEST_MAGNITUDE, Solver::EigenSolutionSpectrumKindEnum, 2,"SMALLEST_MAGNITUDE")
DeclareEnumName (LARGEST_REAL, Solver::EigenSolutionSpectrumKindEnum, 3,"LARGEST_REAL")
DeclareEnumName (SMALLEST_REAL, Solver::EigenSolutionSpectrumKindEnum, 4,"SMALLEST_REAL")
DeclareEnumName (LARGEST_IMAGINARY, Solver::EigenSolutionSpectrumKindEnum, 5,"LARGEST_IMAGINARY")
DeclareEnumName (SMALLEST_IMAGINARY, Solver::EigenSolutionSpectrumKindEnum, 6,"SMALLEST_IMAGINARY")
DeclareEnumClass (EigenSolutionShiftKindEnum)
DeclareEnumName (NO_SHIFT, Solver::EigenSolutionShiftKindEnum, 1,"NO_SHIFT")
DeclareEnumName (ORIGIN_SHIFT, Solver::EigenSolutionShiftKindEnum, 2,"ORIGIN_SHIFT")
DeclareEnumName (SPECTRUM_FOLD, Solver::EigenSolutionShiftKindEnum, 3,"SPECTRUM_FOLD")
DeclareEnumName (SHIFT_AND_INVERT, Solver::EigenSolutionShiftKindEnum, 4,"SHIFT_AND_INVERT")
DeclareEnumName (CAYLEY_SHIFT, Solver::EigenSolutionShiftKindEnum, 5,"CAYLEY_SHIFT")
DeclareEnumClass (EigenSolverKindEnum)
DeclareEnumName (EIGEN_SOLVER_INFO, Solver::SolverInfoEnum, 3,"EIGEN_SOLVER_INFO")
DeclareEnumName (EULER_LINEAR_TRANSIENT_SOLVER, Solver::TransientSolverKindEnum, 7,"EULER_LINEAR_TRANSIENT_SOLVER")
DeclareEnumName (EULER_NONLINEAR_TRANSIENT_SOLVER, Solver::TransientSolverKindEnum, 8,"EULER_NONLINEAR_TRANSIENT_SOLVER")
DeclareEnumName (EULER_LINEAR_TRANSIENT_SOLVER_INFO, Solver::SolverInfoEnum, 8,"EULER_LINEAR_TRANSIENT_SOLVER_INFO")
DeclareEnumName (EULER_NONLINEAR_TRANSIENT_SOLVER_INFO, Solver::SolverInfoEnum, 9,"EULER_NONLINEAR_TRANSIENT_SOLVER_INFO")
DeclareEnumClass (SolverClassEnum)
std::auto_ptr
< Solver::LinearSolver > createLinearSolver (const Solver::LinearSolverInfo &info)
std::auto_ptr
< Solver::NonlinearSolver > createNonlinearSolver (const Solver::NonlinearSolverInfo &info, const Solver::LinearSolverInfo &linear_info)
std::auto_ptr
< Solver::EigenSolverBase > createEigenSolver (const Solver::EigenSolverInfo &eigen_info, const Solver::LinearSolverInfo &linear_info)
std::auto_ptr
< Solver::LinearTransientSolverBase > createLinearTransientSolver (const Solver::LinearTransientSolverInfo &transient_info, const Solver::LinearSolverInfo &linear_info)
std::auto_ptr
< Solver::NonlinearTransientSolverBase > createNonlinearTransientSolver (const Solver::NonlinearTransientSolverInfo &transient_info, const Solver::NonlinearSolverInfo &nonlinear_info, const Solver::LinearSolverInfo &linear_info)
DeclareEnumName (LINEAR_SOLVER, Solver::SolverClassEnum, 1,"LINEAR_SOLVER")
DeclareEnumClass (LinearSolverKindEnum)
DeclareEnumClass (PCTypeEnum)
DeclareEnumName (PC_LU, Solver::PCTypeEnum, 1,"PC_LU")
DeclareEnumName (PC_JACOBI, Solver::PCTypeEnum, 2,"PC_JACOBI")
DeclareEnumName (PC_BJACOBI, Solver::PCTypeEnum, 3,"PC_BJACOBI")
DeclareEnumName (PC_SOR, Solver::PCTypeEnum, 4,"PC_SOR")
DeclareEnumName (PC_EISENSTAT, Solver::PCTypeEnum, 5,"PC_EISENSTAT")
DeclareEnumName (PC_ICC, Solver::PCTypeEnum, 6,"PC_ICC")
DeclareEnumName (PC_ILU, Solver::PCTypeEnum, 7,"PC_ILU")
DeclareEnumName (PC_ASM, Solver::PCTypeEnum, 8,"PC_ASM")
DeclareEnumName (PC_KSP, Solver::PCTypeEnum, 9,"PC_KSP")
DeclareEnumName (PC_CHOLESKY, Solver::PCTypeEnum, 10,"PC_CHOLESKY")
DeclareEnumName (PC_NONE, Solver::PCTypeEnum, 11,"PC_NONE")
DeclareEnumClass (KSPTypeEnum)
DeclareEnumName (KSP_RICHARDSON, Solver::KSPTypeEnum, 1,"KSP_RICHARDSON")
DeclareEnumName (KSP_CHEBYCHEV, Solver::KSPTypeEnum, 2,"KSP_CHEBYCHEV")
DeclareEnumName (KSP_CG, Solver::KSPTypeEnum, 3,"KSP_CG")
DeclareEnumName (KSP_GMRES, Solver::KSPTypeEnum, 4,"KSP_GMRES")
DeclareEnumName (KSP_TCQMR, Solver::KSPTypeEnum, 5,"KSP_TCQMR")
DeclareEnumName (KSP_BCG, Solver::KSPTypeEnum, 6,"KSP_BCGS")
DeclareEnumName (KSP_CGS, Solver::KSPTypeEnum, 7,"KSP_CGS")
DeclareEnumName (KSP_TFQMR, Solver::KSPTypeEnum, 8,"KSP_TFQMR")
DeclareEnumName (KSP_CR, Solver::KSPTypeEnum, 9,"KSP_CR")
DeclareEnumName (KSP_LSQR, Solver::KSPTypeEnum, 10,"KSP_LSQR")
DeclareEnumName (KSP_BICG, Solver::KSPTypeEnum, 11,"KSP_BICG")
DeclareEnumName (KSP_PRE_ONLY, Solver::KSPTypeEnum, 12,"KSP_PRE_ONLY")
DeclareEnumName (LINEAR_SOLVER_INFO, Solver::SolverInfoEnum, 1,"LINEAR_SOLVER_INFO")
DeclareEnumName (NEWMARK_LINEAR_TRANSIENT_SOLVER, Solver::TransientSolverKindEnum, 5,"NEWMARK_LINEAR_TRANSIENT_SOLVER")
DeclareEnumName (NEWMARK_NONLINEAR_TRANSIENT_SOLVER, Solver::TransientSolverKindEnum, 6,"NEWMARK_NONLINEAR_TRANSIENT_SOLVER")
DeclareEnumName (NEWMARK_LINEAR_TRANSIENT_SOLVER_INFO, Solver::SolverInfoEnum, 6,"NEWMARK_LINEAR_TRANSIENT_SOLVER_INFO")
DeclareEnumName (NEWMARK_NONLINEAR_TRANSIENT_SOLVER_INFO, Solver::SolverInfoEnum, 7,"NEWMARK_NONLINEAR_TRANSIENT_SOLVER_INFO")
DeclareEnumName (FESYSTEM_NEWTON_NONLINEAR_SOLVER, Solver::NonlinearSolverKindEnum, 1,"FESYSTEM_NEWTON_NONLINEAR_SOLVER")
DeclareEnumClass (NonlinearSolverKindEnum)
DeclareEnumName (NONLINEAR_SOLVER, Solver::SolverClassEnum, 2,"NONLINEAR_SOLVER")
DeclareEnumName (NONLINEAR_SOLVER_INFO, SolverInfoEnum, 2,"NONLINEAR_SOLVER_INFO")
DeclareEnumName (PETSC_LINEAR_SOLVER, LinearSolverKindEnum, 1,"PETSC_LINEAR_SOLVER")
DeclareEnumName (NEWTON_NONLINEAR_SOLVER_CUBIC_LINE_SEARCH, Solver::NonlinearSolverKindEnum, 2,"NEWTON_NONLINEAR_SOLVER_CUBIC_LINE_SEARCH")
DeclareEnumName (NEWTON_NONLINEAR_SOLVER_QUADRATIC_LINE_SEARCH, Solver::NonlinearSolverKindEnum, 3,"NEWTON_NONLINEAR_SOLVER_QUADRATIC_LINE_SEARCH")
DeclareEnumName (NEWTON_NONLINEAR_SOLVER_NO_LINE_SEARCH, Solver::NonlinearSolverKindEnum, 4,"NEWTON_NONLINEAR_SOLVER_NO_LINE_SEARCH")
DeclareEnumName (NEWTON_NONLINEAR_SOLVER_NO_NORMS_LINE_SEARCH, Solver::NonlinearSolverKindEnum, 5,"NEWTON_NONLINEAR_SOLVER_NO_NORMS_LINE_SEARCH")
DeclareEnumName (PETSC_BEULER_TRANSIENT_SOLVER, Solver::TransientSolverKindEnum, 1,"PETSC_BEULER_TRANSIENT_SOLVER")
DeclareEnumName (PETSC_FEULER_TRANSIENT_SOLVER, Solver::TransientSolverKindEnum, 2,"PETSC_FEULER_TRANSIENT_SOLVER")
DeclareEnumName (PETSC_RUNGE_KUTTA_TRANSIENT_SOLVER, Solver::TransientSolverKindEnum, 3,"PETSC_RUNGE_KUTTA_TRANSIENT_SOLVER")
DeclareEnumName (PETSC_CRANK_NICHOLSON_TRANSIENT_SOLVER, Solver::TransientSolverKindEnum, 4,"PETSC_CRANK_NICHOLSON_TRANSIENT_SOLVER")
DeclareEnumName (EPS_LAPACK_EIGEN_SOLVER, Solver::EigenSolverKindEnum, 1,"EPS_LAPACK_EIGEN_SOLVER")
DeclareEnumName (EPS_POWER_EIGEN_SOLVER, Solver::EigenSolverKindEnum, 2,"EPS_POWER_EIGEN_SOLVER")
DeclareEnumName (EPS_SUBSPACE_EIGEN_SOLVER, Solver::EigenSolverKindEnum, 3,"EPS_SUBSPACE_EIGEN_SOLVER")
DeclareEnumName (EPS_ARNOLDI_EIGEN_SOLVER, Solver::EigenSolverKindEnum, 4,"EPS_ARNOLDI_EIGEN_SOLVER")
DeclareEnumName (EPS_LANCZOS_EIGEN_SOLVER, Solver::EigenSolverKindEnum, 5,"EPS_LANCZOS_EIGEN_SOLVER")
DeclareEnumName (EPS_KRYLOV_SCHUR_EIGEN_SOLVER, Solver::EigenSolverKindEnum, 6,"EPS_KRYLOV_SCHUR_EIGEN_SOLVER")
DeclareEnumClass (SolverInfoEnum)
std::auto_ptr< Solver::SolverInfo > createSolverInfo (const unsigned int enum_ID)
DeclareEnumName (LINEAR_TRANSIENT_SOLVER, Solver::SolverClassEnum, 4,"LINEAR_TRANSIENT_SOLVER")
DeclareEnumName (NONLINEAR_TRANSIENT_SOLVER, Solver::SolverClassEnum, 5,"NONLINEAR_TRANSIENT_SOLVER")
DeclareEnumClass (TransientSolverKindEnum)
DeclareEnumName (LINEAR_TRANSIENT_SOLVER_INFO, Solver::SolverInfoEnum, 4,"LINEAR_TRANSIENT_SOLVER_INFO")
DeclareEnumName (NONLINEAR_TRANSIENT_SOLVER_INFO, Solver::SolverInfoEnum, 5,"NONLINEAR_TRANSIENT_SOLVER_INFO")
Detailed Description
this class provides an interface to a solver for the solution of a linear system of equations. This inherits from the FESystemSolverBase class. It takes a pointer to the analysis driver object that owns an instantiation of this class
Function Documentation
std::auto_ptr< Solver::EigenSolverBase > Solver::createEigenSolver (const Solver::EigenSolverInfo & eigen_info, const Solver::LinearSolverInfo & linear_info)
Definition at line 128 of file FESystemSolverBase.C.
References ARPACK_EIGEN_SOLVER_ENUM_ID, EPS_ARNOLDI_EIGEN_SOLVER_ENUM_ID, EPS_KRYLOV_SCHUR_EIGEN_SOLVER_ENUM_ID, EPS_LANCZOS_EIGEN_SOLVER_ENUM_ID, EPS_LAPACK_EIGEN_SOLVER_ENUM_ID, EPS_POWER_EIGEN_SOLVER_ENUM_ID, EPS_SUBSPACE_EIGEN_SOLVER_ENUM_ID, and Solver::EigenSolverInfo::getEigenSolverKindEnumID().
Referenced by Solution::AeroelasticitySolution::aeroelasticSolve(), and Solution::SolutionBase::eigenSolve().
{
  std::auto_ptr<Solver::EigenSolverBase> solver_ptr(NULL);
  unsigned int eigen_solver_type = eigen_info.getEigenSolverKindEnumID();
  switch(eigen_solver_type)
    {
    case EPS_LAPACK_EIGEN_SOLVER_ENUM_ID:
    case EPS_POWER_EIGEN_SOLVER_ENUM_ID:
    case EPS_SUBSPACE_EIGEN_SOLVER_ENUM_ID:
    case EPS_ARNOLDI_EIGEN_SOLVER_ENUM_ID:
    case EPS_LANCZOS_EIGEN_SOLVER_ENUM_ID:
    case EPS_KRYLOV_SCHUR_EIGEN_SOLVER_ENUM_ID:
      {
        solver_ptr.reset(new Solver::SlepcEigenSolver(eigen_info, linear_info));
      }
      break;
    case ARPACK_EIGEN_SOLVER_ENUM_ID:
      {
        solver_ptr.reset(new Solver::ArpackEigenSolver(eigen_info, linear_info));
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (Solver::EigenSolverKindEnum::enumName(eigen_solver_type)));
    };
  return solver_ptr;
}
std::auto_ptr< Solver::LinearSolver > Solver::createLinearSolver (const Solver::LinearSolverInfo & info)
Definition at line 71 of file FESystemSolverBase.C.
References Solver::LinearSolverInfo::getLinearSolverEnumID(), and PETSC_LINEAR_SOLVER_ENUM_ID.
Referenced by Solution::AeroelasticitySolution::aeroelasticSolve(), Solution::SolutionBase::eigenSolve(), Solver::ArpackEigenSolver::initLinearSolver(), Solution::SolutionBase::linearSolve(), Solver::NewtonNonlinearSolver::NewtonNonlinearSolver(), Solution::SolutionBase::nonlinearSolve(), Solver::EulerLinearTransientSolver::solve(), Solver::NewmarkLinearTransientSolver::solve(), and Solver::NewmarkNonlinearTransientSolver::solve().
{
  std::auto_ptr<Solver::LinearSolver> solver_ptr(NULL);
  unsigned int solver_enum_ID = info.getLinearSolverEnumID();
  switch(solver_enum_ID)
    {
    case PETSC_LINEAR_SOLVER_ENUM_ID:
      {
        solver_ptr.reset(new Solver::PetscLinearSolver(info));
      }
      break;
    default:
      Assert(false, ExcInternalError());
    };
  return solver_ptr;
}
std::auto_ptr< Solver::LinearTransientSolverBase > Solver::createLinearTransientSolver (const Solver::LinearTransientSolverInfo & transient_info, const Solver::LinearSolverInfo & linear_info)
Definition at line 164 of file FESystemSolverBase.C.
References EULER_LINEAR_TRANSIENT_SOLVER_ENUM_ID, Solver::TransientSolverInfoBase::getTransientSolverKindEnumID(), and NEWMARK_LINEAR_TRANSIENT_SOLVER_ENUM_ID.
Referenced by Solution::SolutionBase::linearTransientSolve(), and Solution::SolutionBase::nonlinearTransientSolve().
{
  std::auto_ptr<Solver::LinearTransientSolverBase> solver_ptr(NULL);
  switch (transient_info.getTransientSolverKindEnumID())
    {
    case NEWMARK_LINEAR_TRANSIENT_SOLVER_ENUM_ID:
      {
        solver_ptr.reset(new Solver::NewmarkLinearTransientSolver(transient_info, linear_info));
      }
      break;
      case EULER_LINEAR_TRANSIENT_SOLVER_ENUM_ID:
      {
        solver_ptr.reset(new Solver::EulerLinearTransientSolver(transient_info, linear_info));
      }
        break;
      default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (Solver::TransientSolverKindEnum::enumName
              (transient_info.getTransientSolverKindEnumID())));
    };
  return solver_ptr;
}
std::auto_ptr< Solver::NonlinearSolver > Solver::createNonlinearSolver (const Solver::NonlinearSolverInfo & info, const Solver::LinearSolverInfo & linear_info)
Definition at line 94 of file FESystemSolverBase.C.
References FESYSTEM_NEWTON_NONLINEAR_SOLVER_ENUM_ID, Solver::NonlinearSolverInfo::getNonlinearSolverKindEnumID(), NEWTON_NONLINEAR_SOLVER_CUBIC_LINE_SEARCH_ENUM_ID, NEWTON_NONLINEAR_SOLVER_NO_LINE_SEARCH_ENUM_ID, NEWTON_NONLINEAR_SOLVER_NO_NORMS_LINE_SEARCH_ENUM_ID, and NEWTON_NONLINEAR_SOLVER_QUADRATIC_LINE_SEARCH_ENUM_ID.
Referenced by Solution::SolutionBase::nonlinearSolve(), and Solver::NewmarkNonlinearTransientSolver::solve().
{
  std::auto_ptr<Solver::NonlinearSolver> solver_ptr(NULL);
  unsigned int nonlinear_solver_type = info.getNonlinearSolverKindEnumID();
  switch(nonlinear_solver_type)
    {
    case FESYSTEM_NEWTON_NONLINEAR_SOLVER_ENUM_ID:
      {
        solver_ptr.reset(new Solver::NewtonNonlinearSolver(info, linear_info));
      }
      break;
    case NEWTON_NONLINEAR_SOLVER_CUBIC_LINE_SEARCH_ENUM_ID:
    case NEWTON_NONLINEAR_SOLVER_QUADRATIC_LINE_SEARCH_ENUM_ID:
    case NEWTON_NONLINEAR_SOLVER_NO_LINE_SEARCH_ENUM_ID:
    case NEWTON_NONLINEAR_SOLVER_NO_NORMS_LINE_SEARCH_ENUM_ID:
      {
        solver_ptr.reset(new Solver::PetscNonlinearSolver(info, linear_info));
      }
      break;
    default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (Solver::NonlinearSolverKindEnum::enumName(nonlinear_solver_type)));
    };
  return solver_ptr;
}
std::auto_ptr< Solver::NonlinearTransientSolverBase > Solver::createNonlinearTransientSolver (const Solver::NonlinearTransientSolverInfo & transient_info, const Solver::NonlinearSolverInfo & nonlinear_info, const Solver::LinearSolverInfo & linear_info)
Definition at line 197 of file FESystemSolverBase.C.
References EULER_NONLINEAR_TRANSIENT_SOLVER_ENUM_ID, Solver::TransientSolverInfoBase::getTransientSolverKindEnumID(), and NEWMARK_NONLINEAR_TRANSIENT_SOLVER_ENUM_ID.
Referenced by Solution::SolutionBase::nonlinearTransientSolve().
{
  std::auto_ptr<Solver::NonlinearTransientSolverBase> solver_ptr(NULL);
  switch (transient_info.getTransientSolverKindEnumID())
    {
    case NEWMARK_NONLINEAR_TRANSIENT_SOLVER_ENUM_ID:
      {
        solver_ptr.reset(new Solver::NewmarkNonlinearTransientSolver
                         (transient_info, nonlinear_info, linear_info));
      }
      break;
      case EULER_NONLINEAR_TRANSIENT_SOLVER_ENUM_ID:
      {
        solver_ptr.reset(new Solver::EulerNonlinearTransientSolver
                         (transient_info, nonlinear_info, linear_info));
      }
        break;
      default:
      Assert(false,
             FESystemExceptions::ExcEnumCaseNotImplemented
             (Solver::TransientSolverKindEnum::enumName
              (transient_info.getTransientSolverKindEnumID())));
    };
  return solver_ptr;
}
std::auto_ptr< Solver::SolverInfo > Solver::createSolverInfo (const unsigned int enum_ID)
Returns:
a pointer to a newly created SolverInfo
Definition at line 40 of file SolverInfo.C.
References EIGEN_SOLVER_INFO_ENUM_ID, EULER_LINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID, EULER_NONLINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID, info, LINEAR_SOLVER_INFO_ENUM_ID, LINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID, NEWMARK_LINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID, NEWMARK_NONLINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID, NONLINEAR_SOLVER_INFO_ENUM_ID, and NONLINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID.
Referenced by FESystem::AnalysisCase::readFromInputStream().
{
  std::auto_ptr<Solver::SolverInfo> info(NULL);
  switch (enum_ID)
    {
    case LINEAR_SOLVER_INFO_ENUM_ID:
      info.reset(new Solver::LinearSolverInfo());
      break;
    case NONLINEAR_SOLVER_INFO_ENUM_ID:
      info.reset(new Solver::NonlinearSolverInfo());
      break;
    case EIGEN_SOLVER_INFO_ENUM_ID:
      info.reset(new Solver::EigenSolverInfo());
      break;
    case LINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID:
      info.reset(new Solver::LinearTransientSolverInfo());
      break;
    case NONLINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID:
      info.reset(new Solver::NonlinearTransientSolverInfo());
      break;
    case NEWMARK_LINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID:
      info.reset(new Solver::NewmarkLinearTransientSolverInfo());
      break;
    case NEWMARK_NONLINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID:
      info.reset(new Solver::NewmarkNonlinearTransientSolverInfo());
      break;
      case EULER_LINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID:
        info.reset(new Solver::EulerLinearTransientSolverInfo());
        break;
      case EULER_NONLINEAR_TRANSIENT_SOLVER_INFO_ENUM_ID:
        info.reset(new Solver::EulerNonlinearTransientSolverInfo());
        break;
    default:
      Assert(false, ExcInternalError());
    }
  return info;
}
Solver::DeclareEnumClass (SolverInfoEnum)
Solver::DeclareEnumClass (SolverClassEnum)
Solver::DeclareEnumClass (NonlinearSolverKindEnum)
Solver::DeclareEnumClass (TransientSolverKindEnum)
Solver::DeclareEnumClass (EigenProblemKindEnum)
Solver::DeclareEnumClass (EigenSolutionSpectrumKindEnum)
Solver::DeclareEnumClass (EigenSolutionShiftKindEnum)
Solver::DeclareEnumClass (EigenSolverKindEnum)
Solver::DeclareEnumClass (LinearSolverKindEnum)
Solver::DeclareEnumClass (PCTypeEnum)
Solver::DeclareEnumClass (KSPTypeEnum)
Solver::DeclareEnumName (NONLINEAR_SOLVER_INFO , SolverInfoEnum , 2 , "NONLINEAR_SOLVER_INFO")
Solver::DeclareEnumName (LINEAR_SOLVER_INFO , Solver::SolverInfoEnum , 1 , "LINEAR_SOLVER_INFO")
Solver::DeclareEnumName (EIGEN_SOLVER_INFO , Solver::SolverInfoEnum , 3 , "EIGEN_SOLVER_INFO")
Solver::DeclareEnumName (FESYSTEM_NEWTON_NONLINEAR_SOLVER , Solver::NonlinearSolverKindEnum , 1 , "FESYSTEM_NEWTON_NONLINEAR_SOLVER")
Solver::DeclareEnumName (NONLINEAR_SOLVER , Solver::SolverClassEnum , 2 , "NONLINEAR_SOLVER")
Solver::DeclareEnumName (PETSC_LINEAR_SOLVER , LinearSolverKindEnum , 1 , "PETSC_LINEAR_SOLVER")
Solver::DeclareEnumName (LINEAR_TRANSIENT_SOLVER_INFO , Solver::SolverInfoEnum , 4 , "LINEAR_TRANSIENT_SOLVER_INFO")
Solver::DeclareEnumName (EULER_LINEAR_TRANSIENT_SOLVER_INFO , Solver::SolverInfoEnum , 8 , "EULER_LINEAR_TRANSIENT_SOLVER_INFO")
Solver::DeclareEnumName (NEWMARK_LINEAR_TRANSIENT_SOLVER_INFO , Solver::SolverInfoEnum , 6 , "NEWMARK_LINEAR_TRANSIENT_SOLVER_INFO")
Solver::DeclareEnumName (NONLINEAR_TRANSIENT_SOLVER_INFO , Solver::SolverInfoEnum , 5 , "NONLINEAR_TRANSIENT_SOLVER_INFO")
Solver::DeclareEnumName (NEWMARK_NONLINEAR_TRANSIENT_SOLVER_INFO , Solver::SolverInfoEnum , 7 , "NEWMARK_NONLINEAR_TRANSIENT_SOLVER_INFO")
Solver::DeclareEnumName (EULER_NONLINEAR_TRANSIENT_SOLVER_INFO , Solver::SolverInfoEnum , 9 , "EULER_NONLINEAR_TRANSIENT_SOLVER_INFO")
Solver::DeclareEnumName (LINEAR_TRANSIENT_SOLVER , Solver::SolverClassEnum , 4 , "LINEAR_TRANSIENT_SOLVER")
Solver::DeclareEnumName (NONLINEAR_TRANSIENT_SOLVER , Solver::SolverClassEnum , 5 , "NONLINEAR_TRANSIENT_SOLVER")
Solver::DeclareEnumName (EULER_LINEAR_TRANSIENT_SOLVER , Solver::TransientSolverKindEnum , 7 , "EULER_LINEAR_TRANSIENT_SOLVER")
Solver::DeclareEnumName (NEWMARK_LINEAR_TRANSIENT_SOLVER , Solver::TransientSolverKindEnum , 5 , "NEWMARK_LINEAR_TRANSIENT_SOLVER")
Solver::DeclareEnumName (EULER_NONLINEAR_TRANSIENT_SOLVER , Solver::TransientSolverKindEnum , 8 , "EULER_NONLINEAR_TRANSIENT_SOLVER")
Solver::DeclareEnumName (NEWMARK_NONLINEAR_TRANSIENT_SOLVER , Solver::TransientSolverKindEnum , 6 , "NEWMARK_NONLINEAR_TRANSIENT_SOLVER")
Solver::DeclareEnumName (NEWTON_NONLINEAR_SOLVER_CUBIC_LINE_SEARCH , Solver::NonlinearSolverKindEnum , 2 , "NEWTON_NONLINEAR_SOLVER_CUBIC_LINE_SEARCH")
Solver::DeclareEnumName (PETSC_BEULER_TRANSIENT_SOLVER , Solver::TransientSolverKindEnum , 1 , "PETSC_BEULER_TRANSIENT_SOLVER")
Solver::DeclareEnumName (NEWTON_NONLINEAR_SOLVER_QUADRATIC_LINE_SEARCH , Solver::NonlinearSolverKindEnum , 3 , "NEWTON_NONLINEAR_SOLVER_QUADRATIC_LINE_SEARCH")
Solver::DeclareEnumName (PETSC_FEULER_TRANSIENT_SOLVER , Solver::TransientSolverKindEnum , 2 , "PETSC_FEULER_TRANSIENT_SOLVER")
Solver::DeclareEnumName (NEWTON_NONLINEAR_SOLVER_NO_LINE_SEARCH , Solver::NonlinearSolverKindEnum , 4 , "NEWTON_NONLINEAR_SOLVER_NO_LINE_SEARCH")
Solver::DeclareEnumName (PETSC_RUNGE_KUTTA_TRANSIENT_SOLVER , Solver::TransientSolverKindEnum , 3 , "PETSC_RUNGE_KUTTA_TRANSIENT_SOLVER")
Solver::DeclareEnumName (NEWTON_NONLINEAR_SOLVER_NO_NORMS_LINE_SEARCH , Solver::NonlinearSolverKindEnum , 5 , "NEWTON_NONLINEAR_SOLVER_NO_NORMS_LINE_SEARCH")
Solver::DeclareEnumName (PETSC_CRANK_NICHOLSON_TRANSIENT_SOLVER , Solver::TransientSolverKindEnum , 4 , "PETSC_CRANK_NICHOLSON_TRANSIENT_SOLVER")
Solver::DeclareEnumName (EPS_LAPACK_EIGEN_SOLVER , Solver::EigenSolverKindEnum , 1 , "EPS_LAPACK_EIGEN_SOLVER")
Solver::DeclareEnumName (EPS_POWER_EIGEN_SOLVER , Solver::EigenSolverKindEnum , 2 , "EPS_POWER_EIGEN_SOLVER")
Solver::DeclareEnumName (EPS_SUBSPACE_EIGEN_SOLVER , Solver::EigenSolverKindEnum , 3 , "EPS_SUBSPACE_EIGEN_SOLVER")
Solver::DeclareEnumName (EPS_ARNOLDI_EIGEN_SOLVER , Solver::EigenSolverKindEnum , 4 , "EPS_ARNOLDI_EIGEN_SOLVER")
Solver::DeclareEnumName (EPS_LANCZOS_EIGEN_SOLVER , Solver::EigenSolverKindEnum , 5 , "EPS_LANCZOS_EIGEN_SOLVER")
Solver::DeclareEnumName (EPS_KRYLOV_SCHUR_EIGEN_SOLVER , Solver::EigenSolverKindEnum , 6 , "EPS_KRYLOV_SCHUR_EIGEN_SOLVER")
Solver::DeclareEnumName (EIGEN_SOLVER , Solver::SolverClassEnum , 3 , "EIGEN_SOLVER")
Solver::DeclareEnumName (HERMITIAN_EIGENPROBLEM , Solver::EigenProblemKindEnum , 1 , "HERMITIAN_EIGENPROBLEM")
Solver::DeclareEnumName (GENERALIZED_HERMITIAN_EIGENPROBLEM , Solver::EigenProblemKindEnum , 2 , "GENERALIZED_HERMITIAN_EIGENPROBLEM")
Solver::DeclareEnumName (NON_HERMITIAN_EIGENPROBLEM , Solver::EigenProblemKindEnum , 3 , "NON_HERMITIAN_EIGENPROBLEM")
Solver::DeclareEnumName (GENERALIZED_NON_HERMITIAN_EIGENPROBLEM , Solver::EigenProblemKindEnum , 4 , "GENERALIZED_NON_HERMITIAN_EIGENPROBLEM")
Solver::DeclareEnumName (LARGEST_MAGNITUDE , Solver::EigenSolutionSpectrumKindEnum , 1 , "LARGEST_MAGNITUDE")
Solver::DeclareEnumName (SMALLEST_MAGNITUDE , Solver::EigenSolutionSpectrumKindEnum , 2 , "SMALLEST_MAGNITUDE")
Solver::DeclareEnumName (LARGEST_REAL , Solver::EigenSolutionSpectrumKindEnum , 3 , "LARGEST_REAL")
Solver::DeclareEnumName (SMALLEST_REAL , Solver::EigenSolutionSpectrumKindEnum , 4 , "SMALLEST_REAL")
Solver::DeclareEnumName (LARGEST_IMAGINARY , Solver::EigenSolutionSpectrumKindEnum , 5 , "LARGEST_IMAGINARY")
Solver::DeclareEnumName (SMALLEST_IMAGINARY , Solver::EigenSolutionSpectrumKindEnum , 6 , "SMALLEST_IMAGINARY")
Solver::DeclareEnumName (NO_SHIFT , Solver::EigenSolutionShiftKindEnum , 1 , "NO_SHIFT")
Solver::DeclareEnumName (ORIGIN_SHIFT , Solver::EigenSolutionShiftKindEnum , 2 , "ORIGIN_SHIFT")
Solver::DeclareEnumName (SPECTRUM_FOLD , Solver::EigenSolutionShiftKindEnum , 3 , "SPECTRUM_FOLD")
Solver::DeclareEnumName (SHIFT_AND_INVERT , Solver::EigenSolutionShiftKindEnum , 4 , "SHIFT_AND_INVERT")
Solver::DeclareEnumName (CAYLEY_SHIFT , Solver::EigenSolutionShiftKindEnum , 5 , "CAYLEY_SHIFT")
Solver::DeclareEnumName (LINEAR_SOLVER , Solver::SolverClassEnum , 1 , "LINEAR_SOLVER")
Solver::DeclareEnumName (PC_LU , Solver::PCTypeEnum , 1 , "PC_LU")
Solver::DeclareEnumName (PC_JACOBI , Solver::PCTypeEnum , 2 , "PC_JACOBI")
Solver::DeclareEnumName (PC_BJACOBI , Solver::PCTypeEnum , 3 , "PC_BJACOBI")
Solver::DeclareEnumName (PC_SOR , Solver::PCTypeEnum , 4 , "PC_SOR")
Solver::DeclareEnumName (PC_EISENSTAT , Solver::PCTypeEnum , 5 , "PC_EISENSTAT")
Solver::DeclareEnumName (PC_ICC , Solver::PCTypeEnum , 6 , "PC_ICC")
Solver::DeclareEnumName (PC_ILU , Solver::PCTypeEnum , 7 , "PC_ILU")
Solver::DeclareEnumName (PC_ASM , Solver::PCTypeEnum , 8 , "PC_ASM")
Solver::DeclareEnumName (PC_KSP , Solver::PCTypeEnum , 9 , "PC_KSP")
Solver::DeclareEnumName (PC_CHOLESKY , Solver::PCTypeEnum , 10 , "PC_CHOLESKY")
Solver::DeclareEnumName (PC_NONE , Solver::PCTypeEnum , 11 , "PC_NONE")
Solver::DeclareEnumName (KSP_RICHARDSON , Solver::KSPTypeEnum , 1 , "KSP_RICHARDSON")
Solver::DeclareEnumName (KSP_CHEBYCHEV , Solver::KSPTypeEnum , 2 , "KSP_CHEBYCHEV")
Solver::DeclareEnumName (KSP_CG , Solver::KSPTypeEnum , 3 , "KSP_CG")
Solver::DeclareEnumName (KSP_GMRES , Solver::KSPTypeEnum , 4 , "KSP_GMRES")
Solver::DeclareEnumName (KSP_TCQMR , Solver::KSPTypeEnum , 5 , "KSP_TCQMR")
Solver::DeclareEnumName (KSP_BCG , Solver::KSPTypeEnum , 6 , "KSP_BCGS")
Solver::DeclareEnumName (KSP_CGS , Solver::KSPTypeEnum , 7 , "KSP_CGS")
Solver::DeclareEnumName (KSP_TFQMR , Solver::KSPTypeEnum , 8 , "KSP_TFQMR")
Solver::DeclareEnumName (KSP_CR , Solver::KSPTypeEnum , 9 , "KSP_CR")
Solver::DeclareEnumName (KSP_LSQR , Solver::KSPTypeEnum , 10 , "KSP_LSQR")
Solver::DeclareEnumName (KSP_BICG , Solver::KSPTypeEnum , 11 , "KSP_BICG")
Solver::DeclareEnumName (KSP_PRE_ONLY , Solver::KSPTypeEnum , 12 , "KSP_PRE_ONLY")
Solver::DeclareEnumName (ARPACK_EIGEN_SOLVER , Solver::EigenSolverKindEnum , 7 , "ARPACK_EIGEN_SOLVER")