fesystem: FESystemIOUtility Namespace Reference
FESystemIOUtility Namespace Reference
Functions
std::istream & readFromInput (std::istream &input, const std::string &tag)
makes sure that the input has the specified tag
std::istream & readFromInput (std::istream &input, const std::string &tag, std::string &str)
reads a string from input and stores it in the input parameter.
std::istream & readFromInput (std::istream &input, const std::string &tag, unsigned int &num)
reads an integer from input and stores it in the input parameter
std::istream & readFromInput (std::istream &input, const std::string &tag, double &num)
reads a real from input and stores it in the input parameter
std::istream & readFromInput (std::istream &input, const std::string &tag, bool &val)
reads a bool from input and stores it in the input parameter
std::istream & peekFromInput (std::istream &input, std::string &tag)
Function Documentation
std::istream & FESystemIOUtility::peekFromInput (std::istream & input, std::string & tag) [inline]
peeks the next string from the input. The function returns the input stream whose seek pointer is unchanged
Definition at line 168 of file InputOutputUtility.h.
Referenced by DirectInterpolation::createLoads(), LoadDatabase::readFromInputStream(), DesignData::DesignDatabase::readFromInputStream(), Property::PropertyDatabase::readFromInputStream(), FESystem::AnalysisCase::readFromInputStream(), and FunctionDatabase::readFromInputStream().
{
  tag.clear();
  std::streampos pos = input.tellg();
  input >> tag;
  input.seekg(pos);
  return input;
}
std::istream & FESystemIOUtility::readFromInput (std::istream & input, const std::string & tag) [inline]
makes sure that the input has the specified tag
Definition at line 50 of file InputOutputUtility.h.
Referenced by ElemSetList::readFromInputStream(), OutputInfo::readFromInputStream(), RadiationCavity::readFromInputStream(), InterpolationCase::readFromInputStream(), Discipline::StructuralDisciplineInfo::readFromInputStream(), Discipline::ThermalDisciplineInfo::readFromInputStream(), LoadDatabase::readFromInputStream(), Solver::LinearSolverInfo::readFromInputStream(), DesignData::DesignDatabase::readFromInputStream(), DesignData::ShapeParameter::readFromInputStream(), DesignData::PropertyParameter::readFromInputStream(), Discipline::PistonTheoryInfo::readFromInputStream(), Solver::NonlinearSolverInfo::readFromInputStream(), Property::PropertyDatabase::readFromInputStream(), Solver::EulerLinearTransientSolverInfo::readFromInputStream(), Solution::TransientStructuralSolution::readFromInputStream(), Solution::StructuralVibrationEigenSolution::readFromInputStream(), Solution::ThermalSolution::readFromInputStream(), Solution::TransientThermalSolution::readFromInputStream(), Solution::LinearizedBucklingEigenSolution::readFromInputStream(), Solution::LinearStressSolution::readFromInputStream(), MeshDS::MeshList::readFromInputStream(), Solver::NewmarkLinearTransientSolverInfo::readFromInputStream(), FESystem::AnalysisCase::readFromInputStream(), IsotropicElemDataCard::readFromInputStream(), Solution::AeroelasticitySolution::readFromInputStream(), Solution::NonlinearStaticStructuralSolution::readFromInputStream(), Property::PropertyCard< double >::readFromInputStream(), Solver::EigenSolverInfo::readFromInputStream(), FunctionDatabase::readFromInputStream(), MultilinearFunction::readFromInputStream(), Solver::EulerNonlinearTransientSolverInfo::readFromInputStream(), Solver::NewmarkNonlinearTransientSolverInfo::readFromInputStream(), Property::LocalParameter::readFromInputStream(), TimeIndependentLoadCase::readFromInputStream(), Solver::LinearTransientSolverInfo::readFromInputStream(), Property::GlobalParameter::readFromInputStream(), VolumeLoadSet::readFromInputStream(), Solver::NonlinearTransientSolverInfo::readFromInputStream(), TimeDependentLoadCase::readFromInputStream(), SurfaceLoadSet::readFromInputStream(), NodalLoadSet::readFromInputStream(), BoundaryConditionLoadSet::readFromInputStream(), ForcedConvection_1D_ElemDataCard::readFromInputStream(), AeroelasticLoadSet::readFromInputStream(), and Property::PropertyCardBase::readParametersFromInputStream().
{
  static std::string in_tag;
  in_tag.clear();
  // read the input and make sure that it is same as the
  // tag specified in the input
  input >> in_tag;
  Assert(in_tag == tag,
         FESystemExceptions::ExcIOBadTag(in_tag, tag));
  return input;
}
std::istream & FESystemIOUtility::readFromInput (std::istream & input, const std::string & tag, std::string & str) [inline]
reads a string from input and stores it in the input parameter.
Definition at line 69 of file InputOutputUtility.h.
{
  static std::string in_tag;
  in_tag.clear();
  // read the input and make sure that it is same as the
  // tag specified in the input
  input >> in_tag;
  Assert(in_tag == tag,
         FESystemExceptions::ExcIOBadTag(in_tag, tag));
  // now read the next value
  input >> str;
  return input;
}
std::istream & FESystemIOUtility::readFromInput (std::istream & input, const std::string & tag, unsigned int & num) [inline]
reads an integer from input and stores it in the input parameter
Definition at line 92 of file InputOutputUtility.h.
{
  static std::string in_tag;
  in_tag.clear();
  // read the input and make sure that it is same as the
  // tag specified in the input
  input >> in_tag;
  Assert(in_tag == tag,
         FESystemExceptions::ExcIOBadTag(in_tag, tag));
  // now read the next value
  input >> num;
  return input;
}
std::istream & FESystemIOUtility::readFromInput (std::istream & input, const std::string & tag, double & num) [inline]
reads a real from input and stores it in the input parameter
Definition at line 115 of file InputOutputUtility.h.
{
  static std::string in_tag;
  in_tag.clear();
  // read the input and make sure that it is same as the
  // tag specified in the input
  input >> in_tag;
  Assert(in_tag == tag,
         FESystemExceptions::ExcIOBadTag(in_tag, tag));
  // now read the next value
  input >> num;
  return input;
}
std::istream & FESystemIOUtility::readFromInput (std::istream & input, const std::string & tag, bool & val) [inline]
reads a bool from input and stores it in the input parameter
Definition at line 137 of file InputOutputUtility.h.
{
  static std::string in_tag;
  in_tag.clear();
  // read the input and make sure that it is same as the
  // tag specified in the input
  input >> in_tag;
  Assert(in_tag == tag,
         FESystemExceptions::ExcIOBadTag(in_tag, tag));
  // now read the next value
  in_tag.clear();
  input >> in_tag;
  if ((in_tag == "TRUE") || (in_tag == "true") || (in_tag == "True"))
    val = true;
  else if ((in_tag == "FALSE") || (in_tag == "false") || (in_tag == "False"))
    val = false;
  else
    Assert(false,
           FESystemExceptions::ExcIOBadTag(in_tag, "TRUE/FALSE"));
  return input;
}